# 03 — AIA CNN Realistic Class-Imbalance Year-Holdout Sanity Experiment

**Purpose:** stress-test the AIA image CNN under a more realistic imbalanced flare-forecasting setup before moving into the formal literature-style baseline.

This notebook is **not a final publication result**. It is an engineering/scientific sanity experiment.

**Design**

- Dataset: baseline AIA 2010–2016 manifest
- Train years: 2010–2013
- Validation year: 2014
- Input: six-channel AIA tensor, originally `512 × 512 × 6`
- Model input resolution: resized to `224 × 224`
- Label: `label_48h_final`
- Important: ignore embedded NPZ `y`; use repaired manifest label only
- Class handling: class-weighted BCE loss using `pos_weight`
- Metrics: ROC-AUC, PR-AUC, precision, recall, specificity, F1, TSS, HSS
- Thresholds: report both fixed `0.5` and validation best-TSS threshold

In [1]:
from pathlib import Path
import hashlib
import json
import subprocess
import random
import time
from copy import deepcopy

import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F
from torch import nn
from torch.utils.data import Dataset, DataLoader

from sklearn.metrics import roc_auc_score, average_precision_score

SEED = 42

ROOT = Path.home() / "solar_flare_aia"
MANIFEST = ROOT / "training/final_metadata/baseline_2010_2016_AR_SPECIFIC_manifest.csv"

CACHE_DIR = ROOT / "cache/gcs_npz_realistic_imbalance"
METRICS_DIR = ROOT / "results/metrics"
MODELS_DIR = ROOT / "results/models"

CACHE_DIR.mkdir(parents=True, exist_ok=True)
METRICS_DIR.mkdir(parents=True, exist_ok=True)
MODELS_DIR.mkdir(parents=True, exist_ok=True)

EXPERIMENT_NAME = "realistic_imbalance_aia_cnn_year_holdout_10to1"

TRAIN_YEARS = [2010, 2011, 2012, 2013]
VAL_YEARS = [2014]

# Cost-aware realistic-imbalance sanity setting.
# This is more realistic than balanced 1:1, but still smaller than the full 65k/2.4k dataset.
TRAIN_POS = 150
NEG_PER_POS = 10
TRAIN_NEG = TRAIN_POS * NEG_PER_POS

VAL_POS = 75
VAL_NEG = VAL_POS * NEG_PER_POS

IMAGE_SIZE = 224
BATCH_SIZE = 16
EPOCHS = 5
LR = 3e-4
WEIGHT_DECAY = 1e-4
NUM_WORKERS = 0

def seed_everything(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

seed_everything(SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print("VRAM GB:", round(torch.cuda.get_device_properties(0).total_memory / 1024**3, 2))
else:
    print("WARNING: CUDA is not available. Do not run training until GPU is available.")

Device: cuda
GPU: NVIDIA L4
VRAM GB: 22.06

In [2]:
df = pd.read_csv(MANIFEST, low_memory=False)

print("Manifest:", MANIFEST)
print("Rows:", len(df))
print("\nColumns:")
print(df.columns.tolist())

print("\nYear counts:")
print(df["year"].value_counts().sort_index())

print("\nOverall labels:")
print(df["label_48h_final"].value_counts())

print("\nLabels by year:")
display(pd.crosstab(df["year"], df["label_48h_final"]))

print("\nMissing checks:")
print("Missing gcp_path:", df["gcp_path"].isna().sum())
print("Missing sample_id:", df["sample_id"].isna().sum())
print("Missing label_48h_final:", df["label_48h_final"].isna().sum())

Manifest: /home/abmoses2000/solar_flare_aia/training/final_metadata/baseline_2010_2016_AR_SPECIFIC_manifest.csv
Rows: 68010

Columns:
['gcp_path', 'file', 'sample_id', 'T_REC_dt', 'HARPNUM', 'NOAA_AR_clean', 'label_48h_global_old', 'label_48h_ar_specific', 'label_48h_final', 'label_48h', 'y', 'local_path', 'year', 'used_timestamp', 'used_s3_path', 'manifest_label_before_repair']

Year counts:
year
2010     3306
2011    11142
2012    10815
2013    13066
2014    11627
2015    11236
2016     6818
Name: count, dtype: int64

Overall labels:
label_48h_final
0    65612
1     2398
Name: count, dtype: int64

Labels by year:

label_48h_final      0    1
year
2010              3277   29
2011             10738  404
2012             10510  305
2013             12574  492
2014             10998  629
2015             10705  531
2016              6810    8

Missing checks:
Missing gcp_path: 0
Missing sample_id: 0
Missing label_48h_final: 0

In [3]:
def sample_imbalanced_subset(df, years, n_pos, n_neg, seed):
    part = df[df["year"].isin(years)].copy()

    pos_pool = part[part["label_48h_final"] == 1]
    neg_pool = part[part["label_48h_final"] == 0]

    actual_pos = min(n_pos, len(pos_pool))
    actual_neg = min(n_neg, len(neg_pool))

    if actual_pos < n_pos:
        print(f"WARNING: requested {n_pos} positives but only {actual_pos} available for years={years}")
    if actual_neg < n_neg:
        print(f"WARNING: requested {n_neg} negatives but only {actual_neg} available for years={years}")

    pos = pos_pool.sample(actual_pos, random_state=seed)
    neg = neg_pool.sample(actual_neg, random_state=seed)

    out = pd.concat([pos, neg]).sample(frac=1, random_state=seed).reset_index(drop=True)
    return out

train_df = sample_imbalanced_subset(
    df, TRAIN_YEARS, TRAIN_POS, TRAIN_NEG, SEED
)

val_df = sample_imbalanced_subset(
    df, VAL_YEARS, VAL_POS, VAL_NEG, SEED + 1
)

print("Train subset rows:", len(train_df))
print(train_df["label_48h_final"].value_counts())
print("\nTrain years:")
print(pd.crosstab(train_df["year"], train_df["label_48h_final"]))

print("\nValidation subset rows:", len(val_df))
print(val_df["label_48h_final"].value_counts())
print("\nValidation years:")
print(pd.crosstab(val_df["year"], val_df["label_48h_final"]))

train_samples_path = METRICS_DIR / f"{EXPERIMENT_NAME}_train_samples.csv"
val_samples_path = METRICS_DIR / f"{EXPERIMENT_NAME}_val_samples.csv"

train_df.to_csv(train_samples_path, index=False)
val_df.to_csv(val_samples_path, index=False)

print("\nSaved train samples:", train_samples_path)
print("Saved val samples:", val_samples_path)

Train subset rows: 1650
label_48h_final
0    1500
1     150
Name: count, dtype: int64

Train years:
label_48h_final    0   1
year
2010             139   1
2011             445  51
2012             409  31
2013             507  67

Validation subset rows: 825
label_48h_final
0    750
1     75
Name: count, dtype: int64

Validation years:
label_48h_final    0   1
year
2014             750  75

Saved train samples: /home/abmoses2000/solar_flare_aia/results/metrics/realistic_imbalance_aia_cnn_year_holdout_10to1_train_samples.csv
Saved val samples: /home/abmoses2000/solar_flare_aia/results/metrics/realistic_imbalance_aia_cnn_year_holdout_10to1_val_samples.csv

In [4]:
def local_cache_path(gcp_path: str) -> Path:
    safe = hashlib.md5(gcp_path.encode()).hexdigest() + ".npz"
    return CACHE_DIR / safe

def cache_gcs_file(gcp_path: str) -> Path:
    local_path = local_cache_path(gcp_path)
    if not local_path.exists():
        subprocess.run(["gcloud", "storage", "cp", gcp_path, str(local_path)], check=True)
    return local_path

def precache_frame(frame: pd.DataFrame, name: str):
    paths = frame["gcp_path"].tolist()
    total = len(paths)
    start = time.time()

    print(f"Pre-caching {name}: {total} files")
    for i, gcp_path in enumerate(paths, 1):
        local_path = local_cache_path(gcp_path)
        if not local_path.exists():
            print(f"[{name}] downloading {i}/{total}: {gcp_path}")
            cache_gcs_file(gcp_path)

        if i % 100 == 0 or i == total:
            elapsed = time.time() - start
            print(f"[{name}] cached/checked {i}/{total} files | elapsed {elapsed/60:.1f} min")

    print(f"Finished pre-caching {name}")

# Run this cell before training. It may take time the first time, but it prevents downloads during batches.
precache_frame(train_df, "train")
precache_frame(val_df, "val")

Pre-caching train: 1650 files
[train] downloading 1/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130627_1448_HARP2878_NOAA11777.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130627_1448_HARP2878_NOAA11777.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5e90db5191887eaf110ac5ede151dae5.npz

.

Average throughput: 148.2MiB/s

[train] downloading 2/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130111_0248_HARP2362_NOAA11652.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130111_0248_HARP2362_NOAA11652.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/034fdc696633152e249882a1f0148a19.npz

.

Average throughput: 167.6MiB/s

[train] downloading 3/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111224_2348_HARP1221_NOAA11383.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111224_2348_HARP1221_NOAA11383.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/bdd4bf511c33ecb31e7c6dc99ffa7808.npz

.

Average throughput: 63.6MiB/s

[train] downloading 4/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130201_0548_HARP2436_NOAA11668.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130201_0548_HARP2436_NOAA11668.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/69d28964706bb1857861586284bfbe4f.npz

.

Average throughput: 134.4MiB/s

[train] downloading 5/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131108_1024_HARP3341_NOAA11890.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131108_1024_HARP3341_NOAA11890.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5e3d3607ed897dde9cfaffbc0a1dcb7a.npz

.

Average throughput: 97.2MiB/s

[train] downloading 6/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100901_1600_HARP155_NOAA11103.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100901_1600_HARP155_NOAA11103.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e8d0ae5ef8967609abda14f07fed96ca.npz

.

Average throughput: 168.9MiB/s

[train] downloading 7/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110401_1524_HARP451_NOAA11183.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110401_1524_HARP451_NOAA11183.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c2d1cc0130754a1510d69d0ebce4e692.npz

.

Average throughput: 166.6MiB/s

[train] downloading 8/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130312_1712_HARP2533_NOAA11690.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130312_1712_HARP2533_NOAA11690.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ff7a10ed84c737e0fdc625ef884f6064.npz

.

Average throughput: 113.1MiB/s

[train] downloading 9/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110612_0612_HARP661_NOAA11234.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110612_0612_HARP661_NOAA11234.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/25d1c242a5bfdb8ac087a504bc25b524.npz

.

Average throughput: 180.6MiB/s

[train] downloading 10/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130411_1112_HARP2636_NOAA11718.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130411_1112_HARP2636_NOAA11718.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cdd06eb09e544ab354bbeef88ef51412.npz

.

Average throughput: 69.8MiB/s

[train] downloading 11/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131121_0036_HARP3376_NOAA11899.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131121_0036_HARP3376_NOAA11899.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fc6f90f78fbc6d2ce2792e110e7c8245.npz

.

Average throughput: 165.4MiB/s

[train] downloading 12/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110910_0312_HARP843_NOAA11287.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110910_0312_HARP843_NOAA11287.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b8fba73eed640f9d344ea09f7d72cf4c.npz

.

Average throughput: 40.6MiB/s

[train] downloading 13/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111006_1024_HARP913_NOAA11308.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111006_1024_HARP913_NOAA11308.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e86f26ea3e763d13b851625809b576dd.npz

.

Average throughput: 124.5MiB/s

[train] downloading 14/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111121_1424_HARP1080_NOAA11357.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111121_1424_HARP1080_NOAA11357.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9fec7f018817499de1234eea108543fb.npz

.

Average throughput: 141.2MiB/s

[train] downloading 15/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120521_2348_HARP1680_NOAA11487.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120521_2348_HARP1680_NOAA11487.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/abd9d8aafc9880be22804d9ea2e6c655.npz

.

Average throughput: 109.1MiB/s

[train] downloading 16/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130510_0136_HARP2716_NOAA11738.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130510_0136_HARP2716_NOAA11738.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8ed69521eb2450e744b30362234418e5.npz

.

Average throughput: 46.6MiB/s

[train] downloading 17/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111228_1936_HARP1237_NOAA11386.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111228_1936_HARP1237_NOAA11386.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9c878367d42161b647f363ee434791a2.npz

.

Average throughput: 57.7MiB/s

[train] downloading 18/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130803_1400_HARP3022_NOAA11808.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130803_1400_HARP3022_NOAA11808.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/793fadcebd093a02612e4ce0c1e33513.npz

.

Average throughput: 149.6MiB/s

[train] downloading 19/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121002_0724_HARP2069_NOAA11582.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121002_0724_HARP2069_NOAA11582.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6862c7b0d32c2f046115edd2ca64ec2d.npz

.

Average throughput: 101.1MiB/s

[train] downloading 20/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130328_0712_HARP2595_NOAA11706.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130328_0712_HARP2595_NOAA11706.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/368dc4fe8d6bb18308ff91b9e50351c7.npz

.

Average throughput: 102.1MiB/s

[train] downloading 21/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101117_1024_HARP256_NOAA11126.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101117_1024_HARP256_NOAA11126.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/af6032e4440ebeea6a2e8cec16873ba9.npz

.

Average throughput: 164.1MiB/s

[train] downloading 22/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110215_1548_HARP371_NOAA11159.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110215_1548_HARP371_NOAA11159.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e9cef9d7718ec14b8bb9b2ec1e7f5b95.npz

.

Average throughput: 104.7MiB/s

[train] downloading 23/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110515_2136_HARP595_NOAA11212.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110515_2136_HARP595_NOAA11212.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/03f46a6d0825471ad29e6901b1558430.npz

.

Average throughput: 179.3MiB/s

[train] downloading 24/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131112_0536_HARP3353_NOAA11892.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131112_0536_HARP3353_NOAA11892.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/bb4c6df16a4d1ad9aa2111135fc92078.npz

.

Average throughput: 97.7MiB/s

[train] downloading 25/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110408_1112_HARP488_NOAA11188.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110408_1112_HARP488_NOAA11188.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f760dfc884f0590b4e942e93836a18ed.npz

.

Average throughput: 138.7MiB/s

[train] downloading 26/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130728_0812_HARP3011_NOAA11812.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130728_0812_HARP3011_NOAA11812.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e3e955d50bacdcfbfc19e656798f98ca.npz

.

Average throughput: 120.5MiB/s

[train] downloading 27/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110606_0424_HARP639_NOAA11228.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110606_0424_HARP639_NOAA11228.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8af81df422ca24d703c2f1b7967b8c05.npz

.

Average throughput: 97.2MiB/s

[train] downloading 28/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130131_0312_HARP2420_NOAA11663.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130131_0312_HARP2420_NOAA11663.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8bfe9c333eb5ba8537019769111a0f20.npz

.

Average throughput: 150.9MiB/s

[train] downloading 29/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110630_0024_HARP684_NOAA11244.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110630_0024_HARP684_NOAA11244.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c4b797c9e1deade1af86b2eb8085da0b.npz

.

Average throughput: 45.8MiB/s

[train] downloading 30/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110404_2148_HARP466_NOAA11184.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110404_2148_HARP466_NOAA11184.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5bf391109a2d9daa2dc6f7d156500f45.npz

.

Average throughput: 64.5MiB/s

[train] downloading 31/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120603_2248_HARP1715_NOAA11495.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120603_2248_HARP1715_NOAA11495.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/73b8015e73456f62c0eb14ee11c838f5.npz

.

Average throughput: 90.6MiB/s

[train] downloading 32/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130221_2236_HARP2489_NOAA11673.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130221_2236_HARP2489_NOAA11673.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f5450da70d42f986350270bff398a982.npz

.

Average throughput: 69.8MiB/s

[train] downloading 33/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130108_0748_HARP2348_NOAA11651.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130108_0748_HARP2348_NOAA11651.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/57f8b930742cdf8c5a0d707cc1d77041.npz

.

Average throughput: 118.5MiB/s

[train] downloading 34/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110512_1524_HARP580_NOAA11210.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110512_1524_HARP580_NOAA11210.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f933b4343aed8d398789e9d5a7c6fb63.npz

.

Average throughput: 83.8MiB/s

[train] downloading 35/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121016_2300_HARP2114_NOAA11592.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121016_2300_HARP2114_NOAA11592.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e784ad9c7c042cb135a668b03d0efd78.npz

.

Average throughput: 179.7MiB/s

[train] downloading 36/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110201_1836_HARP355_NOAA11150.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110201_1836_HARP355_NOAA11150.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b7d96654fafe47db2e85d9f937a14e4d.npz

.

Average throughput: 92.1MiB/s

[train] downloading 37/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110213_1236_HARP371_NOAA11159.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110213_1236_HARP371_NOAA11159.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3524aa597d992c2f505bf400b3042c6d.npz

.

Average throughput: 123.4MiB/s

[train] downloading 38/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111014_1348_HARP956_NOAA11318.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111014_1348_HARP956_NOAA11318.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3c299af511c0b0f9c4e72928963e2ed9.npz

.

Average throughput: 155.5MiB/s

[train] downloading 39/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120304_2048_HARP1455_NOAA11431.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120304_2048_HARP1455_NOAA11431.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f48f92c0ff8379ada9bf2cced31744d5.npz

.

Average throughput: 185.3MiB/s

[train] downloading 40/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110212_1712_HARP377_NOAA11158.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110212_1712_HARP377_NOAA11158.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/94c2c6201a74cb1ea33ab724dd5f2d9e.npz

.

Average throughput: 201.4MiB/s

[train] downloading 41/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110804_1048_HARP751_NOAA11264.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110804_1048_HARP751_NOAA11264.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/32a17c5a034cb163e70bd7e7c447e0de.npz

.

Average throughput: 101.2MiB/s

[train] downloading 42/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120909_2012_HARP2011_NOAA11566.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120909_2012_HARP2011_NOAA11566.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8bc10b80ab92f1538694e5fcc47e98d4.npz

.

Average throughput: 66.3MiB/s

[train] downloading 43/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111001_1136_HARP902_NOAA11305.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111001_1136_HARP902_NOAA11305.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/30b83162d0469ade27f5fd718eaf2a0a.npz

.

Average throughput: 147.5MiB/s

[train] downloading 44/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120325_1448_HARP1497_NOAA11446.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120325_1448_HARP1497_NOAA11446.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a37927e20f8a33954dc87838c8134654.npz

.

Average throughput: 73.8MiB/s

[train] downloading 45/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110414_1912_HARP495_NOAA11190.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110414_1912_HARP495_NOAA11190.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/948f36e8730590515dc67124cfca0fdb.npz

.

Average throughput: 151.7MiB/s

[train] downloading 46/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130817_0524_HARP3056_NOAA11818.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130817_0524_HARP3056_NOAA11818.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d5517acfe134e8868fd6a06c5060bae2.npz

.

Average throughput: 77.7MiB/s

[train] downloading 47/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130314_0400_HARP2533_NOAA11690.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130314_0400_HARP2533_NOAA11690.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c9bb8d23aafdf382d80e43371f8f4165.npz

.

Average throughput: 160.2MiB/s

[train] downloading 48/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120415_0400_HARP1557_NOAA11454.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120415_0400_HARP1557_NOAA11454.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fb78681dfb5d29dba26eed678c6d27c0.npz

.

Average throughput: 180.9MiB/s

[train] downloading 49/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130522_0124_HARP2748_NOAA11748.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130522_0124_HARP2748_NOAA11748.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/007f6bd5eba0ac2df07ce2e0b8f43ed1.npz

.

Average throughput: 159.1MiB/s

[train] downloading 50/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130715_1636_HARP2976_NOAA11796.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130715_1636_HARP2976_NOAA11796.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d4d318459d283d176942c1dc8a344d3f.npz

.

Average throughput: 117.4MiB/s

[train] downloading 51/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130707_0748_HARP2920_NOAA11785.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130707_0748_HARP2920_NOAA11785.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/790127aab172b8a72e7a75c6a40a8342.npz

...

Average throughput: 180.4MiB/s

[train] downloading 52/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100829_0336_HARP146_NOAA11102.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100829_0336_HARP146_NOAA11102.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/962c6ab68291b9e55a5b4831db489908.npz

...

Average throughput: 91.0MiB/s

[train] downloading 53/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131031_1824_HARP3321_NOAA11884.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131031_1824_HARP3321_NOAA11884.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9742f92a4f1d926bd473ef8ffca89ff0.npz

...

Average throughput: 90.3MiB/s

[train] downloading 54/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120421_1048_HARP1574_NOAA11459.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120421_1048_HARP1574_NOAA11459.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/43b27c37e87c91bf629d1534c71dd7d7.npz

...

Average throughput: 110.2MiB/s

[train] downloading 55/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111209_1236_HARP1126_NOAA11364.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111209_1236_HARP1126_NOAA11364.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/472394b85d7947b16c6f1ecc9cd5b93c.npz

.

Average throughput: 89.4MiB/s

[train] downloading 56/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120214_1048_HARP1390_NOAA11418.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120214_1048_HARP1390_NOAA11418.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c7f692bddf0bc08d5dbf847a9be0f0b2.npz

.

Average throughput: 80.5MiB/s

[train] downloading 57/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111121_2236_HARP1079_NOAA11350.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111121_2236_HARP1079_NOAA11350.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2883bedbbf27f7a2c2221b8523324f58.npz

.

Average throughput: 110.0MiB/s

[train] downloading 58/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130716_1424_HARP2952_NOAA11791.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130716_1424_HARP2952_NOAA11791.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c8307bc909565b4e47be42529f8a6aac.npz

.

Average throughput: 174.6MiB/s

[train] downloading 59/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100620_0524_HARP57_NOAA11082.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100620_0524_HARP57_NOAA11082.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/16df0226e9553a5ad3d90b6b83d222dd.npz

.

Average throughput: 178.6MiB/s

[train] downloading 60/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130531_2312_HARP2812_NOAA11766.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130531_2312_HARP2812_NOAA11766.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/36b00bc309f994daf88246c22c46573a.npz

.

Average throughput: 98.8MiB/s

[train] downloading 61/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111120_1336_HARP1089_NOAA11352.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111120_1336_HARP1089_NOAA11352.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c0b82aeae7aa012b0a7eeb11b7440153.npz

.

Average throughput: 126.7MiB/s

[train] downloading 62/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120420_1124_HARP1574_NOAA11459.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120420_1124_HARP1574_NOAA11459.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e27d2c7e75e385452527376e104df282.npz

.

Average throughput: 180.1MiB/s

[train] downloading 63/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120521_2212_HARP1680_NOAA11487.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120521_2212_HARP1680_NOAA11487.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c4824ec7501df64cf0bac49922f99983.npz

.

Average throughput: 74.3MiB/s

[train] downloading 64/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121016_1812_HARP2121_NOAA11591.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121016_1812_HARP2121_NOAA11591.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/dc6512e3f5f7dcbd8f49c8ba70112a9e.npz

.

Average throughput: 79.6MiB/s

[train] downloading 65/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111108_0500_HARP1026_NOAA11338.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111108_0500_HARP1026_NOAA11338.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/63df182788188cda0a694dd157039c11.npz

.

Average throughput: 94.2MiB/s

[train] downloading 66/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100928_1712_HARP190_NOAA11110.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100928_1712_HARP190_NOAA11110.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/36af20f31a525e861bbec7c8d437db95.npz

.

Average throughput: 72.3MiB/s

[train] downloading 67/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120324_1800_HARP1497_NOAA11446.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120324_1800_HARP1497_NOAA11446.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/da8b5e487609678539221e049dc9ad6e.npz

.

Average throughput: 74.4MiB/s

[train] downloading 68/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110306_2112_HARP401_NOAA11166.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110306_2112_HARP401_NOAA11166.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8b8f04523215b4691d4e10729ee6a5d0.npz

.

Average throughput: 159.1MiB/s

[train] downloading 69/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130808_0912_HARP3049_NOAA11813.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130808_0912_HARP3049_NOAA11813.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f18d4705385a13ea55632bb1eeba0063.npz

.

Average throughput: 116.3MiB/s

[train] downloading 70/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131006_1100_HARP3252_NOAA11862.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131006_1100_HARP3252_NOAA11862.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/06d9a153f0190f8b7c403f94143d2cea.npz

.

Average throughput: 185.3MiB/s

[train] downloading 71/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121124_0500_HARP2220_NOAA11618.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121124_0500_HARP2220_NOAA11618.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9e1594c7339b1d9c2d6aaf422f907fcf.npz

.

Average throughput: 92.3MiB/s

[train] downloading 72/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120617_1100_HARP1756_NOAA11506.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120617_1100_HARP1756_NOAA11506.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/22705d13f0b03c2f873a57a6fcdc1dde.npz

.

Average throughput: 158.7MiB/s

[train] downloading 73/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121118_0836_HARP2203_NOAA11616.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121118_0836_HARP2203_NOAA11616.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cb6e7296c49d0d6f48af000da7664f6a.npz

.

Average throughput: 63.6MiB/s

[train] downloading 74/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130107_1548_HARP2348_NOAA11651.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130107_1548_HARP2348_NOAA11651.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/96ad01ba094d7a64483c29978463bb0c.npz

.

Average throughput: 111.9MiB/s

[train] downloading 75/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130108_1836_HARP2358_NOAA11649.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130108_1836_HARP2358_NOAA11649.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/70fb233a1428949dbb4a2aa2957400bd.npz

.

Average throughput: 166.8MiB/s

[train] downloading 76/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120908_0400_HARP2011_NOAA11566.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120908_0400_HARP2011_NOAA11566.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/22f48548221da27ade9af772ed29a8d8.npz

.

Average throughput: 118.1MiB/s

[train] downloading 77/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131229_1048_HARP3535_NOAA11936.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131229_1048_HARP3535_NOAA11936.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5d255dce1d3b36ea62ce60b0974620a4.npz

.

Average throughput: 140.6MiB/s

[train] downloading 78/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130530_0512_HARP2790_NOAA11758.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130530_0512_HARP2790_NOAA11758.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e8ceedd37f267b08de0901511f543504.npz

.

Average throughput: 80.9MiB/s

[train] downloading 79/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111004_0600_HARP924_NOAA11310.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111004_0600_HARP924_NOAA11310.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0492184a20f0a7c18ad5728e9d62eca6.npz

.

Average throughput: 82.1MiB/s

[train] downloading 80/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130630_1848_HARP2910_NOAA11782.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130630_1848_HARP2910_NOAA11782.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5d8866e280e45132c88794f740c0a3b5.npz

.

Average throughput: 92.8MiB/s

[train] downloading 81/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131023_0624_HARP3291_NOAA11875.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131023_0624_HARP3291_NOAA11875.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4c1c500932bbaa954f2226f94eca89fe.npz

.

Average throughput: 97.7MiB/s

[train] downloading 82/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111206_0936_HARP1165_NOAA11367.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111206_0936_HARP1165_NOAA11367.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/51f2ee768e8da46f539868f2ab407bfe.npz

.

Average throughput: 73.6MiB/s

[train] downloading 83/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130112_2024_HARP2362_NOAA11652.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130112_2024_HARP2362_NOAA11652.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/12e37f36a220b613f12a732b5ea28eed.npz

.

Average throughput: 149.5MiB/s

[train] downloading 84/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121020_2100_HARP2117_NOAA11593.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121020_2100_HARP2117_NOAA11593.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/61230065bd9764b33da8b67177cdd914.npz

.

Average throughput: 130.5MiB/s

[train] downloading 85/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110623_1200_HARP676_NOAA11239.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110623_1200_HARP676_NOAA11239.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4fbcb322e425b12c45705c6d8645614c.npz



Average throughput: 149.2MiB/s

[train] downloading 86/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121006_0936_HARP2098_NOAA11585.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121006_0936_HARP2098_NOAA11585.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f3eea0b312a2990816b182fe9796211f.npz

.

Average throughput: 136.0MiB/s

[train] downloading 87/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121117_0724_HARP2191_NOAA11613.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121117_0724_HARP2191_NOAA11613.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/be7771a11660501533f4e3b6fad067f3.npz

.

Average throughput: 96.5MiB/s

[train] downloading 88/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130402_0400_HARP2610_NOAA11712.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130402_0400_HARP2610_NOAA11712.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/88175780dea8e1d4b29111ec0f230693.npz

.

Average throughput: 108.9MiB/s

[train] downloading 89/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131103_1900_HARP3330_NOAA11887.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131103_1900_HARP3330_NOAA11887.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/138d3ee5f11c8b0f840375804f6cc587.npz

.

Average throughput: 53.5MiB/s

[train] downloading 90/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130104_1836_HARP2342_NOAA11643.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130104_1836_HARP2342_NOAA11643.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/87557de62016c9bbd86c27560023ed25.npz

.

Average throughput: 52.5MiB/s

[train] downloading 91/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111105_1912_HARP1019_NOAA11336.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111105_1912_HARP1019_NOAA11336.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5b7db63d7dde4167a8a1f526ca2fa2fe.npz

.

Average throughput: 158.3MiB/s

[train] downloading 92/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130311_1500_HARP2522_NOAA11689.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130311_1500_HARP2522_NOAA11689.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8151558e505e454afa5d77d47c44d7d0.npz

.

Average throughput: 81.1MiB/s

[train] downloading 93/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130916_1312_HARP3176_NOAA11841.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130916_1312_HARP3176_NOAA11841.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/13f5d2e4c4d62a8deaa5461e8a965496.npz

.

Average throughput: 37.2MiB/s

[train] downloading 94/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111215_1300_HARP1186_NOAA11378.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111215_1300_HARP1186_NOAA11378.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c83d5523801549483552e2e319341cae.npz

.

Average throughput: 70.0MiB/s

[train] downloading 95/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120512_0212_HARP1638_NOAA11476.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120512_0212_HARP1638_NOAA11476.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/01121557748c6961d6c55a5dd40eeb6a.npz

.

Average throughput: 92.1MiB/s

[train] downloading 96/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131021_0800_HARP3291_NOAA11875.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131021_0800_HARP3291_NOAA11875.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/eda603a86d0cfd8d3d61398a961b1c9c.npz

.

Average throughput: 93.0MiB/s

[train] downloading 97/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111102_2000_HARP1021_NOAA11334.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111102_2000_HARP1021_NOAA11334.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b085b7376f64291ef50d61271c7f2154.npz

.

Average throughput: 161.9MiB/s

[train] downloading 98/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120421_0212_HARP1574_NOAA11459.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120421_0212_HARP1574_NOAA11459.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7eeb684c7aaf5a178c956dd5b447e68a.npz

.

Average throughput: 127.6MiB/s

[train] downloading 99/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100926_0348_HARP190_NOAA11110.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100926_0348_HARP190_NOAA11110.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/65ea911e92bf9af7c5e7f79a33597dca.npz

.

Average throughput: 51.1MiB/s

[train] downloading 100/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111116_2000_HARP1066_NOAA11346.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111116_2000_HARP1066_NOAA11346.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/49595ca3a179b0d91a5eed1e0043531b.npz

.

Average throughput: 152.7MiB/s

[train] cached/checked 100/1650 files | elapsed 2.6 min
[train] downloading 101/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111225_0400_HARP1232_NOAA11385.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111225_0400_HARP1232_NOAA11385.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e890b7cf8f99603980903faa9452cc8b.npz

.

Average throughput: 150.3MiB/s

[train] downloading 102/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131003_1824_HARP3240_NOAA11854.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131003_1824_HARP3240_NOAA11854.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f02699c7e84e8f3bdcf48b07d43bd126.npz

.

Average throughput: 74.6MiB/s

[train] downloading 103/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130102_0436_HARP2329_NOAA11639.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130102_0436_HARP2329_NOAA11639.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0163f688d0cb1c1a0b7adc451d3e4aeb.npz

.

Average throughput: 109.1MiB/s

[train] downloading 104/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130506_1348_HARP2711_NOAA11737.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130506_1348_HARP2711_NOAA11737.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9602802acf92ff4a3a4cbac7f3df5e73.npz

.

Average throughput: 77.1MiB/s

[train] downloading 105/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100903_0524_HARP156_NOAA11105.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100903_0524_HARP156_NOAA11105.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/99b1970c9f1791f9dd7bc68f5edbc84e.npz

.

Average throughput: 115.6MiB/s

[train] downloading 106/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130308_0100_HARP2522_NOAA11689.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130308_0100_HARP2522_NOAA11689.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8a7f80234575317c7f0b12b5f3ec2cd7.npz

.

Average throughput: 145.5MiB/s

[train] downloading 107/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121102_1112_HARP2169_NOAA11603.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121102_1112_HARP2169_NOAA11603.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/bd0eca01dee0f0c41787aa6663c69f76.npz

.

Average throughput: 105.8MiB/s

[train] downloading 108/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130117_0948_HARP2380_NOAA11656.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130117_0948_HARP2380_NOAA11656.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b49398f319f94a6088d75f81025d3626.npz

.

Average throughput: 158.6MiB/s

[train] downloading 109/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110328_1024_HARP437_NOAA11176.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110328_1024_HARP437_NOAA11176.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a076353dcb36de80cb9bca4ba52afc8b.npz

.

Average throughput: 144.2MiB/s

[train] downloading 110/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120729_1236_HARP1892_NOAA11533.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120729_1236_HARP1892_NOAA11533.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8abad8db183f85b1f718ee985b011d33.npz

.

Average throughput: 188.8MiB/s

[train] downloading 111/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120228_0112_HARP1422_NOAA11423.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120228_0112_HARP1422_NOAA11423.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4a0266486a397391109ed5cb46614415.npz

.

Average throughput: 170.5MiB/s

[train] downloading 112/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120418_0400_HARP1557_NOAA11454.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120418_0400_HARP1557_NOAA11454.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b03188781ba48b3463512c7557c32b73.npz

.

Average throughput: 139.6MiB/s

[train] downloading 113/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111010_1300_HARP927_NOAA11312.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111010_1300_HARP927_NOAA11312.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/52b1e8f57898668e222a7dea676f148b.npz

.

Average throughput: 144.4MiB/s

[train] downloading 114/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131029_2024_HARP3326_NOAA11886.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131029_2024_HARP3326_NOAA11886.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/47d1b930a9898d580d6ed7ea9af7a5fd.npz

.

Average throughput: 120.3MiB/s

[train] downloading 115/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130112_0400_HARP2360_NOAA11650.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130112_0400_HARP2360_NOAA11650.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fa42cb1a52f7b8dd52a0bf436ab57751.npz

.

Average throughput: 84.0MiB/s

[train] downloading 116/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120710_1400_HARP1834_NOAA11519.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120710_1400_HARP1834_NOAA11519.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a68946048c83b05b187b87e4af8f6258.npz

.

Average throughput: 146.7MiB/s

[train] downloading 117/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120328_1536_HARP1520_NOAA11449.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120328_1536_HARP1520_NOAA11449.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/eec0f4c8187bbc679ba468e7c18d4d18.npz

.

Average throughput: 119.1MiB/s

[train] downloading 118/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120420_1436_HARP1574_NOAA11459.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120420_1436_HARP1574_NOAA11459.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b1e5d25c93d2f978418443c82088dde6.npz

.

Average throughput: 120.0MiB/s

[train] downloading 119/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120503_0424_HARP1621_NOAA11470.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120503_0424_HARP1621_NOAA11470.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/60786a26d699385383f1a9c6c0c8ce2f.npz

.

Average throughput: 188.3MiB/s

[train] downloading 120/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100531_2012_HARP43_NOAA11076.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100531_2012_HARP43_NOAA11076.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4424c8b54c6dcd1f959f731bb02a1201.npz

.

Average throughput: 163.1MiB/s

[train] downloading 121/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131016_2324_HARP3273_NOAA11868.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131016_2324_HARP3273_NOAA11868.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/823185993c64e28aad4fb3b00eb110d4.npz

.

Average throughput: 82.2MiB/s

[train] downloading 122/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120303_1036_HARP1425_NOAA11424.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120303_1036_HARP1425_NOAA11424.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1bcb1f9d9f7de4988b9b04fbe6c5e935.npz

.

Average throughput: 66.4MiB/s

[train] downloading 123/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101129_2136_HARP274_NOAA11130.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101129_2136_HARP274_NOAA11130.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/dff176ac58409110faf4b59ed1405a23.npz

.

Average throughput: 92.6MiB/s

[train] downloading 124/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131216_1824_HARP3497_NOAA11925.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131216_1824_HARP3497_NOAA11925.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ff3ca19e529b3f11fb52ba20ec6c0e91.npz



Average throughput: 196.4MiB/s

[train] downloading 125/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111013_1524_HARP956_NOAA11318.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111013_1524_HARP956_NOAA11318.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/078affebf1c241a0836af096f17902b7.npz

.

Average throughput: 88.5MiB/s

[train] downloading 126/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130815_1948_HARP3056_NOAA11818.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130815_1948_HARP3056_NOAA11818.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2c379807cc6edd4c38b30d4a930e269d.npz

.

Average throughput: 105.7MiB/s

[train] downloading 127/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120402_0000_HARP1514_NOAA11448.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120402_0000_HARP1514_NOAA11448.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/902766a8defe1842259f3b4f31bad20e.npz

.

Average throughput: 162.1MiB/s

[train] downloading 128/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110329_2300_HARP438_NOAA11177.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110329_2300_HARP438_NOAA11177.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8f5c083ca2d9c8966322508640c2fb48.npz

.

Average throughput: 102.6MiB/s

[train] downloading 129/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111112_1300_HARP1038_NOAA11340.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111112_1300_HARP1038_NOAA11340.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/19e49f762461b2230611791761c2b685.npz

.

Average throughput: 128.1MiB/s

[train] downloading 130/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130824_0124_HARP3098_NOAA11827.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130824_0124_HARP3098_NOAA11827.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f755ef6464b742e8081a04c4b635a1e1.npz

.

Average throughput: 169.5MiB/s

[train] downloading 131/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130527_0836_HARP2760_NOAA11753.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130527_0836_HARP2760_NOAA11753.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b013509d84a4e06d5ad8961510ea0e37.npz

.

Average throughput: 98.1MiB/s

[train] downloading 132/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110205_1036_HARP361_NOAA11152.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110205_1036_HARP361_NOAA11152.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8d8d949360d2913714ad2842f63adc08.npz



Average throughput: 199.6MiB/s

[train] downloading 133/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120327_0248_HARP1492_NOAA11442.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120327_0248_HARP1492_NOAA11442.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e88fb9cd5d9b7a93cbc5346abd305fed.npz



Average throughput: 182.2MiB/s

[train] downloading 134/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111021_1124_HARP975_NOAA11321.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111021_1124_HARP975_NOAA11321.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f1ae00c3756fa0c15d518322ff09c161.npz

.

Average throughput: 98.3MiB/s

[train] downloading 135/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121102_0036_HARP2166_NOAA11602.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121102_0036_HARP2166_NOAA11602.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/39486a1328869b7e4d0d78a293f0a0d0.npz

.

Average throughput: 86.0MiB/s

[train] downloading 136/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100818_1800_HARP128_NOAA11097.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100818_1800_HARP128_NOAA11097.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1f9765494bb9c3540ae081f4cf83570a.npz

.

Average throughput: 172.1MiB/s

[train] downloading 137/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121023_2000_HARP2130_NOAA11596.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121023_2000_HARP2130_NOAA11596.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2610be621bd7c5c79621dc30896319af.npz

.

Average throughput: 105.0MiB/s

[train] downloading 138/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130105_0812_HARP2338_NOAA11641.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130105_0812_HARP2338_NOAA11641.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7d3ae8a6093fe5dfb02978d8352dd1c7.npz

.

Average throughput: 179.5MiB/s

[train] downloading 139/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101206_1936_HARP279_NOAA11131.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101206_1936_HARP279_NOAA11131.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fbc86484fd4801fbbaf406d8dbde6a40.npz

.

Average throughput: 170.2MiB/s

[train] downloading 140/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120728_0124_HARP1892_NOAA11533.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120728_0124_HARP1892_NOAA11533.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d434945f4768d06269be8725e52d1f43.npz

.

Average throughput: 201.4MiB/s

[train] downloading 141/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111121_0500_HARP1079_NOAA11350.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111121_0500_HARP1079_NOAA11350.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ad5c9bbf741c47eb301a6181eab663de.npz

.

Average throughput: 85.9MiB/s

[train] downloading 142/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130726_0912_HARP2981_NOAA11799.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130726_0912_HARP2981_NOAA11799.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6762143b6bbf87a6d135ebdf5f096072.npz

.

Average throughput: 143.2MiB/s

[train] downloading 143/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100804_0800_HARP104_NOAA11092.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100804_0800_HARP104_NOAA11092.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a05b3a9201877f4ff9f8d7088c799fd3.npz

.

Average throughput: 86.7MiB/s

[train] downloading 144/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120510_0748_HARP1638_NOAA11476.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120510_0748_HARP1638_NOAA11476.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5f099b2e594295c75ff077f139b8ff16.npz

.

Average throughput: 138.8MiB/s

[train] downloading 145/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130502_1012_HARP2693_NOAA11731.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130502_1012_HARP2693_NOAA11731.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c3e790757c73b5a599e71a8ef92498ad.npz

.

Average throughput: 189.2MiB/s

[train] downloading 146/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130107_1448_HARP2352_NOAA11648.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130107_1448_HARP2352_NOAA11648.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f88de142c42d65f9fb78c8b167e525a9.npz

.

Average throughput: 64.7MiB/s

[train] downloading 147/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111011_2100_HARP927_NOAA11312.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111011_2100_HARP927_NOAA11312.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/73791138abbfb752167917812e75f278.npz

.

Average throughput: 86.8MiB/s

[train] downloading 148/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110716_0424_HARP714_NOAA11251.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110716_0424_HARP714_NOAA11251.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b4b4fae1be4d26e8c2080c50f299831b.npz

.

Average throughput: 136.0MiB/s

[train] downloading 149/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121212_2100_HARP2291_NOAA11631.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121212_2100_HARP2291_NOAA11631.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fd53b83b17c850079618ce14fbdf80ee.npz

.

Average throughput: 164.2MiB/s

[train] downloading 150/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101112_0848_HARP245_NOAA11121.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101112_0848_HARP245_NOAA11121.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ad0deae88d97979bdaea277453505ec9.npz

.

Average throughput: 114.6MiB/s

[train] downloading 151/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131210_0812_HARP3474_NOAA11927.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131210_0812_HARP3474_NOAA11927.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ff577bc0d4b5d1d184634d2e553490fd.npz

.

Average throughput: 169.5MiB/s

[train] downloading 152/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111118_1612_HARP1079_NOAA11350.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111118_1612_HARP1079_NOAA11350.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a5323983f7a5bdfc787494ca31a47f61.npz

.

Average throughput: 104.6MiB/s

[train] downloading 153/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100727_1836_HARP98_NOAA11090.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100727_1836_HARP98_NOAA11090.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/abf20973f1dada482d4ba8a5fbc1f583.npz

.

Average throughput: 94.6MiB/s

[train] downloading 154/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130501_1012_HARP2693_NOAA11731.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130501_1012_HARP2693_NOAA11731.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/93761280c48d0197c89bd711cdcca52f.npz



Average throughput: 130.6MiB/s

[train] downloading 155/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121212_0736_HARP2262_NOAA11628.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121212_0736_HARP2262_NOAA11628.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b327eef023bdfd8766438faa8c413303.npz

.

Average throughput: 107.2MiB/s

[train] downloading 156/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130112_0248_HARP2362_NOAA11652.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130112_0248_HARP2362_NOAA11652.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d2dacb97cdbcafc6910bbbec81a63882.npz

.

Average throughput: 178.4MiB/s

[train] downloading 157/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121031_0936_HARP2169_NOAA11603.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121031_0936_HARP2169_NOAA11603.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e2c773debf8bd2f4b3ed9ff4ed34a8f7.npz

.

Average throughput: 178.0MiB/s

[train] downloading 158/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130307_1000_HARP2511_NOAA11683.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130307_1000_HARP2511_NOAA11683.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0e2c84f3cd5866cd9b910479534875e7.npz

.

Average throughput: 154.0MiB/s

[train] downloading 159/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111209_2036_HARP1126_NOAA11364.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111209_2036_HARP1126_NOAA11364.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4cfbda8b0fc494a235a629618d50ae54.npz

.

Average throughput: 126.1MiB/s

[train] downloading 160/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110301_0312_HARP394_NOAA11165.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110301_0312_HARP394_NOAA11165.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/533cb2ee02afbfb2dfa511ccb75ee053.npz

.

Average throughput: 180.7MiB/s

[train] downloading 161/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100529_1112_HARP40_NOAA11075.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100529_1112_HARP40_NOAA11075.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2b0fb95b712cc3ab8009f105cfc21a4a.npz

.

Average throughput: 114.0MiB/s

[train] downloading 162/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120906_0612_HARP2007_NOAA11565.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120906_0612_HARP2007_NOAA11565.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/bf44a0f0ded0802f6161b9a629528bb8.npz

.

Average throughput: 102.3MiB/s

[train] downloading 163/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131228_2200_HARP3535_NOAA11936.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131228_2200_HARP3535_NOAA11936.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/71eb8d8e9d3706e6a4b87cc709a36090.npz

.

Average throughput: 130.8MiB/s

[train] downloading 164/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110405_1700_HARP466_NOAA11184.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110405_1700_HARP466_NOAA11184.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/22a59c382111cd813871bb8bbfdc0873.npz



Average throughput: 140.4MiB/s

[train] downloading 165/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120918_0200_HARP2026_NOAA11569.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120918_0200_HARP2026_NOAA11569.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6a83783fd1cfcfed51978c8d4930e239.npz

.

Average throughput: 177.6MiB/s

[train] downloading 166/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100827_0824_HARP146_NOAA11102.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100827_0824_HARP146_NOAA11102.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/295af97f1025822f571a496c91c7ba5a.npz

.

Average throughput: 90.1MiB/s

[train] downloading 167/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110714_1000_HARP712_NOAA11250.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110714_1000_HARP712_NOAA11250.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b180dd5bf0ad8a5cb68bcc3a8aa511a9.npz

.

Average throughput: 74.3MiB/s

[train] downloading 168/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131203_0636_HARP3446_NOAA11911.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131203_0636_HARP3446_NOAA11911.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2466f6644b267fb4c27abd69cef9a8ee.npz

.

Average throughput: 120.6MiB/s

[train] downloading 169/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120518_1924_HARP1658_NOAA11483.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120518_1924_HARP1658_NOAA11483.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7dbd0547b9b1e85b4826179da99e8871.npz

.

Average throughput: 191.6MiB/s

[train] downloading 170/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131020_1948_HARP3293_NOAA11874.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131020_1948_HARP3293_NOAA11874.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/820bba8b06e5bf3173a6930d85bc2afa.npz

.

Average throughput: 121.6MiB/s

[train] downloading 171/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110926_1748_HARP878_NOAA11301.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110926_1748_HARP878_NOAA11301.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b9c3a82fab0008a76922021c37631090.npz

.

Average throughput: 137.8MiB/s

[train] downloading 172/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120807_0312_HARP1907_NOAA11538.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120807_0312_HARP1907_NOAA11538.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7b94fd62bb23ff671fe1ff0360b304d9.npz

.

Average throughput: 86.1MiB/s

[train] downloading 173/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120908_2000_HARP2017_NOAA11568.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120908_2000_HARP2017_NOAA11568.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/08ecaa4113e91c9761eff66a62fddc93.npz

.

Average throughput: 187.7MiB/s

[train] downloading 174/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130406_1512_HARP2597_NOAA11713.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130406_1512_HARP2597_NOAA11713.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9f934394c077378c453fe4407970065d.npz

.

Average throughput: 162.2MiB/s

[train] downloading 175/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130421_2200_HARP2673_NOAA11726.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130421_2200_HARP2673_NOAA11726.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9c40aaabc9e063b8afe3b3493c16e388.npz

.

Average throughput: 105.7MiB/s

[train] downloading 176/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121229_2324_HARP2322_NOAA11636.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121229_2324_HARP2322_NOAA11636.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2a7686c37a9aaa63f99883642f852d95.npz

.

Average throughput: 111.6MiB/s

[train] downloading 177/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121111_0248_HARP2177_NOAA11608.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121111_0248_HARP2177_NOAA11608.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ffbf08d565f842d9039c381960f5071d.npz

.

Average throughput: 72.6MiB/s

[train] downloading 178/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110927_0348_HARP892_NOAA11302.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110927_0348_HARP892_NOAA11302.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d3f35e74bd891015da94956072850d37.npz

.

Average throughput: 46.4MiB/s

[train] downloading 179/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111003_1900_HARP903_NOAA11306.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111003_1900_HARP903_NOAA11306.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1844e7841ce7e51b451337558a4b4955.npz

.

Average throughput: 161.4MiB/s

[train] downloading 180/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130922_1224_HARP3212_NOAA11845.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130922_1224_HARP3212_NOAA11845.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/24455d673f0561f06be8388abc3da046.npz

.

Average throughput: 183.0MiB/s

[train] downloading 181/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131010_0200_HARP3248_NOAA11856.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131010_0200_HARP3248_NOAA11856.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/632bf80105fa5eb732bb38c37523f5d4.npz

.

Average throughput: 192.0MiB/s

[train] downloading 182/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111217_2112_HARP1183_NOAA11376.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111217_2112_HARP1183_NOAA11376.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/260b788e2087a0180c64ef3668733092.npz

.

Average throughput: 118.8MiB/s

[train] downloading 183/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131012_1200_HARP3258_NOAA11861.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131012_1200_HARP3258_NOAA11861.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a2e7f98768c0ac94f5b7936d42a875ba.npz

.

Average throughput: 108.7MiB/s

[train] downloading 184/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120518_0636_HARP1658_NOAA11483.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120518_0636_HARP1658_NOAA11483.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/57accbdefdc0125ba2fefe41bd576b4c.npz

.

Average throughput: 113.1MiB/s

[train] downloading 185/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120401_1424_HARP1514_NOAA11448.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120401_1424_HARP1514_NOAA11448.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6eaaae7c9dd35e0242987683995b2e24.npz

.

Average throughput: 134.0MiB/s

[train] downloading 186/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131106_0612_HARP3330_NOAA11887.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131106_0612_HARP3330_NOAA11887.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a93734d675b29d39f6000d39bebc33c1.npz

.

Average throughput: 182.9MiB/s

[train] downloading 187/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131130_0700_HARP3443_NOAA11914.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131130_0700_HARP3443_NOAA11914.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/818c1d41cbbfc45d6f3acf53b7aff6c3.npz

.

Average throughput: 154.8MiB/s

[train] downloading 188/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111107_0148_HARP1026_NOAA11338.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111107_0148_HARP1026_NOAA11338.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0cbf947500276689b9d595e61d358aae.npz

.

Average throughput: 169.0MiB/s

[train] downloading 189/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110807_1500_HARP759_NOAA11266.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110807_1500_HARP759_NOAA11266.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4cd4d5f68cf8d15cf0b288183accb994.npz

.

Average throughput: 95.4MiB/s

[train] downloading 190/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101025_0048_HARP223_NOAA11118.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101025_0048_HARP223_NOAA11118.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5d179e5a05caeba0617877c1eda85772.npz

.

Average throughput: 166.8MiB/s

[train] downloading 191/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100902_1500_HARP147_NOAA11104.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100902_1500_HARP147_NOAA11104.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e91963375dfb3577d24e9640516cd606.npz

.

Average throughput: 105.5MiB/s

[train] downloading 192/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110903_1748_HARP824_NOAA11281.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110903_1748_HARP824_NOAA11281.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8bcfd99f844fdbcff8adfbcfc56f4998.npz

.

Average throughput: 144.1MiB/s

[train] downloading 193/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111016_0548_HARP950_NOAA11316.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111016_0548_HARP950_NOAA11316.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/998439adfee9d170c4041d09d3986cc8.npz

.

Average throughput: 75.2MiB/s

[train] downloading 194/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130207_2012_HARP2450_NOAA11669.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130207_2012_HARP2450_NOAA11669.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c47f4a47d727a09fe04b9f3a850226a4.npz



Average throughput: 186.5MiB/s

[train] downloading 195/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120627_2248_HARP1795_NOAA11512.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120627_2248_HARP1795_NOAA11512.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/94e6be5159c763b70a21eb0383f0b999.npz

.

Average throughput: 138.7MiB/s

[train] downloading 196/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110605_2336_HARP639_NOAA11228.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110605_2336_HARP639_NOAA11228.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/af36aa1352592702dc778576536f5a58.npz

.

Average throughput: 115.2MiB/s

[train] downloading 197/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130419_0836_HARP2663_NOAA11723.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130419_0836_HARP2663_NOAA11723.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ab8bc0206e0ed9698e43ab9976a374cc.npz

.

Average throughput: 194.7MiB/s

[train] downloading 198/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130814_0800_HARP3079_NOAA11821.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130814_0800_HARP3079_NOAA11821.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b44a4fc90fefd88416968ad05914f3d7.npz

.

Average throughput: 101.2MiB/s

[train] downloading 199/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130925_0724_HARP3194_NOAA11845.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130925_0724_HARP3194_NOAA11845.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/de4879513c0e0593eaf02a6a73c231e6.npz

.

Average throughput: 97.8MiB/s

[train] downloading 200/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101226_2148_HARP317_NOAA11137.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101226_2148_HARP317_NOAA11137.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6e39a3b4c16997c55361fb827d899e74.npz

.

Average throughput: 142.6MiB/s

[train] cached/checked 200/1650 files | elapsed 5.2 min
[train] downloading 201/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101111_1512_HARP245_NOAA11121.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101111_1512_HARP245_NOAA11121.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/19129b01427effab11ac9364cebf9cdd.npz

.

Average throughput: 110.0MiB/s

[train] downloading 202/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120915_1224_HARP2026_NOAA11569.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120915_1224_HARP2026_NOAA11569.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c73d44ac9c95c6a9b7b52fb54e7d8779.npz

.

Average throughput: 81.5MiB/s

[train] downloading 203/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111004_0248_HARP924_NOAA11310.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111004_0248_HARP924_NOAA11310.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/68ece2c903e6e1fb3648d3a758731147.npz

.

Average throughput: 96.3MiB/s

[train] downloading 204/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100920_2100_HARP185_NOAA11108.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100920_2100_HARP185_NOAA11108.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0c05f8dd06afe05f3246669e1fbcf778.npz

.

Average throughput: 39.3MiB/s

[train] downloading 205/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110620_0312_HARP667_NOAA11236.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110620_0312_HARP667_NOAA11236.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/793a88fb7f855d22ef22f3724f1fb8ba.npz

.

Average throughput: 151.9MiB/s

[train] downloading 206/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111013_0236_HARP956_NOAA11318.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111013_0236_HARP956_NOAA11318.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/669705a157932e2046247dd684552566.npz

.

Average throughput: 133.0MiB/s

[train] downloading 207/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110219_2348_HARP384_NOAA11160.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110219_2348_HARP384_NOAA11160.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0f3a99efa7e3e96d1be0739ee400ea69.npz

.

Average throughput: 157.6MiB/s

[train] downloading 208/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130323_0112_HARP2571_NOAA11700.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130323_0112_HARP2571_NOAA11700.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/062a692f78d6276753563468880ae64c.npz

.

Average throughput: 125.9MiB/s

[train] downloading 209/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130109_2336_HARP2362_NOAA11652.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130109_2336_HARP2362_NOAA11652.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3d3cc9f510ce7f566740625dcfcd6c3f.npz

.

Average throughput: 175.2MiB/s

[train] downloading 210/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130530_0724_HARP2779_NOAA11757.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130530_0724_HARP2779_NOAA11757.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/db128a9f2b523322dc838d87ab206d20.npz

.

Average throughput: 33.3MiB/s

[train] downloading 211/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121110_0424_HARP2181_NOAA11609.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121110_0424_HARP2181_NOAA11609.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/92507839113eb980bd69402621583490.npz

.

Average throughput: 92.6MiB/s

[train] downloading 212/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110911_0900_HARP851_NOAA11291.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110911_0900_HARP851_NOAA11291.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6b873ad40e16ba2257fa50441f64ee07.npz

.

Average throughput: 180.7MiB/s

[train] downloading 213/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111007_1012_HARP918_NOAA11309.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111007_1012_HARP918_NOAA11309.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/27ebb19ce6464e0bf06f792c1a9e8379.npz

.

Average throughput: 60.0MiB/s

[train] downloading 214/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110914_2136_HARP847_NOAA11289.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110914_2136_HARP847_NOAA11289.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/480e38429b51f3dd72a3ac1ae927749a.npz

.

Average throughput: 80.6MiB/s

[train] downloading 215/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131022_0412_HARP3286_NOAA11872.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131022_0412_HARP3286_NOAA11872.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cc3efa6ba1d4188c8c0b7e911cf81575.npz

.

Average throughput: 151.8MiB/s

[train] downloading 216/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130526_1836_HARP2758_NOAA11754.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130526_1836_HARP2758_NOAA11754.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b1e5c5d197e171d6f96d116a45ce16ae.npz

.

Average throughput: 104.5MiB/s

[train] downloading 217/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130904_1012_HARP3129_NOAA11836.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130904_1012_HARP3129_NOAA11836.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2888293845df43e95d6e2516c85b6bdc.npz

.

Average throughput: 70.5MiB/s

[train] downloading 218/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120418_2224_HARP1578_NOAA11460.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120418_2224_HARP1578_NOAA11460.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0b753fd578b6ac523fca5bffd8d18c91.npz

.

Average throughput: 115.1MiB/s

[train] downloading 219/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120921_1736_HARP2037_NOAA11573.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120921_1736_HARP2037_NOAA11573.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/73bc7e4fca71c50b5767d4da07e58075.npz

.

Average throughput: 106.1MiB/s

[train] downloading 220/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131220_1700_HARP3515_NOAA11930.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131220_1700_HARP3515_NOAA11930.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8a9bcd4ac25ce6e2a6fe7d813f5f1dc5.npz

.

Average throughput: 125.0MiB/s

[train] downloading 221/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130214_1236_HARP2469_NOAA11671.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130214_1236_HARP2469_NOAA11671.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/20e777e9fcd171477ba390337bd923df.npz

.

Average throughput: 81.8MiB/s

[train] downloading 222/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120415_1700_HARP1569_NOAA11457.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120415_1700_HARP1569_NOAA11457.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2d248327da72526b0c78edbde7392fca.npz

.

Average throughput: 102.7MiB/s

[train] downloading 223/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120228_0548_HARP1426_NOAA11426.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120228_0548_HARP1426_NOAA11426.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/090258ce1df8730ec2aefe95cdcdc575.npz

.

Average throughput: 111.7MiB/s

[train] downloading 224/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110209_1512_HARP367_NOAA11156.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110209_1512_HARP367_NOAA11156.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/698fc451ab3ef49430e55a50833f7a2b.npz

.

Average throughput: 156.1MiB/s

[train] downloading 225/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100702_0612_HARP71_NOAA11084.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100702_0612_HARP71_NOAA11084.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3a014edf34b237cb397eec74ce34f52c.npz

.

Average throughput: 88.5MiB/s

[train] downloading 226/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120629_1348_HARP1795_NOAA11512.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120629_1348_HARP1795_NOAA11512.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/be6170b4ac5a07c13fd7001a60617104.npz

.

Average throughput: 165.3MiB/s

[train] downloading 227/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120127_2236_HARP1338_NOAA11408.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120127_2236_HARP1338_NOAA11408.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b1c405c02ad2ffe096e4a496bf2e10aa.npz

.

Average throughput: 80.4MiB/s

[train] downloading 228/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131202_0700_HARP3446_NOAA11911.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131202_0700_HARP3446_NOAA11911.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1a6a5149c4c2ac070b53174cc220709a.npz



Average throughput: 176.9MiB/s

[train] downloading 229/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100829_1548_HARP147_NOAA11104.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100829_1548_HARP147_NOAA11104.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0fef6e8f5553b08b28bb314c9f5d9ca2.npz

.

Average throughput: 83.0MiB/s

[train] downloading 230/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130421_1612_HARP2683_NOAA11729.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130421_1612_HARP2683_NOAA11729.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/19f851713811bbfb28beabf227435b04.npz

.

Average throughput: 104.5MiB/s

[train] downloading 231/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121017_0348_HARP2114_NOAA11592.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121017_0348_HARP2114_NOAA11592.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e29e9d6553fae082c992e6863c2b0a6b.npz

.

Average throughput: 153.3MiB/s

[train] downloading 232/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110310_1800_HARP401_NOAA11166.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110310_1800_HARP401_NOAA11166.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/927ed770bdc866253c45198739ea06a5.npz

.

Average throughput: 94.5MiB/s

[train] downloading 233/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100821_0512_HARP135_NOAA11100.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100821_0512_HARP135_NOAA11100.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/dd1239c94684ebeb62007a6fec24d662.npz

.

Average throughput: 102.9MiB/s

[train] downloading 234/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110719_1436_HARP728_NOAA11256.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110719_1436_HARP728_NOAA11256.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a4457278b9fd85f53abd444f7ba02507.npz

.

Average throughput: 153.9MiB/s

[train] downloading 235/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120117_2048_HARP1312_NOAA11397.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120117_2048_HARP1312_NOAA11397.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cd39d8477404276279a14afba566ee8a.npz

.

Average throughput: 54.8MiB/s

[train] downloading 236/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130102_0100_HARP2322_NOAA11636.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130102_0100_HARP2322_NOAA11636.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/04e8ffdc3590fe33c96fc8a70fa5ea08.npz

.

Average throughput: 59.8MiB/s

[train] downloading 237/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110620_0848_HARP676_NOAA11239.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110620_0848_HARP676_NOAA11239.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/44c43d9a25c8135df03723772bcdd8da.npz

.

Average throughput: 101.9MiB/s

[train] downloading 238/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121203_2348_HARP2260_NOAA11627.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121203_2348_HARP2260_NOAA11627.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7f33f3834c9b074d199d003530b267fa.npz

.

Average throughput: 81.9MiB/s

[train] downloading 239/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130319_1412_HARP2557_NOAA11695.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130319_1412_HARP2557_NOAA11695.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a736efd474e973c77ef55741a584a299.npz

.

Average throughput: 118.4MiB/s

[train] downloading 240/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111203_0400_HARP1133_NOAA11365.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111203_0400_HARP1133_NOAA11365.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5e78ee8c8f74b5e8a0c61aa8793014a5.npz

.

Average throughput: 165.9MiB/s

[train] downloading 241/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130621_1912_HARP2852_NOAA11769.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130621_1912_HARP2852_NOAA11769.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fce516cc184d3fdf9a86a117b3c78382.npz

.

Average throughput: 75.5MiB/s

[train] downloading 242/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130627_1312_HARP2878_NOAA11777.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130627_1312_HARP2878_NOAA11777.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1e1962021ef4ad5b83244c9159597add.npz

.

Average throughput: 144.2MiB/s

[train] downloading 243/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131012_1348_HARP3267_NOAA11867.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131012_1348_HARP3267_NOAA11867.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8ebc5721358316de318269bff5fd4e2c.npz



Average throughput: 190.4MiB/s

[train] downloading 244/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130122_0312_HARP2400_NOAA11660.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130122_0312_HARP2400_NOAA11660.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/62510706cde3c51188962d7a7de8d758.npz

.

Average throughput: 177.6MiB/s

[train] downloading 245/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131111_0500_HARP3367_NOAA11898.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131111_0500_HARP3367_NOAA11898.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/11bd22403201f07e5ddf7d2d08b8b284.npz

.

Average throughput: 138.5MiB/s

[train] downloading 246/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110908_0536_HARP833_NOAA11283.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110908_0536_HARP833_NOAA11283.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9bdf41032db3386f3b8f5ebaded6fd8d.npz

.

Average throughput: 113.5MiB/s

[train] downloading 247/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130913_1724_HARP3154_NOAA11838.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130913_1724_HARP3154_NOAA11838.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/223fc92dd071b81cf43f4f9131f98bde.npz



Average throughput: 168.5MiB/s

[train] downloading 248/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110202_2324_HARP355_NOAA11150.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110202_2324_HARP355_NOAA11150.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a6456d62436def5b19d936c20f0d7b93.npz

.

Average throughput: 84.0MiB/s

[train] downloading 249/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120731_0000_HARP1877_NOAA11527.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120731_0000_HARP1877_NOAA11527.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a6140780802e8b3d8758d92d37760009.npz



Average throughput: 195.2MiB/s

[train] downloading 250/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130531_1824_HARP2808_NOAA11761.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130531_1824_HARP2808_NOAA11761.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7c6ff5eac918c0f35770520f64851304.npz

.

Average throughput: 132.7MiB/s

[train] downloading 251/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110204_1524_HARP361_NOAA11152.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110204_1524_HARP361_NOAA11152.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0ac34c60e2e991f13ba133e8cb15818a.npz

.

Average throughput: 123.6MiB/s

[train] downloading 252/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121207_0848_HARP2259_NOAA11626.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121207_0848_HARP2259_NOAA11626.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ff512a93f1d81e313c3aa820306ead29.npz

.

Average throughput: 80.0MiB/s

[train] downloading 253/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130329_1300_HARP2595_NOAA11706.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130329_1300_HARP2595_NOAA11706.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/651003249203b1ff66fbb2aa596894da.npz

.

Average throughput: 75.0MiB/s

[train] downloading 254/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120512_1948_HARP1638_NOAA11476.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120512_1948_HARP1638_NOAA11476.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7655c6360fa54e398a49a29fa7c8e858.npz

.

Average throughput: 111.1MiB/s

[train] downloading 255/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131211_0812_HARP3474_NOAA11927.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131211_0812_HARP3474_NOAA11927.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/731a86600499ba09a6f5f61eb1cdf5c8.npz

.

Average throughput: 107.4MiB/s

[train] downloading 256/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130327_1924_HARP2587_NOAA11704.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130327_1924_HARP2587_NOAA11704.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b291db5100b5b717eba1e6797479ec73.npz

.

Average throughput: 150.9MiB/s

[train] downloading 257/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130824_1548_HARP3103_NOAA11828.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130824_1548_HARP3103_NOAA11828.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0e2198216fa1ea271faa980f4bfe8190.npz



Average throughput: 194.3MiB/s

[train] downloading 258/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130404_1412_HARP2605_NOAA11711.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130404_1412_HARP2605_NOAA11711.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fcf31cd8351a479974fb3b5eaee3293b.npz

.

Average throughput: 173.1MiB/s

[train] downloading 259/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120131_1912_HARP1348_NOAA11411.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120131_1912_HARP1348_NOAA11411.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4aaba06891a2cf6f67767fb9f3d04655.npz

.

Average throughput: 73.6MiB/s

[train] downloading 260/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110830_1036_HARP817_NOAA11285.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110830_1036_HARP817_NOAA11285.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/df5fc9a54e4e8fa3711578153b8480f9.npz

.

Average throughput: 160.5MiB/s

[train] downloading 261/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120825_1500_HARP1951_NOAA11552.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120825_1500_HARP1951_NOAA11552.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a09fb703fa4f3e1fd3dcfc3d603763ee.npz

.

Average throughput: 113.9MiB/s

[train] downloading 262/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130502_1724_HARP2710_NOAA11736.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130502_1724_HARP2710_NOAA11736.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ae40b44060c54482bc40f22c51535ffb.npz

.

Average throughput: 184.4MiB/s

[train] downloading 263/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110930_1948_HARP892_NOAA11302.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110930_1948_HARP892_NOAA11302.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2f87cf1fa7a46d096e426159d6565c0f.npz

.

Average throughput: 109.6MiB/s

[train] downloading 264/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111209_1248_HARP1149_NOAA11367.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111209_1248_HARP1149_NOAA11367.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/540e3c157b8a55018b9ba5a2762195eb.npz

.

Average throughput: 182.4MiB/s

[train] downloading 265/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111002_1436_HARP903_NOAA11306.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111002_1436_HARP903_NOAA11306.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0bb3441c0bb41fbdf8744c7e859312d4.npz

.

Average throughput: 152.1MiB/s

[train] downloading 266/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111031_1248_HARP1005_NOAA11332.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111031_1248_HARP1005_NOAA11332.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/007c1649db4e6e338de6262f52f49e00.npz

.

Average throughput: 81.5MiB/s

[train] downloading 267/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101014_0912_HARP211_NOAA11112.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101014_0912_HARP211_NOAA11112.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1c6b75ac86c573c64cf0d08dd48a6794.npz

.

Average throughput: 131.9MiB/s

[train] downloading 268/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120522_0436_HARP1669_NOAA11485.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120522_0436_HARP1669_NOAA11485.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/77166831522cafad335a56d3e3c0d496.npz

.

Average throughput: 148.1MiB/s

[train] downloading 269/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120607_1536_HARP1724_NOAA11494.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120607_1536_HARP1724_NOAA11494.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/92ba8e62f30ff918744afc11d5862c51.npz

.

Average throughput: 119.9MiB/s

[train] downloading 270/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111211_1724_HARP1164_NOAA11368.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111211_1724_HARP1164_NOAA11368.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ed582a3bcacea600b20105f8a3e3dc67.npz

.

Average throughput: 155.8MiB/s

[train] downloading 271/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120420_1236_HARP1572_NOAA11458.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120420_1236_HARP1572_NOAA11458.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e7834c95c187b46abf98694fafd916fb.npz

.

Average throughput: 173.1MiB/s

[train] downloading 272/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120723_1812_HARP1866_NOAA11524.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120723_1812_HARP1866_NOAA11524.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/729fd169c0c56339a9ef261a229bc3e0.npz

.

Average throughput: 147.1MiB/s

[train] downloading 273/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100727_0000_HARP92_NOAA11089.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100727_0000_HARP92_NOAA11089.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/12ed56496365316c1290cbdfa5f1944a.npz

.

Average throughput: 128.1MiB/s

[train] downloading 274/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101112_1912_HARP252_NOAA11124.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101112_1912_HARP252_NOAA11124.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/af0e76ce97df63f1d12f9db560c639ce.npz

.

Average throughput: 121.9MiB/s

[train] downloading 275/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100731_0300_HARP98_NOAA11090.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100731_0300_HARP98_NOAA11090.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4524015f79366e0f1b46137493339c43.npz

.

Average throughput: 124.8MiB/s

[train] downloading 276/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120216_0848_HARP1391_NOAA11417.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120216_0848_HARP1391_NOAA11417.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5f5da85561b754561b384dcb2d8460e3.npz

.

Average throughput: 142.1MiB/s

[train] downloading 277/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120414_1336_HARP1557_NOAA11454.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120414_1336_HARP1557_NOAA11454.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d4b37117221937a61177d5130303491a.npz

.

Average throughput: 136.1MiB/s

[train] downloading 278/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121110_1536_HARP2177_NOAA11608.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121110_1536_HARP2177_NOAA11608.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/81f175aac017f1675eb40c938aac74d3.npz

.

Average throughput: 100.4MiB/s

[train] downloading 279/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110214_0112_HARP377_NOAA11158.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110214_0112_HARP377_NOAA11158.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/47baf7089fc54b3bcc1ad73263a7f887.npz



Average throughput: 169.9MiB/s

[train] downloading 280/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130702_0112_HARP2910_NOAA11782.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130702_0112_HARP2910_NOAA11782.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0736a8ff009ce6091dcc016b4f1bef02.npz

.

Average throughput: 118.3MiB/s

[train] downloading 281/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131101_1512_HARP3321_NOAA11884.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131101_1512_HARP3321_NOAA11884.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8e0680000e1357a002ea3bbb48cbcba6.npz

.

Average throughput: 128.0MiB/s

[train] downloading 282/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130501_0348_HARP2693_NOAA11731.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130501_0348_HARP2693_NOAA11731.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c998655193111494ab14a9d7f65b9948.npz

.

Average throughput: 85.1MiB/s

[train] downloading 283/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101202_1048_HARP270_NOAA11128.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101202_1048_HARP270_NOAA11128.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2750876c2d593a99e3d2736eda437c9f.npz

.

Average throughput: 158.6MiB/s

[train] downloading 284/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120720_1948_HARP1866_NOAA11524.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120720_1948_HARP1866_NOAA11524.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6977c17202d4426c89d8d503d0e428a8.npz

.

Average throughput: 73.8MiB/s

[train] downloading 285/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110310_2112_HARP401_NOAA11166.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110310_2112_HARP401_NOAA11166.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cf99eff63994e6e2498079d2f7a44123.npz

.

Average throughput: 168.6MiB/s

[train] downloading 286/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110501_2324_HARP538_NOAA11200.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110501_2324_HARP538_NOAA11200.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/50691a7254e6da33a792376a2c0471df.npz

.

Average throughput: 76.3MiB/s

[train] downloading 287/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120510_0124_HARP1638_NOAA11476.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120510_0124_HARP1638_NOAA11476.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/55ecb23bcad417eb4c25cf2af92fe7a0.npz

.

Average throughput: 144.0MiB/s

[train] downloading 288/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131126_1936_HARP3415_NOAA11906.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131126_1936_HARP3415_NOAA11906.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0c3e2b54a9513ebfc0987e9904e143d9.npz

.

Average throughput: 148.2MiB/s

[train] downloading 289/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120101_0212_HARP1249_NOAA11390.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120101_0212_HARP1249_NOAA11390.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f2595c2d52b9047d52177607a1d5bee3.npz

.

Average throughput: 145.9MiB/s

[train] downloading 290/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100820_0512_HARP135_NOAA11100.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100820_0512_HARP135_NOAA11100.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b97176035938be02b1d64c85fea6d463.npz

.

Average throughput: 154.2MiB/s

[train] downloading 291/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131112_1700_HARP3364_NOAA11893.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131112_1700_HARP3364_NOAA11893.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/65caad4031df984c6dc8c04a03184604.npz

.

Average throughput: 31.7MiB/s

[train] downloading 292/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131029_1500_HARP3311_NOAA11882.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131029_1500_HARP3311_NOAA11882.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e09647538d514cd68d4cab142ceed2d3.npz

.

Average throughput: 147.2MiB/s

[train] downloading 293/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100723_1400_HARP92_NOAA11089.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100723_1400_HARP92_NOAA11089.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4fcf1196a7c584bd35295d0a334df8b8.npz

.

Average throughput: 108.5MiB/s

[train] downloading 294/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130320_0312_HARP2571_NOAA11700.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130320_0312_HARP2571_NOAA11700.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0cc749c469d4fb06e859bb3edae1fbe4.npz

.

Average throughput: 166.3MiB/s

[train] downloading 295/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100802_1724_HARP107_NOAA11094.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100802_1724_HARP107_NOAA11094.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/96887a068d3f809d61423bdc4534ba38.npz

.

Average throughput: 181.0MiB/s

[train] downloading 296/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130502_1636_HARP2693_NOAA11731.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130502_1636_HARP2693_NOAA11731.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9d2244d9d7df3ccf12886aa5396a243f.npz

.

Average throughput: 105.8MiB/s

[train] downloading 297/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120121_0512_HARP1321_NOAA11401.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120121_0512_HARP1321_NOAA11401.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/bd9a31403e8807458584aa657d31da6a.npz

.

Average throughput: 86.3MiB/s

[train] downloading 298/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120729_1248_HARP1877_NOAA11527.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120729_1248_HARP1877_NOAA11527.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f777eae49a708bc4923c9ba36e382068.npz

.

Average throughput: 61.9MiB/s

[train] downloading 299/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121231_2012_HARP2337_NOAA11640.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121231_2012_HARP2337_NOAA11640.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/78ccf927ce5dbc71c6305ddf10d2e090.npz

.

Average throughput: 135.1MiB/s

[train] downloading 300/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131117_2036_HARP3366_NOAA11895.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131117_2036_HARP3366_NOAA11895.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/06bfbc3b3551bab6c07b6b58f804a4f5.npz



Average throughput: 115.9MiB/s

[train] cached/checked 300/1650 files | elapsed 7.7 min
[train] downloading 301/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121024_2224_HARP2144_NOAA11600.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121024_2224_HARP2144_NOAA11600.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a5d05aeb9ed2115d4e423710d6bd9c68.npz

.

Average throughput: 198.9MiB/s

[train] downloading 302/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130730_1924_HARP3011_NOAA11812.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130730_1924_HARP3011_NOAA11812.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/be20d7275eb538c086e85d044ca212fd.npz

.

Average throughput: 101.7MiB/s

[train] downloading 303/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120604_0412_HARP1737_NOAA11500.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120604_0412_HARP1737_NOAA11500.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7645f10758f443aca82fdd7907363db2.npz

.

Average throughput: 122.2MiB/s

[train] downloading 304/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131201_0800_HARP3432_NOAA11908.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131201_0800_HARP3432_NOAA11908.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2a5103d6cc43027f210c307f27836b38.npz

.

Average throughput: 27.6MiB/s

[train] downloading 305/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100803_0624_HARP104_NOAA11092.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100803_0624_HARP104_NOAA11092.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1f5bb50292e2aa6a3f2c3d9a2996577d.npz

.

Average throughput: 119.3MiB/s

[train] downloading 306/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120906_0736_HARP2017_NOAA11568.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120906_0736_HARP2017_NOAA11568.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6a146b5d3f8df27598ddf4207262c7d1.npz

.

Average throughput: 172.5MiB/s

[train] downloading 307/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110205_1212_HARP361_NOAA11152.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110205_1212_HARP361_NOAA11152.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d93ff7afc33776ec9743427518fcd1e1.npz

.

Average throughput: 150.1MiB/s

[train] downloading 308/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131018_1948_HARP3293_NOAA11874.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131018_1948_HARP3293_NOAA11874.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b4a878b89bcf5eebaae98c23a150ccf5.npz

.

Average throughput: 66.3MiB/s

[train] downloading 309/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130919_1036_HARP3195_NOAA11843.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130919_1036_HARP3195_NOAA11843.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f477d20d171c94a8e3006f4df8b0918e.npz

.

Average throughput: 135.3MiB/s

[train] downloading 310/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111101_0400_HARP1021_NOAA11334.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111101_0400_HARP1021_NOAA11334.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f25fd37761551392fab1e013c0b608b2.npz

.

Average throughput: 140.1MiB/s

[train] downloading 311/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131004_0312_HARP3244_NOAA11855.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131004_0312_HARP3244_NOAA11855.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3d7a784d9822455d3efff1ee7584128a.npz

.

Average throughput: 75.5MiB/s

[train] downloading 312/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131102_1612_HARP3336_NOAA11889.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131102_1612_HARP3336_NOAA11889.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5f5b77474e021a5d7644c093d9f569ac.npz

.

Average throughput: 176.9MiB/s

[train] downloading 313/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110908_2324_HARP846_NOAA11288.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110908_2324_HARP846_NOAA11288.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c4e4ed58c334f9bffa50f1cc5ba1b540.npz

.

Average throughput: 114.5MiB/s

[train] downloading 314/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111110_1100_HARP1028_NOAA11339.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111110_1100_HARP1028_NOAA11339.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/17a4c9b35b8fef7090227bc8de0375c4.npz

.

Average throughput: 64.5MiB/s

[train] downloading 315/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130129_1536_HARP2414_NOAA11662.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130129_1536_HARP2414_NOAA11662.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4d532644e01e3651c43004a94b8e4ca8.npz



Average throughput: 171.8MiB/s

[train] downloading 316/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101023_2312_HARP223_NOAA11118.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101023_2312_HARP223_NOAA11118.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e5ba5be0f78b15a965a96ee0fcba1d99.npz

.

Average throughput: 60.5MiB/s

[train] downloading 317/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130117_1436_HARP2380_NOAA11656.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130117_1436_HARP2380_NOAA11656.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e93ed3e260b21a5e2cd96ec6be7c8df3.npz

.

Average throughput: 95.1MiB/s

[train] downloading 318/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100622_1148_HARP57_NOAA11082.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100622_1148_HARP57_NOAA11082.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5dd6a6ed1d5fba3b0f46616c2bc80a95.npz

.

Average throughput: 159.0MiB/s

[train] downloading 319/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110710_0500_HARP695_NOAA11247.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110710_0500_HARP695_NOAA11247.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fb47c79c34d54c4e4d24e84d63a82230.npz

.

Average throughput: 55.3MiB/s

[train] downloading 320/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130630_0900_HARP2912_NOAA11781.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130630_0900_HARP2912_NOAA11781.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d972aa9a4538243f9221733544c35987.npz

.

Average throughput: 157.8MiB/s

[train] downloading 321/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130731_2212_HARP2999_NOAA11801.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130731_2212_HARP2999_NOAA11801.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/aa07298be897bf114e66ed462cdae3e5.npz

.

Average throughput: 106.3MiB/s

[train] downloading 322/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110206_1348_HARP361_NOAA11152.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110206_1348_HARP361_NOAA11152.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/98c30ac6f31468b41ad4607d85c66efb.npz

.

Average throughput: 186.3MiB/s

[train] downloading 323/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110304_0700_HARP393_NOAA11164.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110304_0700_HARP393_NOAA11164.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/105dbcba3853a1fd7c0aa6b0fa83d769.npz

.

Average throughput: 172.4MiB/s

[train] downloading 324/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131106_1612_HARP3336_NOAA11889.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131106_1612_HARP3336_NOAA11889.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/932c79c86901a9a36e6bd2071eb8fd4f.npz

.

Average throughput: 68.7MiB/s

[train] downloading 325/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110603_0736_HARP639_NOAA11228.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110603_0736_HARP639_NOAA11228.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c25d3398356498ba08482dc776315b93.npz

.

Average throughput: 123.1MiB/s

[train] downloading 326/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120306_1824_HARP1449_NOAA11429.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120306_1824_HARP1449_NOAA11429.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c166828f0381addad8b293844ff94923.npz

.

Average throughput: 90.6MiB/s

[train] downloading 327/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111117_0400_HARP1066_NOAA11346.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111117_0400_HARP1066_NOAA11346.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/80954aa1b789dded421669caaf87f35c.npz

.

Average throughput: 149.1MiB/s

[train] downloading 328/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110711_1912_HARP702_NOAA11249.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110711_1912_HARP702_NOAA11249.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b490bdc62bfd71f914375a98280a2527.npz

.

Average throughput: 163.9MiB/s

[train] downloading 329/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120120_1448_HARP1321_NOAA11401.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120120_1448_HARP1321_NOAA11401.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/59d97f2f3c9729a742ab9b0f6dc582d6.npz

.

Average throughput: 64.5MiB/s

[train] downloading 330/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121119_1324_HARP2203_NOAA11616.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121119_1324_HARP2203_NOAA11616.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fb4a88857d5966b4661add834eb6b82a.npz

.

Average throughput: 39.5MiB/s

[train] downloading 331/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121009_2300_HARP2098_NOAA11585.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121009_2300_HARP2098_NOAA11585.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4b7da970c4f6fb8bce337fc23b0bba6f.npz

.

Average throughput: 106.0MiB/s

[train] downloading 332/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120831_2324_HARP1997_NOAA11561.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120831_2324_HARP1997_NOAA11561.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c4ca2d8ccc798e362f5ea308cf1dac6f.npz

.

Average throughput: 93.0MiB/s

[train] downloading 333/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110412_0824_HARP480_NOAA11185.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110412_0824_HARP480_NOAA11185.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8bb8ae269560964cc14edc9347630841.npz

.

Average throughput: 83.6MiB/s

[train] downloading 334/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130808_0148_HARP3028_NOAA11809.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130808_0148_HARP3028_NOAA11809.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/da0b60f36685a18f6e28a88b6a072a5b.npz

.

Average throughput: 102.6MiB/s

[train] downloading 335/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131108_0400_HARP3341_NOAA11890.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131108_0400_HARP3341_NOAA11890.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/546e696497e56e86eacdbb31c35e5e84.npz

.

Average throughput: 110.2MiB/s

[train] downloading 336/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120527_1312_HARP1688_NOAA11488.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120527_1312_HARP1688_NOAA11488.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e0989efa09afd55e0a3b455b07bbd639.npz

.

Average throughput: 119.0MiB/s

[train] downloading 337/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130819_0424_HARP3068_NOAA11825.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130819_0424_HARP3068_NOAA11825.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/37603cdec5c88587142f480af3cd7503.npz

.

Average throughput: 160.8MiB/s

[train] downloading 338/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130105_0324_HARP2338_NOAA11641.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130105_0324_HARP2338_NOAA11641.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/203a326c711c9004fc030a646cb7df12.npz

.

Average throughput: 123.8MiB/s

[train] downloading 339/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120529_1036_HARP1690_NOAA11489.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120529_1036_HARP1690_NOAA11489.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/03d026825d2e4761d892a39598e9bd17.npz

.

Average throughput: 96.2MiB/s

[train] downloading 340/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110606_1748_HARP651_NOAA11231.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110606_1748_HARP651_NOAA11231.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/63e3b75f8eb8d9dc653d8bae67d09119.npz

.

Average throughput: 95.5MiB/s

[train] downloading 341/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110331_0124_HARP437_NOAA11176.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110331_0124_HARP437_NOAA11176.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/51552545d3209926fb153c09d772db7e.npz

.

Average throughput: 84.8MiB/s

[train] downloading 342/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120614_1236_HARP1756_NOAA11506.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120614_1236_HARP1756_NOAA11506.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/673ac0857d903ad4883f86e68bfaefb9.npz

.

Average throughput: 89.2MiB/s

[train] downloading 343/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130719_0312_HARP2966_NOAA11797.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130719_0312_HARP2966_NOAA11797.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e5e306c4e1afdd24295c7f2e6fe9d188.npz

.

Average throughput: 180.2MiB/s

[train] downloading 344/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130103_1248_HARP2329_NOAA11639.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130103_1248_HARP2329_NOAA11639.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4afdc3a925a2a5f649465907019bbcd8.npz

.

Average throughput: 107.1MiB/s

[train] downloading 345/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130602_2136_HARP2809_NOAA11760.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130602_2136_HARP2809_NOAA11760.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/979ae8858f157fa1c4500e24368afb1c.npz

.

Average throughput: 162.0MiB/s

[train] downloading 346/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120101_0148_HARP1256_NOAA11388.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120101_0148_HARP1256_NOAA11388.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/16947085669d83f5eb3b31e4a9cc5b7c.npz

.

Average throughput: 88.0MiB/s

[train] downloading 347/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110504_0000_HARP572_NOAA11206.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110504_0000_HARP572_NOAA11206.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5fc562610628237ed9ffff6694eb7939.npz

.

Average throughput: 123.4MiB/s

[train] downloading 348/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130731_1900_HARP3012_NOAA11806.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130731_1900_HARP3012_NOAA11806.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b289d1460676d1d5ec437201aaf9feba.npz

.

Average throughput: 91.4MiB/s

[train] downloading 349/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121118_0724_HARP2191_NOAA11613.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121118_0724_HARP2191_NOAA11613.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1a6e80b9cf21f6b4d75349dc05327041.npz

.

Average throughput: 158.0MiB/s

[train] downloading 350/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110605_2200_HARP639_NOAA11228.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110605_2200_HARP639_NOAA11228.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4630163bb5ed3bb68fd8e8e313966e9a.npz

.

Average throughput: 69.0MiB/s

[train] downloading 351/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110731_0100_HARP750_NOAA11261.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110731_0100_HARP750_NOAA11261.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/96f927c26c55268898ad2d6db7a3dcab.npz

.

Average throughput: 93.6MiB/s

[train] downloading 352/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131011_1512_HARP3258_NOAA11861.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131011_1512_HARP3258_NOAA11861.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8cba17bad2c74d3e1119ed4dcafd1aa8.npz

.

Average throughput: 101.9MiB/s

[train] downloading 353/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131106_0500_HARP3336_NOAA11889.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131106_0500_HARP3336_NOAA11889.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e62e2344d33eba55b207fe3e1463b88e.npz

.

Average throughput: 55.3MiB/s

[train] downloading 354/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101024_1512_HARP223_NOAA11118.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101024_1512_HARP223_NOAA11118.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a8c6895b043b5a8384f623c2d33b866f.npz

.

Average throughput: 119.2MiB/s

[train] downloading 355/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120324_1448_HARP1497_NOAA11446.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120324_1448_HARP1497_NOAA11446.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8f42c5caea917125f7fab1889b76369c.npz



Average throughput: 173.6MiB/s

[train] downloading 356/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120906_1848_HARP2017_NOAA11568.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120906_1848_HARP2017_NOAA11568.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/51f3f9ee915d779633963adeb472f788.npz

.

Average throughput: 110.7MiB/s

[train] downloading 357/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130331_2112_HARP2599_NOAA11710.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130331_2112_HARP2599_NOAA11710.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0f04e2c521a63e6e5d482bacf030985f.npz

.

Average throughput: 44.8MiB/s

[train] downloading 358/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131212_1124_HARP3474_NOAA11927.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131212_1124_HARP3474_NOAA11927.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0aec8866ddadec61904dd774807ca9b5.npz

.

Average throughput: 88.3MiB/s

[train] downloading 359/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130930_1012_HARP3244_NOAA11855.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130930_1012_HARP3244_NOAA11855.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f58bbd612d44eb89a77cc3cfeb14f20a.npz

.

Average throughput: 179.9MiB/s

[train] downloading 360/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110703_0212_HARP685_NOAA11243.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110703_0212_HARP685_NOAA11243.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4db698b81e16df8a7babbe7e20d58737.npz

.

Average throughput: 48.0MiB/s

[train] downloading 361/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130814_1912_HARP3079_NOAA11821.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130814_1912_HARP3079_NOAA11821.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a52bd16ee2c6ffab94d355b56377a320.npz

.

Average throughput: 155.8MiB/s

[train] downloading 362/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111009_1324_HARP918_NOAA11309.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111009_1324_HARP918_NOAA11309.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5f91c16fdc41c2d5505b6e83095f8b33.npz

.

Average throughput: 138.3MiB/s

[train] downloading 363/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110716_0512_HARP712_NOAA11250.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110716_0512_HARP712_NOAA11250.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ea193e2131e7d2a8679ee31d364b2b78.npz

.

Average throughput: 94.6MiB/s

[train] downloading 364/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110105_0112_HARP321_NOAA11139.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110105_0112_HARP321_NOAA11139.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a4d6611e54e44e43e056abbb83adc031.npz

.

Average throughput: 140.7MiB/s

[train] downloading 365/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130225_1000_HARP2493_NOAA11677.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130225_1000_HARP2493_NOAA11677.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f049fdd60d112ea50c8917d5209bc986.npz

.

Average throughput: 146.7MiB/s

[train] downloading 366/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110524_0136_HARP605_NOAA11216.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110524_0136_HARP605_NOAA11216.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1b657765c72cd6d3ec1e9e5d1909e9fd.npz

.

Average throughput: 83.2MiB/s

[train] downloading 367/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131219_1212_HARP3515_NOAA11930.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131219_1212_HARP3515_NOAA11930.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a694239933b07450e611f9c993f5cf62.npz

.

Average throughput: 71.6MiB/s

[train] downloading 368/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110908_0436_HARP843_NOAA11287.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110908_0436_HARP843_NOAA11287.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6dabdc945c93bb043b794d52cbe9ae69.npz

.

Average throughput: 113.8MiB/s

[train] downloading 369/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110425_0500_HARP514_NOAA11195.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110425_0500_HARP514_NOAA11195.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/512bd0622500fa316e282f9a485109e9.npz

.

Average throughput: 86.2MiB/s

[train] downloading 370/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131112_0712_HARP3353_NOAA11892.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131112_0712_HARP3353_NOAA11892.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d6ea20de8ce53827112d719a03a7832d.npz

.

Average throughput: 188.4MiB/s

[train] downloading 371/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120114_2336_HARP1309_NOAA11396.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120114_2336_HARP1309_NOAA11396.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/46b4b44f854007233cc91543c38c6d2f.npz

.

Average throughput: 191.9MiB/s

[train] downloading 372/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110126_2336_HARP354_NOAA11151.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110126_2336_HARP354_NOAA11151.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/11df493d24cd56c15718ab9ac6b4bc90.npz

..

Average throughput: 86.5MiB/s

[train] downloading 373/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130724_0048_HARP2984_NOAA11799.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130724_0048_HARP2984_NOAA11799.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/87eb7635ea7cfb75f26cac89d03ec241.npz

.

Average throughput: 174.7MiB/s

[train] downloading 374/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130730_0948_HARP3011_NOAA11812.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130730_0948_HARP3011_NOAA11812.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0556825d5e1d34c585b0bff3b51f4a89.npz

.

Average throughput: 121.7MiB/s

[train] downloading 375/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130628_0348_HARP2898_NOAA11779.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130628_0348_HARP2898_NOAA11779.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/52d2583888c0296b920ccff7f3c8fa9d.npz

.

Average throughput: 144.6MiB/s

[train] downloading 376/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120222_1624_HARP1410_NOAA11421.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120222_1624_HARP1410_NOAA11421.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8e40b0468c86da5c0ede1f5ee170024e.npz

.

Average throughput: 112.7MiB/s

[train] downloading 377/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110509_0000_HARP589_NOAA11209.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110509_0000_HARP589_NOAA11209.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7b0fbc72911392f2285e1f9dfe265e49.npz

.

Average throughput: 65.9MiB/s

[train] downloading 378/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111008_2300_HARP918_NOAA11309.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111008_2300_HARP918_NOAA11309.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7df5212bfef2aefb02b090825aaae922.npz

..

Average throughput: 164.2MiB/s

[train] downloading 379/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131115_1212_HARP3364_NOAA11893.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131115_1212_HARP3364_NOAA11893.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/02500c1ce222d7916f899db6f7c533b7.npz

.

Average throughput: 61.3MiB/s

[train] downloading 380/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131231_0912_HARP3542_NOAA11937.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131231_0912_HARP3542_NOAA11937.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/75c2927a3d69b0ff7193b8b7eb2f205f.npz

.

Average throughput: 112.5MiB/s

[train] downloading 381/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100626_0536_HARP67_NOAA11085.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100626_0536_HARP67_NOAA11085.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/776df650217f13d4df26fd189d4af264.npz

.

Average throughput: 109.2MiB/s

[train] downloading 382/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131129_2136_HARP3415_NOAA11906.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131129_2136_HARP3415_NOAA11906.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/89bb792eafbc01578469348a88667cf3.npz

.

Average throughput: 181.5MiB/s

[train] downloading 383/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120823_1448_HARP1942_NOAA11546.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120823_1448_HARP1942_NOAA11546.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/804455cf4a13a3302e97283435508a9f.npz

.

Average throughput: 69.3MiB/s

[train] downloading 384/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110718_1712_HARP714_NOAA11251.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110718_1712_HARP714_NOAA11251.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4a95dc529fac6cc17f70f610c9feb824.npz

.

Average throughput: 56.6MiB/s

[train] downloading 385/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130723_2348_HARP2981_NOAA11799.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130723_2348_HARP2981_NOAA11799.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/bde0c6a5e248f0e2fa64e33afff2e1ad.npz



Average throughput: 164.5MiB/s

[train] downloading 386/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121018_0148_HARP2121_NOAA11591.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121018_0148_HARP2121_NOAA11591.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ade320ae5ded97f7ecb05340aba5cbdb.npz

.

Average throughput: 103.0MiB/s

[train] downloading 387/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120109_1000_HARP1278_NOAA11391.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120109_1000_HARP1278_NOAA11391.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/22646464c415f127d234abb3087c8dd3.npz

.

Average throughput: 113.4MiB/s

[train] downloading 388/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130630_0200_HARP2887_NOAA11778.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130630_0200_HARP2887_NOAA11778.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/23718f1fff1247da2d9df65de8864069.npz

.

Average throughput: 181.4MiB/s

[train] downloading 389/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131201_0348_HARP3443_NOAA11914.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131201_0348_HARP3443_NOAA11914.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ca152928ace3e012e3d14652e7383f69.npz

.

Average throughput: 171.1MiB/s

[train] downloading 390/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131106_2024_HARP3344_NOAA11891.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131106_2024_HARP3344_NOAA11891.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f9c76b8d886d509b62cbe8fba3726009.npz

.

Average throughput: 67.7MiB/s

[train] downloading 391/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111103_1912_HARP1019_NOAA11336.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111103_1912_HARP1019_NOAA11336.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/73bc87ef24d8cd4ee7f2ab48e1cfd50b.npz

.

Average throughput: 85.5MiB/s

[train] downloading 392/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130405_1336_HARP2597_NOAA11713.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130405_1336_HARP2597_NOAA11713.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8549ad9cd2fca17d49eacf1f55fd1e15.npz

.

Average throughput: 99.4MiB/s

[train] downloading 393/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110205_0936_HARP362_NOAA11153.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110205_0936_HARP362_NOAA11153.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/28266af32756ca4b3cc38884b96b501e.npz

.

Average throughput: 65.3MiB/s

[train] downloading 394/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130110_0236_HARP2358_NOAA11649.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130110_0236_HARP2358_NOAA11649.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6b2a46edcd5f69e0b21c2543544daf68.npz

.

Average throughput: 147.1MiB/s

[train] downloading 395/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130404_1548_HARP2605_NOAA11711.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130404_1548_HARP2605_NOAA11711.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3f0ff9488edcdcd23f629a850ed66612.npz

.

Average throughput: 70.2MiB/s

[train] downloading 396/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100829_1936_HARP146_NOAA11102.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100829_1936_HARP146_NOAA11102.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d009ca99c0d7f56edfbb0a5eeeaa7036.npz

.

Average throughput: 206.8MiB/s

[train] downloading 397/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111206_1112_HARP1124_NOAA11363.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111206_1112_HARP1124_NOAA11363.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3b006248831cf7219184dc0b58789265.npz

.

Average throughput: 72.6MiB/s

[train] downloading 398/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120210_1712_HARP1389_NOAA11416.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120210_1712_HARP1389_NOAA11416.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9ec932aee24ec2b61190832ac3a1bc1e.npz

.

Average throughput: 147.9MiB/s

[train] downloading 399/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110516_2136_HARP595_NOAA11212.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110516_2136_HARP595_NOAA11212.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ff27d97ea2d96f24028b0b4a89670f67.npz



Average throughput: 191.1MiB/s

[train] downloading 400/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120821_1300_HARP1943_NOAA11547.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120821_1300_HARP1943_NOAA11547.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/784e53ebff9fffdbb54dd4f7b96092df.npz

.

Average throughput: 37.7MiB/s

[train] cached/checked 400/1650 files | elapsed 10.3 min
[train] downloading 401/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111119_1036_HARP1090_NOAA11359.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111119_1036_HARP1090_NOAA11359.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5055458db5b9af252fd6aff0739c710b.npz

.

Average throughput: 136.6MiB/s

[train] downloading 402/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120507_0036_HARP1632_NOAA11474.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120507_0036_HARP1632_NOAA11474.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f3acf65f15662cee88b9dfbb9076d83b.npz



Average throughput: 206.3MiB/s

[train] downloading 403/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130227_1124_HARP2501_NOAA11682.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130227_1124_HARP2501_NOAA11682.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/923a2d3bdcd023b20bacd02188ae020b.npz

.

Average throughput: 140.8MiB/s

[train] downloading 404/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120528_1836_HARP1697_NOAA11489.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120528_1836_HARP1697_NOAA11489.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/65a1c0c91fc74a144b46ad80fd631e6d.npz

.

Average throughput: 168.2MiB/s

[train] downloading 405/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111112_1748_HARP1038_NOAA11340.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111112_1748_HARP1038_NOAA11340.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/232bebdedbe610c0dd2b44065e9206e3.npz

.

Average throughput: 207.4MiB/s

[train] downloading 406/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120429_0336_HARP1613_NOAA11467.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120429_0336_HARP1613_NOAA11467.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4c7f061e4a14e6b9c8bfdddddbaec63a.npz

.

Average throughput: 184.0MiB/s

[train] downloading 407/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110215_0612_HARP371_NOAA11159.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110215_0612_HARP371_NOAA11159.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/561f03411a95a99c63d56d16d92a523e.npz



Average throughput: 138.4MiB/s

[train] downloading 408/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110105_0836_HARP323_NOAA11140.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110105_0836_HARP323_NOAA11140.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cbd5f0946f5d73fbf3819fa3d03e8f40.npz

.

Average throughput: 126.5MiB/s

[train] downloading 409/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130110_2012_HARP2358_NOAA11649.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130110_2012_HARP2358_NOAA11649.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/80f0d3528357af118e5373f444eda003.npz

.

Average throughput: 66.1MiB/s

[train] downloading 410/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101018_1124_HARP221_NOAA11116.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101018_1124_HARP221_NOAA11116.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/959824a19f27deadba312d49554da2f2.npz

.

Average throughput: 92.6MiB/s

[train] downloading 411/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100817_1624_HARP128_NOAA11097.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100817_1624_HARP128_NOAA11097.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d62c8add193e89486f5e4ef3df14cf16.npz

.

Average throughput: 114.4MiB/s

[train] downloading 412/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110828_0700_HARP805_NOAA11275.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110828_0700_HARP805_NOAA11275.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ccc3ce13380bf221bab97b723f24b23f.npz

.

Average throughput: 56.6MiB/s

[train] downloading 413/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110330_0600_HARP437_NOAA11176.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110330_0600_HARP437_NOAA11176.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a74fc1fb28dfd3226c57d8b4127649a4.npz

.

Average throughput: 75.5MiB/s

[train] downloading 414/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130619_2124_HARP2875_NOAA11776.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130619_2124_HARP2875_NOAA11776.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6390bba06ebd4751d28d38a503c258cc.npz

.

Average throughput: 106.3MiB/s

[train] downloading 415/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110712_0848_HARP700_NOAA11245.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110712_0848_HARP700_NOAA11245.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ed8ad7d57487fd6c17e37ec85ee5d172.npz

.

Average throughput: 135.8MiB/s

[train] downloading 416/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120812_0436_HARP1930_NOAA11542.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120812_0436_HARP1930_NOAA11542.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/44319f72bbc54cc862ef6145fcea7d0b.npz

.

Average throughput: 139.8MiB/s

[train] downloading 417/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120826_0848_HARP1959_NOAA11553.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120826_0848_HARP1959_NOAA11553.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/16df721fb52a150130ea25b5bc1769a4.npz

.

Average throughput: 90.3MiB/s

[train] downloading 418/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120317_0236_HARP1464_NOAA11434.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120317_0236_HARP1464_NOAA11434.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4f38e82edbd4b70e10dc4ab8f58b5bbd.npz

.

Average throughput: 119.7MiB/s

[train] downloading 419/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110711_0136_HARP702_NOAA11249.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110711_0136_HARP702_NOAA11249.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6e097877af3f5a38d51764468ce59093.npz

.

Average throughput: 127.7MiB/s

[train] downloading 420/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121127_1836_HARP2249_NOAA11624.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121127_1836_HARP2249_NOAA11624.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6302e8821864b358bed295dcc91027de.npz

.

Average throughput: 80.8MiB/s

[train] downloading 421/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120524_1536_HARP1677_NOAA11486.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120524_1536_HARP1677_NOAA11486.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f40d0905d246264196558dd41dfe8646.npz

.

Average throughput: 39.1MiB/s

[train] downloading 422/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131015_0412_HARP3263_NOAA11861.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131015_0412_HARP3263_NOAA11861.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3f1e77d8fea8a0d940b32b3d9b9bdda9.npz

.

Average throughput: 120.8MiB/s

[train] downloading 423/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120715_2312_HARP1863_NOAA11523.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120715_2312_HARP1863_NOAA11523.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cddb07ea6b1b93a8f6d5a478a658c78f.npz



Average throughput: 173.8MiB/s

[train] downloading 424/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110605_1112_HARP637_NOAA11226.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110605_1112_HARP637_NOAA11226.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/04ad274a94fab2c6476aca82f8fbda32.npz

.

Average throughput: 89.9MiB/s

[train] downloading 425/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120418_0648_HARP1578_NOAA11460.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120418_0648_HARP1578_NOAA11460.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b881f3fa6fd8778343a1facafeedd503.npz

.

Average throughput: 74.3MiB/s

[train] downloading 426/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110412_0200_HARP495_NOAA11190.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110412_0200_HARP495_NOAA11190.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/33f9c71459e6376c7b0b3ed731cfb60b.npz

.

Average throughput: 155.4MiB/s

[train] downloading 427/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110828_0900_HARP817_NOAA11285.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110828_0900_HARP817_NOAA11285.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4b18f7bcee48699b9ce5ec3c04660714.npz

.

Average throughput: 184.6MiB/s

[train] downloading 428/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120507_2124_HARP1632_NOAA11474.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120507_2124_HARP1632_NOAA11474.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b504e3b9a18c58ba0393bdbe0029e118.npz

.

Average throughput: 206.6MiB/s

[train] downloading 429/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100809_0836_HARP116_NOAA11096.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100809_0836_HARP116_NOAA11096.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c8e1616a862d49e25527af89a5d2f628.npz

.

Average throughput: 105.6MiB/s

[train] downloading 430/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131203_1248_HARP3461_NOAA11915.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131203_1248_HARP3461_NOAA11915.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ba65b40ddafd914bed0a7868ccfbf605.npz

.

Average throughput: 55.3MiB/s

[train] downloading 431/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101210_0648_HARP284_NOAA11133.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101210_0648_HARP284_NOAA11133.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7d2f0cf1109f5b3bb9fa3498f203dd41.npz

.

Average throughput: 69.4MiB/s

[train] downloading 432/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111010_0948_HARP927_NOAA11312.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111010_0948_HARP927_NOAA11312.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9def7604cb6ac1143bef327fc2518c10.npz

.

Average throughput: 89.6MiB/s

[train] downloading 433/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120127_2000_HARP1339_NOAA11412.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120127_2000_HARP1339_NOAA11412.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4e42368fb93dac024cb2bf1796374d4c.npz

.

Average throughput: 134.6MiB/s

[train] downloading 434/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120118_1112_HARP1312_NOAA11397.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120118_1112_HARP1312_NOAA11397.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3056f958dcd1d7cfad4d25ac9f648a63.npz

.

Average throughput: 167.6MiB/s

[train] downloading 435/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110516_1024_HARP595_NOAA11212.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110516_1024_HARP595_NOAA11212.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c14e94ee82293b10a995765c26955f57.npz

.

Average throughput: 187.3MiB/s

[train] downloading 436/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130525_1012_HARP2760_NOAA11753.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130525_1012_HARP2760_NOAA11753.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e9db09120f44cf835544258202a18c14.npz

.

Average throughput: 96.1MiB/s

[train] downloading 437/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120622_1048_HARP1783_NOAA11510.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120622_1048_HARP1783_NOAA11510.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/19b591a836374f0e476ec6d38d2b692c.npz

.

Average throughput: 41.2MiB/s

[train] downloading 438/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120605_0648_HARP1727_NOAA11497.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120605_0648_HARP1727_NOAA11497.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/41906e9f6ae6bc76d5c14449d9dabc6b.npz

.

Average throughput: 73.1MiB/s

[train] downloading 439/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131014_0712_HARP3258_NOAA11861.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131014_0712_HARP3258_NOAA11861.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ea12bd9f36868f418ad3a54e91d3a4ba.npz

.

Average throughput: 59.7MiB/s

[train] downloading 440/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110912_2148_HARP851_NOAA11291.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110912_2148_HARP851_NOAA11291.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f2c29ae552586adb956d0e93263cd2f6.npz

.

Average throughput: 112.0MiB/s

[train] downloading 441/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131217_2348_HARP3483_NOAA11920.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131217_2348_HARP3483_NOAA11920.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/250e2ebeb7286426d34949f95b5dbdac.npz

.

Average throughput: 81.4MiB/s

[train] downloading 442/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110211_0924_HARP364_NOAA11157.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110211_0924_HARP364_NOAA11157.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/62c2c854270825c639084a6792a8a078.npz

.

Average throughput: 62.6MiB/s

[train] downloading 443/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120901_2348_HARP1990_NOAA11562.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120901_2348_HARP1990_NOAA11562.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e8cffe392d4e7001ffea70d7b3319ae7.npz

.

Average throughput: 134.0MiB/s

[train] downloading 444/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130706_0912_HARP2922_NOAA11784.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130706_0912_HARP2922_NOAA11784.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6d0dd6f1728a64274da533445d8cfc74.npz

.

Average throughput: 180.8MiB/s

[train] downloading 445/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110430_1212_HARP538_NOAA11200.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110430_1212_HARP538_NOAA11200.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/dfcb0368252bb3a870df589ac9735d70.npz

.

Average throughput: 116.7MiB/s

[train] downloading 446/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130201_1836_HARP2436_NOAA11668.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130201_1836_HARP2436_NOAA11668.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7d6af2e8adc200ec8067eef9ac18db62.npz

.

Average throughput: 149.7MiB/s

[train] downloading 447/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120916_0112_HARP2026_NOAA11569.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120916_0112_HARP2026_NOAA11569.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/dbaa68a64cdd7413e26020475a65f215.npz

.

Average throughput: 170.4MiB/s

[train] downloading 448/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130923_0000_HARP3188_NOAA11853.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130923_0000_HARP3188_NOAA11853.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3d11fc96703349aaaea8d218ba27715c.npz

.

Average throughput: 152.6MiB/s

[train] downloading 449/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121029_1948_HARP2143_NOAA11599.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121029_1948_HARP2143_NOAA11599.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/83cfba702881fa6d03424d11dd906ec5.npz

.

Average throughput: 67.2MiB/s

[train] downloading 450/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120423_2048_HARP1582_NOAA11461.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120423_2048_HARP1582_NOAA11461.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7e6f7a854afd79365458a1c48246dea3.npz

.

Average throughput: 115.6MiB/s

[train] downloading 451/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120818_0500_HARP1943_NOAA11547.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120818_0500_HARP1943_NOAA11547.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/10fed7f32c906d7c7ccac24aa535b7b9.npz

.

Average throughput: 165.9MiB/s

[train] downloading 452/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110703_0700_HARP685_NOAA11243.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110703_0700_HARP685_NOAA11243.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9456d97ebc88196095b5167691744f7e.npz

.

Average throughput: 120.6MiB/s

[train] downloading 453/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110712_1912_HARP702_NOAA11249.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110712_1912_HARP702_NOAA11249.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/bc3a918d8d87ea046fc52a38bc674c15.npz

.

Average throughput: 164.4MiB/s

[train] downloading 454/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110705_2000_HARP693_NOAA11246.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110705_2000_HARP693_NOAA11246.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c58cb710ba04d13c72164db7cd9bae2c.npz

.

Average throughput: 192.6MiB/s

[train] downloading 455/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110317_0536_HARP431_NOAA11174.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110317_0536_HARP431_NOAA11174.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/000513cffed961998a945c9a89f9926e.npz

.

Average throughput: 123.1MiB/s

[train] downloading 456/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101219_2348_HARP297_NOAA11135.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101219_2348_HARP297_NOAA11135.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a8077a9865699e579365753db08bf843.npz

.

Average throughput: 164.4MiB/s

[train] downloading 457/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130103_1424_HARP2329_NOAA11639.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130103_1424_HARP2329_NOAA11639.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d05b19bfabb01f01af50ae543063b62b.npz

.

Average throughput: 189.4MiB/s

[train] downloading 458/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120116_2224_HARP1312_NOAA11397.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120116_2224_HARP1312_NOAA11397.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/79a371b51b90803c39dd97bebbdb35ff.npz

.

Average throughput: 81.0MiB/s

[train] downloading 459/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100930_0336_HARP187_NOAA11109.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100930_0336_HARP187_NOAA11109.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1d4e599d1cd82cfc8be7a40cbdbb3f2b.npz

.

Average throughput: 77.8MiB/s

[train] downloading 460/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120503_1700_HARP1628_NOAA11472.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120503_1700_HARP1628_NOAA11472.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9580c8447aed26a552d98f590d087f4a.npz

.

Average throughput: 41.1MiB/s

[train] downloading 461/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120128_0312_HARP1348_NOAA11411.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120128_0312_HARP1348_NOAA11411.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/108b827eef633b23b3264a1b573a9260.npz

.

Average throughput: 115.7MiB/s

[train] downloading 462/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110312_0024_HARP415_NOAA11171.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110312_0024_HARP415_NOAA11171.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fc79e40d058bf9f86c35864e480bd06d.npz

.

Average throughput: 120.3MiB/s

[train] downloading 463/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130724_1936_HARP2984_NOAA11799.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130724_1936_HARP2984_NOAA11799.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d47671eeb1c4dc97fb6e4c5ccc55daf9.npz

..

Average throughput: 50.7MiB/s

[train] downloading 464/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110901_1324_HARP814_NOAA11277.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110901_1324_HARP814_NOAA11277.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/96560313651ec6122e945b005df2ac9b.npz

.

Average throughput: 65.7MiB/s

[train] downloading 465/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120924_0424_HARP2040_NOAA11575.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120924_0424_HARP2040_NOAA11575.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8d4ffe0cae0bc1782d97b37a43449a1c.npz

.

Average throughput: 138.6MiB/s

[train] downloading 466/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121221_2012_HARP2306_NOAA11633.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121221_2012_HARP2306_NOAA11633.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/be90ae208f963cdf5de6c62cc00d2460.npz

.

Average throughput: 100.1MiB/s

[train] downloading 467/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111021_2100_HARP975_NOAA11321.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111021_2100_HARP975_NOAA11321.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7c5336c5dd912e4281ff109d427e68b5.npz



Average throughput: 148.5MiB/s

[train] downloading 468/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131205_1848_HARP3437_NOAA11909.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131205_1848_HARP3437_NOAA11909.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/525698fc7b6802a6610ca80a6e6a112d.npz



Average throughput: 156.9MiB/s

[train] downloading 469/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120815_0136_HARP1931_NOAA11543.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120815_0136_HARP1931_NOAA11543.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4ebdd662aa4b518a0e2751d1be2aa819.npz

.

Average throughput: 98.8MiB/s

[train] downloading 470/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110723_1012_HARP740_NOAA11259.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110723_1012_HARP740_NOAA11259.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/01e077d002a3672a56d56965cd26ed5a.npz

.

Average throughput: 76.3MiB/s

[train] downloading 471/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121102_2224_HARP2169_NOAA11603.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121102_2224_HARP2169_NOAA11603.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2b301b5004341d7218b170968f302a3a.npz

.

Average throughput: 182.5MiB/s

[train] downloading 472/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120523_0736_HARP1677_NOAA11486.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120523_0736_HARP1677_NOAA11486.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/204028d6351a31d71263d9c91719e813.npz

.

Average throughput: 108.9MiB/s

[train] downloading 473/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120416_1212_HARP1569_NOAA11457.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120416_1212_HARP1569_NOAA11457.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0fe2031a63bcb953a70d898cafa1b9bb.npz

.

Average throughput: 81.2MiB/s

[train] downloading 474/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131103_0948_HARP3336_NOAA11889.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131103_0948_HARP3336_NOAA11889.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/30bd2b749a51fb4b23822b41af20ef25.npz

.

Average throughput: 149.1MiB/s

[train] downloading 475/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130525_0524_HARP2760_NOAA11753.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130525_0524_HARP2760_NOAA11753.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1c2863de1e56b5bc16dbfdef741e3d22.npz

.

Average throughput: 80.5MiB/s

[train] downloading 476/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130107_0024_HARP2344_NOAA11644.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130107_0024_HARP2344_NOAA11644.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/db80f63f3ebd89acbc791107ff84e3c7.npz

.

Average throughput: 164.1MiB/s

[train] downloading 477/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120522_0748_HARP1669_NOAA11485.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120522_0748_HARP1669_NOAA11485.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/aa337f115e35e27a4c198b13db9d65e7.npz

.

Average throughput: 77.0MiB/s

[train] downloading 478/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110803_0348_HARP753_NOAA11263.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110803_0348_HARP753_NOAA11263.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6928644702399ed2d6a91cef8c594ef2.npz

.

Average throughput: 73.8MiB/s

[train] downloading 479/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121002_0624_HARP2061_NOAA11580.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121002_0624_HARP2061_NOAA11580.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fd6014a0f55212e465843ebab52e5090.npz



Average throughput: 204.9MiB/s

[train] downloading 480/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131116_0612_HARP3368_NOAA11896.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131116_0612_HARP3368_NOAA11896.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6c2e68301c455197964c8994864971f6.npz

.

Average throughput: 112.2MiB/s

[train] downloading 481/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101107_0548_HARP241_NOAA11120.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101107_0548_HARP241_NOAA11120.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/08e5dfd385b02e1eb9708d454b06b649.npz

.

Average throughput: 173.8MiB/s

[train] downloading 482/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110828_2024_HARP812_NOAA11280.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110828_2024_HARP812_NOAA11280.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8730e7212be769f69c1cd2efb4b05812.npz

.

Average throughput: 64.2MiB/s

[train] downloading 483/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111017_0148_HARP948_NOAA11317.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111017_0148_HARP948_NOAA11317.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/994e2961fc6532dcc45627a6eb12da9c.npz

.

Average throughput: 134.8MiB/s

[train] downloading 484/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120228_1524_HARP1425_NOAA11424.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120228_1524_HARP1425_NOAA11424.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/10eca0ce5cd5e715286ff5d051b12d26.npz

.

Average throughput: 183.0MiB/s

[train] downloading 485/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111206_2048_HARP1124_NOAA11363.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111206_2048_HARP1124_NOAA11363.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/49a963a70477edae577e19146615c164.npz

.

Average throughput: 134.5MiB/s

[train] downloading 486/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130603_1336_HARP2809_NOAA11760.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130603_1336_HARP2809_NOAA11760.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c0582edacca3e4091ec77e181c495943.npz

.

Average throughput: 175.6MiB/s

[train] downloading 487/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110213_1048_HARP377_NOAA11158.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110213_1048_HARP377_NOAA11158.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b5674bb19f5061ad7104ff358953c2ee.npz

.

Average throughput: 73.7MiB/s

[train] downloading 488/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121222_1948_HARP2314_NOAA11635.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121222_1948_HARP2314_NOAA11635.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/880946680f9078badad6ef09f4527397.npz

.

Average throughput: 100.2MiB/s

[train] downloading 489/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130608_2248_HARP2832_NOAA11768.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130608_2248_HARP2832_NOAA11768.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/602e19f829e64c427b8fedb8c479ba8f.npz

.

Average throughput: 93.8MiB/s

[train] downloading 490/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131203_2200_HARP3448_NOAA11916.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131203_2200_HARP3448_NOAA11916.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c2cf26de188804eb5bce4b2b2bf49c0c.npz

.

Average throughput: 163.9MiB/s

[train] downloading 491/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120804_2000_HARP1908_NOAA11537.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120804_2000_HARP1908_NOAA11537.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/81664132464aa3b20c8b899f61641677.npz

.

Average throughput: 72.5MiB/s

[train] downloading 492/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111215_0548_HARP1168_NOAA11374.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111215_0548_HARP1168_NOAA11374.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ac5ea4a17fada8bf1c5a162beb131e6e.npz

.

Average throughput: 103.4MiB/s

[train] downloading 493/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120307_0824_HARP1447_NOAA11428.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120307_0824_HARP1447_NOAA11428.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a16212b300a14370d59e49224fea8965.npz

.

Average throughput: 107.8MiB/s

[train] downloading 494/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111108_2036_HARP1038_NOAA11340.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111108_2036_HARP1038_NOAA11340.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/350b8e0fc542b3039d18139b11b2d9f4.npz

.

Average throughput: 173.1MiB/s

[train] downloading 495/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120314_1324_HARP1471_NOAA11435.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120314_1324_HARP1471_NOAA11435.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/88dea01c55dbbb45c91dd40cb82a3363.npz

.

Average throughput: 168.9MiB/s

[train] downloading 496/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130502_0836_HARP2693_NOAA11731.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130502_0836_HARP2693_NOAA11731.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/04cd60186c408aca0f710baa584b2344.npz

.

Average throughput: 79.7MiB/s

[train] downloading 497/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130516_0324_HARP2733_NOAA11742.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130516_0324_HARP2733_NOAA11742.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7a2a85ef3bee9686af7008de50675ff6.npz

.

Average throughput: 185.5MiB/s

[train] downloading 498/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110418_1948_HARP504_NOAA11191.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110418_1948_HARP504_NOAA11191.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/97cbfd6c68feb3bf157f017fb9e40a89.npz

.

Average throughput: 58.2MiB/s

[train] downloading 499/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120627_1800_HARP1795_NOAA11512.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120627_1800_HARP1795_NOAA11512.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/406637b49779a364cc64ad1d52cab39b.npz



Average throughput: 177.3MiB/s

[train] downloading 500/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120925_0436_HARP2040_NOAA11575.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120925_0436_HARP2040_NOAA11575.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4e46a4e6a0738a4e1976c35b62db0ff7.npz

.

Average throughput: 122.3MiB/s

[train] cached/checked 500/1650 files | elapsed 12.8 min
[train] downloading 501/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130112_0236_HARP2358_NOAA11649.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130112_0236_HARP2358_NOAA11649.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0422420d671622f760495314668fde7c.npz

.

Average throughput: 166.2MiB/s

[train] downloading 502/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100830_0748_HARP147_NOAA11104.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100830_0748_HARP147_NOAA11104.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/eba6fa9869e445955669e53842a58b91.npz

.

Average throughput: 94.8MiB/s

[train] downloading 503/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121006_0136_HARP2098_NOAA11585.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121006_0136_HARP2098_NOAA11585.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c31be1bf0da33d9b8582e6e9745f3e53.npz

.

Average throughput: 183.5MiB/s

[train] downloading 504/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121201_1300_HARP2240_NOAA11621.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121201_1300_HARP2240_NOAA11621.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e72fb2bf4635cd30c856c622010f5b46.npz

.

Average throughput: 176.1MiB/s

[train] downloading 505/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130422_0912_HARP2673_NOAA11726.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130422_0912_HARP2673_NOAA11726.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7d6d291ad81434408cd7561ac3d030ac.npz

.

Average throughput: 105.7MiB/s

[train] downloading 506/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131213_0624_HARP3481_NOAA11923.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131213_0624_HARP3481_NOAA11923.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5dcaae4c05d3183faad691a3eb224294.npz

.

Average throughput: 123.0MiB/s

[train] downloading 507/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121024_1536_HARP2144_NOAA11600.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121024_1536_HARP2144_NOAA11600.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/18b5792ee3bfe9860fbdd9677f286573.npz

.

Average throughput: 78.8MiB/s

[train] downloading 508/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111029_1112_HARP997_NOAA11330.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111029_1112_HARP997_NOAA11330.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c746fd5f0749a792451fd2c355a9355b.npz

.

Average throughput: 164.7MiB/s

[train] downloading 509/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111015_2136_HARP940_NOAA11314.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111015_2136_HARP940_NOAA11314.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2249038c9b8601eed8227192ed010725.npz

.

Average throughput: 113.1MiB/s

[train] downloading 510/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110307_2212_HARP403_NOAA11167.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110307_2212_HARP403_NOAA11167.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a6ee44ac07ea8f0301de8c7723486dc6.npz

.

Average throughput: 160.3MiB/s

[train] downloading 511/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131006_0536_HARP3247_NOAA11857.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131006_0536_HARP3247_NOAA11857.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8377f183e4ffca6c9ebf60a6ab241c99.npz

.

Average throughput: 44.6MiB/s

[train] downloading 512/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111122_0012_HARP1079_NOAA11350.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111122_0012_HARP1079_NOAA11350.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ed52962add04f2f6cdd96b723f9fb523.npz

.

Average throughput: 194.0MiB/s

[train] downloading 513/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110726_1900_HARP748_NOAA11265.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110726_1900_HARP748_NOAA11265.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a31feaecb89ce4e7190e780627a019c5.npz

.

Average throughput: 130.9MiB/s

[train] downloading 514/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130403_0148_HARP2597_NOAA11713.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130403_0148_HARP2597_NOAA11713.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1b97b790ff163f61b9d6b528a033c899.npz

.

Average throughput: 95.5MiB/s

[train] downloading 515/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101027_0024_HARP226_NOAA11117.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101027_0024_HARP226_NOAA11117.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6d26ba0c7c236f24973a3d8ce595c409.npz

.

Average throughput: 129.1MiB/s

[train] downloading 516/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101024_0848_HARP226_NOAA11117.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101024_0848_HARP226_NOAA11117.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7f9555b65087852f268f4962b9734899.npz

.

Average throughput: 82.4MiB/s

[train] downloading 517/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110326_0336_HARP438_NOAA11177.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110326_0336_HARP438_NOAA11177.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c1335a45ab613ced44d9038ce659840f.npz

.

Average throughput: 154.1MiB/s

[train] downloading 518/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110918_0548_HARP856_NOAA11295.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110918_0548_HARP856_NOAA11295.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6639be93edf3ca5541a8d9772533367a.npz

.

Average throughput: 132.6MiB/s

[train] downloading 519/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131015_2148_HARP3263_NOAA11861.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131015_2148_HARP3263_NOAA11861.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/21debfec8bd6912360428b491e18cae4.npz

.

Average throughput: 174.6MiB/s

[train] downloading 520/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130716_0748_HARP2954_NOAA11792.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130716_0748_HARP2954_NOAA11792.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fa327309cb1bc7622d01d3e4be5f2ee7.npz

.

Average throughput: 189.9MiB/s

[train] downloading 521/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120317_0100_HARP1464_NOAA11434.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120317_0100_HARP1464_NOAA11434.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c8afede53dd1beda49874f85f74746b9.npz

.

Average throughput: 163.8MiB/s

[train] downloading 522/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110905_2000_HARP833_NOAA11283.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110905_2000_HARP833_NOAA11283.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9820149750339022a433b3132ab0011a.npz

.

Average throughput: 113.0MiB/s

[train] downloading 523/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130709_0924_HARP2920_NOAA11785.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130709_0924_HARP2920_NOAA11785.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/170c71bb91242eedd1831600000b91f8.npz

.

Average throughput: 86.3MiB/s

[train] downloading 524/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100902_0212_HARP156_NOAA11105.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100902_0212_HARP156_NOAA11105.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/80e1e8572d1273f05e4a6685ce36bb92.npz

.

Average throughput: 184.4MiB/s

[train] downloading 525/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110806_1948_HARP764_NOAA11267.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110806_1948_HARP764_NOAA11267.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/773cb60669c49633eef4988cd594bb76.npz

.

Average throughput: 51.7MiB/s

[train] downloading 526/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110730_1036_HARP750_NOAA11261.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110730_1036_HARP750_NOAA11261.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c9af8594cf4ed9f5b4b7f4241ea906da.npz

.

Average throughput: 90.3MiB/s

[train] downloading 527/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120509_0212_HARP1634_NOAA11475.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120509_0212_HARP1634_NOAA11475.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/466d8e60ca402d23180b8442a1ab2108.npz

.

Average throughput: 38.8MiB/s

[train] downloading 528/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130709_0000_HARP2948_NOAA11789.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130709_0000_HARP2948_NOAA11789.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5efdf2ee2ad1af4a4fd8fa2ac9f5a274.npz

.

Average throughput: 175.1MiB/s

[train] downloading 529/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110710_1648_HARP700_NOAA11245.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110710_1648_HARP700_NOAA11245.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/07a1ef6b61a6481c202b01e27d702085.npz

.

Average throughput: 112.0MiB/s

[train] downloading 530/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130517_0848_HARP2739_NOAA11745.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130517_0848_HARP2739_NOAA11745.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9404d4927e050a5e00404c1a7c375e35.npz

.

Average throughput: 170.3MiB/s

[train] downloading 531/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110404_0836_HARP451_NOAA11183.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110404_0836_HARP451_NOAA11183.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e4f536cd18b57f615eaa7fbaa1aaeaf3.npz

.

Average throughput: 148.8MiB/s

[train] downloading 532/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120221_1248_HARP1410_NOAA11421.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120221_1248_HARP1410_NOAA11421.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0c8f1159111ba3c77ed679eb28b9762c.npz

.

Average throughput: 94.5MiB/s

[train] downloading 533/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110711_1648_HARP700_NOAA11245.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110711_1648_HARP700_NOAA11245.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/becc9724dda7c4d5e99ffae714155d19.npz

.

Average throughput: 141.8MiB/s

[train] downloading 534/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120418_0024_HARP1578_NOAA11460.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120418_0024_HARP1578_NOAA11460.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/936cdcaf7073dd2b5ea56c9f56f7b044.npz

.

Average throughput: 78.7MiB/s

[train] downloading 535/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130920_0112_HARP3188_NOAA11853.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130920_0112_HARP3188_NOAA11853.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/249505c663ddecc6c51e4f28f2b63cc6.npz

.

Average throughput: 93.0MiB/s

[train] downloading 536/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111112_0648_HARP1046_NOAA11343.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111112_0648_HARP1046_NOAA11343.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a788d6eb120b3b2ec93d39fc8ba46095.npz

.

Average throughput: 159.1MiB/s

[train] downloading 537/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130110_0536_HARP2360_NOAA11650.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130110_0536_HARP2360_NOAA11650.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3e54f52ec60d8a6615d0bcdf77c7efda.npz

.

Average throughput: 80.7MiB/s

[train] downloading 538/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131104_1912_HARP3344_NOAA11891.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131104_1912_HARP3344_NOAA11891.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/562a7c2025a800a4752fd4f0e25286c2.npz

.

Average throughput: 64.8MiB/s

[train] downloading 539/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130627_0124_HARP2904_NOAA11780.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130627_0124_HARP2904_NOAA11780.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a81bd7e177aa26b7705a1caad1c25906.npz

.

Average throughput: 53.6MiB/s

[train] downloading 540/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111218_1436_HARP1186_NOAA11378.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111218_1436_HARP1186_NOAA11378.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f6ba67f65dd4a7ae66caa4947742b788.npz

.

Average throughput: 101.8MiB/s

[train] downloading 541/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110616_0748_HARP661_NOAA11234.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110616_0748_HARP661_NOAA11234.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c4ac2fda05b5c616d2f63c04a973b210.npz



Average throughput: 184.7MiB/s

[train] downloading 542/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120202_2312_HARP1367_NOAA11415.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120202_2312_HARP1367_NOAA11415.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/40bae8a91d350013e2fdfb396cf36748.npz

.

Average throughput: 140.2MiB/s

[train] downloading 543/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130828_1412_HARP3119_NOAA11834.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130828_1412_HARP3119_NOAA11834.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/149c0af57841822cc6a8fe6299634ccb.npz



Average throughput: 162.0MiB/s

[train] downloading 544/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110403_0036_HARP451_NOAA11183.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110403_0036_HARP451_NOAA11183.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/dd871224712f442642766ec31fb8da29.npz

.

Average throughput: 78.3MiB/s

[train] downloading 545/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110818_0024_HARP799_NOAA11273.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110818_0024_HARP799_NOAA11273.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/314aa6bda55b48754823be9588c4b073.npz

.

Average throughput: 240.4MiB/s

[train] downloading 546/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120126_0436_HARP1339_NOAA11412.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120126_0436_HARP1339_NOAA11412.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/04cc9eacf0890af11d17556bb7dcf957.npz

.

Average throughput: 99.0MiB/s

[train] downloading 547/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110718_1848_HARP714_NOAA11251.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110718_1848_HARP714_NOAA11251.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/72f6f595aa7176fa9133c80090ff127d.npz

.

Average throughput: 126.2MiB/s

[train] downloading 548/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120908_0224_HARP2017_NOAA11568.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120908_0224_HARP2017_NOAA11568.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/32d7cae33c1d6ebd06c4bf98ff961ecb.npz

.

Average throughput: 156.5MiB/s

[train] downloading 549/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100927_0748_HARP187_NOAA11109.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100927_0748_HARP187_NOAA11109.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/91195a1a89b01a70785972016baa4249.npz

.

Average throughput: 102.3MiB/s

[train] downloading 550/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111129_0512_HARP1113_NOAA11358.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111129_0512_HARP1113_NOAA11358.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c302c264bb97d8a8d5d133e927cba2c2.npz



Average throughput: 148.5MiB/s

[train] downloading 551/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110908_1236_HARP843_NOAA11287.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110908_1236_HARP843_NOAA11287.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2579771ab6cfd09eeb4d731037e8e642.npz

.

Average throughput: 180.1MiB/s

[train] downloading 552/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120713_1424_HARP1834_NOAA11519.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120713_1424_HARP1834_NOAA11519.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8835e018bb1a9ac5720a6650851f4318.npz

.

Average throughput: 155.6MiB/s

[train] downloading 553/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110606_1436_HARP651_NOAA11231.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110606_1436_HARP651_NOAA11231.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3114611f752620a39a34c04f19dbb6dd.npz

.

Average throughput: 164.1MiB/s

[train] downloading 554/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120116_2048_HARP1312_NOAA11397.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120116_2048_HARP1312_NOAA11397.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c17a8e5a1cecd0db27ad5099b1de3cef.npz

.

Average throughput: 82.9MiB/s

[train] downloading 555/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121213_1436_HARP2291_NOAA11631.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121213_1436_HARP2291_NOAA11631.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6ec9ef9c3f9d01d104d457f8b1dbfea6.npz

.

Average throughput: 132.5MiB/s

[train] downloading 556/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120518_0524_HARP1657_NOAA11481.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120518_0524_HARP1657_NOAA11481.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/188d6bd2bba570a6e5a18f3a8c356309.npz

.

Average throughput: 121.1MiB/s

[train] downloading 557/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120822_2124_HARP1952_NOAA11551.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120822_2124_HARP1952_NOAA11551.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6e88c4f753c427edbedfb51f22a952b1.npz

.

Average throughput: 107.6MiB/s

[train] downloading 558/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120214_0112_HARP1390_NOAA11418.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120214_0112_HARP1390_NOAA11418.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cc30e9e965826615851ed05703124a58.npz

.

Average throughput: 71.8MiB/s

[train] downloading 559/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130728_1824_HARP3019_NOAA11807.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130728_1824_HARP3019_NOAA11807.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/601210d6512cbd42f4cef92dab3b8a7c.npz

.

Average throughput: 84.0MiB/s

[train] downloading 560/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111208_1312_HARP1165_NOAA11367.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111208_1312_HARP1165_NOAA11367.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fee225bf96bd8784f62d10b667e3886f.npz

.

Average throughput: 53.0MiB/s

[train] downloading 561/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111021_0112_HARP970_NOAA11323.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111021_0112_HARP970_NOAA11323.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ec5ec2c7a4c578c9875b25928673f2e0.npz

.

Average throughput: 157.0MiB/s

[train] downloading 562/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110528_1200_HARP622_NOAA11219.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110528_1200_HARP622_NOAA11219.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/451e1051cde0d237bf5f228088aeec1b.npz

.

Average throughput: 95.1MiB/s

[train] downloading 563/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110117_0336_HARP347_NOAA11148.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110117_0336_HARP347_NOAA11148.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/da81b134981719aa8a2aaa470cd123a0.npz

.

Average throughput: 178.7MiB/s

[train] downloading 564/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130817_1148_HARP3056_NOAA11818.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130817_1148_HARP3056_NOAA11818.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/43832e6f037aa9597f9293e6f7ecfaa0.npz

.

Average throughput: 169.9MiB/s

[train] downloading 565/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100926_2336_HARP187_NOAA11109.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100926_2336_HARP187_NOAA11109.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/03804db5c40492cfb588054027fc3584.npz

.

Average throughput: 100.7MiB/s

[train] downloading 566/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110601_0024_HARP643_NOAA11229.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110601_0024_HARP643_NOAA11229.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/acf144c33870af461bc3bf418234e3b4.npz

.

Average throughput: 92.8MiB/s

[train] downloading 567/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130401_0024_HARP2599_NOAA11710.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130401_0024_HARP2599_NOAA11710.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2afe7b16a5b85fadbe1a2e99f5ca858f.npz

.

Average throughput: 81.4MiB/s

[train] downloading 568/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100607_1748_HARP46_NOAA11078.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100607_1748_HARP46_NOAA11078.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3a02957cc24de02e3103f254d26fd26e.npz

.

Average throughput: 65.6MiB/s

[train] downloading 569/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120321_2300_HARP1484_NOAA11440.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120321_2300_HARP1484_NOAA11440.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/51ec7acd5c3d4d1066a9b6af7caf99f6.npz

.

Average throughput: 166.5MiB/s

[train] downloading 570/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130411_0312_HARP2636_NOAA11718.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130411_0312_HARP2636_NOAA11718.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8499fc51d83e6b8f919b6243fa8f5a05.npz

.

Average throughput: 139.0MiB/s

[train] downloading 571/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120711_1112_HARP1834_NOAA11519.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120711_1112_HARP1834_NOAA11519.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/30330878dcdd89c58a87987ddddcc5e3.npz

.

Average throughput: 175.0MiB/s

[train] downloading 572/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131213_1636_HARP3473_NOAA11917.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131213_1636_HARP3473_NOAA11917.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4ff32ab0a1cca1a5b1e60b5ee2ad966f.npz

.

Average throughput: 43.9MiB/s

[train] downloading 573/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130902_1412_HARP3129_NOAA11836.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130902_1412_HARP3129_NOAA11836.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/dee852b60a1921ace0f7beafd0c4eccd.npz

.

Average throughput: 110.3MiB/s

[train] downloading 574/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111020_2024_HARP982_NOAA11327.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111020_2024_HARP982_NOAA11327.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5a8ce976489d1091ef86722cc13238a0.npz

.

Average throughput: 122.4MiB/s

[train] downloading 575/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130820_0124_HARP3082_NOAA11823.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130820_0124_HARP3082_NOAA11823.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/159e4dab428440a61ea505a3e2bdabfd.npz

.

Average throughput: 71.5MiB/s

[train] downloading 576/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120827_2124_HARP1951_NOAA11552.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120827_2124_HARP1951_NOAA11552.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/797b306a5a66eda55d070fece492db76.npz

.

Average throughput: 110.1MiB/s

[train] downloading 577/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120817_1300_HARP1943_NOAA11547.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120817_1300_HARP1943_NOAA11547.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d9da276cc26eadfde7ccafc319b14261.npz

.

Average throughput: 94.7MiB/s

[train] downloading 578/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110622_1248_HARP674_NOAA11237.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110622_1248_HARP674_NOAA11237.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d07d056d4f1855087655dec57575e415.npz

.

Average throughput: 75.3MiB/s

[train] downloading 579/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131028_1900_HARP3323_NOAA11888.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131028_1900_HARP3323_NOAA11888.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/92fd8c04f2c49041d36edf30adce2d4a.npz



Average throughput: 188.1MiB/s

[train] downloading 580/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111001_0324_HARP902_NOAA11305.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111001_0324_HARP902_NOAA11305.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ff4f61be55f4c4370a4a6876a092c0c9.npz

.

Average throughput: 93.4MiB/s

[train] downloading 581/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130711_0248_HARP2945_NOAA11794.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130711_0248_HARP2945_NOAA11794.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2ff891a975a1bcb8fc70f9a5773e6ce4.npz

.

Average throughput: 168.9MiB/s

[train] downloading 582/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110601_1600_HARP637_NOAA11226.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110601_1600_HARP637_NOAA11226.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/713ac2e71cdbf938bfadf7f25c5051df.npz

.

Average throughput: 143.8MiB/s

[train] downloading 583/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130108_2012_HARP2341_NOAA11642.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130108_2012_HARP2341_NOAA11642.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/49c851830a821cc8ddbafaddbd3e8a4a.npz

.

Average throughput: 133.7MiB/s

[train] downloading 584/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120930_2012_HARP2069_NOAA11582.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120930_2012_HARP2069_NOAA11582.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3272d3f93a3ed8c52edcaafdcf919bec.npz

.

Average throughput: 187.0MiB/s

[train] downloading 585/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111225_0212_HARP1209_NOAA11380.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111225_0212_HARP1209_NOAA11380.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e36603c53e89dbd5b70a1d260c367760.npz

.

Average throughput: 82.5MiB/s

[train] downloading 586/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130421_1224_HARP2673_NOAA11726.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130421_1224_HARP2673_NOAA11726.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/473bfe7d8c546d9368476710748344b7.npz

.

Average throughput: 119.7MiB/s

[train] downloading 587/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120106_1148_HARP1275_NOAA11393.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120106_1148_HARP1275_NOAA11393.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/485b7dcf5a94e3637fcb61288f0e8fc7.npz

.

Average throughput: 178.4MiB/s

[train] downloading 588/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131101_2348_HARP3320_NOAA11883.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131101_2348_HARP3320_NOAA11883.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/490be9e90b2f9c6ba78e9b0c951c3758.npz

.

Average throughput: 161.9MiB/s

[train] downloading 589/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130101_2324_HARP2337_NOAA11640.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130101_2324_HARP2337_NOAA11640.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f2bfe4e600ae118887a1d0ae4f618426.npz

.

Average throughput: 85.8MiB/s

[train] downloading 590/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130101_2148_HARP2337_NOAA11640.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130101_2148_HARP2337_NOAA11640.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7e66600ffd731ab4675471b2bd3b8fbe.npz

.

Average throughput: 77.0MiB/s

[train] downloading 591/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130403_2348_HARP2605_NOAA11711.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130403_2348_HARP2605_NOAA11711.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3190e56fdb8678c3f49562d23f6021aa.npz

.

Average throughput: 132.4MiB/s

[train] downloading 592/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111110_0300_HARP1028_NOAA11339.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111110_0300_HARP1028_NOAA11339.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/516e4b31782b831ee58c69b3881d61cb.npz

.

Average throughput: 144.0MiB/s

[train] downloading 593/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111203_1200_HARP1120_NOAA11362.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111203_1200_HARP1120_NOAA11362.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d496ca955b45829fef751ab821222ce5.npz

.

Average throughput: 101.9MiB/s

[train] downloading 594/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110713_1724_HARP712_NOAA11250.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110713_1724_HARP712_NOAA11250.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/58352d3b14f1bcca758407120f857e26.npz

.

Average throughput: 50.3MiB/s

[train] downloading 595/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130222_0112_HARP2492_NOAA11676.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130222_0112_HARP2492_NOAA11676.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d663f2671c393f04a7d48b8e3025529b.npz

.

Average throughput: 70.8MiB/s

[train] downloading 596/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111211_0436_HARP1164_NOAA11368.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111211_0436_HARP1164_NOAA11368.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/36b4f44476becaa58966a79d43e8b22f.npz

.

Average throughput: 109.1MiB/s

[train] downloading 597/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100829_0024_HARP146_NOAA11102.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100829_0024_HARP146_NOAA11102.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f2b7f2ba78ab63d9fe46f2e71b2b8ab6.npz

.

Average throughput: 90.3MiB/s

[train] downloading 598/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110930_0524_HARP892_NOAA11302.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110930_0524_HARP892_NOAA11302.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/05c3157695d7e350ca8ca0536c69b1e3.npz

.

Average throughput: 101.9MiB/s

[train] downloading 599/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110522_2348_HARP610_NOAA11218.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110522_2348_HARP610_NOAA11218.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ad7e905a72428dc0ae715e63fdaeb901.npz

.

Average throughput: 170.3MiB/s

[train] downloading 600/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100916_0936_HARP175_NOAA11106.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100916_0936_HARP175_NOAA11106.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2a2b2971a230baf7c8a315868b4466dd.npz

.

Average throughput: 111.7MiB/s

[train] cached/checked 600/1650 files | elapsed 15.4 min
[train] downloading 601/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131125_2100_HARP3400_NOAA11903.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131125_2100_HARP3400_NOAA11903.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9f474a6269ff6a1c1ca1f90bd7dfaad6.npz

.

Average throughput: 119.9MiB/s

[train] downloading 602/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120320_1848_HARP1478_NOAA11436.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120320_1848_HARP1478_NOAA11436.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cb6efc1586c25024176a47d582e26056.npz

.

Average throughput: 94.0MiB/s

[train] downloading 603/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131212_0524_HARP3473_NOAA11917.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131212_0524_HARP3473_NOAA11917.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/611651a3d214b01802abe45bad95f49d.npz

.

Average throughput: 172.6MiB/s

[train] downloading 604/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110904_0536_HARP833_NOAA11283.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110904_0536_HARP833_NOAA11283.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b56cedc163bd1e9229a45da93280b245.npz

.

Average throughput: 163.8MiB/s

[train] downloading 605/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110331_2200_HARP451_NOAA11183.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110331_2200_HARP451_NOAA11183.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3834d4fdcfe4e04063e31342cfe31e7f.npz

.

Average throughput: 128.8MiB/s

[train] downloading 606/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120413_2048_HARP1549_NOAA11455.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120413_2048_HARP1549_NOAA11455.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/44618077d6e67432d17d0507bcac76e2.npz

.

Average throughput: 108.3MiB/s

[train] downloading 607/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130701_0600_HARP2910_NOAA11782.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130701_0600_HARP2910_NOAA11782.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5817d24d704eeff07722bce30acd569d.npz

.

Average throughput: 71.2MiB/s

[train] downloading 608/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130925_1412_HARP3199_NOAA11850.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130925_1412_HARP3199_NOAA11850.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9730e123a5c4d611279b28f3b3ba8efb.npz

.

Average throughput: 159.5MiB/s

[train] downloading 609/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111103_1200_HARP1021_NOAA11334.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111103_1200_HARP1021_NOAA11334.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/396bf85f36e363939a2ec0bd7da90d9b.npz

.

Average throughput: 101.6MiB/s

[train] downloading 610/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110912_1836_HARP851_NOAA11291.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110912_1836_HARP851_NOAA11291.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b45835a48857433e38305685009025ed.npz

.

Average throughput: 76.5MiB/s

[train] downloading 611/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120904_1224_HARP1999_NOAA11563.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120904_1224_HARP1999_NOAA11563.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/371119e39c1a8c5fd9858c3b9726852d.npz

.

Average throughput: 129.2MiB/s

[train] downloading 612/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120520_0500_HARP1658_NOAA11483.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120520_0500_HARP1658_NOAA11483.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/19c632d87a5e9758905eebf7ddd1216f.npz

.

Average throughput: 62.4MiB/s

[train] downloading 613/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121113_1524_HARP2186_NOAA11611.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121113_1524_HARP2186_NOAA11611.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/dfa41bbc4914eb69249149d2e93a1ce3.npz

..

Average throughput: 73.9MiB/s

[train] downloading 614/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110909_2048_HARP843_NOAA11287.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110909_2048_HARP843_NOAA11287.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/28b568cc74b5ec8632ede671e9238fb3.npz

.

Average throughput: 86.3MiB/s

[train] downloading 615/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130927_1424_HARP3220_NOAA11858.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130927_1424_HARP3220_NOAA11858.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/077ad48f06cfb819daeaa7806042706b.npz

.

Average throughput: 162.9MiB/s

[train] downloading 616/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120325_2312_HARP1488_NOAA11438.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120325_2312_HARP1488_NOAA11438.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4176cffca7cc5c70960f631afe117d0a.npz

.

Average throughput: 107.4MiB/s

[train] downloading 617/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110328_0124_HARP455_NOAA11182.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110328_0124_HARP455_NOAA11182.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/da09a59b44ab994535f0ffd483bc5d50.npz

.

Average throughput: 87.5MiB/s

[train] downloading 618/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111122_2312_HARP1089_NOAA11352.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111122_2312_HARP1089_NOAA11352.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c1e8238cf64dbb085ab5d403b1022105.npz

.

Average throughput: 180.6MiB/s

[train] downloading 619/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100530_1424_HARP40_NOAA11075.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100530_1424_HARP40_NOAA11075.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c92036c0de7a8032f316a52080c8da4d.npz

.

Average throughput: 53.1MiB/s

[train] downloading 620/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130624_0336_HARP2878_NOAA11777.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130624_0336_HARP2878_NOAA11777.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/43a4da5cc3354b54330d56f8562bda44.npz

.

Average throughput: 61.7MiB/s

[train] downloading 621/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120722_0036_HARP1866_NOAA11524.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120722_0036_HARP1866_NOAA11524.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b83fee3acd05be7d9935aa11d2eb3ddb.npz

.

Average throughput: 120.3MiB/s

[train] downloading 622/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131113_2200_HARP3371_NOAA11901.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131113_2200_HARP3371_NOAA11901.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f74532d24632eb72aa7290a23746edc5.npz

.

Average throughput: 70.7MiB/s

[train] downloading 623/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100522_1324_HARP26_NOAA11072.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100522_1324_HARP26_NOAA11072.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3744bac0093a4eebd29cc1c3d6ae875e.npz

.

Average throughput: 77.3MiB/s

[train] downloading 624/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120323_0248_HARP1495_NOAA11447.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120323_0248_HARP1495_NOAA11447.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a01273a6ecca9ad73c4b4974c52549bb.npz

.

Average throughput: 113.9MiB/s

[train] downloading 625/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121205_1724_HARP2260_NOAA11627.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121205_1724_HARP2260_NOAA11627.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a87d4761b1889fd2580b8cf684eb780c.npz

.

Average throughput: 68.4MiB/s

[train] downloading 626/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110803_0900_HARP750_NOAA11261.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110803_0900_HARP750_NOAA11261.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c5e08a15e517d55c5a639378a2555fed.npz

.

Average throughput: 117.6MiB/s

[train] downloading 627/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110423_0636_HARP514_NOAA11195.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110423_0636_HARP514_NOAA11195.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/09ae58c2a714eae9b262722453f202c3.npz

.

Average throughput: 54.6MiB/s

[train] downloading 628/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120722_1948_HARP1866_NOAA11524.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120722_1948_HARP1866_NOAA11524.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9a48e0b672e741ddcf89795def3435c0.npz

.

Average throughput: 123.4MiB/s

[train] downloading 629/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120828_0524_HARP1951_NOAA11552.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120828_0524_HARP1951_NOAA11552.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fb764371d73cb864867973e3111195c3.npz

.

Average throughput: 133.8MiB/s

[train] downloading 630/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130703_1548_HARP2910_NOAA11782.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130703_1548_HARP2910_NOAA11782.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0fc816b04272e729ffecaac1588a4177.npz

.

Average throughput: 165.4MiB/s

[train] downloading 631/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120211_1712_HARP1389_NOAA11416.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120211_1712_HARP1389_NOAA11416.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ac495c0a551771f77483c40f65de9ae1.npz

.

Average throughput: 106.5MiB/s

[train] downloading 632/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130826_2036_HARP3103_NOAA11828.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130826_2036_HARP3103_NOAA11828.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/eeff1c80a9eca95f7c136f64e7570f01.npz

.

Average throughput: 87.2MiB/s

[train] downloading 633/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111116_0048_HARP1075_NOAA11347.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111116_0048_HARP1075_NOAA11347.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d2a911f8e335c61003f403e7cdad8d9a.npz

.

Average throughput: 32.4MiB/s

[train] downloading 634/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120214_2312_HARP1391_NOAA11417.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120214_2312_HARP1391_NOAA11417.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6705334cc761605f5dd6ffa29b3b860d.npz

.

Average throughput: 105.1MiB/s

[train] downloading 635/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131027_0236_HARP3295_NOAA11877.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131027_0236_HARP3295_NOAA11877.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b03f61ff68ca40a3cf954eaf8e75eb1b.npz

.

Average throughput: 191.4MiB/s

[train] downloading 636/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121121_0436_HARP2220_NOAA11618.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121121_0436_HARP2220_NOAA11618.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8d8c31a33b1e515ac48e41537b3c3271.npz

.

Average throughput: 177.1MiB/s

[train] downloading 637/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110319_2024_HARP421_NOAA11172.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110319_2024_HARP421_NOAA11172.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/49211f9c899f805e18fc1f4c79f88fef.npz

.

Average throughput: 67.4MiB/s

[train] downloading 638/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131106_2112_HARP3341_NOAA11890.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131106_2112_HARP3341_NOAA11890.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5cd3589931efb3bf99985b0f61e298b6.npz

.

Average throughput: 95.4MiB/s

[train] downloading 639/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130509_0948_HARP2718_NOAA11740.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130509_0948_HARP2718_NOAA11740.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f68bd3a7793ee55b41f9597d101831b6.npz

.

Average throughput: 43.3MiB/s

[train] downloading 640/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121103_0836_HARP2166_NOAA11602.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121103_0836_HARP2166_NOAA11602.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e6d3a5be5014812cdedaeb2fa49d140d.npz



Average throughput: 162.9MiB/s

[train] downloading 641/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130307_1400_HARP2525_NOAA11693.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130307_1400_HARP2525_NOAA11693.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cb0828c5733b94c2751fa7e101c4ed1b.npz

.

Average throughput: 85.8MiB/s

[train] downloading 642/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110620_1248_HARP667_NOAA11236.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110620_1248_HARP667_NOAA11236.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c34a6ed55c44773ea2e2bac7185da28a.npz

.

Average throughput: 82.8MiB/s

[train] downloading 643/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110906_2348_HARP843_NOAA11287.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110906_2348_HARP843_NOAA11287.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3bb404dfb013203e0dcecb3585e562b3.npz

.

Average throughput: 142.5MiB/s

[train] downloading 644/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111008_1124_HARP913_NOAA11308.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111008_1124_HARP913_NOAA11308.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/78fe94f7f470a3c847bc7340902c8452.npz



Average throughput: 178.2MiB/s

[train] downloading 645/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121203_0500_HARP2240_NOAA11621.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121203_0500_HARP2240_NOAA11621.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f89c834bc920782eb56fe410f5e78279.npz

.

Average throughput: 116.3MiB/s

[train] downloading 646/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100915_1124_HARP175_NOAA11106.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100915_1124_HARP175_NOAA11106.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b03442fc146b023c8b32ca7d93b73afb.npz

.

Average throughput: 190.4MiB/s

[train] downloading 647/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130406_1548_HARP2605_NOAA11711.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130406_1548_HARP2605_NOAA11711.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a1dd7c435adbe0485b06e1819367b229.npz

.

Average throughput: 150.6MiB/s

[train] downloading 648/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111212_1836_HARP1168_NOAA11374.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111212_1836_HARP1168_NOAA11374.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2b0475d713aa79a2d8bdd046342e04c4.npz

.

Average throughput: 84.7MiB/s

[train] downloading 649/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130708_2348_HARP2920_NOAA11785.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130708_2348_HARP2920_NOAA11785.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/19041da0cef78554be9d5f531bcfe8d4.npz

.

Average throughput: 98.9MiB/s

[train] downloading 650/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110504_2212_HARP556_NOAA11203.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110504_2212_HARP556_NOAA11203.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3969265e1cb0fcf91993aedaa20520c7.npz

.

Average throughput: 126.1MiB/s

[train] downloading 651/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111110_0500_HARP1026_NOAA11338.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111110_0500_HARP1026_NOAA11338.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/04d14bbdb18a4e14f25dd40d5a89f2b2.npz

.

Average throughput: 143.5MiB/s

[train] downloading 652/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101201_0724_HARP270_NOAA11128.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101201_0724_HARP270_NOAA11128.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7f726c15ff36a9f39544cc14374f3f38.npz

.

Average throughput: 108.1MiB/s

[train] downloading 653/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130629_1136_HARP2887_NOAA11778.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130629_1136_HARP2887_NOAA11778.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d92bb902a00159c12af35660e1050a8f.npz

.

Average throughput: 152.1MiB/s

[train] downloading 654/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120126_1200_HARP1338_NOAA11408.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120126_1200_HARP1338_NOAA11408.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3065d96c24c97fa240279ade12416255.npz

.

Average throughput: 98.4MiB/s

[train] downloading 655/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120929_1924_HARP2059_NOAA11579.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120929_1924_HARP2059_NOAA11579.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0e122535c5b914dc0563b6b8cc4f144e.npz

.

Average throughput: 65.8MiB/s

[train] downloading 656/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120509_0836_HARP1634_NOAA11475.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120509_0836_HARP1634_NOAA11475.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/677cec8d682cda09a15532d8614be00d.npz

.

Average throughput: 102.3MiB/s

[train] downloading 657/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120419_0136_HARP1573_NOAA11462.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120419_0136_HARP1573_NOAA11462.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f47ca32e1edb1efd50450d083ec26431.npz

.

Average throughput: 142.0MiB/s

[train] downloading 658/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110726_0124_HARP748_NOAA11265.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110726_0124_HARP748_NOAA11265.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b20d113eb1dd9c3254cb055374a22b70.npz

.

Average throughput: 178.1MiB/s

[train] downloading 659/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130923_0312_HARP3188_NOAA11853.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130923_0312_HARP3188_NOAA11853.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/68bcd9e447cd40934f2a452d09ec2c9b.npz

.

Average throughput: 163.6MiB/s

[train] downloading 660/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130517_0400_HARP2739_NOAA11745.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130517_0400_HARP2739_NOAA11745.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3b866716bb33ecd79da2dd9946194298.npz

.

Average throughput: 99.0MiB/s

[train] downloading 661/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131002_0300_HARP3240_NOAA11854.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131002_0300_HARP3240_NOAA11854.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1dbf5ab98d2523317228e3dbff3c3a44.npz

.

Average throughput: 90.4MiB/s

[train] downloading 662/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130923_0824_HARP3194_NOAA11845.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130923_0824_HARP3194_NOAA11845.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/789b7eaefbd2590ef1b1e4a06897fe58.npz

.

Average throughput: 167.8MiB/s

[train] downloading 663/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110623_1512_HARP676_NOAA11239.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110623_1512_HARP676_NOAA11239.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e446708325e7303c6ff81dd5af5defb3.npz

..

Average throughput: 41.8MiB/s

[train] downloading 664/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120418_2036_HARP1572_NOAA11458.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120418_2036_HARP1572_NOAA11458.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7e0c5227dd3054954c408bc58a81e1ae.npz

.

Average throughput: 106.0MiB/s

[train] downloading 665/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110204_0624_HARP362_NOAA11153.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110204_0624_HARP362_NOAA11153.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/62008bff93ca55860495f7793aeded67.npz

.

Average throughput: 174.3MiB/s

[train] downloading 666/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130816_0200_HARP3048_NOAA11814.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130816_0200_HARP3048_NOAA11814.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f51588fd85eb89c7f45f345c5695f1fa.npz

.

Average throughput: 161.8MiB/s

[train] downloading 667/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130725_1636_HARP2984_NOAA11799.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130725_1636_HARP2984_NOAA11799.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d4375dc1f04ad7416bd70a09582dfa36.npz

.

Average throughput: 84.6MiB/s

[train] downloading 668/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110520_1112_HARP605_NOAA11216.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110520_1112_HARP605_NOAA11216.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8dc2ab59a4a7740e19c542e76de8f3b6.npz

.

Average throughput: 74.7MiB/s

[train] downloading 669/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120908_1512_HARP2011_NOAA11566.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120908_1512_HARP2011_NOAA11566.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b6b2d15616286f7e94551c881eea38eb.npz

.

Average throughput: 106.6MiB/s

[train] downloading 670/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101112_0136_HARP252_NOAA11124.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101112_0136_HARP252_NOAA11124.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e6d72633cbef058bd8087b6e2e72393f.npz

.

Average throughput: 84.5MiB/s

[train] downloading 671/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120128_1612_HARP1338_NOAA11408.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120128_1612_HARP1338_NOAA11408.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/aac1975333625c6f7d5307eae25662a0.npz

.

Average throughput: 75.5MiB/s

[train] downloading 672/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110201_0100_HARP355_NOAA11150.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110201_0100_HARP355_NOAA11150.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/de8192774b44c7e4dd506fc3a2f833b5.npz

.

Average throughput: 171.8MiB/s

[train] downloading 673/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110605_1248_HARP637_NOAA11226.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110605_1248_HARP637_NOAA11226.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7a8d7936d410ee3e86925043f6bb13a0.npz

.

Average throughput: 94.8MiB/s

[train] downloading 674/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120213_0736_HARP1390_NOAA11418.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120213_0736_HARP1390_NOAA11418.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/92c9406d92fb0f17ad12e2f85fe3a1f4.npz

.

Average throughput: 164.6MiB/s

[train] downloading 675/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110807_0524_HARP764_NOAA11267.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110807_0524_HARP764_NOAA11267.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3ab5513eb33f01c8120ac5fe8eaa8a44.npz

.

Average throughput: 116.8MiB/s

[train] downloading 676/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120219_1336_HARP1405_NOAA11422.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120219_1336_HARP1405_NOAA11422.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/47e2e3a4ed09e2c3f80f774b65c4e764.npz

.

Average throughput: 185.0MiB/s

[train] downloading 677/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111206_1400_HARP1149_NOAA11367.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111206_1400_HARP1149_NOAA11367.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3273aa986728d873e44ea09d7260a376.npz

.

Average throughput: 114.5MiB/s

[train] downloading 678/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131129_2348_HARP3420_NOAA11905.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131129_2348_HARP3420_NOAA11905.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c6d2081cff862dc8df8d196a0406d337.npz

.

Average throughput: 132.0MiB/s

[train] downloading 679/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110910_0824_HARP851_NOAA11291.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110910_0824_HARP851_NOAA11291.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/99731c5267cc7d7b658d3797ecb559e4.npz

..

Average throughput: 57.2MiB/s

[train] downloading 680/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131121_2236_HARP3400_NOAA11903.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131121_2236_HARP3400_NOAA11903.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1a5bec8650b7c6a89f444fe6b3801cfb.npz

.

Average throughput: 83.2MiB/s

[train] downloading 681/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120703_2348_HARP1806_NOAA11513.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120703_2348_HARP1806_NOAA11513.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8067a109b8f1f9c32681f0810b92cb5c.npz

.

Average throughput: 31.6MiB/s

[train] downloading 682/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131014_0724_HARP3263_NOAA11861.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131014_0724_HARP3263_NOAA11861.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c78763dd323bf3c43306624c4b48d5a8.npz

.

Average throughput: 170.8MiB/s

[train] downloading 683/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130725_1712_HARP2981_NOAA11799.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130725_1712_HARP2981_NOAA11799.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/90c3318f446003a11b9fe29bc80bc296.npz

.

Average throughput: 81.6MiB/s

[train] downloading 684/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120116_1112_HARP1312_NOAA11397.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120116_1112_HARP1312_NOAA11397.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b7cc3313a88cf5506174ff3fc1df8817.npz

.

Average throughput: 51.7MiB/s

[train] downloading 685/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110826_1036_HARP803_NOAA11274.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110826_1036_HARP803_NOAA11274.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/43515fa7f967b56041e45d1b7c989a27.npz

.

Average throughput: 135.8MiB/s

[train] downloading 686/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101023_0248_HARP224_NOAA11119.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101023_0248_HARP224_NOAA11119.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/87a160736cb138bee5540f5cb962a527.npz

.

Average throughput: 169.0MiB/s

[train] downloading 687/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131204_1712_HARP3448_NOAA11916.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131204_1712_HARP3448_NOAA11916.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cd2109fa1f7355c394470b3e7d470acd.npz

.

Average throughput: 170.6MiB/s

[train] downloading 688/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121120_2212_HARP2220_NOAA11618.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121120_2212_HARP2220_NOAA11618.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/154f95ba784ecbd70b21865b3659cb9a.npz

..

Average throughput: 63.9MiB/s

[train] downloading 689/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130402_1436_HARP2597_NOAA11713.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130402_1436_HARP2597_NOAA11713.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/60071a831be86ea03c7dd43673d45259.npz

.

Average throughput: 107.4MiB/s

[train] downloading 690/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120730_0436_HARP1892_NOAA11533.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120730_0436_HARP1892_NOAA11533.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a8c8402fca03d5c2a7c04794524928c6.npz

.

Average throughput: 72.7MiB/s

[train] downloading 691/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130923_2312_HARP3199_NOAA11850.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130923_2312_HARP3199_NOAA11850.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fa613e09964ce2e226afa88845a5ecf5.npz

.

Average throughput: 86.5MiB/s

[train] downloading 692/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110714_0924_HARP700_NOAA11245.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110714_0924_HARP700_NOAA11245.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3a732a53f580ba1174e0ae8487c1a282.npz

.

Average throughput: 126.0MiB/s

[train] downloading 693/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121118_2324_HARP2191_NOAA11613.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121118_2324_HARP2191_NOAA11613.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e3c6032b82ea533516b1a7d3facfb64f.npz

.

Average throughput: 87.6MiB/s

[train] downloading 694/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101112_0048_HARP245_NOAA11121.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101112_0048_HARP245_NOAA11121.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/14c5da4e1a9d4fab9da28b29cbcf6c0f.npz

.

Average throughput: 75.4MiB/s

[train] downloading 695/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110202_1836_HARP355_NOAA11150.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110202_1836_HARP355_NOAA11150.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/757bdf8b6740922ab1fd8879c44a922f.npz

.

Average throughput: 74.0MiB/s

[train] downloading 696/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121029_0212_HARP2143_NOAA11599.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121029_0212_HARP2143_NOAA11599.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/aa5378f8d6ba7a5eab8fd8508bcc4738.npz

.

Average throughput: 165.8MiB/s

[train] downloading 697/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130501_0524_HARP2685_NOAA11728.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130501_0524_HARP2685_NOAA11728.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7f156d5309e0313cac7c3301dd8cde80.npz

.

Average throughput: 97.8MiB/s

[train] downloading 698/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121220_0724_HARP2306_NOAA11633.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121220_0724_HARP2306_NOAA11633.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/59eacbf1ba8b91efd364cbeaa73eea82.npz

.

Average throughput: 83.7MiB/s

[train] downloading 699/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131210_1624_HARP3490_NOAA11922.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131210_1624_HARP3490_NOAA11922.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7cc7e92ff3a9b067397187216c1f2031.npz

.

Average throughput: 140.2MiB/s

[train] downloading 700/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101201_2336_HARP270_NOAA11128.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101201_2336_HARP270_NOAA11128.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2b00f703e68784519e9296a3aabc9d7c.npz

.

Average throughput: 150.8MiB/s

[train] cached/checked 700/1650 files | elapsed 18.0 min
[train] downloading 701/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131219_1848_HARP3497_NOAA11925.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131219_1848_HARP3497_NOAA11925.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1b2b89a1844ba1b322cd51a932dafbbf.npz

.

Average throughput: 109.6MiB/s

[train] downloading 702/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131009_1648_HARP3267_NOAA11867.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131009_1648_HARP3267_NOAA11867.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/efd7c6122660355ab86400f3597e604d.npz

.

Average throughput: 83.8MiB/s

[train] downloading 703/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120317_1924_HARP1480_NOAA11437.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120317_1924_HARP1480_NOAA11437.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0756cefb40cf2e16889c69bb7ed6edd4.npz

.

Average throughput: 134.9MiB/s

[train] downloading 704/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130817_1712_HARP3068_NOAA11825.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130817_1712_HARP3068_NOAA11825.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/769a152dad9a98c6700a2ef9558cef27.npz

.

Average throughput: 139.8MiB/s

[train] downloading 705/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130601_1648_HARP2808_NOAA11761.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130601_1648_HARP2808_NOAA11761.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/27b4c0503e898043aa2d55ebd0f4e882.npz

.

Average throughput: 103.6MiB/s

[train] downloading 706/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130322_1712_HARP2571_NOAA11700.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130322_1712_HARP2571_NOAA11700.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/123e49e4db0d7747a45c6fa057ac7cb4.npz

.

Average throughput: 134.8MiB/s

[train] downloading 707/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131215_1236_HARP3483_NOAA11920.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131215_1236_HARP3483_NOAA11920.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6348a2dbbb23424ec8b741c38106a6d1.npz

.

Average throughput: 95.3MiB/s

[train] downloading 708/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120317_1900_HARP1464_NOAA11434.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120317_1900_HARP1464_NOAA11434.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/56fb880ec97b0b06b4c62bb641152a00.npz

.

Average throughput: 120.3MiB/s

[train] downloading 709/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130912_0524_HARP3154_NOAA11838.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130912_0524_HARP3154_NOAA11838.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b02d70e7fadceaf649a28dc85b295f8c.npz

.

Average throughput: 100.9MiB/s

[train] downloading 710/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121202_1924_HARP2240_NOAA11621.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121202_1924_HARP2240_NOAA11621.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cae2f52b617be864bfdc7dfdee45c22a.npz

.

Average throughput: 82.9MiB/s

[train] downloading 711/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120512_1500_HARP1638_NOAA11476.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120512_1500_HARP1638_NOAA11476.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/421711abd9f47d6015d7260c22148ffc.npz

.

Average throughput: 163.5MiB/s

[train] downloading 712/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131031_2000_HARP3321_NOAA11884.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131031_2000_HARP3321_NOAA11884.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1e1d300c7caee2dc5a13b19ca8b8e3ac.npz

.

Average throughput: 152.5MiB/s

[train] downloading 713/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130926_2300_HARP3199_NOAA11850.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130926_2300_HARP3199_NOAA11850.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/91fc35d8ed70e932fce81e7876190ffd.npz

.

Average throughput: 91.2MiB/s

[train] downloading 714/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110604_0136_HARP637_NOAA11226.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110604_0136_HARP637_NOAA11226.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6888d3c14b750cdefe66839b9785d059.npz

.

Average throughput: 171.8MiB/s

[train] downloading 715/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131022_1348_HARP3286_NOAA11872.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131022_1348_HARP3286_NOAA11872.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3d927d6bb7c66c82c31e8bb7b113effe.npz

.

Average throughput: 189.2MiB/s

[train] downloading 716/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110309_1624_HARP401_NOAA11166.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110309_1624_HARP401_NOAA11166.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/da60761fc0744b03637d2f5b78887299.npz

.

Average throughput: 160.6MiB/s

[train] downloading 717/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100810_0036_HARP116_NOAA11096.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100810_0036_HARP116_NOAA11096.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ab6f2e345fc302213394cf404d238ff0.npz

.

Average throughput: 139.3MiB/s

[train] downloading 718/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120829_2312_HARP1959_NOAA11553.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120829_2312_HARP1959_NOAA11553.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/19e6c3cfbdd2e93febb9992611305c4c.npz

.

Average throughput: 55.8MiB/s

[train] downloading 719/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130303_1736_HARP2519_NOAA11686.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130303_1736_HARP2519_NOAA11686.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3aea2ae3057b26064f278a3db4c1a04e.npz

.

Average throughput: 127.2MiB/s

[train] downloading 720/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120509_1812_HARP1634_NOAA11475.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120509_1812_HARP1634_NOAA11475.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/311e930127d30aec7a11c21c0c088ad9.npz

.

Average throughput: 128.9MiB/s

[train] downloading 721/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120521_0748_HARP1680_NOAA11487.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120521_0748_HARP1680_NOAA11487.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/846c1f0b306c275187fac6340911d3da.npz

.

Average throughput: 143.2MiB/s

[train] downloading 722/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110113_1224_HARP342_NOAA11146.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110113_1224_HARP342_NOAA11146.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5130304724b5319f298f286ea8af7f95.npz

.

Average throughput: 113.3MiB/s

[train] downloading 723/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120218_0048_HARP1405_NOAA11422.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120218_0048_HARP1405_NOAA11422.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/05e5609d535b803b864d776d54bae186.npz

.

Average throughput: 92.4MiB/s

[train] downloading 724/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130922_2200_HARP3192_NOAA11847.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130922_2200_HARP3192_NOAA11847.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f8ee95590fcfed80f6c7616309a8d71c.npz



Average throughput: 179.7MiB/s

[train] downloading 725/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130628_2124_HARP2898_NOAA11779.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130628_2124_HARP2898_NOAA11779.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2ea2c20b355b0d9d1fb0aa2147a0a1f3.npz

.

Average throughput: 159.1MiB/s

[train] downloading 726/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100602_2136_HARP38_NOAA11073.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100602_2136_HARP38_NOAA11073.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d04fa2b730ed86f1357f2871aad3e5fb.npz

.

Average throughput: 146.7MiB/s

[train] downloading 727/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131005_0612_HARP3246_NOAA11866.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131005_0612_HARP3246_NOAA11866.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/767d2b5db5d5550b1b516b088abd9f92.npz

.

Average throughput: 76.4MiB/s

[train] downloading 728/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110205_2048_HARP362_NOAA11153.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110205_2048_HARP362_NOAA11153.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cf0b364e2cb18912d93236d642c780fa.npz

.

Average throughput: 167.1MiB/s

[train] downloading 729/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121026_0536_HARP2144_NOAA11600.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121026_0536_HARP2144_NOAA11600.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d318e9a4d0fea6ccaa165bdc0898751b.npz

.

Average throughput: 124.7MiB/s

[train] downloading 730/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130707_1200_HARP2942_NOAA11789.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130707_1200_HARP2942_NOAA11789.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4a4d0301572363acaf27505985552f66.npz

.

Average throughput: 151.2MiB/s

[train] downloading 731/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120103_1300_HARP1256_NOAA11388.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120103_1300_HARP1256_NOAA11388.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e8557062a365724168a9424853d137ba.npz

.

Average throughput: 70.2MiB/s

[train] downloading 732/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111221_2024_HARP1209_NOAA11380.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111221_2024_HARP1209_NOAA11380.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/359e505f7000f5e5f832211fa1412715.npz

.

Average throughput: 182.3MiB/s

[train] downloading 733/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121018_0500_HARP2123_NOAA11594.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121018_0500_HARP2123_NOAA11594.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e77a4895896f37b056edd95e874751ac.npz

.

Average throughput: 139.1MiB/s

[train] downloading 734/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121115_0248_HARP2193_NOAA11614.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121115_0248_HARP2193_NOAA11614.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9f5145abc27aa8b541c931278782d551.npz

.

Average throughput: 74.3MiB/s

[train] downloading 735/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130515_1048_HARP2733_NOAA11742.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130515_1048_HARP2733_NOAA11742.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/42d428e260b32f6d1daf2bb43afba9ee.npz

.

Average throughput: 106.9MiB/s

[train] downloading 736/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100820_1448_HARP135_NOAA11100.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100820_1448_HARP135_NOAA11100.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fc1ac185969324b41ed642413d3c2121.npz

.

Average throughput: 54.4MiB/s

[train] downloading 737/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130808_2200_HARP3049_NOAA11813.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130808_2200_HARP3049_NOAA11813.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2241d677c6234b0b673a53e05da68384.npz

.

Average throughput: 81.2MiB/s

[train] downloading 738/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130122_2248_HARP2401_NOAA11659.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130122_2248_HARP2401_NOAA11659.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/94ee813dc47a75ceb70a961edd49cc6b.npz

.

Average throughput: 163.9MiB/s

[train] downloading 739/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110606_2200_HARP639_NOAA11228.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110606_2200_HARP639_NOAA11228.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/79d5059555c627c526953b2329c4dc9e.npz

.

Average throughput: 128.7MiB/s

[train] downloading 740/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110111_0712_HARP335_NOAA11143.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110111_0712_HARP335_NOAA11143.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a1de21dbee669ed9057e8dce68c09f0d.npz

.

Average throughput: 82.6MiB/s

[train] downloading 741/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110107_1324_HARP323_NOAA11140.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110107_1324_HARP323_NOAA11140.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f439b6633781b7361c2943de318825b8.npz

.

Average throughput: 154.4MiB/s

[train] downloading 742/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120515_0412_HARP1644_NOAA11477.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120515_0412_HARP1644_NOAA11477.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d32d2b8f1d3fdb439b2a9792bddb1319.npz

.

Average throughput: 106.2MiB/s

[train] downloading 743/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110304_0836_HARP393_NOAA11164.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110304_0836_HARP393_NOAA11164.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/86dd7746f16df5a5076e71da8935b19f.npz

.

Average throughput: 167.9MiB/s

[train] downloading 744/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130102_0236_HARP2337_NOAA11640.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130102_0236_HARP2337_NOAA11640.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/613bc738e1576736ce1ff16b7bd43c33.npz

.

Average throughput: 109.2MiB/s

[train] downloading 745/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121204_2336_HARP2245_NOAA11623.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121204_2336_HARP2245_NOAA11623.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cea84249f67a5a6dbb087db7248545f2.npz

.

Average throughput: 85.7MiB/s

[train] downloading 746/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130728_1924_HARP3011_NOAA11812.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130728_1924_HARP3011_NOAA11812.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/abd47dbc3ef2406925c6422fe2d082d0.npz

.

Average throughput: 99.6MiB/s

[train] downloading 747/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120111_2148_HARP1303_NOAA11398.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120111_2148_HARP1303_NOAA11398.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ff21e26879abb503f5fb8f8925d2fb81.npz

.

Average throughput: 65.4MiB/s

[train] downloading 748/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130407_0624_HARP2625_NOAA11716.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130407_0624_HARP2625_NOAA11716.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/84e1cde099683cf18ea8b96923721c6b.npz

.

Average throughput: 63.6MiB/s

[train] downloading 749/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120316_1812_HARP1471_NOAA11435.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120316_1812_HARP1471_NOAA11435.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/acc63dfdaef0faf30c1e2d869b9b3a8e.npz

.

Average throughput: 177.3MiB/s

[train] downloading 750/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100827_1312_HARP146_NOAA11102.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100827_1312_HARP146_NOAA11102.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0088802b9986b93e1aaaa81773070125.npz

.

Average throughput: 135.8MiB/s

[train] downloading 751/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131224_1624_HARP3520_NOAA11931.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131224_1624_HARP3520_NOAA11931.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/eb79626985bb7dfeac619bf283eb3c65.npz

.

Average throughput: 65.1MiB/s

[train] downloading 752/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111120_0000_HARP1080_NOAA11357.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111120_0000_HARP1080_NOAA11357.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/752195ec6ef98171699325422deedaa7.npz

.

Average throughput: 182.1MiB/s

[train] downloading 753/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110702_0524_HARP685_NOAA11243.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110702_0524_HARP685_NOAA11243.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c131e55f10ddd67a05277cd703920106.npz

.

Average throughput: 70.9MiB/s

[train] downloading 754/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120328_0412_HARP1492_NOAA11442.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120328_0412_HARP1492_NOAA11442.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4d932897d806977cf7f4f1f9f7a39a11.npz

.

Average throughput: 81.5MiB/s

[train] downloading 755/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120316_1836_HARP1464_NOAA11434.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120316_1836_HARP1464_NOAA11434.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/544faabd42d1cc1a8dd0d5ff9dc55ba0.npz



Average throughput: 187.9MiB/s

[train] downloading 756/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120923_0548_HARP2037_NOAA11573.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120923_0548_HARP2037_NOAA11573.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/49a927e1b4d413a23b165aa01423ca9d.npz

.

Average throughput: 172.9MiB/s

[train] downloading 757/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120518_1500_HARP1662_NOAA11484.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120518_1500_HARP1662_NOAA11484.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/46a30c29bc97c2f9e7cd582478bed96e.npz

.

Average throughput: 123.8MiB/s

[train] downloading 758/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110802_0724_HARP750_NOAA11261.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110802_0724_HARP750_NOAA11261.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/85a8788c335ead13b7741b5ccdaf91d1.npz

.

Average throughput: 75.3MiB/s

[train] downloading 759/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130731_1136_HARP2999_NOAA11801.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130731_1136_HARP2999_NOAA11801.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0d4ff114b44998ffde23200664705a58.npz

.

Average throughput: 104.3MiB/s

[train] downloading 760/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101218_0300_HARP297_NOAA11135.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101218_0300_HARP297_NOAA11135.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5e32f039cacdee5851cbc1e63d9b8677.npz

.

Average throughput: 87.6MiB/s

[train] downloading 761/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111224_2136_HARP1232_NOAA11385.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111224_2136_HARP1232_NOAA11385.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b7c86ee78014111905c7c7c7e855c8a3.npz

.

Average throughput: 141.5MiB/s

[train] downloading 762/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130514_0212_HARP2749_NOAA11749.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130514_0212_HARP2749_NOAA11749.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b041673a1dc783531846a2681e986912.npz

.

Average throughput: 205.0MiB/s

[train] downloading 763/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131123_0948_HARP3400_NOAA11903.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131123_0948_HARP3400_NOAA11903.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ee9737d13b8412069759a90027903093.npz

.

Average throughput: 157.4MiB/s

[train] downloading 764/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120905_0848_HARP1999_NOAA11563.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120905_0848_HARP1999_NOAA11563.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b6c635e0ba7f7c1db24ff8e79c97d519.npz

.

Average throughput: 83.4MiB/s

[train] downloading 765/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130315_0312_HARP2546_NOAA11692.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130315_0312_HARP2546_NOAA11692.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/dc4783219352e9acf4cdd3a7a9e3bc2a.npz

.

Average throughput: 119.8MiB/s

[train] downloading 766/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120602_0300_HARP1705_NOAA11492.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120602_0300_HARP1705_NOAA11492.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b2a43fe555a01381bde7c57270eb4141.npz

.

Average throughput: 164.5MiB/s

[train] downloading 767/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130515_1100_HARP2737_NOAA11746.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130515_1100_HARP2737_NOAA11746.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e2bc2b231b91fb25dde825a8e5520a57.npz

.

Average throughput: 118.5MiB/s

[train] downloading 768/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101209_0800_HARP284_NOAA11133.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101209_0800_HARP284_NOAA11133.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f96d812bb3a3eb8ce6e94e6c2dc3f6fb.npz

.

Average throughput: 186.1MiB/s

[train] downloading 769/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110105_0348_HARP323_NOAA11140.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110105_0348_HARP323_NOAA11140.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8503693de04e6336152e5b86762a2b60.npz

.

Average throughput: 174.6MiB/s

[train] downloading 770/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130509_0312_HARP2716_NOAA11738.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130509_0312_HARP2716_NOAA11738.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/07609a242a84a079c77b1d3352f4e2b4.npz

.

Average throughput: 120.9MiB/s

[train] downloading 771/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121021_1124_HARP2123_NOAA11594.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121021_1124_HARP2123_NOAA11594.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/519f9137764eb6909fbbc6422fd9e13a.npz

.

Average throughput: 160.3MiB/s

[train] downloading 772/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120902_1212_HARP1979_NOAA11558.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120902_1212_HARP1979_NOAA11558.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/10a2da5373520ab32bb8c38791eb006c.npz

.

Average throughput: 85.4MiB/s

[train] downloading 773/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110912_2236_HARP854_NOAA11294.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110912_2236_HARP854_NOAA11294.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/27f6800bbca22bad7ec8df254c4a6f2c.npz

.

Average throughput: 154.5MiB/s

[train] downloading 774/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101207_1312_HARP279_NOAA11131.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101207_1312_HARP279_NOAA11131.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9f72de5234291f44f53ad22a4b762a38.npz

.

Average throughput: 134.9MiB/s

[train] downloading 775/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110116_0048_HARP342_NOAA11146.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110116_0048_HARP342_NOAA11146.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ebf3c99f2239094aa2aa52d6708bd111.npz

.

Average throughput: 174.5MiB/s

[train] downloading 776/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131027_0124_HARP3309_NOAA11881.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131027_0124_HARP3309_NOAA11881.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2213462579cb3f109e1beb342b31f112.npz

.

Average throughput: 153.5MiB/s

[train] downloading 777/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120516_2300_HARP1657_NOAA11481.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120516_2300_HARP1657_NOAA11481.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fb354d6ebca860eb6f68ace6d6b8b866.npz

..

Average throughput: 103.8MiB/s

[train] downloading 778/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110816_2112_HARP799_NOAA11273.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110816_2112_HARP799_NOAA11273.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e1c9c7468d8d8301a8121609cc4c2d8b.npz

.

Average throughput: 146.2MiB/s

[train] downloading 779/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120116_0648_HARP1319_NOAA11400.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120116_0648_HARP1319_NOAA11400.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4f5b6531ebbfd89d3324394f34a79887.npz

.

Average throughput: 116.6MiB/s

[train] downloading 780/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131020_1348_HARP3288_NOAA11873.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131020_1348_HARP3288_NOAA11873.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7bebdace21531467a56e103a4c5bb512.npz

.

Average throughput: 107.8MiB/s

[train] downloading 781/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111124_1312_HARP1093_NOAA11353.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111124_1312_HARP1093_NOAA11353.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/79079e90c984f0ed5b4910643af0600c.npz

.

Average throughput: 91.1MiB/s

[train] downloading 782/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120201_2312_HARP1350_NOAA11410.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120201_2312_HARP1350_NOAA11410.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e6b0a0bc75631e289b5c20e79fb1b435.npz



Average throughput: 174.4MiB/s

[train] downloading 783/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110801_1500_HARP753_NOAA11263.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110801_1500_HARP753_NOAA11263.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2e5ea3ef61f3c34b189e899dd8df733b.npz

.

Average throughput: 163.8MiB/s

[train] downloading 784/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130502_1148_HARP2693_NOAA11731.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130502_1148_HARP2693_NOAA11731.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3ade1d1c237915b32f1139f151b445df.npz

..

Average throughput: 22.6MiB/s

[train] downloading 785/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100530_0000_HARP40_NOAA11075.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100530_0000_HARP40_NOAA11075.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/00e539ce71960c7c22313125d7946c8c.npz

.

Average throughput: 164.8MiB/s

[train] downloading 786/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130702_0736_HARP2910_NOAA11782.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130702_0736_HARP2910_NOAA11782.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/71890af34985f722e4665faa766691b0.npz

.

Average throughput: 141.8MiB/s

[train] downloading 787/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130709_1336_HARP2942_NOAA11789.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130709_1336_HARP2942_NOAA11789.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2a00861d6b82aaba47aa1dce247954ec.npz

.

Average throughput: 175.7MiB/s

[train] downloading 788/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130319_1724_HARP2557_NOAA11695.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130319_1724_HARP2557_NOAA11695.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1bf780bc5e4f587f46144a9ae995a9de.npz

.

Average throughput: 180.6MiB/s

[train] downloading 789/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130110_1700_HARP2358_NOAA11649.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130110_1700_HARP2358_NOAA11649.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b7312b83f4bc55b69e3ecab203f8ebe0.npz

.

Average throughput: 167.7MiB/s

[train] downloading 790/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130104_0436_HARP2331_NOAA11638.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130104_0436_HARP2331_NOAA11638.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2f91d77e2234fb624866e5d8c7d7432a.npz

.

Average throughput: 160.8MiB/s

[train] downloading 791/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121127_1524_HARP2249_NOAA11624.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121127_1524_HARP2249_NOAA11624.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/abcd9893d275e48388d0f163d442a094.npz

.

Average throughput: 91.0MiB/s

[train] downloading 792/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130820_0800_HARP3066_NOAA11820.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130820_0800_HARP3066_NOAA11820.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/dd1b7abcb7eeae7253ce65cd57fd525f.npz

.

Average throughput: 80.1MiB/s

[train] downloading 793/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131205_0912_HARP3437_NOAA11909.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131205_0912_HARP3437_NOAA11909.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7966e3955d5423fc41bb8141bbe2751b.npz

.

Average throughput: 170.7MiB/s

[train] downloading 794/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110816_1836_HARP781_NOAA11270.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110816_1836_HARP781_NOAA11270.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/76f0383edfe73443fcfe47be6e42b8dd.npz

.

Average throughput: 49.0MiB/s

[train] downloading 795/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130731_1024_HARP3012_NOAA11806.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130731_1024_HARP3012_NOAA11806.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a907e5f079200a6460656928278e171e.npz

.

Average throughput: 77.8MiB/s

[train] downloading 796/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110705_1512_HARP693_NOAA11246.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110705_1512_HARP693_NOAA11246.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2f69876cab0c7cec941122bd6d10dc34.npz

.

Average throughput: 167.3MiB/s

[train] downloading 797/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120723_2024_HARP1873_NOAA11526.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120723_2024_HARP1873_NOAA11526.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/97f303f3adcc7fd7c79eed8505254bb5.npz

.

Average throughput: 74.6MiB/s

[train] downloading 798/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120829_1512_HARP1959_NOAA11553.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120829_1512_HARP1959_NOAA11553.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d02b4b588086b2274835227a25cf1507.npz

.

Average throughput: 105.7MiB/s

[train] downloading 799/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100730_1724_HARP107_NOAA11094.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100730_1724_HARP107_NOAA11094.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e731d696f52da46ae7eccd8e42a3e469.npz

.

Average throughput: 176.2MiB/s

[train] downloading 800/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110629_1812_HARP686_NOAA11242.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110629_1812_HARP686_NOAA11242.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cfbd2d4ec558fb821d1df575919cf758.npz

.

Average throughput: 147.6MiB/s

[train] cached/checked 800/1650 files | elapsed 20.5 min
[train] downloading 801/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130203_0548_HARP2433_NOAA11665.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130203_0548_HARP2433_NOAA11665.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6494262d9d11b0c70a235d405d085529.npz

.

Average throughput: 77.5MiB/s

[train] downloading 802/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120522_0124_HARP1680_NOAA11487.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120522_0124_HARP1680_NOAA11487.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2d57266ad1cbe5fb7237b3016f0d8d2b.npz

.

Average throughput: 82.5MiB/s

[train] downloading 803/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121007_2236_HARP2098_NOAA11585.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121007_2236_HARP2098_NOAA11585.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/314d3c2f8bddd22b8a3d22eefef93fcc.npz

.

Average throughput: 65.4MiB/s

[train] downloading 804/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120509_2312_HARP1638_NOAA11476.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120509_2312_HARP1638_NOAA11476.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/921fce5004a3e2a0e997d4e88ef9442a.npz

.

Average throughput: 158.2MiB/s

[train] downloading 805/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131010_1336_HARP3259_NOAA11863.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131010_1336_HARP3259_NOAA11863.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/200fd1661fb99f53c4794481386cf016.npz

.

Average throughput: 173.4MiB/s

[train] downloading 806/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130924_0200_HARP3205_NOAA11849.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130924_0200_HARP3205_NOAA11849.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9ac1ec79aa9efcb1674489914d30577a.npz

.

Average throughput: 130.3MiB/s

[train] downloading 807/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121127_0224_HARP2227_NOAA11620.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121127_0224_HARP2227_NOAA11620.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/77095d7fe4e10ae31aa9102619b410c8.npz

.

Average throughput: 112.3MiB/s

[train] downloading 808/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130214_2336_HARP2471_NOAA11672.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130214_2336_HARP2471_NOAA11672.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5b088290a008fd43203e7cadad124a21.npz

.

Average throughput: 89.2MiB/s

[train] downloading 809/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110826_2012_HARP803_NOAA11274.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110826_2012_HARP803_NOAA11274.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8308c1082dbff62420778f1343fd4e51.npz

.

Average throughput: 110.3MiB/s

[train] downloading 810/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130816_1148_HARP3056_NOAA11818.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130816_1148_HARP3056_NOAA11818.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ec5269d3fad8bed616a7272945fcfda0.npz

.

Average throughput: 165.6MiB/s

[train] downloading 811/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131101_0536_HARP3321_NOAA11884.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131101_0536_HARP3321_NOAA11884.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7a8041071aa4dbb3e027c9c74400f39c.npz

.

Average throughput: 108.4MiB/s

[train] downloading 812/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130420_1736_HARP2661_NOAA11724.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130420_1736_HARP2661_NOAA11724.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/95daff02b5aa23216651b8b32871321c.npz

.

Average throughput: 87.1MiB/s

[train] downloading 813/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120605_0724_HARP1724_NOAA11494.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120605_0724_HARP1724_NOAA11494.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5f900a4f17b6b5b129acb48a80106ff8.npz

.

Average throughput: 139.4MiB/s

[train] downloading 814/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130808_1324_HARP3031_NOAA11810.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130808_1324_HARP3031_NOAA11810.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1ad91913349d3a1401da9a5bd5db42c8.npz

.

Average throughput: 154.4MiB/s

[train] downloading 815/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130421_1248_HARP2661_NOAA11724.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130421_1248_HARP2661_NOAA11724.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a2fa435f92f4d88bdc80af90790f653b.npz

.

Average throughput: 199.3MiB/s

[train] downloading 816/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130314_1248_HARP2546_NOAA11692.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130314_1248_HARP2546_NOAA11692.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8443175d372fdf0b33cce05230906a6a.npz

.

Average throughput: 112.4MiB/s

[train] downloading 817/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130923_0848_HARP3212_NOAA11845.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130923_0848_HARP3212_NOAA11845.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/eff395c15acde9b2b3084ff3d056fd60.npz

.

Average throughput: 84.9MiB/s

[train] downloading 818/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101018_0012_HARP221_NOAA11116.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101018_0012_HARP221_NOAA11116.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a3862a8961438e121c1851411470672f.npz

.

Average throughput: 123.2MiB/s

[train] downloading 819/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111109_1900_HARP1028_NOAA11339.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111109_1900_HARP1028_NOAA11339.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e7509867a0789c1ca14966a799ef811d.npz

.

Average throughput: 49.1MiB/s

[train] downloading 820/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110215_0112_HARP377_NOAA11158.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110215_0112_HARP377_NOAA11158.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5e332876556ebfdea446bf25681bc24a.npz

.

Average throughput: 129.0MiB/s

[train] downloading 821/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131019_1348_HARP3273_NOAA11868.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131019_1348_HARP3273_NOAA11868.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cb51711846a93f5971881b188a91a0b1.npz

.

Average throughput: 188.2MiB/s

[train] downloading 822/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111230_1636_HARP1249_NOAA11390.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111230_1636_HARP1249_NOAA11390.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c791a6d429418635eb0c259ab581e0a1.npz

.

Average throughput: 190.3MiB/s

[train] downloading 823/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120520_2124_HARP1662_NOAA11484.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120520_2124_HARP1662_NOAA11484.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/218b610f9c1fef866cbd556c90286b21.npz

.

Average throughput: 54.1MiB/s

[train] downloading 824/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120828_1012_HARP1951_NOAA11552.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120828_1012_HARP1951_NOAA11552.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/67b1af10aa35e4b704c4eb4164c04bf2.npz

.

Average throughput: 98.9MiB/s

[train] downloading 825/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110801_0236_HARP750_NOAA11261.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110801_0236_HARP750_NOAA11261.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/37dcc405f80ae979e9c587d17e20e922.npz

.

Average throughput: 131.5MiB/s

[train] downloading 826/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130913_1236_HARP3154_NOAA11838.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130913_1236_HARP3154_NOAA11838.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/815f4ee26d3b143f1bb536f3c5327846.npz

.

Average throughput: 72.4MiB/s

[train] downloading 827/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130627_0336_HARP2878_NOAA11777.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130627_0336_HARP2878_NOAA11777.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/317c03583b9e54e72ebd328441df23e6.npz

.

Average throughput: 103.3MiB/s

[train] downloading 828/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110628_0836_HARP686_NOAA11242.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110628_0836_HARP686_NOAA11242.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3ecbdfccc5544e45b01d3d1eb0f1d325.npz

.

Average throughput: 154.4MiB/s

[train] downloading 829/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110715_0200_HARP705_NOAA11248.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110715_0200_HARP705_NOAA11248.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d429572ac26ce64073ced6895f6ec8b9.npz

.

Average throughput: 121.9MiB/s

[train] downloading 830/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120318_0500_HARP1480_NOAA11437.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120318_0500_HARP1480_NOAA11437.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/66a4c187d8a8b37e38a2c2a5b9df8e99.npz

.

Average throughput: 88.8MiB/s

[train] downloading 831/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130804_1912_HARP3032_NOAA11811.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130804_1912_HARP3032_NOAA11811.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/263d54e9c0b6d41e7106365ad0c92e95.npz

.

Average throughput: 135.1MiB/s

[train] downloading 832/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110629_1324_HARP686_NOAA11242.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110629_1324_HARP686_NOAA11242.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7dd4a46a09f85f31fece036d843c3f16.npz

.

Average throughput: 145.5MiB/s

[train] downloading 833/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130115_2048_HARP2372_NOAA11654.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130115_2048_HARP2372_NOAA11654.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5fcc33a287ea463aaf452b120f10de08.npz

.

Average throughput: 71.4MiB/s

[train] downloading 834/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130407_1912_HARP2625_NOAA11716.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130407_1912_HARP2625_NOAA11716.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/024ea9a7dab3c2ea85d93d496d03e445.npz

.

Average throughput: 147.9MiB/s

[train] downloading 835/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130719_1312_HARP2964_NOAA11795.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130719_1312_HARP2964_NOAA11795.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d7f2a89ccee2c9b1336e06e655b97e39.npz

.

Average throughput: 97.9MiB/s

[train] downloading 836/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130131_1248_HARP2420_NOAA11663.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130131_1248_HARP2420_NOAA11663.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d854a5c7cfe8eeaf1e7da8519b4a816b.npz

.

Average throughput: 158.5MiB/s

[train] downloading 837/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111111_0148_HARP1038_NOAA11340.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111111_0148_HARP1038_NOAA11340.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f0a4a7c66cadda5f2126b0a08526f977.npz

.

Average throughput: 127.2MiB/s

[train] downloading 838/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110111_1024_HARP335_NOAA11143.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110111_1024_HARP335_NOAA11143.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a1faa3718d2c1dec4e7feb28e2494a2e.npz

.

Average throughput: 74.2MiB/s

[train] downloading 839/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120117_0636_HARP1313_NOAA11403.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120117_0636_HARP1313_NOAA11403.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5329b408e4a2c400425e0cf5782d2da7.npz

.

Average throughput: 113.1MiB/s

[train] downloading 840/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120915_0148_HARP2026_NOAA11569.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120915_0148_HARP2026_NOAA11569.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/014b0d3416776a1c4f2b965a4194ec90.npz

.

Average throughput: 108.9MiB/s

[train] downloading 841/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120822_0212_HARP1952_NOAA11551.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120822_0212_HARP1952_NOAA11551.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3b8cf5df0c19ed615d339617c194d65c.npz

.

Average throughput: 118.7MiB/s

[train] downloading 842/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131231_0912_HARP3535_NOAA11936.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131231_0912_HARP3535_NOAA11936.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2d93206d6e2cf7e6ed65f022ef1559d5.npz

.

Average throughput: 191.3MiB/s

[train] downloading 843/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120406_1436_HARP1527_NOAA11451.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120406_1436_HARP1527_NOAA11451.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b20647120071c0dc430869cb7218a1f5.npz

.

Average throughput: 175.0MiB/s

[train] downloading 844/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110215_0600_HARP377_NOAA11158.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110215_0600_HARP377_NOAA11158.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d642fb31cc64bbac2d76182f0f3d95ed.npz

.

Average throughput: 115.5MiB/s

[train] downloading 845/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120418_0824_HARP1578_NOAA11460.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120418_0824_HARP1578_NOAA11460.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0b7d03ebea5a1b57795be8a42ca67965.npz

.

Average throughput: 58.5MiB/s

[train] downloading 846/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131106_2012_HARP3330_NOAA11887.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131106_2012_HARP3330_NOAA11887.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/49941d58a168fb02c03341aa4ede78e6.npz

.

Average throughput: 173.5MiB/s

[train] downloading 847/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130922_1712_HARP3192_NOAA11847.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130922_1712_HARP3192_NOAA11847.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/27dbf04573b1a33e8a9a9e9445581bf2.npz



Average throughput: 186.6MiB/s

[train] downloading 848/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101020_1348_HARP220_NOAA11115.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101020_1348_HARP220_NOAA11115.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0cd2281bb21b400fc97b64d8ca4dd83b.npz

.

Average throughput: 143.3MiB/s

[train] downloading 849/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100816_2112_HARP128_NOAA11097.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100816_2112_HARP128_NOAA11097.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/741acd2e2891108ccb336cb1af011fd1.npz

.

Average throughput: 190.2MiB/s

[train] downloading 850/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120806_0800_HARP1907_NOAA11538.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120806_0800_HARP1907_NOAA11538.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/32973ab1a03bd1b9d1d520ffda2ea182.npz

.

Average throughput: 134.4MiB/s

[train] downloading 851/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111231_2300_HARP1249_NOAA11390.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111231_2300_HARP1249_NOAA11390.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/195808d144e2a39825389e4d8923a71c.npz

.

Average throughput: 147.3MiB/s

[train] downloading 852/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110504_0100_HARP556_NOAA11203.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110504_0100_HARP556_NOAA11203.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/37e929beb396a43b1ce8074ea5f9664c.npz

.

Average throughput: 117.8MiB/s

[train] downloading 853/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101130_1024_HARP274_NOAA11130.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101130_1024_HARP274_NOAA11130.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a00d7dcc13e4fa65341d7d9a6f818103.npz

.

Average throughput: 162.7MiB/s

[train] downloading 854/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130825_0336_HARP3116_NOAA11833.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130825_0336_HARP3116_NOAA11833.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e7d77f05f07adb191806114d780e420b.npz

.

Average throughput: 145.1MiB/s

[train] downloading 855/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130922_0400_HARP3205_NOAA11849.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130922_0400_HARP3205_NOAA11849.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9d8137ee8a5af63bedfa7baa13d6027e.npz

.

Average throughput: 74.1MiB/s

[train] downloading 856/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120910_0100_HARP2017_NOAA11568.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120910_0100_HARP2017_NOAA11568.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3633c8e8ce8f6e47a40c3d9e0bae71b7.npz

.

Average throughput: 132.5MiB/s

[train] downloading 857/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131127_1624_HARP3415_NOAA11906.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131127_1624_HARP3415_NOAA11906.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/280009d71139c9870535d531af7873f5.npz

.

Average throughput: 99.6MiB/s

[train] downloading 858/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110307_1312_HARP401_NOAA11166.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110307_1312_HARP401_NOAA11166.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/967d01cbe1f3da2374e54faa6f491543.npz

.

Average throughput: 183.1MiB/s

[train] downloading 859/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120616_1136_HARP1750_NOAA11504.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120616_1136_HARP1750_NOAA11504.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/77d530fd01e4c117e77d346dfd550ec6.npz

.

Average throughput: 142.7MiB/s

[train] downloading 860/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111002_0024_HARP902_NOAA11305.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111002_0024_HARP902_NOAA11305.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4e0ec7269a73562e6478dd3e29c17dfc.npz

.

Average throughput: 79.8MiB/s

[train] downloading 861/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120915_1712_HARP2028_NOAA11571.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120915_1712_HARP2028_NOAA11571.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/df56531e782b279a0812e4e87af5da7d.npz

.

Average throughput: 183.2MiB/s

[train] downloading 862/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120426_1712_HARP1603_NOAA11466.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120426_1712_HARP1603_NOAA11466.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/44647286d9026cf1772e1552d24317a9.npz

.

Average throughput: 77.3MiB/s

[train] downloading 863/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110701_1812_HARP685_NOAA11243.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110701_1812_HARP685_NOAA11243.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/bcf44a6de3191143c5068b7e4f4e549b.npz

.

Average throughput: 144.8MiB/s

[train] downloading 864/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120826_1636_HARP1951_NOAA11552.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120826_1636_HARP1951_NOAA11552.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9bb757a4b58a9e0dc1dca15745011846.npz

.

Average throughput: 57.2MiB/s

[train] downloading 865/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110904_1024_HARP833_NOAA11283.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110904_1024_HARP833_NOAA11283.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d38659652c8e0cdd769b178607b35c85.npz

.

Average throughput: 187.6MiB/s

[train] downloading 866/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110704_1512_HARP693_NOAA11246.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110704_1512_HARP693_NOAA11246.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8236348dca90d903b7d14709e5313120.npz

.

Average throughput: 146.8MiB/s

[train] downloading 867/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130601_1212_HARP2790_NOAA11758.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130601_1212_HARP2790_NOAA11758.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f4dea980bb0177acc3f661c6b392e144.npz

.

Average throughput: 87.7MiB/s

[train] downloading 868/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110214_2200_HARP377_NOAA11158.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110214_2200_HARP377_NOAA11158.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/40b00ceb6e3786484fbc3ea911d5015c.npz

.

Average throughput: 153.7MiB/s

[train] downloading 869/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111206_0448_HARP1165_NOAA11367.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111206_0448_HARP1165_NOAA11367.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/02ce17e26b7e1145dee13591ec036066.npz

.

Average throughput: 167.7MiB/s

[train] downloading 870/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111015_1612_HARP948_NOAA11317.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111015_1612_HARP948_NOAA11317.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/569e8107810e5d87b66d423b1a010de3.npz

.

Average throughput: 87.2MiB/s

[train] downloading 871/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120420_1500_HARP1582_NOAA11461.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120420_1500_HARP1582_NOAA11461.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/20e24a68dfc3f3c3b6569a1170e5e46f.npz

.

Average throughput: 112.5MiB/s

[train] downloading 872/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111207_0136_HARP1124_NOAA11363.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111207_0136_HARP1124_NOAA11363.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/377df9befb837d4ba0b58d1af047e8e1.npz

.

Average throughput: 107.9MiB/s

[train] downloading 873/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130620_0036_HARP2875_NOAA11776.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130620_0036_HARP2875_NOAA11776.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a8b5f02aa943b95cb28793790918e7b2.npz

.

Average throughput: 114.2MiB/s

[train] downloading 874/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131007_1900_HARP3252_NOAA11862.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131007_1900_HARP3252_NOAA11862.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5cf2498954d088a09bdb750c048bc01a.npz

.

Average throughput: 134.1MiB/s

[train] downloading 875/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131107_0248_HARP3344_NOAA11891.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131107_0248_HARP3344_NOAA11891.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f93e09d33f5d90d9c4f2e1369e6983f0.npz

.

Average throughput: 92.1MiB/s

[train] downloading 876/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110510_2136_HARP576_NOAA11207.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110510_2136_HARP576_NOAA11207.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d6d324edb2172bce415d0d31c0969843.npz

.

Average throughput: 131.5MiB/s

[train] downloading 877/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111001_1800_HARP902_NOAA11305.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111001_1800_HARP902_NOAA11305.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/484ec0c333f3173473b96d0e00c91c09.npz

.

Average throughput: 77.8MiB/s

[train] downloading 878/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131101_1824_HARP3321_NOAA11884.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131101_1824_HARP3321_NOAA11884.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/684cac9577ae6c8f40d3d10e152c81e1.npz

.

Average throughput: 66.1MiB/s

[train] downloading 879/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111021_1748_HARP975_NOAA11321.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111021_1748_HARP975_NOAA11321.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9862930545afe37055e50d83a4e43054.npz

.

Average throughput: 78.0MiB/s

[train] downloading 880/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120310_0000_HARP1449_NOAA11429.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120310_0000_HARP1449_NOAA11429.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/65a21f80fe8731465235631682bed336.npz



Average throughput: 195.9MiB/s

[train] downloading 881/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130408_1336_HARP2636_NOAA11718.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130408_1336_HARP2636_NOAA11718.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f1ae2a633eb95a40ecc1a4358103433f.npz

.

Average throughput: 52.4MiB/s

[train] downloading 882/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120530_2000_HARP1705_NOAA11492.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120530_2000_HARP1705_NOAA11492.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/afbe0c167d66376206c376350f2c2924.npz

.

Average throughput: 124.9MiB/s

[train] downloading 883/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130414_0300_HARP2651_NOAA11721.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130414_0300_HARP2651_NOAA11721.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a7978b8b5cd19dfc3c7f991075c398cb.npz

.

Average throughput: 122.6MiB/s

[train] downloading 884/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120114_1400_HARP1303_NOAA11398.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120114_1400_HARP1303_NOAA11398.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/210b78fa47dc56e011bbb10117d9040c.npz

.

Average throughput: 111.8MiB/s

[train] downloading 885/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121205_0336_HARP2259_NOAA11626.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121205_0336_HARP2259_NOAA11626.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d2c78ba3719032baed25d2411a04c11c.npz

.

Average throughput: 156.2MiB/s

[train] downloading 886/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131203_2100_HARP3443_NOAA11914.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131203_2100_HARP3443_NOAA11914.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e4eb3bcee39eb1177119fa09d08d6eec.npz



Average throughput: 180.9MiB/s

[train] downloading 887/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111006_2248_HARP926_NOAA11311.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111006_2248_HARP926_NOAA11311.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d7ae09220eab21846bef665b41e9e26b.npz

.

Average throughput: 105.9MiB/s

[train] downloading 888/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110808_0312_HARP765_NOAA11268.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110808_0312_HARP765_NOAA11268.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fb18bc0c9e1c9333d0f6d9b9c841bda4.npz

.

Average throughput: 59.2MiB/s

[train] downloading 889/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100815_0612_HARP131_NOAA11098.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100815_0612_HARP131_NOAA11098.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/713d2efabb0b09832cc4f569c6b9f317.npz

.

Average throughput: 118.9MiB/s

[train] downloading 890/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120319_2024_HARP1484_NOAA11440.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120319_2024_HARP1484_NOAA11440.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/89aa5a4cc66357a4cd3a5611ca9dedc4.npz

.

Average throughput: 26.7MiB/s

[train] downloading 891/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110314_1700_HARP415_NOAA11171.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110314_1700_HARP415_NOAA11171.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/84976b0b5ba14bf37b8ff88987fd966d.npz

.

Average throughput: 59.5MiB/s

[train] downloading 892/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120325_1624_HARP1497_NOAA11446.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120325_1624_HARP1497_NOAA11446.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/964c91774a83bb1d5f60f6a0629eea97.npz

.

Average throughput: 118.6MiB/s

[train] downloading 893/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120318_2148_HARP1480_NOAA11437.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120318_2148_HARP1480_NOAA11437.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f3cae9e025408efea31e707669d7bf8e.npz

.

Average throughput: 196.1MiB/s

[train] downloading 894/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130315_0136_HARP2546_NOAA11692.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130315_0136_HARP2546_NOAA11692.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5a9e99277c89de612de77a56b65fcd67.npz



Average throughput: 162.2MiB/s

[train] downloading 895/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120701_0300_HARP1807_NOAA11514.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120701_0300_HARP1807_NOAA11514.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/32b80c8c087e71c27c1f2ff7eaf8971a.npz

.

Average throughput: 175.2MiB/s

[train] downloading 896/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110827_1224_HARP812_NOAA11280.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110827_1224_HARP812_NOAA11280.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ac906c66387521f9c20e55740bfaa21e.npz

.

Average throughput: 78.4MiB/s

[train] downloading 897/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100803_0448_HARP104_NOAA11092.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100803_0448_HARP104_NOAA11092.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b4951708978b9086d1414ea2f275b452.npz

.

Average throughput: 138.7MiB/s

[train] downloading 898/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120929_0936_HARP2061_NOAA11580.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120929_0936_HARP2061_NOAA11580.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4fece82e20af86e19ce43f20e8e7120e.npz

.

Average throughput: 111.2MiB/s

[train] downloading 899/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110604_2248_HARP643_NOAA11229.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110604_2248_HARP643_NOAA11229.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/747aa173b91bbbca61397737dc669065.npz

.

Average throughput: 160.1MiB/s

[train] downloading 900/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101130_0848_HARP274_NOAA11130.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101130_0848_HARP274_NOAA11130.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a2b26953e49ea997d8ae1c5869258449.npz

.

Average throughput: 86.8MiB/s

[train] cached/checked 900/1650 files | elapsed 23.1 min
[train] downloading 901/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131228_0112_HARP3535_NOAA11936.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131228_0112_HARP3535_NOAA11936.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/643545d6ccb95ec9393f3508baaefe77.npz

.

Average throughput: 129.5MiB/s

[train] downloading 902/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110803_0048_HARP751_NOAA11264.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110803_0048_HARP751_NOAA11264.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1d44c48b859cf49f43ccb208b21e81ae.npz

.

Average throughput: 72.8MiB/s

[train] downloading 903/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120312_2336_HARP1461_NOAA11432.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120312_2336_HARP1461_NOAA11432.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f3054a48d29e0082c40ad9c42cd1803c.npz

.

Average throughput: 198.1MiB/s

[train] downloading 904/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111231_0524_HARP1249_NOAA11390.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111231_0524_HARP1249_NOAA11390.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/da1484fae00a8ed2cfaa73c8f4b20fde.npz

.

Average throughput: 97.6MiB/s

[train] downloading 905/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110724_1224_HARP740_NOAA11259.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110724_1224_HARP740_NOAA11259.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/416f8853d3ac86e0fb3ee08310f831f2.npz

.

Average throughput: 139.1MiB/s

[train] downloading 906/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131115_0612_HARP3368_NOAA11896.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131115_0612_HARP3368_NOAA11896.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5256c654bc2ed6f4d0f0ac78534fd4cd.npz

.

Average throughput: 134.1MiB/s

[train] downloading 907/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110516_1236_HARP602_NOAA11214.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110516_1236_HARP602_NOAA11214.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b5e4fb1fd5284699aa89a2d3351f4b01.npz

.

Average throughput: 148.4MiB/s

[train] downloading 908/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120525_1512_HARP1677_NOAA11486.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120525_1512_HARP1677_NOAA11486.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f755525c652f168d68316ac87452c887.npz

.

Average throughput: 163.2MiB/s

[train] downloading 909/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130513_0112_HARP2733_NOAA11742.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130513_0112_HARP2733_NOAA11742.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7f68a9eff35b69cb254f6257d7280d0b.npz

.

Average throughput: 179.6MiB/s

[train] downloading 910/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130129_1848_HARP2414_NOAA11662.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130129_1848_HARP2414_NOAA11662.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1b030b5102a9f9f3fb866219ca7f2f8f.npz

.

Average throughput: 124.5MiB/s

[train] downloading 911/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120615_2336_HARP1744_NOAA11507.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120615_2336_HARP1744_NOAA11507.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9b5b0ab79c9afb630fde76ca0ddd9353.npz

.

Average throughput: 142.6MiB/s

[train] downloading 912/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131117_1724_HARP3368_NOAA11896.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131117_1724_HARP3368_NOAA11896.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b689fb821dca0b92fd14868482c0c93f.npz



Average throughput: 150.1MiB/s

[train] downloading 913/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121231_2136_HARP2331_NOAA11638.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121231_2136_HARP2331_NOAA11638.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/312f83c7dfc5dfe965ace2a214f5f4a4.npz

.

Average throughput: 142.8MiB/s

[train] downloading 914/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130411_1724_HARP2651_NOAA11721.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130411_1724_HARP2651_NOAA11721.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/be0c70cc3d5c1fedb6714138a9040487.npz

.

Average throughput: 90.4MiB/s

[train] downloading 915/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110115_2312_HARP342_NOAA11146.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110115_2312_HARP342_NOAA11146.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6447a15152f9377c318daa52c57b8097.npz

.

Average throughput: 192.5MiB/s

[train] downloading 916/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110103_1536_HARP321_NOAA11139.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110103_1536_HARP321_NOAA11139.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/556a46299a36fc7db586d175a15454b3.npz

.

Average throughput: 162.1MiB/s

[train] downloading 917/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110723_0900_HARP744_NOAA11262.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110723_0900_HARP744_NOAA11262.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9995922485ab29c1dfd24258541e8773.npz

.

Average throughput: 170.4MiB/s

[train] downloading 918/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111102_1648_HARP1021_NOAA11334.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111102_1648_HARP1021_NOAA11334.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/dcb7046dd90956db57a2380e648959ab.npz

.

Average throughput: 161.7MiB/s

[train] downloading 919/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131124_2236_HARP3400_NOAA11903.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131124_2236_HARP3400_NOAA11903.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c5fe5e4b91c05df31d62eaf0915f77b3.npz

.

Average throughput: 91.2MiB/s

[train] downloading 920/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131019_2148_HARP3286_NOAA11872.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131019_2148_HARP3286_NOAA11872.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5af4fdb4a8fc9709bc7f51f3d41c9c35.npz

.

Average throughput: 147.4MiB/s

[train] downloading 921/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121018_1300_HARP2114_NOAA11592.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121018_1300_HARP2114_NOAA11592.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b9b40a447c2028ecc2d4f436977043c6.npz

.

Average throughput: 192.1MiB/s

[train] downloading 922/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110213_1400_HARP377_NOAA11158.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110213_1400_HARP377_NOAA11158.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e695bc5f3117fd627600c48279396693.npz

.

Average throughput: 174.3MiB/s

[train] downloading 923/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100901_0136_HARP145_NOAA11101.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100901_0136_HARP145_NOAA11101.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f8c421708b83f98d53c775ed07686d8f.npz

.

Average throughput: 88.9MiB/s

[train] downloading 924/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120124_0548_HARP1340_NOAA11409.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120124_0548_HARP1340_NOAA11409.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8c27de9b247f14deaf1659200c14c3f3.npz

.

Average throughput: 59.0MiB/s

[train] downloading 925/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120418_1136_HARP1578_NOAA11460.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120418_1136_HARP1578_NOAA11460.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/512b83afe7d2e6ab6879f9ed96aec27c.npz

.

Average throughput: 68.8MiB/s

[train] downloading 926/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110724_0112_HARP740_NOAA11259.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110724_0112_HARP740_NOAA11259.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/83e9baafb094c6fd8b21ad6f52d1771c.npz

.

Average throughput: 59.4MiB/s

[train] downloading 927/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120203_0536_HARP1367_NOAA11415.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120203_0536_HARP1367_NOAA11415.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a9251bdb4c48a7236c083ce9b0dff749.npz

.

Average throughput: 123.3MiB/s

[train] downloading 928/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131107_1624_HARP3341_NOAA11890.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131107_1624_HARP3341_NOAA11890.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a49e169ac7a221379bd280923cc64214.npz

.

Average throughput: 156.0MiB/s

[train] downloading 929/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131030_2136_HARP3321_NOAA11884.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131030_2136_HARP3321_NOAA11884.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1009c160f4dfd0c544a8235c2b716770.npz

.

Average throughput: 91.5MiB/s

[train] downloading 930/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120212_1224_HARP1389_NOAA11416.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120212_1224_HARP1389_NOAA11416.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8ff34bb7e8d42f58a4e4ff8550eb4c91.npz

.

Average throughput: 155.7MiB/s

[train] downloading 931/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110907_1648_HARP833_NOAA11283.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110907_1648_HARP833_NOAA11283.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fbb86bbbc80d71561473e276161c4126.npz



Average throughput: 190.5MiB/s

[train] downloading 932/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101130_2324_HARP270_NOAA11128.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101130_2324_HARP270_NOAA11128.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2da71f795b902ce7e3bbe53c33966c1d.npz

.

Average throughput: 68.9MiB/s

[train] downloading 933/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111101_1824_HARP1021_NOAA11334.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111101_1824_HARP1021_NOAA11334.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d92361d9a336d6e27b5a574ddb1e8f82.npz

.

Average throughput: 106.1MiB/s

[train] downloading 934/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120221_1200_HARP1405_NOAA11422.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120221_1200_HARP1405_NOAA11422.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1f76962aee823b78205fedc2910e9e59.npz



Average throughput: 167.1MiB/s

[train] downloading 935/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111013_0312_HARP932_NOAA11313.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111013_0312_HARP932_NOAA11313.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8916da4b3c3da847c37135e50342d515.npz

.

Average throughput: 90.3MiB/s

[train] downloading 936/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110713_0800_HARP702_NOAA11249.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110713_0800_HARP702_NOAA11249.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6ab293651f48b34b82140683b3d25af8.npz

.

Average throughput: 65.8MiB/s

[train] downloading 937/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110606_1124_HARP651_NOAA11231.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110606_1124_HARP651_NOAA11231.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b1ef15f1002aea59b447c74388db1687.npz

.

Average throughput: 160.3MiB/s

[train] downloading 938/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130217_0436_HARP2469_NOAA11671.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130217_0436_HARP2469_NOAA11671.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/078706854f7fa6eabecf49fc7dcd6ce4.npz

.

Average throughput: 68.2MiB/s

[train] downloading 939/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120904_0636_HARP2007_NOAA11565.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120904_0636_HARP2007_NOAA11565.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/604f4d8242ae43aaa128b29215c60897.npz

.

Average throughput: 99.1MiB/s

[train] downloading 940/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130808_1224_HARP3049_NOAA11813.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130808_1224_HARP3049_NOAA11813.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9b91fbebedacb7a8d9c21a80f64eea0c.npz

.

Average throughput: 109.7MiB/s

[train] downloading 941/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120317_1236_HARP1464_NOAA11434.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120317_1236_HARP1464_NOAA11434.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6b13f39c709f09e3f59ee41017917559.npz

.

Average throughput: 132.4MiB/s

[train] downloading 942/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110810_0412_HARP759_NOAA11266.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110810_0412_HARP759_NOAA11266.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9dc7fc72747c5163953d8b02c29c3f91.npz

.

Average throughput: 63.8MiB/s

[train] downloading 943/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120528_1336_HARP1701_NOAA11490.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120528_1336_HARP1701_NOAA11490.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c402ff00adce5f16d422470765c1f408.npz

.

Average throughput: 133.3MiB/s

[train] downloading 944/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110801_1348_HARP750_NOAA11261.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110801_1348_HARP750_NOAA11261.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e1060aef1fd5c1517f660a61a0c953ce.npz

.

Average throughput: 108.8MiB/s

[train] downloading 945/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101016_0948_HARP211_NOAA11112.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101016_0948_HARP211_NOAA11112.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6dadd5a614a90a6d2737c225e571209c.npz

.

Average throughput: 174.9MiB/s

[train] downloading 946/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110615_0724_HARP662_NOAA11235.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110615_0724_HARP662_NOAA11235.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/75adc3e664fe2689f3fb7d8ce7af5ebf.npz

.

Average throughput: 137.7MiB/s

[train] downloading 947/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110214_1224_HARP377_NOAA11158.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110214_1224_HARP377_NOAA11158.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b14702d5f7600d651eb1aebe27743e5d.npz

.

Average throughput: 145.7MiB/s

[train] downloading 948/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110826_2024_HARP812_NOAA11280.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110826_2024_HARP812_NOAA11280.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3c0ff111c61636164d9255176dd5428a.npz

.

Average throughput: 188.9MiB/s

[train] downloading 949/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120521_1512_HARP1662_NOAA11484.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120521_1512_HARP1662_NOAA11484.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/39cda12a6723ebe190e3b79858319241.npz

.

Average throughput: 54.4MiB/s

[train] downloading 950/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120328_2124_HARP1492_NOAA11442.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120328_2124_HARP1492_NOAA11442.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9a9576bc22ef967df1aa3aa00f88c95a.npz

.

Average throughput: 130.5MiB/s

[train] downloading 951/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110723_1948_HARP740_NOAA11259.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110723_1948_HARP740_NOAA11259.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/16dd590a905ec4d95a2e9e5f03156524.npz

.

Average throughput: 145.1MiB/s

[train] downloading 952/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111230_1000_HARP1237_NOAA11386.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111230_1000_HARP1237_NOAA11386.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/aacb3b41a71845b582034fd00c8cc53a.npz

.

Average throughput: 176.3MiB/s

[train] downloading 953/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110830_1948_HARP814_NOAA11277.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110830_1948_HARP814_NOAA11277.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/51f5e6eb02224439612857b3bc178c68.npz

.

Average throughput: 149.2MiB/s

[train] downloading 954/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120413_0448_HARP1549_NOAA11455.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120413_0448_HARP1549_NOAA11455.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/33440f7e081747e070eeaa864be578fb.npz

.

Average throughput: 95.8MiB/s

[train] downloading 955/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130512_2136_HARP2727_NOAA11741.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130512_2136_HARP2727_NOAA11741.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/dc6a2c742fbd4525f142afe0a3d8d065.npz

.

Average throughput: 114.0MiB/s

[train] downloading 956/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120131_1648_HARP1350_NOAA11410.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120131_1648_HARP1350_NOAA11410.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9ce2bcf60e7948564ff91a31cc66806c.npz

.

Average throughput: 130.1MiB/s

[train] downloading 957/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121029_2300_HARP2143_NOAA11599.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121029_2300_HARP2143_NOAA11599.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b645d050ae1e5de308a111eecd0b204c.npz

.

Average throughput: 187.5MiB/s

[train] downloading 958/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110412_1624_HARP495_NOAA11190.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110412_1624_HARP495_NOAA11190.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/386853dfd5543e133b7fac3a4562ed42.npz

.

Average throughput: 197.0MiB/s

[train] downloading 959/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130619_0024_HARP2861_NOAA11773.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130619_0024_HARP2861_NOAA11773.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/978362ccf1347339a60f2ace6d4bad67.npz

.

Average throughput: 91.3MiB/s

[train] downloading 960/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120810_2036_HARP1930_NOAA11542.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120810_2036_HARP1930_NOAA11542.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/521fc849e942ef26a549dc95f5611244.npz

.

Average throughput: 180.2MiB/s

[train] downloading 961/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130926_0348_HARP3217_NOAA11851.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130926_0348_HARP3217_NOAA11851.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/867f940aa0120c7a8d03593e87e9c5fd.npz

.

Average throughput: 94.0MiB/s

[train] downloading 962/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110508_0712_HARP576_NOAA11207.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110508_0712_HARP576_NOAA11207.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5c1a16a63e59bcf4a17d54bb6ea0705d.npz

.

Average throughput: 146.4MiB/s

[train] downloading 963/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121030_1500_HARP2143_NOAA11599.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121030_1500_HARP2143_NOAA11599.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e079779d55ca6f036e4ac79b95e5c2af.npz

.

Average throughput: 156.3MiB/s

[train] downloading 964/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130121_1000_HARP2401_NOAA11659.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130121_1000_HARP2401_NOAA11659.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/02bee2f8be958101d1b3f6deab8ed92f.npz

.

Average throughput: 198.4MiB/s

[train] downloading 965/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110711_1112_HARP702_NOAA11249.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110711_1112_HARP702_NOAA11249.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/abc9c9ac7679e293aa7332f9201d51e5.npz

.

Average throughput: 77.5MiB/s

[train] downloading 966/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110213_0600_HARP377_NOAA11158.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110213_0600_HARP377_NOAA11158.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e8fabd55e64cfc5334b9725c2172329c.npz

.

Average throughput: 142.3MiB/s

[train] downloading 967/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121128_1524_HARP2249_NOAA11624.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121128_1524_HARP2249_NOAA11624.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f1f1fcf616c89882de914710bf3b2df2.npz

.

Average throughput: 141.5MiB/s

[train] downloading 968/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110220_1236_HARP384_NOAA11160.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110220_1236_HARP384_NOAA11160.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ac82be5a66413831cf11d3722fac6899.npz

.

Average throughput: 73.6MiB/s

[train] downloading 969/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110828_1700_HARP819_NOAA11284.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110828_1700_HARP819_NOAA11284.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/db716fed76e6eeb329de3447d5273ff9.npz

.

Average throughput: 157.2MiB/s

[train] downloading 970/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111216_1612_HARP1186_NOAA11378.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111216_1612_HARP1186_NOAA11378.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3b462c78ce75050245245286cb111ccc.npz

.

Average throughput: 105.6MiB/s

[train] downloading 971/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110705_1024_HARP693_NOAA11246.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110705_1024_HARP693_NOAA11246.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/44fbdd3b077c69d5db3202643e0c3978.npz

.

Average throughput: 170.1MiB/s

[train] downloading 972/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130418_1148_HARP2663_NOAA11723.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130418_1148_HARP2663_NOAA11723.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/542482680c67cc2371266a252d429de4.npz

.

Average throughput: 126.1MiB/s

[train] downloading 973/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120823_1948_HARP1946_NOAA11548.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120823_1948_HARP1946_NOAA11548.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/04a72872da3179103dc8276104bb8e59.npz

.

Average throughput: 133.6MiB/s

[train] downloading 974/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130707_2348_HARP2920_NOAA11785.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130707_2348_HARP2920_NOAA11785.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/185c7226053660a6d631a5494c4ea56a.npz

.

Average throughput: 94.0MiB/s

[train] downloading 975/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130816_1324_HARP3056_NOAA11818.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130816_1324_HARP3056_NOAA11818.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/668d5667ac56b12891f788d7caac49d5.npz

.

Average throughput: 151.7MiB/s

[train] downloading 976/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100620_2124_HARP57_NOAA11082.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100620_2124_HARP57_NOAA11082.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/134e6f8e77fecceac2c8f9213f401cca.npz

.

Average throughput: 143.8MiB/s

[train] downloading 977/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110429_1836_HARP538_NOAA11200.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110429_1836_HARP538_NOAA11200.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a38e356ab2c4f69affbfbe75d61587bf.npz

.

Average throughput: 171.0MiB/s

[train] downloading 978/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130722_1512_HARP2982_NOAA11798.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130722_1512_HARP2982_NOAA11798.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5a0a13ae769fe394d76ab7155f5459c3.npz

.

Average throughput: 38.0MiB/s

[train] downloading 979/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120930_1348_HARP2069_NOAA11582.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120930_1348_HARP2069_NOAA11582.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1565c000ccc9e0b1298677b601a371bf.npz

.

Average throughput: 172.3MiB/s

[train] downloading 980/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110701_1648_HARP684_NOAA11244.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110701_1648_HARP684_NOAA11244.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/02b48511472c7d07ec75466c16092c71.npz

.

Average throughput: 144.3MiB/s

[train] downloading 981/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130210_1212_HARP2450_NOAA11669.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130210_1212_HARP2450_NOAA11669.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c1cb87ed845162d0efb640f7334f736a.npz

.

Average throughput: 134.3MiB/s

[train] downloading 982/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131230_2336_HARP3535_NOAA11936.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131230_2336_HARP3535_NOAA11936.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3f28e1a62988c11baa41ea77ef65cbc4.npz

.

Average throughput: 156.4MiB/s

[train] downloading 983/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110718_1048_HARP714_NOAA11251.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110718_1048_HARP714_NOAA11251.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6d9549353dc8bc1fc04698f4516aca81.npz

.

Average throughput: 69.8MiB/s

[train] downloading 984/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110608_0012_HARP651_NOAA11231.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110608_0012_HARP651_NOAA11231.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/552bd0d124769863a3f3f2e02d11c203.npz

.

Average throughput: 207.4MiB/s

[train] downloading 985/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120730_1424_HARP1877_NOAA11527.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120730_1424_HARP1877_NOAA11527.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ec41beeb2d65f93a17ed1625f64759ef.npz

.

Average throughput: 142.7MiB/s

[train] downloading 986/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110215_1400_HARP377_NOAA11158.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110215_1400_HARP377_NOAA11158.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6eb2ca287293577cc974ebb372fbc43e.npz

.

Average throughput: 169.6MiB/s

[train] downloading 987/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130918_0212_HARP3176_NOAA11841.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130918_0212_HARP3176_NOAA11841.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d75d68953a6f12df1d6e61122613d85c.npz

.

Average throughput: 180.1MiB/s

[train] downloading 988/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121112_1224_HARP2181_NOAA11609.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121112_1224_HARP2181_NOAA11609.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0952dd69ebcab22d631c195aa6fdbd36.npz

.

Average throughput: 147.3MiB/s

[train] downloading 989/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130102_2312_HARP2331_NOAA11638.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130102_2312_HARP2331_NOAA11638.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e9279246c945352c358d4bedb8fbb6e4.npz

.

Average throughput: 64.3MiB/s

[train] downloading 990/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120308_1612_HARP1447_NOAA11428.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120308_1612_HARP1447_NOAA11428.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/947369f1fa8c72db2a7068a6157df4ce.npz

.

Average throughput: 88.1MiB/s

[train] downloading 991/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130102_2336_HARP2338_NOAA11641.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130102_2336_HARP2338_NOAA11641.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e09b30ea3078b4098d08b9be398a84ce.npz

.

Average throughput: 82.9MiB/s

[train] downloading 992/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130711_2336_HARP2945_NOAA11794.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130711_2336_HARP2945_NOAA11794.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7627b5da5fc03514f4769d8553a80830.npz

.

Average throughput: 124.4MiB/s

[train] downloading 993/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110307_2112_HARP401_NOAA11166.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110307_2112_HARP401_NOAA11166.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/72a02370e075290dac694a80f00a86a3.npz

.

Average throughput: 118.3MiB/s

[train] downloading 994/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110902_1636_HARP814_NOAA11277.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110902_1636_HARP814_NOAA11277.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a7da19f09ec009d9c39a490d7a510b31.npz

.

Average throughput: 157.0MiB/s

[train] downloading 995/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130513_0048_HARP2727_NOAA11741.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130513_0048_HARP2727_NOAA11741.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6fc33c581d221ad62e5ffaabbbe33352.npz

.

Average throughput: 136.3MiB/s

[train] downloading 996/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120112_0736_HARP1300_NOAA11395.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120112_0736_HARP1300_NOAA11395.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/48630b616e0afa43395b853328be26d2.npz

.

Average throughput: 133.8MiB/s

[train] downloading 997/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100604_0736_HARP46_NOAA11078.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100604_0736_HARP46_NOAA11078.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6ab152bd60e1475d183e38b35f9bfd87.npz

.

Average throughput: 122.0MiB/s

[train] downloading 998/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120823_2312_HARP1942_NOAA11546.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120823_2312_HARP1942_NOAA11546.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/56aae673c005aa2b60b1c9caca7d6cd7.npz

.

Average throughput: 161.3MiB/s

[train] downloading 999/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121110_1048_HARP2181_NOAA11609.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121110_1048_HARP2181_NOAA11609.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6838338438fb9903d011729a876d26cc.npz

.

Average throughput: 35.9MiB/s

[train] downloading 1000/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130722_2036_HARP2982_NOAA11798.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130722_2036_HARP2982_NOAA11798.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/da099dce0e42032ddc781eb7bb55e599.npz

.

Average throughput: 126.8MiB/s

[train] cached/checked 1000/1650 files | elapsed 25.7 min
[train] downloading 1001/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130529_0548_HARP2779_NOAA11757.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130529_0548_HARP2779_NOAA11757.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/61e527ee9218da5f7faa0b74fea15cbf.npz

.

Average throughput: 92.6MiB/s

[train] downloading 1002/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130717_1000_HARP2954_NOAA11792.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130717_1000_HARP2954_NOAA11792.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/06647bcb915c29c3a19f5ba3f48a4b8b.npz

.

Average throughput: 76.8MiB/s

[train] downloading 1003/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130725_1848_HARP2981_NOAA11799.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130725_1848_HARP2981_NOAA11799.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/df40924898438d95653e5f03b1756b0a.npz

.

Average throughput: 180.8MiB/s

[train] downloading 1004/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130311_0312_HARP2522_NOAA11689.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130311_0312_HARP2522_NOAA11689.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/05ca0cb9efc6580c48baf1abb5c7cf51.npz

.

Average throughput: 29.3MiB/s

[train] downloading 1005/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110825_1700_HARP819_NOAA11284.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110825_1700_HARP819_NOAA11284.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/80cd38b5de11e7996ea3b5481a37e396.npz

.

Average throughput: 98.3MiB/s

[train] downloading 1006/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130527_0348_HARP2760_NOAA11753.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130527_0348_HARP2760_NOAA11753.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6b2a0e69443e6c872c3bb6fde509f000.npz

.

Average throughput: 130.5MiB/s

[train] downloading 1007/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130311_1336_HARP2533_NOAA11690.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130311_1336_HARP2533_NOAA11690.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6b52a1863ed6502be77b90de49b26a9f.npz

.

Average throughput: 93.6MiB/s

[train] downloading 1008/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111014_1524_HARP950_NOAA11316.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111014_1524_HARP950_NOAA11316.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8e2989e53e0c111ff777690b500930c1.npz

.

Average throughput: 94.4MiB/s

[train] downloading 1009/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130522_0612_HARP2748_NOAA11748.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130522_0612_HARP2748_NOAA11748.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/261f8338a8f90e52de4e665559ad8803.npz

.

Average throughput: 88.6MiB/s

[train] downloading 1010/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120605_0100_HARP1722_NOAA11493.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120605_0100_HARP1722_NOAA11493.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f10a8167b8259afbc8e2b4ae0914c17e.npz

.

Average throughput: 156.8MiB/s

[train] downloading 1011/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131005_1724_HARP3252_NOAA11862.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131005_1724_HARP3252_NOAA11862.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fae4192660a24c44499895819617a857.npz

.

Average throughput: 108.3MiB/s

[train] downloading 1012/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110909_1036_HARP846_NOAA11288.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110909_1036_HARP846_NOAA11288.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b42e0fdac95c6bc709a893608fd79bba.npz

.

Average throughput: 174.4MiB/s

[train] downloading 1013/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131024_0024_HARP3291_NOAA11875.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131024_0024_HARP3291_NOAA11875.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e398b3117d2735e43ebd3d46b2bf00c5.npz

.

Average throughput: 175.8MiB/s

[train] downloading 1014/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131021_1348_HARP3286_NOAA11872.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131021_1348_HARP3286_NOAA11872.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/af00e5f6a2c41c6298ef68dd75cc9d46.npz

.

Average throughput: 112.0MiB/s

[train] downloading 1015/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101024_0848_HARP223_NOAA11118.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101024_0848_HARP223_NOAA11118.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/13668223943676b98f5388b2742d047b.npz

.

Average throughput: 175.3MiB/s

[train] downloading 1016/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130102_2036_HARP2329_NOAA11639.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130102_2036_HARP2329_NOAA11639.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/585c0b5f2b71cd5f2c87854acb31ff30.npz

.

Average throughput: 62.1MiB/s

[train] downloading 1017/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110902_2124_HARP814_NOAA11277.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110902_2124_HARP814_NOAA11277.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d76f097155478ee68ecc88a25166ab0b.npz

.

Average throughput: 89.8MiB/s

[train] downloading 1018/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120623_1148_HARP1789_NOAA11511.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120623_1148_HARP1789_NOAA11511.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6acf4243963822d23d2d9162ef9480b8.npz

.

Average throughput: 69.4MiB/s

[train] downloading 1019/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110711_1300_HARP695_NOAA11247.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110711_1300_HARP695_NOAA11247.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f2885e7ac3c410c1a783b3e1ff2fc1d1.npz

.

Average throughput: 137.2MiB/s

[train] downloading 1020/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100924_2248_HARP190_NOAA11110.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100924_2248_HARP190_NOAA11110.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/49d188ecf67cb573e732504a3f03b58f.npz

.

Average throughput: 172.7MiB/s

[train] downloading 1021/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100609_0648_HARP49_NOAA11079.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100609_0648_HARP49_NOAA11079.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e8f1e3d87aa048616251f5a53bf0a54a.npz

.

Average throughput: 174.0MiB/s

[train] downloading 1022/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130403_0512_HARP2599_NOAA11710.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130403_0512_HARP2599_NOAA11710.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c7e279112f93e39aeadccd2a278aaf39.npz

.

Average throughput: 60.7MiB/s

[train] downloading 1023/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101021_0824_HARP218_NOAA11113.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101021_0824_HARP218_NOAA11113.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ffbb563ab8c66aefe7c3fd98406d091e.npz

.

Average throughput: 199.8MiB/s

[train] downloading 1024/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120814_0936_HARP1931_NOAA11543.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120814_0936_HARP1931_NOAA11543.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/133d7bfceafdc4ab49c53caf67d8aa96.npz

.

Average throughput: 146.9MiB/s

[train] downloading 1025/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111213_1800_HARP1171_NOAA11375.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111213_1800_HARP1171_NOAA11375.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e48c6e244da3fc03081127719d42946e.npz

.

Average throughput: 69.6MiB/s

[train] downloading 1026/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111117_0048_HARP1066_NOAA11346.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111117_0048_HARP1066_NOAA11346.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ffefd410a36183b37e3d9a878a0f2f0d.npz

.

Average throughput: 113.4MiB/s

[train] downloading 1027/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130720_0224_HARP2982_NOAA11798.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130720_0224_HARP2982_NOAA11798.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/951d65c613e2f80119ce8066a98de213.npz

.

Average throughput: 132.3MiB/s

[train] downloading 1028/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111106_1600_HARP1019_NOAA11336.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111106_1600_HARP1019_NOAA11336.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0ced57b196d6c21a70cf35920ec632e0.npz

.

Average throughput: 167.8MiB/s

[train] downloading 1029/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120903_0300_HARP1990_NOAA11562.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120903_0300_HARP1990_NOAA11562.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ca1b1cc3cfa386cf7247c139b3d80ec9.npz

.

Average throughput: 184.1MiB/s

[train] downloading 1030/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100916_1912_HARP175_NOAA11106.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100916_1912_HARP175_NOAA11106.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f926e8dd7a02bb2bef9d0edc655fd029.npz

.

Average throughput: 181.2MiB/s

[train] downloading 1031/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130718_1248_HARP2966_NOAA11797.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130718_1248_HARP2966_NOAA11797.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a77a93343999cfe19bf2032d5c3bf6f5.npz

.

Average throughput: 165.5MiB/s

[train] downloading 1032/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120627_1624_HARP1795_NOAA11512.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120627_1624_HARP1795_NOAA11512.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/48ad9695b3560a468661bc1b355012d3.npz

.

Average throughput: 37.1MiB/s

[train] downloading 1033/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110910_0236_HARP846_NOAA11288.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110910_0236_HARP846_NOAA11288.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ad00fb89b787c6ea1cf852d80e74d5ad.npz

.

Average throughput: 42.1MiB/s

[train] downloading 1034/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130818_0936_HARP3066_NOAA11820.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130818_0936_HARP3066_NOAA11820.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f810e10ac274c62ccd658edf577720fd.npz

.

Average throughput: 111.5MiB/s

[train] downloading 1035/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111203_0448_HARP1124_NOAA11363.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111203_0448_HARP1124_NOAA11363.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/87790fd32e1a8d8740796841986420f9.npz

.

Average throughput: 122.5MiB/s

[train] downloading 1036/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110622_1024_HARP676_NOAA11239.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110622_1024_HARP676_NOAA11239.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/452d0f30b1b20dac457ee2d0de1481e7.npz

.

Average throughput: 134.9MiB/s

[train] downloading 1037/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130419_0524_HARP2663_NOAA11723.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130419_0524_HARP2663_NOAA11723.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7312f9f4e6e7c176590a570ba228e767.npz

.

Average throughput: 113.8MiB/s

[train] downloading 1038/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100630_0536_HARP67_NOAA11085.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100630_0536_HARP67_NOAA11085.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/281e741bbc1bd6b42c659c270d118039.npz

.

Average throughput: 156.2MiB/s

[train] downloading 1039/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110415_0136_HARP494_NOAA11187.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110415_0136_HARP494_NOAA11187.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/08d5b4c85d1cbb474400802456a7fa6f.npz

.

Average throughput: 159.6MiB/s

[train] downloading 1040/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110203_0548_HARP355_NOAA11150.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110203_0548_HARP355_NOAA11150.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/daf686e9326875d03b5274aaa8b76ff0.npz

.

Average throughput: 126.7MiB/s

[train] downloading 1041/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111218_0948_HARP1186_NOAA11378.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111218_0948_HARP1186_NOAA11378.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fdfeed292919510b99074433de1d90fc.npz

.

Average throughput: 187.1MiB/s

[train] downloading 1042/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131025_1612_HARP3291_NOAA11875.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131025_1612_HARP3291_NOAA11875.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3d43c883b4cfbb08fbe80e6ee319c56c.npz

.

Average throughput: 131.2MiB/s

[train] downloading 1043/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130112_0100_HARP2371_NOAA11657.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130112_0100_HARP2371_NOAA11657.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1df1b3b40d530dbb767c8f8aa3632412.npz

.

Average throughput: 99.2MiB/s

[train] downloading 1044/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100606_1400_HARP46_NOAA11078.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100606_1400_HARP46_NOAA11078.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/31dcc45c97e4a253bebc2bc8ff50f2d5.npz

.

Average throughput: 68.1MiB/s

[train] downloading 1045/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130223_1448_HARP2493_NOAA11677.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130223_1448_HARP2493_NOAA11677.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/00a1b11b6e6a99b3cf8574cf33a4f905.npz

.

Average throughput: 97.3MiB/s

[train] downloading 1046/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130819_1248_HARP3066_NOAA11820.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130819_1248_HARP3066_NOAA11820.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/993ad0f7dbd34d2ac9161e9a2d3ecd0e.npz



Average throughput: 192.2MiB/s

[train] downloading 1047/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110906_2312_HARP833_NOAA11283.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110906_2312_HARP833_NOAA11283.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/83cf681eae2a18852a99dc04d31cdc7b.npz

.

Average throughput: 111.9MiB/s

[train] downloading 1048/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111001_1936_HARP902_NOAA11305.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111001_1936_HARP902_NOAA11305.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5257435fa54b711442e63a6f4ffd25c1.npz

.

Average throughput: 109.2MiB/s

[train] downloading 1049/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110327_1712_HARP438_NOAA11177.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110327_1712_HARP438_NOAA11177.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/791f253572b5df6b096eb88ce4c1c5d1.npz

.

Average throughput: 183.3MiB/s

[train] downloading 1050/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110711_1124_HARP695_NOAA11247.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110711_1124_HARP695_NOAA11247.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e350ef04995995cfb1c6da900510c5cf.npz

.

Average throughput: 156.1MiB/s

[train] downloading 1051/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110501_1900_HARP532_NOAA11201.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110501_1900_HARP532_NOAA11201.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0eec345d800583b300b80081bea650a7.npz

.

Average throughput: 136.7MiB/s

[train] downloading 1052/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130407_0124_HARP2605_NOAA11711.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130407_0124_HARP2605_NOAA11711.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ca189b17b831c697854578222231fb0e.npz

.

Average throughput: 68.4MiB/s

[train] downloading 1053/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110902_0036_HARP814_NOAA11277.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110902_0036_HARP814_NOAA11277.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/83dd062276bac6ecf024700096acf4de.npz

.

Average throughput: 134.7MiB/s

[train] downloading 1054/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111204_1348_HARP1126_NOAA11364.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111204_1348_HARP1126_NOAA11364.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/81edaedd22fa28ec5e3c69eea13eb7ab.npz

.

Average throughput: 110.7MiB/s

[train] downloading 1055/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111130_0336_HARP1113_NOAA11358.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111130_0336_HARP1113_NOAA11358.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a5170ac5b2bef7638d7c05959e933fed.npz

.

Average throughput: 117.7MiB/s

[train] downloading 1056/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120503_2024_HARP1621_NOAA11470.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120503_2024_HARP1621_NOAA11470.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/386ebeb5419f5e69622ddfad04f2ef5d.npz

.

Average throughput: 101.0MiB/s

[train] downloading 1057/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130701_1148_HARP2898_NOAA11779.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130701_1148_HARP2898_NOAA11779.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/057b8c6f402eac60873a7133a5d33afd.npz

.

Average throughput: 69.5MiB/s

[train] downloading 1058/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130625_2248_HARP2878_NOAA11777.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130625_2248_HARP2878_NOAA11777.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/871b9f1108a9482e37b56ffccac598d5.npz

.

Average throughput: 54.8MiB/s

[train] downloading 1059/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120415_2200_HARP1558_NOAA11463.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120415_2200_HARP1558_NOAA11463.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/01c7e7cfbb7ac727d12672369e34cd23.npz

.

Average throughput: 187.6MiB/s

[train] downloading 1060/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110323_1224_HARP436_NOAA11179.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110323_1224_HARP436_NOAA11179.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6b8e8701675469517d8056f49f6538e4.npz

.

Average throughput: 139.3MiB/s

[train] downloading 1061/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110514_0712_HARP595_NOAA11212.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110514_0712_HARP595_NOAA11212.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/627b36b2fb139613fb7eef68d622bdd6.npz

.

Average throughput: 81.8MiB/s

[train] downloading 1062/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100521_2300_HARP26_NOAA11072.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100521_2300_HARP26_NOAA11072.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f5c5ad1ebd2dcb2a21cc3d35171f1ebf.npz

.

Average throughput: 73.8MiB/s

[train] downloading 1063/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110326_1512_HARP438_NOAA11177.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110326_1512_HARP438_NOAA11177.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f44ee48b1861915a906c7871f2399597.npz

.

Average throughput: 36.5MiB/s

[train] downloading 1064/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131023_1112_HARP3291_NOAA11875.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131023_1112_HARP3291_NOAA11875.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/403db2c038b39e9aada881fc1cf0475d.npz

.

Average throughput: 70.1MiB/s

[train] downloading 1065/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100801_1548_HARP107_NOAA11094.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100801_1548_HARP107_NOAA11094.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/edc74745f922791806673be05c6ff843.npz

.

Average throughput: 74.1MiB/s

[train] downloading 1066/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131107_1800_HARP3341_NOAA11890.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131107_1800_HARP3341_NOAA11890.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8ddf479fc8d45d84853b24f100980c9d.npz

.

Average throughput: 96.5MiB/s

[train] downloading 1067/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111207_1600_HARP1124_NOAA11363.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111207_1600_HARP1124_NOAA11363.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a7cd6a2c21c20e66dc4e06ba2873abaf.npz

.

Average throughput: 109.8MiB/s

[train] downloading 1068/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120522_1224_HARP1677_NOAA11486.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120522_1224_HARP1677_NOAA11486.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/aae8bdbdee3e5bdf97a6b4973c9f78a1.npz

.

Average throughput: 168.6MiB/s

[train] downloading 1069/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120916_1700_HARP2039_NOAA11574.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120916_1700_HARP2039_NOAA11574.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/621999685835b4fed288eda3bdc86afb.npz

.

Average throughput: 142.0MiB/s

[train] downloading 1070/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131110_1648_HARP3353_NOAA11892.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131110_1648_HARP3353_NOAA11892.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ad953b5634564a543fed8649c2106929.npz

.

Average throughput: 67.9MiB/s

[train] downloading 1071/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110608_2100_HARP651_NOAA11231.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110608_2100_HARP651_NOAA11231.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/bfe4c247182657af75aca2d87cc3ff88.npz

.

Average throughput: 170.7MiB/s

[train] downloading 1072/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130717_0936_HARP2964_NOAA11795.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130717_0936_HARP2964_NOAA11795.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6d1c3cda2382e4a50b6b2f421e832897.npz

.

Average throughput: 174.7MiB/s

[train] downloading 1073/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120525_0200_HARP1688_NOAA11488.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120525_0200_HARP1688_NOAA11488.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/05312d078f77325e0415dfa92e256b78.npz

.

Average throughput: 91.1MiB/s

[train] downloading 1074/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110213_0248_HARP377_NOAA11158.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110213_0248_HARP377_NOAA11158.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fb99d82e19ad3c125dc7c61dd59b72b2.npz

.

Average throughput: 166.6MiB/s

[train] downloading 1075/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111027_0448_HARP997_NOAA11330.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111027_0448_HARP997_NOAA11330.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/356252f0b062c5cb0df0d00039ac919d.npz

.

Average throughput: 132.7MiB/s

[train] downloading 1076/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130802_1600_HARP3032_NOAA11811.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130802_1600_HARP3032_NOAA11811.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8053e08871095ba72279e54352c5a684.npz

.

Average throughput: 111.3MiB/s

[train] downloading 1077/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131214_1636_HARP3473_NOAA11917.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131214_1636_HARP3473_NOAA11917.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b6ca789454679aef1be37531c68a7ce7.npz

.

Average throughput: 129.8MiB/s

[train] downloading 1078/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130530_1348_HARP2779_NOAA11757.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130530_1348_HARP2779_NOAA11757.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5da0c5ae74730e4657f9a5b3dd6bc2d8.npz

.

Average throughput: 122.5MiB/s

[train] downloading 1079/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100812_1112_HARP115_NOAA11093.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100812_1112_HARP115_NOAA11093.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/72dd1d93f578d4d79edca6f0c686855b.npz

.

Average throughput: 153.8MiB/s

[train] downloading 1080/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110916_2300_HARP853_NOAA11292.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110916_2300_HARP853_NOAA11292.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/dec8e7b5f44e2006a60e07acd6b878d6.npz

.

Average throughput: 67.1MiB/s

[train] downloading 1081/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120126_2236_HARP1338_NOAA11408.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120126_2236_HARP1338_NOAA11408.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/78343044f3c1557cc95e117ede8e42ed.npz

.

Average throughput: 117.7MiB/s

[train] downloading 1082/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110918_1048_HARP856_NOAA11295.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110918_1048_HARP856_NOAA11295.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4fd1a22401d5489d0bdb806fc4695bad.npz

.

Average throughput: 162.2MiB/s

[train] downloading 1083/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131216_0436_HARP3483_NOAA11920.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131216_0436_HARP3483_NOAA11920.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/095e8819f6dc56f1c285618a14cbcc70.npz

.

Average throughput: 165.2MiB/s

[train] downloading 1084/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131011_1212_HARP3263_NOAA11861.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131011_1212_HARP3263_NOAA11861.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8c238306cb2d0b6a6e1b20364bd4fcb2.npz

.

Average throughput: 140.3MiB/s

[train] downloading 1085/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130922_1200_HARP3194_NOAA11845.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130922_1200_HARP3194_NOAA11845.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b865a318671de8c8ead8070e050a658c.npz

.

Average throughput: 155.1MiB/s

[train] downloading 1086/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110510_1600_HARP587_NOAA11208.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110510_1600_HARP587_NOAA11208.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/818ec4bbc5d1f9b18398d2718d4f0500.npz

.

Average throughput: 107.3MiB/s

[train] downloading 1087/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121025_1048_HARP2130_NOAA11596.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121025_1048_HARP2130_NOAA11596.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7a14c308afd4e6e295bcbcfbf48d1b83.npz

.

Average throughput: 158.7MiB/s

[train] downloading 1088/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110910_1836_HARP846_NOAA11288.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110910_1836_HARP846_NOAA11288.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/827e93505f6464047c8e456fae1dcf8c.npz

.

Average throughput: 143.2MiB/s

[train] downloading 1089/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130823_1100_HARP3098_NOAA11827.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130823_1100_HARP3098_NOAA11827.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0b3104dd01ca767000075290fe2365a7.npz

.

Average throughput: 69.4MiB/s

[train] downloading 1090/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120926_1100_HARP2047_NOAA11578.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120926_1100_HARP2047_NOAA11578.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e1756dc13e75d0392a69bd0495ee2a5a.npz

.

Average throughput: 88.8MiB/s

[train] downloading 1091/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130923_1312_HARP3194_NOAA11845.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130923_1312_HARP3194_NOAA11845.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8f4c632cba99ceb809771054f0bf17ca.npz

.

Average throughput: 161.1MiB/s

[train] downloading 1092/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131101_2312_HARP3321_NOAA11884.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131101_2312_HARP3321_NOAA11884.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1b08b6a76259670cc2a486a911963574.npz

.

Average throughput: 61.7MiB/s

[train] downloading 1093/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131214_1500_HARP3473_NOAA11917.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131214_1500_HARP3473_NOAA11917.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8677ebc63ddffcd581dac2e6ba9a2faa.npz

.

Average throughput: 75.7MiB/s

[train] downloading 1094/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131130_1336_HARP3415_NOAA11906.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131130_1336_HARP3415_NOAA11906.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ba3795c67fc496ff0330b28a2d7f213a.npz



Average throughput: 148.3MiB/s

[train] downloading 1095/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120905_1024_HARP1999_NOAA11563.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120905_1024_HARP1999_NOAA11563.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f41b01d6e811b65dd6744615b5791d90.npz

.

Average throughput: 127.6MiB/s

[train] downloading 1096/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131026_2036_HARP3309_NOAA11881.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131026_2036_HARP3309_NOAA11881.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/238d4d7a7db50093a0ce885776951a78.npz

.

Average throughput: 55.9MiB/s

[train] downloading 1097/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100918_1900_HARP175_NOAA11106.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100918_1900_HARP175_NOAA11106.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8a45dc93abb48e86f7d9993ba1104f78.npz

.

Average throughput: 149.6MiB/s

[train] downloading 1098/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130527_1812_HARP2760_NOAA11753.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130527_1812_HARP2760_NOAA11753.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fb319f5f148c31b3a90380dd58b76fbd.npz

.

Average throughput: 146.6MiB/s

[train] downloading 1099/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110606_0600_HARP639_NOAA11228.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110606_0600_HARP639_NOAA11228.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a4adb63c02aea7ae72ba8fdc61d89bf2.npz

.

Average throughput: 119.6MiB/s

[train] downloading 1100/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101022_2336_HARP224_NOAA11119.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101022_2336_HARP224_NOAA11119.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9691b02a663c2fa28a1731de5bf6162c.npz

.

Average throughput: 39.2MiB/s

[train] cached/checked 1100/1650 files | elapsed 28.2 min
[train] downloading 1101/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110728_1900_HARP746_NOAA11260.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110728_1900_HARP746_NOAA11260.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1071f6033b811a9c70681bdbe4ca571c.npz

.

Average throughput: 68.9MiB/s

[train] downloading 1102/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111225_0536_HARP1232_NOAA11385.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111225_0536_HARP1232_NOAA11385.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/286e92823a8b56b3322ddcf7d36b0f5a.npz

.

Average throughput: 106.9MiB/s

[train] downloading 1103/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101107_1036_HARP241_NOAA11120.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101107_1036_HARP241_NOAA11120.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/bdf5ea853fdd9c64b15b5b2de05cfa30.npz

.

Average throughput: 102.2MiB/s

[train] downloading 1104/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120702_2212_HARP1807_NOAA11514.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120702_2212_HARP1807_NOAA11514.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b2fa5d4b8bc6d03a55833a7711a67750.npz

.

Average throughput: 120.3MiB/s

[train] downloading 1105/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130822_2248_HARP3082_NOAA11823.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130822_2248_HARP3082_NOAA11823.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cff66de63dcc5174fbc6a21bbf0313ed.npz



Average throughput: 194.4MiB/s

[train] downloading 1106/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131115_0300_HARP3368_NOAA11896.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131115_0300_HARP3368_NOAA11896.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cb4595a79f50094edfdfa73bb7ea9515.npz

.

Average throughput: 127.3MiB/s

[train] downloading 1107/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120312_2200_HARP1461_NOAA11432.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120312_2200_HARP1461_NOAA11432.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/66dba33a4bed16c65e8aa50f73a4009a.npz

.

Average throughput: 61.8MiB/s

[train] downloading 1108/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100829_1348_HARP145_NOAA11101.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100829_1348_HARP145_NOAA11101.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/345bf6e9f6c75bea7fb44858077a08ad.npz

.

Average throughput: 136.1MiB/s

[train] downloading 1109/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120602_1000_HARP1715_NOAA11495.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120602_1000_HARP1715_NOAA11495.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d79f1e9e383d98f008423d5aef20e493.npz

.

Average throughput: 143.8MiB/s

[train] downloading 1110/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121030_0748_HARP2158_NOAA11601.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121030_0748_HARP2158_NOAA11601.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/31e3e8c48d54957df575ad7e94d44a06.npz

.

Average throughput: 42.2MiB/s

[train] downloading 1111/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131010_1512_HARP3258_NOAA11861.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131010_1512_HARP3258_NOAA11861.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d80e50c6ba31bf0816d92fa5bcfc96ce.npz

.

Average throughput: 153.2MiB/s

[train] downloading 1112/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100722_1400_HARP92_NOAA11089.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100722_1400_HARP92_NOAA11089.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9e76b2ac2e381e04a3b1df3550f635bc.npz

.

Average throughput: 122.2MiB/s

[train] downloading 1113/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130314_1348_HARP2543_NOAA11698.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130314_1348_HARP2543_NOAA11698.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c278e355bbb29eea3212baebd78c73dd.npz

.

Average throughput: 158.9MiB/s

[train] downloading 1114/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120531_0224_HARP1701_NOAA11490.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120531_0224_HARP1701_NOAA11490.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2cb6389788d4f39c39b1d3786ab5df7f.npz

.

Average throughput: 161.5MiB/s

[train] downloading 1115/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120103_0036_HARP1271_NOAA11392.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120103_0036_HARP1271_NOAA11392.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9098f0bb69e2026e33b2e1ec9c70d057.npz

.

Average throughput: 73.8MiB/s

[train] downloading 1116/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121126_1336_HARP2227_NOAA11620.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121126_1336_HARP2227_NOAA11620.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ac2f37101d697e2f38c7b1f357c67d2d.npz

.

Average throughput: 103.9MiB/s

[train] downloading 1117/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130829_0936_HARP3122_NOAA11835.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130829_0936_HARP3122_NOAA11835.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/dd0fe084c479aacd457f8aa6a5e8d526.npz

.

Average throughput: 109.7MiB/s

[train] downloading 1118/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130224_1400_HARP2492_NOAA11676.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130224_1400_HARP2492_NOAA11676.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6b4947b6f0a4a57fe3cd4e08f71c97ef.npz

.

Average throughput: 101.2MiB/s

[train] downloading 1119/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120103_2300_HARP1271_NOAA11392.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120103_2300_HARP1271_NOAA11392.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1853e202111ffd7694a2ed5d390c6fca.npz

.

Average throughput: 184.7MiB/s

[train] downloading 1120/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130921_1224_HARP3212_NOAA11845.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130921_1224_HARP3212_NOAA11845.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3acc7e59b6d86203909537396dd9210c.npz

.....

Average throughput: 6.8MiB/s

[train] downloading 1121/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131107_0024_HARP3341_NOAA11890.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131107_0024_HARP3341_NOAA11890.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/70df5278f9565777af2ffc62ec3491bb.npz

.

Average throughput: 116.1MiB/s

[train] downloading 1122/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120826_1836_HARP1946_NOAA11548.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120826_1836_HARP1946_NOAA11548.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/64efc01d289cd3f4717f7bedfbecac5f.npz

.

Average throughput: 120.0MiB/s

[train] downloading 1123/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100809_1536_HARP114_NOAA11095.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100809_1536_HARP114_NOAA11095.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f9e15b034b6e9cddafd59542d3fa4191.npz

.

Average throughput: 167.1MiB/s

[train] downloading 1124/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111201_2300_HARP1119_NOAA11361.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111201_2300_HARP1119_NOAA11361.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c3eff9ce068f4388550603dac64d8e47.npz

.

Average throughput: 73.7MiB/s

[train] downloading 1125/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101107_0800_HARP248_NOAA11122.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101107_0800_HARP248_NOAA11122.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a0a04dfda334e6bf86a6399547e41564.npz

.

Average throughput: 175.8MiB/s

[train] downloading 1126/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110614_0612_HARP661_NOAA11234.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110614_0612_HARP661_NOAA11234.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/44b043761cddb8c78367eaafb3239ac4.npz

.

Average throughput: 185.5MiB/s

[train] downloading 1127/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101024_2136_HARP226_NOAA11117.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101024_2136_HARP226_NOAA11117.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4ea764868af687cea9d0b06ebb585b44.npz

.

Average throughput: 178.8MiB/s

[train] downloading 1128/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111231_0212_HARP1249_NOAA11390.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111231_0212_HARP1249_NOAA11390.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ff0da76ba20d36eed7789494c1e3c7d5.npz

.

Average throughput: 174.9MiB/s

[train] downloading 1129/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110926_0224_HARP900_NOAA11304.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110926_0224_HARP900_NOAA11304.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/48442d28235b774e010996fb673de55d.npz

.

Average throughput: 157.8MiB/s

[train] downloading 1130/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121121_1724_HARP2220_NOAA11618.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121121_1724_HARP2220_NOAA11618.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4d37c3f92b4bd883e10ce97e8c7d87da.npz

.

Average throughput: 170.0MiB/s

[train] downloading 1131/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131020_1212_HARP3273_NOAA11868.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131020_1212_HARP3273_NOAA11868.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/641159b5e24dcc106a165fcfc2a6ed0c.npz

.

Average throughput: 162.1MiB/s

[train] downloading 1132/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120527_1700_HARP1690_NOAA11489.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120527_1700_HARP1690_NOAA11489.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/87ba39a3d0347b47d54f5a59a7f7e963.npz

.

Average throughput: 99.9MiB/s

[train] downloading 1133/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110710_2224_HARP702_NOAA11249.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110710_2224_HARP702_NOAA11249.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/09300416596d519f4ee87cf433e5e201.npz

.

Average throughput: 133.0MiB/s

[train] downloading 1134/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120415_1348_HARP1569_NOAA11457.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120415_1348_HARP1569_NOAA11457.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e41e11e9440f14e98eb086713db50403.npz

.

Average throughput: 173.5MiB/s

[train] downloading 1135/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131103_1512_HARP3321_NOAA11884.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131103_1512_HARP3321_NOAA11884.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/eff67149709cd5093dac41d41ddd0263.npz

.

Average throughput: 167.1MiB/s

[train] downloading 1136/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111209_1448_HARP1165_NOAA11367.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111209_1448_HARP1165_NOAA11367.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3438ec26b0fe7230f71600ce1135d42d.npz

.

Average throughput: 87.0MiB/s

[train] downloading 1137/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130517_0224_HARP2739_NOAA11745.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130517_0224_HARP2739_NOAA11745.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d1194fe7d7637908cc166de76b91c8d4.npz

.

Average throughput: 77.6MiB/s

[train] downloading 1138/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110308_1100_HARP403_NOAA11167.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110308_1100_HARP403_NOAA11167.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f3b88f79e03436fffccd02de79f24761.npz

.

Average throughput: 187.8MiB/s

[train] downloading 1139/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121126_1824_HARP2227_NOAA11620.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121126_1824_HARP2227_NOAA11620.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3422d72d9f4d6cd71f539d44b2a3e64a.npz

.

Average throughput: 97.8MiB/s

[train] downloading 1140/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130527_0524_HARP2760_NOAA11753.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130527_0524_HARP2760_NOAA11753.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/22c09d125698ca9560262b543fc829d0.npz

.

Average throughput: 74.3MiB/s

[train] downloading 1141/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130818_1048_HARP3102_NOAA11826.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130818_1048_HARP3102_NOAA11826.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5b35eb2310e5528ca11671da02e76a1d.npz

.

Average throughput: 148.1MiB/s

[train] downloading 1142/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100805_0636_HARP104_NOAA11092.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100805_0636_HARP104_NOAA11092.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cc80bfec542d9395543e6f3d6ac54a60.npz

.

Average throughput: 116.4MiB/s

[train] downloading 1143/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101118_0900_HARP256_NOAA11126.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101118_0900_HARP256_NOAA11126.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2ee6aedc719494700aebc8b898b75f12.npz

.

Average throughput: 56.4MiB/s

[train] downloading 1144/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110711_0624_HARP702_NOAA11249.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110711_0624_HARP702_NOAA11249.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/598226144d6d68ed55bbe1b1c37f1325.npz

.

Average throughput: 111.5MiB/s

[train] downloading 1145/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131016_0236_HARP3263_NOAA11861.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131016_0236_HARP3263_NOAA11861.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/315967b9bb540907fa3b0a9fd7e3fd7e.npz

.

Average throughput: 107.2MiB/s

[train] downloading 1146/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110918_0412_HARP856_NOAA11295.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110918_0412_HARP856_NOAA11295.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a8f444869ff76241f03ea9ad90520d64.npz

.

Average throughput: 165.0MiB/s

[train] downloading 1147/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130909_1300_HARP3154_NOAA11838.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130909_1300_HARP3154_NOAA11838.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/eca04e406bcdd02c826b0b7ad21db441.npz

.

Average throughput: 163.4MiB/s

[train] downloading 1148/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111109_0748_HARP1038_NOAA11340.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111109_0748_HARP1038_NOAA11340.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/18aa5980b6a853b9ac9fbc7c45e7b13e.npz

.

Average throughput: 145.4MiB/s

[train] downloading 1149/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120318_0836_HARP1465_NOAA11433.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120318_0836_HARP1465_NOAA11433.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/58a72db7aab2c6e4fb82c8c85a61f590.npz

.

Average throughput: 108.8MiB/s

[train] downloading 1150/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111023_0736_HARP970_NOAA11323.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111023_0736_HARP970_NOAA11323.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d32b8a1b5a5af82efabcc1c4f0a9e5a1.npz

.

Average throughput: 141.1MiB/s

[train] downloading 1151/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131023_0224_HARP3295_NOAA11877.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131023_0224_HARP3295_NOAA11877.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f6a4e282cd2dbdff03cd6a9a5f3b20f9.npz



Average throughput: 217.6MiB/s

[train] downloading 1152/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120215_1024_HARP1391_NOAA11417.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120215_1024_HARP1391_NOAA11417.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d431ec8151a52cb39cd58fd6c1ba5038.npz

.

Average throughput: 146.4MiB/s

[train] downloading 1153/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101122_2300_HARP259_NOAA11127.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101122_2300_HARP259_NOAA11127.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/672d51356ccf46f29b96a538f15a6505.npz

.

Average throughput: 124.4MiB/s

[train] downloading 1154/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110828_1036_HARP817_NOAA11285.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110828_1036_HARP817_NOAA11285.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c28cb2b5dd80c2536d566cd765f5fe7d.npz

.

Average throughput: 64.1MiB/s

[train] downloading 1155/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131213_0812_HARP3474_NOAA11927.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131213_0812_HARP3474_NOAA11927.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f9deae0b8137c9c881c8e974df5447c0.npz

..

Average throughput: 85.3MiB/s

[train] downloading 1156/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131029_0924_HARP3309_NOAA11881.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131029_0924_HARP3309_NOAA11881.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b7fdaa203693f493ef50b9ee96f4a15d.npz

.

Average throughput: 138.5MiB/s

[train] downloading 1157/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130514_1048_HARP2733_NOAA11742.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130514_1048_HARP2733_NOAA11742.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/26ce6888fa47917091f71d7ed2e3fcc3.npz

.

Average throughput: 118.3MiB/s

[train] downloading 1158/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110311_0800_HARP407_NOAA11169.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110311_0800_HARP407_NOAA11169.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/75c7720505d03e3cb6e83a0917c09a84.npz

..

Average throughput: 29.3MiB/s

[train] downloading 1159/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120525_1136_HARP1688_NOAA11488.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120525_1136_HARP1688_NOAA11488.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0e36c749bf66b2bf7a35f161a2b5f6ca.npz

.

Average throughput: 130.0MiB/s

[train] downloading 1160/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110120_2200_HARP345_NOAA11147.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110120_2200_HARP345_NOAA11147.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a9eb8740120d743a74be519d1758b90c.npz

.

Average throughput: 111.6MiB/s

[train] downloading 1161/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130717_2312_HARP2954_NOAA11792.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130717_2312_HARP2954_NOAA11792.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8f4ec72f3d44414282547dcd04b515e2.npz

.

Average throughput: 65.9MiB/s

[train] downloading 1162/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111205_1112_HARP1124_NOAA11363.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111205_1112_HARP1124_NOAA11363.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3ff6a62e31fe4c3a83009d2562e47c1e.npz

.

Average throughput: 107.5MiB/s

[train] downloading 1163/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121031_0300_HARP2158_NOAA11601.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121031_0300_HARP2158_NOAA11601.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/507d9b6372f5785f3172e1b2f42642c3.npz

.

Average throughput: 199.1MiB/s

[train] downloading 1164/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130825_2112_HARP3116_NOAA11833.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130825_2112_HARP3116_NOAA11833.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3cfe4fb575a50c1bf70ec37b72c5f986.npz

.

Average throughput: 94.2MiB/s

[train] downloading 1165/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131012_2136_HARP3258_NOAA11861.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131012_2136_HARP3258_NOAA11861.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/84ca4ce3a2c3d232512102644ba48915.npz

.

Average throughput: 162.4MiB/s

[train] downloading 1166/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111205_0224_HARP1133_NOAA11365.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111205_0224_HARP1133_NOAA11365.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5382bc3fc65395bf5506159486977685.npz

.

Average throughput: 137.6MiB/s

[train] downloading 1167/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111208_0900_HARP1170_NOAA11373.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111208_0900_HARP1170_NOAA11373.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0b9bf500fc2dc88a67e85554030dea48.npz

.

Average throughput: 60.9MiB/s

[train] downloading 1168/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131224_1800_HARP3520_NOAA11931.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131224_1800_HARP3520_NOAA11931.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d6463c869c2376fe82fbec8535fd5a98.npz

.

Average throughput: 130.4MiB/s

[train] downloading 1169/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120930_0812_HARP2059_NOAA11579.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120930_0812_HARP2059_NOAA11579.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b894204b3d27a507ba944786cff534a4.npz

.

Average throughput: 157.5MiB/s

[train] downloading 1170/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111029_0000_HARP1005_NOAA11332.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111029_0000_HARP1005_NOAA11332.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/dabf2e4598d98277b250407d6167248d.npz

.

Average throughput: 178.7MiB/s

[train] downloading 1171/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130802_0912_HARP3022_NOAA11808.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130802_0912_HARP3022_NOAA11808.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/41e2427243793870901baa7c5bb6dd1e.npz

.

Average throughput: 103.3MiB/s

[train] downloading 1172/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110625_0936_HARP681_NOAA11241.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110625_0936_HARP681_NOAA11241.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/87f75c92a5070bc735a23c2a0b338009.npz

.

Average throughput: 116.0MiB/s

[train] downloading 1173/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110717_1748_HARP728_NOAA11256.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110717_1748_HARP728_NOAA11256.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c6440a5d1fa9c45121e04a5fefc20e3b.npz

.

Average throughput: 115.9MiB/s

[train] downloading 1174/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100811_1100_HARP115_NOAA11093.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100811_1100_HARP115_NOAA11093.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e4695ff6c0c9d7a6ad7aaec5ce54bb0d.npz

.

Average throughput: 93.5MiB/s

[train] downloading 1175/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131107_1712_HARP3344_NOAA11891.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131107_1712_HARP3344_NOAA11891.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ac17c5d79dba2313df753343ced9a64c.npz

.

Average throughput: 152.7MiB/s

[train] downloading 1176/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110918_0136_HARP867_NOAA11299.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110918_0136_HARP867_NOAA11299.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4e51611121c270e0bdcd1e91a73f0380.npz

.

Average throughput: 96.8MiB/s

[train] downloading 1177/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111119_1512_HARP1066_NOAA11346.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111119_1512_HARP1066_NOAA11346.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/befc78c3658e7ade9226a8dd5aa59f96.npz

.

Average throughput: 85.9MiB/s

[train] downloading 1178/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111215_1136_HARP1171_NOAA11375.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111215_1136_HARP1171_NOAA11375.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fee402dfde52b39d2be7dad28427806a.npz

.

Average throughput: 86.6MiB/s

[train] downloading 1179/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131218_0400_HARP3497_NOAA11925.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131218_0400_HARP3497_NOAA11925.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a1e23395dc63b7794feeb4106a9ac393.npz

.

Average throughput: 171.3MiB/s

[train] downloading 1180/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130325_2324_HARP2585_NOAA11705.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130325_2324_HARP2585_NOAA11705.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6103cc712573b13d67f103a4bb022d5b.npz

.

Average throughput: 165.5MiB/s

[train] downloading 1181/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111218_2248_HARP1183_NOAA11376.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111218_2248_HARP1183_NOAA11376.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6ffa66b9777246a173134369756397ea.npz

.

Average throughput: 95.4MiB/s

[train] downloading 1182/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120711_0448_HARP1834_NOAA11519.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120711_0448_HARP1834_NOAA11519.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b7b97fcd99e328c767975f59d172dc35.npz

.

Average throughput: 157.5MiB/s

[train] downloading 1183/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120810_0000_HARP1907_NOAA11538.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120810_0000_HARP1907_NOAA11538.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b6772896112983e9e580c4c6cb2625df.npz

.

Average throughput: 158.2MiB/s

[train] downloading 1184/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120829_1200_HARP1970_NOAA11555.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120829_1200_HARP1970_NOAA11555.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2292cdfe117c4588c70367067f0547ef.npz

.

Average throughput: 101.7MiB/s

[train] downloading 1185/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120527_0200_HARP1688_NOAA11488.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120527_0200_HARP1688_NOAA11488.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2ffab7480f1657b7a308e5ff7aa757d7.npz

.

Average throughput: 148.4MiB/s

[train] downloading 1186/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110926_1812_HARP892_NOAA11302.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110926_1812_HARP892_NOAA11302.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cac9c637a8ac0b7cc48ce87252f23c3b.npz

.

Average throughput: 156.1MiB/s

[train] downloading 1187/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130111_1548_HARP2366_NOAA11653.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130111_1548_HARP2366_NOAA11653.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/34131705b508b2170b5c88beb3fa4142.npz

.

Average throughput: 186.2MiB/s

[train] downloading 1188/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120513_1012_HARP1638_NOAA11476.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120513_1012_HARP1638_NOAA11476.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fc4b06ccd27a0cde5e0c91e2619b86a6.npz

.

Average throughput: 72.2MiB/s

[train] downloading 1189/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120906_1312_HARP1996_NOAA11563.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120906_1312_HARP1996_NOAA11563.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2b1753264b4f02332e4244591267050a.npz

.

Average throughput: 67.8MiB/s

[train] downloading 1190/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131020_0900_HARP3286_NOAA11872.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131020_0900_HARP3286_NOAA11872.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0dbcb17289ba7c880b0e57b49e3445a4.npz

.

Average throughput: 158.3MiB/s

[train] downloading 1191/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101023_1712_HARP224_NOAA11119.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101023_1712_HARP224_NOAA11119.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1821d566848712ac00eaa101affd3124.npz

.

Average throughput: 143.8MiB/s

[train] downloading 1192/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110220_2348_HARP384_NOAA11160.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110220_2348_HARP384_NOAA11160.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f9d74c22134c4b5e49e9803a83318c94.npz

.

Average throughput: 154.9MiB/s

[train] downloading 1193/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120529_1824_HARP1705_NOAA11492.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120529_1824_HARP1705_NOAA11492.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/bdfbdfe9b5b8e978438c67952f9f19eb.npz

.

Average throughput: 178.2MiB/s

[train] downloading 1194/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130310_1300_HARP2525_NOAA11693.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130310_1300_HARP2525_NOAA11693.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/950ab717b4fcdc5f2cd62999374e95d9.npz

.

Average throughput: 86.4MiB/s

[train] downloading 1195/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111225_0124_HARP1221_NOAA11383.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111225_0124_HARP1221_NOAA11383.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/945bce4902466c8506500077d197350c.npz

.

Average throughput: 181.6MiB/s

[train] downloading 1196/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110815_1100_HARP772_NOAA11269.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110815_1100_HARP772_NOAA11269.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0f77e2532d5465d4a7344a763ba4c45b.npz

.

Average throughput: 79.0MiB/s

[train] downloading 1197/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120824_1836_HARP1946_NOAA11548.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120824_1836_HARP1946_NOAA11548.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7766fa829d5832034185830e159ba2b3.npz

.

Average throughput: 64.9MiB/s

[train] downloading 1198/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131216_1512_HARP3497_NOAA11925.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131216_1512_HARP3497_NOAA11925.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/dad1b9ac80e193dddb8c7fc5d315bab0.npz

.

Average throughput: 67.5MiB/s

[train] downloading 1199/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120302_1224_HARP1422_NOAA11423.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120302_1224_HARP1422_NOAA11423.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/787afd72f0df6d0f2f0ed368bee32669.npz

.

Average throughput: 90.1MiB/s

[train] downloading 1200/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121017_0348_HARP2121_NOAA11591.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121017_0348_HARP2121_NOAA11591.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b6eb7edc5088b408f6edbaa9213f123e.npz

.

Average throughput: 151.2MiB/s

[train] cached/checked 1200/1650 files | elapsed 30.8 min
[train] downloading 1201/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110606_0148_HARP651_NOAA11231.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110606_0148_HARP651_NOAA11231.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6fdfbc4b9aaa629185c6774d6a8e4f22.npz

.

Average throughput: 98.9MiB/s

[train] downloading 1202/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100925_0324_HARP185_NOAA11108.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100925_0324_HARP185_NOAA11108.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6a1b5a175221fb75fad3ceb089e35efc.npz

.

Average throughput: 53.8MiB/s

[train] downloading 1203/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111006_0848_HARP913_NOAA11308.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111006_0848_HARP913_NOAA11308.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8d1701c87229fe48f89a481243c6bd6e.npz

.

Average throughput: 80.5MiB/s

[train] downloading 1204/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130901_0412_HARP3129_NOAA11836.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130901_0412_HARP3129_NOAA11836.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0e62a9b699542e1cb6afccf81e85822e.npz

.

Average throughput: 71.2MiB/s

[train] downloading 1205/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130412_1724_HARP2651_NOAA11721.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130412_1724_HARP2651_NOAA11721.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/eb2a11a28b1a77410b9f3bdba9897e2a.npz



Average throughput: 203.9MiB/s

[train] downloading 1206/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120708_1848_HARP1832_NOAA11518.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120708_1848_HARP1832_NOAA11518.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/040da5c1436d447467fd20341674e7e5.npz

.

Average throughput: 134.9MiB/s

[train] downloading 1207/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111126_2112_HARP1093_NOAA11353.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111126_2112_HARP1093_NOAA11353.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a24d2de2067033ecea0dda1086d436dc.npz

.

Average throughput: 98.2MiB/s

[train] downloading 1208/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110203_0412_HARP361_NOAA11152.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110203_0412_HARP361_NOAA11152.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/dad0575e6e49460cb315edeff4600b90.npz

.

Average throughput: 105.1MiB/s

[train] downloading 1209/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130807_1300_HARP3028_NOAA11809.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130807_1300_HARP3028_NOAA11809.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8481414585db664c90c55526aeb88483.npz

.

Average throughput: 67.1MiB/s

[train] downloading 1210/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100606_2048_HARP46_NOAA11078.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100606_2048_HARP46_NOAA11078.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b2e7de5da0c976134436a4d971cba1c5.npz

.

Average throughput: 93.4MiB/s

[train] downloading 1211/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101228_0800_HARP318_NOAA11138.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101228_0800_HARP318_NOAA11138.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a369a1edf5a5eafbf02d2f9d6ff9e541.npz

.

Average throughput: 112.3MiB/s

[train] downloading 1212/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121121_1412_HARP2220_NOAA11618.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121121_1412_HARP2220_NOAA11618.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/af7ddeda572203383dcee20784e85608.npz

..

Average throughput: 40.3MiB/s

[train] downloading 1213/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130112_1848_HARP2372_NOAA11654.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130112_1848_HARP2372_NOAA11654.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b7828ce5788ce41c23fc4dcecb57b3cf.npz

.

Average throughput: 128.7MiB/s

[train] downloading 1214/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111106_1236_HARP1028_NOAA11339.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111106_1236_HARP1028_NOAA11339.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d2bb0406bd41321a4f271be324654e31.npz

.

Average throughput: 92.9MiB/s

[train] downloading 1215/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101207_0824_HARP279_NOAA11131.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101207_0824_HARP279_NOAA11131.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3fb805e37adb15066020d27b75e369c9.npz

.

Average throughput: 93.3MiB/s

[train] downloading 1216/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120314_0936_HARP1461_NOAA11432.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120314_0936_HARP1461_NOAA11432.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9f3571f9cb8cc5630dc2fa4396521caa.npz

.

Average throughput: 67.5MiB/s

[train] downloading 1217/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130513_1200_HARP2735_NOAA11744.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130513_1200_HARP2735_NOAA11744.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/419778c5a0e8a9d225114e341a5263be.npz

.

Average throughput: 102.4MiB/s

[train] downloading 1218/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110716_1448_HARP712_NOAA11250.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110716_1448_HARP712_NOAA11250.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ab64afe3c9571eec2ab0c95dbf761876.npz

.

Average throughput: 153.0MiB/s

[train] downloading 1219/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120213_1536_HARP1389_NOAA11416.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120213_1536_HARP1389_NOAA11416.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/83501cf6336e715d83d478345a4c76a6.npz

.

Average throughput: 81.2MiB/s

[train] downloading 1220/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131102_1100_HARP3330_NOAA11887.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131102_1100_HARP3330_NOAA11887.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/240473c4d802273015fed65283605234.npz

.

Average throughput: 76.5MiB/s

[train] downloading 1221/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130311_1636_HARP2522_NOAA11689.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130311_1636_HARP2522_NOAA11689.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9ca252cf82350b12207bdbff661e2ebf.npz

.

Average throughput: 119.6MiB/s

[train] downloading 1222/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131219_1348_HARP3515_NOAA11930.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131219_1348_HARP3515_NOAA11930.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6010291af8f3b11a11b01fffac19471d.npz

.

Average throughput: 151.6MiB/s

[train] downloading 1223/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131025_0100_HARP3295_NOAA11877.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131025_0100_HARP3295_NOAA11877.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3ee77696dc9dfb9e7fd5dcfe62704b90.npz

.

Average throughput: 118.9MiB/s

[train] downloading 1224/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130312_1312_HARP2541_NOAA11691.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130312_1312_HARP2541_NOAA11691.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ff72694aabf770fcc57d69ddf86a6a89.npz

.

Average throughput: 109.0MiB/s

[train] downloading 1225/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110830_1812_HARP814_NOAA11277.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110830_1812_HARP814_NOAA11277.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/13b89eb4fead86025bc7254f3da9dda9.npz



Average throughput: 152.1MiB/s

[train] downloading 1226/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120605_1524_HARP1724_NOAA11494.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120605_1524_HARP1724_NOAA11494.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7345f7889ea690f9a0941d0b3b34eed5.npz

.

Average throughput: 74.9MiB/s

[train] downloading 1227/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131115_0548_HARP3386_NOAA11902.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131115_0548_HARP3386_NOAA11902.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c62e82f546ce6bf956d1694460346010.npz

.

Average throughput: 183.8MiB/s

[train] downloading 1228/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120904_1148_HARP1990_NOAA11562.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120904_1148_HARP1990_NOAA11562.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a4e69f4022f0d9f59653937bd3501130.npz

.

Average throughput: 116.4MiB/s

[train] downloading 1229/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110813_1100_HARP772_NOAA11269.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110813_1100_HARP772_NOAA11269.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/96ca636c12f92087273aa6a6b2bf16d5.npz

.

Average throughput: 85.0MiB/s

[train] downloading 1230/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130414_0436_HARP2651_NOAA11721.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130414_0436_HARP2651_NOAA11721.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/99e90cf98cda421c67c6cc61d72c5d3b.npz

.

Average throughput: 113.2MiB/s

[train] downloading 1231/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120627_0336_HARP1795_NOAA11512.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120627_0336_HARP1795_NOAA11512.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e781b210bff5feeb3dac30c2c541991c.npz

.

Average throughput: 125.7MiB/s

[train] downloading 1232/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131102_2212_HARP3330_NOAA11887.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131102_2212_HARP3330_NOAA11887.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5fbde30fb9951fc86778a14a03aa11ff.npz

.

Average throughput: 92.8MiB/s

[train] downloading 1233/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131110_0224_HARP3341_NOAA11890.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131110_0224_HARP3341_NOAA11890.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/409baad94843b4ebfcb2f1fa8b8c346a.npz

.

Average throughput: 77.6MiB/s

[train] downloading 1234/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110713_0300_HARP712_NOAA11250.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110713_0300_HARP712_NOAA11250.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/872d039523382615a1e1fd84dd11ee89.npz

.

Average throughput: 78.3MiB/s

[train] downloading 1235/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130918_1012_HARP3195_NOAA11843.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130918_1012_HARP3195_NOAA11843.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0a76da12ebdbbccfc785d0d4225668e5.npz

.

Average throughput: 173.6MiB/s

[train] downloading 1236/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131114_2012_HARP3386_NOAA11902.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131114_2012_HARP3386_NOAA11902.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/23eff5c51a0ed98b1400486107c62d1c.npz

.

Average throughput: 111.0MiB/s

[train] downloading 1237/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110529_0848_HARP625_NOAA11223.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110529_0848_HARP625_NOAA11223.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ec4ef7c63215778832c7e2b00640b864.npz

.

Average throughput: 113.2MiB/s

[train] downloading 1238/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130801_0324_HARP3012_NOAA11806.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130801_0324_HARP3012_NOAA11806.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5cf28b31396bf27fcb48994fd66ba524.npz

.

Average throughput: 132.7MiB/s

[train] downloading 1239/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130831_0800_HARP3119_NOAA11834.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130831_0800_HARP3119_NOAA11834.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cd2282ebf9a2331bc78c3b897dc72984.npz

.

Average throughput: 156.7MiB/s

[train] downloading 1240/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130115_0900_HARP2380_NOAA11656.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130115_0900_HARP2380_NOAA11656.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6c5021c0e264c92649cfb7960a9946ac.npz

.

Average throughput: 74.2MiB/s

[train] downloading 1241/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130415_1412_HARP2651_NOAA11721.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130415_1412_HARP2651_NOAA11721.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d95b214ab398aef4b4d4bad43b0fc99c.npz

.

Average throughput: 116.8MiB/s

[train] downloading 1242/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130321_1224_HARP2581_NOAA11702.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130321_1224_HARP2581_NOAA11702.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b9b1f9132b46dcfe34a1bf46c86a9f6a.npz

.

Average throughput: 148.2MiB/s

[train] downloading 1243/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130728_0948_HARP3011_NOAA11812.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130728_0948_HARP3011_NOAA11812.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f9b2eb6be15b00f92532bdc1a7fee0ac.npz

.

Average throughput: 113.8MiB/s

[train] downloading 1244/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100713_0012_HARP86_NOAA11087.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100713_0012_HARP86_NOAA11087.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6f099c83efe24428a800458836e0d29a.npz



Average throughput: 171.7MiB/s

[train] downloading 1245/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120902_1724_HARP1990_NOAA11562.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120902_1724_HARP1990_NOAA11562.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b3c82d2ee462929381db36fac1ecf1ba.npz

.

Average throughput: 171.6MiB/s

[train] downloading 1246/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131211_1624_HARP3490_NOAA11922.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131211_1624_HARP3490_NOAA11922.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7b4ba940fd89ebbf00c13beff054b422.npz

.

Average throughput: 94.5MiB/s

[train] downloading 1247/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110803_0036_HARP753_NOAA11263.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110803_0036_HARP753_NOAA11263.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b3284098a41da2fa60d71defb52742d4.npz

.

Average throughput: 135.9MiB/s

[train] downloading 1248/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120503_1348_HARP1628_NOAA11472.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120503_1348_HARP1628_NOAA11472.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/34a08f5d9933b43de52641617e0ae5cf.npz

..

Average throughput: 127.4MiB/s

[train] downloading 1249/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120927_0048_HARP2044_NOAA11576.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120927_0048_HARP2044_NOAA11576.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/576e6fb76de7da8064e40cd5b1359514.npz

.

Average throughput: 150.0MiB/s

[train] downloading 1250/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130717_2324_HARP2952_NOAA11791.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130717_2324_HARP2952_NOAA11791.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4b7a1375a60134b128039bcd8a412b74.npz

.

Average throughput: 167.9MiB/s

[train] downloading 1251/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131101_0400_HARP3321_NOAA11884.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131101_0400_HARP3321_NOAA11884.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/67063bd190634e8067ba81a152315b85.npz

.

Average throughput: 43.4MiB/s

[train] downloading 1252/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120922_1600_HARP2044_NOAA11576.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120922_1600_HARP2044_NOAA11576.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/90d6aa61749f8c997acfb093a730b1a8.npz

.

Average throughput: 183.9MiB/s

[train] downloading 1253/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130620_0036_HARP2861_NOAA11773.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130620_0036_HARP2861_NOAA11773.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a9456a85e926746699748fa999f273e7.npz

.

Average throughput: 56.0MiB/s

[train] downloading 1254/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130829_0448_HARP3119_NOAA11834.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130829_0448_HARP3119_NOAA11834.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/502ecc19c6acd35a70adc6307fc963e9.npz

.

Average throughput: 167.7MiB/s

[train] downloading 1255/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110622_0624_HARP674_NOAA11237.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110622_0624_HARP674_NOAA11237.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/bf685ea6a9a63473fb6c3baefef9af15.npz

.

Average throughput: 135.2MiB/s

[train] downloading 1256/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110622_1824_HARP676_NOAA11239.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110622_1824_HARP676_NOAA11239.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6ec59f85e7c99090844d49b8b4566e94.npz

.

Average throughput: 81.5MiB/s

[train] downloading 1257/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111202_1648_HARP1120_NOAA11362.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111202_1648_HARP1120_NOAA11362.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/70682ab5ba33806972864264fbf940ff.npz

.

Average throughput: 98.0MiB/s

[train] downloading 1258/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120522_0924_HARP1680_NOAA11487.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120522_0924_HARP1680_NOAA11487.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/dca0904b4c7c811615a6d2abd908b79e.npz

.

Average throughput: 102.3MiB/s

[train] downloading 1259/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121008_0012_HARP2098_NOAA11585.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121008_0012_HARP2098_NOAA11585.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/123f24e990b2503bc6e0dc864483e3f2.npz

.

Average throughput: 194.7MiB/s

[train] downloading 1260/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131224_1324_HARP3513_NOAA11929.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131224_1324_HARP3513_NOAA11929.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1db56360fd798aefe6cf816f20ad504d.npz

.

Average throughput: 120.4MiB/s

[train] downloading 1261/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120924_1612_HARP2047_NOAA11578.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120924_1612_HARP2047_NOAA11578.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/03f2167cd546e40afa731df9aafb2c9c.npz

.

Average throughput: 87.7MiB/s

[train] downloading 1262/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111012_0648_HARP927_NOAA11312.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111012_0648_HARP927_NOAA11312.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0f26e9b15ba5ed9930edccbd44e06bc7.npz

.

Average throughput: 72.5MiB/s

[train] downloading 1263/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110905_2136_HARP833_NOAA11283.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110905_2136_HARP833_NOAA11283.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/702353739566dd38b458fa3f39aa30ad.npz

.

Average throughput: 158.1MiB/s

[train] downloading 1264/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131209_1324_HARP3482_NOAA11919.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131209_1324_HARP3482_NOAA11919.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6af367b2dbee44101ece356e1edd052c.npz

.

Average throughput: 183.5MiB/s

[train] downloading 1265/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121126_2000_HARP2227_NOAA11620.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121126_2000_HARP2227_NOAA11620.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/37b5330ccb3bb5e3c99186b0686f6c7a.npz

.

Average throughput: 147.3MiB/s

[train] downloading 1266/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101020_1748_HARP218_NOAA11113.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101020_1748_HARP218_NOAA11113.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7cd700dd58419cd6d406ab45a3834122.npz

.

Average throughput: 176.2MiB/s

[train] downloading 1267/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130410_1624_HARP2625_NOAA11716.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130410_1624_HARP2625_NOAA11716.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2994fd28acbf60882b6f71a56087d079.npz

.

Average throughput: 71.1MiB/s

[train] downloading 1268/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100524_0836_HARP26_NOAA11072.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100524_0836_HARP26_NOAA11072.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/533087692ec1d507dfdbcf3a1d1c75a1.npz

.

Average throughput: 115.9MiB/s

[train] downloading 1269/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130604_0224_HARP2808_NOAA11761.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130604_0224_HARP2808_NOAA11761.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/10a84996f149c4f48c76ee43d316b818.npz

.

Average throughput: 154.2MiB/s

[train] downloading 1270/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131004_1724_HARP3252_NOAA11862.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131004_1724_HARP3252_NOAA11862.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f88caf1983f8e60cde90da0794a3bfe7.npz



Average throughput: 184.4MiB/s

[train] downloading 1271/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121117_1348_HARP2191_NOAA11613.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121117_1348_HARP2191_NOAA11613.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/eda1e027b054ad83991b5a603a2c9ecb.npz

.

Average throughput: 101.9MiB/s

[train] downloading 1272/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130515_1548_HARP2737_NOAA11746.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130515_1548_HARP2737_NOAA11746.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c37910afeb2d3cbd78070c11a662e2c1.npz

.

Average throughput: 138.9MiB/s

[train] downloading 1273/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100804_1736_HARP104_NOAA11092.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100804_1736_HARP104_NOAA11092.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/28991d3c89252cce4cad0d015a96fcf6.npz

.

Average throughput: 85.1MiB/s

[train] downloading 1274/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110203_0800_HARP362_NOAA11153.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110203_0800_HARP362_NOAA11153.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/922dcfbe3196c98d6828e7cbd2f124f4.npz

.

Average throughput: 136.9MiB/s

[train] downloading 1275/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110605_1824_HARP650_NOAA11232.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110605_1824_HARP650_NOAA11232.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a04fdd9d677bbeb865cf34b84e12ef3f.npz

.

Average throughput: 162.2MiB/s

[train] downloading 1276/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131028_0612_HARP3309_NOAA11881.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131028_0612_HARP3309_NOAA11881.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/338b7ead99446e21fce1d994ebc4891c.npz



Average throughput: 191.6MiB/s

[train] downloading 1277/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131019_1524_HARP3286_NOAA11872.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131019_1524_HARP3286_NOAA11872.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8be94bff75115cf18dc030b64e992154.npz

.

Average throughput: 97.1MiB/s

[train] downloading 1278/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120516_2100_HARP1658_NOAA11483.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120516_2100_HARP1658_NOAA11483.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/934be5a3b6fcc4116f5c6ed4af245c69.npz

.

Average throughput: 108.6MiB/s

[train] downloading 1279/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120806_1912_HARP1907_NOAA11538.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120806_1912_HARP1907_NOAA11538.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5b968dbe1d8e0a0d4158ff01f4d44934.npz

.

Average throughput: 133.8MiB/s

[train] downloading 1280/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131031_0436_HARP3326_NOAA11886.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131031_0436_HARP3326_NOAA11886.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d5120e3721aa28416c116cabeea501a0.npz

.

Average throughput: 166.9MiB/s

[train] downloading 1281/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120107_1812_HARP1275_NOAA11393.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120107_1812_HARP1275_NOAA11393.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0efd9b70d86b51cb83be59e9e5ba3567.npz

.

Average throughput: 82.5MiB/s

[train] downloading 1282/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130706_0112_HARP2922_NOAA11784.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130706_0112_HARP2922_NOAA11784.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5c2d01f685735ae66fe879ff71d90cbf.npz

.

Average throughput: 122.4MiB/s

[train] downloading 1283/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130113_0536_HARP2360_NOAA11650.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130113_0536_HARP2360_NOAA11650.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/75e50af16a2aef1ae886a728ee28bf65.npz

.

Average throughput: 88.4MiB/s

[train] downloading 1284/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130218_0124_HARP2491_NOAA11675.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130218_0124_HARP2491_NOAA11675.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a4d875f18d927fee1e5c1a4a52777b2c.npz

.

Average throughput: 67.1MiB/s

[train] downloading 1285/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111018_1024_HARP940_NOAA11314.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111018_1024_HARP940_NOAA11314.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/52ec006ce4c434e67d91eaffb68a2c62.npz

.

Average throughput: 112.3MiB/s

[train] downloading 1286/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110926_0836_HARP892_NOAA11302.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110926_0836_HARP892_NOAA11302.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/92a7f0484cf8ca8f2e5f4b601e91a9fb.npz

.

Average throughput: 65.0MiB/s

[train] downloading 1287/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111001_1000_HARP902_NOAA11305.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111001_1000_HARP902_NOAA11305.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ed024d386c43dfd6a17673cec0ffe52e.npz

.

Average throughput: 130.8MiB/s

[train] downloading 1288/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110621_1648_HARP676_NOAA11239.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110621_1648_HARP676_NOAA11239.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8d53d66ba09b5db4d990e422d5c37f28.npz

.

Average throughput: 90.0MiB/s

[train] downloading 1289/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120121_0924_HARP1318_NOAA11399.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120121_0924_HARP1318_NOAA11399.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c6cbcd3d4386f6da2a1428344731607e.npz

.

Average throughput: 169.0MiB/s

[train] downloading 1290/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131019_0548_HARP3273_NOAA11868.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131019_0548_HARP3273_NOAA11868.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0e4cb58f63323222079cb3c2689109b2.npz



Average throughput: 210.7MiB/s

[train] downloading 1291/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130930_0836_HARP3244_NOAA11855.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130930_0836_HARP3244_NOAA11855.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/65c677ad6d6efded50b1c63680e0ff31.npz

.

Average throughput: 168.2MiB/s

[train] downloading 1292/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130529_0036_HARP2760_NOAA11753.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130529_0036_HARP2760_NOAA11753.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/22d3977f995c4cd833620d74a13b3781.npz

.

Average throughput: 105.0MiB/s

[train] downloading 1293/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130927_2224_HARP3220_NOAA11858.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130927_2224_HARP3220_NOAA11858.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/39e14244888a562f0ea2bb73662cd7d8.npz

.

Average throughput: 126.0MiB/s

[train] downloading 1294/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111002_2100_HARP902_NOAA11305.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111002_2100_HARP902_NOAA11305.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a82b2c02361dcd8022a91c9d94baccfd.npz

.

Average throughput: 72.0MiB/s

[train] downloading 1295/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101201_0900_HARP270_NOAA11128.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101201_0900_HARP270_NOAA11128.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0ba49ccf4e933abd07cad2bba161c52f.npz

.

Average throughput: 146.5MiB/s

[train] downloading 1296/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121028_1812_HARP2143_NOAA11599.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121028_1812_HARP2143_NOAA11599.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a8c45ac05cd4565570f9a5d5e49f85fa.npz

.

Average throughput: 165.5MiB/s

[train] downloading 1297/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130518_1900_HARP2748_NOAA11748.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130518_1900_HARP2748_NOAA11748.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/89e564a66e2a9fe96b61b2282294aefb.npz

.

Average throughput: 55.6MiB/s

[train] downloading 1298/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130716_0036_HARP2976_NOAA11796.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130716_0036_HARP2976_NOAA11796.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9584565d731340066fbc7b02c64aee8b.npz

.

Average throughput: 165.3MiB/s

[train] downloading 1299/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100802_0448_HARP104_NOAA11092.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100802_0448_HARP104_NOAA11092.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/00ea0eb57419a1be3be7a36c170e990b.npz

.

Average throughput: 67.0MiB/s

[train] downloading 1300/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101021_0200_HARP218_NOAA11113.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101021_0200_HARP218_NOAA11113.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4a96a0fd44db2ecf62a45b855daf464b.npz

.

Average throughput: 108.4MiB/s

[train] cached/checked 1300/1650 files | elapsed 33.4 min
[train] downloading 1301/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110315_1212_HARP421_NOAA11172.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110315_1212_HARP421_NOAA11172.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/50f8d703d51e7b2efce3c8479f3538f9.npz

.

Average throughput: 90.7MiB/s

[train] downloading 1302/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131105_0636_HARP3336_NOAA11889.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131105_0636_HARP3336_NOAA11889.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f6db5d58cb0d96de221249896a9f1d52.npz

.

Average throughput: 82.3MiB/s

[train] downloading 1303/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110526_1000_HARP625_NOAA11223.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110526_1000_HARP625_NOAA11223.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/be595bf4cebfc495df1103aca4ae4814.npz

.

Average throughput: 159.0MiB/s

[train] downloading 1304/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131104_0948_HARP3336_NOAA11889.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131104_0948_HARP3336_NOAA11889.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cb432e08aa3cef7d6d5c77178e74bcf5.npz

.

Average throughput: 156.4MiB/s

[train] downloading 1305/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110213_1548_HARP364_NOAA11157.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110213_1548_HARP364_NOAA11157.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ace4c2c7213a6b730e37571668d037ef.npz

.

Average throughput: 111.4MiB/s

[train] downloading 1306/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130513_0424_HARP2733_NOAA11742.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130513_0424_HARP2733_NOAA11742.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/575bb9359159233b40b40ace4d9caa79.npz

.

Average throughput: 75.6MiB/s

[train] downloading 1307/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121023_0048_HARP2130_NOAA11596.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121023_0048_HARP2130_NOAA11596.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/228fca6e1d24b51f35b7d106fb1d2d0e.npz

.

Average throughput: 55.5MiB/s

[train] downloading 1308/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110710_1748_HARP695_NOAA11247.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110710_1748_HARP695_NOAA11247.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0c1567da0256f41d8a6f214ee3aecee0.npz

.

Average throughput: 171.1MiB/s

[train] downloading 1309/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100925_1012_HARP190_NOAA11110.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100925_1012_HARP190_NOAA11110.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/94677fb06fe4edfea68720413afe5dcf.npz

.

Average throughput: 161.7MiB/s

[train] downloading 1310/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131116_1236_HARP3366_NOAA11895.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131116_1236_HARP3366_NOAA11895.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/245eefd444957c8358807c9cefabcde2.npz

.

Average throughput: 76.2MiB/s

[train] downloading 1311/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130421_2336_HARP2673_NOAA11726.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130421_2336_HARP2673_NOAA11726.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/077a3ecf4ab761e355dfdfd19e460e60.npz

.

Average throughput: 90.0MiB/s

[train] downloading 1312/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111109_2212_HARP1038_NOAA11340.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111109_2212_HARP1038_NOAA11340.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/77131b0ff5103bcd2685200be8860d73.npz

.

Average throughput: 160.6MiB/s

[train] downloading 1313/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130803_1912_HARP3032_NOAA11811.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130803_1912_HARP3032_NOAA11811.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f553ff6b744c32448de04702f3c0316f.npz

.

Average throughput: 149.8MiB/s

[train] downloading 1314/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120918_2336_HARP2028_NOAA11571.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120918_2336_HARP2028_NOAA11571.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/387832e8113794b6f47e420361aeca41.npz

.

Average throughput: 85.7MiB/s

[train] downloading 1315/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130110_0124_HARP2348_NOAA11651.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130110_0124_HARP2348_NOAA11651.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/86ddf817ffd2abc5aa050040ab9a43c5.npz

.

Average throughput: 116.5MiB/s

[train] downloading 1316/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131022_0412_HARP3288_NOAA11873.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131022_0412_HARP3288_NOAA11873.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7f90e2d33006bdfc751d371e56edf449.npz

.

Average throughput: 142.9MiB/s

[train] downloading 1317/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110812_0300_HARP772_NOAA11269.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110812_0300_HARP772_NOAA11269.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/32d2a928eed868a3711be559059dfbfa.npz

..

Average throughput: 70.9MiB/s

[train] downloading 1318/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100928_0736_HARP190_NOAA11110.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100928_0736_HARP190_NOAA11110.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a2d4b61a23624de198cf9b27062499d7.npz

.

Average throughput: 70.8MiB/s

[train] downloading 1319/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111226_0436_HARP1221_NOAA11383.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111226_0436_HARP1221_NOAA11383.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a9aa9ebdf326bcf959b24388d4b3c741.npz

.

Average throughput: 140.6MiB/s

[train] downloading 1320/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130203_1836_HARP2433_NOAA11665.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130203_1836_HARP2433_NOAA11665.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/775560cff06496b500a5a95396489278.npz

.

Average throughput: 94.1MiB/s

[train] downloading 1321/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131029_1712_HARP3326_NOAA11886.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131029_1712_HARP3326_NOAA11886.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1a0ccc5b5c772c05c62b5775df267ccc.npz

.

Average throughput: 142.0MiB/s

[train] downloading 1322/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120421_0200_HARP1594_NOAA11464.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120421_0200_HARP1594_NOAA11464.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fb81d96027aab79c61847f3566417c34.npz

.

Average throughput: 189.6MiB/s

[train] downloading 1323/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131216_1024_HARP3497_NOAA11925.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131216_1024_HARP3497_NOAA11925.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3adc177e9eae7d0e532764c35bb24efa.npz

.

Average throughput: 173.9MiB/s

[train] downloading 1324/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120621_2300_HARP1789_NOAA11511.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120621_2300_HARP1789_NOAA11511.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7d6f176e52ccf01162255b33ba1ef9b3.npz

.

Average throughput: 73.3MiB/s

[train] downloading 1325/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130313_1800_HARP2546_NOAA11692.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130313_1800_HARP2546_NOAA11692.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e1864884cdae338ba4e52cf591fa2ed8.npz

.

Average throughput: 124.5MiB/s

[train] downloading 1326/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110802_0936_HARP755_NOAA11264.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110802_0936_HARP755_NOAA11264.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/dadb542e3bc6a039f21f633986ce9776.npz

.

Average throughput: 159.5MiB/s

[train] downloading 1327/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111216_0336_HARP1171_NOAA11375.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111216_0336_HARP1171_NOAA11375.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3a69ce6270f7b82e548ea382ab012b87.npz

.

Average throughput: 156.4MiB/s

[train] downloading 1328/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110803_0936_HARP755_NOAA11264.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110803_0936_HARP755_NOAA11264.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1e53cdf159d5b305a791eac5e62dee54.npz

.

Average throughput: 168.2MiB/s

[train] downloading 1329/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131031_1236_HARP3326_NOAA11886.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131031_1236_HARP3326_NOAA11886.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/717b2a45a247173c021aecccb977d7a6.npz

.

Average throughput: 71.6MiB/s

[train] downloading 1330/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110305_1936_HARP393_NOAA11164.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110305_1936_HARP393_NOAA11164.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/226fe4b57de1861d521d3321ce8b7c13.npz

.

Average throughput: 58.5MiB/s

[train] downloading 1331/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130127_0236_HARP2411_NOAA11661.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130127_0236_HARP2411_NOAA11661.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9d1cf39bf25a566ff52714348ae8cc44.npz

.

Average throughput: 57.5MiB/s

[train] downloading 1332/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111223_0736_HARP1209_NOAA11380.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111223_0736_HARP1209_NOAA11380.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/513bc11d771944c58f7df009abb2ec86.npz

.

Average throughput: 92.6MiB/s

[train] downloading 1333/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111202_2236_HARP1119_NOAA11361.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111202_2236_HARP1119_NOAA11361.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/490b98557d1dc7bc43dae5c7291b02e4.npz

.

Average throughput: 167.9MiB/s

[train] downloading 1334/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130522_1836_HARP2758_NOAA11754.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130522_1836_HARP2758_NOAA11754.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/367fbaf01d5fd5979be5d126f1ac3a59.npz

.

Average throughput: 88.0MiB/s

[train] downloading 1335/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131103_2036_HARP3330_NOAA11887.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131103_2036_HARP3330_NOAA11887.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c4ba0b3450690cf3a487da181fc74db8.npz

.

Average throughput: 165.2MiB/s

[train] downloading 1336/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120129_1112_HARP1348_NOAA11411.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120129_1112_HARP1348_NOAA11411.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7f5ad182e814ab71925d7f8442d553f0.npz

.

Average throughput: 99.9MiB/s

[train] downloading 1337/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130313_1948_HARP2543_NOAA11698.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130313_1948_HARP2543_NOAA11698.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/864f6ae81945cc7708583c8a5dc5460f.npz

.

Average throughput: 82.8MiB/s

[train] downloading 1338/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120127_1512_HARP1339_NOAA11412.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120127_1512_HARP1339_NOAA11412.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/29bb48cf7296be385fde6f73ab4c3a05.npz

.

Average throughput: 99.6MiB/s

[train] downloading 1339/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131217_0924_HARP3483_NOAA11920.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131217_0924_HARP3483_NOAA11920.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c1b6f28289f36594632ac2d4e7a7ff85.npz

.

Average throughput: 154.0MiB/s

[train] downloading 1340/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131115_1236_HARP3366_NOAA11895.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131115_1236_HARP3366_NOAA11895.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2b222947aeaf7ce7c3d830c6ed79acaa.npz

.

Average throughput: 137.1MiB/s

[train] downloading 1341/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120824_2300_HARP1951_NOAA11552.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120824_2300_HARP1951_NOAA11552.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9e88d137424cb5963e726d295b5e22fa.npz

.

Average throughput: 88.8MiB/s

[train] downloading 1342/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120901_0548_HARP1979_NOAA11558.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120901_0548_HARP1979_NOAA11558.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7be551708f693e0c16ed7ab6d8caadb0.npz

.

Average throughput: 124.4MiB/s

[train] downloading 1343/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120603_0512_HARP1715_NOAA11495.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120603_0512_HARP1715_NOAA11495.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/aa2bb27b9d5e55acde2ab8f4892b5449.npz

.

Average throughput: 67.2MiB/s

[train] downloading 1344/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110715_2248_HARP712_NOAA11250.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110715_2248_HARP712_NOAA11250.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f58cba0e422d67902f0f22129ec615c5.npz

.

Average throughput: 91.4MiB/s

[train] downloading 1345/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131218_1824_HARP3497_NOAA11925.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131218_1824_HARP3497_NOAA11925.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/bce8b5ae5d6ddb085247371cbceb5f75.npz

.

Average throughput: 167.0MiB/s

[train] downloading 1346/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110903_0948_HARP824_NOAA11281.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110903_0948_HARP824_NOAA11281.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/11c750b9edf635ee1f83c7e797996a4d.npz

.

Average throughput: 56.9MiB/s

[train] downloading 1347/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130724_1100_HARP2982_NOAA11798.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130724_1100_HARP2982_NOAA11798.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/164594599cdaab5ced1394d37ba8b89a.npz

.

Average throughput: 124.2MiB/s

[train] downloading 1348/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111111_0348_HARP1041_NOAA11341.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111111_0348_HARP1041_NOAA11341.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e226482623c5a7f1a8fe2786ce1ad82c.npz

.

Average throughput: 126.3MiB/s

[train] downloading 1349/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121008_1924_HARP2098_NOAA11585.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121008_1924_HARP2098_NOAA11585.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/65f8fc349a705b523de60df840e57f1b.npz

.

Average throughput: 155.5MiB/s

[train] downloading 1350/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120318_0612_HARP1464_NOAA11434.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120318_0612_HARP1464_NOAA11434.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5c952dd1a9cde6fd0126f12a53013260.npz

.

Average throughput: 138.9MiB/s

[train] downloading 1351/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111213_0648_HARP1171_NOAA11375.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111213_0648_HARP1171_NOAA11375.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a28a2e943d17ea69c4a5dfffbab9c0b3.npz

.

Average throughput: 162.0MiB/s

[train] downloading 1352/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130723_1236_HARP2982_NOAA11798.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130723_1236_HARP2982_NOAA11798.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0b056bf47de94b11fc60bbec0580a601.npz

.

Average throughput: 101.9MiB/s

[train] downloading 1353/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131003_2048_HARP3244_NOAA11855.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131003_2048_HARP3244_NOAA11855.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/056202fac90aa8da66faab8058d5fae0.npz

.

Average throughput: 109.7MiB/s

[train] downloading 1354/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130310_1112_HARP2543_NOAA11698.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130310_1112_HARP2543_NOAA11698.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5b0c82160637b72f8161bf16f18e3016.npz

.

Average throughput: 77.7MiB/s

[train] downloading 1355/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130928_1912_HARP3220_NOAA11858.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130928_1912_HARP3220_NOAA11858.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7cb2e6e20526c4a8acb95b5fb2e2d6fd.npz

.

Average throughput: 155.9MiB/s

[train] downloading 1356/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130830_1248_HARP3122_NOAA11835.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130830_1248_HARP3122_NOAA11835.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5561b64a952cfa0ea75be89703e68bba.npz

.

Average throughput: 66.4MiB/s

[train] downloading 1357/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110727_0312_HARP744_NOAA11262.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110727_0312_HARP744_NOAA11262.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a81c1bbf675405263ef70b3fb069d124.npz

..

Average throughput: 112.9MiB/s

[train] downloading 1358/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110104_0524_HARP323_NOAA11140.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110104_0524_HARP323_NOAA11140.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9b83be528c200744c940301cd3827444.npz

.

Average throughput: 108.9MiB/s

[train] downloading 1359/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131102_0536_HARP3321_NOAA11884.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131102_0536_HARP3321_NOAA11884.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fee6512f450c5cb05fbcd87a96f748af.npz

.

Average throughput: 176.2MiB/s

[train] downloading 1360/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120728_2348_HARP1892_NOAA11533.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120728_2348_HARP1892_NOAA11533.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a965e1cca8ead83419a1cc1a9ead1123.npz

.

Average throughput: 168.5MiB/s

[train] downloading 1361/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111121_1736_HARP1080_NOAA11357.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111121_1736_HARP1080_NOAA11357.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/41e9bbd6816ade92db1f90cb2e985ad9.npz

.

Average throughput: 148.4MiB/s

[train] downloading 1362/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120206_0848_HARP1367_NOAA11415.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120206_0848_HARP1367_NOAA11415.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/72078c0d54620a27ea6d7ae079d62529.npz

.

Average throughput: 114.1MiB/s

[train] downloading 1363/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110212_1848_HARP377_NOAA11158.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110212_1848_HARP377_NOAA11158.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4cb488228a872f83d98fff46dee08175.npz

.

Average throughput: 118.2MiB/s

[train] downloading 1364/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130720_0224_HARP2968_NOAA11793.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130720_0224_HARP2968_NOAA11793.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d70101240f68a92087ea1c833fd4ebb9.npz

.

Average throughput: 170.6MiB/s

[train] downloading 1365/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130516_0612_HARP2735_NOAA11744.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130516_0612_HARP2735_NOAA11744.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d5b83232df752f0b31fe9fd6fe6fdaeb.npz

.

Average throughput: 41.7MiB/s

[train] downloading 1366/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131118_0200_HARP3376_NOAA11899.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131118_0200_HARP3376_NOAA11899.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/77ff909cb8b5a0d38a721c7df24dadad.npz

.

Average throughput: 150.1MiB/s

[train] downloading 1367/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120802_1448_HARP1893_NOAA11534.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120802_1448_HARP1893_NOAA11534.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ff31f128703ae6aa27bc82a57ccf9a02.npz

.

Average throughput: 155.1MiB/s

[train] downloading 1368/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130522_2012_HARP2758_NOAA11754.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130522_2012_HARP2758_NOAA11754.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c26f8a583de5b54a16e3f33cd0889f06.npz

..

Average throughput: 44.5MiB/s

[train] downloading 1369/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100730_0900_HARP98_NOAA11090.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100730_0900_HARP98_NOAA11090.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fe4e14eae3ed9defe472e585ca94d8a8.npz

.

Average throughput: 192.8MiB/s

[train] downloading 1370/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120523_1536_HARP1677_NOAA11486.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120523_1536_HARP1677_NOAA11486.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/61fffceae410b92b332f25e5ad30020e.npz

.

Average throughput: 107.6MiB/s

[train] downloading 1371/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110305_1000_HARP393_NOAA11164.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110305_1000_HARP393_NOAA11164.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/29b1d2333bcbbaecd8252dfcd0bbf156.npz



Average throughput: 110.8MiB/s

[train] downloading 1372/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130107_2036_HARP2348_NOAA11651.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130107_2036_HARP2348_NOAA11651.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/579de1a33e6e563e186c96f10cf8f15e.npz

.

Average throughput: 182.9MiB/s

[train] downloading 1373/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110319_0548_HARP421_NOAA11172.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110319_0548_HARP421_NOAA11172.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/20dc2cfe05900a88b56884a59cb38add.npz



Average throughput: 177.8MiB/s

[train] downloading 1374/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120731_1000_HARP1879_NOAA11529.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120731_1000_HARP1879_NOAA11529.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1a65498b8c38d50edf23d46916ccbbfc.npz

.

Average throughput: 179.9MiB/s

[train] downloading 1375/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130405_1900_HARP2605_NOAA11711.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130405_1900_HARP2605_NOAA11711.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cfd533907b1ca06ced706d098506d6b1.npz

.

Average throughput: 48.9MiB/s

[train] downloading 1376/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130827_0436_HARP3103_NOAA11828.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130827_0436_HARP3103_NOAA11828.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/80c441eb780e9afb05faad37fe0022da.npz

.

Average throughput: 81.0MiB/s

[train] downloading 1377/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100816_0200_HARP128_NOAA11097.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100816_0200_HARP128_NOAA11097.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/491a766e45fdb6e0697c201a1f1c97fb.npz

.

Average throughput: 139.7MiB/s

[train] downloading 1378/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120513_1500_HARP1638_NOAA11476.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120513_1500_HARP1638_NOAA11476.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e935c6a98507d2b762363d78fed77233.npz

.

Average throughput: 106.9MiB/s

[train] downloading 1379/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120428_2248_HARP1613_NOAA11467.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120428_2248_HARP1613_NOAA11467.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0b1acd772bb1c8365179fb771122f144.npz

.

Average throughput: 79.2MiB/s

[train] downloading 1380/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130702_1600_HARP2923_NOAA11786.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130702_1600_HARP2923_NOAA11786.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/45479ce1776b6822640cb8b5c4b283a7.npz

.

Average throughput: 116.4MiB/s

[train] downloading 1381/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111219_1624_HARP1210_NOAA11381.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111219_1624_HARP1210_NOAA11381.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9409c32e2bda2db610784dfd436705d7.npz

.

Average throughput: 60.3MiB/s

[train] downloading 1382/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120225_0824_HARP1410_NOAA11421.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120225_0824_HARP1410_NOAA11421.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7ee8f4106d3800a163f84fa04d006e5c.npz

.

Average throughput: 118.2MiB/s

[train] downloading 1383/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130818_1424_HARP3066_NOAA11820.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130818_1424_HARP3066_NOAA11820.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2742a446a3c3994199ff3f35e69229b2.npz

.

Average throughput: 93.7MiB/s

[train] downloading 1384/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111113_0348_HARP1041_NOAA11341.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111113_0348_HARP1041_NOAA11341.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7c3deb13fe922634715537cba8f56db0.npz

.

Average throughput: 102.7MiB/s

[train] downloading 1385/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121202_0948_HARP2240_NOAA11621.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121202_0948_HARP2240_NOAA11621.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6d897271059a526c853e605b69a08e0b.npz

.

Average throughput: 141.1MiB/s

[train] downloading 1386/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120203_2312_HARP1350_NOAA11410.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120203_2312_HARP1350_NOAA11410.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a827636756112a046e305e3f20a66bb1.npz

.

Average throughput: 53.1MiB/s

[train] downloading 1387/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131018_0036_HARP3293_NOAA11874.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131018_0036_HARP3293_NOAA11874.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/de38b91781f01455c260f50b8eccabcf.npz

.

Average throughput: 151.8MiB/s

[train] downloading 1388/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121118_2148_HARP2191_NOAA11613.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121118_2148_HARP2191_NOAA11613.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a3be02794dac0a612cd4406b7feca889.npz

.

Average throughput: 96.8MiB/s

[train] downloading 1389/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131106_0948_HARP3336_NOAA11889.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131106_0948_HARP3336_NOAA11889.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/30abde7875a91615c6b3ae95c5a694c2.npz

.

Average throughput: 125.7MiB/s

[train] downloading 1390/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130805_1824_HARP3031_NOAA11810.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130805_1824_HARP3031_NOAA11810.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/29eec307425da7d405ea2714d061a615.npz

.

Average throughput: 122.9MiB/s

[train] downloading 1391/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130718_1136_HARP2964_NOAA11795.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130718_1136_HARP2964_NOAA11795.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4dd2629d4e93b9c38b83b6cffb4154b0.npz

.

Average throughput: 125.8MiB/s

[train] downloading 1392/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110213_1712_HARP367_NOAA11156.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110213_1712_HARP367_NOAA11156.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c0989b44f43dd6ca0c8c9542d0d4987f.npz

.

Average throughput: 94.0MiB/s

[train] downloading 1393/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111031_1112_HARP1005_NOAA11332.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111031_1112_HARP1005_NOAA11332.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/05a3eed072bee3baa1187c44b3f23c9a.npz

.

Average throughput: 63.3MiB/s

[train] downloading 1394/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121219_0836_HARP2306_NOAA11633.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121219_0836_HARP2306_NOAA11633.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d34d360d027b8f780f26495c0a3745bc.npz

.

Average throughput: 185.9MiB/s

[train] downloading 1395/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101231_1512_HARP325_NOAA11141.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101231_1512_HARP325_NOAA11141.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/42ed9f9c3242056a6d966357aa5f4020.npz

.

Average throughput: 193.2MiB/s

[train] downloading 1396/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130515_2224_HARP2750_NOAA11750.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130515_2224_HARP2750_NOAA11750.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ae11a993406e7b105198aaf9e379d6d0.npz

.

Average throughput: 181.6MiB/s

[train] downloading 1397/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120316_0148_HARP1464_NOAA11434.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120316_0148_HARP1464_NOAA11434.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6ed0c90aef8621ea0f69ec36da58a5e2.npz

.

Average throughput: 161.9MiB/s

[train] downloading 1398/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130103_1236_HARP2338_NOAA11641.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130103_1236_HARP2338_NOAA11641.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/bf69253d417599b0faa9a823fe6cdbdd.npz

.

Average throughput: 160.4MiB/s

[train] downloading 1399/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131127_2112_HARP3415_NOAA11906.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131127_2112_HARP3415_NOAA11906.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/50f87928331755c751e69566b6064d56.npz

.

Average throughput: 183.3MiB/s

[train] downloading 1400/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120525_0900_HARP1690_NOAA11489.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120525_0900_HARP1690_NOAA11489.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/afd66ffca3215eebade747c58087eaac.npz

.

Average throughput: 149.7MiB/s

[train] cached/checked 1400/1650 files | elapsed 36.0 min
[train] downloading 1401/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110818_1000_HARP799_NOAA11273.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110818_1000_HARP799_NOAA11273.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/58e0afcdd5d3cd8252f14d3eedd66051.npz

.

Average throughput: 152.7MiB/s

[train] downloading 1402/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111101_2136_HARP1021_NOAA11334.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111101_2136_HARP1021_NOAA11334.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3582f99832865772c29c06b07acd3053.npz

.

Average throughput: 100.1MiB/s

[train] downloading 1403/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100821_0824_HARP135_NOAA11100.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100821_0824_HARP135_NOAA11100.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c0615641dbab933ab3ffe894442e8d04.npz

.

Average throughput: 183.4MiB/s

[train] downloading 1404/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120704_1600_HARP1807_NOAA11514.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120704_1600_HARP1807_NOAA11514.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/935b93a7f41147c0c9d0a738e3f420a4.npz

.

Average throughput: 175.2MiB/s

[train] downloading 1405/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120806_1336_HARP1908_NOAA11537.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120806_1336_HARP1908_NOAA11537.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e1eb5521d1ffc18119ec907ac8f9d406.npz

.

Average throughput: 97.9MiB/s

[train] downloading 1406/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100529_0312_HARP40_NOAA11075.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100529_0312_HARP40_NOAA11075.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5a260d761a1f90e8cf383170a9462aa3.npz

.

Average throughput: 90.8MiB/s

[train] downloading 1407/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120915_0500_HARP2026_NOAA11569.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120915_0500_HARP2026_NOAA11569.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/149e5440c58c51f44052cb11cd7c063c.npz

.

Average throughput: 186.8MiB/s

[train] downloading 1408/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131113_1712_HARP3371_NOAA11901.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131113_1712_HARP3371_NOAA11901.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d81fc6e575890ceed7ece651b5f98534.npz

.

Average throughput: 152.2MiB/s

[train] downloading 1409/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110401_2324_HARP451_NOAA11183.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110401_2324_HARP451_NOAA11183.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a7d00ef61dd1869526dd0163dd36a939.npz

.

Average throughput: 121.5MiB/s

[train] downloading 1410/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130113_0736_HARP2362_NOAA11652.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130113_0736_HARP2362_NOAA11652.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f3cf35994ad4bf95b818e80075a1f26c.npz

.

Average throughput: 58.2MiB/s

[train] downloading 1411/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130104_2324_HARP2353_NOAA11645.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130104_2324_HARP2353_NOAA11645.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f4cfb3998bfc915ea51addb3a2583101.npz

.

Average throughput: 58.6MiB/s

[train] downloading 1412/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120115_1900_HARP1300_NOAA11395.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120115_1900_HARP1300_NOAA11395.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/548732dc20c1bdce5a93063b3e1f708f.npz

.

Average throughput: 90.9MiB/s

[train] downloading 1413/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131026_0724_HARP3295_NOAA11877.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131026_0724_HARP3295_NOAA11877.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/58e99a74b4ae7ccf4482c79f72e8686b.npz

.

Average throughput: 136.3MiB/s

[train] downloading 1414/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130406_1336_HARP2619_NOAA11714.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130406_1336_HARP2619_NOAA11714.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0627211d2aaa2ecb3648f6ce21620c78.npz

.

Average throughput: 153.8MiB/s

[train] downloading 1415/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111205_0000_HARP1124_NOAA11363.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111205_0000_HARP1124_NOAA11363.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8946248375533c9adedd647e58505f10.npz

.

Average throughput: 146.9MiB/s

[train] downloading 1416/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120801_0648_HARP1879_NOAA11529.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120801_0648_HARP1879_NOAA11529.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d9971320300a8b1ee4b69a10e525df04.npz

.

Average throughput: 136.5MiB/s

[train] downloading 1417/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120212_1224_HARP1390_NOAA11418.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120212_1224_HARP1390_NOAA11418.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/61bff355dac95504b2a279b8b0cbb215.npz

.

Average throughput: 39.1MiB/s

[train] downloading 1418/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110630_1136_HARP684_NOAA11244.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110630_1136_HARP684_NOAA11244.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7cdbccba7e36d54d221720ccfbed3737.npz

.

Average throughput: 67.9MiB/s

[train] downloading 1419/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131230_0912_HARP3535_NOAA11936.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131230_0912_HARP3535_NOAA11936.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/456fda8c6cb9be7cd6e91fd97b411b43.npz

.

Average throughput: 166.0MiB/s

[train] downloading 1420/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131022_1036_HARP3288_NOAA11873.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131022_1036_HARP3288_NOAA11873.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ce1a6f5886885f35ed09edf5b3a81bdb.npz

.

Average throughput: 184.3MiB/s

[train] downloading 1421/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120513_1700_HARP1644_NOAA11477.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120513_1700_HARP1644_NOAA11477.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3cd28681ad1344468f11f8d922fde34d.npz

.

Average throughput: 155.8MiB/s

[train] downloading 1422/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130116_0448_HARP2372_NOAA11654.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130116_0448_HARP2372_NOAA11654.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/56b4564290dd9a9112665253b1edb4d2.npz

.

Average throughput: 81.5MiB/s

[train] downloading 1423/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110608_1512_HARP650_NOAA11232.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110608_1512_HARP650_NOAA11232.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1478c73e6e4160e67415cde2285e1e50.npz

.

Average throughput: 181.5MiB/s

[train] downloading 1424/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111204_1512_HARP1120_NOAA11362.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111204_1512_HARP1120_NOAA11362.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6366be47ae95c74d5d93bbb9a13d3d1a.npz

.

Average throughput: 138.7MiB/s

[train] downloading 1425/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110219_0436_HARP384_NOAA11160.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110219_0436_HARP384_NOAA11160.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fdb3aa772111bba35b317f95d3abd9d4.npz

.

Average throughput: 120.9MiB/s

[train] downloading 1426/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120314_1424_HARP1465_NOAA11433.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120314_1424_HARP1465_NOAA11433.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/aec53781368d9587dfafcf9380ae30fb.npz

.

Average throughput: 69.6MiB/s

[train] downloading 1427/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111124_0712_HARP1089_NOAA11352.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111124_0712_HARP1089_NOAA11352.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6d265d1c435a4a2b908ce6184cc934d8.npz

.

Average throughput: 161.2MiB/s

[train] downloading 1428/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121003_0724_HARP2069_NOAA11582.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121003_0724_HARP2069_NOAA11582.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/062b1fddc47f92c31fd15a1e32c43556.npz

.

Average throughput: 116.6MiB/s

[train] downloading 1429/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120225_1448_HARP1410_NOAA11421.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120225_1448_HARP1410_NOAA11421.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/eb1c1e1980606a8d0f99e89c6ce0633c.npz

.

Average throughput: 48.3MiB/s

[train] downloading 1430/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121031_1100_HARP2158_NOAA11601.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121031_1100_HARP2158_NOAA11601.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cda1705e9272d06d28e3e60e19fcbe09.npz

.

Average throughput: 123.5MiB/s

[train] downloading 1431/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130703_1236_HARP2910_NOAA11782.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130703_1236_HARP2910_NOAA11782.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c808eef38ba74dcf9e5309435fe36c87.npz

.

Average throughput: 108.2MiB/s

[train] downloading 1432/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121120_1724_HARP2220_NOAA11618.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121120_1724_HARP2220_NOAA11618.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2f54e90d420fd8b8b0a922fdd43f976b.npz

.

Average throughput: 133.7MiB/s

[train] downloading 1433/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131231_0424_HARP3535_NOAA11936.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131231_0424_HARP3535_NOAA11936.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5c24297b86bcc24fd578999138e7c551.npz

.

Average throughput: 130.1MiB/s

[train] downloading 1434/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100604_1124_HARP45_NOAA11073.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100604_1124_HARP45_NOAA11073.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/41d7246667c75262ed26f07a575bf9b7.npz

.

Average throughput: 78.2MiB/s

[train] downloading 1435/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131006_0300_HARP3248_NOAA11856.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131006_0300_HARP3248_NOAA11856.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/34b753b887da22dfe7a8e3b7f025d838.npz

.

Average throughput: 95.8MiB/s

[train] downloading 1436/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111108_2212_HARP1028_NOAA11339.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111108_2212_HARP1028_NOAA11339.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a46f2c6e6ee7364876e07a074d2bcb3b.npz

.

Average throughput: 100.6MiB/s

[train] downloading 1437/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110209_1836_HARP364_NOAA11157.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110209_1836_HARP364_NOAA11157.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0536b1e21a6a0ffef91e273fd9b0aaba.npz

.

Average throughput: 147.8MiB/s

[train] downloading 1438/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111122_1612_HARP1079_NOAA11350.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111122_1612_HARP1079_NOAA11350.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d92e2084ed5d1473c0d0d5e42f973d45.npz

.

Average throughput: 171.4MiB/s

[train] downloading 1439/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100806_2224_HARP116_NOAA11096.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100806_2224_HARP116_NOAA11096.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ddffbc79fd9b0b47b548596e8c8b2306.npz

.

Average throughput: 47.2MiB/s

[train] downloading 1440/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120902_0124_HARP1990_NOAA11562.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120902_0124_HARP1990_NOAA11562.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/256db7143516d54cfb44c8c09420dec6.npz

.

Average throughput: 107.9MiB/s

[train] downloading 1441/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130924_0400_HARP3199_NOAA11850.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130924_0400_HARP3199_NOAA11850.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d9ed9b1eced40aa0d9081ea9ee38c534.npz

.

Average throughput: 70.8MiB/s

[train] downloading 1442/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120517_0748_HARP1644_NOAA11477.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120517_0748_HARP1644_NOAA11477.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d1fbeb8e0fb385fc710e41552de75d87.npz

.

Average throughput: 125.7MiB/s

[train] downloading 1443/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120529_0536_HARP1701_NOAA11490.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120529_0536_HARP1701_NOAA11490.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f4ed62eeec8f44dada5dc475bcc95b02.npz

.

Average throughput: 76.8MiB/s

[train] downloading 1444/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130503_1924_HARP2710_NOAA11736.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130503_1924_HARP2710_NOAA11736.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7ca3e14911c6cfe7c5a6fbb1bdb6770a.npz

.

Average throughput: 102.5MiB/s

[train] downloading 1445/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120824_1324_HARP1951_NOAA11552.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120824_1324_HARP1951_NOAA11552.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8fd07dd4bb403229f56661e0688bd931.npz

.

Average throughput: 115.2MiB/s

[train] downloading 1446/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130821_1236_HARP3082_NOAA11823.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130821_1236_HARP3082_NOAA11823.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/29b1485a163dce9b5f7b1beccd2355f5.npz

.

Average throughput: 138.9MiB/s

[train] downloading 1447/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100528_1248_HARP40_NOAA11075.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100528_1248_HARP40_NOAA11075.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ad7a44bb251292705af3de204f9ff964.npz

.

Average throughput: 76.6MiB/s

[train] downloading 1448/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110729_1948_HARP748_NOAA11265.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110729_1948_HARP748_NOAA11265.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3a7707637762297f3375561163d8a0a2.npz

.

Average throughput: 128.3MiB/s

[train] downloading 1449/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120519_1436_HARP1658_NOAA11483.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120519_1436_HARP1658_NOAA11483.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2f1f9be52c537682572575e26a92c00e.npz

.

Average throughput: 83.9MiB/s

[train] downloading 1450/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130627_1312_HARP2887_NOAA11778.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130627_1312_HARP2887_NOAA11778.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/11a5b5ade0e1537479f730b0508c6d5f.npz

.

Average throughput: 64.2MiB/s

[train] downloading 1451/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110525_0124_HARP610_NOAA11218.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110525_0124_HARP610_NOAA11218.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/bed427eab2a855f9d9c0092d34230b43.npz

.

Average throughput: 90.3MiB/s

[train] downloading 1452/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110911_2012_HARP847_NOAA11289.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110911_2012_HARP847_NOAA11289.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2ee9300913988953df9d852513dd494c.npz

.

Average throughput: 92.9MiB/s

[train] downloading 1453/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110830_0424_HARP812_NOAA11280.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110830_0424_HARP812_NOAA11280.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/271e0029b03b5df09c5bc847d747241b.npz

.

Average throughput: 173.0MiB/s

[train] downloading 1454/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111024_1224_HARP970_NOAA11323.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111024_1224_HARP970_NOAA11323.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/67530ad9b0b3d66abcb363a0c33dd4ad.npz

.

Average throughput: 67.4MiB/s

[train] downloading 1455/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131005_0048_HARP3240_NOAA11854.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131005_0048_HARP3240_NOAA11854.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/873da674635dcab62056afa10176e579.npz

.

Average throughput: 168.5MiB/s

[train] downloading 1456/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111017_1124_HARP948_NOAA11317.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111017_1124_HARP948_NOAA11317.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e43c414f82c43277de7e2e7a2e67368c.npz

.

Average throughput: 121.9MiB/s

[train] downloading 1457/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130719_1800_HARP2964_NOAA11795.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130719_1800_HARP2964_NOAA11795.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/513e4c6c7e955349db7c11b8f7897419.npz

.

Average throughput: 91.2MiB/s

[train] downloading 1458/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130107_1348_HARP2342_NOAA11643.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130107_1348_HARP2342_NOAA11643.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/845cff912393a5946ae986fdce87e022.npz

.

Average throughput: 52.2MiB/s

[train] downloading 1459/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121010_0036_HARP2098_NOAA11585.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121010_0036_HARP2098_NOAA11585.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/04d88e04dea3ba6c5940bdaa95a72f02.npz

.

Average throughput: 169.8MiB/s

[train] downloading 1460/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110720_0112_HARP714_NOAA11251.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110720_0112_HARP714_NOAA11251.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b68b967c02cf8b16540ea84382a762f0.npz

.

Average throughput: 109.8MiB/s

[train] downloading 1461/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101025_0712_HARP226_NOAA11117.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101025_0712_HARP226_NOAA11117.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/feb0514d008d77bd8aee711a5bf899f1.npz

.

Average throughput: 49.6MiB/s

[train] downloading 1462/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130408_1424_HARP2625_NOAA11716.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130408_1424_HARP2625_NOAA11716.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ff3cd5a3e4f0b43d71b853adfc2789c6.npz

.

Average throughput: 142.7MiB/s

[train] downloading 1463/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110218_0300_HARP384_NOAA11160.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110218_0300_HARP384_NOAA11160.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d92a24a1b390c649a6b424fb8686488b.npz

.

Average throughput: 171.9MiB/s

[train] downloading 1464/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100828_2148_HARP145_NOAA11101.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100828_2148_HARP145_NOAA11101.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1d32d462172ef46d262a76a5045b133d.npz

.

Average throughput: 172.1MiB/s

[train] downloading 1465/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131222_0524_HARP3513_NOAA11929.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131222_0524_HARP3513_NOAA11929.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/05ffb4159bdc1ef58c75d26ad48da474.npz

.

Average throughput: 89.8MiB/s

[train] downloading 1466/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120930_2236_HARP2059_NOAA11579.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120930_2236_HARP2059_NOAA11579.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9ce0c93fe067394707ffdaa72289c0de.npz



Average throughput: 195.1MiB/s

[train] downloading 1467/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130612_0712_HARP2839_NOAA11767.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130612_0712_HARP2839_NOAA11767.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/57606a6b063a8074bc409acd471b524b.npz

.

Average throughput: 154.0MiB/s

[train] downloading 1468/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130927_1812_HARP3199_NOAA11850.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130927_1812_HARP3199_NOAA11850.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5dc60b30771281d3ce9f10b31cf0e345.npz



Average throughput: 192.6MiB/s

[train] downloading 1469/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131201_0912_HARP3437_NOAA11909.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131201_0912_HARP3437_NOAA11909.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a0f0fe29204e8c09a2388b64051e5b9f.npz

.

Average throughput: 83.2MiB/s

[train] downloading 1470/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120901_0436_HARP1970_NOAA11555.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120901_0436_HARP1970_NOAA11555.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d2dc4bc01d91c221898f34c197f385cd.npz

.

Average throughput: 65.6MiB/s

[train] downloading 1471/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120411_1712_HARP1549_NOAA11455.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120411_1712_HARP1549_NOAA11455.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b273580b490f1f15680f956de6b96c4c.npz



Average throughput: 189.6MiB/s

[train] downloading 1472/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101226_1112_HARP318_NOAA11138.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101226_1112_HARP318_NOAA11138.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cf5265c0996f834e4e322a61550cee1e.npz

.

Average throughput: 47.7MiB/s

[train] downloading 1473/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120925_0812_HARP2047_NOAA11578.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120925_0812_HARP2047_NOAA11578.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6af129a620d67db5c10713cc3277941d.npz

.

Average throughput: 118.2MiB/s

[train] downloading 1474/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111202_1336_HARP1133_NOAA11365.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111202_1336_HARP1133_NOAA11365.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ac63531e498106d8d4cf7e7b29941df2.npz

.

Average throughput: 166.4MiB/s

[train] downloading 1475/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130530_0336_HARP2790_NOAA11758.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130530_0336_HARP2790_NOAA11758.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b250138a6277ca976b1e0715929d85f6.npz

.

Average throughput: 67.9MiB/s

[train] downloading 1476/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130220_0124_HARP2491_NOAA11675.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130220_0124_HARP2491_NOAA11675.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4f84e90b0accdb6e7be72430936e9a43.npz

.

Average throughput: 58.2MiB/s

[train] downloading 1477/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130829_1112_HARP3122_NOAA11835.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130829_1112_HARP3122_NOAA11835.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3a90c01b7818d6f5afd84a4b5d5bb61a.npz

.

Average throughput: 85.8MiB/s

[train] downloading 1478/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121026_1724_HARP2137_NOAA11598.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121026_1724_HARP2137_NOAA11598.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/41801e9878a072d8dacd0e28909ca212.npz

.

Average throughput: 90.3MiB/s

[train] downloading 1479/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120422_0624_HARP1596_NOAA11465.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120422_0624_HARP1596_NOAA11465.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/81ce840ddb2374e30a3e96966dd29982.npz

..

Average throughput: 40.2MiB/s

[train] downloading 1480/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110907_1100_HARP843_NOAA11287.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110907_1100_HARP843_NOAA11287.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/27ea8888073a19049e9405c4996d270e.npz

.

Average throughput: 194.0MiB/s

[train] downloading 1481/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131206_0800_HARP3448_NOAA11916.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131206_0800_HARP3448_NOAA11916.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/283e5d9514d0f0e00dd025866a28254a.npz

.

Average throughput: 103.7MiB/s

[train] downloading 1482/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110527_0224_HARP625_NOAA11223.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110527_0224_HARP625_NOAA11223.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d05aeb664b8428e5ab72891af246c3e5.npz

.

Average throughput: 75.0MiB/s

[train] downloading 1483/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120925_1100_HARP2044_NOAA11576.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120925_1100_HARP2044_NOAA11576.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/27f23e1ff31f5c049c67865ac0ff7ceb.npz

.

Average throughput: 105.0MiB/s

[train] downloading 1484/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110104_1500_HARP323_NOAA11140.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110104_1500_HARP323_NOAA11140.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9d26b7f4339f20974b7eae501357860f.npz

.

Average throughput: 193.4MiB/s

[train] downloading 1485/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131208_1636_HARP3457_NOAA11912.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131208_1636_HARP3457_NOAA11912.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1076cee5bbc6b23840ac625f6ada4c6d.npz

.

Average throughput: 145.9MiB/s

[train] downloading 1486/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110311_0336_HARP401_NOAA11166.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110311_0336_HARP401_NOAA11166.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3e744ba651496222b9da51894ba72e26.npz

.

Average throughput: 115.0MiB/s

[train] downloading 1487/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120910_1736_HARP2011_NOAA11566.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120910_1736_HARP2011_NOAA11566.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/256aff5c2d106ff25c0c8c4cf65cc449.npz



Average throughput: 186.3MiB/s

[train] downloading 1488/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110303_1912_HARP392_NOAA11163.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110303_1912_HARP392_NOAA11163.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a078eb9e6a10dea5827fce5ebfe08267.npz

.

Average throughput: 168.4MiB/s

[train] downloading 1489/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130626_1448_HARP2878_NOAA11777.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130626_1448_HARP2878_NOAA11777.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f0773626cabe715b5ba444fcb625e54f.npz

.

Average throughput: 189.8MiB/s

[train] downloading 1490/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110908_1548_HARP843_NOAA11287.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110908_1548_HARP843_NOAA11287.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f137d03712f147a40510c33846bf7943.npz

.

Average throughput: 106.2MiB/s

[train] downloading 1491/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100803_1900_HARP107_NOAA11094.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100803_1900_HARP107_NOAA11094.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ccbf13d20451547603f2cad1ad08f5a4.npz

.

Average throughput: 138.0MiB/s

[train] downloading 1492/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131201_1600_HARP3432_NOAA11908.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131201_1600_HARP3432_NOAA11908.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/98de350a081fbd8662f921f47aade6b3.npz

.

Average throughput: 170.9MiB/s

[train] downloading 1493/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110112_1536_HARP342_NOAA11146.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110112_1536_HARP342_NOAA11146.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/14c0610e0fd7d12350435159f23c044a.npz

.

Average throughput: 85.7MiB/s

[train] downloading 1494/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110111_0400_HARP335_NOAA11143.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110111_0400_HARP335_NOAA11143.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2235a8d34d61d7e42a4e5194d8fa3a86.npz

.

Average throughput: 133.6MiB/s

[train] downloading 1495/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131130_0212_HARP3446_NOAA11911.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131130_0212_HARP3446_NOAA11911.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d72375b9604029773fb5eb50b4c0b83e.npz

.

Average throughput: 147.9MiB/s

[train] downloading 1496/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110116_1200_HARP342_NOAA11146.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110116_1200_HARP342_NOAA11146.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d47018abd4c468a9a614190f8c4db88d.npz

.

Average throughput: 157.6MiB/s

[train] downloading 1497/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110917_1500_HARP853_NOAA11292.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110917_1500_HARP853_NOAA11292.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ee4995fd0fed1becb29505f7db496fb8.npz

.

Average throughput: 58.8MiB/s

[train] downloading 1498/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110718_0212_HARP713_NOAA11258.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110718_0212_HARP713_NOAA11258.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0b8455a4b885d35667083a6019acb9b5.npz

.

Average throughput: 133.0MiB/s

[train] downloading 1499/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111002_1500_HARP909_NOAA11307.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111002_1500_HARP909_NOAA11307.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/236f7bef2f89c3b257d6d60286be3900.npz

.

Average throughput: 35.9MiB/s

[train] downloading 1500/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130116_2224_HARP2387_NOAA11658.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130116_2224_HARP2387_NOAA11658.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a0da869cc5fad0e493e3f156abc54b17.npz

.

Average throughput: 87.4MiB/s

[train] cached/checked 1500/1650 files | elapsed 38.5 min
[train] downloading 1501/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131113_1348_HARP3364_NOAA11893.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131113_1348_HARP3364_NOAA11893.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6d24a81f7a6bed11258523e11302e4da.npz

.

Average throughput: 92.7MiB/s

[train] downloading 1502/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110428_1148_HARP538_NOAA11200.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110428_1148_HARP538_NOAA11200.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/078546b965e08c0e4ef8152111f9ed62.npz

.

Average throughput: 141.4MiB/s

[train] downloading 1503/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110213_0612_HARP371_NOAA11159.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110213_0612_HARP371_NOAA11159.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/35d779adcf55e19ce4c130447959f52c.npz

.

Average throughput: 110.4MiB/s

[train] downloading 1504/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120516_1100_HARP1658_NOAA11483.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120516_1100_HARP1658_NOAA11483.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d3a02282e84825f9f2f5da7113739374.npz

.

Average throughput: 130.3MiB/s

[train] downloading 1505/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130318_0836_HARP2557_NOAA11695.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130318_0836_HARP2557_NOAA11695.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3df12d58da694bb4ed91c20a67f45aab.npz

.

Average throughput: 67.9MiB/s

[train] downloading 1506/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130711_1048_HARP2948_NOAA11789.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130711_1048_HARP2948_NOAA11789.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/19a82a8ecbb9a1059c77174c69ae242a.npz

.

Average throughput: 169.7MiB/s

[train] downloading 1507/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120307_0112_HARP1447_NOAA11428.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120307_0112_HARP1447_NOAA11428.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b097cb7b3382821adfbc12dd5f7b75d6.npz

.

Average throughput: 137.5MiB/s

[train] downloading 1508/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110413_0024_HARP495_NOAA11190.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110413_0024_HARP495_NOAA11190.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ca8a4d49826cd6f229bd8034528a38c9.npz

.

Average throughput: 98.4MiB/s

[train] downloading 1509/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110605_1200_HARP650_NOAA11232.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110605_1200_HARP650_NOAA11232.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ba4d78dd8f93ccade6a834123fa1e7c7.npz

.

Average throughput: 80.9MiB/s

[train] downloading 1510/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120315_0036_HARP1461_NOAA11432.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120315_0036_HARP1461_NOAA11432.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cc50fce8e5417dedc834026fe836a00a.npz

.

Average throughput: 109.2MiB/s

[train] downloading 1511/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130731_1548_HARP3012_NOAA11806.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130731_1548_HARP3012_NOAA11806.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9c3390b72d5d60a0bddd5ed6d38e47a3.npz

.

Average throughput: 191.3MiB/s

[train] downloading 1512/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120419_1248_HARP1594_NOAA11464.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120419_1248_HARP1594_NOAA11464.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/971a72e17e73954c7a66a92f2edacb8b.npz

.

Average throughput: 68.4MiB/s

[train] downloading 1513/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110701_1012_HARP685_NOAA11243.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110701_1012_HARP685_NOAA11243.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0c038bde77c0e799fe7cbe2bf3cdc9e3.npz

.

Average throughput: 122.4MiB/s

[train] downloading 1514/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111109_0324_HARP1026_NOAA11338.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111109_0324_HARP1026_NOAA11338.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/09470eb426f0878ca45ea7b7e7500952.npz

.

Average throughput: 74.8MiB/s

[train] downloading 1515/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120924_0736_HARP2040_NOAA11575.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120924_0736_HARP2040_NOAA11575.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9b55045034febd9490ec4671a48590b2.npz

.

Average throughput: 190.9MiB/s

[train] downloading 1516/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121116_2336_HARP2193_NOAA11614.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121116_2336_HARP2193_NOAA11614.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5c41550f31ed31d88fcff48d5ae97276.npz

.

Average throughput: 152.9MiB/s

[train] downloading 1517/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130525_2124_HARP2760_NOAA11753.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130525_2124_HARP2760_NOAA11753.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c8531fd67d678f5c863c72da758cd3f9.npz

.

Average throughput: 71.4MiB/s

[train] downloading 1518/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130325_1036_HARP2585_NOAA11705.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130325_1036_HARP2585_NOAA11705.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2424b1b8094e54c0cd89083ea5e8cedf.npz

.

Average throughput: 136.2MiB/s

[train] downloading 1519/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120614_1000_HARP1750_NOAA11504.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120614_1000_HARP1750_NOAA11504.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/18b7abb3c8be04325d304769cf3d2ff1.npz

.

Average throughput: 124.6MiB/s

[train] downloading 1520/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110228_0624_HARP394_NOAA11165.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110228_0624_HARP394_NOAA11165.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2a6b13cad98eb957ec831815148fdcfe.npz

.

Average throughput: 122.5MiB/s

[train] downloading 1521/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130502_1812_HARP2693_NOAA11731.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130502_1812_HARP2693_NOAA11731.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/eb2f5562593b9362084d1483673f6ce8.npz

.

Average throughput: 99.2MiB/s

[train] downloading 1522/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111201_1324_HARP1119_NOAA11361.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111201_1324_HARP1119_NOAA11361.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a5a00b3bec775a318b480a6f73813ea9.npz

.

Average throughput: 85.9MiB/s

[train] downloading 1523/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131009_0224_HARP3260_NOAA11860.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131009_0224_HARP3260_NOAA11860.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/88ae9238e2d39c1d8ebaa85dda7cceae.npz

.

Average throughput: 26.7MiB/s

[train] downloading 1524/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110727_0748_HARP748_NOAA11265.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110727_0748_HARP748_NOAA11265.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6e56990e7b9d46e6ca2df631f9593618.npz

.

Average throughput: 114.2MiB/s

[train] downloading 1525/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120508_0524_HARP1632_NOAA11474.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120508_0524_HARP1632_NOAA11474.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/dbf61ce2d3fc2f670e240f0fa2bf188d.npz

.

Average throughput: 46.1MiB/s

[train] downloading 1526/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130129_1912_HARP2420_NOAA11663.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130129_1912_HARP2420_NOAA11663.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/50cbc86aa3b7bd7d4e280aafca548794.npz

.

Average throughput: 197.8MiB/s

[train] downloading 1527/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130715_0936_HARP2952_NOAA11791.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130715_0936_HARP2952_NOAA11791.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e7ced69820b16ec4fdd9aa4c329d8729.npz

.

Average throughput: 170.7MiB/s

[train] downloading 1528/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130418_1912_HARP2661_NOAA11724.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130418_1912_HARP2661_NOAA11724.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0d5c86c172f1f0a35ba249c7aa92a0b3.npz

.

Average throughput: 90.5MiB/s

[train] downloading 1529/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120105_0148_HARP1256_NOAA11388.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120105_0148_HARP1256_NOAA11388.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ad6b39949f93c74c9278eb9eb8185d1c.npz

.

Average throughput: 131.1MiB/s

[train] downloading 1530/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121006_1300_HARP2106_NOAA11588.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121006_1300_HARP2106_NOAA11588.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8a7e486378eb64c8ea0eca5675314ab6.npz

.

Average throughput: 115.2MiB/s

[train] downloading 1531/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130312_0812_HARP2541_NOAA11691.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130312_0812_HARP2541_NOAA11691.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f5fb97e30ca487a3a50537823d8a3a75.npz

.

Average throughput: 159.6MiB/s

[train] downloading 1532/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131113_1836_HARP3364_NOAA11893.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131113_1836_HARP3364_NOAA11893.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d8229b9a5e8592ab3d4a6d775206a1a7.npz

.

Average throughput: 136.3MiB/s

[train] downloading 1533/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110603_1712_HARP639_NOAA11228.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110603_1712_HARP639_NOAA11228.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/abc7c72ba73e96700473e0efe2489f90.npz

.

Average throughput: 144.0MiB/s

[train] downloading 1534/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100730_1836_HARP98_NOAA11090.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100730_1836_HARP98_NOAA11090.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/560e7d737adbc5f7099a8e5d330c0d28.npz

.

Average throughput: 118.0MiB/s

[train] downloading 1535/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111117_2000_HARP1066_NOAA11346.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111117_2000_HARP1066_NOAA11346.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/06711b1f00ca627d1d7db83d2693c04a.npz

.

Average throughput: 121.0MiB/s

[train] downloading 1536/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131230_0036_HARP3557_NOAA11938.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131230_0036_HARP3557_NOAA11938.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/af0339e3152d495ccf342d9003dabd1d.npz

.

Average throughput: 57.4MiB/s

[train] downloading 1537/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120501_0336_HARP1613_NOAA11467.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120501_0336_HARP1613_NOAA11467.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/875da63c12b3aecb9eb331f04ddbc899.npz

.

Average throughput: 93.1MiB/s

[train] downloading 1538/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130217_1100_HARP2491_NOAA11675.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130217_1100_HARP2491_NOAA11675.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e79f1dbdf66c3e2c45e6d48e0cdca26f.npz

.

Average throughput: 48.4MiB/s

[train] downloading 1539/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120316_2324_HARP1464_NOAA11434.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120316_2324_HARP1464_NOAA11434.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/452f313281cf3394cf4387ae0fbdce97.npz

.

Average throughput: 103.7MiB/s

[train] downloading 1540/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130518_0848_HARP2739_NOAA11745.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130518_0848_HARP2739_NOAA11745.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/783bb1ba85726516de96ce8d9285c95b.npz

.

Average throughput: 80.5MiB/s

[train] downloading 1541/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100728_0900_HARP98_NOAA11090.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100728_0900_HARP98_NOAA11090.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/49ccbe78ce1f3b3854b07d2c26373a0d.npz

.

Average throughput: 147.7MiB/s

[train] downloading 1542/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130327_2148_HARP2585_NOAA11705.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130327_2148_HARP2585_NOAA11705.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/febe1d51b3cf960a771b64e702f1ce86.npz

.

Average throughput: 75.3MiB/s

[train] downloading 1543/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120101_2100_HARP1256_NOAA11388.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120101_2100_HARP1256_NOAA11388.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/61542601fcde79c8e94c392052f6359a.npz

.

Average throughput: 94.6MiB/s

[train] downloading 1544/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130217_0748_HARP2469_NOAA11671.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130217_0748_HARP2469_NOAA11671.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/60fb76fceddd296577488ef8cdde4812.npz

.

Average throughput: 151.6MiB/s

[train] downloading 1545/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110504_0412_HARP556_NOAA11203.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110504_0412_HARP556_NOAA11203.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8b773877d5daa83d1e63197ab697ae01.npz

.

Average throughput: 166.3MiB/s

[train] downloading 1546/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120614_0612_HARP1756_NOAA11506.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120614_0612_HARP1756_NOAA11506.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c321496827bd0d9c792806312de371e1.npz

.

Average throughput: 150.6MiB/s

[train] downloading 1547/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120402_0348_HARP1528_NOAA11450.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120402_0348_HARP1528_NOAA11450.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/17038ccdd151d01eb6ed321c81f621b1.npz

.

Average throughput: 156.5MiB/s

[train] downloading 1548/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110203_1212_HARP355_NOAA11150.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110203_1212_HARP355_NOAA11150.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/bc7505aa40fc0eab46c31fae8f5384aa.npz

.

Average throughput: 74.5MiB/s

[train] downloading 1549/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110703_1512_HARP693_NOAA11246.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110703_1512_HARP693_NOAA11246.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3cb15b83d24186f227356ee04aec13bd.npz

.

Average throughput: 197.0MiB/s

[train] downloading 1550/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121021_0948_HARP2123_NOAA11594.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121021_0948_HARP2123_NOAA11594.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0c4b11abc53875bb6f06a3aa69281b05.npz

.

Average throughput: 63.3MiB/s

[train] downloading 1551/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120723_2124_HARP1866_NOAA11524.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120723_2124_HARP1866_NOAA11524.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/bffd4fd3ad248b0005340a45a0bd7d23.npz

.

Average throughput: 194.1MiB/s

[train] downloading 1552/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111012_0148_HARP956_NOAA11318.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111012_0148_HARP956_NOAA11318.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fd945d05c34e0008427fbdd016ff38de.npz

.

Average throughput: 172.0MiB/s

[train] downloading 1553/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120513_1348_HARP1644_NOAA11477.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120513_1348_HARP1644_NOAA11477.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fbb955d2a93630d78f5e40db6ef8cea5.npz



Average throughput: 173.2MiB/s

[train] downloading 1554/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110718_1600_HARP725_NOAA11254.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110718_1600_HARP725_NOAA11254.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4914df4f3b02edf5bd3bd82743379791.npz

.

Average throughput: 113.3MiB/s

[train] downloading 1555/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120109_1936_HARP1278_NOAA11391.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120109_1936_HARP1278_NOAA11391.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7a05d300bfaa3fd4cba6d68645b5fdb9.npz

.

Average throughput: 112.1MiB/s

[train] downloading 1556/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130210_0900_HARP2450_NOAA11669.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130210_0900_HARP2450_NOAA11669.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d81dfdd2f73c832a0cfdf162be905456.npz

.

Average throughput: 95.6MiB/s

[train] downloading 1557/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110311_2224_HARP407_NOAA11169.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110311_2224_HARP407_NOAA11169.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2ccb64a81db9b451d037fa006ffb252d.npz

.

Average throughput: 192.2MiB/s

[train] downloading 1558/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130601_1600_HARP2779_NOAA11757.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130601_1600_HARP2779_NOAA11757.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/463ac2b575e0994d3a66e6d2f5236f02.npz

.

Average throughput: 149.0MiB/s

[train] downloading 1559/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100916_1612_HARP182_NOAA11107.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100916_1612_HARP182_NOAA11107.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/079caf214be8c2430a262eed0cda025f.npz

.

Average throughput: 116.1MiB/s

[train] downloading 1560/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111106_1748_HARP1026_NOAA11338.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111106_1748_HARP1026_NOAA11338.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ff624614b03d50f261b7ad6407b8ded2.npz

.

Average throughput: 50.1MiB/s

[train] downloading 1561/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111028_0312_HARP997_NOAA11330.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111028_0312_HARP997_NOAA11330.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/938630ae525211081764e025ef75ba8b.npz

.

Average throughput: 147.5MiB/s

[train] downloading 1562/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130612_1512_HARP2839_NOAA11767.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130612_1512_HARP2839_NOAA11767.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/33d6820a35308ab436e8f204b19bb390.npz

.

Average throughput: 89.9MiB/s

[train] downloading 1563/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130628_0300_HARP2904_NOAA11780.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130628_0300_HARP2904_NOAA11780.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/60a274e8a9b1ab314d46fb35b7813033.npz

.

Average throughput: 137.0MiB/s

[train] downloading 1564/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120120_0036_HARP1313_NOAA11403.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120120_0036_HARP1313_NOAA11403.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8b448e6d1402a9e9d5a70f67146d846a.npz

.

Average throughput: 135.5MiB/s

[train] downloading 1565/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130823_1412_HARP3103_NOAA11828.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130823_1412_HARP3103_NOAA11828.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f5b6e9f49c2f5f3ecf112f20cf0d0bf9.npz

.

Average throughput: 76.8MiB/s

[train] downloading 1566/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130328_0324_HARP2587_NOAA11704.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130328_0324_HARP2587_NOAA11704.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/37a410ad5938a330679f9be61c42428e.npz

.

Average throughput: 144.1MiB/s

[train] downloading 1567/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130715_2048_HARP2952_NOAA11791.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130715_2048_HARP2952_NOAA11791.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1dfa86170c707c4cffd8b8cd1566e799.npz

.

Average throughput: 147.2MiB/s

[train] downloading 1568/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131104_2348_HARP3330_NOAA11887.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131104_2348_HARP3330_NOAA11887.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4813d23ba4c3ee98024df6c4f86bc709.npz

.

Average throughput: 90.7MiB/s

[train] downloading 1569/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101128_1200_HARP274_NOAA11130.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101128_1200_HARP274_NOAA11130.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/41308b8b24ccff83ace1ce7fab9a0956.npz

.

Average throughput: 28.8MiB/s

[train] downloading 1570/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110330_0212_HARP443_NOAA11181.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110330_0212_HARP443_NOAA11181.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e80acc7590e8cfb2983fc0b32b71c980.npz

.

Average throughput: 81.6MiB/s

[train] downloading 1571/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130720_1936_HARP2964_NOAA11795.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130720_1936_HARP2964_NOAA11795.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1c5271241509af4b156d739b8b6890a2.npz

.

Average throughput: 176.1MiB/s

[train] downloading 1572/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130708_2024_HARP2945_NOAA11794.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130708_2024_HARP2945_NOAA11794.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b6323e59b110bef3e52ebbfd2ef4fd3f.npz

.

Average throughput: 101.8MiB/s

[train] downloading 1573/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121121_0212_HARP2203_NOAA11616.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121121_0212_HARP2203_NOAA11616.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3f6fd0bc642343ae88bb76123c97f8e0.npz

.

Average throughput: 151.9MiB/s

[train] downloading 1574/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120802_1000_HARP1879_NOAA11529.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120802_1000_HARP1879_NOAA11529.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/53688da477fe0dc595d4aa64ef8a862a.npz

.

Average throughput: 185.7MiB/s

[train] downloading 1575/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120605_0900_HARP1724_NOAA11494.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120605_0900_HARP1724_NOAA11494.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7e11fddd09b30a9366f055d60f0a6a82.npz

.

Average throughput: 153.7MiB/s

[train] downloading 1576/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120601_1000_HARP1715_NOAA11495.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120601_1000_HARP1715_NOAA11495.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5e52f875bc4e329565324bb51c3373b7.npz

.

Average throughput: 60.4MiB/s

[train] downloading 1577/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110427_1224_HARP540_NOAA11199.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110427_1224_HARP540_NOAA11199.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7d438b43ec366c628cf4cb5346c8217e.npz

.

Average throughput: 59.1MiB/s

[train] downloading 1578/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120516_0612_HARP1658_NOAA11483.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120516_0612_HARP1658_NOAA11483.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d1f314ca5a24b7f8ce21612721a1bb18.npz

.

Average throughput: 70.5MiB/s

[train] downloading 1579/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131029_0212_HARP3311_NOAA11882.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131029_0212_HARP3311_NOAA11882.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cb6b374162e1f3842276707e52c8b0e7.npz

.

Average throughput: 173.8MiB/s

[train] downloading 1580/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110621_1600_HARP674_NOAA11237.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110621_1600_HARP674_NOAA11237.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/df703f97d9680cad7a7aef90b73f8501.npz

.

Average throughput: 169.4MiB/s

[train] downloading 1581/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120501_0648_HARP1613_NOAA11467.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120501_0648_HARP1613_NOAA11467.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7f0aba2ac8c6d3d2abefcdde1a81cc1e.npz

.

Average throughput: 119.9MiB/s

[train] downloading 1582/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120606_1836_HARP1724_NOAA11494.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120606_1836_HARP1724_NOAA11494.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ffc2bdcc82df739a682aa1642c60c612.npz

.

Average throughput: 78.0MiB/s

[train] downloading 1583/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101002_1612_HARP198_NOAA11111.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101002_1612_HARP198_NOAA11111.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6b5dcc09735872c36ef19f457b65ddaf.npz

.

Average throughput: 143.9MiB/s

[train] downloading 1584/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120820_1436_HARP1943_NOAA11547.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120820_1436_HARP1943_NOAA11547.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/691f92c2ebc15dca72ba9652e8b6cbe6.npz

.

Average throughput: 159.4MiB/s

[train] downloading 1585/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130602_0100_HARP2790_NOAA11758.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130602_0100_HARP2790_NOAA11758.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/129bbbca0a19e447e46d795c679e1a8a.npz

.

Average throughput: 92.5MiB/s

[train] downloading 1586/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120522_1724_HARP1680_NOAA11487.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120522_1724_HARP1680_NOAA11487.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1fe56af079aa3346266b095bc4450b4c.npz

.

Average throughput: 63.2MiB/s

[train] downloading 1587/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120602_1236_HARP1705_NOAA11492.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120602_1236_HARP1705_NOAA11492.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e14a833b11e172757c82b266d0f53644.npz

.

Average throughput: 52.4MiB/s

[train] downloading 1588/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111021_0324_HARP975_NOAA11321.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111021_0324_HARP975_NOAA11321.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a8e3fbd6f65811d97c0c16a729db464c.npz

.

Average throughput: 113.4MiB/s

[train] downloading 1589/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131106_1936_HARP3341_NOAA11890.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131106_1936_HARP3341_NOAA11890.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5821cca518f60dec6db1aa45a471c4ed.npz

.

Average throughput: 166.7MiB/s

[train] downloading 1590/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100828_1312_HARP146_NOAA11102.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100828_1312_HARP146_NOAA11102.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/71288499707b30ebaa8e1904b9f72071.npz

.

Average throughput: 149.7MiB/s

[train] downloading 1591/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121121_1924_HARP2220_NOAA11618.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121121_1924_HARP2220_NOAA11618.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d4bb3081c2b313ccdbfafc0eef630080.npz

.

Average throughput: 98.4MiB/s

[train] downloading 1592/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120923_0800_HARP2044_NOAA11576.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120923_0800_HARP2044_NOAA11576.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/eef1e2c1e6e93b6f26680ba7146d398a.npz

.

Average throughput: 129.9MiB/s

[train] downloading 1593/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120605_0236_HARP1722_NOAA11493.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120605_0236_HARP1722_NOAA11493.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1c9cd77b2cb638252979349f72415cae.npz

.

Average throughput: 174.7MiB/s

[train] downloading 1594/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131006_2212_HARP3246_NOAA11866.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131006_2212_HARP3246_NOAA11866.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c288f23ffc8e55e9d28f7359854bbcc0.npz

.

Average throughput: 166.9MiB/s

[train] downloading 1595/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130411_2324_HARP2634_NOAA11717.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130411_2324_HARP2634_NOAA11717.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4ab91ae1ef844563e0f2f42cea2937af.npz

.

Average throughput: 102.8MiB/s

[train] downloading 1596/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131108_0312_HARP3344_NOAA11891.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131108_0312_HARP3344_NOAA11891.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/02697d2a0735efe1ccf0bc33aa62084a.npz

.

Average throughput: 157.7MiB/s

[train] downloading 1597/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121222_0724_HARP2306_NOAA11633.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121222_0724_HARP2306_NOAA11633.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/007b3a58d1347be00aee88725e699716.npz

.

Average throughput: 120.7MiB/s

[train] downloading 1598/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120218_1648_HARP1405_NOAA11422.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120218_1648_HARP1405_NOAA11422.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/666f2b1e357c2a8479f73801abd6d031.npz

.

Average throughput: 67.8MiB/s

[train] downloading 1599/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130606_1524_HARP2825_NOAA11765.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130606_1524_HARP2825_NOAA11765.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/eda9253fa0a4facd88ddd602fe2aa909.npz

.

Average throughput: 126.9MiB/s

[train] downloading 1600/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120202_1024_HARP1367_NOAA11415.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120202_1024_HARP1367_NOAA11415.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/394a356b6d4a69e4f8ebd96915344a02.npz

.

Average throughput: 142.6MiB/s

[train] cached/checked 1600/1650 files | elapsed 41.1 min
[train] downloading 1601/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120526_0536_HARP1677_NOAA11486.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120526_0536_HARP1677_NOAA11486.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/31b0379d3a9dde76a8a156ffd4c00a2e.npz

.

Average throughput: 155.7MiB/s

[train] downloading 1602/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111116_1648_HARP1066_NOAA11346.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111116_1648_HARP1066_NOAA11346.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e0b2cc2be54bd05d910d9baa28b5f9e1.npz



Average throughput: 176.6MiB/s

[train] downloading 1603/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100828_1448_HARP146_NOAA11102.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100828_1448_HARP146_NOAA11102.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/31f81a1a653d1a0cbc84dc4cf6f7feb2.npz

.

Average throughput: 102.9MiB/s

[train] downloading 1604/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130806_2100_HARP3028_NOAA11809.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130806_2100_HARP3028_NOAA11809.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f4e5647a9c6bf48d147c783c9d7aa1db.npz

.

Average throughput: 89.0MiB/s

[train] downloading 1605/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131130_1112_HARP3432_NOAA11908.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131130_1112_HARP3432_NOAA11908.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/dfbc5749aa6d3bdafba3be3890d44ff7.npz

.

Average throughput: 90.0MiB/s

[train] downloading 1606/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131023_0236_HARP3286_NOAA11872.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131023_0236_HARP3286_NOAA11872.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ccccc1a5050a66dd376bd20f2ba55593.npz

.

Average throughput: 162.9MiB/s

[train] downloading 1607/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130405_0400_HARP2626_NOAA11715.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130405_0400_HARP2626_NOAA11715.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f14e42f2c5646753996db0c0b89c1f30.npz

.

Average throughput: 170.5MiB/s

[train] downloading 1608/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110506_0612_HARP556_NOAA11203.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110506_0612_HARP556_NOAA11203.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/64ad661d854bec68c5245d95511727a9.npz

.

Average throughput: 100.5MiB/s

[train] downloading 1609/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120213_0912_HARP1389_NOAA11416.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120213_0912_HARP1389_NOAA11416.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8adad4415d1793ae3934e342515023a3.npz

.

Average throughput: 157.6MiB/s

[train] downloading 1610/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111123_1312_HARP1093_NOAA11353.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111123_1312_HARP1093_NOAA11353.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d951e3a43f67f62c989e912fe382b497.npz

.

Average throughput: 76.2MiB/s

[train] downloading 1611/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130530_2148_HARP2790_NOAA11758.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130530_2148_HARP2790_NOAA11758.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3d9b89d1bd5e93f8c2e7d2fd9685ff5e.npz

.

Average throughput: 165.5MiB/s

[train] downloading 1612/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120129_0948_HARP1338_NOAA11408.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120129_0948_HARP1338_NOAA11408.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f1ddfeb8c9a3705745c126bb30cabdf8.npz

.

Average throughput: 139.2MiB/s

[train] downloading 1613/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130105_1036_HARP2353_NOAA11645.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130105_1036_HARP2353_NOAA11645.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f828ae1dd905ce6e8b2330858ee598dc.npz

.

Average throughput: 76.8MiB/s

[train] downloading 1614/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101022_1400_HARP224_NOAA11119.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20101022_1400_HARP224_NOAA11119.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c910727a3cf45320e8f477c822e3b133.npz

.

Average throughput: 132.0MiB/s

[train] downloading 1615/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111110_0636_HARP1026_NOAA11338.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111110_0636_HARP1026_NOAA11338.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/28c6134c691f67910aad7a00415e39ed.npz

.

Average throughput: 94.0MiB/s

[train] downloading 1616/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130303_0012_HARP2519_NOAA11686.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130303_0012_HARP2519_NOAA11686.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/91d68c2aab2345590fcc68d553eb893e.npz

.

Average throughput: 116.6MiB/s

[train] downloading 1617/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111202_2312_HARP1120_NOAA11362.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111202_2312_HARP1120_NOAA11362.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/984424c14e0a3699336ea689d081ded8.npz

.

Average throughput: 120.3MiB/s

[train] downloading 1618/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120824_0736_HARP1962_NOAA11554.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120824_0736_HARP1962_NOAA11554.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f0b75fee89655117564e889ea771d5aa.npz

.

Average throughput: 153.1MiB/s

[train] downloading 1619/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110905_1336_HARP833_NOAA11283.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110905_1336_HARP833_NOAA11283.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f8e2cbce12c10b2c0eda8dda920f7523.npz



Average throughput: 186.7MiB/s

[train] downloading 1620/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130406_1236_HARP2605_NOAA11711.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130406_1236_HARP2605_NOAA11711.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/757706a61154fc9c5c2ac417249255a6.npz

.

Average throughput: 151.7MiB/s

[train] downloading 1621/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111001_1136_HARP903_NOAA11306.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111001_1136_HARP903_NOAA11306.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/029aefe21b0b0d9bc581de9d7ff8dd48.npz

.

Average throughput: 110.1MiB/s

[train] downloading 1622/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111115_1336_HARP1075_NOAA11347.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111115_1336_HARP1075_NOAA11347.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cece589d12541576568be705ad61c023.npz

.

Average throughput: 139.6MiB/s

[train] downloading 1623/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111119_0712_HARP1075_NOAA11347.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111119_0712_HARP1075_NOAA11347.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/16c204a48f51ae0306090329556badbf.npz

.

Average throughput: 84.3MiB/s

[train] downloading 1624/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111018_0224_HARP940_NOAA11314.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111018_0224_HARP940_NOAA11314.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a4d3d66ac8dd70f83f9ab1d0d6673f74.npz

.

Average throughput: 102.0MiB/s

[train] downloading 1625/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120214_0048_HARP1391_NOAA11417.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120214_0048_HARP1391_NOAA11417.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/682acad7b51f7f5d23e3064ae25063dc.npz

.

Average throughput: 37.7MiB/s

[train] downloading 1626/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120117_1712_HARP1309_NOAA11396.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120117_1712_HARP1309_NOAA11396.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c608a73581d58dea0a7a34ba45bdee45.npz

.

Average throughput: 75.4MiB/s

[train] downloading 1627/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130108_1036_HARP2342_NOAA11643.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130108_1036_HARP2342_NOAA11643.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/096e48147cbb1c1bfabd293e73b47d84.npz

.

Average throughput: 94.9MiB/s

[train] downloading 1628/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110214_0612_HARP371_NOAA11159.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110214_0612_HARP371_NOAA11159.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0d53f579072d65e06b8530c76a3fc007.npz

.

Average throughput: 147.4MiB/s

[train] downloading 1629/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111130_0648_HARP1113_NOAA11358.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111130_0648_HARP1113_NOAA11358.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9fe865eab79c72e4887540ab0a695c38.npz

.

Average throughput: 149.7MiB/s

[train] downloading 1630/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111029_1912_HARP997_NOAA11330.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111029_1912_HARP997_NOAA11330.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7ceb920da406aaf4f05c21ea2f0294e8.npz

.

Average throughput: 97.6MiB/s

[train] downloading 1631/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110724_1848_HARP740_NOAA11259.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110724_1848_HARP740_NOAA11259.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/505db21e5ad5cd93e9fd5e12e0734e0c.npz

.

Average throughput: 142.3MiB/s

[train] downloading 1632/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111009_0148_HARP913_NOAA11308.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111009_0148_HARP913_NOAA11308.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6356ae940a397f683f7fcf9c4af75994.npz

.

Average throughput: 89.8MiB/s

[train] downloading 1633/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131022_0312_HARP3291_NOAA11875.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131022_0312_HARP3291_NOAA11875.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/639d2f79b74f3e79ab288616b468e980.npz

.

Average throughput: 156.5MiB/s

[train] downloading 1634/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110715_0648_HARP705_NOAA11248.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110715_0648_HARP705_NOAA11248.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/00e52767f33cbf0d1f6184e7d3e81625.npz



Average throughput: 181.4MiB/s

[train] downloading 1635/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120204_2036_HARP1381_NOAA11414.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20120204_2036_HARP1381_NOAA11414.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7f0f5e3c6ccd75aa3820d14d0102b3ed.npz

.

Average throughput: 183.3MiB/s

[train] downloading 1636/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110407_1736_HARP488_NOAA11188.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110407_1736_HARP488_NOAA11188.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1bd8391961899134aefa9190d87bf16f.npz

.

Average throughput: 50.1MiB/s

[train] downloading 1637/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110213_1712_HARP377_NOAA11158.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110213_1712_HARP377_NOAA11158.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/82064a00427be2966575c5e2424ec109.npz

.

Average throughput: 80.5MiB/s

[train] downloading 1638/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110713_1548_HARP705_NOAA11248.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110713_1548_HARP705_NOAA11248.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/206d1dfe5a0b0e981e2b958f34cf8466.npz

.

Average throughput: 85.3MiB/s

[train] downloading 1639/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130111_0548_HARP2358_NOAA11649.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130111_0548_HARP2358_NOAA11649.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8c459cbed71a1c9d6299598220b9189d.npz

.

Average throughput: 128.4MiB/s

[train] downloading 1640/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110612_2148_HARP662_NOAA11235.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110612_2148_HARP662_NOAA11235.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/19a9868344cb63b3d8b90383b6319160.npz

.

Average throughput: 128.7MiB/s

[train] downloading 1641/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100604_0324_HARP45_NOAA11073.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2010/20100604_0324_HARP45_NOAA11073.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2054bc7da35b690c81a528abca6511fe.npz

.

Average throughput: 96.1MiB/s

[train] downloading 1642/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110305_2248_HARP393_NOAA11164.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110305_2248_HARP393_NOAA11164.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/64575daf50747f782c0f089901d83152.npz

.

Average throughput: 186.5MiB/s

[train] downloading 1643/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131031_2036_HARP3320_NOAA11883.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131031_2036_HARP3320_NOAA11883.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8b211b92978f5b3bc99393dda104c160.npz

.

Average throughput: 122.6MiB/s

[train] downloading 1644/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111012_0400_HARP932_NOAA11313.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20111012_0400_HARP932_NOAA11313.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ecca4897638a068d426ac52fb555f8ff.npz

..

Average throughput: 23.2MiB/s

[train] downloading 1645/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130301_2200_HARP2502_NOAA11681.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130301_2200_HARP2502_NOAA11681.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c8fd64b6c03828ed090545e71280f802.npz

.

Average throughput: 108.5MiB/s

[train] downloading 1646/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110820_0600_HARP798_NOAA11272.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110820_0600_HARP798_NOAA11272.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9efef7a590389f273f953a818d3b44fc.npz

.

Average throughput: 62.6MiB/s

[train] downloading 1647/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121017_0948_HARP2109_NOAA11589.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2012/20121017_0948_HARP2109_NOAA11589.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/86b6213961a22cf46729445db7613c83.npz

.

Average throughput: 116.2MiB/s

[train] downloading 1648/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131116_2012_HARP3386_NOAA11902.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20131116_2012_HARP3386_NOAA11902.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c694b06d85952812e4c8cffac0e8fb60.npz

.

Average throughput: 186.7MiB/s

[train] downloading 1649/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130921_1424_HARP3188_NOAA11853.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2013/20130921_1424_HARP3188_NOAA11853.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4ec75844c059f6fbff176493b470176d.npz

.

Average throughput: 94.4MiB/s

[train] downloading 1650/1650: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110322_1200_HARP436_NOAA11179.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2011/20110322_1200_HARP436_NOAA11179.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/df8422a91dbe9ed23ea5c0580594acc9.npz

.

Average throughput: 80.4MiB/s

[train] cached/checked 1650/1650 files | elapsed 42.4 min
Finished pre-caching train
Pre-caching val: 825 files
[val] downloading 1/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140705_0812_HARP4294_NOAA12102.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140705_0812_HARP4294_NOAA12102.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e3b4f877bc3deb59ec37fa87598162cb.npz

.

Average throughput: 105.2MiB/s

[val] downloading 2/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141229_0512_HARP5005_NOAA12256.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141229_0512_HARP5005_NOAA12256.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b5a764fe56e7a3dc1d8152d3780a11ff.npz

.

Average throughput: 90.4MiB/s

[val] downloading 3/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141127_2036_HARP4868_NOAA12219.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141127_2036_HARP4868_NOAA12219.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ae077d64315f8ff3facbca8f64d79ec0.npz

.

Average throughput: 151.1MiB/s

[val] downloading 4/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141207_2236_HARP4888_NOAA12227.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141207_2236_HARP4888_NOAA12227.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c3a7c63ba1be6aa2feb7969930507931.npz

.

Average throughput: 152.6MiB/s

[val] downloading 5/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140526_1236_HARP4156_NOAA12071.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140526_1236_HARP4156_NOAA12071.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0414a9e13c27ebd7d5ddddae0fc9d23d.npz

.

Average throughput: 144.8MiB/s

[val] downloading 6/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141104_0624_HARP4760_NOAA12201.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141104_0624_HARP4760_NOAA12201.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/26c499237ae541f23cebf593b1bd3cde.npz

.

Average throughput: 206.1MiB/s

[val] downloading 7/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140630_0700_HARP4302_NOAA12105.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140630_0700_HARP4302_NOAA12105.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8116fe523f0911b034bd45fb4e42686b.npz

.

Average throughput: 172.4MiB/s

[val] downloading 8/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140708_2136_HARP4328_NOAA12111.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140708_2136_HARP4328_NOAA12111.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7caa951729228586a7b817946dbfce14.npz

.

Average throughput: 165.2MiB/s

[val] downloading 9/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141130_0112_HARP4864_NOAA12218.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141130_0112_HARP4864_NOAA12218.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1926658f42c98c93f5e2d1a88c1bd1fd.npz

.

Average throughput: 157.6MiB/s

[val] downloading 10/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140805_1148_HARP4422_NOAA12133.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140805_1148_HARP4422_NOAA12133.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9a153a97d1889a04906872cbdb9a521d.npz

.

Average throughput: 122.1MiB/s

[val] downloading 11/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140113_0824_HARP3586_NOAA11948.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140113_0824_HARP3586_NOAA11948.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c262bc5310324bebb2281c8026913d54.npz

.

Average throughput: 73.9MiB/s

[val] downloading 12/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140112_1448_HARP3608_NOAA11953.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140112_1448_HARP3608_NOAA11953.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2fd335ff61b1badb08a1f1652cbb6a13.npz

.

Average throughput: 167.3MiB/s

[val] downloading 13/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140401_0112_HARP3912_NOAA12021.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140401_0112_HARP3912_NOAA12021.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0e8d432f948af480f46b55025155da40.npz

.

Average throughput: 141.3MiB/s

[val] downloading 14/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141201_2024_HARP4864_NOAA12218.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141201_2024_HARP4864_NOAA12218.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e59abb5c47fa217d36ed207ef214778b.npz

.

Average throughput: 124.7MiB/s

[val] downloading 15/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140508_1324_HARP4088_NOAA12052.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140508_1324_HARP4088_NOAA12052.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/73274ebacd1940f3b1997bc79a5b1345.npz

.

Average throughput: 161.1MiB/s

[val] downloading 16/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141119_1248_HARP4817_NOAA12113.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141119_1248_HARP4817_NOAA12113.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/07afe28a1e021451225d4157c35d8536.npz

.

Average throughput: 40.4MiB/s

[val] downloading 17/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140610_1848_HARP4197_NOAA12080.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140610_1848_HARP4197_NOAA12080.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/35156630f237cecfd82eec7dba3cc073.npz

.

Average throughput: 127.0MiB/s

[val] downloading 18/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141209_0100_HARP4901_NOAA12229.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141209_0100_HARP4901_NOAA12229.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/18c7c4ed942b068fe0e816fd2468d4af.npz

.

Average throughput: 150.6MiB/s

[val] downloading 19/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140305_0148_HARP3813_NOAA11996.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140305_0148_HARP3813_NOAA11996.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/502ef75ee1f51d4ea0611caa544a4b31.npz

.

Average throughput: 49.4MiB/s

[val] downloading 20/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140607_2324_HARP4201_NOAA12084.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140607_2324_HARP4201_NOAA12084.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c4bbfde71c574dab6a65e4d08163778f.npz

.

Average throughput: 149.6MiB/s

[val] downloading 21/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140520_2100_HARP4138_NOAA12065.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140520_2100_HARP4138_NOAA12065.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/039ec6f0002e18f750f1d8edf4148d86.npz

.

Average throughput: 82.5MiB/s

[val] downloading 22/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141103_2212_HARP4764_NOAA12203.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141103_2212_HARP4764_NOAA12203.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8a56e5d16a066af660efd0e7f4ddf5fa.npz

.

Average throughput: 98.2MiB/s

[val] downloading 23/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140227_2324_HARP3806_NOAA11992.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140227_2324_HARP3806_NOAA11992.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/44f2140c023d5c8e68f7153edd5e0ec0.npz

.

Average throughput: 96.5MiB/s

[val] downloading 24/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140322_1012_HARP3875_NOAA12016.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140322_1012_HARP3875_NOAA12016.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/eb346d30e9ca418c63b758a150051182.npz

.

Average throughput: 78.6MiB/s

[val] downloading 25/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140504_0136_HARP4075_NOAA12050.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140504_0136_HARP4075_NOAA12050.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3fc1ad67c742eb26b6a27f480a31cb13.npz

.

Average throughput: 127.4MiB/s

[val] downloading 26/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140613_1112_HARP4231_NOAA12089.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140613_1112_HARP4231_NOAA12089.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/266c0c68c79d3140a43425e1fd9af2f5.npz

.

Average throughput: 177.3MiB/s

[val] downloading 27/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140217_0548_HARP3740_NOAA11977.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140217_0548_HARP3740_NOAA11977.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4bf71b7a218795334f2612ca6de2d711.npz

.

Average throughput: 114.6MiB/s

[val] downloading 28/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141029_1936_HARP4726_NOAA12195.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141029_1936_HARP4726_NOAA12195.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6334bb6df41897a0e24e844621a9c281.npz

.

Average throughput: 75.5MiB/s

[val] downloading 29/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140806_0212_HARP4422_NOAA12133.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140806_0212_HARP4422_NOAA12133.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fcd44b3497f08dff3bb1ac1e4ac56d9f.npz

.

Average throughput: 136.2MiB/s

[val] downloading 30/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141206_0348_HARP4882_NOAA12225.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141206_0348_HARP4882_NOAA12225.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/599d500ee47e303ca624db6f34ebf224.npz

.

Average throughput: 86.5MiB/s

[val] downloading 31/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140712_1124_HARP4351_NOAA12114.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140712_1124_HARP4351_NOAA12114.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/90c19cdf9f14670970d241bfc2acba6e.npz

.

Average throughput: 56.7MiB/s

[val] downloading 32/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140515_1336_HARP4135_NOAA12064.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140515_1336_HARP4135_NOAA12064.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/28df9621b69529afea91c51ddd6e0e4b.npz

.

Average throughput: 100.7MiB/s

[val] downloading 33/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140416_2212_HARP4023_NOAA12041.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140416_2212_HARP4023_NOAA12041.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ff50159436d859f27e2c920f4c5d6ffc.npz

.

Average throughput: 151.4MiB/s

[val] downloading 34/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140227_1836_HARP3806_NOAA11992.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140227_1836_HARP3806_NOAA11992.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/448f3c16d2325587b187e4bcbc0741f5.npz

.

Average throughput: 101.8MiB/s

[val] downloading 35/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140620_2336_HARP4256_NOAA12094.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140620_2336_HARP4256_NOAA12094.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fdccfff14105bd755db0f4621e957bb6.npz

.

Average throughput: 127.3MiB/s

[val] downloading 36/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140621_2136_HARP4252_NOAA12093.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140621_2136_HARP4252_NOAA12093.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c303124a687cf9a87fef897bc48a787d.npz

.

Average throughput: 169.9MiB/s

[val] downloading 37/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140421_0824_HARP4025_NOAA12042.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140421_0824_HARP4025_NOAA12042.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/80bfa8f976a75ac2d4e13dd2bb2e6a12.npz

.

Average throughput: 199.7MiB/s

[val] downloading 38/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141214_1500_HARP4908_NOAA12232.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141214_1500_HARP4908_NOAA12232.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/77630bf13209cff22a83aa1303f80f21.npz

.

Average throughput: 109.3MiB/s

[val] downloading 39/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141127_0900_HARP4879_NOAA12223.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141127_0900_HARP4879_NOAA12223.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9e25d61c78929f5322a9fa5011065505.npz

.

Average throughput: 76.2MiB/s

[val] downloading 40/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141217_1036_HARP4932_NOAA12236.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141217_1036_HARP4932_NOAA12236.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b2e9dab207e427047a44c20aabaddb34.npz

.

Average throughput: 122.6MiB/s

[val] downloading 41/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140329_1548_HARP3901_NOAA12020.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140329_1548_HARP3901_NOAA12020.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2662cd224e454618bf15ecfd2c77c545.npz

.

Average throughput: 83.3MiB/s

[val] downloading 42/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140503_0800_HARP4075_NOAA12050.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140503_0800_HARP4075_NOAA12050.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/65b23cce5a2c2b2058bdd2cab3e0df1d.npz



Average throughput: 170.5MiB/s

[val] downloading 43/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140508_0412_HARP4093_NOAA12054.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140508_0412_HARP4093_NOAA12054.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5fb6dcc472d8ffabbee054daad8797d3.npz

.

Average throughput: 124.3MiB/s

[val] downloading 44/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140710_2324_HARP4328_NOAA12111.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140710_2324_HARP4328_NOAA12111.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/071d70836bdd77484690860ecf215b54.npz

.

Average throughput: 97.6MiB/s

[val] downloading 45/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141116_0912_HARP4800_NOAA12207.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141116_0912_HARP4800_NOAA12207.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f71e60784cd6e327173a567952486160.npz

.

Average throughput: 177.4MiB/s

[val] downloading 46/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140224_1612_HARP3766_NOAA11981.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140224_1612_HARP3766_NOAA11981.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7ee7ecd0e78d944533b0b9f440b1b6df.npz

.

Average throughput: 195.1MiB/s

[val] downloading 47/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140305_1848_HARP3821_NOAA11999.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140305_1848_HARP3821_NOAA11999.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5721aaecb50bc891bff7e659c2be1b70.npz

.

Average throughput: 104.9MiB/s

[val] downloading 48/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140401_1000_HARP3907_NOAA12024.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140401_1000_HARP3907_NOAA12024.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/67cb12aea267e4c589e9b5de6d445dff.npz

.

Average throughput: 149.4MiB/s

[val] downloading 49/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140604_1800_HARP4201_NOAA12084.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140604_1800_HARP4201_NOAA12084.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f6ff9917de09bea3c6ad4e5b39494e0a.npz

.

Average throughput: 98.2MiB/s

[val] downloading 50/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141225_2336_HARP4963_NOAA12244.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141225_2336_HARP4963_NOAA12244.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/028671fb72f298c3dde268991eed9fd9.npz

.

Average throughput: 123.8MiB/s

[val] downloading 51/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141005_0624_HARP4616_NOAA12178.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141005_0624_HARP4616_NOAA12178.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0cbd6f6a1dfd8d1105a1f790121325c6.npz

.

Average throughput: 184.5MiB/s

[val] downloading 52/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141114_1324_HARP4814_NOAA12212.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141114_1324_HARP4814_NOAA12212.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f86566166c5e84d828a5c8c0fdd0a3d1.npz

.

Average throughput: 155.0MiB/s

[val] downloading 53/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140110_0924_HARP3612_NOAA11951.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140110_0924_HARP3612_NOAA11951.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/45a93c8af5f83f5b33987b53014e3c3a.npz

.

Average throughput: 43.6MiB/s

[val] downloading 54/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140704_1936_HARP4295_NOAA12103.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140704_1936_HARP4295_NOAA12103.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6f5963d606dd20e2cfc5390431b7003d.npz

.

Average throughput: 104.4MiB/s

[val] downloading 55/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140202_1000_HARP3686_NOAA11967.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140202_1000_HARP3686_NOAA11967.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cfb5e59dccccade38a1bca36b03ade78.npz

.

Average throughput: 175.6MiB/s

[val] downloading 56/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140326_0824_HARP3879_NOAA12014.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140326_0824_HARP3879_NOAA12014.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a6125b217d2a1ab4f86345a45cbed659.npz

.

Average throughput: 61.6MiB/s

[val] downloading 57/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140103_0600_HARP3569_NOAA11945.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140103_0600_HARP3569_NOAA11945.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/aec627c6bf6c1a82abe5b5b62b3be2e7.npz

.

Average throughput: 110.5MiB/s

[val] downloading 58/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140201_0848_HARP3700_NOAA11969.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140201_0848_HARP3700_NOAA11969.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ee61f267035f2098004a5496e93d2d4c.npz

.

Average throughput: 84.1MiB/s

[val] downloading 59/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141228_2148_HARP4973_NOAA12246.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141228_2148_HARP4973_NOAA12246.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ce34bbb8c1e7dce0c558d9442ccbd41b.npz



Average throughput: 166.2MiB/s

[val] downloading 60/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141030_0200_HARP4726_NOAA12195.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141030_0200_HARP4726_NOAA12195.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a21c4c3a4b3491d0d3ba1913f64d2d10.npz

.

Average throughput: 57.1MiB/s

[val] downloading 61/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141028_0836_HARP4734_NOAA12197.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141028_0836_HARP4734_NOAA12197.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/dad005c4ded231641e1773c914eabaa3.npz

.

Average throughput: 131.9MiB/s

[val] downloading 62/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141202_2124_HARP4874_NOAA12222.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141202_2124_HARP4874_NOAA12222.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c335da34537fd482a111f1d1361c4f59.npz

.

Average throughput: 172.9MiB/s

[val] downloading 63/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140413_0012_HARP3985_NOAA12032.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140413_0012_HARP3985_NOAA12032.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/aaf0a91a56e7d0862cf0e3ddc042b795.npz

.

Average throughput: 157.4MiB/s

[val] downloading 64/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140706_2012_HARP4321_NOAA12109.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140706_2012_HARP4321_NOAA12109.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/49a31e137552f51e0215fcddc116caa9.npz

.

Average throughput: 159.9MiB/s

[val] downloading 65/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141218_1124_HARP4941_NOAA12241.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141218_1124_HARP4941_NOAA12241.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6ffdeca3fc5a2ee61298fc7c35b2c372.npz

.

Average throughput: 185.7MiB/s

[val] downloading 66/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140111_0936_HARP3604_NOAA11950.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140111_0936_HARP3604_NOAA11950.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fc7c4470394ad329002551b5719362d4.npz

.

Average throughput: 153.2MiB/s

[val] downloading 67/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141124_2136_HARP4851_NOAA12216.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141124_2136_HARP4851_NOAA12216.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f996b5f85fd4ccf7d066a1244592bc67.npz

.

Average throughput: 128.9MiB/s

[val] downloading 68/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141019_0712_HARP4711_NOAA12193.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141019_0712_HARP4711_NOAA12193.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7eea56dc9e747d2563531f7d83316922.npz



Average throughput: 170.7MiB/s

[val] downloading 69/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140806_1148_HARP4422_NOAA12133.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140806_1148_HARP4422_NOAA12133.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/20e4b7058994cc5e2ed1f5cfbfeb2fb9.npz

.

Average throughput: 69.4MiB/s

[val] downloading 70/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140101_0348_HARP3557_NOAA11938.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140101_0348_HARP3557_NOAA11938.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/90f5f24bb93a8c22dfaa4af24c9427a7.npz

.

Average throughput: 89.9MiB/s

[val] downloading 71/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140114_2000_HARP3601_NOAA11949.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140114_2000_HARP3601_NOAA11949.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e032fad20c2c56cf0dac8314c3bea887.npz

.

Average throughput: 169.1MiB/s

[val] downloading 72/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141009_1624_HARP4640_NOAA12183.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141009_1624_HARP4640_NOAA12183.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fafbb75f53d123c954bf8986106f78cd.npz

.

Average throughput: 60.0MiB/s

[val] downloading 73/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140930_0912_HARP4610_NOAA12177.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140930_0912_HARP4610_NOAA12177.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/805c1dbb777c597561a3c7b0c94a80ae.npz

.

Average throughput: 72.8MiB/s

[val] downloading 74/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140605_0100_HARP4189_NOAA12078.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140605_0100_HARP4189_NOAA12078.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/aa6ef9af0451675b32cbf711bafa0219.npz

.

Average throughput: 72.6MiB/s

[val] downloading 75/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141115_0348_HARP4814_NOAA12212.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141115_0348_HARP4814_NOAA12212.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/863bb1b0f1abdfe49a5379b9183a8278.npz

.

Average throughput: 105.7MiB/s

[val] downloading 76/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140511_1200_HARP4097_NOAA12055.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140511_1200_HARP4097_NOAA12055.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9e3c806c5a7c8b72b6835a2ea703166b.npz

.

Average throughput: 136.1MiB/s

[val] downloading 77/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140224_2300_HARP3785_NOAA11988.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140224_2300_HARP3785_NOAA11988.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f9df0a1d70f59e3ecf768ee514be029f.npz

.

Average throughput: 146.4MiB/s

[val] downloading 78/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141212_0700_HARP4908_NOAA12232.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141212_0700_HARP4908_NOAA12232.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8b547f04bc42a50131c463c75c4aebd6.npz

.

Average throughput: 119.5MiB/s

[val] downloading 79/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140310_2224_HARP3824_NOAA11998.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140310_2224_HARP3824_NOAA11998.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ceba386923b4b24ee4d062dd1f0759d3.npz

.

Average throughput: 150.3MiB/s

[val] downloading 80/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140319_0548_HARP3877_NOAA12011.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140319_0548_HARP3877_NOAA12011.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7dcde4db190810ff6b60172993eaacc8.npz

.

Average throughput: 85.3MiB/s

[val] downloading 81/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140514_1848_HARP4111_NOAA12058.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140514_1848_HARP4111_NOAA12058.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f0c032026c810ce62239a1376da54e07.npz

.

Average throughput: 195.9MiB/s

[val] downloading 82/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141221_2200_HARP4954_NOAA12243.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141221_2200_HARP4954_NOAA12243.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d07546bbf5aecc03cb4e36b02e8ced1f.npz

.

Average throughput: 165.6MiB/s

[val] downloading 83/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141019_0024_HARP4690_NOAA12190.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141019_0024_HARP4690_NOAA12190.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1131efecd2d3f4b1e3d717da372dfbf5.npz

.

Average throughput: 137.0MiB/s

[val] downloading 84/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140626_1124_HARP4284_NOAA12098.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140626_1124_HARP4284_NOAA12098.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/38df56badab3cc4288f27d493c863d0a.npz

.

Average throughput: 47.9MiB/s

[val] downloading 85/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140508_1212_HARP4092_NOAA12053.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140508_1212_HARP4092_NOAA12053.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f560e5b01dba14c5d6dbbd5ac0de9e96.npz

.

Average throughput: 108.4MiB/s

[val] downloading 86/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141225_0112_HARP4963_NOAA12244.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141225_0112_HARP4963_NOAA12244.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/baeb52601c91495ab69d336837d21667.npz

.

Average throughput: 111.5MiB/s

[val] downloading 87/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141001_0600_HARP4610_NOAA12177.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141001_0600_HARP4610_NOAA12177.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/892a4c59ce3d68879c438847e8ab3049.npz

.

Average throughput: 94.1MiB/s

[val] downloading 88/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140226_1548_HARP3785_NOAA11988.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140226_1548_HARP3785_NOAA11988.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/283ee83bc72c58733d2084dfe50fc8d3.npz

.

Average throughput: 90.3MiB/s

[val] downloading 89/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141013_1412_HARP4667_NOAA12186.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141013_1412_HARP4667_NOAA12186.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9f45183c06f5a5298b62324c25f5ef50.npz

.

Average throughput: 66.4MiB/s

[val] downloading 90/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140215_2012_HARP3740_NOAA11977.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140215_2012_HARP3740_NOAA11977.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f121eaf0bfca05111935d807811705e5.npz

.

Average throughput: 173.0MiB/s

[val] downloading 91/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140408_1236_HARP3941_NOAA12027.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140408_1236_HARP3941_NOAA12027.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fdcd4ea729dfa6c21763e68ad4ae7af5.npz

.

Average throughput: 167.9MiB/s

[val] downloading 92/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140611_1536_HARP4231_NOAA12089.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140611_1536_HARP4231_NOAA12089.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4162d6afe230627dffb73258d39041b1.npz

.

Average throughput: 70.8MiB/s

[val] downloading 93/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140113_1800_HARP3608_NOAA11953.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140113_1800_HARP3608_NOAA11953.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/673472dfde370a53ea49ecc7d3021f53.npz

.

Average throughput: 90.7MiB/s

[val] downloading 94/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141103_0300_HARP4750_NOAA12199.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141103_0300_HARP4750_NOAA12199.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/99c85070d0c47febdcb4bf3658978ea2.npz

.

Average throughput: 108.1MiB/s

[val] downloading 95/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141105_0912_HARP4767_NOAA12204.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141105_0912_HARP4767_NOAA12204.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a6b8e5e00e2e8c67b843e07b27fd7bb3.npz

.

Average throughput: 54.9MiB/s

[val] downloading 96/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141116_0248_HARP4800_NOAA12207.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141116_0248_HARP4800_NOAA12207.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/67e233ee571b24eb3b7c4277ecbaf653.npz

.

Average throughput: 84.4MiB/s

[val] downloading 97/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140329_1512_HARP3894_NOAA12017.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140329_1512_HARP3894_NOAA12017.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/80328124dc2c8c7965b2ebac72104371.npz



Average throughput: 180.0MiB/s

[val] downloading 98/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140505_1248_HARP4075_NOAA12050.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140505_1248_HARP4075_NOAA12050.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/df03df52356d28755a30a6fc85b8f857.npz

.

Average throughput: 162.8MiB/s

[val] downloading 99/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140311_0312_HARP3824_NOAA11998.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140311_0312_HARP3824_NOAA11998.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ede5ad4cbd352625199ab105405151a9.npz

.

Average throughput: 105.7MiB/s

[val] downloading 100/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141223_0424_HARP4954_NOAA12243.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141223_0424_HARP4954_NOAA12243.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e60d39614e38e8cc0a348d7c41b9ef91.npz

.

Average throughput: 95.3MiB/s

[val] cached/checked 100/825 files | elapsed 2.6 min
[val] downloading 101/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140729_0400_HARP4383_NOAA12123.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140729_0400_HARP4383_NOAA12123.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3c50e9a925ceba518f0f4cfe09f7379e.npz

.

Average throughput: 149.6MiB/s

[val] downloading 102/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141229_0236_HARP4973_NOAA12246.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141229_0236_HARP4973_NOAA12246.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/937378d9c83e5a03178e6dcd8fb34289.npz

.

Average throughput: 202.5MiB/s

[val] downloading 103/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140701_1400_HARP4288_NOAA12100.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140701_1400_HARP4288_NOAA12100.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4060cfa9fbcc650d2832dda2b907aeef.npz

.

Average throughput: 145.0MiB/s

[val] downloading 104/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140512_0600_HARP4111_NOAA12058.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140512_0600_HARP4111_NOAA12058.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1530a2b353e605d0a57143c4498c2caf.npz

.

Average throughput: 140.0MiB/s

[val] downloading 105/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140116_0524_HARP3620_NOAA11952.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140116_0524_HARP3620_NOAA11952.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0813787e458548d29cc7cb334498b35e.npz

.

Average throughput: 97.0MiB/s

[val] downloading 106/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140111_2248_HARP3586_NOAA11948.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140111_2248_HARP3586_NOAA11948.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0640a4e059da47e763190e4f779b80ae.npz

.

Average throughput: 134.8MiB/s

[val] downloading 107/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140418_0900_HARP4000_NOAA12035.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140418_0900_HARP4000_NOAA12035.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e037a34becc55a6c97eb81106456638b.npz

.

Average throughput: 93.8MiB/s

[val] downloading 108/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141128_1212_HARP4879_NOAA12223.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141128_1212_HARP4879_NOAA12223.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4caf740a293abd355f65f759fbf88bde.npz

.

Average throughput: 94.3MiB/s

[val] downloading 109/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140217_0912_HARP3730_NOAA11976.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140217_0912_HARP3730_NOAA11976.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/08595537d5f10c84a596f8da424e2ee5.npz

.

Average throughput: 145.9MiB/s

[val] downloading 110/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141022_0448_HARP4698_NOAA12192.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141022_0448_HARP4698_NOAA12192.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/35647ecaacd0c4375795ba652f98bc34.npz

.

Average throughput: 104.0MiB/s

[val] downloading 111/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141030_0724_HARP4734_NOAA12197.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141030_0724_HARP4734_NOAA12197.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4b74c570843bb3d3ff0b8624c2359b32.npz

.

Average throughput: 102.3MiB/s

[val] downloading 112/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140427_0536_HARP4042_NOAA12045.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140427_0536_HARP4042_NOAA12045.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/58e18f9fd08d516778f3d18424bd3929.npz

.

Average throughput: 89.5MiB/s

[val] downloading 113/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141217_2236_HARP4932_NOAA12236.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141217_2236_HARP4932_NOAA12236.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d3bcd4d48bb76bb007e8e57d6b258c66.npz

.

Average throughput: 172.3MiB/s

[val] downloading 114/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141004_0312_HARP4610_NOAA12177.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141004_0312_HARP4610_NOAA12177.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/52243ec76cfa27ab6263a285c9c2b11d.npz

..

Average throughput: 51.6MiB/s

[val] downloading 115/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140404_2248_HARP3926_NOAA12022.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140404_2248_HARP3926_NOAA12022.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/bb39c3e53f95835262b28ce0dc0a15c8.npz

.

Average throughput: 162.3MiB/s

[val] downloading 116/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141130_0912_HARP4864_NOAA12218.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141130_0912_HARP4864_NOAA12218.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1319f9b49986979fd39db25a761604fe.npz

..

Average throughput: 30.0MiB/s

[val] downloading 117/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140805_0200_HARP4398_NOAA12128.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140805_0200_HARP4398_NOAA12128.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ad8408ac5e76b58ca537277c12656863.npz

.

Average throughput: 168.2MiB/s

[val] downloading 118/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140517_0500_HARP4133_NOAA12063.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140517_0500_HARP4133_NOAA12063.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7f0cfe3ce6469e53042d85cac9f89db0.npz

.

Average throughput: 180.8MiB/s

[val] downloading 119/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140102_0548_HARP3557_NOAA11938.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140102_0548_HARP3557_NOAA11938.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f88ced8b779a54f0801b4f643c54bb7c.npz

.

Average throughput: 162.9MiB/s

[val] downloading 120/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141006_1800_HARP4639_NOAA12182.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141006_1800_HARP4639_NOAA12182.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2400f332ad41d3a2a1a0dada972f2d32.npz

.

Average throughput: 71.5MiB/s

[val] downloading 121/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141115_0400_HARP4810_NOAA12210.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141115_0400_HARP4810_NOAA12210.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/78d8eb890003c2dd6a37ad8fabe188e0.npz

.

Average throughput: 138.0MiB/s

[val] downloading 122/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140109_0000_HARP3580_NOAA11946.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140109_0000_HARP3580_NOAA11946.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5416e3221690c532c9fde0f202e1b85e.npz

.

Average throughput: 130.7MiB/s

[val] downloading 123/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140605_1836_HARP4201_NOAA12084.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140605_1836_HARP4201_NOAA12084.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/689b1148e17339b8e4a46ea228d8be3b.npz

.

Average throughput: 84.3MiB/s

[val] downloading 124/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140119_0424_HARP3635_NOAA11961.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140119_0424_HARP3635_NOAA11961.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0d61c48ba544c0e05b24a9aa2b2064d8.npz

.

Average throughput: 153.6MiB/s

[val] downloading 125/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141129_1712_HARP4864_NOAA12218.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141129_1712_HARP4864_NOAA12218.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/833bba37e3c1311682c040fd9b447649.npz

.

Average throughput: 102.9MiB/s

[val] downloading 126/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141002_1624_HARP4623_NOAA12181.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141002_1624_HARP4623_NOAA12181.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cde32b9460713c6b8d4904105505d485.npz

.

Average throughput: 113.9MiB/s

[val] downloading 127/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140214_0524_HARP3721_NOAA11974.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140214_0524_HARP3721_NOAA11974.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e36fc3626f471461bccc412c78df23e2.npz

.

Average throughput: 179.9MiB/s

[val] downloading 128/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140601_2036_HARP4179_NOAA12083.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140601_2036_HARP4179_NOAA12083.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b22367f50e8c09ebf0450be3ce4741d0.npz

.

Average throughput: 48.7MiB/s

[val] downloading 129/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140416_1848_HARP3999_NOAA12036.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140416_1848_HARP3999_NOAA12036.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d3fd250fddd7fd371a59c596aa0b9447.npz

.

Average throughput: 162.7MiB/s

[val] downloading 130/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140503_2012_HARP4073_NOAA12049.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140503_2012_HARP4073_NOAA12049.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c424765deb433386392f9193f65a4677.npz

.

Average throughput: 105.9MiB/s

[val] downloading 131/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140309_1112_HARP3826_NOAA12000.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140309_1112_HARP3826_NOAA12000.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f8ec5f3b0c403d9f4c2e17593807d376.npz

.

Average throughput: 173.2MiB/s

[val] downloading 132/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141216_2148_HARP4920_NOAA12235.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141216_2148_HARP4920_NOAA12235.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/82c616e6fe86a6475f52d622e72576f6.npz

.

Average throughput: 100.5MiB/s

[val] downloading 133/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140727_0424_HARP4379_NOAA12121.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140727_0424_HARP4379_NOAA12121.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1285dbd100d883a4763e2c45cc5334a8.npz

.

Average throughput: 69.4MiB/s

[val] downloading 134/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140417_0624_HARP3996_NOAA12034.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140417_0624_HARP3996_NOAA12034.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/86ca6c9ff3f9b554b0bcfcae82f378fd.npz

.

Average throughput: 131.4MiB/s

[val] downloading 135/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141224_0800_HARP4955_NOAA12249.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141224_0800_HARP4955_NOAA12249.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/61d7c0421709f6e7cf6c013163c65fdf.npz

.

Average throughput: 144.4MiB/s

[val] downloading 136/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141101_1012_HARP4733_NOAA12196.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141101_1012_HARP4733_NOAA12196.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/367bdf83066b052a57ed46b36f9bebd9.npz

.

Average throughput: 56.7MiB/s

[val] downloading 137/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141024_1900_HARP4718_NOAA12194.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141024_1900_HARP4718_NOAA12194.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/340d7a16f4ee3b748a019a8b5de8df59.npz

.

Average throughput: 148.3MiB/s

[val] downloading 138/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140327_0600_HARP3894_NOAA12017.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140327_0600_HARP3894_NOAA12017.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8a1f91b486bb1aa7296a079c12c1f2da.npz

.

Average throughput: 95.2MiB/s

[val] downloading 139/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140223_1900_HARP3779_NOAA11986.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140223_1900_HARP3779_NOAA11986.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a2c4df5a575f1ca9d912ddc10ac36f0d.npz

.

Average throughput: 156.3MiB/s

[val] downloading 140/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141209_0336_HARP4915_NOAA12233.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141209_0336_HARP4915_NOAA12233.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/26db0b35b39ce12089997e773c15b7e7.npz

.

Average throughput: 132.3MiB/s

[val] downloading 141/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140204_2212_HARP3688_NOAA11968.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140204_2212_HARP3688_NOAA11968.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2861174538cc7a48b8a19114b9b1609d.npz

.

Average throughput: 185.4MiB/s

[val] downloading 142/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140203_0300_HARP3688_NOAA11968.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140203_0300_HARP3688_NOAA11968.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d4c5069693f914db67e9a37e88aaa01b.npz

.

Average throughput: 127.0MiB/s

[val] downloading 143/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141117_2124_HARP4814_NOAA12212.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141117_2124_HARP4814_NOAA12212.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/be8d29185f3b0f54d0b52f929f1c84af.npz

.

Average throughput: 80.6MiB/s

[val] downloading 144/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140414_1224_HARP3996_NOAA12034.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140414_1224_HARP3996_NOAA12034.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/36d0247a06d7461b8fc0d8e7a0b28337.npz

.

Average throughput: 84.9MiB/s

[val] downloading 145/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141009_0924_HARP4639_NOAA12182.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141009_0924_HARP4639_NOAA12182.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0e4e10e2aacb57b120d31cf1939352ae.npz

.

Average throughput: 59.3MiB/s

[val] downloading 146/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140531_1412_HARP4179_NOAA12083.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140531_1412_HARP4179_NOAA12083.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/872df8a5a1956e96653326a7bbfc3d38.npz

.

Average throughput: 38.0MiB/s

[val] downloading 147/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140418_0136_HARP3996_NOAA12034.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140418_0136_HARP3996_NOAA12034.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9a312f956b8b0ca5284e3139d875fbe4.npz

.

Average throughput: 40.3MiB/s

[val] downloading 148/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141225_1512_HARP4995_NOAA12250.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141225_1512_HARP4995_NOAA12250.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ff1cfcc447effc92882796f96bf4ccb2.npz

.

Average throughput: 93.5MiB/s

[val] downloading 149/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141201_2000_HARP4862_NOAA12217.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141201_2000_HARP4862_NOAA12217.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9a4b640ebd90e3449b04370c52d1f5da.npz

.

Average throughput: 109.9MiB/s

[val] downloading 150/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140604_1136_HARP4201_NOAA12084.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140604_1136_HARP4201_NOAA12084.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/368c64d4020e1a260f81370536e98d84.npz

.

Average throughput: 76.8MiB/s

[val] downloading 151/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140516_0948_HARP4133_NOAA12063.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140516_0948_HARP4133_NOAA12063.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b9f777f764b890c97260858059002bc0.npz

.

Average throughput: 63.3MiB/s

[val] downloading 152/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140508_1348_HARP4092_NOAA12053.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140508_1348_HARP4092_NOAA12053.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/909b16dd90b3ab9dea07fe961a4926c9.npz

.

Average throughput: 144.7MiB/s

[val] downloading 153/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140504_1700_HARP4073_NOAA12049.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140504_1700_HARP4073_NOAA12049.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b1b09cb9b89929bba1cbe21b6f15d848.npz

..

Average throughput: 56.9MiB/s

[val] downloading 154/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140417_0800_HARP3999_NOAA12036.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140417_0800_HARP3999_NOAA12036.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/78d861be190532aad9741907caa39d4c.npz

.

Average throughput: 94.4MiB/s

[val] downloading 155/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140606_1748_HARP4205_NOAA12082.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140606_1748_HARP4205_NOAA12082.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/15ce24f2d2b6478e0cb6e7be8543d45e.npz



Average throughput: 170.7MiB/s

[val] downloading 156/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140404_0548_HARP3957_NOAA12029.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140404_0548_HARP3957_NOAA12029.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1527bd7db846889e33d4468b1c0c4d21.npz



Average throughput: 184.5MiB/s

[val] downloading 157/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141219_0124_HARP4943_NOAA12240.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141219_0124_HARP4943_NOAA12240.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d01f6c83f590bb31b3e33caa81820871.npz

.

Average throughput: 174.7MiB/s

[val] downloading 158/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140111_0800_HARP3604_NOAA11950.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140111_0800_HARP3604_NOAA11950.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5cf526ce4ee267548b14c9876a8f670c.npz

.

Average throughput: 85.0MiB/s

[val] downloading 159/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141201_2336_HARP4864_NOAA12218.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141201_2336_HARP4864_NOAA12218.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6e4884c15b9b2d27529318de5b844e21.npz



Average throughput: 168.7MiB/s

[val] downloading 160/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140215_1212_HARP3740_NOAA11977.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140215_1212_HARP3740_NOAA11977.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/625b88b9e5be9f9793cb128cec876bf6.npz

.

Average throughput: 186.7MiB/s

[val] downloading 161/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140114_0024_HARP3601_NOAA11949.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140114_0024_HARP3601_NOAA11949.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/62d3c13563c84f88c1ca692e2297f581.npz

.

Average throughput: 128.7MiB/s

[val] downloading 162/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140319_1200_HARP3848_NOAA12005.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140319_1200_HARP3848_NOAA12005.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/34d232284837524604bba78cb3a02d46.npz

.

Average throughput: 79.2MiB/s

[val] downloading 163/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141204_0048_HARP4872_NOAA12221.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141204_0048_HARP4872_NOAA12221.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2ca60ca1ad759f09b07dfdc59cd20ec7.npz

.

Average throughput: 144.8MiB/s

[val] downloading 164/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140602_0012_HARP4189_NOAA12078.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140602_0012_HARP4189_NOAA12078.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5f1e78624be760edddd9500eb6aa47a8.npz

.

Average throughput: 147.6MiB/s

[val] downloading 165/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140406_1900_HARP3941_NOAA12027.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140406_1900_HARP3941_NOAA12027.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/52723315af231ef36f274b4927f24dfa.npz

.

Average throughput: 63.6MiB/s

[val] downloading 166/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140529_1024_HARP4166_NOAA12075.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140529_1024_HARP4166_NOAA12075.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cb3b33afbffc597c7899f206a9013480.npz

.

Average throughput: 119.7MiB/s

[val] downloading 167/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140529_0312_HARP4156_NOAA12071.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140529_0312_HARP4156_NOAA12071.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f6ad502686a9cd1e902d2f23326e3deb.npz

.

Average throughput: 110.2MiB/s

[val] downloading 168/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140612_1224_HARP4224_NOAA12091.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140612_1224_HARP4224_NOAA12091.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/91f1cab71087398832bbd7c5d278bd59.npz

.

Average throughput: 126.6MiB/s

[val] downloading 169/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141221_2000_HARP4941_NOAA12241.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141221_2000_HARP4941_NOAA12241.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/26a753166cb3e9ca850e47368ba94198.npz

.

Average throughput: 126.4MiB/s

[val] downloading 170/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140223_0812_HARP3766_NOAA11981.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140223_0812_HARP3766_NOAA11981.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/eee568c053055d0bdb01f100e7cec252.npz

.

Average throughput: 89.7MiB/s

[val] downloading 171/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140402_1136_HARP3907_NOAA12024.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140402_1136_HARP3907_NOAA12024.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9170bcd2c54c8fd17ec5f01722649f71.npz

.

Average throughput: 134.7MiB/s

[val] downloading 172/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140712_2100_HARP4351_NOAA12114.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140712_2100_HARP4351_NOAA12114.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/87f8372d2c399dfa93595634c7b27fc4.npz

.

Average throughput: 93.3MiB/s

[val] downloading 173/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140727_1636_HARP4381_NOAA12122.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140727_1636_HARP4381_NOAA12122.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/970471cdfaf308404010f70860dae526.npz

.

Average throughput: 79.6MiB/s

[val] downloading 174/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140123_0300_HARP3647_NOAA11958.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140123_0300_HARP3647_NOAA11958.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cabc35e0fc36af9af7316c94e14644a3.npz

.

Average throughput: 39.0MiB/s

[val] downloading 175/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141021_0048_HARP4711_NOAA12193.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141021_0048_HARP4711_NOAA12193.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b76b287ebba1816bab41151f3285e517.npz

.

Average throughput: 83.7MiB/s

[val] downloading 176/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140114_0824_HARP3610_NOAA11954.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140114_0824_HARP3610_NOAA11954.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/43eafea3025c843e5da4d5ce84b0b69c.npz

.

Average throughput: 119.6MiB/s

[val] downloading 177/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140715_1436_HARP4351_NOAA12114.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140715_1436_HARP4351_NOAA12114.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5bfbf787f1b5122670c89cc582ec27b8.npz

.

Average throughput: 84.8MiB/s

[val] downloading 178/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140307_0036_HARP3813_NOAA11996.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140307_0036_HARP3813_NOAA11996.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c9d3e0a5b42a11f164d25252cca792a0.npz

.

Average throughput: 127.5MiB/s

[val] downloading 179/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140122_0812_HARP3631_NOAA11955.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140122_0812_HARP3631_NOAA11955.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f84e67dcf0a838e7b607ea5d2a4a6fec.npz

.

Average throughput: 106.9MiB/s

[val] downloading 180/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140513_1200_HARP4097_NOAA12055.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140513_1200_HARP4097_NOAA12055.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9b26deb53a4d95486daa3db52262f041.npz

.

Average throughput: 150.0MiB/s

[val] downloading 181/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140629_2148_HARP4288_NOAA12100.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140629_2148_HARP4288_NOAA12100.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/74dd2b6fc2701679716eba7da01cf823.npz

.

Average throughput: 85.4MiB/s

[val] downloading 182/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140126_0936_HARP3647_NOAA11958.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140126_0936_HARP3647_NOAA11958.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/81946216950bc33292779364128dbd78.npz

.

Average throughput: 100.4MiB/s

[val] downloading 183/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141021_1912_HARP4698_NOAA12192.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141021_1912_HARP4698_NOAA12192.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/64733a27d82aa18f68c75c61aa18030a.npz



Average throughput: 152.8MiB/s

[val] downloading 184/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140705_1612_HARP4294_NOAA12102.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140705_1612_HARP4294_NOAA12102.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/64be3ba83328c268ca7eb264430eab88.npz

.

Average throughput: 123.0MiB/s

[val] downloading 185/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140306_1948_HARP3813_NOAA11996.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140306_1948_HARP3813_NOAA11996.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cf4a3ba7f280c899696e8053bc37c6bd.npz

.

Average throughput: 132.8MiB/s

[val] downloading 186/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141224_0000_HARP4955_NOAA12249.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141224_0000_HARP4955_NOAA12249.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e3f33b1c970d71c89bfb18f449810c4a.npz

.

Average throughput: 80.1MiB/s

[val] downloading 187/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140509_1824_HARP4097_NOAA12055.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140509_1824_HARP4097_NOAA12055.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/07b6e1bff7eeafe8dacfc366c10132b6.npz

.

Average throughput: 90.6MiB/s

[val] downloading 188/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141216_0548_HARP4938_NOAA12238.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141216_0548_HARP4938_NOAA12238.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3a017a658765d6bf23294a324362421c.npz

.

Average throughput: 60.3MiB/s

[val] downloading 189/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140217_0248_HARP3730_NOAA11976.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140217_0248_HARP3730_NOAA11976.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/901952c30d2d1389d894d72669b8cc54.npz

.

Average throughput: 104.2MiB/s

[val] downloading 190/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141231_1100_HARP4978_NOAA12247.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141231_1100_HARP4978_NOAA12247.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6d65eeb3750cbec92f9a1f13e9c7cdb8.npz

.

Average throughput: 104.5MiB/s

[val] downloading 191/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140122_0400_HARP3658_NOAA11962.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140122_0400_HARP3658_NOAA11962.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7577f9361c03d6a4b312add76c45beae.npz

.

Average throughput: 115.7MiB/s

[val] downloading 192/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141102_0100_HARP4761_NOAA12202.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141102_0100_HARP4761_NOAA12202.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e7a066d03cdd8230bcdb96b06a5456e4.npz

.

Average throughput: 66.1MiB/s

[val] downloading 193/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140114_0512_HARP3601_NOAA11949.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140114_0512_HARP3601_NOAA11949.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e506bf5cafc45a7f4cb9d2e2a1348667.npz

.

Average throughput: 180.1MiB/s

[val] downloading 194/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141027_0924_HARP4718_NOAA12194.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141027_0924_HARP4718_NOAA12194.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/af81ad1f525f8c21fe6782068e68fa14.npz

.

Average throughput: 71.4MiB/s

[val] downloading 195/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141028_1012_HARP4734_NOAA12197.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141028_1012_HARP4734_NOAA12197.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6d7a8f779aa647ea62d4675ae1eac63d.npz

.

Average throughput: 101.1MiB/s

[val] downloading 196/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141027_0748_HARP4718_NOAA12194.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141027_0748_HARP4718_NOAA12194.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/476a9b01604dc5deee3e9948c24f3208.npz

.

Average throughput: 117.8MiB/s

[val] downloading 197/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140706_1936_HARP4315_NOAA12108.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140706_1936_HARP4315_NOAA12108.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6392daf4ab7923619d8ce4ae4c410599.npz

.

Average throughput: 159.3MiB/s

[val] downloading 198/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140516_0636_HARP4131_NOAA12066.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140516_0636_HARP4131_NOAA12066.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/261b014e02df2bc7172d94c9a33d9c6a.npz

.

Average throughput: 149.1MiB/s

[val] downloading 199/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140328_0348_HARP3894_NOAA12017.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140328_0348_HARP3894_NOAA12017.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f4f5ffcb246e93e1dd13caec33ff0a3d.npz



Average throughput: 151.5MiB/s

[val] downloading 200/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140605_1348_HARP4201_NOAA12084.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140605_1348_HARP4201_NOAA12084.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1342cca4611ed07608b345c864dd6add.npz

.

Average throughput: 98.8MiB/s

[val] cached/checked 200/825 files | elapsed 5.1 min
[val] downloading 201/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141209_1524_HARP4901_NOAA12229.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141209_1524_HARP4901_NOAA12229.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/93b9326c19afe3f54747d173e52d7f71.npz

.

Average throughput: 70.7MiB/s

[val] downloading 202/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140615_1112_HARP4225_NOAA12087.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140615_1112_HARP4225_NOAA12087.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7064af53da2649cf4c4caaa86929c88a.npz

.

Average throughput: 170.3MiB/s

[val] downloading 203/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140111_0924_HARP3612_NOAA11951.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140111_0924_HARP3612_NOAA11951.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/045e9e3ee0d7af046a3fd3025a407214.npz

.

Average throughput: 134.4MiB/s

[val] downloading 204/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141016_2224_HARP4679_NOAA12189.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141016_2224_HARP4679_NOAA12189.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d174dac0e75acf8ea1e0991c7f3a077a.npz

.

Average throughput: 124.0MiB/s

[val] downloading 205/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140224_1412_HARP3779_NOAA11986.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140224_1412_HARP3779_NOAA11986.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/30346ac4f0ab4ed42f8652df9613a592.npz

.

Average throughput: 82.2MiB/s

[val] downloading 206/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140701_1524_HARP4295_NOAA12103.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140701_1524_HARP4295_NOAA12103.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c88c8542a11f630de6b6961fe5bd8a7e.npz

.

Average throughput: 100.3MiB/s

[val] downloading 207/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141015_0748_HARP4667_NOAA12186.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141015_0748_HARP4667_NOAA12186.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2c3dedc012a6fb3245796468e5d7f5c7.npz

.

Average throughput: 133.3MiB/s

[val] downloading 208/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141231_1348_HARP5020_NOAA12254.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141231_1348_HARP5020_NOAA12254.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f6e8121505cf4f646f56c7145e78019a.npz

.

Average throughput: 147.7MiB/s

[val] downloading 209/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141106_1048_HARP4767_NOAA12204.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141106_1048_HARP4767_NOAA12204.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ffd99f7fa7d108b74328dd7aaee32940.npz

.

Average throughput: 115.4MiB/s

[val] downloading 210/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141104_0000_HARP4760_NOAA12201.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141104_0000_HARP4760_NOAA12201.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/bb66075d46756d7b415fd6c720882c53.npz

.

Average throughput: 118.7MiB/s

[val] downloading 211/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140101_1048_HARP3542_NOAA11937.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140101_1048_HARP3542_NOAA11937.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3226c18cc05a29e728a6b197267a8b7f.npz

.

Average throughput: 110.3MiB/s

[val] downloading 212/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140112_0512_HARP3586_NOAA11948.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140112_0512_HARP3586_NOAA11948.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6c5b3cef57385ec0a49548a47dd18bf3.npz

.

Average throughput: 177.3MiB/s

[val] downloading 213/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141219_0348_HARP4932_NOAA12236.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141219_0348_HARP4932_NOAA12236.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5c3a14e5d7e932cabc99ba5360120c92.npz

.

Average throughput: 123.5MiB/s

[val] downloading 214/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141006_1036_HARP4640_NOAA12183.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141006_1036_HARP4640_NOAA12183.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4e5f2e997ce1f70af57c89a2cab43d6a.npz

.

Average throughput: 108.8MiB/s

[val] downloading 215/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140104_2336_HARP3560_NOAA11942.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140104_2336_HARP3560_NOAA11942.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cbfd30b447da0b6f5cce554d060471e1.npz

.

Average throughput: 56.8MiB/s

[val] downloading 216/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140120_0312_HARP3648_NOAA11957.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140120_0312_HARP3648_NOAA11957.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ca1da91f3d3ce7def95db66480d66e43.npz

.

Average throughput: 135.9MiB/s

[val] downloading 217/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140129_1300_HARP3668_NOAA11965.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140129_1300_HARP3668_NOAA11965.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/85c5394b575f1c9e2e7e065c3ffcec5a.npz

.

Average throughput: 90.3MiB/s

[val] downloading 218/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140807_0548_HARP4424_NOAA12134.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140807_0548_HARP4424_NOAA12134.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0de8f24d6080dca3b62b7c81e854d09e.npz

.

Average throughput: 81.5MiB/s

[val] downloading 219/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140612_1536_HARP4224_NOAA12091.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140612_1536_HARP4224_NOAA12091.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5c1774b6d12527cf9710fb086e713e69.npz

.

Average throughput: 136.0MiB/s

[val] downloading 220/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140121_1112_HARP3648_NOAA11957.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140121_1112_HARP3648_NOAA11957.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b1e8bde18bb935443b3fbd44f218137a.npz

.

Average throughput: 70.9MiB/s

[val] downloading 221/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140630_1348_HARP4288_NOAA12100.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140630_1348_HARP4288_NOAA12100.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/79c66f604ea28f16362edf35863f0caa.npz

.

Average throughput: 91.5MiB/s

[val] downloading 222/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141114_1148_HARP4814_NOAA12212.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141114_1148_HARP4814_NOAA12212.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a1f30eee06af9ce1e26818e8e6dbdc09.npz

.

Average throughput: 87.2MiB/s

[val] downloading 223/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141013_0300_HARP4667_NOAA12186.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141013_0300_HARP4667_NOAA12186.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7df189e9f49af1126a3b390887d2f2ce.npz

.

Average throughput: 158.7MiB/s

[val] downloading 224/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141108_2312_HARP4784_NOAA12206.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141108_2312_HARP4784_NOAA12206.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d36440add3a7dc2f75269e1d5b823401.npz

.

Average throughput: 109.7MiB/s

[val] downloading 225/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141110_2000_HARP4784_NOAA12206.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141110_2000_HARP4784_NOAA12206.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6772d93c0325a96689c5c0de30e402b5.npz

.

Average throughput: 114.4MiB/s

[val] downloading 226/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140703_1136_HARP4295_NOAA12103.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140703_1136_HARP4295_NOAA12103.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8e77186a8de2ce106103092581a53c1c.npz

.

Average throughput: 110.2MiB/s

[val] downloading 227/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140118_0212_HARP3620_NOAA11952.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140118_0212_HARP3620_NOAA11952.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/83b6b604de943f47032a257d41cd8894.npz

.

Average throughput: 123.9MiB/s

[val] downloading 228/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140517_0248_HARP4123_NOAA12061.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140517_0248_HARP4123_NOAA12061.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fa1f7f6f47779e5d272bac7ea3e5fc83.npz

.

Average throughput: 47.9MiB/s

[val] downloading 229/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141102_1912_HARP4751_NOAA12200.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141102_1912_HARP4751_NOAA12200.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b33c8222adb5b8bdd5d1511142b73051.npz

.

Average throughput: 128.2MiB/s

[val] downloading 230/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140503_0100_HARP4073_NOAA12049.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140503_0100_HARP4073_NOAA12049.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8b8e0de0df82f39a48528519d1cac5c5.npz

.

Average throughput: 66.0MiB/s

[val] downloading 231/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140106_0812_HARP3580_NOAA11946.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140106_0812_HARP3580_NOAA11946.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3dae39dae2451ce2ca5dc70868280657.npz

.

Average throughput: 76.0MiB/s

[val] downloading 232/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140404_2148_HARP3942_NOAA12026.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140404_2148_HARP3942_NOAA12026.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/de35f4b964f728ca9808c03caae10592.npz

..

Average throughput: 29.2MiB/s

[val] downloading 233/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140618_2236_HARP4228_NOAA12090.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140618_2236_HARP4228_NOAA12090.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/857b94ea328627f23c0cb4a47a53336c.npz

.

Average throughput: 148.8MiB/s

[val] downloading 234/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140215_0548_HARP3740_NOAA11977.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140215_0548_HARP3740_NOAA11977.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7c6affd7abe8056de780ba217ff9a9ca.npz

.

Average throughput: 79.0MiB/s

[val] downloading 235/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141118_0848_HARP4810_NOAA12210.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141118_0848_HARP4810_NOAA12210.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4bb28292acd30419c915cd2b9b7d6e5a.npz

.

Average throughput: 130.4MiB/s

[val] downloading 236/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140210_0636_HARP3711_NOAA11971.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140210_0636_HARP3711_NOAA11971.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a3c5b35028390343b6667463123a01e2.npz



Average throughput: 157.1MiB/s

[val] downloading 237/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140119_1148_HARP3620_NOAA11952.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140119_1148_HARP3620_NOAA11952.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/bcd5e5a0b4ed3718a0d6407979c6a64c.npz

.

Average throughput: 153.4MiB/s

[val] downloading 238/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140424_0048_HARP4042_NOAA12045.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140424_0048_HARP4042_NOAA12045.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/064868ec3fd727981ec4eb390f22584e.npz

.

Average throughput: 67.9MiB/s

[val] downloading 239/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140111_0436_HARP3612_NOAA11951.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140111_0436_HARP3612_NOAA11951.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/37a74d5888850f374f9b6dd3eefeff4e.npz

.

Average throughput: 149.3MiB/s

[val] downloading 240/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140606_1836_HARP4201_NOAA12084.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140606_1836_HARP4201_NOAA12084.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/50fc654f74df0e2c8987f925e7fad6de.npz

.

Average throughput: 123.0MiB/s

[val] downloading 241/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140104_0424_HARP3560_NOAA11942.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140104_0424_HARP3560_NOAA11942.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6d6358f75d91f5e4e2652a4a32e05929.npz

.

Average throughput: 44.5MiB/s

[val] downloading 242/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140806_1148_HARP4396_NOAA12127.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140806_1148_HARP4396_NOAA12127.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/905cc958e2515e0ce55afe9338d946b7.npz

.

Average throughput: 41.2MiB/s

[val] downloading 243/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140205_0112_HARP3703_NOAA11970.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140205_0112_HARP3703_NOAA11970.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/722e790b0df4cd28f6d40e40b5ed2d65.npz

.

Average throughput: 74.8MiB/s

[val] downloading 244/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140802_2300_HARP4396_NOAA12127.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140802_2300_HARP4396_NOAA12127.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2439c08c45625c5be1cbf72266783c17.npz

.

Average throughput: 81.2MiB/s

[val] downloading 245/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141102_1212_HARP4761_NOAA12202.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141102_1212_HARP4761_NOAA12202.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f189c4613dabc4341ed6dad603d5d6eb.npz

.

Average throughput: 40.1MiB/s

[val] downloading 246/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141215_0348_HARP4908_NOAA12232.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141215_0348_HARP4908_NOAA12232.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1d775c9d63a3748dbd2f93a1d713e3b6.npz

.

Average throughput: 183.6MiB/s

[val] downloading 247/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140319_2024_HARP3848_NOAA12005.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140319_2024_HARP3848_NOAA12005.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/bb1531964ae3296d91386bb575d0c4a3.npz

.

Average throughput: 145.4MiB/s

[val] downloading 248/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141201_2312_HARP4862_NOAA12217.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141201_2312_HARP4862_NOAA12217.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e4971f6c309585a0ab2a99c5ef1a81aa.npz

.

Average throughput: 83.8MiB/s

[val] downloading 249/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141218_1148_HARP4932_NOAA12236.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141218_1148_HARP4932_NOAA12236.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/68eadbd4f0cdd479d2bcf6c319c84d97.npz

.

Average throughput: 121.0MiB/s

[val] downloading 250/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141218_1524_HARP4938_NOAA12238.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141218_1524_HARP4938_NOAA12238.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f6d69bc14838b71b8e2775835a094d3f.npz

.

Average throughput: 179.5MiB/s

[val] downloading 251/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140628_1724_HARP4290_NOAA12099.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140628_1724_HARP4290_NOAA12099.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f37732cc7e4540d14ff30be3fe912b7d.npz



Average throughput: 159.4MiB/s

[val] downloading 252/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140323_0736_HARP3856_NOAA12008.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140323_0736_HARP3856_NOAA12008.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/952a244c18729a98bf1750095e38bd52.npz

.

Average throughput: 103.2MiB/s

[val] downloading 253/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141208_0948_HARP4888_NOAA12227.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141208_0948_HARP4888_NOAA12227.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0bbfc94f3eb27032dd0125d956407d37.npz

.

Average throughput: 68.8MiB/s

[val] downloading 254/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141208_1436_HARP4888_NOAA12227.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141208_1436_HARP4888_NOAA12227.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f6665f68ea269df05428aac2920f01a5.npz



Average throughput: 169.6MiB/s

[val] downloading 255/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140606_0912_HARP4190_NOAA12079.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140606_0912_HARP4190_NOAA12079.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7424a34e022fb10c421185552df4c085.npz

.

Average throughput: 39.5MiB/s

[val] downloading 256/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140204_2248_HARP3686_NOAA11967.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140204_2248_HARP3686_NOAA11967.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0b57ff6259f295fd6688745a78eaf32d.npz

.

Average throughput: 83.3MiB/s

[val] downloading 257/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140303_0524_HARP3793_NOAA11990.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140303_0524_HARP3793_NOAA11990.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0c0b8fe8d5186db1ff449699046caf10.npz

.

Average throughput: 77.7MiB/s

[val] downloading 258/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140507_0648_HARP4088_NOAA12052.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140507_0648_HARP4088_NOAA12052.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5cc4b441789da5f1f59981cab777c768.npz

.

Average throughput: 94.9MiB/s

[val] downloading 259/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140718_2324_HARP4376_NOAA12120.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140718_2324_HARP4376_NOAA12120.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1ad53ff8ff124a325031f5ab61a7eba3.npz

.

Average throughput: 151.4MiB/s

[val] downloading 260/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140211_0648_HARP3721_NOAA11974.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140211_0648_HARP3721_NOAA11974.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1409dab1e6a04079ca8e8f66bc1b1425.npz

.

Average throughput: 100.9MiB/s

[val] downloading 261/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141130_2248_HARP4872_NOAA12221.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141130_2248_HARP4872_NOAA12221.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3708b41781222991e78e43bdea65372b.npz

.

Average throughput: 62.9MiB/s

[val] downloading 262/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140805_1012_HARP4422_NOAA12133.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140805_1012_HARP4422_NOAA12133.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/963da42b10a19f8211e60535dbecf170.npz

.

Average throughput: 86.6MiB/s

[val] downloading 263/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140707_1000_HARP4315_NOAA12108.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140707_1000_HARP4315_NOAA12108.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f5de6bcad12b743c8d22a434b61e0c20.npz

.

Average throughput: 155.0MiB/s

[val] downloading 264/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140601_1724_HARP4179_NOAA12083.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140601_1724_HARP4179_NOAA12083.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8c7a483ac585c1ff53a7d6ad9f29657a.npz

.

Average throughput: 102.6MiB/s

[val] downloading 265/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140310_0012_HARP3824_NOAA11998.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140310_0012_HARP3824_NOAA11998.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/752eedecf90365575f596e9ff9d850ea.npz

.

Average throughput: 133.8MiB/s

[val] downloading 266/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140504_1800_HARP4088_NOAA12052.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140504_1800_HARP4088_NOAA12052.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c79e8f0796baa4cad5ebcfb0a94e1655.npz

.

Average throughput: 106.4MiB/s

[val] downloading 267/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141123_1724_HARP4839_NOAA12215.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141123_1724_HARP4839_NOAA12215.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/426aa7aae40cbcbe8ae2b641c2e8731b.npz

.

Average throughput: 70.7MiB/s

[val] downloading 268/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140105_0736_HARP3569_NOAA11945.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140105_0736_HARP3569_NOAA11945.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f4172bd8f9ba690a061d03e1ad2ce8c4.npz

.

Average throughput: 127.9MiB/s

[val] downloading 269/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140810_0724_HARP4424_NOAA12134.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140810_0724_HARP4424_NOAA12134.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e67d4c93fdc7298c3ed869949253b8c0.npz

.

Average throughput: 179.4MiB/s

[val] downloading 270/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140528_1012_HARP4166_NOAA12075.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140528_1012_HARP4166_NOAA12075.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3c1ec7c24241612b418af76a1ffcac85.npz

.

Average throughput: 63.4MiB/s

[val] downloading 271/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140114_0000_HARP3612_NOAA11951.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140114_0000_HARP3612_NOAA11951.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3bb78dfaac5041b84231a6ba1a683c86.npz

.

Average throughput: 73.7MiB/s

[val] downloading 272/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140116_0836_HARP3620_NOAA11952.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140116_0836_HARP3620_NOAA11952.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b0d1ae256f2f0b9506cd5a0fd2d2b054.npz

.

Average throughput: 44.8MiB/s

[val] downloading 273/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140224_0012_HARP3766_NOAA11981.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140224_0012_HARP3766_NOAA11981.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/43788ede07d132eaacdc7425ac9266d8.npz

.

Average throughput: 154.4MiB/s

[val] downloading 274/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141101_2036_HARP4750_NOAA12199.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141101_2036_HARP4750_NOAA12199.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e3b9ad95aad0839b049088f68087516e.npz

.

Average throughput: 123.5MiB/s

[val] downloading 275/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141212_1812_HARP4908_NOAA12232.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141212_1812_HARP4908_NOAA12232.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1778346554332a593ff30966a3bd5a3b.npz

.

Average throughput: 84.9MiB/s

[val] downloading 276/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140622_0600_HARP4256_NOAA12094.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140622_0600_HARP4256_NOAA12094.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/28636f23cebecc1d635f5c280fc3d98f.npz

.

Average throughput: 169.7MiB/s

[val] downloading 277/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140710_1212_HARP4321_NOAA12109.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140710_1212_HARP4321_NOAA12109.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a8bd5d05b5a363934a5655191b44bfa1.npz

.

Average throughput: 184.0MiB/s

[val] downloading 278/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140111_2036_HARP3612_NOAA11951.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140111_2036_HARP3612_NOAA11951.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/07273fa1e29e32740cd37a7f119f9ab8.npz

.

Average throughput: 127.9MiB/s

[val] downloading 279/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140510_0536_HARP4097_NOAA12055.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140510_0536_HARP4097_NOAA12055.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fc08527ac751aa2b05984fc815b4747b.npz

.

Average throughput: 103.8MiB/s

[val] downloading 280/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140619_1436_HARP4228_NOAA12090.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140619_1436_HARP4228_NOAA12090.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/82fbafc91c430cc3c199056174b40923.npz

.

Average throughput: 174.1MiB/s

[val] downloading 281/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140227_1524_HARP3779_NOAA11986.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140227_1524_HARP3779_NOAA11986.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b5c7487ec50e9c651e2267a46bc2015c.npz



Average throughput: 187.5MiB/s

[val] downloading 282/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140617_0724_HARP4228_NOAA12090.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140617_0724_HARP4228_NOAA12090.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/45188fbf79c657977a74c35f729be1aa.npz

.

Average throughput: 151.5MiB/s

[val] downloading 283/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140317_2112_HARP3853_NOAA12009.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140317_2112_HARP3853_NOAA12009.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9a8f992f54045cf5ad377c0cab008f63.npz



Average throughput: 171.5MiB/s

[val] downloading 284/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140116_0300_HARP3601_NOAA11949.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140116_0300_HARP3601_NOAA11949.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ae459c67075cc193a06ade7292f12141.npz

.

Average throughput: 184.9MiB/s

[val] downloading 285/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140718_1424_HARP4375_NOAA12119.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140718_1424_HARP4375_NOAA12119.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ef9212570d8e6f08460c080d1b0005df.npz

.

Average throughput: 115.5MiB/s

[val] downloading 286/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141027_2212_HARP4718_NOAA12194.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141027_2212_HARP4718_NOAA12194.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a7652a508d6c8eca275ebc66a4bebce4.npz

.

Average throughput: 145.3MiB/s

[val] downloading 287/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141001_1848_HARP4616_NOAA12178.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141001_1848_HARP4616_NOAA12178.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7f2f0a68f5938cb6100bf8abc5d862ed.npz

.

Average throughput: 147.9MiB/s

[val] downloading 288/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140118_2124_HARP3620_NOAA11952.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140118_2124_HARP3620_NOAA11952.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/72b71b3783bfcd81b5165f2f8843a05d.npz

.

Average throughput: 175.2MiB/s

[val] downloading 289/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140512_0900_HARP4093_NOAA12054.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140512_0900_HARP4093_NOAA12054.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2790085efc49042b44f937c372e6c936.npz

.

Average throughput: 162.2MiB/s

[val] downloading 290/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140401_0200_HARP3907_NOAA12024.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140401_0200_HARP3907_NOAA12024.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/28fb987ae36c6ce781c091d112b35ca0.npz

.

Average throughput: 79.8MiB/s

[val] downloading 291/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140516_1112_HARP4111_NOAA12058.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140516_1112_HARP4111_NOAA12058.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2626609fdf9e5ab9fe3eafac11bab162.npz

.

Average throughput: 58.8MiB/s

[val] downloading 292/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140501_1400_HARP4075_NOAA12050.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140501_1400_HARP4075_NOAA12050.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9922cf600533a3522c0fbce082006eea.npz

.

Average throughput: 187.7MiB/s

[val] downloading 293/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141005_0000_HARP4616_NOAA12178.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141005_0000_HARP4616_NOAA12178.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0d6baa2012a7741a92e2d0f50f341193.npz

.

Average throughput: 68.8MiB/s

[val] downloading 294/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141226_0348_HARP4969_NOAA12245.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141226_0348_HARP4969_NOAA12245.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/19c684a31a617c15e5b486bd7bd97140.npz

.

Average throughput: 80.4MiB/s

[val] downloading 295/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141209_2336_HARP4900_NOAA12230.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141209_2336_HARP4900_NOAA12230.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/934f32cb1a1d28b7d501a5ab84b0b593.npz



Average throughput: 183.8MiB/s

[val] downloading 296/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141006_0412_HARP4640_NOAA12183.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141006_0412_HARP4640_NOAA12183.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3702cae39f11f5d527b88a597a7eefd9.npz

.

Average throughput: 151.1MiB/s

[val] downloading 297/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140315_2336_HARP3836_NOAA12002.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140315_2336_HARP3836_NOAA12002.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fbf39f7124b5431baff81797d7364187.npz

.

Average throughput: 63.6MiB/s

[val] downloading 298/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141225_2200_HARP4963_NOAA12244.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141225_2200_HARP4963_NOAA12244.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/282814dc09fd5710bc30379abb93b4b7.npz

.

Average throughput: 97.7MiB/s

[val] downloading 299/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141125_2012_HARP4868_NOAA12219.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141125_2012_HARP4868_NOAA12219.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8cfe2864f2264c7b4648f25c285c1c30.npz

.

Average throughput: 96.6MiB/s

[val] downloading 300/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141220_0912_HARP4932_NOAA12236.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141220_0912_HARP4932_NOAA12236.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5683a828e865c32d1ab18c002537dfa8.npz

.

Average throughput: 109.9MiB/s

[val] cached/checked 300/825 files | elapsed 7.7 min
[val] downloading 301/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140618_0036_HARP4225_NOAA12087.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140618_0036_HARP4225_NOAA12087.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c27d65cecd6e5467ca702cb38e5ae88e.npz

.

Average throughput: 87.3MiB/s

[val] downloading 302/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141125_0300_HARP4868_NOAA12219.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141125_0300_HARP4868_NOAA12219.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/918a50840f735e014dc05031a4ce88c5.npz

.

Average throughput: 68.3MiB/s

[val] downloading 303/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140327_0912_HARP3879_NOAA12014.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140327_0912_HARP3879_NOAA12014.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1ea216bed8d2aaa1377893c6dd82848a.npz

.

Average throughput: 114.9MiB/s

[val] downloading 304/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141014_2048_HARP4683_NOAA12188.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141014_2048_HARP4683_NOAA12188.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cc7ded3c61eb06b00c6132d5706113ad.npz

.

Average throughput: 99.2MiB/s

[val] downloading 305/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140603_1124_HARP4189_NOAA12078.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140603_1124_HARP4189_NOAA12078.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/45587bc5c4fe0aabe60f07d367b25396.npz

.

Average throughput: 129.3MiB/s

[val] downloading 306/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140607_1712_HARP4197_NOAA12080.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140607_1712_HARP4197_NOAA12080.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/dcacc16a39c44f7451d0811bf6ada283.npz

.

Average throughput: 51.0MiB/s

[val] downloading 307/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140704_0912_HARP4296_NOAA12104.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140704_0912_HARP4296_NOAA12104.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7e9faf32baf8f636d07fb168d52d8029.npz

.

Average throughput: 85.1MiB/s

[val] downloading 308/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140615_0312_HARP4231_NOAA12089.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140615_0312_HARP4231_NOAA12089.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/88da6fee1b4a45fb45e3f679baea1790.npz

.

Average throughput: 184.4MiB/s

[val] downloading 309/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140311_1100_HARP3824_NOAA11998.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140311_1100_HARP3824_NOAA11998.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/403aace94f425d3f332404655eeb72cc.npz

.

Average throughput: 66.2MiB/s

[val] downloading 310/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141023_0224_HARP4698_NOAA12192.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141023_0224_HARP4698_NOAA12192.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4d5d4c73d4551979249c78a0c1377a1a.npz

.

Average throughput: 109.2MiB/s

[val] downloading 311/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140113_0936_HARP3604_NOAA11950.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140113_0936_HARP3604_NOAA11950.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3c235c8ada753a49c19dfaedfb1a1b11.npz

.

Average throughput: 130.3MiB/s

[val] downloading 312/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140518_2348_HARP4123_NOAA12061.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140518_2348_HARP4123_NOAA12061.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/dcafa3ef8d96a0d89a1eb2b767854a8e.npz

.

Average throughput: 169.8MiB/s

[val] downloading 313/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140213_0524_HARP3721_NOAA11974.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140213_0524_HARP3721_NOAA11974.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e766935eb99d601c9b33e5d3d14ab255.npz

.

Average throughput: 141.5MiB/s

[val] downloading 314/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140501_0912_HARP4075_NOAA12050.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140501_0912_HARP4075_NOAA12050.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cb06cd8593fc45f27e7cfce03775bfec.npz

.

Average throughput: 47.9MiB/s

[val] downloading 315/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141107_1336_HARP4784_NOAA12206.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141107_1336_HARP4784_NOAA12206.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/332e5c6c0c1a3656a9e1026a20e10232.npz

.

Average throughput: 37.6MiB/s

[val] downloading 316/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140316_0236_HARP3853_NOAA12009.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140316_0236_HARP3853_NOAA12009.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/155736661849b75a77e6eeb56a08745f.npz

.

Average throughput: 116.9MiB/s

[val] downloading 317/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141207_0236_HARP4901_NOAA12229.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141207_0236_HARP4901_NOAA12229.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a4f8d0a11a96be6fb727abb7f9c203e6.npz

.

Average throughput: 105.0MiB/s

[val] downloading 318/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141106_1936_HARP4760_NOAA12201.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141106_1936_HARP4760_NOAA12201.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9ccbfb7a2a89b614117da82e6c130b5a.npz

.

Average throughput: 84.3MiB/s

[val] downloading 319/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140601_1300_HARP4189_NOAA12078.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140601_1300_HARP4189_NOAA12078.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c3967625c2f506de3461945e5597eff3.npz

.

Average throughput: 131.5MiB/s

[val] downloading 320/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140527_0300_HARP4156_NOAA12071.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140527_0300_HARP4156_NOAA12071.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/16b043a98ab7dd97794077af7ee3b928.npz

.

Average throughput: 93.4MiB/s

[val] downloading 321/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140705_0736_HARP4296_NOAA12104.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140705_0736_HARP4296_NOAA12104.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2d17419f85b583e8033333e2585710e7.npz



Average throughput: 141.4MiB/s

[val] downloading 322/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140207_0636_HARP3711_NOAA11971.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140207_0636_HARP3711_NOAA11971.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d36f57e502fcae0649458c3a609b2f55.npz

.

Average throughput: 71.6MiB/s

[val] downloading 323/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140528_1148_HARP4166_NOAA12075.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140528_1148_HARP4166_NOAA12075.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b292277ae94b0115f7e2be9d14cd28cb.npz

.

Average throughput: 93.0MiB/s

[val] downloading 324/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141116_0400_HARP4810_NOAA12210.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141116_0400_HARP4810_NOAA12210.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1a18a1d8b05bbb6d78ae85ec80bc385f.npz

.

Average throughput: 85.0MiB/s

[val] downloading 325/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140116_1848_HARP3635_NOAA11961.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140116_1848_HARP3635_NOAA11961.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b321cea780ecae28dd0350b06c25855d.npz

.

Average throughput: 165.1MiB/s

[val] downloading 326/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140120_0212_HARP3620_NOAA11952.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140120_0212_HARP3620_NOAA11952.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/16cccc6c4f5475b2df380f248d94cdde.npz

.

Average throughput: 85.4MiB/s

[val] downloading 327/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141015_1236_HARP4667_NOAA12186.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141015_1236_HARP4667_NOAA12186.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8f13b7415967fe3f940ff6fd2321c1a7.npz

.

Average throughput: 61.0MiB/s

[val] downloading 328/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141002_1600_HARP4616_NOAA12178.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141002_1600_HARP4616_NOAA12178.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5271539c00d0fa8837d08b194a8238d6.npz

.

Average throughput: 90.0MiB/s

[val] downloading 329/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140207_2236_HARP3711_NOAA11971.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140207_2236_HARP3711_NOAA11971.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b1b8e8eaa1b137bc94df83405f17a1aa.npz

.

Average throughput: 83.2MiB/s

[val] downloading 330/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140712_1436_HARP4351_NOAA12114.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140712_1436_HARP4351_NOAA12114.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/afb4f93ca7f0e2ed060997a7501eb66c.npz

.

Average throughput: 72.1MiB/s

[val] downloading 331/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140208_1124_HARP3711_NOAA11971.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140208_1124_HARP3711_NOAA11971.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c1c224220fd211c2209933c2001cab12.npz

.

Average throughput: 169.2MiB/s

[val] downloading 332/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140209_1924_HARP3719_NOAA11973.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140209_1924_HARP3719_NOAA11973.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1eaa34c65f262deda5d40a6f08bd0b62.npz

.

Average throughput: 98.6MiB/s

[val] downloading 333/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140306_1624_HARP3821_NOAA11999.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140306_1624_HARP3821_NOAA11999.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0079b9766587ff1146f358386dd91dcf.npz

.

Average throughput: 116.8MiB/s

[val] downloading 334/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141031_0836_HARP4733_NOAA12196.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141031_0836_HARP4733_NOAA12196.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/64ceab6fa21d7cb36287948a33e6b268.npz

.

Average throughput: 153.1MiB/s

[val] downloading 335/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140104_2200_HARP3569_NOAA11945.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140104_2200_HARP3569_NOAA11945.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7cae8abc522d5bb012e167d5cd56cfd4.npz

.

Average throughput: 85.6MiB/s

[val] downloading 336/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141002_2248_HARP4623_NOAA12181.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141002_2248_HARP4623_NOAA12181.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6a3b241afc5901a32b97f64393f8d8f1.npz

.

Average throughput: 98.0MiB/s

[val] downloading 337/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140204_0436_HARP3688_NOAA11968.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140204_0436_HARP3688_NOAA11968.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/30c0f4ef941ea7dc42aeb3b165e7ad4c.npz

.

Average throughput: 102.9MiB/s

[val] downloading 338/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141227_1100_HARP4978_NOAA12247.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141227_1100_HARP4978_NOAA12247.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/15b5ba74854e4d67d6594f153591df24.npz

.

Average throughput: 140.7MiB/s

[val] downloading 339/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140720_1424_HARP4375_NOAA12119.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140720_1424_HARP4375_NOAA12119.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2d82978179c6302b6a0c252452577fea.npz

.

Average throughput: 158.0MiB/s

[val] downloading 340/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141210_1048_HARP4900_NOAA12230.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141210_1048_HARP4900_NOAA12230.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9b72748ec8527603ce522b23a9f646b7.npz

.

Average throughput: 162.8MiB/s

[val] downloading 341/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140731_0812_HARP4390_NOAA12124.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140731_0812_HARP4390_NOAA12124.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/42eb6147531d0fdcf6c2655b828537f8.npz

.

Average throughput: 184.6MiB/s

[val] downloading 342/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140424_1824_HARP4042_NOAA12045.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140424_1824_HARP4042_NOAA12045.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d3adec5d3a0b7bcd9c59930ba42f011c.npz

.

Average throughput: 86.1MiB/s

[val] downloading 343/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141123_0612_HARP4839_NOAA12215.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141123_0612_HARP4839_NOAA12215.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e015ec7c0f4ed086f83b5a1e1987da06.npz

.

Average throughput: 179.7MiB/s

[val] downloading 344/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140626_1436_HARP4284_NOAA12098.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140626_1436_HARP4284_NOAA12098.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/42656755d7e5dbe28fb00e94986ac694.npz

.

Average throughput: 112.1MiB/s

[val] downloading 345/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140519_1900_HARP4138_NOAA12065.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140519_1900_HARP4138_NOAA12065.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/53867de76be30b9fedad0f3663160f2a.npz

.

Average throughput: 120.9MiB/s

[val] downloading 346/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141106_1448_HARP4751_NOAA12200.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141106_1448_HARP4751_NOAA12200.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d777f58efa2a100d59bf8694a2f4efb3.npz



Average throughput: 210.4MiB/s

[val] downloading 347/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140328_0212_HARP3894_NOAA12017.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140328_0212_HARP3894_NOAA12017.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1701f682b59a742c9027173f03641a47.npz

.

Average throughput: 130.4MiB/s

[val] downloading 348/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141211_1812_HARP4921_NOAA12234.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141211_1812_HARP4921_NOAA12234.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6656fce4f447dfbcccd7aa69d18ab64c.npz

.

Average throughput: 182.6MiB/s

[val] downloading 349/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141005_1936_HARP4639_NOAA12182.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141005_1936_HARP4639_NOAA12182.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a55b4135ff6470df8ef5097d9ab3d0a0.npz

.

Average throughput: 75.5MiB/s

[val] downloading 350/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141217_1900_HARP4942_NOAA12239.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141217_1900_HARP4942_NOAA12239.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b8e6ed93fd1edc87ea2e08cbfb9c881c.npz

.

Average throughput: 125.8MiB/s

[val] downloading 351/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140403_0512_HARP3926_NOAA12022.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140403_0512_HARP3926_NOAA12022.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ef3808b13c2c39de2129e1b3d68f51a1.npz

.

Average throughput: 159.1MiB/s

[val] downloading 352/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140120_2312_HARP3658_NOAA11962.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140120_2312_HARP3658_NOAA11962.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/383cfff83a7a33a9c17046f09d628b97.npz

.

Average throughput: 171.4MiB/s

[val] downloading 353/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141225_2000_HARP4973_NOAA12246.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141225_2000_HARP4973_NOAA12246.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/463d20628812c964c1c37ff5bea26405.npz

.

Average throughput: 62.7MiB/s

[val] downloading 354/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140101_0112_HARP3542_NOAA11937.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140101_0112_HARP3542_NOAA11937.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b3150bd072f41acfcedc2bd7dbd92875.npz

.

Average throughput: 173.2MiB/s

[val] downloading 355/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141121_1448_HARP4839_NOAA12215.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141121_1448_HARP4839_NOAA12215.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e41da310aae568e7d5d41eac9ef7afac.npz

.

Average throughput: 108.4MiB/s

[val] downloading 356/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140323_0112_HARP3856_NOAA12008.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140323_0112_HARP3856_NOAA12008.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/61438b569cd31d0b15a274c4cabae5ad.npz

.

Average throughput: 104.1MiB/s

[val] downloading 357/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140415_0912_HARP3996_NOAA12034.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140415_0912_HARP3996_NOAA12034.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4a71f241c62bfefacdf4c325d683de3e.npz

.

Average throughput: 175.1MiB/s

[val] downloading 358/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141003_0648_HARP4623_NOAA12181.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141003_0648_HARP4623_NOAA12181.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/226aa9bb3451231a6a84d3dd6f4a73b3.npz

.

Average throughput: 160.5MiB/s

[val] downloading 359/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140324_1300_HARP3879_NOAA12014.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140324_1300_HARP3879_NOAA12014.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8e01bfd43a518969221323e847a2d2a7.npz

.

Average throughput: 84.9MiB/s

[val] downloading 360/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141026_2048_HARP4726_NOAA12195.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141026_2048_HARP4726_NOAA12195.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6664010ec768e069260bb788fc648713.npz



Average throughput: 189.0MiB/s

[val] downloading 361/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140212_2112_HARP3721_NOAA11974.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140212_2112_HARP3721_NOAA11974.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f9e6aac4f2a3cb18743314ca7b649df6.npz

.

Average throughput: 126.4MiB/s

[val] downloading 362/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140310_0324_HARP3824_NOAA11998.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140310_0324_HARP3824_NOAA11998.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e1b772764fa37415a90b5e6a85ed50b2.npz

.

Average throughput: 169.6MiB/s

[val] downloading 363/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140405_1036_HARP3957_NOAA12029.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140405_1036_HARP3957_NOAA12029.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4cb46a8596d349fc139f49ecffd6d569.npz

.

Average throughput: 62.2MiB/s

[val] downloading 364/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141221_2112_HARP4943_NOAA12240.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141221_2112_HARP4943_NOAA12240.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/26382b8518ca410216e69db6b14fe46f.npz

.

Average throughput: 124.1MiB/s

[val] downloading 365/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141030_0836_HARP4733_NOAA12196.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141030_0836_HARP4733_NOAA12196.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2ef617d87da54a9d673ed6862d6d8a8f.npz

.

Average throughput: 99.8MiB/s

[val] downloading 366/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141106_1336_HARP4784_NOAA12206.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141106_1336_HARP4784_NOAA12206.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/033c8a09442fe32f580f990db7fa465e.npz

.

Average throughput: 74.9MiB/s

[val] downloading 367/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140708_2000_HARP4328_NOAA12111.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140708_2000_HARP4328_NOAA12111.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6d320bc044cff7217789e3ade8af5510.npz

.

Average throughput: 167.8MiB/s

[val] downloading 368/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140509_2324_HARP4093_NOAA12054.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140509_2324_HARP4093_NOAA12054.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2134a18c7d8289fdaa0d24908bc38e69.npz

.

Average throughput: 185.3MiB/s

[val] downloading 369/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141030_2036_HARP4750_NOAA12199.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141030_2036_HARP4750_NOAA12199.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3b31a0e686838be37632831d6480e2fa.npz

.

Average throughput: 118.2MiB/s

[val] downloading 370/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141118_1648_HARP4810_NOAA12210.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141118_1648_HARP4810_NOAA12210.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e2f7f824d9e0ebe63b1888aa9b32d95a.npz

.

Average throughput: 84.1MiB/s

[val] downloading 371/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140217_1348_HARP3740_NOAA11977.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140217_1348_HARP3740_NOAA11977.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/96bd4147e10309b4264297508c7f85ea.npz

.

Average throughput: 97.7MiB/s

[val] downloading 372/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141207_1948_HARP4882_NOAA12225.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141207_1948_HARP4882_NOAA12225.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2241009e4cdb89744d9e94727fd226c0.npz

.

Average throughput: 66.6MiB/s

[val] downloading 373/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141028_0724_HARP4748_NOAA12198.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141028_0724_HARP4748_NOAA12198.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0f65e8893f1b4873b6b07082cd6dce8b.npz

.

Average throughput: 82.4MiB/s

[val] downloading 374/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140102_0900_HARP3557_NOAA11938.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140102_0900_HARP3557_NOAA11938.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0e5e435e7369ae5731f62b0e31f21205.npz

.

Average throughput: 117.0MiB/s

[val] downloading 375/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141216_1524_HARP4942_NOAA12239.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141216_1524_HARP4942_NOAA12239.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2b0902a4a1e54229d431627729b31e0c.npz

.

Average throughput: 140.0MiB/s

[val] downloading 376/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140609_0600_HARP4197_NOAA12080.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140609_0600_HARP4197_NOAA12080.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/359486b2b756b5eaecb8be6406dfce61.npz

.

Average throughput: 140.3MiB/s

[val] downloading 377/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141125_0748_HARP4868_NOAA12219.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141125_0748_HARP4868_NOAA12219.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e2cb4b35a4f50cf51973a8b7c76b3ab5.npz

.

Average throughput: 91.7MiB/s

[val] downloading 378/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140113_2112_HARP3610_NOAA11954.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140113_2112_HARP3610_NOAA11954.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9b90426d993d4346c059a45080e5f969.npz

.

Average throughput: 149.8MiB/s

[val] downloading 379/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140526_1412_HARP4156_NOAA12071.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140526_1412_HARP4156_NOAA12071.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1e519f19b9ab145d7cbb39e101484981.npz

.

Average throughput: 126.7MiB/s

[val] downloading 380/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141120_0400_HARP4839_NOAA12215.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141120_0400_HARP4839_NOAA12215.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a32d493b8c750fe5991dde0c26a860c9.npz

.

Average throughput: 107.7MiB/s

[val] downloading 381/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140202_1448_HARP3686_NOAA11967.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140202_1448_HARP3686_NOAA11967.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4c5d3f52e51cb5f0b75a3ca0dae32aff.npz

.

Average throughput: 139.4MiB/s

[val] downloading 382/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140314_2024_HARP3836_NOAA12002.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140314_2024_HARP3836_NOAA12002.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ea7944efa092e33a7e500c339f849eee.npz

.

Average throughput: 41.3MiB/s

[val] downloading 383/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141218_1700_HARP4942_NOAA12239.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141218_1700_HARP4942_NOAA12239.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ad37d77640794c58092018fe7a5ac928.npz

.

Average throughput: 161.5MiB/s

[val] downloading 384/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140426_2324_HARP4065_NOAA12048.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140426_2324_HARP4065_NOAA12048.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6eae9109f26757f2dfd898adb7a4c40b.npz

.

Average throughput: 69.2MiB/s

[val] downloading 385/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140527_0748_HARP4156_NOAA12071.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140527_0748_HARP4156_NOAA12071.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8868c35b06f436112225d2b892476b09.npz

.

Average throughput: 71.6MiB/s

[val] downloading 386/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141004_0000_HARP4616_NOAA12178.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141004_0000_HARP4616_NOAA12178.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/62bc397b636575ecfb64a86732672683.npz

.

Average throughput: 53.1MiB/s

[val] downloading 387/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141212_0212_HARP4921_NOAA12234.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141212_0212_HARP4921_NOAA12234.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/abc25697ea8c11172f559b4dae9f6b8c.npz

.

Average throughput: 171.3MiB/s

[val] downloading 388/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140518_0924_HARP4123_NOAA12061.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140518_0924_HARP4123_NOAA12061.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fa506281aa14197e132616d1e15620c4.npz

.

Average throughput: 92.2MiB/s

[val] downloading 389/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140405_0436_HARP3941_NOAA12027.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140405_0436_HARP3941_NOAA12027.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/aa477837d8f1fc128497299491e60d9e.npz

.

Average throughput: 97.1MiB/s

[val] downloading 390/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141201_1948_HARP4874_NOAA12222.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141201_1948_HARP4874_NOAA12222.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3e6aceda03f9e257ca797cce87014b90.npz

.

Average throughput: 87.2MiB/s

[val] downloading 391/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140109_1724_HARP3612_NOAA11951.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140109_1724_HARP3612_NOAA11951.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/741b913ce5bd0d5815274a1e7063d121.npz

.

Average throughput: 153.9MiB/s

[val] downloading 392/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140422_0112_HARP4040_NOAA12044.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140422_0112_HARP4040_NOAA12044.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/857d372d37a9342dbb42ad673113273b.npz

.

Average throughput: 145.8MiB/s

[val] downloading 393/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140209_2236_HARP3721_NOAA11974.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140209_2236_HARP3721_NOAA11974.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3f2c73d2fa24c07927ba892a4f0db1f4.npz

.

Average throughput: 165.7MiB/s

[val] downloading 394/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141031_0748_HARP4750_NOAA12199.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141031_0748_HARP4750_NOAA12199.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/dc9f18b2c238d718ac2b563d3c85e9ab.npz

.

Average throughput: 52.3MiB/s

[val] downloading 395/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141227_1524_HARP4973_NOAA12246.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141227_1524_HARP4973_NOAA12246.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fd9fa4939683bdc3b507e81b2e1f2f54.npz

.

Average throughput: 112.5MiB/s

[val] downloading 396/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140428_2012_HARP4071_NOAA12047.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140428_2012_HARP4071_NOAA12047.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/bbf6dfc60405b76b7aef1fef34127d13.npz

.

Average throughput: 60.5MiB/s

[val] downloading 397/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141018_2112_HARP4678_NOAA12187.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141018_2112_HARP4678_NOAA12187.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1467d7e48d13392f7dabc37945f02200.npz

.

Average throughput: 54.2MiB/s

[val] downloading 398/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141130_0336_HARP4872_NOAA12221.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141130_0336_HARP4872_NOAA12221.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8b1383e8f88d84a778a2a2af9e001069.npz

.

Average throughput: 151.0MiB/s

[val] downloading 399/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140701_1700_HARP4295_NOAA12103.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140701_1700_HARP4295_NOAA12103.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9e019204bbf1c7e3c1eb2b5d04d8a79f.npz

.

Average throughput: 52.2MiB/s

[val] downloading 400/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140418_0000_HARP3999_NOAA12036.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140418_0000_HARP3999_NOAA12036.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/bdd19fa83991c1f26cdc96e6ebaea202.npz

.

Average throughput: 99.6MiB/s

[val] cached/checked 400/825 files | elapsed 10.3 min
[val] downloading 401/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140719_1600_HARP4375_NOAA12119.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140719_1600_HARP4375_NOAA12119.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e69268a47138e806af49be4321a5928e.npz

.

Average throughput: 129.5MiB/s

[val] downloading 402/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140202_1624_HARP3686_NOAA11967.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140202_1624_HARP3686_NOAA11967.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2eff5b2e203f24a83202fb9f5e300042.npz

.

Average throughput: 107.0MiB/s

[val] downloading 403/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140311_1224_HARP3826_NOAA12000.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140311_1224_HARP3826_NOAA12000.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e1bce4970848d28c022289db9703950f.npz

.

Average throughput: 84.3MiB/s

[val] downloading 404/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140309_1612_HARP3824_NOAA11998.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140309_1612_HARP3824_NOAA11998.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e95541eb30593330b927af84b5327df9.npz

.

Average throughput: 154.9MiB/s

[val] downloading 405/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140225_1948_HARP3785_NOAA11988.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140225_1948_HARP3785_NOAA11988.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/582f9a4ce85d28254f56ee19c9204b09.npz

.

Average throughput: 73.5MiB/s

[val] downloading 406/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140607_0424_HARP4190_NOAA12079.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140607_0424_HARP4190_NOAA12079.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5ffb9714f72ddaa6a84392b980718ec8.npz

.

Average throughput: 92.9MiB/s

[val] downloading 407/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140718_1500_HARP4374_NOAA12118.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140718_1500_HARP4374_NOAA12118.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e064ed86d2deb76ff020b103980d3a9c.npz

.

Average throughput: 195.0MiB/s

[val] downloading 408/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141114_2024_HARP4800_NOAA12207.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141114_2024_HARP4800_NOAA12207.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c065b4a54ebace8f30994bb664b93c43.npz

.

Average throughput: 156.0MiB/s

[val] downloading 409/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140113_0024_HARP3610_NOAA11954.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140113_0024_HARP3610_NOAA11954.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/da4c43544eb37d65f6b0df07e2e51620.npz

.

Average throughput: 144.3MiB/s

[val] downloading 410/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140213_0424_HARP3730_NOAA11976.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140213_0424_HARP3730_NOAA11976.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d2f5edbe3c4dbb0e7fb525a7c4eb4432.npz

.

Average throughput: 161.8MiB/s

[val] downloading 411/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140204_1624_HARP3686_NOAA11967.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140204_1624_HARP3686_NOAA11967.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/14f0efb72222511e27525ef311c88b30.npz

.

Average throughput: 68.0MiB/s

[val] downloading 412/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140601_0800_HARP4166_NOAA12075.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140601_0800_HARP4166_NOAA12075.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c49eff54890e0d15f1875eaf5cf7a5b1.npz

.

Average throughput: 164.7MiB/s

[val] downloading 413/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141112_0700_HARP4781_NOAA12205.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141112_0700_HARP4781_NOAA12205.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/233a4cfde9deab6c5007056bc116c145.npz

.

Average throughput: 92.4MiB/s

[val] downloading 414/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141212_2312_HARP4915_NOAA12233.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141212_2312_HARP4915_NOAA12233.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/280a44d275d3e574f489d7798d35d827.npz

.

Average throughput: 94.6MiB/s

[val] downloading 415/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140203_1936_HARP3686_NOAA11967.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140203_1936_HARP3686_NOAA11967.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/155ea6cbae32314072109ece31f64f39.npz

.

Average throughput: 76.9MiB/s

[val] downloading 416/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140117_1148_HARP3620_NOAA11952.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140117_1148_HARP3620_NOAA11952.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ff44c4ffc49a4d1c737d7fa718635241.npz

.

Average throughput: 157.7MiB/s

[val] downloading 417/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140120_0536_HARP3658_NOAA11962.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140120_0536_HARP3658_NOAA11962.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3da1a7dc64e69789f25ccb133cc63917.npz

.

Average throughput: 196.9MiB/s

[val] downloading 418/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140607_1300_HARP4205_NOAA12082.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140607_1300_HARP4205_NOAA12082.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/62fdb75f6c0fc819858dd7d1a6948211.npz

.

Average throughput: 168.4MiB/s

[val] downloading 419/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141127_0612_HARP4868_NOAA12219.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141127_0612_HARP4868_NOAA12219.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b287c9623dd84cb1afbe57c4197dad16.npz

.

Average throughput: 123.1MiB/s

[val] downloading 420/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140620_2200_HARP4256_NOAA12094.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140620_2200_HARP4256_NOAA12094.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/981ab93fde302baa7aaddd4da76da198.npz

.

Average throughput: 137.8MiB/s

[val] downloading 421/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140423_2312_HARP4042_NOAA12045.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140423_2312_HARP4042_NOAA12045.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/63ae8ce0ce0582075175af651245ae47.npz

.

Average throughput: 175.7MiB/s

[val] downloading 422/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141031_0100_HARP4761_NOAA12202.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141031_0100_HARP4761_NOAA12202.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1070004222265722849c26c58c186919.npz

.

Average throughput: 81.8MiB/s

[val] downloading 423/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140111_2224_HARP3604_NOAA11950.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140111_2224_HARP3604_NOAA11950.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8aca81130ab9b449bc3f412d3da0e6a6.npz

.

Average throughput: 171.5MiB/s

[val] downloading 424/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140404_0100_HARP3957_NOAA12029.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140404_0100_HARP3957_NOAA12029.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fb252bfb15af3250ec48d02a6bf9c4b9.npz

.

Average throughput: 123.0MiB/s

[val] downloading 425/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140119_0700_HARP3620_NOAA11952.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140119_0700_HARP3620_NOAA11952.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c2d7e93dfb5d4c9a4af71861fe28ca8c.npz

.

Average throughput: 98.2MiB/s

[val] downloading 426/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141203_1148_HARP4874_NOAA12222.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141203_1148_HARP4874_NOAA12222.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d44c5c2d9c9567056e22bd24376cf02e.npz

.

Average throughput: 73.1MiB/s

[val] downloading 427/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140615_0624_HARP4225_NOAA12087.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140615_0624_HARP4225_NOAA12087.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d494131f8a7a6cd8bed0c4c44f0afb7a.npz

..

Average throughput: 35.1MiB/s

[val] downloading 428/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141217_1612_HARP4943_NOAA12240.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141217_1612_HARP4943_NOAA12240.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ec3be3325c362c8152c6319b1b374e80.npz

.

Average throughput: 105.4MiB/s

[val] downloading 429/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140123_1948_HARP3631_NOAA11955.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140123_1948_HARP3631_NOAA11955.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b9b7f4c7af9055420476bc2e0b0059ad.npz

.

Average throughput: 151.2MiB/s

[val] downloading 430/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140305_1548_HARP3813_NOAA11996.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140305_1548_HARP3813_NOAA11996.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0990aec35b32eb598899ba1162d083ee.npz

.

Average throughput: 121.9MiB/s

[val] downloading 431/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140211_1800_HARP3721_NOAA11974.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140211_1800_HARP3721_NOAA11974.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5661a818c62d7cbd457eb703ef516a85.npz

.

Average throughput: 111.4MiB/s

[val] downloading 432/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141114_0736_HARP4800_NOAA12207.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141114_0736_HARP4800_NOAA12207.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b1722e44157068eef5c65ea93532f87d.npz

.

Average throughput: 92.1MiB/s

[val] downloading 433/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140624_2212_HARP4284_NOAA12098.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140624_2212_HARP4284_NOAA12098.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7c143b1a9184371afa4deac77213cc62.npz



Average throughput: 186.7MiB/s

[val] downloading 434/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141206_1700_HARP4901_NOAA12229.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141206_1700_HARP4901_NOAA12229.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/123cfc65cca2d769ac9a4b97ae8a8efc.npz

.

Average throughput: 107.5MiB/s

[val] downloading 435/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140416_1348_HARP4023_NOAA12041.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140416_1348_HARP4023_NOAA12041.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e4b0fe1800909eb0df3c40dd9da1da05.npz



Average throughput: 205.1MiB/s

[val] downloading 436/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140614_1048_HARP4224_NOAA12091.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140614_1048_HARP4224_NOAA12091.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3eaceb7692eb49757cd4b3e895d037aa.npz

.

Average throughput: 94.9MiB/s

[val] downloading 437/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140730_0912_HARP4379_NOAA12121.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140730_0912_HARP4379_NOAA12121.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5ed7b34d93b3130d617d9488327eafaa.npz

.

Average throughput: 104.2MiB/s

[val] downloading 438/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140705_0324_HARP4294_NOAA12102.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140705_0324_HARP4294_NOAA12102.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/847b644cc7089098a3c3128b920fcace.npz

.

Average throughput: 167.6MiB/s

[val] downloading 439/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141109_0700_HARP4781_NOAA12205.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141109_0700_HARP4781_NOAA12205.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a259982a7cfc1785cf250d49dabda8f6.npz

.

Average throughput: 77.7MiB/s

[val] downloading 440/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140627_0300_HARP4290_NOAA12099.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140627_0300_HARP4290_NOAA12099.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9cea85c8099a5a78d7b5d8db2a1105ea.npz

.

Average throughput: 191.0MiB/s

[val] downloading 441/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140725_0900_HARP4381_NOAA12122.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140725_0900_HARP4381_NOAA12122.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c6841e5df4c7133e5b90f941c7b50150.npz

.

Average throughput: 112.7MiB/s

[val] downloading 442/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140120_0000_HARP3648_NOAA11957.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140120_0000_HARP3648_NOAA11957.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/929a1f8128e35f91c4e8acb8506a4f11.npz

.

Average throughput: 141.8MiB/s

[val] downloading 443/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141106_0648_HARP4751_NOAA12200.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141106_0648_HARP4751_NOAA12200.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/da5c68c04a8859f7c4c5f1025f87d374.npz

.

Average throughput: 81.1MiB/s

[val] downloading 444/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140121_2136_HARP3658_NOAA11962.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140121_2136_HARP3658_NOAA11962.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1d792cd1e07d591141256b82e09cdcf7.npz

.

Average throughput: 161.8MiB/s

[val] downloading 445/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141004_0824_HARP4623_NOAA12181.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141004_0824_HARP4623_NOAA12181.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c488fec109d8c964049db9a6c590ca20.npz

.

Average throughput: 117.2MiB/s

[val] downloading 446/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141014_0300_HARP4667_NOAA12186.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141014_0300_HARP4667_NOAA12186.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ac7584c96b9f9d0a14a4350b0d2bd5a0.npz

.

Average throughput: 169.9MiB/s

[val] downloading 447/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141013_1424_HARP4683_NOAA12188.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141013_1424_HARP4683_NOAA12188.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a4037c2f33ab5e7a5a0094e64d83535b.npz

.

Average throughput: 106.0MiB/s

[val] downloading 448/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140127_0448_HARP3647_NOAA11958.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140127_0448_HARP3647_NOAA11958.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/90fced32a65914a47795f2510f59dc2b.npz

.

Average throughput: 168.6MiB/s

[val] downloading 449/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141030_0548_HARP4734_NOAA12197.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141030_0548_HARP4734_NOAA12197.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0da9cf2278225a5525a49bf3bc628138.npz

.

Average throughput: 79.4MiB/s

[val] downloading 450/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140418_2248_HARP4011_NOAA12040.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140418_2248_HARP4011_NOAA12040.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/656b08afc56ba315e8ac6717639d12b6.npz

.

Average throughput: 135.8MiB/s

[val] downloading 451/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141110_0524_HARP4781_NOAA12205.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141110_0524_HARP4781_NOAA12205.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/41f849f18697f19e9f0eb0eba3be094a.npz

.

Average throughput: 127.2MiB/s

[val] downloading 452/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140125_2100_HARP3668_NOAA11965.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140125_2100_HARP3668_NOAA11965.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c73de15dd5f236f361c32cd6ee485212.npz

.

Average throughput: 103.0MiB/s

[val] downloading 453/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140225_0012_HARP3766_NOAA11981.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140225_0012_HARP3766_NOAA11981.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e9ee37804c6d21a09d87b206bfcae3c0.npz

.

Average throughput: 153.8MiB/s

[val] downloading 454/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140426_0248_HARP4040_NOAA12044.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140426_0248_HARP4040_NOAA12044.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cd1e566cbbdbe53779ac5e580b2f57d0.npz

.

Average throughput: 61.5MiB/s

[val] downloading 455/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140515_0012_HARP4131_NOAA12066.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140515_0012_HARP4131_NOAA12066.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e01c8cd3e1611aa26393aaf34fea020a.npz

.

Average throughput: 106.2MiB/s

[val] downloading 456/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141007_0724_HARP4640_NOAA12183.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141007_0724_HARP4640_NOAA12183.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c6c2bfd88eff32a79a3e891449e01685.npz

.

Average throughput: 63.6MiB/s

[val] downloading 457/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140428_0400_HARP4042_NOAA12045.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140428_0400_HARP4042_NOAA12045.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ec1aed37acc2a66f4005549e6b14104b.npz



Average throughput: 190.1MiB/s

[val] downloading 458/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140608_0912_HARP4190_NOAA12079.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140608_0912_HARP4190_NOAA12079.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/363ea0cd7fe7e22d33bc8d109dffff07.npz

.

Average throughput: 77.0MiB/s

[val] downloading 459/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140705_2236_HARP4294_NOAA12102.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140705_2236_HARP4294_NOAA12102.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b967e5291d9b3e759bd8c609203aed03.npz

.

Average throughput: 86.2MiB/s

[val] downloading 460/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141025_0648_HARP4698_NOAA12192.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141025_0648_HARP4698_NOAA12192.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a634419370e2dc7673a6754385c9c43b.npz

.

Average throughput: 101.7MiB/s

[val] downloading 461/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141220_2112_HARP4943_NOAA12240.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141220_2112_HARP4943_NOAA12240.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8c301ac015262a82226a9e173ed47971.npz

.

Average throughput: 158.3MiB/s

[val] downloading 462/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141203_1448_HARP4872_NOAA12221.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141203_1448_HARP4872_NOAA12221.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a1e24cbfcf902b18cc4332ad98a74fb6.npz

.

Average throughput: 119.2MiB/s

[val] downloading 463/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140215_1224_HARP3730_NOAA11976.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140215_1224_HARP3730_NOAA11976.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/42d4b85275bcd5a2f3f11e6d776508f4.npz

.

Average throughput: 158.6MiB/s

[val] downloading 464/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141103_1900_HARP4750_NOAA12199.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141103_1900_HARP4750_NOAA12199.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/806ea30000d9eb8dcff91acf2e3fd771.npz

.

Average throughput: 157.5MiB/s

[val] downloading 465/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140621_2200_HARP4256_NOAA12094.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140621_2200_HARP4256_NOAA12094.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e8467b71024854855ccfdad06a2162ac.npz

.

Average throughput: 100.7MiB/s

[val] downloading 466/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140201_0400_HARP3700_NOAA11969.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140201_0400_HARP3700_NOAA11969.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f8e19ed497bcf34f71dc6c25574c36e2.npz

.

Average throughput: 164.4MiB/s

[val] downloading 467/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140325_1936_HARP3894_NOAA12017.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140325_1936_HARP3894_NOAA12017.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/403e9079d171914f2e2e690669ad3386.npz

.

Average throughput: 126.4MiB/s

[val] downloading 468/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140422_1048_HARP4040_NOAA12044.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140422_1048_HARP4040_NOAA12044.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d5fba32cad89fc9886901edeccc50d90.npz

.

Average throughput: 89.4MiB/s

[val] downloading 469/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140518_0024_HARP4133_NOAA12063.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140518_0024_HARP4133_NOAA12063.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a067c6fcdd0d1a0025991d645b56a194.npz

.

Average throughput: 128.0MiB/s

[val] downloading 470/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140712_0312_HARP4344_NOAA12113.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140712_0312_HARP4344_NOAA12113.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3856e313e1e2c3c14a93fc54abd249fa.npz

.

Average throughput: 89.1MiB/s

[val] downloading 471/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140610_0148_HARP4205_NOAA12082.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140610_0148_HARP4205_NOAA12082.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/187e2048b9da57a3a911d381120d5780.npz

.

Average throughput: 133.6MiB/s

[val] downloading 472/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140101_1224_HARP3542_NOAA11937.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140101_1224_HARP3542_NOAA11937.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/363b8efb14f26c48f5b6ce14d54c593e.npz

.

Average throughput: 80.8MiB/s

[val] downloading 473/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141031_2124_HARP4733_NOAA12196.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141031_2124_HARP4733_NOAA12196.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f7767972233b9e821ce374501b75e350.npz

.

Average throughput: 82.1MiB/s

[val] downloading 474/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140801_2012_HARP4390_NOAA12124.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140801_2012_HARP4390_NOAA12124.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5ce3e38536980d1fbf833f6b1dee2489.npz

.

Average throughput: 167.2MiB/s

[val] downloading 475/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140609_0948_HARP4205_NOAA12082.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140609_0948_HARP4205_NOAA12082.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1ab9152cfb084950dd0f5b9717bb53df.npz

.

Average throughput: 91.8MiB/s

[val] downloading 476/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140113_1600_HARP3604_NOAA11950.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140113_1600_HARP3604_NOAA11950.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d5f05377fb059a780396aca520c94da5.npz

.

Average throughput: 94.2MiB/s

[val] downloading 477/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141026_0548_HARP4718_NOAA12194.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141026_0548_HARP4718_NOAA12194.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/813cd02d1b060a9712d41fdb044c5da3.npz

.

Average throughput: 196.7MiB/s

[val] downloading 478/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141202_2300_HARP4874_NOAA12222.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141202_2300_HARP4874_NOAA12222.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0b57cff50d72d5efd88a1ef5a0b73dc8.npz

.

Average throughput: 147.6MiB/s

[val] downloading 479/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140120_1600_HARP3648_NOAA11957.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140120_1600_HARP3648_NOAA11957.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/680d33a2c41addfa9f530aaafcd90ba8.npz

.

Average throughput: 145.2MiB/s

[val] downloading 480/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141108_0400_HARP4784_NOAA12206.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141108_0400_HARP4784_NOAA12206.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b0cb98eaacd0697747d6bdbc97cc0075.npz

.

Average throughput: 145.8MiB/s

[val] downloading 481/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140403_0824_HARP3912_NOAA12021.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140403_0824_HARP3912_NOAA12021.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9753623a24d349b6cd118b8a60d9824c.npz

.

Average throughput: 103.8MiB/s

[val] downloading 482/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140417_2136_HARP4022_NOAA12039.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140417_2136_HARP4022_NOAA12039.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b64acd2dc9d8e9d214b46dddcd7c9226.npz

.

Average throughput: 67.3MiB/s

[val] downloading 483/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140807_1536_HARP4422_NOAA12133.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140807_1536_HARP4422_NOAA12133.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/bf0a137054452ce156873d871b98f233.npz

.

Average throughput: 74.5MiB/s

[val] downloading 484/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141118_0112_HARP4817_NOAA12113.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141118_0112_HARP4817_NOAA12113.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4f992208d2a2abf50fec8590ffc10d14.npz

.

Average throughput: 76.9MiB/s

[val] downloading 485/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141102_1900_HARP4764_NOAA12203.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141102_1900_HARP4764_NOAA12203.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/68c29a5218cf1a69ddf11bd1fd947b5a.npz

.

Average throughput: 138.3MiB/s

[val] downloading 486/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140608_0248_HARP4197_NOAA12080.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140608_0248_HARP4197_NOAA12080.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/dd832ed50bba421f6d83939a605b7bb4.npz

.

Average throughput: 141.8MiB/s

[val] downloading 487/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140127_0136_HARP3647_NOAA11958.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140127_0136_HARP3647_NOAA11958.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/bd120d64a4b18b5eb1a236b7e800421d.npz

.

Average throughput: 125.0MiB/s

[val] downloading 488/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141231_2136_HARP5005_NOAA12256.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141231_2136_HARP5005_NOAA12256.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a9fcca0a9a9a946365f69f23fc653fa9.npz

.

Average throughput: 124.2MiB/s

[val] downloading 489/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141114_2012_HARP4816_NOAA12210.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141114_2012_HARP4816_NOAA12210.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/711da24d329ebd82aa023147ee4bb43c.npz

.

Average throughput: 135.9MiB/s

[val] downloading 490/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141201_0036_HARP4874_NOAA12222.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141201_0036_HARP4874_NOAA12222.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1e841130d89d2e34f4ec0dc2ffe1f580.npz

.

Average throughput: 142.2MiB/s

[val] downloading 491/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140213_0212_HARP3721_NOAA11974.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140213_0212_HARP3721_NOAA11974.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3fc343aa71b1f336fea604ca1f584950.npz

.

Average throughput: 164.1MiB/s

[val] downloading 492/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140403_0900_HARP3957_NOAA12029.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140403_0900_HARP3957_NOAA12029.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/52f7f6515ddba2e03bfcc2cb0bf852bd.npz

.

Average throughput: 136.3MiB/s

[val] downloading 493/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141221_0312_HARP4955_NOAA12249.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141221_0312_HARP4955_NOAA12249.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cebc36f4c0fcce1e1994bf832988620e.npz

.

Average throughput: 30.9MiB/s

[val] downloading 494/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141010_1448_HARP4661_NOAA12184.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141010_1448_HARP4661_NOAA12184.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fc373aafa75e31c57ad9085b24d9c5cf.npz

.

Average throughput: 81.5MiB/s

[val] downloading 495/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140417_1912_HARP3999_NOAA12036.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140417_1912_HARP3999_NOAA12036.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5ad42f149f6b695a162aa07157b5186b.npz

.

Average throughput: 89.3MiB/s

[val] downloading 496/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140327_1800_HARP3879_NOAA12014.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140327_1800_HARP3879_NOAA12014.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/25f6c0844e54e02751f1c4675262a6ec.npz



Average throughput: 178.1MiB/s

[val] downloading 497/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140622_0424_HARP4256_NOAA12094.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140622_0424_HARP4256_NOAA12094.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f87058543bf597a45e5fa72f9f0ba40a.npz

.

Average throughput: 194.4MiB/s

[val] downloading 498/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140206_2048_HARP3703_NOAA11970.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140206_2048_HARP3703_NOAA11970.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0b747e17359add6ebe98f505e450ae6c.npz

.

Average throughput: 117.0MiB/s

[val] downloading 499/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141117_0836_HARP4814_NOAA12212.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141117_0836_HARP4814_NOAA12212.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/21377738020fa09011d12cd849f65c8d.npz

.

Average throughput: 94.7MiB/s

[val] downloading 500/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141202_1312_HARP4872_NOAA12221.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141202_1312_HARP4872_NOAA12221.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/223a413663fc717a05523a2fef1015b4.npz

.

Average throughput: 171.3MiB/s

[val] cached/checked 500/825 files | elapsed 12.9 min
[val] downloading 501/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140325_0024_HARP3874_NOAA12013.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140325_0024_HARP3874_NOAA12013.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/56653f94cedd8c1dd4006443a959db15.npz

.

Average throughput: 163.2MiB/s

[val] downloading 502/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141009_1448_HARP4640_NOAA12183.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141009_1448_HARP4640_NOAA12183.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f1b12b38ef3990576c916b43301d12ae.npz

.

Average throughput: 142.4MiB/s

[val] downloading 503/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141221_1712_HARP4954_NOAA12243.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141221_1712_HARP4954_NOAA12243.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a554d2416b3ee074d5bfc4bbd15d40a5.npz

.

Average throughput: 99.9MiB/s

[val] downloading 504/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140418_1036_HARP4000_NOAA12035.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140418_1036_HARP4000_NOAA12035.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2a22576c9b1a927e9e6a8bd93f591b02.npz

.

Average throughput: 169.9MiB/s

[val] downloading 505/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140228_1124_HARP3793_NOAA11990.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140228_1124_HARP3793_NOAA11990.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/725e8505ed704eefbfcedaa58e0b4ccf.npz

.

Average throughput: 67.8MiB/s

[val] downloading 506/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141220_1848_HARP4954_NOAA12243.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141220_1848_HARP4954_NOAA12243.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9b5cfd12f51da856cb6ec86e2f704ee3.npz

.

Average throughput: 68.3MiB/s

[val] downloading 507/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141212_1500_HARP4908_NOAA12232.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141212_1500_HARP4908_NOAA12232.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0c4ca85d0795b86b29cdee8a7e951430.npz

.

Average throughput: 199.8MiB/s

[val] downloading 508/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141218_2100_HARP4941_NOAA12241.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141218_2100_HARP4941_NOAA12241.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3f6a085b5e628cc7df2e2fceadf1312b.npz

.

Average throughput: 137.4MiB/s

[val] downloading 509/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140207_0648_HARP3703_NOAA11970.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140207_0648_HARP3703_NOAA11970.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a5fbf55f85aa389a2fd9eb348a55f479.npz

.

Average throughput: 152.6MiB/s

[val] downloading 510/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141103_0448_HARP4751_NOAA12200.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141103_0448_HARP4751_NOAA12200.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/639d0c24f87ba185ef02bca28987a7b2.npz

.

Average throughput: 45.7MiB/s

[val] downloading 511/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140212_1200_HARP3721_NOAA11974.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140212_1200_HARP3721_NOAA11974.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7628ad135ab5cb5f71a6178231f86631.npz

.

Average throughput: 112.4MiB/s

[val] downloading 512/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140810_0900_HARP4424_NOAA12134.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140810_0900_HARP4424_NOAA12134.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/56f51d594a2cea347e4b1820f1e2a7fd.npz

.

Average throughput: 172.0MiB/s

[val] downloading 513/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141106_1000_HARP4751_NOAA12200.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141106_1000_HARP4751_NOAA12200.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/108a8c5d1873367190bdabeacf8b35b1.npz

.

Average throughput: 79.2MiB/s

[val] downloading 514/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141105_1136_HARP4751_NOAA12200.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141105_1136_HARP4751_NOAA12200.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/49318f14002408c3b8bb3f15ed5e7900.npz

.

Average throughput: 102.0MiB/s

[val] downloading 515/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140131_2312_HARP3700_NOAA11969.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140131_2312_HARP3700_NOAA11969.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/26374922d441b35857915be177d583c8.npz

.

Average throughput: 90.1MiB/s

[val] downloading 516/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140209_2100_HARP3721_NOAA11974.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140209_2100_HARP3721_NOAA11974.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b1695d3f789ac12239984929d9c89f64.npz

.

Average throughput: 112.0MiB/s

[val] downloading 517/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140326_1312_HARP3894_NOAA12017.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140326_1312_HARP3894_NOAA12017.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a2a1771a15a362c1be8b8d154e86f046.npz

.

Average throughput: 118.4MiB/s

[val] downloading 518/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141209_1000_HARP4915_NOAA12233.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141209_1000_HARP4915_NOAA12233.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e24fdc5dad5687b498f1e313c73bd478.npz

.

Average throughput: 156.3MiB/s

[val] downloading 519/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140213_0700_HARP3721_NOAA11974.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140213_0700_HARP3721_NOAA11974.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2394c82330c9e3190a3e6a04a00f0bb1.npz

.

Average throughput: 92.4MiB/s

[val] downloading 520/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140604_2324_HARP4201_NOAA12084.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140604_2324_HARP4201_NOAA12084.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/51dde4556ff67c203d139471fe23338a.npz

.

Average throughput: 146.7MiB/s

[val] downloading 521/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140804_0336_HARP4398_NOAA12128.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140804_0336_HARP4398_NOAA12128.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/377691b853078a6060c2f519f61b6e78.npz

.

Average throughput: 172.2MiB/s

[val] downloading 522/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140609_1848_HARP4197_NOAA12080.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140609_1848_HARP4197_NOAA12080.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cba916d718ee8a7ef453248ac845ce63.npz

.

Average throughput: 163.8MiB/s

[val] downloading 523/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141212_2300_HARP4908_NOAA12232.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141212_2300_HARP4908_NOAA12232.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cb94d84466b4f83b4045ce4538cecab2.npz

.

Average throughput: 164.1MiB/s

[val] downloading 524/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140621_1400_HARP4256_NOAA12094.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140621_1400_HARP4256_NOAA12094.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a907222d03b3120d1b2a39e25089efad.npz

.

Average throughput: 116.1MiB/s

[val] downloading 525/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140520_0648_HARP4133_NOAA12063.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140520_0648_HARP4133_NOAA12063.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/57f8b128b421fd94109e0dc4a4848c64.npz

.

Average throughput: 105.7MiB/s

[val] downloading 526/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140302_0300_HARP3806_NOAA11992.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140302_0300_HARP3806_NOAA11992.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b90cd896e55e2e06c05f2995cdf61d2b.npz

.

Average throughput: 77.7MiB/s

[val] downloading 527/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140516_2236_HARP4131_NOAA12066.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140516_2236_HARP4131_NOAA12066.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/eb45ebfd9e0505915cc4a0ece20fcbc9.npz

.

Average throughput: 189.6MiB/s

[val] downloading 528/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140228_1936_HARP3784_NOAA11987.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140228_1936_HARP3784_NOAA11987.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f4f796b7e545f128eba23212229187b0.npz

.

Average throughput: 145.2MiB/s

[val] downloading 529/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140425_2336_HARP4040_NOAA12044.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140425_2336_HARP4040_NOAA12044.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7a74de61197cdc0154f394dd09951b0f.npz

.

Average throughput: 117.9MiB/s

[val] downloading 530/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140117_2336_HARP3635_NOAA11961.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140117_2336_HARP3635_NOAA11961.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b1249b591de6276436c0a339ebc2148a.npz

.

Average throughput: 117.5MiB/s

[val] downloading 531/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140406_0412_HARP3942_NOAA12026.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140406_0412_HARP3942_NOAA12026.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5159b5f0db5144f731c64b044aae5461.npz

.

Average throughput: 161.0MiB/s

[val] downloading 532/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140405_0548_HARP3957_NOAA12029.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140405_0548_HARP3957_NOAA12029.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/80f17729211b1fb704574a2a17f327a5.npz

.

Average throughput: 131.9MiB/s

[val] downloading 533/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140515_1424_HARP4111_NOAA12058.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140515_1424_HARP4111_NOAA12058.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7cf84812c133775a61cc622142acba5b.npz

.

Average throughput: 183.2MiB/s

[val] downloading 534/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141218_1348_HARP4942_NOAA12239.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141218_1348_HARP4942_NOAA12239.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/90e5fcb061a7f6b36ee45453c49422d1.npz

..

Average throughput: 42.2MiB/s

[val] downloading 535/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140202_1136_HARP3686_NOAA11967.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140202_1136_HARP3686_NOAA11967.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/74f795a43cdae99e861e5cfe8c0192c8.npz

.

Average throughput: 170.8MiB/s

[val] downloading 536/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141118_2224_HARP4817_NOAA12113.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141118_2224_HARP4817_NOAA12113.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e07727eb265631ee401923011b6be48f.npz

.

Average throughput: 116.6MiB/s

[val] downloading 537/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140517_0324_HARP4133_NOAA12063.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140517_0324_HARP4133_NOAA12063.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/43398365b83cf354313aa81c8e822725.npz

.

Average throughput: 179.4MiB/s

[val] downloading 538/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140201_2248_HARP3686_NOAA11967.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140201_2248_HARP3686_NOAA11967.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/176f187e14e74dcb9b00a7cab35ac243.npz

.

Average throughput: 135.5MiB/s

[val] downloading 539/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141128_1048_HARP4864_NOAA12218.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141128_1048_HARP4864_NOAA12218.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8b66dbc117f0a3a507dccf292bfd2dbf.npz

.

Average throughput: 64.8MiB/s

[val] downloading 540/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140522_1400_HARP4152_NOAA12069.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140522_1400_HARP4152_NOAA12069.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cf4618f81289998cdfe9846a68271d1c.npz

.

Average throughput: 169.1MiB/s

[val] downloading 541/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140101_0836_HARP3557_NOAA11938.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140101_0836_HARP3557_NOAA11938.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/23672f4d413ee7681fce1642b3b9bab2.npz

.

Average throughput: 147.3MiB/s

[val] downloading 542/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140215_1036_HARP3740_NOAA11977.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140215_1036_HARP3740_NOAA11977.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/27fec3f421a5631541fc308ac9621e3d.npz

.

Average throughput: 106.8MiB/s

[val] downloading 543/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140320_2124_HARP3856_NOAA12008.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140320_2124_HARP3856_NOAA12008.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6e9960e25066d6066cd62d9a2fbdbeee.npz

.

Average throughput: 175.4MiB/s

[val] downloading 544/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141221_1224_HARP4954_NOAA12243.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141221_1224_HARP4954_NOAA12243.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b1e46cfa75db554a7a71c2b940566e79.npz

.

Average throughput: 108.0MiB/s

[val] downloading 545/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140702_0248_HARP4302_NOAA12105.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140702_0248_HARP4302_NOAA12105.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a5ae48ad75c40b698b4632520803ffa4.npz

.

Average throughput: 107.9MiB/s

[val] downloading 546/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140303_1536_HARP3804_NOAA11991.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140303_1536_HARP3804_NOAA11991.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/383181c4f234b3a50b6102ab42da4cd3.npz

.

Average throughput: 80.4MiB/s

[val] downloading 547/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140607_1848_HARP4190_NOAA12079.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140607_1848_HARP4190_NOAA12079.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b9b5c65fe904a3f9ace35c9d13ca21ab.npz

..

Average throughput: 21.6MiB/s

[val] downloading 548/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141222_0448_HARP4955_NOAA12249.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141222_0448_HARP4955_NOAA12249.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/bf8e23009ca562fa7f30b3dd05c51fc0.npz

.

Average throughput: 64.3MiB/s

[val] downloading 549/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140114_2248_HARP3604_NOAA11950.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140114_2248_HARP3604_NOAA11950.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/db79f1a8d05f060f4a6181a2efecf4d4.npz

.

Average throughput: 60.5MiB/s

[val] downloading 550/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140225_1548_HARP3779_NOAA11986.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140225_1548_HARP3779_NOAA11986.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e025a5c18f66e0d5085a4d8ca1a98a7d.npz

.

Average throughput: 112.1MiB/s

[val] downloading 551/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141028_1600_HARP4726_NOAA12195.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141028_1600_HARP4726_NOAA12195.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6eb20e041ab1ba30003337f6c952428d.npz

.

Average throughput: 130.3MiB/s

[val] downloading 552/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140207_1136_HARP3703_NOAA11970.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140207_1136_HARP3703_NOAA11970.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1345222655468a72ba5a8d42db3910ab.npz

.

Average throughput: 128.5MiB/s

[val] downloading 553/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140729_2336_HARP4379_NOAA12121.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140729_2336_HARP4379_NOAA12121.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/725d6c7ac51337815f042ff8eb11a3ae.npz

.

Average throughput: 156.0MiB/s

[val] downloading 554/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141124_1900_HARP4868_NOAA12219.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141124_1900_HARP4868_NOAA12219.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/88d72b5e3040386d2947da6cc7c74a43.npz

.

Average throughput: 84.6MiB/s

[val] downloading 555/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140713_0948_HARP4351_NOAA12114.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140713_0948_HARP4351_NOAA12114.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4b7ee2352798c42d4101d88e8a7e5348.npz

.

Average throughput: 91.9MiB/s

[val] downloading 556/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140628_2048_HARP4272_NOAA12096.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140628_2048_HARP4272_NOAA12096.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cb370259aabb95527c40e0282873104c.npz

.

Average throughput: 72.5MiB/s

[val] downloading 557/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140113_2048_HARP3604_NOAA11950.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140113_2048_HARP3604_NOAA11950.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0ba625f7bef156d133339fa9a5b6080f.npz



Average throughput: 197.1MiB/s

[val] downloading 558/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140513_1648_HARP4097_NOAA12055.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140513_1648_HARP4097_NOAA12055.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/172f25e2082524679873424d8a8b0aa3.npz

.

Average throughput: 84.2MiB/s

[val] downloading 559/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140630_0348_HARP4302_NOAA12105.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140630_0348_HARP4302_NOAA12105.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/957e65b75100e49a5395dd8f5c0c53cb.npz

.

Average throughput: 129.6MiB/s

[val] downloading 560/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140423_0136_HARP4040_NOAA12044.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140423_0136_HARP4040_NOAA12044.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b7c2898deb250b0c5590fe99323d210b.npz

.

Average throughput: 110.2MiB/s

[val] downloading 561/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140325_2300_HARP3874_NOAA12013.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140325_2300_HARP3874_NOAA12013.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cc3f867fdfb2da8f1610ceee38ac1ace.npz

.

Average throughput: 81.2MiB/s

[val] downloading 562/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140416_0000_HARP4011_NOAA12040.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140416_0000_HARP4011_NOAA12040.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ba1dfe82c00f8b4ed7ec186c10cefea1.npz

.

Average throughput: 133.3MiB/s

[val] downloading 563/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140805_2124_HARP4396_NOAA12127.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140805_2124_HARP4396_NOAA12127.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2323420361f09233a9a2e68e6732627f.npz

.

Average throughput: 91.0MiB/s

[val] downloading 564/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140110_1136_HARP3563_NOAA11943.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140110_1136_HARP3563_NOAA11943.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f02966289466bcdabc4be9f88619299a.npz



Average throughput: 196.1MiB/s

[val] downloading 565/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141003_1136_HARP4623_NOAA12181.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141003_1136_HARP4623_NOAA12181.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3300c1c7f151b4393c959e9cfc4c499e.npz

.

Average throughput: 167.6MiB/s

[val] downloading 566/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140216_0412_HARP3740_NOAA11977.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140216_0412_HARP3740_NOAA11977.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/57016a13e5e149999f28686106ef8f5b.npz

..

Average throughput: 47.3MiB/s

[val] downloading 567/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140521_0500_HARP4138_NOAA12065.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140521_0500_HARP4138_NOAA12065.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/91952ccf3cd4069e375bcac3c0b84e37.npz

.

Average throughput: 54.4MiB/s

[val] downloading 568/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140509_2148_HARP4092_NOAA12053.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140509_2148_HARP4092_NOAA12053.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6c68c48c273b0661f5ca697f50ee3304.npz

.

Average throughput: 64.9MiB/s

[val] downloading 569/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141023_2300_HARP4698_NOAA12192.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141023_2300_HARP4698_NOAA12192.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/50e5778759ccf6a2938dd103254e5c5f.npz

.

Average throughput: 188.2MiB/s

[val] downloading 570/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140608_0236_HARP4201_NOAA12084.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140608_0236_HARP4201_NOAA12084.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/feb7aada19845309fad6d6cd22f95d70.npz

.

Average throughput: 63.9MiB/s

[val] downloading 571/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141202_0512_HARP4872_NOAA12221.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141202_0512_HARP4872_NOAA12221.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9f9fba6e1f2003b088c68923837f79a6.npz

.

Average throughput: 84.3MiB/s

[val] downloading 572/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140104_0248_HARP3569_NOAA11945.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140104_0248_HARP3569_NOAA11945.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e0de402818534770cdf5b15c7c8b4a3a.npz

.

Average throughput: 146.5MiB/s

[val] downloading 573/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141002_0936_HARP4610_NOAA12177.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141002_0936_HARP4610_NOAA12177.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c28e792e2e809a775b3da252020d2eb7.npz

.

Average throughput: 178.5MiB/s

[val] downloading 574/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140228_2112_HARP3784_NOAA11987.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140228_2112_HARP3784_NOAA11987.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0af1c849b61cf5ba79ce4881cccfbe8a.npz

.

Average throughput: 213.9MiB/s

[val] downloading 575/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140607_1048_HARP4186_NOAA12077.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140607_1048_HARP4186_NOAA12077.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/774bebaaa328eb384db3dcce1ccccb1f.npz

.

Average throughput: 133.0MiB/s

[val] downloading 576/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140615_1648_HARP4228_NOAA12090.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140615_1648_HARP4228_NOAA12090.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3329fe31ce7fa74cd64854b622898302.npz

.

Average throughput: 113.1MiB/s

[val] downloading 577/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140312_1524_HARP3836_NOAA12002.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140312_1524_HARP3836_NOAA12002.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8fd11685cd6718374c22e7620f8833e8.npz

.

Average throughput: 115.3MiB/s

[val] downloading 578/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140507_0024_HARP4088_NOAA12052.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140507_0024_HARP4088_NOAA12052.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4909defa65459087b84f3eb9e67ac9ea.npz

.

Average throughput: 148.3MiB/s

[val] downloading 579/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141214_0348_HARP4908_NOAA12232.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141214_0348_HARP4908_NOAA12232.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4e26b7e618d323bd7b2b0107ddb11202.npz

.

Average throughput: 132.0MiB/s

[val] downloading 580/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140531_1112_HARP4166_NOAA12075.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140531_1112_HARP4166_NOAA12075.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/422483f6857ea23bb18eb0add3074a0a.npz

.

Average throughput: 99.8MiB/s

[val] downloading 581/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141115_0548_HARP4816_NOAA12210.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141115_0548_HARP4816_NOAA12210.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ac7d8b52e3279d533f2a70d269eaae8f.npz

.

Average throughput: 94.0MiB/s

[val] downloading 582/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140607_0600_HARP4197_NOAA12080.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140607_0600_HARP4197_NOAA12080.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/293d3c856efb5cadc38088aa196840ca.npz

.

Average throughput: 142.5MiB/s

[val] downloading 583/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140621_1200_HARP4252_NOAA12093.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140621_1200_HARP4252_NOAA12093.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cb9e048afa85e4154ba19ca9e539a1fe.npz

.

Average throughput: 71.0MiB/s

[val] downloading 584/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140312_2236_HARP3824_NOAA11998.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140312_2236_HARP3824_NOAA11998.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/082ac250b3682eb34955693b81d12e17.npz

.

Average throughput: 58.3MiB/s

[val] downloading 585/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140326_0336_HARP3894_NOAA12017.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140326_0336_HARP3894_NOAA12017.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/db7eab2b87030a0b4041ddd0a8f0d5d0.npz

.

Average throughput: 55.4MiB/s

[val] downloading 586/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140930_2048_HARP4623_NOAA12181.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140930_2048_HARP4623_NOAA12181.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ac692fb7c8359bdd15b376d1910c74a8.npz

.

Average throughput: 95.2MiB/s

[val] downloading 587/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140711_2324_HARP4328_NOAA12111.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140711_2324_HARP4328_NOAA12111.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f631aafdde666e688bb1ac673808a4ff.npz

.

Average throughput: 192.1MiB/s

[val] downloading 588/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140806_1500_HARP4424_NOAA12134.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140806_1500_HARP4424_NOAA12134.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f7b7555575de4a24531979f485c5a26f.npz

.

Average throughput: 174.6MiB/s

[val] downloading 589/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141008_1224_HARP4640_NOAA12183.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141008_1224_HARP4640_NOAA12183.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3bd25f4f38a9b7133277c1af00d494bc.npz

.

Average throughput: 141.0MiB/s

[val] downloading 590/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140315_1524_HARP3853_NOAA12009.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140315_1524_HARP3853_NOAA12009.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2f9dd14fe8f8817ca9d96d23b4d2972c.npz

.

Average throughput: 89.8MiB/s

[val] downloading 591/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140209_1300_HARP3711_NOAA11971.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140209_1300_HARP3711_NOAA11971.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e92c4fa0f9b496b6ab95fc7afd8e23b7.npz

.

Average throughput: 90.1MiB/s

[val] downloading 592/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140613_0312_HARP4231_NOAA12089.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140613_0312_HARP4231_NOAA12089.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/35012ca9ad53ae1b6145c1d3097c3595.npz

.

Average throughput: 56.3MiB/s

[val] downloading 593/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140426_1200_HARP4042_NOAA12045.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140426_1200_HARP4042_NOAA12045.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c141178f7eb688f7d5e304f20ed89e93.npz

.

Average throughput: 102.1MiB/s

[val] downloading 594/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141112_0524_HARP4781_NOAA12205.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141112_0524_HARP4781_NOAA12205.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b5ff10bb246b2d3ac440488563f36980.npz

.

Average throughput: 202.2MiB/s

[val] downloading 595/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141005_0024_HARP4623_NOAA12181.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141005_0024_HARP4623_NOAA12181.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7b9f5ae32136552567eff3ba859d8d4e.npz

.

Average throughput: 89.9MiB/s

[val] downloading 596/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140501_1536_HARP4075_NOAA12050.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140501_1536_HARP4075_NOAA12050.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5cacc21dd9fa4f142e88a8472c160704.npz

.

Average throughput: 93.1MiB/s

[val] downloading 597/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141218_0436_HARP4941_NOAA12241.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141218_0436_HARP4941_NOAA12241.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/55cd3bf44fe87bf08e4c1cae5932abf1.npz

.

Average throughput: 156.0MiB/s

[val] downloading 598/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140318_0836_HARP3877_NOAA12011.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140318_0836_HARP3877_NOAA12011.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/99a8b29745963b81b9a9402a5ee654e9.npz

.

Average throughput: 92.6MiB/s

[val] downloading 599/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140302_2224_HARP3804_NOAA11991.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140302_2224_HARP3804_NOAA11991.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/de102ecf7de1a0b0a0f48f8c99cdaeb2.npz

.

Average throughput: 87.5MiB/s

[val] downloading 600/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141213_1324_HARP4908_NOAA12232.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141213_1324_HARP4908_NOAA12232.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6545a07c72df133ddbc4d581bde8e8ea.npz

.

Average throughput: 69.0MiB/s

[val] cached/checked 600/825 files | elapsed 15.5 min
[val] downloading 601/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140618_1812_HARP4225_NOAA12087.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140618_1812_HARP4225_NOAA12087.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5adca448cd8786d580fbebb81f720d9f.npz

.

Average throughput: 104.7MiB/s

[val] downloading 602/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140212_0048_HARP3721_NOAA11974.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140212_0048_HARP3721_NOAA11974.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5d17db694657b390ea59a80e8d1413fa.npz

.

Average throughput: 78.9MiB/s

[val] downloading 603/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141025_0112_HARP4698_NOAA12192.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141025_0112_HARP4698_NOAA12192.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/efba8dfe1ccd2963d9b1caecf3dfd1d5.npz

.

Average throughput: 152.0MiB/s

[val] downloading 604/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140729_2024_HARP4379_NOAA12121.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140729_2024_HARP4379_NOAA12121.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f14439a202679c9b4d68681daecd3e1d.npz

.

Average throughput: 122.6MiB/s

[val] downloading 605/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141002_1112_HARP4610_NOAA12177.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141002_1112_HARP4610_NOAA12177.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1c52d5333f26bf962cfc9c12482733b1.npz

.

Average throughput: 183.7MiB/s

[val] downloading 606/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140501_1736_HARP4075_NOAA12050.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140501_1736_HARP4075_NOAA12050.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0e648fcde9718ed165525a2e986ed58a.npz

.

Average throughput: 74.9MiB/s

[val] downloading 607/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141214_0400_HARP4920_NOAA12235.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141214_0400_HARP4920_NOAA12235.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7c7d9e9559ff960fa5cbf666a38d1da8.npz

.

Average throughput: 151.2MiB/s

[val] downloading 608/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140508_0100_HARP4092_NOAA12053.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140508_0100_HARP4092_NOAA12053.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6e4ebf5a1a74cb2d408df700fc9a75d2.npz

.

Average throughput: 148.2MiB/s

[val] downloading 609/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140730_0712_HARP4383_NOAA12123.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140730_0712_HARP4383_NOAA12123.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/05f5cd6891bc803a3763471256e19a13.npz

.

Average throughput: 95.0MiB/s

[val] downloading 610/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140205_1000_HARP3686_NOAA11967.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140205_1000_HARP3686_NOAA11967.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1ffdd728ec411516524a1ca5b8a05716.npz

.

Average throughput: 105.8MiB/s

[val] downloading 611/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140810_1836_HARP4424_NOAA12134.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140810_1836_HARP4424_NOAA12134.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b504b6934737c313d9e9bd92fb2143b5.npz

.

Average throughput: 61.2MiB/s

[val] downloading 612/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140509_0036_HARP4088_NOAA12052.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140509_0036_HARP4088_NOAA12052.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/381a1b1301c91560b6eb51d7b413d739.npz

.

Average throughput: 97.2MiB/s

[val] downloading 613/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141014_2036_HARP4667_NOAA12186.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141014_2036_HARP4667_NOAA12186.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/746fd12020f9ce750ca036525708cab9.npz

.

Average throughput: 171.5MiB/s

[val] downloading 614/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140517_1048_HARP4123_NOAA12061.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140517_1048_HARP4123_NOAA12061.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2e3b1a8bf8f41dba298d7d6185789818.npz

.

Average throughput: 159.4MiB/s

[val] downloading 615/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140312_1348_HARP3836_NOAA12002.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140312_1348_HARP3836_NOAA12002.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/39d428b4e61de948718fc7bb7fe85da7.npz

.

Average throughput: 119.6MiB/s

[val] downloading 616/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141008_1012_HARP4639_NOAA12182.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141008_1012_HARP4639_NOAA12182.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e109119bb24e7a3d97f07c244d46a01e.npz

.

Average throughput: 91.9MiB/s

[val] downloading 617/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140403_1212_HARP3957_NOAA12029.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140403_1212_HARP3957_NOAA12029.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3905bc44b8fc5a4715ee51a4c3562b0f.npz

.

Average throughput: 103.3MiB/s

[val] downloading 618/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140609_1536_HARP4197_NOAA12080.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140609_1536_HARP4197_NOAA12080.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c6a823906659e03cfed7ef1143ff92dc.npz

.

Average throughput: 73.2MiB/s

[val] downloading 619/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141104_2248_HARP4751_NOAA12200.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141104_2248_HARP4751_NOAA12200.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/defb6fa81a33899e22dc34deee6fcd37.npz

.

Average throughput: 166.1MiB/s

[val] downloading 620/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141021_0512_HARP4678_NOAA12187.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141021_0512_HARP4678_NOAA12187.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/264662746d26c02710f8d3542838b5a4.npz

.

Average throughput: 121.6MiB/s

[val] downloading 621/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140611_0736_HARP4197_NOAA12080.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140611_0736_HARP4197_NOAA12080.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1b28734a47f60d66b690ecd8a16ed3b9.npz

.

Average throughput: 160.0MiB/s

[val] downloading 622/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140518_2112_HARP4133_NOAA12063.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140518_2112_HARP4133_NOAA12063.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/eafef2cc178c46704ff13d2ccb12c74c.npz

.

Average throughput: 168.1MiB/s

[val] downloading 623/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140516_1124_HARP4131_NOAA12066.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140516_1124_HARP4131_NOAA12066.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b7a70954d6ecf4ef8b690bd663e3c8c8.npz

.

Average throughput: 147.8MiB/s

[val] downloading 624/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140329_2348_HARP3901_NOAA12020.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140329_2348_HARP3901_NOAA12020.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/68696b49ca68317168f19d05bd4e3780.npz

.

Average throughput: 171.1MiB/s

[val] downloading 625/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141117_0736_HARP4817_NOAA12113.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141117_0736_HARP4817_NOAA12113.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0408867af7bfd8a1558c0b5a61b6e9b9.npz

.

Average throughput: 119.2MiB/s

[val] downloading 626/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140107_0324_HARP3580_NOAA11946.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140107_0324_HARP3580_NOAA11946.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4b4f545fcef728ce965694b6e6e21757.npz

.

Average throughput: 144.8MiB/s

[val] downloading 627/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140306_0448_HARP3804_NOAA11991.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140306_0448_HARP3804_NOAA11991.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0936312475c70c88031c11224f039748.npz

.

Average throughput: 171.3MiB/s

[val] downloading 628/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140726_1048_HARP4383_NOAA12123.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140726_1048_HARP4383_NOAA12123.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/04b7e22ad352e39d4614731fbe1f7b1b.npz

.

Average throughput: 89.5MiB/s

[val] downloading 629/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141018_2000_HARP4711_NOAA12193.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141018_2000_HARP4711_NOAA12193.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0fd933ef7dd1cb3c052817293f11e07e.npz

.

Average throughput: 96.0MiB/s

[val] downloading 630/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140318_1724_HARP3853_NOAA12009.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140318_1724_HARP3853_NOAA12009.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/60f1d5091095c5ce277899127b3ab308.npz

.

Average throughput: 146.3MiB/s

[val] downloading 631/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140318_1412_HARP3853_NOAA12009.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140318_1412_HARP3853_NOAA12009.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d98b956c4d6db2d137c73d84089ad2a4.npz

.

Average throughput: 160.8MiB/s

[val] downloading 632/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141226_2324_HARP4995_NOAA12250.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141226_2324_HARP4995_NOAA12250.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0525ffc93a945f23d3bbe236b4881513.npz

.

Average throughput: 102.2MiB/s

[val] downloading 633/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141101_0412_HARP4761_NOAA12202.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141101_0412_HARP4761_NOAA12202.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1bd5e613a8b80368aa39e9e0930b2190.npz

.

Average throughput: 101.0MiB/s

[val] downloading 634/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140209_0500_HARP3711_NOAA11971.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140209_0500_HARP3711_NOAA11971.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5307433221486bae3776ff34d8117668.npz



Average throughput: 153.6MiB/s

[val] downloading 635/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140809_1524_HARP4424_NOAA12134.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140809_1524_HARP4424_NOAA12134.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c14d8dd63109756d010db09936be4b55.npz

.

Average throughput: 143.5MiB/s

[val] downloading 636/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140113_0924_HARP3612_NOAA11951.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140113_0924_HARP3612_NOAA11951.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6cda27ba4f637e04a53be278e440e0eb.npz



Average throughput: 190.2MiB/s

[val] downloading 637/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141121_0112_HARP4817_NOAA12113.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141121_0112_HARP4817_NOAA12113.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/bb15262fbd346a84047906c0cde77ed8.npz

.

Average throughput: 77.0MiB/s

[val] downloading 638/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140701_2200_HARP4288_NOAA12100.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140701_2200_HARP4288_NOAA12100.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/05798c3562994114aafe7cddfe70ac32.npz

..

Average throughput: 164.7MiB/s

[val] downloading 639/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140114_2000_HARP3608_NOAA11953.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140114_2000_HARP3608_NOAA11953.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/119cc2de46ddef6bdad23fc4424639f7.npz



Average throughput: 162.5MiB/s

[val] downloading 640/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141023_0400_HARP4698_NOAA12192.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141023_0400_HARP4698_NOAA12192.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/933ea895ec4be7c18b5127deb26e1198.npz

.

Average throughput: 95.5MiB/s

[val] downloading 641/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140808_0248_HARP4422_NOAA12133.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140808_0248_HARP4422_NOAA12133.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/18c61239256f030ba620a96344089a59.npz

.

Average throughput: 55.1MiB/s

[val] downloading 642/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140613_1736_HARP4231_NOAA12089.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140613_1736_HARP4231_NOAA12089.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/024fcabba2a1b0cda02c860cd6e3f3fe.npz

.

Average throughput: 127.0MiB/s

[val] downloading 643/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140216_2324_HARP3740_NOAA11977.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140216_2324_HARP3740_NOAA11977.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a9bf29f92df87f2f09fbaf06b38d7425.npz

.

Average throughput: 182.4MiB/s

[val] downloading 644/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140610_1712_HARP4197_NOAA12080.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140610_1712_HARP4197_NOAA12080.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b036f8323f0efee376a77f04addd2dee.npz

.

Average throughput: 83.8MiB/s

[val] downloading 645/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141228_0848_HARP4969_NOAA12245.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141228_0848_HARP4969_NOAA12245.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/6ff6449b310170a430340b9e7623c568.npz

.

Average throughput: 82.2MiB/s

[val] downloading 646/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140714_1300_HARP4351_NOAA12114.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140714_1300_HARP4351_NOAA12114.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/68c8002718c0b3235bf03ecc905134fc.npz

.

Average throughput: 201.9MiB/s

[val] downloading 647/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140502_1424_HARP4075_NOAA12050.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140502_1424_HARP4075_NOAA12050.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5904bc05b5fb96e96a4edfe134b1f5ab.npz

.

Average throughput: 129.3MiB/s

[val] downloading 648/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140709_0048_HARP4328_NOAA12111.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140709_0048_HARP4328_NOAA12111.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e3352a749102216cf7fe4da659a55b39.npz

.

Average throughput: 152.2MiB/s

[val] downloading 649/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140418_0336_HARP4011_NOAA12040.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140418_0336_HARP4011_NOAA12040.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e78bb256f0780525c9887b2b4dbdae4b.npz

.

Average throughput: 140.0MiB/s

[val] downloading 650/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141031_0436_HARP4750_NOAA12199.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141031_0436_HARP4750_NOAA12199.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/079ee572ddbb67bd5abe1833ca08d511.npz

.

Average throughput: 87.8MiB/s

[val] downloading 651/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140630_1812_HARP4302_NOAA12105.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140630_1812_HARP4302_NOAA12105.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/97df1caf6ced7badbd5bfb6ff668c490.npz

.

Average throughput: 109.6MiB/s

[val] downloading 652/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140328_0700_HARP3894_NOAA12017.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140328_0700_HARP3894_NOAA12017.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3801dc79d6ecf4b7abf74086129840c9.npz



Average throughput: 176.9MiB/s

[val] downloading 653/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141107_1200_HARP4784_NOAA12206.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141107_1200_HARP4784_NOAA12206.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e2739da3051300c62ce1d2b8ff1f20ef.npz

.

Average throughput: 147.7MiB/s

[val] downloading 654/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141201_0824_HARP4872_NOAA12221.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141201_0824_HARP4872_NOAA12221.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a1233a3ce4ab5d4fbe072931ea42e89c.npz

.

Average throughput: 33.2MiB/s

[val] downloading 655/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140111_1448_HARP3586_NOAA11948.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140111_1448_HARP3586_NOAA11948.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2fb10ad746eb767c5e879385ad0e0811.npz

.

Average throughput: 61.2MiB/s

[val] downloading 656/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141215_1524_HARP4938_NOAA12238.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141215_1524_HARP4938_NOAA12238.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4285bd8b81d662fa5496b1576a613db0.npz

.

Average throughput: 153.8MiB/s

[val] downloading 657/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141007_0512_HARP4639_NOAA12182.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141007_0512_HARP4639_NOAA12182.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2dff6dfa926694d4f0a309d3509f504a.npz

.

Average throughput: 178.4MiB/s

[val] downloading 658/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141101_0100_HARP4761_NOAA12202.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141101_0100_HARP4761_NOAA12202.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/20b7f10437fb1745cd294a88d12b0224.npz

.

Average throughput: 94.2MiB/s

[val] downloading 659/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140619_0836_HARP4252_NOAA12093.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140619_0836_HARP4252_NOAA12093.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7f277cc46e5472a85bc866799ca1f3f1.npz

.

Average throughput: 106.2MiB/s

[val] downloading 660/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140730_0924_HARP4390_NOAA12124.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140730_0924_HARP4390_NOAA12124.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/819751e4d7487810f2973f3ece6e9326.npz

.

Average throughput: 129.6MiB/s

[val] downloading 661/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141228_0436_HARP4978_NOAA12247.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141228_0436_HARP4978_NOAA12247.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d80414cb8753a5203d6843e5aa2fb0c4.npz

.

Average throughput: 67.4MiB/s

[val] downloading 662/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141213_0036_HARP4921_NOAA12234.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141213_0036_HARP4921_NOAA12234.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f6f97c9c6d83dec781b370095f44c092.npz

.

Average throughput: 121.5MiB/s

[val] downloading 663/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141226_0400_HARP4995_NOAA12250.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141226_0400_HARP4995_NOAA12250.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e472ffad47f925a75e3386529c67039a.npz

.

Average throughput: 173.3MiB/s

[val] downloading 664/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140606_0100_HARP4201_NOAA12084.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140606_0100_HARP4201_NOAA12084.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/508268424f9ff3c8d0fb571b1171ba24.npz

.

Average throughput: 91.9MiB/s

[val] downloading 665/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140121_0536_HARP3658_NOAA11962.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140121_0536_HARP3658_NOAA11962.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/451b1977a0815ed9185129e0fe876562.npz

.

Average throughput: 182.8MiB/s

[val] downloading 666/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140516_0312_HARP4111_NOAA12058.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140516_0312_HARP4111_NOAA12058.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4614da48221d7a2e4c0cbbfc2b78a14d.npz

.

Average throughput: 163.6MiB/s

[val] downloading 667/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140131_0048_HARP3700_NOAA11969.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140131_0048_HARP3700_NOAA11969.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e8ca3c6f3e65e6be58b164ad8d18fe3d.npz

.

Average throughput: 135.7MiB/s

[val] downloading 668/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140109_1624_HARP3586_NOAA11948.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140109_1624_HARP3586_NOAA11948.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2f1716f949679ba34fd5ae5f6afc0fe2.npz

.

Average throughput: 173.2MiB/s

[val] downloading 669/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141201_0048_HARP4862_NOAA12217.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141201_0048_HARP4862_NOAA12217.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d6978235b6a0014cee2c4e23acc492e7.npz

.

Average throughput: 183.7MiB/s

[val] downloading 670/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141114_1524_HARP4816_NOAA12210.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141114_1524_HARP4816_NOAA12210.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1c5f15139dc65434214985992be9201d.npz

.

Average throughput: 56.9MiB/s

[val] downloading 671/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140123_1312_HARP3648_NOAA11957.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140123_1312_HARP3648_NOAA11957.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1e0cd8ed017f9c097935bef523817437.npz

.

Average throughput: 76.5MiB/s

[val] downloading 672/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140616_0536_HARP4228_NOAA12090.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140616_0536_HARP4228_NOAA12090.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/00bc26508d5537fc47e5086c68df4b18.npz

.

Average throughput: 131.3MiB/s

[val] downloading 673/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141122_0512_HARP4839_NOAA12215.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141122_0512_HARP4839_NOAA12215.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9175e828cd75bea83a63a87c514ffe25.npz

.

Average throughput: 101.0MiB/s

[val] downloading 674/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141218_2148_HARP4942_NOAA12239.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141218_2148_HARP4942_NOAA12239.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/00b4da6785cccf6d52559f4779167e34.npz



Average throughput: 195.9MiB/s

[val] downloading 675/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141218_1636_HARP4932_NOAA12236.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141218_1636_HARP4932_NOAA12236.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/42a295d0a0dd6ef80e14156a763d7430.npz

.

Average throughput: 67.0MiB/s

[val] downloading 676/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141218_1524_HARP4942_NOAA12239.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141218_1524_HARP4942_NOAA12239.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/87e8a5bca506c57b4ff8ed379f2183bf.npz

.

Average throughput: 85.0MiB/s

[val] downloading 677/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140209_1612_HARP3719_NOAA11973.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140209_1612_HARP3719_NOAA11973.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e77ff0ad1b6274629379332a31314449.npz

.

Average throughput: 150.8MiB/s

[val] downloading 678/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140419_1312_HARP4011_NOAA12040.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140419_1312_HARP4011_NOAA12040.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/818290cf5cf9300027c45b960f21cbb6.npz

.

Average throughput: 193.3MiB/s

[val] downloading 679/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140514_0400_HARP4097_NOAA12055.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140514_0400_HARP4097_NOAA12055.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0a4d9568a6d5833f452bd55e4de706d0.npz

.

Average throughput: 74.3MiB/s

[val] downloading 680/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141023_0536_HARP4698_NOAA12192.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141023_0536_HARP4698_NOAA12192.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/616524303f1b21ec4c09e03450723c9d.npz

.

Average throughput: 104.6MiB/s

[val] downloading 681/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140515_1748_HARP4131_NOAA12066.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140515_1748_HARP4131_NOAA12066.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5956b615b0133253a5b02b72f27deddb.npz

.

Average throughput: 74.9MiB/s

[val] downloading 682/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140510_2136_HARP4097_NOAA12055.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140510_2136_HARP4097_NOAA12055.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c18491e4a20775511ab7a18007ceb17c.npz

.

Average throughput: 48.7MiB/s

[val] downloading 683/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140710_1348_HARP4321_NOAA12109.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140710_1348_HARP4321_NOAA12109.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e31c000f06cb7bbe47879a7cf5815139.npz

.

Average throughput: 107.9MiB/s

[val] downloading 684/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140708_1036_HARP4321_NOAA12109.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140708_1036_HARP4321_NOAA12109.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/394116fb11c36618bd2b0f48620d6a11.npz

.

Average throughput: 126.0MiB/s

[val] downloading 685/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140106_2124_HARP3563_NOAA11943.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140106_2124_HARP3563_NOAA11943.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a35e553aa9bb15f824ffaa6e45407219.npz

.

Average throughput: 112.3MiB/s

[val] downloading 686/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140324_0524_HARP3875_NOAA12016.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140324_0524_HARP3875_NOAA12016.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ff37094b8f50e1b1a6e565f9f84d54b1.npz

.

Average throughput: 109.6MiB/s

[val] downloading 687/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141204_0412_HARP4874_NOAA12222.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141204_0412_HARP4874_NOAA12222.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8fc993ed108b847a7e90337c7a80890c.npz

.

Average throughput: 58.0MiB/s

[val] downloading 688/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141201_0648_HARP4872_NOAA12221.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141201_0648_HARP4872_NOAA12221.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/310c4f1cd1b8f294504f5a607536e3c3.npz

.

Average throughput: 104.6MiB/s

[val] downloading 689/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140302_1200_HARP3784_NOAA11987.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140302_1200_HARP3784_NOAA11987.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a0d4b72c42ce363db4f7b06c861aa058.npz

.

Average throughput: 167.3MiB/s

[val] downloading 690/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140510_1124_HARP4108_NOAA12054.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140510_1124_HARP4108_NOAA12054.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5afa7926bf4c3d29ed13bc34c5009ad1.npz



Average throughput: 195.7MiB/s

[val] downloading 691/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140216_1836_HARP3740_NOAA11977.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140216_1836_HARP3740_NOAA11977.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8dfd6880cff639b74928d4f9c6f4280b.npz

.

Average throughput: 140.3MiB/s

[val] downloading 692/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141210_1300_HARP4888_NOAA12227.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141210_1300_HARP4888_NOAA12227.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/48b971d3bd997d446a14a12fd794c55d.npz

.

Average throughput: 150.1MiB/s

[val] downloading 693/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140509_1348_HARP4093_NOAA12054.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140509_1348_HARP4093_NOAA12054.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d9ab1d1254840552a26f5856ffa3f255.npz

.

Average throughput: 95.8MiB/s

[val] downloading 694/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141104_1100_HARP4764_NOAA12203.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141104_1100_HARP4764_NOAA12203.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f06e85b73e9e1580c99d83540bdf2810.npz

.

Average throughput: 80.7MiB/s

[val] downloading 695/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141028_0448_HARP4726_NOAA12195.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141028_0448_HARP4726_NOAA12195.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7d1e8b999535068777276962b7ac1379.npz

.

Average throughput: 74.4MiB/s

[val] downloading 696/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140107_1748_HARP3580_NOAA11946.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140107_1748_HARP3580_NOAA11946.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/bc2f2d8434e740a0b2fca803aa927328.npz

.

Average throughput: 137.7MiB/s

[val] downloading 697/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140417_0936_HARP3999_NOAA12036.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140417_0936_HARP3999_NOAA12036.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d04b03da41e3fc528285259868d378ef.npz

.

Average throughput: 157.8MiB/s

[val] downloading 698/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140107_0912_HARP3560_NOAA11942.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140107_0912_HARP3560_NOAA11942.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/45fea3ee995756a5b3734d8c99f1228e.npz

.

Average throughput: 152.1MiB/s

[val] downloading 699/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140725_0548_HARP4381_NOAA12122.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140725_0548_HARP4381_NOAA12122.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9f85b3cb8011a9ac6b9b006aa2190364.npz

.

Average throughput: 107.9MiB/s

[val] downloading 700/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140528_0036_HARP4166_NOAA12075.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140528_0036_HARP4166_NOAA12075.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ce242ae487f600cfc82d02b4d42a7dd8.npz

.

Average throughput: 137.0MiB/s

[val] cached/checked 700/825 files | elapsed 18.0 min
[val] downloading 701/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141003_0024_HARP4623_NOAA12181.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141003_0024_HARP4623_NOAA12181.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5b54eb607218c921051aad5e6144f4d7.npz

.

Average throughput: 78.4MiB/s

[val] downloading 702/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140505_1824_HARP4092_NOAA12053.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140505_1824_HARP4092_NOAA12053.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/89e967555089856cec728cf76cb2eea0.npz

.

Average throughput: 46.4MiB/s

[val] downloading 703/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140615_1736_HARP4225_NOAA12087.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140615_1736_HARP4225_NOAA12087.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/01990dc43d9c9928537a3eb73ee3b5c7.npz

.

Average throughput: 105.4MiB/s

[val] downloading 704/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141017_1112_HARP4679_NOAA12189.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141017_1112_HARP4679_NOAA12189.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3498cf00768e91a3af9ed451e6b3d078.npz

.

Average throughput: 164.7MiB/s

[val] downloading 705/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141028_1212_HARP4748_NOAA12198.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141028_1212_HARP4748_NOAA12198.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1a915789fec1f67f08eb38d5f30afb35.npz



Average throughput: 161.5MiB/s

[val] downloading 706/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140512_0100_HARP4093_NOAA12054.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140512_0100_HARP4093_NOAA12054.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/27d9c7de2f483a80df6b5f5cc3bfe216.npz

.

Average throughput: 141.4MiB/s

[val] downloading 707/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140227_1700_HARP3779_NOAA11986.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140227_1700_HARP3779_NOAA11986.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/236bda8a66fa2a700a601ea0b6f092c6.npz

.

Average throughput: 105.1MiB/s

[val] downloading 708/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141219_2236_HARP4943_NOAA12240.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141219_2236_HARP4943_NOAA12240.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d448a17944a2ddb8fe29c50bfcf9c128.npz

.

Average throughput: 102.5MiB/s

[val] downloading 709/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141223_0936_HARP4955_NOAA12249.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141223_0936_HARP4955_NOAA12249.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0f7bd144e79349c1373f1ccc1ea51105.npz

.

Average throughput: 93.3MiB/s

[val] downloading 710/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140611_1936_HARP4223_NOAA12086.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140611_1936_HARP4223_NOAA12086.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fa27013244d768c4dbf4f2ab252c0ca3.npz

.

Average throughput: 160.4MiB/s

[val] downloading 711/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140323_1048_HARP3856_NOAA12008.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140323_1048_HARP3856_NOAA12008.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d58ff51451a5938609275f2731b1c229.npz

.

Average throughput: 206.4MiB/s

[val] downloading 712/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140301_1900_HARP3806_NOAA11992.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140301_1900_HARP3806_NOAA11992.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a7b7df3154eedb19f93389707d1e43a5.npz

.

Average throughput: 85.0MiB/s

[val] downloading 713/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140123_2348_HARP3647_NOAA11958.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140123_2348_HARP3647_NOAA11958.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/615969b8730a8253e5ce317e5b223daf.npz

.

Average throughput: 114.2MiB/s

[val] downloading 714/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141224_1648_HARP4963_NOAA12244.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141224_1648_HARP4963_NOAA12244.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1d855b564e59340a138991472240efaa.npz

.

Average throughput: 179.5MiB/s

[val] downloading 715/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141210_2000_HARP4915_NOAA12233.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141210_2000_HARP4915_NOAA12233.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/451b2104f4f243ccbfe0314d2d2d08cb.npz

.

Average throughput: 181.8MiB/s

[val] downloading 716/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140508_0236_HARP4093_NOAA12054.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140508_0236_HARP4093_NOAA12054.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fea9275d36ab589f85345d29c1c9f2f3.npz

.

Average throughput: 151.0MiB/s

[val] downloading 717/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140123_1148_HARP3631_NOAA11955.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140123_1148_HARP3631_NOAA11955.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e5304cd39d8622d318313f25fc3a7d9b.npz

.

Average throughput: 158.3MiB/s

[val] downloading 718/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141114_0112_HARP4800_NOAA12207.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141114_0112_HARP4800_NOAA12207.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/74fae2a0c506ddbdb232ae7058b1f6fa.npz

.

Average throughput: 90.2MiB/s

[val] downloading 719/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140216_1436_HARP3765_NOAA11985.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140216_1436_HARP3765_NOAA11985.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f5df9b7e8a39900c0d7e8e1857bc0437.npz

.

Average throughput: 100.4MiB/s

[val] downloading 720/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141104_0312_HARP4751_NOAA12200.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141104_0312_HARP4751_NOAA12200.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b5dabce338438beb88b8c01b8254399c.npz

.

Average throughput: 169.2MiB/s

[val] downloading 721/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140803_0824_HARP4398_NOAA12128.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140803_0824_HARP4398_NOAA12128.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4b87a49c0ac664eb4f357fec6a1205d8.npz

.

Average throughput: 109.6MiB/s

[val] downloading 722/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140407_0124_HARP3941_NOAA12027.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140407_0124_HARP3941_NOAA12027.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7187029159cb452d56a5c5c4828db545.npz

.

Average throughput: 101.0MiB/s

[val] downloading 723/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140113_1236_HARP3612_NOAA11951.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140113_1236_HARP3612_NOAA11951.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4beba07352d2fdfca926000e80214e80.npz

.

Average throughput: 139.1MiB/s

[val] downloading 724/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140414_0600_HARP3999_NOAA12036.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140414_0600_HARP3999_NOAA12036.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/331df37d5e765e222ec1f65b30ff0ffc.npz

.

Average throughput: 155.2MiB/s

[val] downloading 725/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141211_2300_HARP4908_NOAA12232.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141211_2300_HARP4908_NOAA12232.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5027dffd979e3ffc7adc80569897109a.npz

.

Average throughput: 107.8MiB/s

[val] downloading 726/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140706_0024_HARP4315_NOAA12108.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140706_0024_HARP4315_NOAA12108.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fd141354bcaf44a38018aeb064c55bc1.npz

.

Average throughput: 57.0MiB/s

[val] downloading 727/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140120_0400_HARP3658_NOAA11962.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140120_0400_HARP3658_NOAA11962.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2cebdbd395416cb4684bfebf0f76a731.npz

.

Average throughput: 156.0MiB/s

[val] downloading 728/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140518_2324_HARP4135_NOAA12064.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140518_2324_HARP4135_NOAA12064.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e203d018a08517484bd29ad0a121d79e.npz

.

Average throughput: 175.8MiB/s

[val] downloading 729/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141216_1700_HARP4938_NOAA12238.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141216_1700_HARP4938_NOAA12238.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/48fcf8a4814d2ee252de3ea2d9efd521.npz

.

Average throughput: 147.3MiB/s

[val] downloading 730/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140808_0100_HARP4424_NOAA12134.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140808_0100_HARP4424_NOAA12134.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/91119b6efd753a0611ccc5459422be2c.npz

.

Average throughput: 51.9MiB/s

[val] downloading 731/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140525_0248_HARP4152_NOAA12069.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140525_0248_HARP4152_NOAA12069.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/cd18025aceb1977e6bc9ffd22786001d.npz

.

Average throughput: 106.6MiB/s

[val] downloading 732/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140421_0336_HARP4025_NOAA12042.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140421_0336_HARP4025_NOAA12042.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b1f6f156fba70680fac5c2a90f842bdd.npz

.

Average throughput: 125.1MiB/s

[val] downloading 733/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141104_1824_HARP4767_NOAA12204.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141104_1824_HARP4767_NOAA12204.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c6f5c139e7950a1b79b99c49408fbad8.npz

.

Average throughput: 130.3MiB/s

[val] downloading 734/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140730_0112_HARP4379_NOAA12121.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140730_0112_HARP4379_NOAA12121.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2b813f162b29a4fbe5576b3a952703de.npz

.

Average throughput: 170.4MiB/s

[val] downloading 735/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140103_0100_HARP3557_NOAA11938.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140103_0100_HARP3557_NOAA11938.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/29c7102b09dae7d24d91fefbfb3afbdd.npz

.

Average throughput: 87.8MiB/s

[val] downloading 736/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140202_1548_HARP3688_NOAA11968.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140202_1548_HARP3688_NOAA11968.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ef776b1278180cdc60ea18e053fecd46.npz

.

Average throughput: 159.3MiB/s

[val] downloading 737/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140709_0824_HARP4315_NOAA12108.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140709_0824_HARP4315_NOAA12108.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/adefcba12d20598f4d79f7c5d30b27c0.npz

.

Average throughput: 99.8MiB/s

[val] downloading 738/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140510_1524_HARP4093_NOAA12054.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140510_1524_HARP4093_NOAA12054.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a08527cf2c37a865d3b48bafc69e3581.npz

.

Average throughput: 113.0MiB/s

[val] downloading 739/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140612_1312_HARP4223_NOAA12086.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140612_1312_HARP4223_NOAA12086.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/bcb8ed8f157a1c9399004280852c56ed.npz

.

Average throughput: 136.8MiB/s

[val] downloading 740/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140522_1848_HARP4152_NOAA12069.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140522_1848_HARP4152_NOAA12069.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d13414f7d1ac5d8e2e077818b1f89367.npz

.

Average throughput: 178.1MiB/s

[val] downloading 741/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141127_2348_HARP4868_NOAA12219.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141127_2348_HARP4868_NOAA12219.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/19a93d2819be52759a56742354f5696e.npz

.

Average throughput: 54.9MiB/s

[val] downloading 742/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140109_1800_HARP3563_NOAA11943.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140109_1800_HARP3563_NOAA11943.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fe90005fe365c15bc9a17ccd912581d1.npz

.

Average throughput: 72.1MiB/s

[val] downloading 743/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140425_0048_HARP4042_NOAA12045.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140425_0048_HARP4042_NOAA12045.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/402db748f37c050a141ffd359141d865.npz

.

Average throughput: 183.9MiB/s

[val] downloading 744/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140515_0148_HARP4131_NOAA12066.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140515_0148_HARP4131_NOAA12066.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8f3eb40c4ed943890fbc4d28c76a9dce.npz

.

Average throughput: 110.8MiB/s

[val] downloading 745/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141102_0436_HARP4750_NOAA12199.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141102_0436_HARP4750_NOAA12199.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8be8a4140effa148628991aa9cddee83.npz

.

Average throughput: 107.4MiB/s

[val] downloading 746/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140628_0336_HARP4284_NOAA12098.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140628_0336_HARP4284_NOAA12098.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/40677848f344255e85bedac321b38241.npz

.

Average throughput: 182.7MiB/s

[val] downloading 747/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141228_1648_HARP4969_NOAA12245.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141228_1648_HARP4969_NOAA12245.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/35183bdceacabca0fda86cefe7f59e95.npz

.

Average throughput: 135.0MiB/s

[val] downloading 748/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140305_0400_HARP3804_NOAA11991.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140305_0400_HARP3804_NOAA11991.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/293f69735f475243950091d819f9acec.npz

.

Average throughput: 159.4MiB/s

[val] downloading 749/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140417_1248_HARP3996_NOAA12034.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140417_1248_HARP3996_NOAA12034.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5b24c09122af01840f766ea2fd8f5e16.npz

.

Average throughput: 125.0MiB/s

[val] downloading 750/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141030_1836_HARP4761_NOAA12202.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141030_1836_HARP4761_NOAA12202.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/106283dba704be79e343505068b67c86.npz

.

Average throughput: 130.3MiB/s

[val] downloading 751/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140114_1448_HARP3610_NOAA11954.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140114_1448_HARP3610_NOAA11954.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e19b79cddf4ffcb57cb789548050ccb5.npz

.

Average throughput: 151.5MiB/s

[val] downloading 752/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140212_2248_HARP3721_NOAA11974.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140212_2248_HARP3721_NOAA11974.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2158c9bf12b67266bd8a05b148867667.npz

.

Average throughput: 163.4MiB/s

[val] downloading 753/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140505_1136_HARP4088_NOAA12052.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140505_1136_HARP4088_NOAA12052.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f413df41725ff2949a96695e139b7544.npz

.

Average throughput: 112.5MiB/s

[val] downloading 754/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140508_1036_HARP4093_NOAA12054.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140508_1036_HARP4093_NOAA12054.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a655e804ed1ae1a33095875341b0fb70.npz

.

Average throughput: 53.5MiB/s

[val] downloading 755/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141225_1336_HARP4995_NOAA12250.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141225_1336_HARP4995_NOAA12250.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/61eb22020da261a9f7b853ecdcb33639.npz

.

Average throughput: 167.2MiB/s

[val] downloading 756/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140515_1300_HARP4131_NOAA12066.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140515_1300_HARP4131_NOAA12066.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9d97484b7f38871c3aca7a9ba6ec970b.npz

.

Average throughput: 167.4MiB/s

[val] downloading 757/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140516_1436_HARP4131_NOAA12066.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140516_1436_HARP4131_NOAA12066.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/43182bea5bbf43af818022415f31a9c6.npz

.

Average throughput: 128.2MiB/s

[val] downloading 758/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140322_1224_HARP3856_NOAA12008.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140322_1224_HARP3856_NOAA12008.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0703f524720c1ddd4a4b9911e88e3392.npz

.

Average throughput: 179.2MiB/s

[val] downloading 759/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140216_2200_HARP3765_NOAA11985.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140216_2200_HARP3765_NOAA11985.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/59f448982701265df1d90c5dfd3e6a2a.npz

.

Average throughput: 178.8MiB/s

[val] downloading 760/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141028_2148_HARP4748_NOAA12198.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141028_2148_HARP4748_NOAA12198.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5b781d0ff657e2d1dd04f7a2d055961e.npz

.

Average throughput: 135.0MiB/s

[val] downloading 761/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141201_1324_HARP4874_NOAA12222.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141201_1324_HARP4874_NOAA12222.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e21a260a525e4bf6b11a8a67d5b1feda.npz

.

Average throughput: 100.5MiB/s

[val] downloading 762/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141122_0648_HARP4839_NOAA12215.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141122_0648_HARP4839_NOAA12215.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3aa800b0f7620bf547cf460971828577.npz

.

Average throughput: 69.7MiB/s

[val] downloading 763/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140208_2248_HARP3703_NOAA11970.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140208_2248_HARP3703_NOAA11970.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/170c8d84c454350ddc5b3453a5cb51aa.npz

.

Average throughput: 116.8MiB/s

[val] downloading 764/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140525_2348_HARP4156_NOAA12071.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140525_2348_HARP4156_NOAA12071.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/85feac23c784ce82f53c9e13ce44ff09.npz

.

Average throughput: 71.6MiB/s

[val] downloading 765/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141021_0648_HARP4678_NOAA12187.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141021_0648_HARP4678_NOAA12187.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4bee5b083f0a8980ab43885709ef6c7f.npz

.

Average throughput: 176.1MiB/s

[val] downloading 766/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140213_1500_HARP3721_NOAA11974.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140213_1500_HARP3721_NOAA11974.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c885bafc5c50a663f92d83226f4f59f3.npz

.

Average throughput: 152.3MiB/s

[val] downloading 767/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141106_0824_HARP4751_NOAA12200.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141106_0824_HARP4751_NOAA12200.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/a293cddcfc357796c625fd91b3a2d881.npz

.

Average throughput: 117.3MiB/s

[val] downloading 768/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140330_1248_HARP3907_NOAA12024.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140330_1248_HARP3907_NOAA12024.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b2e70866ef29ab0a191987dc40144b2b.npz

.

Average throughput: 166.4MiB/s

[val] downloading 769/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140802_0836_HARP4396_NOAA12127.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140802_0836_HARP4396_NOAA12127.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3359573e39d965f05528142d563d49bd.npz

.

Average throughput: 106.6MiB/s

[val] downloading 770/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140612_0736_HARP4224_NOAA12091.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140612_0736_HARP4224_NOAA12091.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7c4488df117e3cab290cbb9ba9c7685e.npz

.

Average throughput: 70.2MiB/s

[val] downloading 771/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141011_2348_HARP4667_NOAA12186.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141011_2348_HARP4667_NOAA12186.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/3ca88cbfd958a01e356c8584f9fec9ea.npz

.

Average throughput: 95.9MiB/s

[val] downloading 772/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140304_1336_HARP3804_NOAA11991.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140304_1336_HARP3804_NOAA11991.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9878355676fe3093b52e191e5e9734d5.npz



Average throughput: 193.0MiB/s

[val] downloading 773/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140628_0800_HARP4272_NOAA12096.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140628_0800_HARP4272_NOAA12096.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1c705c3e0f670fe07d20ec4077b200a4.npz

.

Average throughput: 34.4MiB/s

[val] downloading 774/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141027_1812_HARP4734_NOAA12197.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141027_1812_HARP4734_NOAA12197.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2dcb096534d9e2d3e0785c4a785c15b5.npz

.

Average throughput: 66.0MiB/s

[val] downloading 775/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141121_0824_HARP4839_NOAA12215.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141121_0824_HARP4839_NOAA12215.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/2aeb959284a0e085de2702181ae0e9b8.npz

.

Average throughput: 172.4MiB/s

[val] downloading 776/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140525_1100_HARP4156_NOAA12071.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140525_1100_HARP4156_NOAA12071.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fb9351b0ee4fa4c2fd196e9786b2e119.npz

.

Average throughput: 81.7MiB/s

[val] downloading 777/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140707_1824_HARP4328_NOAA12111.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140707_1824_HARP4328_NOAA12111.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/8467de83fd1a07d9421cf4b1157b5a25.npz

.

Average throughput: 50.8MiB/s

[val] downloading 778/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140427_1024_HARP4042_NOAA12045.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140427_1024_HARP4042_NOAA12045.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7c50c9bd61e955828bdf25fa93ee8517.npz

.

Average throughput: 177.4MiB/s

[val] downloading 779/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140316_2300_HARP3853_NOAA12009.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140316_2300_HARP3853_NOAA12009.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ccd226f99a6b5bbf41a8783807ac3df5.npz

.

Average throughput: 107.1MiB/s

[val] downloading 780/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141211_1012_HARP4921_NOAA12234.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141211_1012_HARP4921_NOAA12234.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b8f40fe585174cf32bb56472b407f37a.npz

.

Average throughput: 72.4MiB/s

[val] downloading 781/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140720_0548_HARP4376_NOAA12120.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140720_0548_HARP4376_NOAA12120.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7918ae20c96b1a5e313dbdeeb42fed53.npz

.

Average throughput: 175.6MiB/s

[val] downloading 782/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141102_0936_HARP4751_NOAA12200.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141102_0936_HARP4751_NOAA12200.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d21ece3802f0f7c9846c3eda297eef4f.npz

.

Average throughput: 62.6MiB/s

[val] downloading 783/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140516_0624_HARP4111_NOAA12058.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140516_0624_HARP4111_NOAA12058.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/eadfcd3217908554f8875be046577d78.npz

.

Average throughput: 117.5MiB/s

[val] downloading 784/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141107_0712_HARP4784_NOAA12206.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141107_0712_HARP4784_NOAA12206.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/b61f2e3b9028db3fa44974193e073676.npz

.

Average throughput: 163.5MiB/s

[val] downloading 785/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140207_1924_HARP3711_NOAA11971.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140207_1924_HARP3711_NOAA11971.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/10aed4c22579f6209e0b695818197ade.npz

.

Average throughput: 104.1MiB/s

[val] downloading 786/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140407_2012_HARP3942_NOAA12026.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140407_2012_HARP3942_NOAA12026.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4efe1aec94413662d72eb977a08a284c.npz

.

Average throughput: 106.6MiB/s

[val] downloading 787/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140309_1300_HARP3824_NOAA11998.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140309_1300_HARP3824_NOAA11998.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/9c192da0f1ff75e71599a906e59393f6.npz



Average throughput: 168.3MiB/s

[val] downloading 788/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140427_1512_HARP4042_NOAA12045.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140427_1512_HARP4042_NOAA12045.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/57b388635c2953ac7651847901eb5e43.npz

.

Average throughput: 189.4MiB/s

[val] downloading 789/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141002_1600_HARP4610_NOAA12177.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141002_1600_HARP4610_NOAA12177.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5c925cdcfdee4c52e70ce3cf48219a46.npz

.

Average throughput: 144.2MiB/s

[val] downloading 790/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140310_0448_HARP3826_NOAA12000.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140310_0448_HARP3826_NOAA12000.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/973c4c59bb6fd0df15f0f9b2be8b1d45.npz



Average throughput: 178.9MiB/s

[val] downloading 791/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141021_0848_HARP4711_NOAA12193.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141021_0848_HARP4711_NOAA12193.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/36be7cae71f03a684805677710771b0d.npz

.

Average throughput: 60.9MiB/s

[val] downloading 792/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140210_0012_HARP3719_NOAA11973.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140210_0012_HARP3719_NOAA11973.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/95e9fe1b2fb653e85e4109a1b4ac4ad0.npz

.

Average throughput: 162.5MiB/s

[val] downloading 793/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141113_2200_HARP4800_NOAA12207.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141113_2200_HARP4800_NOAA12207.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/16781dca9cc0bc86f60c4f91c5cac513.npz

.

Average throughput: 145.3MiB/s

[val] downloading 794/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141215_0036_HARP4908_NOAA12232.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141215_0036_HARP4908_NOAA12232.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/4de875dc11be750de61ab3ad9cbccf23.npz

.

Average throughput: 143.7MiB/s

[val] downloading 795/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141217_1812_HARP4941_NOAA12241.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141217_1812_HARP4941_NOAA12241.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7c76c91267e95a7bcbad2bb6b5ddf4dd.npz

.

Average throughput: 155.3MiB/s

[val] downloading 796/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140403_1800_HARP3926_NOAA12022.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140403_1800_HARP3926_NOAA12022.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/97775ba11f09f5630c6a3dd741c74f2e.npz

.

Average throughput: 192.5MiB/s

[val] downloading 797/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141127_0436_HARP4868_NOAA12219.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141127_0436_HARP4868_NOAA12219.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/99921e022446c5127aef15682865aa89.npz

.

Average throughput: 86.1MiB/s

[val] downloading 798/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140211_2136_HARP3721_NOAA11974.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140211_2136_HARP3721_NOAA11974.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0fac95b90c5f44a16d935328b82fdd31.npz

.

Average throughput: 144.4MiB/s

[val] downloading 799/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140205_0300_HARP3688_NOAA11968.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140205_0300_HARP3688_NOAA11968.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/871e09c1d5e7952dce4b66c1d851d4a8.npz

.

Average throughput: 143.3MiB/s

[val] downloading 800/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140418_0000_HARP3996_NOAA12034.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140418_0000_HARP3996_NOAA12034.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/1b205b671430d26e2e5ec3bef6f995d4.npz

.

Average throughput: 91.5MiB/s

[val] cached/checked 800/825 files | elapsed 20.6 min
[val] downloading 801/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140404_1936_HARP3926_NOAA12022.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140404_1936_HARP3926_NOAA12022.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/29dfb13e4a6cfd3165f82cd342209f59.npz

.

Average throughput: 156.2MiB/s

[val] downloading 802/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141107_0600_HARP4767_NOAA12204.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141107_0600_HARP4767_NOAA12204.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/e9f113b719203289cb8221fabd89cec0.npz

.

Average throughput: 60.1MiB/s

[val] downloading 803/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140111_0512_HARP3608_NOAA11953.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140111_0512_HARP3608_NOAA11953.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/113360792e8b8667529cdb1a210e6308.npz

.

Average throughput: 93.6MiB/s

[val] downloading 804/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140312_2348_HARP3836_NOAA12002.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140312_2348_HARP3836_NOAA12002.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/062cdcc4feb300ff15dd4af7e9edd258.npz

.

Average throughput: 167.6MiB/s

[val] downloading 805/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140628_0436_HARP4290_NOAA12099.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140628_0436_HARP4290_NOAA12099.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/5f015eaaae9b6fdeb909221fdb8e5e23.npz

.

Average throughput: 164.9MiB/s

[val] downloading 806/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141208_0500_HARP4888_NOAA12227.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141208_0500_HARP4888_NOAA12227.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/fed4ea2d585bd55cf7c5da5c0e90224a.npz

.

Average throughput: 59.6MiB/s

[val] downloading 807/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140101_1636_HARP3557_NOAA11938.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140101_1636_HARP3557_NOAA11938.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/bf2609bb4d6a237aa65b76927a4903bd.npz

.

Average throughput: 118.8MiB/s

[val] downloading 808/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140208_1612_HARP3719_NOAA11973.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140208_1612_HARP3719_NOAA11973.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/f1597f9448b185cb7ffc51587895240d.npz

.

Average throughput: 182.6MiB/s

[val] downloading 809/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140718_1736_HARP4375_NOAA12119.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140718_1736_HARP4375_NOAA12119.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/80a24abbfdb83153b8945636678e5c5d.npz

.

Average throughput: 79.7MiB/s

[val] downloading 810/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140326_2336_HARP3879_NOAA12014.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140326_2336_HARP3879_NOAA12014.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/60c5573287bb521174452049b2514b82.npz

.

Average throughput: 105.6MiB/s

[val] downloading 811/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140107_1048_HARP3560_NOAA11942.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140107_1048_HARP3560_NOAA11942.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/16422fad67f34834aa05d1dc347ec7f8.npz

.

Average throughput: 114.6MiB/s

[val] downloading 812/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140704_2236_HARP4294_NOAA12102.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140704_2236_HARP4294_NOAA12102.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/90f36bce049e28117e0895d0be701e50.npz

.

Average throughput: 122.9MiB/s

[val] downloading 813/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141222_0736_HARP4954_NOAA12243.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141222_0736_HARP4954_NOAA12243.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/7fda14be53a139d7a064fe854f9890c4.npz

.

Average throughput: 104.8MiB/s

[val] downloading 814/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140127_1924_HARP3668_NOAA11965.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140127_1924_HARP3668_NOAA11965.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ecfbd473fb0b810ce96f2283b857e858.npz

.

Average throughput: 135.3MiB/s

[val] downloading 815/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141019_1000_HARP4690_NOAA12190.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141019_1000_HARP4690_NOAA12190.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/502d21c9a0a2f7fafcd40599fc11ec6a.npz

.

Average throughput: 165.5MiB/s

[val] downloading 816/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140708_0900_HARP4321_NOAA12109.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140708_0900_HARP4321_NOAA12109.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/04c2df57ea82fb4f176b6be93e978bb0.npz

.

Average throughput: 125.2MiB/s

[val] downloading 817/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140709_0900_HARP4321_NOAA12109.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140709_0900_HARP4321_NOAA12109.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c0f8b696dfa555698c307d61e096fbf3.npz

.

Average throughput: 160.4MiB/s

[val] downloading 818/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140109_1736_HARP3580_NOAA11946.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140109_1736_HARP3580_NOAA11946.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/aabbb1bdd5147d80c9a69535b36f5fc6.npz

.

Average throughput: 93.5MiB/s

[val] downloading 819/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141020_0536_HARP4711_NOAA12193.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141020_0536_HARP4711_NOAA12193.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d52fad5862a0b47dec8e83acc5deb50f.npz

.

Average throughput: 182.3MiB/s

[val] downloading 820/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140327_0248_HARP3894_NOAA12017.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140327_0248_HARP3894_NOAA12017.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/ed5ebbf9049385be95ab3405f4ad867c.npz

.

Average throughput: 158.0MiB/s

[val] downloading 821/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140327_0424_HARP3894_NOAA12017.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140327_0424_HARP3894_NOAA12017.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/34fe3bd0d8f2e477f373e337fa625ad3.npz

.

Average throughput: 146.7MiB/s

[val] downloading 822/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140618_1636_HARP4225_NOAA12087.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140618_1636_HARP4225_NOAA12087.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/d4809f9285098df46aea808f454c0d44.npz

.

Average throughput: 142.8MiB/s

[val] downloading 823/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140508_0524_HARP4088_NOAA12052.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140508_0524_HARP4088_NOAA12052.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/774fa76609fc421faa7888afb2624eee.npz

.

Average throughput: 105.3MiB/s

[val] downloading 824/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141005_1112_HARP4616_NOAA12178.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20141005_1112_HARP4616_NOAA12178.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/c569d00521c0fa48d586cd4bda08cbb9.npz

.

Average throughput: 74.9MiB/s

[val] downloading 825/825: gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140306_1636_HARP3813_NOAA11996.npz

Copying gs://suryabench-sharp-pipeline-bamidele/samples_npz/2014/20140306_1636_HARP3813_NOAA11996.npz to file:///home/abmoses2000/solar_flare_aia/cache/gcs_npz_realistic_imbalance/0714ec6dccbb1dd4ac0a2bd68a821273.npz

.

[val] cached/checked 825/825 files | elapsed 21.3 min
Finished pre-caching val

Average throughput: 152.4MiB/s

In [5]:
class AIANPZDataset(Dataset):
    def __init__(self, frame: pd.DataFrame, image_size: int = 224):
        self.frame = frame.reset_index(drop=True)
        self.image_size = image_size

    def __len__(self):
        return len(self.frame)

    def __getitem__(self, idx):
        row = self.frame.iloc[idx]
        local_path = cache_gcs_file(row["gcp_path"])

        data = np.load(local_path, allow_pickle=True)

        # Official image tensor is H, W, C = 512, 512, 6
        x = data["x"].astype(np.float32)
        x = np.nan_to_num(x, nan=0.0, posinf=1.0, neginf=0.0)
        x = np.clip(x, 0.0, 1.0)

        # Convert to PyTorch C, H, W = 6, 512, 512
        x = torch.from_numpy(np.transpose(x, (2, 0, 1))).float()

        # Resize to reduce compute cost
        if self.image_size != 512:
            x = F.interpolate(
                x.unsqueeze(0),
                size=(self.image_size, self.image_size),
                mode="bilinear",
                align_corners=False,
            ).squeeze(0)

        # Important: use repaired manifest label, not embedded NPZ y
        y = torch.tensor(float(row["label_48h_final"]), dtype=torch.float32)

        return x, y, str(row["sample_id"])

train_loader = DataLoader(
    AIANPZDataset(train_df, image_size=IMAGE_SIZE),
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=NUM_WORKERS,
    pin_memory=torch.cuda.is_available(),
)

val_loader = DataLoader(
    AIANPZDataset(val_df, image_size=IMAGE_SIZE),
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=torch.cuda.is_available(),
)

x_batch, y_batch, sample_ids = next(iter(train_loader))
print("x batch shape:", tuple(x_batch.shape))
print("y batch shape:", tuple(y_batch.shape))
print("y positives in batch:", int(y_batch.sum().item()))
print("x min/max:", float(x_batch.min()), float(x_batch.max()))
print("sample ids:", list(sample_ids[:3]))

x batch shape: (16, 6, 224, 224)
y batch shape: (16,)
y positives in batch: 2
x min/max: 0.002895033685490489 0.9993789792060852
sample ids: ['20121126_1824_HARP2227_NOAA11620', '20111218_0948_HARP1186_NOAA11378', '20110215_1400_HARP377_NOAA11158']

In [6]:
class SmallAIAImbalanceCNN(nn.Module):
    def __init__(self, in_channels=6):
        super().__init__()

        self.features = nn.Sequential(
            nn.Conv2d(in_channels, 32, kernel_size=7, stride=2, padding=3),
            nn.BatchNorm2d(32),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2),

            nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2),

            nn.Conv2d(64, 128, kernel_size=3, stride=1, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2),

            nn.Conv2d(128, 192, kernel_size=3, stride=1, padding=1),
            nn.BatchNorm2d(192),
            nn.ReLU(inplace=True),

            nn.AdaptiveAvgPool2d((1, 1)),
        )

        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Dropout(0.25),
            nn.Linear(192, 64),
            nn.ReLU(inplace=True),
            nn.Dropout(0.25),
            nn.Linear(64, 1),
        )

    def forward(self, x):
        return self.classifier(self.features(x)).squeeze(1)

model = SmallAIAImbalanceCNN(in_channels=6).to(device)

with torch.no_grad():
    test_logits = model(x_batch.to(device))

print(model.__class__.__name__)
print("Test logits shape:", tuple(test_logits.shape))
print("Model device:", next(model.parameters()).device)
print("Trainable parameters:", sum(p.numel() for p in model.parameters() if p.requires_grad))

SmallAIAImbalanceCNN
Test logits shape: (16,)
Model device: cuda:0
Trainable parameters: 336417

In [7]:
def safe_auc(y_true, y_prob):
    try:
        return float(roc_auc_score(y_true, y_prob))
    except ValueError:
        return None

def safe_ap(y_true, y_prob):
    try:
        return float(average_precision_score(y_true, y_prob))
    except ValueError:
        return None

def binary_metrics_at_threshold(y_true, y_prob, threshold=0.5):
    y_true = np.asarray(y_true).astype(int)
    y_prob = np.asarray(y_prob).astype(float)
    y_pred = (y_prob >= threshold).astype(int)

    tp = int(((y_true == 1) & (y_pred == 1)).sum())
    tn = int(((y_true == 0) & (y_pred == 0)).sum())
    fp = int(((y_true == 0) & (y_pred == 1)).sum())
    fn = int(((y_true == 1) & (y_pred == 0)).sum())

    eps = 1e-12

    accuracy = (tp + tn) / max(tp + tn + fp + fn, 1)
    precision = tp / max(tp + fp, 1)
    recall = tp / max(tp + fn, 1)
    specificity = tn / max(tn + fp, 1)
    f1 = 2 * precision * recall / max(precision + recall, eps)
    tss = recall + specificity - 1

    numerator = 2 * (tp * tn - fp * fn)
    denominator = ((tp + fn) * (fn + tn) + (tp + fp) * (fp + tn))
    hss = numerator / max(denominator, eps)

    return {
        "threshold": float(threshold),
        "accuracy": float(accuracy),
        "precision": float(precision),
        "recall": float(recall),
        "specificity": float(specificity),
        "f1": float(f1),
        "tss": float(tss),
        "hss": float(hss),
        "tp": tp,
        "tn": tn,
        "fp": fp,
        "fn": fn,
    }

def best_tss_threshold(y_true, y_prob):
    y_prob = np.asarray(y_prob).astype(float)
    thresholds = np.unique(np.round(y_prob, 6))
    if len(thresholds) > 400:
        thresholds = np.linspace(0.0, 1.0, 401)

    best = None
    for thr in thresholds:
        m = binary_metrics_at_threshold(y_true, y_prob, threshold=float(thr))
        if best is None or m["tss"] > best["tss"]:
            best = m

    return best

def evaluate_predictions(y_true, y_prob):
    fixed = binary_metrics_at_threshold(y_true, y_prob, threshold=0.5)
    best = best_tss_threshold(y_true, y_prob)

    return {
        "roc_auc": safe_auc(y_true, y_prob),
        "pr_auc": safe_ap(y_true, y_prob),
        "metrics_at_0_5": fixed,
        "metrics_at_best_tss_threshold": best,
    }

def collect_predictions(model, loader, device):
    model.eval()
    rows = []
    y_true, y_prob = [], []

    with torch.no_grad():
        for x, y, sample_ids in loader:
            x = x.to(device, non_blocking=True)
            logits = model(x)
            prob = torch.sigmoid(logits).detach().cpu().numpy()

            y_np = y.numpy()
            for sid, yy, pp in zip(sample_ids, y_np, prob):
                rows.append({
                    "sample_id": sid,
                    "y_true": int(yy),
                    "y_prob": float(pp),
                })

            y_true.extend(y_np.tolist())
            y_prob.extend(prob.tolist())

    pred_df = pd.DataFrame(rows)
    metrics = evaluate_predictions(y_true, y_prob)
    return pred_df, metrics

In [8]:
pos_count = int(train_df["label_48h_final"].sum())
neg_count = int(len(train_df) - pos_count)
pos_weight_value = neg_count / max(pos_count, 1)

print("Train positive count:", pos_count)
print("Train negative count:", neg_count)
print("pos_weight:", pos_weight_value)

model = SmallAIAImbalanceCNN(in_channels=6).to(device)
criterion = nn.BCEWithLogitsLoss(
    pos_weight=torch.tensor([pos_weight_value], dtype=torch.float32, device=device)
)
optimizer = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)

history = []
best_record = None
best_state = None

for epoch in range(1, EPOCHS + 1):
    epoch_start = time.time()
    model.train()
    losses = []

    for step, (x, y, sample_ids) in enumerate(train_loader, 1):
        x = x.to(device, non_blocking=True)
        y = y.to(device, non_blocking=True)

        optimizer.zero_grad(set_to_none=True)
        logits = model(x)
        loss = criterion(logits, y)
        loss.backward()
        optimizer.step()

        losses.append(float(loss.item()))

        if step == 1:
            print(f"Epoch {epoch} first batch x:", tuple(x.shape), "y positives:", int(y.sum().item()))

    train_pred_df, train_eval = collect_predictions(model, train_loader, device)
    val_pred_df, val_eval = collect_predictions(model, val_loader, device)

    record = {
        "epoch": epoch,
        "train_loss": float(np.mean(losses)),
        "train_eval": train_eval,
        "val_eval": val_eval,
        "elapsed_minutes": float((time.time() - epoch_start) / 60.0),
    }
    history.append(record)

    val_best_tss = val_eval["metrics_at_best_tss_threshold"]["tss"]
    if best_record is None or val_best_tss > best_record["val_eval"]["metrics_at_best_tss_threshold"]["tss"]:
        best_record = deepcopy(record)
        best_state = deepcopy(model.state_dict())

    print(f"\nEpoch {epoch}/{EPOCHS}")
    print("Train loss:", record["train_loss"])
    print("Train PR-AUC:", train_eval["pr_auc"], "ROC-AUC:", train_eval["roc_auc"])
    print("Val PR-AUC:", val_eval["pr_auc"], "ROC-AUC:", val_eval["roc_auc"])
    print("Val @0.5:", val_eval["metrics_at_0_5"])
    print("Val @best TSS:", val_eval["metrics_at_best_tss_threshold"])
    print("Elapsed min:", round(record["elapsed_minutes"], 2))

print("\nBest epoch by validation TSS:", best_record["epoch"])
print("Best validation metrics:", best_record["val_eval"]["metrics_at_best_tss_threshold"])

Train positive count: 150
Train negative count: 1500
pos_weight: 10.0
Epoch 1 first batch x: (16, 6, 224, 224) y positives: 1

Epoch 1/5
Train loss: 1.176922469184949
Train PR-AUC: 0.17174235181309683 ROC-AUC: 0.6959155555555556
Val PR-AUC: 0.19798268783934198 ROC-AUC: 0.7264177777777778
Val @0.5: {'threshold': 0.5, 'accuracy': 0.7236363636363636, 'precision': 0.17446808510638298, 'recall': 0.5466666666666666, 'specificity': 0.7413333333333333, 'f1': 0.2645161290322581, 'tss': 0.2879999999999998, 'hss': 0.1469387755102041, 'tp': 41, 'tn': 556, 'fp': 194, 'fn': 34}
Val @best TSS: {'threshold': 0.4375, 'accuracy': 0.6872727272727273, 'precision': 0.17437722419928825, 'recall': 0.6533333333333333, 'specificity': 0.6906666666666667, 'f1': 0.2752808988764045, 'tss': 0.34399999999999986, 'hss': 0.15384615384615385, 'tp': 49, 'tn': 518, 'fp': 232, 'fn': 26}
Elapsed min: 3.44
Epoch 2 first batch x: (16, 6, 224, 224) y positives: 0

Epoch 2/5
Train loss: 1.1349235389095087
Train PR-AUC: 0.2433358415321346 ROC-AUC: 0.766991111111111
Val PR-AUC: 0.1254214309517401 ROC-AUC: 0.6361777777777777
Val @0.5: {'threshold': 0.5, 'accuracy': 0.4315151515151515, 'precision': 0.1182170542635659, 'recall': 0.8133333333333334, 'specificity': 0.3933333333333333, 'f1': 0.20642978003384096, 'tss': 0.20666666666666655, 'hss': 0.05668312305723167, 'tp': 61, 'tn': 295, 'fp': 455, 'fn': 14}
Val @best TSS: {'threshold': 0.5700000000000001, 'accuracy': 0.5503030303030303, 'precision': 0.13366336633663367, 'recall': 0.72, 'specificity': 0.5333333333333333, 'f1': 0.2254697286012526, 'tss': 0.2533333333333334, 'hss': 0.08518269446312486, 'tp': 54, 'tn': 400, 'fp': 350, 'fn': 21}
Elapsed min: 3.78
Epoch 3 first batch x: (16, 6, 224, 224) y positives: 0

Epoch 3/5
Train loss: 1.0853979518780341
Train PR-AUC: 0.1992052269604558 ROC-AUC: 0.7497022222222223
Val PR-AUC: 0.12555779324294863 ROC-AUC: 0.6209777777777779
Val @0.5: {'threshold': 0.5, 'accuracy': 0.4775757575757576, 'precision': 0.10619469026548672, 'recall': 0.64, 'specificity': 0.4613333333333333, 'f1': 0.18216318785578747, 'tss': 0.10133333333333328, 'hss': 0.031064786429593295, 'tp': 48, 'tn': 346, 'fp': 404, 'fn': 27}
Val @best TSS: {'threshold': 0.43, 'accuracy': 0.3878787878787879, 'precision': 0.12147887323943662, 'recall': 0.92, 'specificity': 0.33466666666666667, 'f1': 0.2146189735614308, 'tss': 0.2546666666666666, 'hss': 0.06434226040087586, 'tp': 69, 'tn': 251, 'fp': 499, 'fn': 6}
Elapsed min: 3.76
Epoch 4 first batch x: (16, 6, 224, 224) y positives: 2

Epoch 4/5
Train loss: 1.0717837741741767
Train PR-AUC: 0.29087460001732185 ROC-AUC: 0.802528888888889
Val PR-AUC: 0.14708920978706722 ROC-AUC: 0.67152
Val @0.5: {'threshold': 0.5, 'accuracy': 0.5587878787878788, 'precision': 0.13784461152882205, 'recall': 0.7333333333333333, 'specificity': 0.5413333333333333, 'f1': 0.2320675105485232, 'tss': 0.2746666666666666, 'hss': 0.09329710144927536, 'tp': 55, 'tn': 406, 'fp': 344, 'fn': 20}
Val @best TSS: {'threshold': 0.5075000000000001, 'accuracy': 0.5709090909090909, 'precision': 0.14138817480719795, 'recall': 0.7333333333333333, 'specificity': 0.5546666666666666, 'f1': 0.23706896551724135, 'tss': 0.2879999999999998, 'hss': 0.09986130374479889, 'tp': 55, 'tn': 416, 'fp': 334, 'fn': 20}
Elapsed min: 3.76
Epoch 5 first batch x: (16, 6, 224, 224) y positives: 4

Epoch 5/5
Train loss: 1.0951227866686308
Train PR-AUC: 0.2791375466559878 ROC-AUC: 0.7918177777777777
Val PR-AUC: 0.13467915812684308 ROC-AUC: 0.6523733333333334
Val @0.5: {'threshold': 0.5, 'accuracy': 0.3490909090909091, 'precision': 0.11627906976744186, 'recall': 0.9333333333333333, 'specificity': 0.2906666666666667, 'f1': 0.206794682422452, 'tss': 0.22399999999999998, 'hss': 0.05382027871215762, 'tp': 70, 'tn': 218, 'fp': 532, 'fn': 5}
Val @best TSS: {'threshold': 0.6375000000000001, 'accuracy': 0.5854545454545454, 'precision': 0.14209115281501342, 'recall': 0.7066666666666667, 'specificity': 0.5733333333333334, 'f1': 0.23660714285714288, 'tss': 0.28, 'hss': 0.10043041606886657, 'tp': 53, 'tn': 430, 'fp': 320, 'fn': 22}
Elapsed min: 3.76

Best epoch by validation TSS: 1
Best validation metrics: {'threshold': 0.4375, 'accuracy': 0.6872727272727273, 'precision': 0.17437722419928825, 'recall': 0.6533333333333333, 'specificity': 0.6906666666666667, 'f1': 0.2752808988764045, 'tss': 0.34399999999999986, 'hss': 0.15384615384615385, 'tp': 49, 'tn': 518, 'fp': 232, 'fn': 26}

In [9]:
# Save outputs
if best_state is not None:
    model.load_state_dict(best_state)

train_pred_df, train_eval_final = collect_predictions(model, train_loader, device)
val_pred_df, val_eval_final = collect_predictions(model, val_loader, device)

train_pred_path = METRICS_DIR / f"{EXPERIMENT_NAME}_train_predictions.csv"
val_pred_path = METRICS_DIR / f"{EXPERIMENT_NAME}_val_predictions.csv"
metrics_path = METRICS_DIR / f"{EXPERIMENT_NAME}_metrics.json"
summary_path = METRICS_DIR / f"{EXPERIMENT_NAME}_readable_summary.md"
model_path = MODELS_DIR / f"{EXPERIMENT_NAME}.pt"

train_pred_df.to_csv(train_pred_path, index=False)
val_pred_df.to_csv(val_pred_path, index=False)

output = {
    "purpose": "Realistic class-imbalance AIA CNN year-holdout sanity experiment; not final publication result",
    "experiment_name": EXPERIMENT_NAME,
    "manifest": str(MANIFEST),
    "uses_label": "label_48h_final",
    "ignores_npz_y": True,
    "train_years": TRAIN_YEARS,
    "val_years": VAL_YEARS,
    "train_rows": int(len(train_df)),
    "val_rows": int(len(val_df)),
    "train_label_counts": {str(k): int(v) for k, v in train_df["label_48h_final"].value_counts().to_dict().items()},
    "val_label_counts": {str(k): int(v) for k, v in val_df["label_48h_final"].value_counts().to_dict().items()},
    "requested_train_pos": TRAIN_POS,
    "requested_train_neg": TRAIN_NEG,
    "requested_val_pos": VAL_POS,
    "requested_val_neg": VAL_NEG,
    "image_size": IMAGE_SIZE,
    "original_input_shape_hwc": [512, 512, 6],
    "model_input_shape_chw": [6, IMAGE_SIZE, IMAGE_SIZE],
    "batch_size": BATCH_SIZE,
    "epochs": EPOCHS,
    "lr": LR,
    "weight_decay": WEIGHT_DECAY,
    "pos_weight": float(pos_weight_value),
    "model_name": model.__class__.__name__,
    "best_epoch_by_val_tss": int(best_record["epoch"]),
    "history": history,
    "final_train_eval": train_eval_final,
    "final_val_eval": val_eval_final,
    "model_path": str(model_path),
    "train_predictions_path": str(train_pred_path),
    "val_predictions_path": str(val_pred_path),
}

metrics_path.write_text(json.dumps(output, indent=2))
torch.save(model.state_dict(), model_path)

best_val = val_eval_final["metrics_at_best_tss_threshold"]
fixed_val = val_eval_final["metrics_at_0_5"]

summary_text = f'''# Realistic Class-Imbalance AIA CNN Year-Holdout Sanity Experiment

Purpose: {output["purpose"]}

Experiment: `{EXPERIMENT_NAME}`

## Protocol

- Train years: {TRAIN_YEARS}
- Validation years: {VAL_YEARS}
- Train rows: {len(train_df)}
- Validation rows: {len(val_df)}
- Train label counts: {output["train_label_counts"]}
- Validation label counts: {output["val_label_counts"]}
- Original input: 512 × 512 × 6
- Model input: {IMAGE_SIZE} × {IMAGE_SIZE} × 6
- Label used: `label_48h_final`
- Embedded NPZ `y`: ignored
- Loss: weighted BCEWithLogitsLoss
- pos_weight: {pos_weight_value:.4f}

## Final validation metrics at fixed threshold 0.5

- ROC-AUC: {val_eval_final["roc_auc"]}
- PR-AUC: {val_eval_final["pr_auc"]}
- Accuracy: {fixed_val["accuracy"]:.4f}
- Precision: {fixed_val["precision"]:.4f}
- Recall: {fixed_val["recall"]:.4f}
- Specificity: {fixed_val["specificity"]:.4f}
- F1: {fixed_val["f1"]:.4f}
- TSS: {fixed_val["tss"]:.4f}
- HSS: {fixed_val["hss"]:.4f}
- TP: {fixed_val["tp"]}
- TN: {fixed_val["tn"]}
- FP: {fixed_val["fp"]}
- FN: {fixed_val["fn"]}

## Final validation metrics at best validation TSS threshold

- Threshold: {best_val["threshold"]:.6f}
- Accuracy: {best_val["accuracy"]:.4f}
- Precision: {best_val["precision"]:.4f}
- Recall: {best_val["recall"]:.4f}
- Specificity: {best_val["specificity"]:.4f}
- F1: {best_val["f1"]:.4f}
- TSS: {best_val["tss"]:.4f}
- HSS: {best_val["hss"]:.4f}
- TP: {best_val["tp"]}
- TN: {best_val["tn"]}
- FP: {best_val["fp"]}
- FN: {best_val["fn"]}

## Important note

This is a sanity experiment under controlled imbalanced sampling, not a final publication result.
'''

summary_path.write_text(summary_text)

print("Saved metrics:", metrics_path)
print("Saved readable summary:", summary_path)
print("Saved train predictions:", train_pred_path)
print("Saved val predictions:", val_pred_path)
print("Saved model:", model_path)

Saved metrics: /home/abmoses2000/solar_flare_aia/results/metrics/realistic_imbalance_aia_cnn_year_holdout_10to1_metrics.json
Saved readable summary: /home/abmoses2000/solar_flare_aia/results/metrics/realistic_imbalance_aia_cnn_year_holdout_10to1_readable_summary.md
Saved train predictions: /home/abmoses2000/solar_flare_aia/results/metrics/realistic_imbalance_aia_cnn_year_holdout_10to1_train_predictions.csv
Saved val predictions: /home/abmoses2000/solar_flare_aia/results/metrics/realistic_imbalance_aia_cnn_year_holdout_10to1_val_predictions.csv
Saved model: /home/abmoses2000/solar_flare_aia/results/models/realistic_imbalance_aia_cnn_year_holdout_10to1.pt

In [10]:
from IPython.display import display, Markdown

rows = []
for item in history:
    val_fixed = item["val_eval"]["metrics_at_0_5"]
    val_best = item["val_eval"]["metrics_at_best_tss_threshold"]

    rows.append({
        "epoch": item["epoch"],
        "train_loss": item["train_loss"],
        "val_roc_auc": item["val_eval"]["roc_auc"],
        "val_pr_auc": item["val_eval"]["pr_auc"],
        "val_tss_at_0_5": val_fixed["tss"],
        "val_f1_at_0_5": val_fixed["f1"],
        "best_tss_threshold": val_best["threshold"],
        "val_best_tss": val_best["tss"],
        "val_best_hss": val_best["hss"],
        "val_best_precision": val_best["precision"],
        "val_best_recall": val_best["recall"],
        "val_best_specificity": val_best["specificity"],
        "val_best_tp": val_best["tp"],
        "val_best_tn": val_best["tn"],
        "val_best_fp": val_best["fp"],
        "val_best_fn": val_best["fn"],
    })

summary_df = pd.DataFrame(rows)

display(Markdown("## Realistic class-imbalance sanity experiment — epoch summary"))
display(summary_df)

display(Markdown("## Final validation result at best-TSS threshold"))
display(pd.DataFrame([val_eval_final["metrics_at_best_tss_threshold"]]))

display(Markdown(f"""
**Final ROC-AUC:** {val_eval_final["roc_auc"]}

**Final PR-AUC:** {val_eval_final["pr_auc"]}

**Important:** This is not a final publication result. It is a realistic-imbalance sanity test before the formal AIA baseline.
"""))

## Realistic class-imbalance sanity experiment — epoch summary

,epoch,train_loss,val_roc_auc,val_pr_auc,val_tss_at_0_5,val_f1_at_0_5,best_tss_threshold,val_best_tss,val_best_hss,val_best_precision,val_best_recall,val_best_specificity,val_best_tp,val_best_tn,val_best_fp,val_best_fn
0,1,1.176922,0.726418,0.197983,0.288000,0.264516,0.4375,0.344000,0.153846,0.174377,0.653333,0.690667,49,518,232,26
1,2,1.134924,0.636178,0.125421,0.206667,0.206430,0.5700,0.253333,0.085183,0.133663,0.720000,0.533333,54,400,350,21
2,3,1.085398,0.620978,0.125558,0.101333,0.182163,0.4300,0.254667,0.064342,0.121479,0.920000,0.334667,69,251,499,6
3,4,1.071784,0.671520,0.147089,0.274667,0.232068,0.5075,0.288000,0.099861,0.141388,0.733333,0.554667,55,416,334,20
4,5,1.095123,0.652373,0.134679,0.224000,0.206795,0.6375,0.280000,0.100430,0.142091,0.706667,0.573333,53,430,320,22

## Final validation result at best-TSS threshold

,threshold,accuracy,precision,recall,specificity,f1,tss,hss,tp,tn,fp,fn
0,0.4375,0.687273,0.174377,0.653333,0.690667,0.275281,0.344,0.153846,49,518,232,26

**Final ROC-AUC:** 0.7264177777777778

**Final PR-AUC:** 0.19798268783934198

**Important:** This is not a final publication result. It is a realistic-imbalance sanity test before the formal AIA baseline.

## After the notebook finishes

Run these commands in the **VS Code terminal** to back up and commit outputs.

```bash
cd ~/solar_flare_aia

gcloud storage cp notebooks/training/03_aia_cnn_realistic_imbalance_year_holdout.ipynb \
  gs://suryabench-sharp-pipeline-bamidele/training_docs/

gcloud storage cp results/metrics/realistic_imbalance_aia_cnn_year_holdout_10to1_* \
  gs://suryabench-sharp-pipeline-bamidele/training_docs/

gcloud storage cp results/models/realistic_imbalance_aia_cnn_year_holdout_10to1.pt \
  gs://suryabench-sharp-pipeline-bamidele/training_models/

git add notebooks/training/03_aia_cnn_realistic_imbalance_year_holdout.ipynb
git add results/metrics/realistic_imbalance_aia_cnn_year_holdout_10to1_*

git commit -m "Add realistic-imbalance AIA CNN year-holdout experiment"
git push
```

Then stop the VM from your Mac Terminal or VS Code terminal:

```bash
gcloud compute instances stop solar-flare-aia-training-l4-c \
  --project=sonorous-shore-450510-i4 \
  --zone=europe-west4-c
```