
# AIA 2025–2026 HARP-Block v3 Sharded Miner — VM Ready

This notebook replaces the slow **six JSOC exports per individual sample** strategy.

## Core idea

Instead of:

```text
1 sample × 6 wavelengths = 6 JSOC export jobs
```

the miner groups required timestamps by **HARPNUM** and **24-hour blocks**:

```text
1 HARP/time block × 6 wavelength-sequence exports
→ many model-ready samples
```

Each wavelength request returns a tracked time series of active-region cutouts. The notebook then:

1. matches each returned AIA image to the required SHARP timestamp;
2. locally extracts the target-specific crop using the FITS WCS;
3. resizes it to `512 × 512`;
4. applies the same historical preprocessing used for 2010–2024;
5. stacks the six channels;
6. uploads each `.npz` immediately to Google Cloud Storage;
7. checkpoints sample and block progress for safe restart.

## Safety

The notebook defaults to `BLOCK_CANARY` mode. It must pass a small block test before `PRODUCTION` mode is enabled.

Official JSOC/DRMS behaviour used here:

- query form: `Series[timespan@cadence][wavelength]{image}`;
- `im_patch` server-side cutouts;
- `t=0` enables solar-rotation tracking;
- one pending export at a time per registered email;
- RequestIDs are saved and reopened after interruption.

## VM execution

Run this notebook on the prepared Compute Engine VM inside `tmux`.

For 2025:

```bash
export TARGET_YEAR=2025
export JSOC_EMAIL=abmoses2000@gmail.com
export WORKER_ID=aia2025
export RUN_MODE=BLOCK_CANARY
```

For 2026, after the 2025 block canary succeeds:

```bash
export TARGET_YEAR=2026
export JSOC_EMAIL=worky4work@gmail.com
export WORKER_ID=aia2026
export RUN_MODE=BLOCK_CANARY
```

After QA passes, change `RUN_MODE=PRODUCTION`.


> **Production sharding:** set `NUM_SHARDS` and `SHARD_INDEX` to split the deterministic block plan into non-overlapping workers. The default `NUM_SHARDS=1` preserves single-worker behaviour.

In [1]:

# The VM environment already contains most packages.
# This cell is safe to rerun and installs only missing dependencies.

%pip install -q --upgrade \
    "drms>=0.9.1" \
    "astropy>=7.0" \
    "sunpy[map]>=7.0" \
    "scikit-image>=0.25" \
    "google-cloud-storage>=3.0"

Note: you may need to restart the kernel to use updated packages.

In [2]:

import os
import re
import gc
import sys
import json
import time
import math
import shutil
import hashlib
import subprocess
from pathlib import Path
from datetime import datetime

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import drms
from drms.exceptions import DrmsExportError
from astropy.io import fits
from astropy import units as u
from astropy.coordinates import SkyCoord
from skimage.transform import resize
from skimage.metrics import structural_similarity

import sunpy.map

print("Python:", sys.version)
print("DRMS:", drms.__version__)
print("SunPy:", sunpy.__version__)

Python: 3.12.3 (main, Mar 23 2026, 19:04:32) [GCC 13.3.0]
DRMS: 0.9.1
SunPy: 7.1.2

/home/abmoses2000/solar_flare_aia/venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## 1. Configuration

In [3]:

# ============================================================
# ENVIRONMENT-AWARE CONFIGURATION
# ============================================================

PROJECT_ID = "sonorous-shore-450510-i4"
GCP_BUCKET = "gs://suryabench-sharp-pipeline-bamidele"

TARGET_YEAR = int(os.environ.get("TARGET_YEAR", "2025"))
JSOC_EMAIL = os.environ.get(
    "JSOC_EMAIL",
    "abmoses2000@gmail.com" if TARGET_YEAR == 2025 else "worky4work@gmail.com",
)
WORKER_ID = os.environ.get("WORKER_ID", f"aia{TARGET_YEAR}")
RUN_MODE = os.environ.get("RUN_MODE", "BLOCK_CANARY").upper()

# Deterministic, non-overlapping production sharding.
# Defaults preserve the original single-worker behaviour.
NUM_SHARDS = int(os.environ.get("NUM_SHARDS", "1"))
SHARD_INDEX = int(os.environ.get("SHARD_INDEX", "0"))

if RUN_MODE not in {"BLOCK_CANARY", "PRODUCTION"}:
    raise ValueError("RUN_MODE must be BLOCK_CANARY or PRODUCTION.")

if NUM_SHARDS < 1:
    raise ValueError("NUM_SHARDS must be at least 1.")

if not 0 <= SHARD_INDEX < NUM_SHARDS:
    raise ValueError(
        f"SHARD_INDEX must be in [0, {NUM_SHARDS - 1}], "
        f"received {SHARD_INDEX}."
    )

if RUN_MODE == "BLOCK_CANARY" and NUM_SHARDS != 1:
    raise ValueError(
        "BLOCK_CANARY must run with NUM_SHARDS=1. "
        "Use sharding only in PRODUCTION mode."
    )

AIA_WAVELENGTHS = [94, 131, 171, 193, 211, 335]
IMAGE_SIZE = 512

# Time grouping
BLOCK_HOURS = 24
TARGET_CADENCE_MIN = 96
MAX_TARGET_TIME_DIFFERENCE_SEC = 180
MAX_GAP_WITHIN_TRACK_SEC = 3 * 3600

# The server-side tracked patch is deliberately larger than the
# target-specific crop. Each target is then cropped locally using WCS.
BLOCK_PATCH_MARGIN_ARCSEC = 160.0
MIN_BLOCK_PATCH_ARCSEC = 300.0
MAX_BLOCK_PATCH_ARCSEC = 1100.0

# Historical geometry constants retained for compatibility with the pilot.
FULL_DISK_SIZE = 4096
IMAGE_CENTER = FULL_DISK_SIZE // 2
AIA_PIXEL_SCALE_ARCSEC = 0.6
SOLAR_RADIUS_ARCSEC = 976.0
SOLAR_RADIUS_PIX = SOLAR_RADIUS_ARCSEC / AIA_PIXEL_SCALE_ARCSEC
CROP_SCALE = 1.2
CROP_PADDING_PIX = 30
MIN_CROP_PIX = 64

# JSOC queue protection
JSOC_MAX_RETRIES = 10
JSOC_INITIAL_BACKOFF_SEC = 20
JSOC_MAX_BACKOFF_SEC = 300
JSOC_WAIT_TIMEOUT_SEC = 7200
JSOC_COOLDOWN_SEC = 12

# Runtime limits
MAX_BLOCKS_THIS_RUN = (
    int(os.environ["MAX_BLOCKS_THIS_RUN"])
    if os.environ.get("MAX_BLOCKS_THIS_RUN")
    else (1 if RUN_MODE == "BLOCK_CANARY" else None)
)
MIN_FREE_DISK_GB = 15

# The canary block is chosen around a previously successful individual sample.
CANARY_SAMPLE_IDS = {
    2025: [
        "20250602_1348_HARP13299_NOAA14100",
        "20250628_2248_HARP13424_NOAA14122",
    ],
    2026: [
        "20260210_0400_HARP14361_NOAA14370",
        "20260211_1648_HARP14371_NOAA14373",
    ],
}

BASE = Path.home() / "solar_flare_aia"
LOCAL_ROOT = BASE / "harp_block_miner" / f"{RUN_MODE.lower()}_{WORKER_ID}"
LOCAL_META = LOCAL_ROOT / "metadata"
LOCAL_TEMP = LOCAL_ROOT / "temp_blocks"
LOCAL_OUTPUT = LOCAL_ROOT / "samples_npz"
LOCAL_LOG = LOCAL_META / f"sample_log_{WORKER_ID}.csv"
LOCAL_BLOCK_LOG = LOCAL_META / f"block_log_{WORKER_ID}.csv"
LOCAL_BLOCK_PLAN = LOCAL_META / f"block_plan_{WORKER_ID}.csv"

for directory in [LOCAL_ROOT, LOCAL_META, LOCAL_TEMP, LOCAL_OUTPUT]:
    directory.mkdir(parents=True, exist_ok=True)

if RUN_MODE == "BLOCK_CANARY":
    GCP_RUN_ROOT = f"{GCP_BUCKET}/jsoc_harp_block_canary_v1/{WORKER_ID}"
else:
    GCP_RUN_ROOT = f"{GCP_BUCKET}/jsoc_2025_2026_production_v1"

GCP_OUTPUT_ROOT = f"{GCP_RUN_ROOT}/samples_npz/{TARGET_YEAR}"
GCP_WORKER_META = f"{GCP_RUN_ROOT}/metadata/workers/{WORKER_ID}"

GCP_METADATA_CANDIDATES = [
    f"{GCP_BUCKET}/metadata/curated_sharp_suryabench_true96min_48h_AR_SPECIFIC_2010_2026.csv",
    f"{GCP_BUCKET}/metadata/curated_2025_2026_AR_SPECIFIC_EXTENSION.csv",
]

PILOT_GCP_ROOT = (
    f"{GCP_BUCKET}/jsoc_2025_2026_pilot/samples_npz/{TARGET_YEAR}"
)

print("=" * 80)
print("TARGET_YEAR:", TARGET_YEAR)
print("JSOC_EMAIL:", JSOC_EMAIL)
print("WORKER_ID:", WORKER_ID)
print("RUN_MODE:", RUN_MODE)
print("NUM_SHARDS:", NUM_SHARDS)
print("SHARD_INDEX:", SHARD_INDEX)
print("MAX_BLOCKS_THIS_RUN:", MAX_BLOCKS_THIS_RUN)
print("LOCAL_ROOT:", LOCAL_ROOT)
print("GCP_OUTPUT_ROOT:", GCP_OUTPUT_ROOT)
print("=" * 80)

================================================================================
TARGET_YEAR: 2025
JSOC_EMAIL: abmoses2000@gmail.com
WORKER_ID: aia2025-s0
RUN_MODE: PRODUCTION
NUM_SHARDS: 4
SHARD_INDEX: 0
MAX_BLOCKS_THIS_RUN: None
LOCAL_ROOT: /home/abmoses2000/solar_flare_aia/harp_block_miner/production_aia2025-s0
GCP_OUTPUT_ROOT: gs://suryabench-sharp-pipeline-bamidele/jsoc_2025_2026_production_v1/samples_npz/2025
================================================================================

## 2. Cloud and JSOC preflight

In [4]:

def run_command(command, check=True, capture=True):
    result = subprocess.run(
        command,
        text=True,
        capture_output=capture,
    )
    if check and result.returncode != 0:
        raise RuntimeError(
            f"Command failed ({result.returncode}): {' '.join(command)}\n"
            f"{result.stderr[-3000:] if result.stderr else ''}"
        )
    return result


def gcp_exists(path):
    return run_command(
        ["gcloud", "storage", "ls", path],
        check=False,
    ).returncode == 0


print("Bucket access:")
bucket_test = run_command(
    ["gcloud", "storage", "ls", GCP_BUCKET],
    check=True,
)
print(bucket_test.stdout[:1000])
print("✅ Bucket access works.")

jsoc_public = drms.Client()
registered = jsoc_public.check_email(JSOC_EMAIL)
print("JSOC registered:", registered, "|", JSOC_EMAIL)
if not registered:
    raise RuntimeError(f"JSOC email is not registered: {JSOC_EMAIL}")

jsoc = drms.Client(email=JSOC_EMAIL)
assert jsoc.email == JSOC_EMAIL
print("✅ JSOC client is using the intended email.")

Bucket access:

gs://suryabench-sharp-pipeline-bamidele/baseline_results/
gs://suryabench-sharp-pipeline-bamidele/jsoc_2025_2026_canary/
gs://suryabench-sharp-pipeline-bamidele/jsoc_2025_2026_pilot/
gs://suryabench-sharp-pipeline-bamidele/jsoc_2025_2026_production_v1/
gs://suryabench-sharp-pipeline-bamidele/jsoc_2026_canary_parallel/
gs://suryabench-sharp-pipeline-bamidele/jsoc_harp_block_canary_v1/
gs://suryabench-sharp-pipeline-bamidele/manifests/
gs://suryabench-sharp-pipeline-bamidele/metadata/
gs://suryabench-sharp-pipeline-bamidele/samples_npz/

✅ Bucket access works.

JSOC registered: True | abmoses2000@gmail.com

✅ JSOC client is using the intended email.

## 3. Load and validate corrected AR-specific metadata

In [5]:

def copy_first_existing(candidates, destination):
    for candidate in candidates:
        print("Checking:", candidate)
        if not gcp_exists(candidate):
            continue
        run_command(
            ["gcloud", "storage", "cp", candidate, str(destination)],
            check=True,
        )
        if destination.exists() and destination.stat().st_size > 0:
            print("✅ Copied:", candidate)
            return candidate
    raise FileNotFoundError("No compatible corrected metadata file was found.")


metadata_path = LOCAL_META / "corrected_ar_specific_metadata.csv"
metadata_source = copy_first_existing(
    GCP_METADATA_CANDIDATES,
    metadata_path,
)

raw_df = pd.read_csv(metadata_path, low_memory=False)
print("Raw metadata:", raw_df.shape)

Checking: gs://suryabench-sharp-pipeline-bamidele/metadata/curated_sharp_suryabench_true96min_48h_AR_SPECIFIC_2010_2026.csv

✅ Copied: gs://suryabench-sharp-pipeline-bamidele/metadata/curated_sharp_suryabench_true96min_48h_AR_SPECIFIC_2010_2026.csv

Raw metadata: (141644, 50)

In [6]:

def clean_noaa(value):
    if pd.isna(value):
        return np.nan
    try:
        number = int(float(value))
        return number if number > 0 else np.nan
    except Exception:
        matches = re.findall(r"\d+", str(value))
        return int(matches[0]) if matches else np.nan


def prepare_metadata(frame):
    frame = frame.copy()

    frame["T_REC_dt"] = pd.to_datetime(
        frame["T_REC_dt"],
        errors="coerce",
    )

    if "NOAA_AR_clean" not in frame.columns:
        source = "NOAA_ARS" if "NOAA_ARS" in frame.columns else "NOAA_AR"
        frame["NOAA_AR_clean"] = frame[source].apply(clean_noaa)

    label_source = next(
        (
            column
            for column in [
                "label_48h_final",
                "label_48h_ar_specific",
                "label_48h",
            ]
            if column in frame.columns
        ),
        None,
    )
    if label_source is None:
        raise ValueError("No AR-specific 48-hour label column exists.")

    frame["label_48h_final"] = pd.to_numeric(
        frame[label_source],
        errors="coerce",
    )
    frame["HARPNUM"] = pd.to_numeric(frame["HARPNUM"], errors="coerce")
    frame["NOAA_AR_clean"] = pd.to_numeric(
        frame["NOAA_AR_clean"],
        errors="coerce",
    )

    required = [
        "T_REC_dt", "HARPNUM", "NOAA_AR_clean", "label_48h_final",
        "LON_MIN", "LON_MAX", "LAT_MIN", "LAT_MAX",
    ]
    missing = [column for column in required if column not in frame.columns]
    if missing:
        raise ValueError(f"Missing required columns: {missing}")

    frame = frame.dropna(subset=required).copy()
    frame["HARPNUM"] = frame["HARPNUM"].astype(int)
    frame["NOAA_AR_clean"] = frame["NOAA_AR_clean"].astype(int)
    frame["label_48h_final"] = frame["label_48h_final"].astype(int)

    if "sample_id" not in frame.columns:
        frame["sample_id"] = frame.apply(
            lambda row: (
                f"{row['T_REC_dt'].strftime('%Y%m%d_%H%M')}"
                f"_HARP{row['HARPNUM']}"
                f"_NOAA{row['NOAA_AR_clean']}"
            ),
            axis=1,
        )

    frame["year"] = frame["T_REC_dt"].dt.year
    frame = frame[frame["year"] == TARGET_YEAR].copy()

    # 2026 rows in the source file were already created using a safe
    # complete-future-window cutoff. Preserve that curated selection.
    frame = (
        frame.drop_duplicates("sample_id")
        .sort_values(["HARPNUM", "T_REC_dt"])
        .reset_index(drop=True)
    )

    return frame


df = prepare_metadata(raw_df)

print("Prepared rows:", len(df))
print(df["label_48h_final"].value_counts().sort_index())
print("Unique HARPs:", df["HARPNUM"].nunique())

expected_rows = 14774 if TARGET_YEAR == 2025 else 3201
if len(df) != expected_rows:
    raise RuntimeError(
        f"Expected {expected_rows} curated rows for {TARGET_YEAR}, "
        f"but found {len(df)}."
    )

print("✅ Metadata count matches the curated year total.")

Prepared rows: 14774
label_48h_final
0    13954
1      820
Name: count, dtype: int64
Unique HARPs: 261
✅ Metadata count matches the curated year total.

## 4. Geometry and preprocessing

In [7]:

def lonlat_to_pixel(lon_deg, lat_deg):
    lon = np.deg2rad(float(lon_deg))
    lat = np.deg2rad(float(lat_deg))
    x = IMAGE_CENTER + SOLAR_RADIUS_PIX * np.cos(lat) * np.sin(lon)
    y = IMAGE_CENTER - SOLAR_RADIUS_PIX * np.sin(lat)
    return float(x), float(y)


def target_geometry(row):
    corners = [
        (row["LON_MIN"], row["LAT_MIN"]),
        (row["LON_MIN"], row["LAT_MAX"]),
        (row["LON_MAX"], row["LAT_MIN"]),
        (row["LON_MAX"], row["LAT_MAX"]),
    ]
    pixels = [lonlat_to_pixel(lon, lat) for lon, lat in corners]
    xs = [item[0] for item in pixels]
    ys = [item[1] for item in pixels]

    center_x_pix = (min(xs) + max(xs)) / 2.0
    center_y_pix = (min(ys) + max(ys)) / 2.0

    width_pix = max(max(xs) - min(xs), MIN_CROP_PIX)
    height_pix = max(max(ys) - min(ys), MIN_CROP_PIX)
    crop_pix = max(width_pix, height_pix) * CROP_SCALE + CROP_PADDING_PIX

    return {
        "x_arcsec": (center_x_pix - IMAGE_CENTER) * AIA_PIXEL_SCALE_ARCSEC,
        "y_arcsec": (IMAGE_CENTER - center_y_pix) * AIA_PIXEL_SCALE_ARCSEC,
        "box_arcsec": crop_pix * AIA_PIXEL_SCALE_ARCSEC,
    }


def historical_preprocess(image):
    image = np.asarray(image, dtype=np.float32)
    image = np.nan_to_num(image, nan=0.0, posinf=0.0, neginf=0.0)
    image = np.clip(image, 0, None)
    image = np.log1p(image)

    low = float(image.min())
    high = float(image.max())
    if high <= low:
        return np.zeros_like(image, dtype=np.float32)

    return ((image - low) / (high - low)).astype(np.float32)


def read_map(path):
    solar_map = sunpy.map.Map(path)
    data = np.asarray(solar_map.data, dtype=np.float32)
    return solar_map, data


def crop_target_from_block(fits_path, row):
    solar_map, data = read_map(fits_path)
    geometry = target_geometry(row)

    coordinate = SkyCoord(
        geometry["x_arcsec"] * u.arcsec,
        geometry["y_arcsec"] * u.arcsec,
        frame=solar_map.coordinate_frame,
    )
    pixel = solar_map.world_to_pixel(coordinate)
    center_x = float(pixel.x.value)
    center_y = float(pixel.y.value)

    scale_x = abs(float(solar_map.scale.axis1.to_value(u.arcsec / u.pix)))
    scale_y = abs(float(solar_map.scale.axis2.to_value(u.arcsec / u.pix)))
    half_width = geometry["box_arcsec"] / (2.0 * scale_x)
    half_height = geometry["box_arcsec"] / (2.0 * scale_y)

    x0 = int(math.floor(center_x - half_width))
    x1 = int(math.ceil(center_x + half_width))
    y0 = int(math.floor(center_y - half_height))
    y1 = int(math.ceil(center_y + half_height))

    if x0 < 0 or y0 < 0 or x1 > data.shape[1] or y1 > data.shape[0]:
        raise ValueError(
            f"Target crop leaves block patch: "
            f"bounds={(x0, x1, y0, y1)}, shape={data.shape}"
        )

    crop = data[y0:y1, x0:x1]
    if crop.size == 0:
        raise ValueError("Empty local crop.")

    resized = resize(
        crop,
        (IMAGE_SIZE, IMAGE_SIZE),
        anti_aliasing=True,
        preserve_range=True,
    )
    return historical_preprocess(resized), {
        "block_shape": list(data.shape),
        "local_bounds": [x0, x1, y0, y1],
        "target_geometry": geometry,
    }


print("✅ Geometry and preprocessing functions ready.")

✅ Geometry and preprocessing functions ready.

## 5. Create HARP/time blocks

In [8]:

def make_blocks(frame, block_hours=24):
    blocks = []

    for harpnum, group in frame.groupby("HARPNUM"):
        group = group.sort_values("T_REC_dt").copy()
        current_indices = []
        block_start = None
        previous_time = None

        for index, row in group.iterrows():
            timestamp = pd.Timestamp(row["T_REC_dt"])

            must_split = False
            if block_start is not None:
                elapsed_hours = (
                    timestamp - block_start
                ).total_seconds() / 3600.0

                gap_seconds = (
                    timestamp - previous_time
                ).total_seconds()

                must_split = (
                    elapsed_hours >= block_hours
                    or gap_seconds > MAX_GAP_WITHIN_TRACK_SEC
                )

            if must_split and current_indices:
                blocks.append(group.loc[current_indices].copy())
                current_indices = []
                block_start = None

            if block_start is None:
                block_start = timestamp

            current_indices.append(index)
            previous_time = timestamp

        if current_indices:
            blocks.append(group.loc[current_indices].copy())

    plan_rows = []
    block_frames = {}

    for number, block in enumerate(blocks):
        first = block["T_REC_dt"].min()
        last = block["T_REC_dt"].max()
        harpnum = int(block["HARPNUM"].iloc[0])
        block_id = (
            f"{TARGET_YEAR}_HARP{harpnum}_"
            f"{first.strftime('%Y%m%d_%H%M')}_"
            f"{last.strftime('%Y%m%d_%H%M')}"
        )

        block_frames[block_id] = block.reset_index(drop=True)
        plan_rows.append(
            {
                "block_id": block_id,
                "HARPNUM": harpnum,
                "start": first,
                "end": last,
                "n_targets": len(block),
                "n_positive": int(block["label_48h_final"].sum()),
            }
        )

    return pd.DataFrame(plan_rows), block_frames


block_plan, block_frames = make_blocks(df, BLOCK_HOURS)

if RUN_MODE == "BLOCK_CANARY":
    wanted_ids = set(CANARY_SAMPLE_IDS[TARGET_YEAR])
    canary_block_ids = []

    for block_id, block in block_frames.items():
        if set(block["sample_id"]).intersection(wanted_ids):
            canary_block_ids.append(block_id)

    if not canary_block_ids:
        raise RuntimeError("No block contains the configured canary samples.")

    block_plan = block_plan[
        block_plan["block_id"].isin(canary_block_ids)
    ].copy()

block_plan = block_plan.sort_values(
    ["start", "HARPNUM", "block_id"]
).reset_index(drop=True)

# Preserve a stable global block index before selecting a shard.
block_plan["global_block_index"] = np.arange(len(block_plan), dtype=int)

if RUN_MODE == "PRODUCTION" and NUM_SHARDS > 1:
    total_blocks_before_sharding = len(block_plan)
    total_targets_before_sharding = int(block_plan["n_targets"].sum())

    block_plan = block_plan[
        block_plan["global_block_index"] % NUM_SHARDS == SHARD_INDEX
    ].copy().reset_index(drop=True)

    print(
        f"Shard {SHARD_INDEX}/{NUM_SHARDS - 1}: selected "
        f"{len(block_plan)} of {total_blocks_before_sharding} blocks."
    )
    print(
        "Targets in selected shard:",
        int(block_plan["n_targets"].sum()),
        "of",
        total_targets_before_sharding,
    )
else:
    print("Sharding disabled: using the complete selected block plan.")

block_plan["num_shards"] = NUM_SHARDS
block_plan["shard_index"] = SHARD_INDEX

block_plan.to_csv(LOCAL_BLOCK_PLAN, index=False)
run_command(
    [
        "gcloud", "storage", "cp",
        str(LOCAL_BLOCK_PLAN),
        f"{GCP_WORKER_META}/{LOCAL_BLOCK_PLAN.name}",
    ],
    check=True,
)

print("Blocks selected:", len(block_plan))
print("Targets represented:", int(block_plan["n_targets"].sum()))
display(block_plan.head(20))

Shard 0/3: selected 372 of 1486 blocks.
Targets in selected shard: 3664 of 14774

Blocks selected: 372
Targets represented: 3664

,block_id,HARPNUM,start,end,n_targets,n_positive,global_block_index,num_shards,shard_index
0,2025_HARP12492_20250101_0100_20250101_2348,12492,2025-01-01 01:00:00,2025-01-01 23:48:00,15,15,0,4,0
1,2025_HARP12511_20250101_1024_20250101_1648,12511,2025-01-01 10:24:00,2025-01-01 16:48:00,5,0,4,4,0
2,2025_HARP12511_20250102_0912_20250102_0912,12511,2025-01-02 09:12:00,2025-01-02 09:12:00,1,0,8,4,0
3,2025_HARP12511_20250103_1324_20250104_1148,12511,2025-01-03 13:24:00,2025-01-04 11:48:00,15,0,12,4,0
4,2025_HARP12506_20250104_0900_20250105_0724,12506,2025-01-04 09:00:00,2025-01-05 07:24:00,15,0,16,4,0
5,2025_HARP12541_20250105_0712_20250106_0536,12541,2025-01-05 07:12:00,2025-01-06 05:36:00,15,0,20,4,0
6,2025_HARP12540_20250105_1512_20250106_1024,12540,2025-01-05 15:12:00,2025-01-06 10:24:00,13,0,24,4,0
7,2025_HARP12515_20250106_0924_20250106_1724,12515,2025-01-06 09:24:00,2025-01-06 17:24:00,6,0,28,4,0
8,2025_HARP12532_20250106_2048_20250107_1924,12532,2025-01-06 20:48:00,2025-01-07 19:24:00,15,12,32,4,0
9,2025_HARP12515_20250107_2048_20250108_0000,12515,2025-01-07 20:48:00,2025-01-08 00:00:00,3,0,36,4,0
10,2025_HARP12537_20250108_0700_20250108_1324,12537,2025-01-08 07:00:00,2025-01-08 13:24:00,5,0,40,4,0
11,2025_HARP12540_20250108_0900_20250108_1212,12540,2025-01-08 09:00:00,2025-01-08 12:12:00,3,0,44,4,0
12,2025_HARP12532_20250108_2000_20250109_1824,12532,2025-01-08 20:00:00,2025-01-09 18:24:00,15,3,48,4,0
13,2025_HARP12532_20250109_2000_20250110_0912,12532,2025-01-09 20:00:00,2025-01-10 09:12:00,9,0,52,4,0
14,2025_HARP12546_20250110_1936_20250111_0648,12546,2025-01-10 19:36:00,2025-01-11 06:48:00,8,0,56,4,0
15,2025_HARP12537_20250111_2200_20250112_0424,12537,2025-01-11 22:00:00,2025-01-12 04:24:00,5,0,60,4,0
16,2025_HARP12572_20250112_1312_20250112_1624,12572,2025-01-12 13:12:00,2025-01-12 16:24:00,3,0,64,4,0
17,2025_HARP12597_20250114_0124_20250114_0436,12597,2025-01-14 01:24:00,2025-01-14 04:36:00,3,0,68,4,0
18,2025_HARP12598_20250114_0924_20250115_0612,12598,2025-01-14 09:24:00,2025-01-15 06:12:00,14,0,72,4,0
19,2025_HARP12597_20250114_1412_20250114_1412,12597,2025-01-14 14:12:00,2025-01-14 14:12:00,1,0,76,4,0

## 6. Discover completed outputs and restore checkpoints

In [9]:

def download_if_exists(gcp_path, local_path):
    if not gcp_exists(gcp_path):
        return False
    run_command(
        ["gcloud", "storage", "cp", gcp_path, str(local_path)],
        check=True,
    )
    return True


download_if_exists(
    f"{GCP_WORKER_META}/{LOCAL_LOG.name}",
    LOCAL_LOG,
)
download_if_exists(
    f"{GCP_WORKER_META}/{LOCAL_BLOCK_LOG.name}",
    LOCAL_BLOCK_LOG,
)

sample_log = (
    pd.read_csv(LOCAL_LOG, low_memory=False)
    if LOCAL_LOG.exists() and LOCAL_LOG.stat().st_size > 0
    else pd.DataFrame()
)
block_log = (
    pd.read_csv(LOCAL_BLOCK_LOG, low_memory=False)
    if LOCAL_BLOCK_LOG.exists() and LOCAL_BLOCK_LOG.stat().st_size > 0
    else pd.DataFrame()
)

# The object listing is the source of truth for completed model-ready files.
listing = run_command(
    ["gcloud", "storage", "ls", "--recursive", GCP_OUTPUT_ROOT],
    check=False,
)
completed_sample_ids = {
    Path(line.strip()).stem
    for line in listing.stdout.splitlines()
    if line.strip().endswith(".npz")
}

print("Completed GCP samples already present:", len(completed_sample_ids))
print("Sample log rows:", len(sample_log))
print("Block log rows:", len(block_log))

Completed GCP samples already present: 12101
Sample log rows: 1892
Block log rows: 372

## 7. Retry-safe JSOC block export

## v2 cadence-phase fix
This version detects multiple 96-minute cadence phases inside one HARP block, reuses any compatible cached FITS files, and submits extra sequence exports only for uncovered timestamp phases.

In [10]:

def parse_jsoc_time(value):
    try:
        return pd.Timestamp(drms.to_datetime(str(value)))
    except Exception:
        text = str(value).replace("_TAI", "").replace("Z", "")
        return pd.to_datetime(text, errors="coerce")


def extract_request_id(message):
    match = re.search(r"(JSOC_\d{8}_\d+)", str(message))
    return match.group(1) if match else None


def wait_for_existing_request(request_id):
    print("Waiting for existing RequestID:", request_id)
    old_request = jsoc.export_from_id(request_id)
    old_request.wait(
        timeout=JSOC_WAIT_TIMEOUT_SEC,
        sleep=15,
        retries_notfound=30,
    )
    print(
        "Existing request status:",
        old_request.status,
        "succeeded:",
        old_request.has_succeeded(),
    )


def submit_export_retry_safe(query_string, process):
    delay = JSOC_INITIAL_BACKOFF_SEC
    last_error = None

    for attempt in range(1, JSOC_MAX_RETRIES + 1):
        try:
            print(
                f"JSOC export attempt {attempt}/{JSOC_MAX_RETRIES}"
            )
            request = jsoc.export(
                query_string,
                method="url",
                protocol="fits",
                email=JSOC_EMAIL,
                process=process,
            )
            request.wait(
                timeout=JSOC_WAIT_TIMEOUT_SEC,
                sleep=15,
                retries_notfound=30,
            )

            if not request.has_succeeded():
                raise RuntimeError(
                    f"Request failed: id={request.id}, "
                    f"status={request.status}"
                )
            return request

        except DrmsExportError as error:
            last_error = error
            message = str(error)

            if "pending export requests" not in message.lower():
                raise

            request_id = extract_request_id(message)
            print("JSOC pending-request protection triggered.")
            print(message)

            if request_id:
                try:
                    wait_for_existing_request(request_id)
                except Exception as wait_error:
                    print("Could not reopen old request:", repr(wait_error))

            print(f"Sleeping {delay} seconds...")
            time.sleep(delay)
            delay = min(delay * 2, JSOC_MAX_BACKOFF_SEC)

    raise RuntimeError(
        f"JSOC remained busy after all retries: {last_error}"
    )


def format_query_time(timestamp):
    return pd.Timestamp(timestamp).strftime("%Y-%m-%dT%H:%M:%S.000")


def split_block_into_cadence_segments(block):
    """Split a HARP block when target times change cadence phase."""
    block = block.sort_values("T_REC_dt").reset_index(drop=True).copy()
    cadence_seconds = TARGET_CADENCE_MIN * 60
    segments = []
    current_rows = [0]

    for position in range(1, len(block)):
        previous_time = pd.Timestamp(block.loc[position - 1, "T_REC_dt"])
        current_time = pd.Timestamp(block.loc[position, "T_REC_dt"])
        gap_seconds = (current_time - previous_time).total_seconds()
        cadence_steps = max(1, int(round(gap_seconds / cadence_seconds)))
        phase_error_seconds = abs(gap_seconds - cadence_steps * cadence_seconds)

        if phase_error_seconds > MAX_TARGET_TIME_DIFFERENCE_SEC:
            segments.append(block.loc[current_rows].copy())
            current_rows = [position]
        else:
            current_rows.append(position)

    if current_rows:
        segments.append(block.loc[current_rows].copy())

    return [segment.reset_index(drop=True) for segment in segments]


def files_cover_targets(files, target_frame):
    """Check that every target has a FITS file within the time tolerance."""
    files = [Path(item) for item in files if str(item).lower().endswith(".fits")]
    if not files:
        return False

    try:
        indexed = index_downloaded_files(files)
    except Exception:
        return False

    available_times = [item[0] for item in indexed]
    for target in pd.to_datetime(target_frame["T_REC_dt"]):
        nearest_delta = min(
            abs((timestamp - pd.Timestamp(target)).total_seconds())
            for timestamp in available_times
        )
        if nearest_delta > MAX_TARGET_TIME_DIFFERENCE_SEC:
            return False
    return True


def build_segment_export(segment, wavelength, segment_directory):
    segment_directory.mkdir(parents=True, exist_ok=True)
    metadata_json = segment_directory / "export_metadata.json"

    for partial in segment_directory.glob("*.part"):
        partial.unlink(missing_ok=True)

    existing_fits = sorted(segment_directory.glob("*.fits"))
    if metadata_json.exists() and existing_fits and files_cover_targets(existing_fits, segment):
        with metadata_json.open() as handle:
            saved = json.load(handle)
        print(f"♻️ Reusing {len(existing_fits)} cadence-aligned files for {wavelength} Å")
        return existing_fits, saved

    segment = segment.sort_values("T_REC_dt").reset_index(drop=True)
    start = pd.Timestamp(segment["T_REC_dt"].min())
    end = pd.Timestamp(segment["T_REC_dt"].max())
    duration_minutes = max(
        TARGET_CADENCE_MIN,
        int(math.ceil((end - start).total_seconds() / 60.0)) + TARGET_CADENCE_MIN,
    )

    reference_time = start + (end - start) / 2
    reference_index = (segment["T_REC_dt"] - reference_time).abs().idxmin()
    reference_row = segment.loc[reference_index]
    reference_geometry = target_geometry(reference_row)

    max_target_box = max(target_geometry(row)["box_arcsec"] for _, row in segment.iterrows())
    patch_size = np.clip(
        max_target_box + BLOCK_PATCH_MARGIN_ARCSEC,
        MIN_BLOCK_PATCH_ARCSEC,
        MAX_BLOCK_PATCH_ARCSEC,
    )

    query_string = (
        f"aia.lev1_euv_12s"
        f"[{format_query_time(start)}/{duration_minutes}m@{TARGET_CADENCE_MIN}m]"
        f"[{int(wavelength)}]"
        f"{{image}}"
    )

    process = {
        "im_patch": {
            "t_ref": format_query_time(reference_time),
            "t": 0,
            "r": 0,
            "c": 0,
            "locunits": "arcsec",
            "boxunits": "arcsec",
            "x": reference_geometry["x_arcsec"],
            "y": reference_geometry["y_arcsec"],
            "width": float(patch_size),
            "height": float(patch_size),
        }
    }

    print("Segment query:", query_string)
    print("Segment reference:", reference_time, "| targets:", len(segment), "| patch arcsec:", float(patch_size))

    request = submit_export_retry_safe(query_string, process)
    request.download(segment_directory, timeout=600)

    fits_files = sorted(segment_directory.glob("*.fits"))
    if not fits_files:
        raise FileNotFoundError(f"No FITS files downloaded for {wavelength} Å segment.")
    if not files_cover_targets(fits_files, segment):
        raise RuntimeError(
            f"Downloaded {wavelength} Å segment does not cover all target timestamps within "
            f"{MAX_TARGET_TIME_DIFFERENCE_SEC} seconds."
        )

    metadata = {
        "request_id": request.id,
        "query": query_string,
        "wavelength": int(wavelength),
        "reference_time": str(reference_time),
        "segment_start": str(start),
        "segment_end": str(end),
        "segment_targets": int(len(segment)),
        "patch_size_arcsec": float(patch_size),
        "reference_geometry": reference_geometry,
        "n_files": len(fits_files),
        "email": JSOC_EMAIL,
    }
    with metadata_json.open("w") as handle:
        json.dump(metadata, handle, indent=2)

    time.sleep(JSOC_COOLDOWN_SEC)
    return fits_files, metadata


def build_block_export(block, wavelength, block_directory):
    """Export one or more cadence-aligned sequences for a HARP block."""
    block_directory.mkdir(parents=True, exist_ok=True)
    wave_directory = block_directory / str(wavelength)
    wave_directory.mkdir(parents=True, exist_ok=True)

    segments = split_block_into_cadence_segments(block)
    print(
        f"{wavelength} Å cadence segments:",
        len(segments),
        [(str(s["T_REC_dt"].min()), str(s["T_REC_dt"].max()), len(s)) for s in segments],
    )

    request_ids = []
    for segment_number, segment in enumerate(segments, start=1):
        cached_files = sorted(wave_directory.rglob("*.fits"))
        if files_cover_targets(cached_files, segment):
            print(
                f"♻️ Segment {segment_number}/{len(segments)} already covered by cached "
                f"{wavelength} Å files."
            )
            continue

        start = pd.Timestamp(segment["T_REC_dt"].min())
        end = pd.Timestamp(segment["T_REC_dt"].max())
        segment_name = (
            f"segment_{segment_number:02d}_"
            f"{start.strftime('%Y%m%d_%H%M')}_"
            f"{end.strftime('%Y%m%d_%H%M')}"
        )
        segment_directory = wave_directory / segment_name
        _, segment_metadata = build_segment_export(segment, wavelength, segment_directory)
        request_ids.append(str(segment_metadata["request_id"]))

    all_fits = sorted(wave_directory.rglob("*.fits"))
    if not all_fits:
        raise FileNotFoundError(f"No complete FITS files available for {wavelength} Å.")

    if not files_cover_targets(all_fits, block):
        uncovered = []
        indexed = index_downloaded_files(all_fits)
        available_times = [item[0] for item in indexed]
        for target in pd.to_datetime(block["T_REC_dt"]):
            nearest_delta = min(
                abs((timestamp - pd.Timestamp(target)).total_seconds())
                for timestamp in available_times
            )
            if nearest_delta > MAX_TARGET_TIME_DIFFERENCE_SEC:
                uncovered.append({
                    "target": str(target),
                    "nearest_delta_seconds": float(nearest_delta),
                })
        raise RuntimeError(f"{wavelength} Å block remains incompletely covered: {uncovered[:10]}")

    for metadata_path in wave_directory.rglob("export_metadata.json"):
        try:
            with metadata_path.open() as handle:
                item = json.load(handle)
            request_id = item.get("request_id")
            if request_id:
                request_ids.append(str(request_id))
        except Exception:
            pass

    request_ids = sorted(set(request_ids))
    combined_metadata = {
        "request_id": ",".join(request_ids) if request_ids else "cached",
        "request_ids": request_ids,
        "wavelength": int(wavelength),
        "n_segments": int(len(segments)),
        "n_files": int(len(all_fits)),
        "coverage_verified": True,
        "max_time_difference_seconds": int(MAX_TARGET_TIME_DIFFERENCE_SEC),
        "email": JSOC_EMAIL,
    }
    return all_fits, combined_metadata


def fits_observation_time(path):
    with fits.open(path, memmap=False) as hdul:
        headers = [
            hdu.header
            for hdu in hdul
            if getattr(hdu, "header", None) is not None
        ]

    for header in headers:
        for key in ["T_REC", "DATE-OBS", "DATE_OBS", "T_OBS"]:
            if key in header:
                parsed = parse_jsoc_time(header[key])
                if not pd.isna(parsed):
                    return pd.Timestamp(parsed)

    raise ValueError(f"No observation time found in {path}")


def index_downloaded_files(files):
    indexed = []
    for path in files:
        try:
            timestamp = fits_observation_time(path)
            indexed.append((timestamp, path))
        except Exception as error:
            print("Skipping unreadable FITS time:", path, repr(error))

    if not indexed:
        raise RuntimeError("No downloaded FITS file has a valid timestamp.")

    return sorted(indexed, key=lambda item: item[0])


def nearest_file(indexed_files, target_time):
    target_time = pd.Timestamp(target_time)
    timestamp, path = min(
        indexed_files,
        key=lambda item: abs((item[0] - target_time).total_seconds()),
    )
    difference = abs((timestamp - target_time).total_seconds())

    if difference > MAX_TARGET_TIME_DIFFERENCE_SEC:
        raise ValueError(
            f"Nearest AIA file is {difference:.1f}s from target "
            f"{target_time}."
        )

    return path, timestamp, float(difference)

## 8. Save, upload and checkpoint model-ready samples

In [11]:

def free_disk_gb(path):
    usage = shutil.disk_usage(path)
    return usage.free / (1024 ** 3)


def upload_verified(local_path, gcp_path):
    run_command(
        ["gcloud", "storage", "cp", str(local_path), gcp_path],
        check=True,
    )
    if not gcp_exists(gcp_path):
        raise RuntimeError(f"Upload verification failed: {gcp_path}")


def append_checkpoint(frame, row, local_path, gcp_path):
    updated = pd.concat(
        [frame, pd.DataFrame([row])],
        ignore_index=True,
    )
    updated = updated.drop_duplicates(
        subset=["sample_id"],
        keep="last",
    )
    updated.to_csv(local_path, index=False)
    run_command(
        ["gcloud", "storage", "cp", str(local_path), gcp_path],
        check=True,
    )
    return updated


def append_block_checkpoint(frame, row):
    updated = pd.concat(
        [frame, pd.DataFrame([row])],
        ignore_index=True,
    )
    updated = updated.drop_duplicates(
        subset=["block_id"],
        keep="last",
    )
    updated.to_csv(LOCAL_BLOCK_LOG, index=False)
    run_command(
        [
            "gcloud", "storage", "cp",
            str(LOCAL_BLOCK_LOG),
            f"{GCP_WORKER_META}/{LOCAL_BLOCK_LOG.name}",
        ],
        check=True,
    )
    return updated


def process_block(block_id, block, sample_log):
    block_started = time.time()
    block_directory = LOCAL_TEMP / block_id
    block_directory.mkdir(parents=True, exist_ok=True)

    pending = block[
        ~block["sample_id"].isin(completed_sample_ids)
    ].copy()

    if len(pending) == 0:
        return sample_log, {
            "block_id": block_id,
            "status": "already_complete",
            "n_targets": len(block),
            "n_saved_this_run": 0,
            "elapsed_minutes": 0.0,
            "message": "all_samples_already_in_gcp",
        }

    if free_disk_gb(LOCAL_ROOT) < MIN_FREE_DISK_GB:
        raise RuntimeError(
            f"Free disk below {MIN_FREE_DISK_GB} GB."
        )

    wavelength_indices = {}
    wavelength_export_meta = {}

    for wavelength in AIA_WAVELENGTHS:
        print("\n" + "-" * 70)
        print(block_id, "| wavelength", wavelength)
        files, export_meta = build_block_export(
            block,
            wavelength,
            block_directory,
        )
        wavelength_indices[wavelength] = index_downloaded_files(files)
        wavelength_export_meta[wavelength] = export_meta

    saved_this_block = 0

    for _, row in pending.iterrows():
        sample_id = str(row["sample_id"])
        target_time = pd.Timestamp(row["T_REC_dt"])
        channels = []
        channel_meta = {}

        try:
            for wavelength in AIA_WAVELENGTHS:
                path, used_time, delta_seconds = nearest_file(
                    wavelength_indices[wavelength],
                    target_time,
                )
                channel, crop_meta = crop_target_from_block(path, row)
                channels.append(channel)

                channel_meta[str(wavelength)] = {
                    "source_file": path.name,
                    "used_time": str(used_time),
                    "delta_seconds": delta_seconds,
                    "request_id": wavelength_export_meta[wavelength][
                        "request_id"
                    ],
                    "crop": crop_meta,
                }

            tensor = np.stack(channels, axis=-1).astype(np.float32)

            if tensor.shape != (IMAGE_SIZE, IMAGE_SIZE, 6):
                raise ValueError(f"Unexpected shape: {tensor.shape}")
            if not np.isfinite(tensor).all():
                raise ValueError("Tensor contains NaN or infinity.")

            year_directory = LOCAL_OUTPUT / str(TARGET_YEAR)
            year_directory.mkdir(parents=True, exist_ok=True)
            local_npz = year_directory / f"{sample_id}.npz"

            np.savez_compressed(
                local_npz,
                x=tensor,
                y=np.array(
                    int(row["label_48h_final"]),
                    dtype=np.int64,
                ),
                sample_id=np.array(sample_id),
                T_REC_dt=np.array(str(target_time)),
                HARPNUM=np.array(int(row["HARPNUM"]), dtype=np.int64),
                NOAA_AR_clean=np.array(
                    int(row["NOAA_AR_clean"]),
                    dtype=np.int64,
                ),
                label_48h_final=np.array(
                    int(row["label_48h_final"]),
                    dtype=np.int64,
                ),
                wavelengths=np.array(
                    AIA_WAVELENGTHS,
                    dtype=np.int64,
                ),
                source=np.array(
                    "JSOC HARP-block tracked im_patch + local WCS crop"
                ),
                block_id=np.array(block_id),
                channel_metadata=np.array(json.dumps(channel_meta)),
            )

            gcp_npz = f"{GCP_OUTPUT_ROOT}/{local_npz.name}"
            upload_verified(local_npz, gcp_npz)
            completed_sample_ids.add(sample_id)
            saved_this_block += 1

            sample_row = {
                "sample_id": sample_id,
                "block_id": block_id,
                "T_REC_dt": str(target_time),
                "HARPNUM": int(row["HARPNUM"]),
                "NOAA_AR_clean": int(row["NOAA_AR_clean"]),
                "label_48h_final": int(row["label_48h_final"]),
                "status": "saved",
                "shape": str(tensor.shape),
                "gcp_path": gcp_npz,
                "message": "success",
                "updated_at_utc": pd.Timestamp.utcnow().isoformat(),
            }

            sample_log = append_checkpoint(
                sample_log,
                sample_row,
                LOCAL_LOG,
                f"{GCP_WORKER_META}/{LOCAL_LOG.name}",
            )

            local_npz.unlink(missing_ok=True)
            print("✅", sample_id)

        except Exception as error:
            sample_row = {
                "sample_id": sample_id,
                "block_id": block_id,
                "T_REC_dt": str(target_time),
                "HARPNUM": int(row["HARPNUM"]),
                "NOAA_AR_clean": int(row["NOAA_AR_clean"]),
                "label_48h_final": int(row["label_48h_final"]),
                "status": "error",
                "shape": None,
                "gcp_path": None,
                "message": repr(error),
                "updated_at_utc": pd.Timestamp.utcnow().isoformat(),
            }

            sample_log = append_checkpoint(
                sample_log,
                sample_row,
                LOCAL_LOG,
                f"{GCP_WORKER_META}/{LOCAL_LOG.name}",
            )
            print("❌", sample_id, repr(error))

    # The whole block is retained only when a target failed, allowing reuse.
    current_errors = sample_log[
        (sample_log["block_id"] == block_id)
        & (sample_log["status"] == "error")
    ] if len(sample_log) else pd.DataFrame()

    if len(current_errors) == 0:
        shutil.rmtree(block_directory, ignore_errors=True)

    elapsed_minutes = (time.time() - block_started) / 60.0

    return sample_log, {
        "block_id": block_id,
        "status": "completed",
        "n_targets": len(block),
        "n_pending_at_start": len(pending),
        "n_saved_this_run": saved_this_block,
        "elapsed_minutes": round(elapsed_minutes, 3),
        "message": (
            "success"
            if len(current_errors) == 0
            else f"{len(current_errors)} sample errors retained for retry"
        ),
    }

## 9. Execute selected blocks

In [12]:

blocks_to_run = block_plan.copy()

if MAX_BLOCKS_THIS_RUN is not None:
    blocks_to_run = blocks_to_run.head(MAX_BLOCKS_THIS_RUN)

print("Blocks this run:", len(blocks_to_run))

for position, plan_row in blocks_to_run.iterrows():
    block_id = plan_row["block_id"]
    block = block_frames[block_id]

    print("\n" + "=" * 90)
    print(
        f"BLOCK {position + 1}/{len(blocks_to_run)} | "
        f"{block_id} | targets={len(block)}"
    )
    print("=" * 90)

    try:
        sample_log, block_result = process_block(
            block_id,
            block,
            sample_log,
        )
    except Exception as error:
        block_result = {
            "block_id": block_id,
            "status": "error",
            "n_targets": len(block),
            "n_pending_at_start": None,
            "n_saved_this_run": 0,
            "elapsed_minutes": None,
            "message": repr(error),
        }
        print("BLOCK ERROR:", repr(error))

    block_log = append_block_checkpoint(
        block_log,
        block_result,
    )
    display(pd.DataFrame([block_result]))

print("\nRun finished.")
print(
    "Completed model-ready objects now visible in GCP:",
    len(completed_sample_ids),
)

Blocks this run: 372

==========================================================================================
BLOCK 1/372 | 2025_HARP12492_20250101_0100_20250101_2348 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12492_20250101_0100_20250101_2348,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 2/372 | 2025_HARP12511_20250101_1024_20250101_1648 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12511_20250101_1024_20250101_1648,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 3/372 | 2025_HARP12511_20250102_0912_20250102_0912 | targets=1
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12511_20250102_0912_20250102_0912,already_complete,1,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 4/372 | 2025_HARP12511_20250103_1324_20250104_1148 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12511_20250103_1324_20250104_1148,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 5/372 | 2025_HARP12506_20250104_0900_20250105_0724 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12506_20250104_0900_20250105_0724,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 6/372 | 2025_HARP12541_20250105_0712_20250106_0536 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12541_20250105_0712_20250106_0536,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 7/372 | 2025_HARP12540_20250105_1512_20250106_1024 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12540_20250105_1512_20250106_1024,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 8/372 | 2025_HARP12515_20250106_0924_20250106_1724 | targets=6
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12515_20250106_0924_20250106_1724,already_complete,6,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 9/372 | 2025_HARP12532_20250106_2048_20250107_1924 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12532_20250106_2048_20250107_1924,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 10/372 | 2025_HARP12515_20250107_2048_20250108_0000 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12515_20250107_2048_20250108_0000,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 11/372 | 2025_HARP12537_20250108_0700_20250108_1324 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12537_20250108_0700_20250108_1324,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 12/372 | 2025_HARP12540_20250108_0900_20250108_1212 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12540_20250108_0900_20250108_1212,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 13/372 | 2025_HARP12532_20250108_2000_20250109_1824 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12532_20250108_2000_20250109_1824,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 14/372 | 2025_HARP12532_20250109_2000_20250110_0912 | targets=9
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12532_20250109_2000_20250110_0912,already_complete,9,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 15/372 | 2025_HARP12546_20250110_1936_20250111_0648 | targets=8
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12546_20250110_1936_20250111_0648,already_complete,8,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 16/372 | 2025_HARP12537_20250111_2200_20250112_0424 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12537_20250111_2200_20250112_0424,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 17/372 | 2025_HARP12572_20250112_1312_20250112_1624 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12572_20250112_1312_20250112_1624,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 18/372 | 2025_HARP12597_20250114_0124_20250114_0436 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12597_20250114_0124_20250114_0436,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 19/372 | 2025_HARP12598_20250114_0924_20250115_0612 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12598_20250114_0924_20250115_0612,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 20/372 | 2025_HARP12597_20250114_1412_20250114_1412 | targets=1
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12597_20250114_1412_20250114_1412,already_complete,1,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 21/372 | 2025_HARP12572_20250115_1012_20250115_1324 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12572_20250115_1012_20250115_1324,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 22/372 | 2025_HARP12576_20250115_2200_20250116_0424 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12576_20250115_2200_20250116_0424,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 23/372 | 2025_HARP12576_20250116_1012_20250117_0536 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12576_20250116_1012_20250117_0536,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 24/372 | 2025_HARP12597_20250116_1900_20250116_1900 | targets=1
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12597_20250116_1900_20250116_1900,already_complete,1,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 25/372 | 2025_HARP12597_20250116_2224_20250117_0624 | targets=6
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12597_20250116_2224_20250117_0624,already_complete,6,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 26/372 | 2025_HARP12597_20250117_1048_20250117_1536 | targets=4
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12597_20250117_1048_20250117_1536,already_complete,4,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 27/372 | 2025_HARP12579_20250118_1000_20250118_1624 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12579_20250118_1000_20250118_1624,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 28/372 | 2025_HARP12589_20250119_1124_20250120_0500 | targets=12
==========================================================================================

----------------------------------------------------------------------
2025_HARP12589_20250119_1124_20250120_0500 | wavelength 94
94 Å cadence segments: 1 [('2025-01-19 11:24:00', '2025-01-20 05:00:00', 12)]
♻️ Segment 1/1 already covered by cached 94 Å files.

----------------------------------------------------------------------
2025_HARP12589_20250119_1124_20250120_0500 | wavelength 131
131 Å cadence segments: 1 [('2025-01-19 11:24:00', '2025-01-20 05:00:00', 12)]
♻️ Segment 1/1 already covered by cached 131 Å files.

----------------------------------------------------------------------
2025_HARP12589_20250119_1124_20250120_0500 | wavelength 171
171 Å cadence segments: 1 [('2025-01-19 11:24:00', '2025-01-20 05:00:00', 12)]
♻️ Segment 1/1 already covered by cached 171 Å files.

----------------------------------------------------------------------
2025_HARP12589_20250119_1124_20250120_0500 | wavelength 193
193 Å cadence segments: 1 [('2025-01-19 11:24:00', '2025-01-20 05:00:00', 12)]
♻️ Segment 1/1 already covered by cached 193 Å files.

----------------------------------------------------------------------
2025_HARP12589_20250119_1124_20250120_0500 | wavelength 211
211 Å cadence segments: 1 [('2025-01-19 11:24:00', '2025-01-20 05:00:00', 12)]
♻️ Segment 1/1 already covered by cached 211 Å files.

----------------------------------------------------------------------
2025_HARP12589_20250119_1124_20250120_0500 | wavelength 335
335 Å cadence segments: 1 [('2025-01-19 11:24:00', '2025-01-20 05:00:00', 12)]
♻️ Segment 1/1 already covered by cached 335 Å files.

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250119_1124_HARP12589_NOAA13961 ValueError('Target crop leaves block patch: bounds=(61, 1845, 40, 1823), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250119_1300_HARP12589_NOAA13961 ValueError('Target crop leaves block patch: bounds=(52, 1847, 34, 1829), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250119_1612_HARP12589_NOAA13961 ValueError('Target crop leaves block patch: bounds=(31, 1838, 16, 1823), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250119_1748_HARP12589_NOAA13961 ValueError('Target crop leaves block patch: bounds=(22, 1840, 9, 1827), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250119_1924_HARP12589_NOAA13961 ValueError('Target crop leaves block patch: bounds=(13, 1843, 2, 1833), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250119_2100_HARP12589_NOAA13961 ValueError('Target crop leaves block patch: bounds=(3, 1847, -6, 1838), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250119_2236_HARP12589_NOAA13961 ValueError('Target crop leaves block patch: bounds=(-12, 1851, -16, 1846), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250120_0012_HARP12589_NOAA13961 ValueError('Target crop leaves block patch: bounds=(-27, 1854, -25, 1855), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250120_0148_HARP12589_NOAA13961 ValueError('Target crop leaves block patch: bounds=(-36, 1855, -28, 1864), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250120_0324_HARP12589_NOAA13961 ValueError('Target crop leaves block patch: bounds=(-48, 1856, -35, 1869), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250120_0500_HARP12589_NOAA13961 ValueError('Target crop leaves block patch: bounds=(-60, 1856, -42, 1874), shape=(1834, 1834)')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12589_20250119_1124_20250120_0500,completed,12,11,0,0.447,11 sample errors retained for retry

==========================================================================================
BLOCK 29/372 | 2025_HARP12589_20250120_1100_20250120_1724 | targets=5
==========================================================================================

----------------------------------------------------------------------
2025_HARP12589_20250120_1100_20250120_1724 | wavelength 94
94 Å cadence segments: 1 [('2025-01-20 11:00:00', '2025-01-20 17:24:00', 5)]
♻️ Segment 1/1 already covered by cached 94 Å files.

----------------------------------------------------------------------
2025_HARP12589_20250120_1100_20250120_1724 | wavelength 131
131 Å cadence segments: 1 [('2025-01-20 11:00:00', '2025-01-20 17:24:00', 5)]

♻️ Segment 1/1 already covered by cached 131 Å files.

----------------------------------------------------------------------
2025_HARP12589_20250120_1100_20250120_1724 | wavelength 171
171 Å cadence segments: 1 [('2025-01-20 11:00:00', '2025-01-20 17:24:00', 5)]
♻️ Segment 1/1 already covered by cached 171 Å files.

----------------------------------------------------------------------
2025_HARP12589_20250120_1100_20250120_1724 | wavelength 193
193 Å cadence segments: 1 [('2025-01-20 11:00:00', '2025-01-20 17:24:00', 5)]
♻️ Segment 1/1 already covered by cached 193 Å files.

----------------------------------------------------------------------
2025_HARP12589_20250120_1100_20250120_1724 | wavelength 211
211 Å cadence segments: 1 [('2025-01-20 11:00:00', '2025-01-20 17:24:00', 5)]
♻️ Segment 1/1 already covered by cached 211 Å files.

----------------------------------------------------------------------
2025_HARP12589_20250120_1100_20250120_1724 | wavelength 335
335 Å cadence segments: 1 [('2025-01-20 11:00:00', '2025-01-20 17:24:00', 5)]
♻️ Segment 1/1 already covered by cached 335 Å files.

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250120_1100_HARP12589_NOAA13961 ValueError('Target crop leaves block patch: bounds=(-57, 1897, -60, 1894), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250120_1236_HARP12589_NOAA13961 ValueError('Target crop leaves block patch: bounds=(-65, 1900, -66, 1899), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250120_1412_HARP12589_NOAA13961 ValueError('Target crop leaves block patch: bounds=(-70, 1903, -70, 1903), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250120_1548_HARP12589_NOAA13961 ValueError('Target crop leaves block patch: bounds=(-76, 1904, -74, 1906), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250120_1724_HARP12589_NOAA13961 ValueError('Target crop leaves block patch: bounds=(-87, 1907, -80, 1913), shape=(1834, 1834)')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12589_20250120_1100_20250120_1724,completed,5,5,0,0.188,5 sample errors retained for retry

==========================================================================================
BLOCK 30/372 | 2025_HARP12600_20250121_1136_20250121_1624 | targets=4
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12600_20250121_1136_20250121_1624,already_complete,4,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 31/372 | 2025_HARP12623_20250122_1024_20250123_0624 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12623_20250122_1024_20250123_0624,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 32/372 | 2025_HARP12589_20250123_0924_20250123_2224 | targets=9
==========================================================================================

----------------------------------------------------------------------
2025_HARP12589_20250123_0924_20250123_2224 | wavelength 94
94 Å cadence segments: 2 [('2025-01-23 09:24:00', '2025-01-23 09:24:00', 1), ('2025-01-23 11:12:00', '2025-01-23 22:24:00', 8)]
♻️ Segment 1/2 already covered by cached 94 Å files.
♻️ Segment 2/2 already covered by cached 94 Å files.

----------------------------------------------------------------------
2025_HARP12589_20250123_0924_20250123_2224 | wavelength 131
131 Å cadence segments: 2 [('2025-01-23 09:24:00', '2025-01-23 09:24:00', 1), ('2025-01-23 11:12:00', '2025-01-23 22:24:00', 8)]
♻️ Segment 1/2 already covered by cached 131 Å files.
♻️ Segment 2/2 already covered by cached 131 Å files.

----------------------------------------------------------------------
2025_HARP12589_20250123_0924_20250123_2224 | wavelength 171
171 Å cadence segments: 2 [('2025-01-23 09:24:00', '2025-01-23 09:24:00', 1), ('2025-01-23 11:12:00', '2025-01-23 22:24:00', 8)]
♻️ Segment 1/2 already covered by cached 171 Å files.
♻️ Segment 2/2 already covered by cached 171 Å files.

----------------------------------------------------------------------
2025_HARP12589_20250123_0924_20250123_2224 | wavelength 193
193 Å cadence segments: 2 [('2025-01-23 09:24:00', '2025-01-23 09:24:00', 1), ('2025-01-23 11:12:00', '2025-01-23 22:24:00', 8)]
♻️ Segment 1/2 already covered by cached 193 Å files.
♻️ Segment 2/2 already covered by cached 193 Å files.

----------------------------------------------------------------------
2025_HARP12589_20250123_0924_20250123_2224 | wavelength 211
211 Å cadence segments: 2 [('2025-01-23 09:24:00', '2025-01-23 09:24:00', 1), ('2025-01-23 11:12:00', '2025-01-23 22:24:00', 8)]
♻️ Segment 1/2 already covered by cached 211 Å files.
♻️ Segment 2/2 already covered by cached 211 Å files.

----------------------------------------------------------------------
2025_HARP12589_20250123_0924_20250123_2224 | wavelength 335
335 Å cadence segments: 2 [('2025-01-23 09:24:00', '2025-01-23 09:24:00', 1), ('2025-01-23 11:12:00', '2025-01-23 22:24:00', 8)]
♻️ Segment 1/2 already covered by cached 335 Å files.
♻️ Segment 2/2 already covered by cached 335 Å files.

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250123_0924_HARP12589_NOAA13961 ValueError('Target crop leaves block patch: bounds=(-48, 1881, -48, 1880), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250123_1112_HARP12589_NOAA13961 ValueError('Target crop leaves block patch: bounds=(-23, 1898, -46, 1876), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250123_1248_HARP12589_NOAA13961 ValueError('Target crop leaves block patch: bounds=(-22, 1890, -41, 1872), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250123_1424_HARP12589_NOAA13961 ValueError('Target crop leaves block patch: bounds=(-19, 1880, -34, 1865), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250123_1600_HARP12589_NOAA13961 ValueError('Target crop leaves block patch: bounds=(-14, 1870, -26, 1858), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250123_1736_HARP12589_NOAA13961 ValueError('Target crop leaves block patch: bounds=(-11, 1860, -19, 1852), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250123_1912_HARP12589_NOAA13961 ValueError('Target crop leaves block patch: bounds=(-7, 1849, -11, 1845), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250123_2048_HARP12589_NOAA13961 ValueError('Target crop leaves block patch: bounds=(-3, 1837, -3, 1836), shape=(1834, 1834)')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12589_20250123_0924_20250123_2224,completed,9,8,0,0.325,8 sample errors retained for retry

==========================================================================================
BLOCK 33/372 | 2025_HARP12600_20250124_1000_20250124_1624 | targets=5
==========================================================================================

----------------------------------------------------------------------
2025_HARP12600_20250124_1000_20250124_1624 | wavelength 94
94 Å cadence segments: 1 [('2025-01-24 10:00:00', '2025-01-24 16:24:00', 5)]
♻️ Segment 1/1 already covered by cached 94 Å files.

----------------------------------------------------------------------
2025_HARP12600_20250124_1000_20250124_1624 | wavelength 131
131 Å cadence segments: 1 [('2025-01-24 10:00:00', '2025-01-24 16:24:00', 5)]

♻️ Segment 1/1 already covered by cached 131 Å files.

----------------------------------------------------------------------
2025_HARP12600_20250124_1000_20250124_1624 | wavelength 171
171 Å cadence segments: 1 [('2025-01-24 10:00:00', '2025-01-24 16:24:00', 5)]
♻️ Segment 1/1 already covered by cached 171 Å files.

----------------------------------------------------------------------
2025_HARP12600_20250124_1000_20250124_1624 | wavelength 193
193 Å cadence segments: 1 [('2025-01-24 10:00:00', '2025-01-24 16:24:00', 5)]
♻️ Segment 1/1 already covered by cached 193 Å files.

----------------------------------------------------------------------
2025_HARP12600_20250124_1000_20250124_1624 | wavelength 211
211 Å cadence segments: 1 [('2025-01-24 10:00:00', '2025-01-24 16:24:00', 5)]
♻️ Segment 1/1 already covered by cached 211 Å files.

----------------------------------------------------------------------
2025_HARP12600_20250124_1000_20250124_1624 | wavelength 335
335 Å cadence segments: 1 [('2025-01-24 10:00:00', '2025-01-24 16:24:00', 5)]
Segment query: aia.lev1_euv_12s[2025-01-24T10:00:00.000/480m@96m][335]{image}
Segment reference: 2025-01-24 13:12:00 | targets: 5 | patch arcsec: 1100.0
JSOC export attempt 1/10

2026-06-30 08:52:08 - drms - INFO: Export request pending. [id=JSOC_20260630_005886, status=2]

2026-06-30 08:52:08 - drms - INFO: Waiting for 15 seconds...

2026-06-30 08:52:23 - drms - INFO: Export request pending. [id=JSOC_20260630_005886, status=1]

2026-06-30 08:52:23 - drms - INFO: Waiting for 15 seconds...

2026-06-30 08:52:39 - drms - INFO: Export request pending. [id=JSOC_20260630_005886, status=1]

2026-06-30 08:52:39 - drms - INFO: Waiting for 15 seconds...

2026-06-30 08:52:54 - drms - INFO: Export request finished. [id=JSOC_20260630_005886, status=0]

2026-06-30 08:52:54 - drms - INFO: Downloading file 1 of 4...

2026-06-30 08:52:54 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-01-24T09:59:59Z][335][JSOC_20260630_005886]

2026-06-30 08:52:54 - drms - INFO:     filename: aia.lev1_euv_12s.2025-01-24T095959Z.335.image.fits

2026-06-30 08:52:57 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP12600_20250124_1000_20250124_1624/335/segment_01_20250124_1000_20250124_1624/aia.lev1_euv_12s.2025-01-24T095959Z.335.image.fits.1

2026-06-30 08:52:57 - drms - INFO: Downloading file 2 of 4...

2026-06-30 08:52:57 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-01-24T11:35:59Z][335][JSOC_20260630_005886]

2026-06-30 08:52:57 - drms - INFO:     filename: aia.lev1_euv_12s.2025-01-24T113559Z.335.image.fits

2026-06-30 08:52:59 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP12600_20250124_1000_20250124_1624/335/segment_01_20250124_1000_20250124_1624/aia.lev1_euv_12s.2025-01-24T113559Z.335.image.fits.1

2026-06-30 08:52:59 - drms - INFO: Downloading file 3 of 4...

2026-06-30 08:52:59 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-01-24T13:11:59Z][335][JSOC_20260630_005886]

2026-06-30 08:52:59 - drms - INFO:     filename: aia.lev1_euv_12s.2025-01-24T131159Z.335.image.fits

2026-06-30 08:53:02 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP12600_20250124_1000_20250124_1624/335/segment_01_20250124_1000_20250124_1624/aia.lev1_euv_12s.2025-01-24T131159Z.335.image.fits.1

2026-06-30 08:53:02 - drms - INFO: Downloading file 4 of 4...

2026-06-30 08:53:02 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-01-24T14:47:59Z][335][JSOC_20260630_005886]

2026-06-30 08:53:02 - drms - INFO:     filename: aia.lev1_euv_12s.2025-01-24T144759Z.335.image.fits

2026-06-30 08:53:04 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP12600_20250124_1000_20250124_1624/335/segment_01_20250124_1000_20250124_1624/aia.lev1_euv_12s.2025-01-24T144759Z.335.image.fits.1

BLOCK ERROR: RuntimeError('Downloaded 335 Å segment does not cover all target timestamps within 180 seconds.')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12600_20250124_1000_20250124_1624,error,5,None,0,None,RuntimeError('Downloaded 335 Å segment does no...

==========================================================================================
BLOCK 34/372 | 2025_HARP12643_20250125_0912_20250126_0424 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12643_20250125_0912_20250126_0424,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 35/372 | 2025_HARP12643_20250126_1012_20250127_0524 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12643_20250126_1012_20250127_0524,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 36/372 | 2025_HARP12660_20250127_2036_20250128_0612 | targets=7
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12660_20250127_2036_20250128_0612,already_complete,7,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 37/372 | 2025_HARP12657_20250130_1012_20250131_0524 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12657_20250130_1012_20250131_0524,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 38/372 | 2025_HARP12679_20250201_1748_20250202_0548 | targets=8
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12679_20250201_1748_20250202_0548,already_complete,8,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 39/372 | 2025_HARP12679_20250202_1112_20250203_0624 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12679_20250202_1112_20250203_0624,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 40/372 | 2025_HARP12701_20250204_0124_20250204_0612 | targets=4
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12701_20250204_0124_20250204_0612,already_complete,4,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 41/372 | 2025_HARP12701_20250204_1936_20250205_0512 | targets=7
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12701_20250204_1936_20250205_0512,already_complete,7,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 42/372 | 2025_HARP12667_20250205_1100_20250205_1724 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12667_20250205_1100_20250205_1724,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 43/372 | 2025_HARP12701_20250206_2024_20250207_0424 | targets=6
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12701_20250206_2024_20250207_0424,already_complete,6,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 44/372 | 2025_HARP12703_20250207_2048_20250208_1912 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12703_20250207_2048_20250208_1912,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 45/372 | 2025_HARP12712_20250209_1000_20250209_1624 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12712_20250209_1000_20250209_1624,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 46/372 | 2025_HARP12708_20250210_1100_20250211_0924 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12708_20250210_1100_20250211_0924,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 47/372 | 2025_HARP12712_20250211_1936_20250212_1624 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12712_20250211_1936_20250212_1624,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 48/372 | 2025_HARP12712_20250212_2000_20250213_1824 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12712_20250212_2000_20250213_1824,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 49/372 | 2025_HARP12765_20250213_1948_20250214_1812 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12765_20250213_1948_20250214_1812,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 50/372 | 2025_HARP12752_20250214_1324_20250215_1148 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12752_20250214_1324_20250215_1148,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 51/372 | 2025_HARP12752_20250215_1324_20250216_1148 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12752_20250215_1324_20250216_1148,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 52/372 | 2025_HARP12732_20250216_1812_20250216_2124 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12732_20250216_1812_20250216_2124,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 53/372 | 2025_HARP12733_20250217_0948_20250218_0812 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12733_20250217_0948_20250218_0812,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 54/372 | 2025_HARP12768_20250218_2312_20250219_2148 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12768_20250218_2312_20250219_2148,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 55/372 | 2025_HARP12793_20250220_1624_20250220_1624 | targets=1
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12793_20250220_1624_20250220_1624,already_complete,1,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 56/372 | 2025_HARP12755_20250221_1936_20250221_2112 | targets=2
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12755_20250221_1936_20250221_2112,already_complete,2,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 57/372 | 2025_HARP12807_20250222_1236_20250223_1100 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12807_20250222_1236_20250223_1100,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 58/372 | 2025_HARP12793_20250223_1936_20250224_1624 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12793_20250223_1936_20250224_1624,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 59/372 | 2025_HARP12810_20250225_0100_20250225_2324 | targets=15
==========================================================================================

----------------------------------------------------------------------
2025_HARP12810_20250225_0100_20250225_2324 | wavelength 94
94 Å cadence segments: 1 [('2025-02-25 01:00:00', '2025-02-25 23:24:00', 15)]
Segment query: aia.lev1_euv_12s[2025-02-25T01:00:00.000/1440m@96m][94]{image}
Segment reference: 2025-02-25 12:12:00 | targets: 15 | patch arcsec: 394.89362354120783
JSOC export attempt 1/10

2026-06-30 08:54:00 - drms - INFO: Export request pending. [id=JSOC_20260630_005907, status=2]

2026-06-30 08:54:00 - drms - INFO: Waiting for 15 seconds...

2026-06-30 08:54:16 - drms - INFO: Export request pending. [id=JSOC_20260630_005907, status=1]

2026-06-30 08:54:16 - drms - INFO: Waiting for 15 seconds...

2026-06-30 08:54:31 - drms - INFO: Export request pending. [id=JSOC_20260630_005907, status=1]

2026-06-30 08:54:31 - drms - INFO: Waiting for 15 seconds...

2026-06-30 08:54:47 - drms - INFO: Export request pending. [id=JSOC_20260630_005907, status=1]

2026-06-30 08:54:47 - drms - INFO: Waiting for 15 seconds...

2026-06-30 08:55:02 - drms - INFO: Export request pending. [id=JSOC_20260630_005907, status=1]

2026-06-30 08:55:02 - drms - INFO: Waiting for 15 seconds...

2026-06-30 08:55:18 - drms - INFO: Export request finished. [id=JSOC_20260630_005907, status=0]

2026-06-30 08:55:18 - drms - INFO: Downloading file 1 of 14...

2026-06-30 08:55:18 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-02-25T00:59:59Z][94][JSOC_20260630_005907]

2026-06-30 08:55:18 - drms - INFO:     filename: aia.lev1_euv_12s.2025-02-25T005959Z.94.image.fits

2026-06-30 08:55:19 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP12810_20250225_0100_20250225_2324/94/segment_01_20250225_0100_20250225_2324/aia.lev1_euv_12s.2025-02-25T005959Z.94.image.fits.1

2026-06-30 08:55:19 - drms - INFO: Downloading file 2 of 14...

2026-06-30 08:55:19 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-02-25T02:35:59Z][94][JSOC_20260630_005907]

2026-06-30 08:55:19 - drms - INFO:     filename: aia.lev1_euv_12s.2025-02-25T023559Z.94.image.fits

2026-06-30 08:55:21 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP12810_20250225_0100_20250225_2324/94/segment_01_20250225_0100_20250225_2324/aia.lev1_euv_12s.2025-02-25T023559Z.94.image.fits.1

2026-06-30 08:55:21 - drms - INFO: Downloading file 3 of 14...

2026-06-30 08:55:21 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-02-25T04:11:59Z][94][JSOC_20260630_005907]

2026-06-30 08:55:21 - drms - INFO:     filename: aia.lev1_euv_12s.2025-02-25T041159Z.94.image.fits

2026-06-30 08:55:23 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP12810_20250225_0100_20250225_2324/94/segment_01_20250225_0100_20250225_2324/aia.lev1_euv_12s.2025-02-25T041159Z.94.image.fits.1

2026-06-30 08:55:23 - drms - INFO: Downloading file 4 of 14...

2026-06-30 08:55:23 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-02-25T05:47:59Z][94][JSOC_20260630_005907]

2026-06-30 08:55:23 - drms - INFO:     filename: aia.lev1_euv_12s.2025-02-25T054759Z.94.image.fits

2026-06-30 08:55:24 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP12810_20250225_0100_20250225_2324/94/segment_01_20250225_0100_20250225_2324/aia.lev1_euv_12s.2025-02-25T054759Z.94.image.fits.1

2026-06-30 08:55:24 - drms - INFO: Downloading file 5 of 14...

2026-06-30 08:55:24 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-02-25T07:23:59Z][94][JSOC_20260630_005907]

2026-06-30 08:55:24 - drms - INFO:     filename: aia.lev1_euv_12s.2025-02-25T072359Z.94.image.fits

2026-06-30 08:55:26 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP12810_20250225_0100_20250225_2324/94/segment_01_20250225_0100_20250225_2324/aia.lev1_euv_12s.2025-02-25T072359Z.94.image.fits.1

2026-06-30 08:55:26 - drms - INFO: Downloading file 6 of 14...

2026-06-30 08:55:26 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-02-25T08:59:59Z][94][JSOC_20260630_005907]

2026-06-30 08:55:26 - drms - INFO:     filename: aia.lev1_euv_12s.2025-02-25T085959Z.94.image.fits

2026-06-30 08:55:27 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP12810_20250225_0100_20250225_2324/94/segment_01_20250225_0100_20250225_2324/aia.lev1_euv_12s.2025-02-25T085959Z.94.image.fits.1

2026-06-30 08:55:27 - drms - INFO: Downloading file 7 of 14...

2026-06-30 08:55:27 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-02-25T10:35:59Z][94][JSOC_20260630_005907]

2026-06-30 08:55:27 - drms - INFO:     filename: aia.lev1_euv_12s.2025-02-25T103559Z.94.image.fits

2026-06-30 08:55:29 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP12810_20250225_0100_20250225_2324/94/segment_01_20250225_0100_20250225_2324/aia.lev1_euv_12s.2025-02-25T103559Z.94.image.fits.1

2026-06-30 08:55:29 - drms - INFO: Downloading file 8 of 14...

2026-06-30 08:55:29 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-02-25T12:11:59Z][94][JSOC_20260630_005907]

2026-06-30 08:55:29 - drms - INFO:     filename: aia.lev1_euv_12s.2025-02-25T121159Z.94.image.fits

2026-06-30 08:55:30 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP12810_20250225_0100_20250225_2324/94/segment_01_20250225_0100_20250225_2324/aia.lev1_euv_12s.2025-02-25T121159Z.94.image.fits.1

2026-06-30 08:55:30 - drms - INFO: Downloading file 9 of 14...

2026-06-30 08:55:30 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-02-25T13:47:59Z][94][JSOC_20260630_005907]

2026-06-30 08:55:30 - drms - INFO:     filename: aia.lev1_euv_12s.2025-02-25T134759Z.94.image.fits

2026-06-30 08:55:32 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP12810_20250225_0100_20250225_2324/94/segment_01_20250225_0100_20250225_2324/aia.lev1_euv_12s.2025-02-25T134759Z.94.image.fits.1

2026-06-30 08:55:32 - drms - INFO: Downloading file 10 of 14...

2026-06-30 08:55:32 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-02-25T15:23:59Z][94][JSOC_20260630_005907]

2026-06-30 08:55:32 - drms - INFO:     filename: aia.lev1_euv_12s.2025-02-25T152359Z.94.image.fits

2026-06-30 08:55:33 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP12810_20250225_0100_20250225_2324/94/segment_01_20250225_0100_20250225_2324/aia.lev1_euv_12s.2025-02-25T152359Z.94.image.fits.1

2026-06-30 08:55:33 - drms - INFO: Downloading file 11 of 14...

2026-06-30 08:55:33 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-02-25T16:59:59Z][94][JSOC_20260630_005907]

2026-06-30 08:55:33 - drms - INFO:     filename: aia.lev1_euv_12s.2025-02-25T165959Z.94.image.fits

2026-06-30 08:55:35 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP12810_20250225_0100_20250225_2324/94/segment_01_20250225_0100_20250225_2324/aia.lev1_euv_12s.2025-02-25T165959Z.94.image.fits.1

2026-06-30 08:55:35 - drms - INFO: Downloading file 12 of 14...

2026-06-30 08:55:35 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-02-25T18:35:59Z][94][JSOC_20260630_005907]

2026-06-30 08:55:35 - drms - INFO:     filename: aia.lev1_euv_12s.2025-02-25T183559Z.94.image.fits

2026-06-30 08:55:36 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP12810_20250225_0100_20250225_2324/94/segment_01_20250225_0100_20250225_2324/aia.lev1_euv_12s.2025-02-25T183559Z.94.image.fits.1

2026-06-30 08:55:36 - drms - INFO: Downloading file 13 of 14...

2026-06-30 08:55:36 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-02-25T21:47:59Z][94][JSOC_20260630_005907]

2026-06-30 08:55:36 - drms - INFO:     filename: aia.lev1_euv_12s.2025-02-25T214759Z.94.image.fits

2026-06-30 08:55:38 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP12810_20250225_0100_20250225_2324/94/segment_01_20250225_0100_20250225_2324/aia.lev1_euv_12s.2025-02-25T214759Z.94.image.fits.1

2026-06-30 08:55:38 - drms - INFO: Downloading file 14 of 14...

2026-06-30 08:55:38 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-02-25T23:23:59Z][94][JSOC_20260630_005907]

2026-06-30 08:55:38 - drms - INFO:     filename: aia.lev1_euv_12s.2025-02-25T232359Z.94.image.fits

2026-06-30 08:55:39 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP12810_20250225_0100_20250225_2324/94/segment_01_20250225_0100_20250225_2324/aia.lev1_euv_12s.2025-02-25T232359Z.94.image.fits.1

BLOCK ERROR: RuntimeError('Downloaded 94 Å segment does not cover all target timestamps within 180 seconds.')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12810_20250225_0100_20250225_2324,error,15,None,0,None,RuntimeError('Downloaded 94 Å segment does not...

==========================================================================================
BLOCK 60/372 | 2025_HARP12810_20250226_0100_20250226_0412 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12810_20250226_0100_20250226_0412,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 61/372 | 2025_HARP12810_20250227_0512_20250227_1136 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12810_20250227_0512_20250227_1136,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 62/372 | 2025_HARP12798_20250227_2112_20250228_1624 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12798_20250227_2112_20250228_1624,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 63/372 | 2025_HARP12798_20250228_1936_20250301_0200 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12798_20250228_1936_20250301_0200,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 64/372 | 2025_HARP12806_20250302_0448_20250302_1600 | targets=8
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12806_20250302_0448_20250302_1600,already_complete,8,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 65/372 | 2025_HARP12808_20250303_1436_20250303_1748 | targets=3
==========================================================================================

----------------------------------------------------------------------
2025_HARP12808_20250303_1436_20250303_1748 | wavelength 94
94 Å cadence segments: 1 [('2025-03-03 14:36:00', '2025-03-03 17:48:00', 3)]
♻️ Segment 1/1 already covered by cached 94 Å files.

----------------------------------------------------------------------
2025_HARP12808_20250303_1436_20250303_1748 | wavelength 131
131 Å cadence segments: 1 [('2025-03-03 14:36:00', '2025-03-03 17:48:00', 3)]
♻️ Segment 1/1 already covered by cached 131 Å files.

----------------------------------------------------------------------
2025_HARP12808_20250303_1436_20250303_1748 | wavelength 171
171 Å cadence segments: 1 [('2025-03-03 14:36:00', '2025-03-03 17:48:00', 3)]

♻️ Segment 1/1 already covered by cached 171 Å files.

----------------------------------------------------------------------
2025_HARP12808_20250303_1436_20250303_1748 | wavelength 193
193 Å cadence segments: 1 [('2025-03-03 14:36:00', '2025-03-03 17:48:00', 3)]
♻️ Segment 1/1 already covered by cached 193 Å files.

----------------------------------------------------------------------
2025_HARP12808_20250303_1436_20250303_1748 | wavelength 211
211 Å cadence segments: 1 [('2025-03-03 14:36:00', '2025-03-03 17:48:00', 3)]
♻️ Segment 1/1 already covered by cached 211 Å files.

----------------------------------------------------------------------
2025_HARP12808_20250303_1436_20250303_1748 | wavelength 335
335 Å cadence segments: 1 [('2025-03-03 14:36:00', '2025-03-03 17:48:00', 3)]
♻️ Segment 1/1 already covered by cached 335 Å files.

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250303_1436_HARP12808_NOAA14006 ValueError('Target crop leaves block patch: bounds=(-168, 2009, -174, 2003), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250303_1612_HARP12808_NOAA14006 ValueError('Target crop leaves block patch: bounds=(-167, 2000, -167, 2000), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250303_1748_HARP12808_NOAA14006 ValueError('Target crop leaves block patch: bounds=(-165, 1990, -157, 1998), shape=(1834, 1834)')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12808_20250303_1436_20250303_1748,completed,3,3,0,0.111,3 sample errors retained for retry

==========================================================================================
BLOCK 66/372 | 2025_HARP12865_20250304_2136_20250305_0048 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12865_20250304_2136_20250305_0048,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 67/372 | 2025_HARP12861_20250306_1136_20250306_1624 | targets=4
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12861_20250306_1136_20250306_1624,already_complete,4,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 68/372 | 2025_HARP12861_20250307_1936_20250307_2112 | targets=2
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12861_20250307_1936_20250307_2112,already_complete,2,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 69/372 | 2025_HARP12861_20250309_0036_20250309_2300 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12861_20250309_0036_20250309_2300,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 70/372 | 2025_HARP12861_20250310_0036_20250310_1636 | targets=11
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12861_20250310_0036_20250310_1636,already_complete,11,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 71/372 | 2025_HARP12861_20250310_1948_20250310_2148 | targets=2
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12861_20250310_1948_20250310_2148,already_complete,2,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 72/372 | 2025_HARP12888_20250311_1100_20250312_0948 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12888_20250311_1100_20250312_0948,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 73/372 | 2025_HARP12873_20250312_1124_20250312_2136 | targets=7
==========================================================================================

----------------------------------------------------------------------
2025_HARP12873_20250312_1124_20250312_2136 | wavelength 94
94 Å cadence segments: 2 [('2025-03-12 11:24:00', '2025-03-12 17:48:00', 5), ('2025-03-12 20:00:00', '2025-03-12 21:36:00', 2)]
♻️ Segment 1/2 already covered by cached 94 Å files.
♻️ Segment 2/2 already covered by cached 94 Å files.

----------------------------------------------------------------------
2025_HARP12873_20250312_1124_20250312_2136 | wavelength 131
131 Å cadence segments: 2 [('2025-03-12 11:24:00', '2025-03-12 17:48:00', 5), ('2025-03-12 20:00:00', '2025-03-12 21:36:00', 2)]
♻️ Segment 1/2 already covered by cached 131 Å files.
♻️ Segment 2/2 already covered by cached 131 Å files.

----------------------------------------------------------------------
2025_HARP12873_20250312_1124_20250312_2136 | wavelength 171
171 Å cadence segments: 2 [('2025-03-12 11:24:00', '2025-03-12 17:48:00', 5), ('2025-03-12 20:00:00', '2025-03-12 21:36:00', 2)]
♻️ Segment 1/2 already covered by cached 171 Å files.
♻️ Segment 2/2 already covered by cached 171 Å files.

----------------------------------------------------------------------
2025_HARP12873_20250312_1124_20250312_2136 | wavelength 193
193 Å cadence segments: 2 [('2025-03-12 11:24:00', '2025-03-12 17:48:00', 5), ('2025-03-12 20:00:00', '2025-03-12 21:36:00', 2)]
♻️ Segment 1/2 already covered by cached 193 Å files.
♻️ Segment 2/2 already covered by cached 193 Å files.

----------------------------------------------------------------------
2025_HARP12873_20250312_1124_20250312_2136 | wavelength 211
211 Å cadence segments: 2 [('2025-03-12 11:24:00', '2025-03-12 17:48:00', 5), ('2025-03-12 20:00:00', '2025-03-12 21:36:00', 2)]
Segment query: aia.lev1_euv_12s[2025-03-12T11:24:00.000/480m@96m][211]{image}
Segment reference: 2025-03-12 14:36:00 | targets: 5 | patch arcsec: 406.26955713475104
JSOC export attempt 1/10

2026-06-30 08:56:15 - drms - INFO: Export request pending. [id=JSOC_20260630_005935, status=2]

2026-06-30 08:56:15 - drms - INFO: Waiting for 15 seconds...

2026-06-30 08:56:31 - drms - INFO: Export request pending. [id=JSOC_20260630_005935, status=1]

2026-06-30 08:56:31 - drms - INFO: Waiting for 15 seconds...

2026-06-30 08:56:46 - drms - INFO: Export request pending. [id=JSOC_20260630_005935, status=1]

2026-06-30 08:56:46 - drms - INFO: Waiting for 15 seconds...

2026-06-30 08:57:02 - drms - INFO: Export request pending. [id=JSOC_20260630_005935, status=1]

2026-06-30 08:57:02 - drms - INFO: Waiting for 15 seconds...

2026-06-30 08:57:17 - drms - INFO: Export request pending. [id=JSOC_20260630_005935, status=1]

2026-06-30 08:57:17 - drms - INFO: Waiting for 15 seconds...

2026-06-30 08:57:33 - drms - INFO: Export request finished. [id=JSOC_20260630_005935, status=0]

2026-06-30 08:57:33 - drms - INFO: Downloading file 1 of 4...

2026-06-30 08:57:33 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-03-12T11:23:59Z][211][JSOC_20260630_005935]

2026-06-30 08:57:33 - drms - INFO:     filename: aia.lev1_euv_12s.2025-03-12T112359Z.211.image.fits

2026-06-30 08:57:34 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP12873_20250312_1124_20250312_2136/211/segment_01_20250312_1124_20250312_1748/aia.lev1_euv_12s.2025-03-12T112359Z.211.image.fits.1

2026-06-30 08:57:34 - drms - INFO: Downloading file 2 of 4...

2026-06-30 08:57:34 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-03-12T12:59:59Z][211][JSOC_20260630_005935]

2026-06-30 08:57:34 - drms - INFO:     filename: aia.lev1_euv_12s.2025-03-12T125959Z.211.image.fits

2026-06-30 08:57:36 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP12873_20250312_1124_20250312_2136/211/segment_01_20250312_1124_20250312_1748/aia.lev1_euv_12s.2025-03-12T125959Z.211.image.fits.1

2026-06-30 08:57:36 - drms - INFO: Downloading file 3 of 4...

2026-06-30 08:57:36 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-03-12T16:11:59Z][211][JSOC_20260630_005935]

2026-06-30 08:57:36 - drms - INFO:     filename: aia.lev1_euv_12s.2025-03-12T161159Z.211.image.fits

2026-06-30 08:57:37 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP12873_20250312_1124_20250312_2136/211/segment_01_20250312_1124_20250312_1748/aia.lev1_euv_12s.2025-03-12T161159Z.211.image.fits.1

2026-06-30 08:57:37 - drms - INFO: Downloading file 4 of 4...

2026-06-30 08:57:37 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-03-12T17:47:59Z][211][JSOC_20260630_005935]

2026-06-30 08:57:37 - drms - INFO:     filename: aia.lev1_euv_12s.2025-03-12T174759Z.211.image.fits

2026-06-30 08:57:39 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP12873_20250312_1124_20250312_2136/211/segment_01_20250312_1124_20250312_1748/aia.lev1_euv_12s.2025-03-12T174759Z.211.image.fits.1

BLOCK ERROR: RuntimeError('Downloaded 211 Å segment does not cover all target timestamps within 180 seconds.')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12873_20250312_1124_20250312_2136,error,7,None,0,None,RuntimeError('Downloaded 211 Å segment does no...

==========================================================================================
BLOCK 74/372 | 2025_HARP12879_20250312_2100_20250313_1924 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12879_20250312_2100_20250313_1924,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 75/372 | 2025_HARP12885_20250313_2012_20250314_0412 | targets=6
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12885_20250313_2012_20250314_0412,already_complete,6,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 76/372 | 2025_HARP12879_20250314_0848_20250315_0712 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12879_20250314_0848_20250315_0712,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 77/372 | 2025_HARP12906_20250314_1524_20250315_1348 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12906_20250314_1524_20250315_1348,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 78/372 | 2025_HARP12893_20250315_1236_20250316_1100 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12893_20250315_1236_20250316_1100,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 79/372 | 2025_HARP12893_20250316_1236_20250317_1100 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12893_20250316_1236_20250317_1100,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 80/372 | 2025_HARP12889_20250317_0212_20250317_1148 | targets=7
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12889_20250317_0212_20250317_1148,already_complete,7,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 81/372 | 2025_HARP12889_20250317_1500_20250318_0212 | targets=8
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12889_20250317_1500_20250318_0212,already_complete,8,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 82/372 | 2025_HARP12907_20250318_0736_20250318_2024 | targets=9
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12907_20250318_0736_20250318_2024,already_complete,9,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 83/372 | 2025_HARP12933_20250318_1936_20250318_1936 | targets=1
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12933_20250318_1936_20250318_1936,already_complete,1,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 84/372 | 2025_HARP12907_20250318_2348_20250319_1724 | targets=12
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12907_20250318_2348_20250319_1724,already_complete,12,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 85/372 | 2025_HARP12955_20250319_1948_20250320_1812 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12955_20250319_1948_20250320_1812,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 86/372 | 2025_HARP12955_20250320_1948_20250321_1812 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12955_20250320_1948_20250321_1812,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 87/372 | 2025_HARP12941_20250321_1712_20250322_0424 | targets=8
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12941_20250321_1712_20250322_0424,already_complete,8,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 88/372 | 2025_HARP12923_20250322_0236_20250323_0100 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12923_20250322_0236_20250323_0100,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 89/372 | 2025_HARP12941_20250324_0736_20250325_0424 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12941_20250324_0736_20250325_0424,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 90/372 | 2025_HARP12962_20250325_1124_20250326_1012 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12962_20250325_1124_20250326_1012,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 91/372 | 2025_HARP12962_20250327_0112_20250327_0424 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12962_20250327_0112_20250327_0424,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 92/372 | 2025_HARP12961_20250328_0212_20250329_0036 | targets=15
==========================================================================================

----------------------------------------------------------------------
2025_HARP12961_20250328_0212_20250329_0036 | wavelength 94
94 Å cadence segments: 1 [('2025-03-28 02:12:00', '2025-03-29 00:36:00', 15)]
♻️ Segment 1/1 already covered by cached 94 Å files.

----------------------------------------------------------------------
2025_HARP12961_20250328_0212_20250329_0036 | wavelength 131
131 Å cadence segments: 1 [('2025-03-28 02:12:00', '2025-03-29 00:36:00', 15)]
♻️ Segment 1/1 already covered by cached 131 Å files.

----------------------------------------------------------------------
2025_HARP12961_20250328_0212_20250329_0036 | wavelength 171
171 Å cadence segments: 1 [('2025-03-28 02:12:00', '2025-03-29 00:36:00', 15)]
♻️ Segment 1/1 already covered by cached 171 Å files.

----------------------------------------------------------------------
2025_HARP12961_20250328_0212_20250329_0036 | wavelength 193
193 Å cadence segments: 1 [('2025-03-28 02:12:00', '2025-03-29 00:36:00', 15)]
♻️ Segment 1/1 already covered by cached 193 Å files.

----------------------------------------------------------------------
2025_HARP12961_20250328_0212_20250329_0036 | wavelength 211
211 Å cadence segments: 1 [('2025-03-28 02:12:00', '2025-03-29 00:36:00', 15)]
♻️ Segment 1/1 already covered by cached 211 Å files.

----------------------------------------------------------------------
2025_HARP12961_20250328_0212_20250329_0036 | wavelength 335
335 Å cadence segments: 1 [('2025-03-28 02:12:00', '2025-03-29 00:36:00', 15)]
♻️ Segment 1/1 already covered by cached 335 Å files.

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250328_0212_HARP12961_NOAA14039 ValueError('Target crop leaves block patch: bounds=(-180, 2101, -219, 2062), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250328_0348_HARP12961_NOAA14039 ValueError('Target crop leaves block patch: bounds=(-197, 2101, -230, 2069), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250328_0524_HARP12961_NOAA14039 ValueError('Target crop leaves block patch: bounds=(-208, 2100, -235, 2073), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250328_0700_HARP12961_NOAA14039 ValueError('Target crop leaves block patch: bounds=(-218, 2099, -240, 2077), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250328_0836_HARP12961_NOAA14039 ValueError('Target crop leaves block patch: bounds=(-233, 2098, -244, 2087), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250328_1012_HARP12961_NOAA14039 ValueError('Target crop leaves block patch: bounds=(-243, 2097, -249, 2091), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250328_1148_HARP12961_NOAA14039 ValueError('Target crop leaves block patch: bounds=(-252, 2095, -252, 2095), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250328_1324_HARP12961_NOAA14039 ValueError('Target crop leaves block patch: bounds=(-260, 2093, -260, 2093), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250328_1500_HARP12961_NOAA14039 ValueError('Target crop leaves block patch: bounds=(-268, 2090, -266, 2092), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250328_1636_HARP12961_NOAA14039 ValueError('Target crop leaves block patch: bounds=(-275, 2087, -271, 2092), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250328_1812_HARP12961_NOAA14039 ValueError('Target crop leaves block patch: bounds=(-286, 2083, -275, 2094), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250328_1948_HARP12961_NOAA14039 ValueError('Target crop leaves block patch: bounds=(-295, 2081, -278, 2098), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250328_2124_HARP12961_NOAA14039 ValueError('Target crop leaves block patch: bounds=(-304, 2077, -279, 2102), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250328_2300_HARP12961_NOAA14039 ValueError('Target crop leaves block patch: bounds=(-312, 2074, -281, 2105), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250329_0036_HARP12961_NOAA14039 ValueError('Target crop leaves block patch: bounds=(-320, 2068, -281, 2107), shape=(1834, 1834)')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12961_20250328_0212_20250329_0036,completed,15,15,0,0.552,15 sample errors retained for retry

==========================================================================================
BLOCK 93/372 | 2025_HARP12961_20250329_0524_20250329_1812 | targets=9
==========================================================================================

----------------------------------------------------------------------
2025_HARP12961_20250329_0524_20250329_1812 | wavelength 94
94 Å cadence segments: 1 [('2025-03-29 05:24:00', '2025-03-29 18:12:00', 9)]
♻️ Segment 1/1 already covered by cached 94 Å files.

----------------------------------------------------------------------
2025_HARP12961_20250329_0524_20250329_1812 | wavelength 131
131 Å cadence segments: 1 [('2025-03-29 05:24:00', '2025-03-29 18:12:00', 9)]
♻️ Segment 1/1 already covered by cached 131 Å files.

----------------------------------------------------------------------
2025_HARP12961_20250329_0524_20250329_1812 | wavelength 171
171 Å cadence segments: 1 [('2025-03-29 05:24:00', '2025-03-29 18:12:00', 9)]

♻️ Segment 1/1 already covered by cached 171 Å files.

----------------------------------------------------------------------
2025_HARP12961_20250329_0524_20250329_1812 | wavelength 193
193 Å cadence segments: 1 [('2025-03-29 05:24:00', '2025-03-29 18:12:00', 9)]

♻️ Segment 1/1 already covered by cached 193 Å files.

----------------------------------------------------------------------
2025_HARP12961_20250329_0524_20250329_1812 | wavelength 211
211 Å cadence segments: 1 [('2025-03-29 05:24:00', '2025-03-29 18:12:00', 9)]

♻️ Segment 1/1 already covered by cached 211 Å files.

----------------------------------------------------------------------
2025_HARP12961_20250329_0524_20250329_1812 | wavelength 335
335 Å cadence segments: 1 [('2025-03-29 05:24:00', '2025-03-29 18:12:00', 9)]

♻️ Segment 1/1 already covered by cached 335 Å files.

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250329_0524_HARP12961_NOAA14039 ValueError('Target crop leaves block patch: bounds=(-263, 2134, -284, 2112), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250329_0700_HARP12961_NOAA14039 ValueError('Target crop leaves block patch: bounds=(-269, 2129, -285, 2113), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250329_0836_HARP12961_NOAA14039 ValueError('Target crop leaves block patch: bounds=(-273, 2125, -284, 2115), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250329_1012_HARP12961_NOAA14039 ValueError('Target crop leaves block patch: bounds=(-278, 2119, -283, 2115), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250329_1148_HARP12961_NOAA14039 ValueError('Target crop leaves block patch: bounds=(-282, 2115, -282, 2115), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250329_1324_HARP12961_NOAA14039 ValueError('Target crop leaves block patch: bounds=(-285, 2109, -280, 2114), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250329_1500_HARP12961_NOAA14039 ValueError('Target crop leaves block patch: bounds=(-288, 2103, -277, 2115), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250329_1636_HARP12961_NOAA14039 ValueError('Target crop leaves block patch: bounds=(-291, 2097, -275, 2113), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250329_1812_HARP12961_NOAA14039 ValueError('Target crop leaves block patch: bounds=(-294, 2090, -272, 2112), shape=(1834, 1834)')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12961_20250329_0524_20250329_1812,completed,9,9,0,0.338,9 sample errors retained for retry

==========================================================================================
BLOCK 94/372 | 2025_HARP12961_20250330_2300_20250331_1812 | targets=13
==========================================================================================

----------------------------------------------------------------------
2025_HARP12961_20250330_2300_20250331_1812 | wavelength 94
94 Å cadence segments: 1 [('2025-03-30 23:00:00', '2025-03-31 18:12:00', 13)]
♻️ Segment 1/1 already covered by cached 94 Å files.

----------------------------------------------------------------------
2025_HARP12961_20250330_2300_20250331_1812 | wavelength 131
131 Å cadence segments: 1 [('2025-03-30 23:00:00', '2025-03-31 18:12:00', 13)]
♻️ Segment 1/1 already covered by cached 131 Å files.

----------------------------------------------------------------------
2025_HARP12961_20250330_2300_20250331_1812 | wavelength 171
171 Å cadence segments: 1 [('2025-03-30 23:00:00', '2025-03-31 18:12:00', 13)]
♻️ Segment 1/1 already covered by cached 171 Å files.

----------------------------------------------------------------------
2025_HARP12961_20250330_2300_20250331_1812 | wavelength 193
193 Å cadence segments: 1 [('2025-03-30 23:00:00', '2025-03-31 18:12:00', 13)]
♻️ Segment 1/1 already covered by cached 193 Å files.

----------------------------------------------------------------------
2025_HARP12961_20250330_2300_20250331_1812 | wavelength 211
211 Å cadence segments: 1 [('2025-03-30 23:00:00', '2025-03-31 18:12:00', 13)]
♻️ Segment 1/1 already covered by cached 211 Å files.

----------------------------------------------------------------------
2025_HARP12961_20250330_2300_20250331_1812 | wavelength 335
335 Å cadence segments: 1 [('2025-03-30 23:00:00', '2025-03-31 18:12:00', 13)]
♻️ Segment 1/1 already covered by cached 335 Å files.

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250330_2300_HARP12961_NOAA14039 ValueError('Target crop leaves block patch: bounds=(-164, 2078, -214, 2028), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250331_0036_HARP12961_NOAA14039 ValueError('Target crop leaves block patch: bounds=(-164, 2065, -206, 2023), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250331_0212_HARP12961_NOAA14039 ValueError('Target crop leaves block patch: bounds=(-172, 2054, -200, 2026), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250331_0348_HARP12961_NOAA14039 ValueError('Target crop leaves block patch: bounds=(-176, 2042, -193, 2024), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250331_0524_HARP12961_NOAA14039 ValueError('Target crop leaves block patch: bounds=(-174, 2029, -184, 2019), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250331_0700_HARP12961_NOAA14039 ValueError('Target crop leaves block patch: bounds=(-171, 2016, -177, 2010), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250331_0836_HARP12961_NOAA14039 ValueError('Target crop leaves block patch: bounds=(-169, 2002, -169, 2002), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250331_1012_HARP12961_NOAA14039 ValueError('Target crop leaves block patch: bounds=(-171, 1990, -164, 1997), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250331_1148_HARP12961_NOAA14039 ValueError('Target crop leaves block patch: bounds=(-168, 1978, -155, 1991), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250331_1324_HARP12961_NOAA14039 ValueError('Target crop leaves block patch: bounds=(-165, 1964, -146, 1983), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250331_1500_HARP12961_NOAA14039 ValueError('Target crop leaves block patch: bounds=(-159, 1950, -135, 1974), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250331_1636_HARP12961_NOAA14039 ValueError('Target crop leaves block patch: bounds=(-155, 1934, -124, 1965), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250331_1812_HARP12961_NOAA14039 ValueError('Target crop leaves block patch: bounds=(-149, 1918, -112, 1955), shape=(1834, 1834)')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12961_20250330_2300_20250331_1812,completed,13,13,0,0.494,13 sample errors retained for retry

==========================================================================================
BLOCK 95/372 | 2025_HARP12961_20250401_0036_20250401_0036 | targets=1
==========================================================================================

----------------------------------------------------------------------
2025_HARP12961_20250401_0036_20250401_0036 | wavelength 94
94 Å cadence segments: 1 [('2025-04-01 00:36:00', '2025-04-01 00:36:00', 1)]
♻️ Segment 1/1 already covered by cached 94 Å files.

----------------------------------------------------------------------
2025_HARP12961_20250401_0036_20250401_0036 | wavelength 131
131 Å cadence segments: 1 [('2025-04-01 00:36:00', '2025-04-01 00:36:00', 1)]
♻️ Segment 1/1 already covered by cached 131 Å files.

----------------------------------------------------------------------
2025_HARP12961_20250401_0036_20250401_0036 | wavelength 171
171 Å cadence segments: 1 [('2025-04-01 00:36:00', '2025-04-01 00:36:00', 1)]
♻️ Segment 1/1 already covered by cached 171 Å files.

----------------------------------------------------------------------
2025_HARP12961_20250401_0036_20250401_0036 | wavelength 193
193 Å cadence segments: 1 [('2025-04-01 00:36:00', '2025-04-01 00:36:00', 1)]
♻️ Segment 1/1 already covered by cached 193 Å files.

----------------------------------------------------------------------
2025_HARP12961_20250401_0036_20250401_0036 | wavelength 211
211 Å cadence segments: 1 [('2025-04-01 00:36:00', '2025-04-01 00:36:00', 1)]
♻️ Segment 1/1 already covered by cached 211 Å files.

----------------------------------------------------------------------
2025_HARP12961_20250401_0036_20250401_0036 | wavelength 335
335 Å cadence segments: 1 [('2025-04-01 00:36:00', '2025-04-01 00:36:00', 1)]
♻️ Segment 1/1 already covered by cached 335 Å files.

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250401_0036_HARP12961_NOAA14039 ValueError('Target crop leaves block patch: bounds=(-22, 1854, -21, 1855), shape=(1834, 1834)')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12961_20250401_0036_20250401_0036,completed,1,1,0,0.035,1 sample errors retained for retry

==========================================================================================
BLOCK 96/372 | 2025_HARP12993_20250402_0236_20250402_1212 | targets=7
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP12993_20250402_0236_20250402_1212,already_complete,7,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 97/372 | 2025_HARP13004_20250402_0924_20250402_1236 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13004_20250402_0924_20250402_1236,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 98/372 | 2025_HARP13009_20250402_2024_20250402_2336 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13009_20250402_2024_20250402_2336,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 99/372 | 2025_HARP13004_20250403_0248_20250403_0424 | targets=2
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13004_20250403_0248_20250403_0424,already_complete,2,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 100/372 | 2025_HARP13011_20250403_2048_20250404_1912 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13011_20250403_2048_20250404_1912,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 101/372 | 2025_HARP13009_20250404_0748_20250405_0612 | targets=15
==========================================================================================

----------------------------------------------------------------------
2025_HARP13009_20250404_0748_20250405_0612 | wavelength 94
94 Å cadence segments: 1 [('2025-04-04 07:48:00', '2025-04-05 06:12:00', 15)]
Segment query: aia.lev1_euv_12s[2025-04-04T07:48:00.000/1440m@96m][94]{image}
Segment reference: 2025-04-04 19:00:00 | targets: 15 | patch arcsec: 494.3349773481148
JSOC export attempt 1/10

2026-06-30 08:59:59 - drms - INFO: Export request pending. [id=JSOC_20260630_005980, status=2]

2026-06-30 08:59:59 - drms - INFO: Waiting for 15 seconds...

2026-06-30 09:00:15 - drms - INFO: Export request pending. [id=JSOC_20260630_005980, status=1]

2026-06-30 09:00:15 - drms - INFO: Waiting for 15 seconds...

2026-06-30 09:00:30 - drms - INFO: Export request pending. [id=JSOC_20260630_005980, status=1]

2026-06-30 09:00:30 - drms - INFO: Waiting for 15 seconds...

2026-06-30 09:00:46 - drms - INFO: Export request pending. [id=JSOC_20260630_005980, status=1]

2026-06-30 09:00:46 - drms - INFO: Waiting for 15 seconds...

2026-06-30 09:01:02 - drms - INFO: Export request finished. [id=JSOC_20260630_005980, status=0]

2026-06-30 09:01:02 - drms - INFO: Downloading file 1 of 12...

2026-06-30 09:01:02 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-04-04T07:47:59Z][94][JSOC_20260630_005980]

2026-06-30 09:01:02 - drms - INFO:     filename: aia.lev1_euv_12s.2025-04-04T074759Z.94.image.fits

2026-06-30 09:01:03 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13009_20250404_0748_20250405_0612/94/segment_01_20250404_0748_20250405_0612/aia.lev1_euv_12s.2025-04-04T074759Z.94.image.fits.1

2026-06-30 09:01:03 - drms - INFO: Downloading file 2 of 12...

2026-06-30 09:01:03 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-04-04T09:23:59Z][94][JSOC_20260630_005980]

2026-06-30 09:01:03 - drms - INFO:     filename: aia.lev1_euv_12s.2025-04-04T092359Z.94.image.fits

2026-06-30 09:01:05 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13009_20250404_0748_20250405_0612/94/segment_01_20250404_0748_20250405_0612/aia.lev1_euv_12s.2025-04-04T092359Z.94.image.fits.1

2026-06-30 09:01:05 - drms - INFO: Downloading file 3 of 12...

2026-06-30 09:01:05 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-04-04T10:59:59Z][94][JSOC_20260630_005980]

2026-06-30 09:01:05 - drms - INFO:     filename: aia.lev1_euv_12s.2025-04-04T105959Z.94.image.fits

2026-06-30 09:01:06 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13009_20250404_0748_20250405_0612/94/segment_01_20250404_0748_20250405_0612/aia.lev1_euv_12s.2025-04-04T105959Z.94.image.fits.1

2026-06-30 09:01:06 - drms - INFO: Downloading file 4 of 12...

2026-06-30 09:01:06 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-04-04T12:35:59Z][94][JSOC_20260630_005980]

2026-06-30 09:01:06 - drms - INFO:     filename: aia.lev1_euv_12s.2025-04-04T123559Z.94.image.fits

2026-06-30 09:01:08 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13009_20250404_0748_20250405_0612/94/segment_01_20250404_0748_20250405_0612/aia.lev1_euv_12s.2025-04-04T123559Z.94.image.fits.1

2026-06-30 09:01:08 - drms - INFO: Downloading file 5 of 12...

2026-06-30 09:01:08 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-04-04T14:11:59Z][94][JSOC_20260630_005980]

2026-06-30 09:01:08 - drms - INFO:     filename: aia.lev1_euv_12s.2025-04-04T141159Z.94.image.fits

2026-06-30 09:01:10 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13009_20250404_0748_20250405_0612/94/segment_01_20250404_0748_20250405_0612/aia.lev1_euv_12s.2025-04-04T141159Z.94.image.fits.1

2026-06-30 09:01:10 - drms - INFO: Downloading file 6 of 12...

2026-06-30 09:01:10 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-04-04T15:47:59Z][94][JSOC_20260630_005980]

2026-06-30 09:01:10 - drms - INFO:     filename: aia.lev1_euv_12s.2025-04-04T154759Z.94.image.fits

2026-06-30 09:01:12 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13009_20250404_0748_20250405_0612/94/segment_01_20250404_0748_20250405_0612/aia.lev1_euv_12s.2025-04-04T154759Z.94.image.fits.1

2026-06-30 09:01:12 - drms - INFO: Downloading file 7 of 12...

2026-06-30 09:01:12 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-04-04T17:23:59Z][94][JSOC_20260630_005980]

2026-06-30 09:01:12 - drms - INFO:     filename: aia.lev1_euv_12s.2025-04-04T172359Z.94.image.fits

2026-06-30 09:01:13 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13009_20250404_0748_20250405_0612/94/segment_01_20250404_0748_20250405_0612/aia.lev1_euv_12s.2025-04-04T172359Z.94.image.fits.1

2026-06-30 09:01:13 - drms - INFO: Downloading file 8 of 12...

2026-06-30 09:01:13 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-04-04T18:59:59Z][94][JSOC_20260630_005980]

2026-06-30 09:01:13 - drms - INFO:     filename: aia.lev1_euv_12s.2025-04-04T185959Z.94.image.fits

2026-06-30 09:01:15 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13009_20250404_0748_20250405_0612/94/segment_01_20250404_0748_20250405_0612/aia.lev1_euv_12s.2025-04-04T185959Z.94.image.fits.1

2026-06-30 09:01:15 - drms - INFO: Downloading file 9 of 12...

2026-06-30 09:01:15 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-04-04T20:35:59Z][94][JSOC_20260630_005980]

2026-06-30 09:01:15 - drms - INFO:     filename: aia.lev1_euv_12s.2025-04-04T203559Z.94.image.fits

2026-06-30 09:01:17 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13009_20250404_0748_20250405_0612/94/segment_01_20250404_0748_20250405_0612/aia.lev1_euv_12s.2025-04-04T203559Z.94.image.fits.1

2026-06-30 09:01:17 - drms - INFO: Downloading file 10 of 12...

2026-06-30 09:01:17 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-04-04T22:11:59Z][94][JSOC_20260630_005980]

2026-06-30 09:01:17 - drms - INFO:     filename: aia.lev1_euv_12s.2025-04-04T221159Z.94.image.fits

2026-06-30 09:01:18 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13009_20250404_0748_20250405_0612/94/segment_01_20250404_0748_20250405_0612/aia.lev1_euv_12s.2025-04-04T221159Z.94.image.fits.1

2026-06-30 09:01:18 - drms - INFO: Downloading file 11 of 12...

2026-06-30 09:01:18 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-04-05T04:35:59Z][94][JSOC_20260630_005980]

2026-06-30 09:01:18 - drms - INFO:     filename: aia.lev1_euv_12s.2025-04-05T043559Z.94.image.fits

2026-06-30 09:01:20 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13009_20250404_0748_20250405_0612/94/segment_01_20250404_0748_20250405_0612/aia.lev1_euv_12s.2025-04-05T043559Z.94.image.fits.1

2026-06-30 09:01:20 - drms - INFO: Downloading file 12 of 12...

2026-06-30 09:01:20 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-04-05T06:11:59Z][94][JSOC_20260630_005980]

2026-06-30 09:01:20 - drms - INFO:     filename: aia.lev1_euv_12s.2025-04-05T061159Z.94.image.fits

2026-06-30 09:01:22 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13009_20250404_0748_20250405_0612/94/segment_01_20250404_0748_20250405_0612/aia.lev1_euv_12s.2025-04-05T061159Z.94.image.fits.1

BLOCK ERROR: RuntimeError('Downloaded 94 Å segment does not cover all target timestamps within 180 seconds.')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13009_20250404_0748_20250405_0612,error,15,None,0,None,RuntimeError('Downloaded 94 Å segment does not...

==========================================================================================
BLOCK 102/372 | 2025_HARP13004_20250405_0748_20250406_0612 | targets=15
==========================================================================================

----------------------------------------------------------------------
2025_HARP13004_20250405_0748_20250406_0612 | wavelength 94
94 Å cadence segments: 1 [('2025-04-05 07:48:00', '2025-04-06 06:12:00', 15)]
Segment query: aia.lev1_euv_12s[2025-04-05T07:48:00.000/1440m@96m][94]{image}
Segment reference: 2025-04-05 19:00:00 | targets: 15 | patch arcsec: 887.1229697652183
JSOC export attempt 1/10

2026-06-30 09:01:26 - drms - INFO: Export request pending. [id=JSOC_20260630_006002, status=2]

2026-06-30 09:01:26 - drms - INFO: Waiting for 15 seconds...

2026-06-30 09:01:42 - drms - INFO: Export request pending. [id=JSOC_20260630_006002, status=1]

2026-06-30 09:01:42 - drms - INFO: Waiting for 15 seconds...

2026-06-30 09:01:58 - drms - INFO: Export request pending. [id=JSOC_20260630_006002, status=1]

2026-06-30 09:01:58 - drms - INFO: Waiting for 15 seconds...

2026-06-30 09:02:13 - drms - INFO: Export request pending. [id=JSOC_20260630_006002, status=1]

2026-06-30 09:02:13 - drms - INFO: Waiting for 15 seconds...

2026-06-30 09:02:29 - drms - INFO: Export request pending. [id=JSOC_20260630_006002, status=1]

2026-06-30 09:02:29 - drms - INFO: Waiting for 15 seconds...

2026-06-30 09:02:44 - drms - INFO: Export request finished. [id=JSOC_20260630_006002, status=0]

2026-06-30 09:02:44 - drms - INFO: Downloading file 1 of 14...

2026-06-30 09:02:44 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-04-05T07:47:59Z][94][JSOC_20260630_006002]

2026-06-30 09:02:44 - drms - INFO:     filename: aia.lev1_euv_12s.2025-04-05T074759Z.94.image.fits

2026-06-30 09:02:47 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13004_20250405_0748_20250406_0612/94/segment_01_20250405_0748_20250406_0612/aia.lev1_euv_12s.2025-04-05T074759Z.94.image.fits.1

2026-06-30 09:02:47 - drms - INFO: Downloading file 2 of 14...

2026-06-30 09:02:47 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-04-05T09:23:59Z][94][JSOC_20260630_006002]

2026-06-30 09:02:47 - drms - INFO:     filename: aia.lev1_euv_12s.2025-04-05T092359Z.94.image.fits

2026-06-30 09:02:50 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13004_20250405_0748_20250406_0612/94/segment_01_20250405_0748_20250406_0612/aia.lev1_euv_12s.2025-04-05T092359Z.94.image.fits.1

2026-06-30 09:02:50 - drms - INFO: Downloading file 3 of 14...

2026-06-30 09:02:50 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-04-05T10:59:59Z][94][JSOC_20260630_006002]

2026-06-30 09:02:50 - drms - INFO:     filename: aia.lev1_euv_12s.2025-04-05T105959Z.94.image.fits

2026-06-30 09:02:52 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13004_20250405_0748_20250406_0612/94/segment_01_20250405_0748_20250406_0612/aia.lev1_euv_12s.2025-04-05T105959Z.94.image.fits.1

2026-06-30 09:02:52 - drms - INFO: Downloading file 4 of 14...

2026-06-30 09:02:52 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-04-05T14:11:59Z][94][JSOC_20260630_006002]

2026-06-30 09:02:52 - drms - INFO:     filename: aia.lev1_euv_12s.2025-04-05T141159Z.94.image.fits

2026-06-30 09:02:55 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13004_20250405_0748_20250406_0612/94/segment_01_20250405_0748_20250406_0612/aia.lev1_euv_12s.2025-04-05T141159Z.94.image.fits.1

2026-06-30 09:02:55 - drms - INFO: Downloading file 5 of 14...

2026-06-30 09:02:55 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-04-05T15:47:59Z][94][JSOC_20260630_006002]

2026-06-30 09:02:55 - drms - INFO:     filename: aia.lev1_euv_12s.2025-04-05T154759Z.94.image.fits

2026-06-30 09:02:57 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13004_20250405_0748_20250406_0612/94/segment_01_20250405_0748_20250406_0612/aia.lev1_euv_12s.2025-04-05T154759Z.94.image.fits.1

2026-06-30 09:02:57 - drms - INFO: Downloading file 6 of 14...

2026-06-30 09:02:57 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-04-05T17:23:59Z][94][JSOC_20260630_006002]

2026-06-30 09:02:57 - drms - INFO:     filename: aia.lev1_euv_12s.2025-04-05T172359Z.94.image.fits

2026-06-30 09:03:00 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13004_20250405_0748_20250406_0612/94/segment_01_20250405_0748_20250406_0612/aia.lev1_euv_12s.2025-04-05T172359Z.94.image.fits.1

2026-06-30 09:03:00 - drms - INFO: Downloading file 7 of 14...

2026-06-30 09:03:00 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-04-05T18:59:59Z][94][JSOC_20260630_006002]

2026-06-30 09:03:00 - drms - INFO:     filename: aia.lev1_euv_12s.2025-04-05T185959Z.94.image.fits

2026-06-30 09:03:02 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13004_20250405_0748_20250406_0612/94/segment_01_20250405_0748_20250406_0612/aia.lev1_euv_12s.2025-04-05T185959Z.94.image.fits.1

2026-06-30 09:03:02 - drms - INFO: Downloading file 8 of 14...

2026-06-30 09:03:02 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-04-05T20:35:59Z][94][JSOC_20260630_006002]

2026-06-30 09:03:02 - drms - INFO:     filename: aia.lev1_euv_12s.2025-04-05T203559Z.94.image.fits

2026-06-30 09:03:04 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13004_20250405_0748_20250406_0612/94/segment_01_20250405_0748_20250406_0612/aia.lev1_euv_12s.2025-04-05T203559Z.94.image.fits.1

2026-06-30 09:03:04 - drms - INFO: Downloading file 9 of 14...

2026-06-30 09:03:04 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-04-05T22:11:59Z][94][JSOC_20260630_006002]

2026-06-30 09:03:04 - drms - INFO:     filename: aia.lev1_euv_12s.2025-04-05T221159Z.94.image.fits

2026-06-30 09:03:07 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13004_20250405_0748_20250406_0612/94/segment_01_20250405_0748_20250406_0612/aia.lev1_euv_12s.2025-04-05T221159Z.94.image.fits.1

2026-06-30 09:03:07 - drms - INFO: Downloading file 10 of 14...

2026-06-30 09:03:07 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-04-05T23:47:59Z][94][JSOC_20260630_006002]

2026-06-30 09:03:07 - drms - INFO:     filename: aia.lev1_euv_12s.2025-04-05T234759Z.94.image.fits

2026-06-30 09:03:09 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13004_20250405_0748_20250406_0612/94/segment_01_20250405_0748_20250406_0612/aia.lev1_euv_12s.2025-04-05T234759Z.94.image.fits.1

2026-06-30 09:03:09 - drms - INFO: Downloading file 11 of 14...

2026-06-30 09:03:09 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-04-06T01:23:59Z][94][JSOC_20260630_006002]

2026-06-30 09:03:09 - drms - INFO:     filename: aia.lev1_euv_12s.2025-04-06T012359Z.94.image.fits

2026-06-30 09:03:12 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13004_20250405_0748_20250406_0612/94/segment_01_20250405_0748_20250406_0612/aia.lev1_euv_12s.2025-04-06T012359Z.94.image.fits.1

2026-06-30 09:03:12 - drms - INFO: Downloading file 12 of 14...

2026-06-30 09:03:12 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-04-06T02:59:59Z][94][JSOC_20260630_006002]

2026-06-30 09:03:12 - drms - INFO:     filename: aia.lev1_euv_12s.2025-04-06T025959Z.94.image.fits

2026-06-30 09:03:15 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13004_20250405_0748_20250406_0612/94/segment_01_20250405_0748_20250406_0612/aia.lev1_euv_12s.2025-04-06T025959Z.94.image.fits.1

2026-06-30 09:03:15 - drms - INFO: Downloading file 13 of 14...

2026-06-30 09:03:15 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-04-06T04:35:59Z][94][JSOC_20260630_006002]

2026-06-30 09:03:15 - drms - INFO:     filename: aia.lev1_euv_12s.2025-04-06T043559Z.94.image.fits

2026-06-30 09:03:17 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13004_20250405_0748_20250406_0612/94/segment_01_20250405_0748_20250406_0612/aia.lev1_euv_12s.2025-04-06T043559Z.94.image.fits.1

2026-06-30 09:03:17 - drms - INFO: Downloading file 14 of 14...

2026-06-30 09:03:17 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-04-06T06:11:59Z][94][JSOC_20260630_006002]

2026-06-30 09:03:17 - drms - INFO:     filename: aia.lev1_euv_12s.2025-04-06T061159Z.94.image.fits

2026-06-30 09:03:19 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13004_20250405_0748_20250406_0612/94/segment_01_20250405_0748_20250406_0612/aia.lev1_euv_12s.2025-04-06T061159Z.94.image.fits.1

BLOCK ERROR: RuntimeError('Downloaded 94 Å segment does not cover all target timestamps within 180 seconds.')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13004_20250405_0748_20250406_0612,error,15,None,0,None,RuntimeError('Downloaded 94 Å segment does not...

==========================================================================================
BLOCK 103/372 | 2025_HARP13030_20250406_0936_20250407_0800 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13030_20250406_0936_20250407_0800,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 104/372 | 2025_HARP13024_20250407_1936_20250408_1624 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13024_20250407_1936_20250408_1624,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 105/372 | 2025_HARP13024_20250408_2000_20250408_2312 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13024_20250408_2000_20250408_2312,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 106/372 | 2025_HARP13053_20250409_1936_20250409_2248 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13053_20250409_1936_20250409_2248,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 107/372 | 2025_HARP13036_20250410_2000_20250411_1824 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13036_20250410_2000_20250411_1824,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 108/372 | 2025_HARP13044_20250412_0124_20250412_2348 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13044_20250412_0124_20250412_2348,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 109/372 | 2025_HARP13035_20250413_1100_20250413_1100 | targets=1
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13035_20250413_1100_20250413_1100,already_complete,1,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 110/372 | 2025_HARP13036_20250413_2136_20250414_0848 | targets=8
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13036_20250413_2136_20250414_0848,already_complete,8,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 111/372 | 2025_HARP13035_20250414_2036_20250414_2348 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13035_20250414_2036_20250414_2348,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 112/372 | 2025_HARP13056_20250415_0300_20250415_1100 | targets=6
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13056_20250415_0300_20250415_1100,already_complete,6,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 113/372 | 2025_HARP13102_20250415_1836_20250415_2336 | targets=4
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13102_20250415_1836_20250415_2336,already_complete,4,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 114/372 | 2025_HARP13102_20250416_0736_20250416_1400 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13102_20250416_0736_20250416_1400,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 115/372 | 2025_HARP13078_20250417_0736_20250417_1536 | targets=6
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13078_20250417_0736_20250417_1536,already_complete,6,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 116/372 | 2025_HARP13102_20250418_0736_20250418_1848 | targets=8
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13102_20250418_0736_20250418_1848,already_complete,8,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 117/372 | 2025_HARP13102_20250419_0736_20250419_1712 | targets=7
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13102_20250419_0736_20250419_1712,already_complete,7,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 118/372 | 2025_HARP13091_20250421_0036_20250421_0036 | targets=1
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13091_20250421_0036_20250421_0036,already_complete,1,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 119/372 | 2025_HARP13108_20250421_0736_20250421_2200 | targets=10
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13108_20250421_0736_20250421_2200,already_complete,10,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 120/372 | 2025_HARP13091_20250422_0348_20250423_0212 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13091_20250422_0348_20250423_0212,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 121/372 | 2025_HARP13108_20250423_0112_20250423_0424 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13108_20250423_0112_20250423_0424,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 122/372 | 2025_HARP13108_20250423_0736_20250424_0624 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13108_20250423_0736_20250424_0624,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 123/372 | 2025_HARP13104_20250424_0148_20250424_2100 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13104_20250424_0148_20250424_2100,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 124/372 | 2025_HARP13118_20250424_1936_20250425_0824 | targets=9
==========================================================================================

----------------------------------------------------------------------
2025_HARP13118_20250424_1936_20250425_0824 | wavelength 94
94 Å cadence segments: 1 [('2025-04-24 19:36:00', '2025-04-25 08:24:00', 9)]
Segment query: aia.lev1_euv_12s[2025-04-24T19:36:00.000/864m@96m][94]{image}
Segment reference: 2025-04-25 02:00:00 | targets: 9 | patch arcsec: 873.962772991921
JSOC export attempt 1/10

2026-06-30 09:04:04 - drms - INFO: Export request pending. [id=JSOC_20260630_006031, status=2]

2026-06-30 09:04:04 - drms - INFO: Waiting for 15 seconds...

2026-06-30 09:04:20 - drms - INFO: Export request pending. [id=JSOC_20260630_006031, status=1]

2026-06-30 09:04:20 - drms - INFO: Waiting for 15 seconds...

2026-06-30 09:04:35 - drms - INFO: Export request pending. [id=JSOC_20260630_006031, status=1]

2026-06-30 09:04:35 - drms - INFO: Waiting for 15 seconds...

2026-06-30 09:04:51 - drms - INFO: Export request pending. [id=JSOC_20260630_006031, status=1]

2026-06-30 09:04:51 - drms - INFO: Waiting for 15 seconds...

2026-06-30 09:05:06 - drms - INFO: Export request finished. [id=JSOC_20260630_006031, status=0]

2026-06-30 09:05:06 - drms - INFO: Downloading file 1 of 8...

2026-06-30 09:05:06 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-04-24T21:11:59Z][94][JSOC_20260630_006031]

2026-06-30 09:05:06 - drms - INFO:     filename: aia.lev1_euv_12s.2025-04-24T211159Z.94.image.fits

2026-06-30 09:05:09 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13118_20250424_1936_20250425_0824/94/segment_01_20250424_1936_20250425_0824/aia.lev1_euv_12s.2025-04-24T211159Z.94.image.fits.2

2026-06-30 09:05:09 - drms - INFO: Downloading file 2 of 8...

2026-06-30 09:05:09 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-04-24T22:47:59Z][94][JSOC_20260630_006031]

2026-06-30 09:05:09 - drms - INFO:     filename: aia.lev1_euv_12s.2025-04-24T224759Z.94.image.fits

2026-06-30 09:05:11 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13118_20250424_1936_20250425_0824/94/segment_01_20250424_1936_20250425_0824/aia.lev1_euv_12s.2025-04-24T224759Z.94.image.fits.2

2026-06-30 09:05:11 - drms - INFO: Downloading file 3 of 8...

2026-06-30 09:05:11 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-04-25T00:23:59Z][94][JSOC_20260630_006031]

2026-06-30 09:05:11 - drms - INFO:     filename: aia.lev1_euv_12s.2025-04-25T002359Z.94.image.fits

2026-06-30 09:05:14 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13118_20250424_1936_20250425_0824/94/segment_01_20250424_1936_20250425_0824/aia.lev1_euv_12s.2025-04-25T002359Z.94.image.fits.2

2026-06-30 09:05:14 - drms - INFO: Downloading file 4 of 8...

2026-06-30 09:05:14 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-04-25T01:59:59Z][94][JSOC_20260630_006031]

2026-06-30 09:05:14 - drms - INFO:     filename: aia.lev1_euv_12s.2025-04-25T015959Z.94.image.fits

2026-06-30 09:05:16 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13118_20250424_1936_20250425_0824/94/segment_01_20250424_1936_20250425_0824/aia.lev1_euv_12s.2025-04-25T015959Z.94.image.fits.2

2026-06-30 09:05:16 - drms - INFO: Downloading file 5 of 8...

2026-06-30 09:05:16 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-04-25T03:35:59Z][94][JSOC_20260630_006031]

2026-06-30 09:05:16 - drms - INFO:     filename: aia.lev1_euv_12s.2025-04-25T033559Z.94.image.fits

2026-06-30 09:05:19 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13118_20250424_1936_20250425_0824/94/segment_01_20250424_1936_20250425_0824/aia.lev1_euv_12s.2025-04-25T033559Z.94.image.fits.2

2026-06-30 09:05:19 - drms - INFO: Downloading file 6 of 8...

2026-06-30 09:05:19 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-04-25T05:11:59Z][94][JSOC_20260630_006031]

2026-06-30 09:05:19 - drms - INFO:     filename: aia.lev1_euv_12s.2025-04-25T051159Z.94.image.fits

2026-06-30 09:05:21 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13118_20250424_1936_20250425_0824/94/segment_01_20250424_1936_20250425_0824/aia.lev1_euv_12s.2025-04-25T051159Z.94.image.fits.2

2026-06-30 09:05:21 - drms - INFO: Downloading file 7 of 8...

2026-06-30 09:05:21 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-04-25T06:47:59Z][94][JSOC_20260630_006031]

2026-06-30 09:05:21 - drms - INFO:     filename: aia.lev1_euv_12s.2025-04-25T064759Z.94.image.fits

2026-06-30 09:05:24 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13118_20250424_1936_20250425_0824/94/segment_01_20250424_1936_20250425_0824/aia.lev1_euv_12s.2025-04-25T064759Z.94.image.fits.2

2026-06-30 09:05:24 - drms - INFO: Downloading file 8 of 8...

2026-06-30 09:05:24 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-04-25T08:23:59Z][94][JSOC_20260630_006031]

2026-06-30 09:05:24 - drms - INFO:     filename: aia.lev1_euv_12s.2025-04-25T082359Z.94.image.fits

2026-06-30 09:05:26 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13118_20250424_1936_20250425_0824/94/segment_01_20250424_1936_20250425_0824/aia.lev1_euv_12s.2025-04-25T082359Z.94.image.fits.2

BLOCK ERROR: RuntimeError('Downloaded 94 Å segment does not cover all target timestamps within 180 seconds.')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13118_20250424_1936_20250425_0824,error,9,None,0,None,RuntimeError('Downloaded 94 Å segment does not...

==========================================================================================
BLOCK 125/372 | 2025_HARP13108_20250425_0800_20250425_1424 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13108_20250425_0800_20250425_1424,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 126/372 | 2025_HARP13117_20250425_2224_20250426_2048 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13117_20250425_2224_20250426_2048,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 127/372 | 2025_HARP13133_20250426_1248_20250427_1200 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13133_20250426_1248_20250427_1200,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 128/372 | 2025_HARP13117_20250426_2224_20250427_1824 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13117_20250426_2224_20250427_1824,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 129/372 | 2025_HARP13133_20250427_1336_20250427_1824 | targets=4
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13133_20250427_1336_20250427_1824,already_complete,4,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 130/372 | 2025_HARP13142_20250428_0200_20250428_2148 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13142_20250428_0200_20250428_2148,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 131/372 | 2025_HARP13144_20250428_0236_20250428_1736 | targets=10
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13144_20250428_0236_20250428_1736,already_complete,10,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 132/372 | 2025_HARP13147_20250428_1100_20250429_0924 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13147_20250428_1100_20250429_0924,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 133/372 | 2025_HARP13133_20250429_0048_20250429_2000 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13133_20250429_0048_20250429_2000,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 134/372 | 2025_HARP13147_20250429_1100_20250429_1724 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13147_20250429_1100_20250429_1724,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 135/372 | 2025_HARP13133_20250430_0048_20250430_2324 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13133_20250430_0048_20250430_2324,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 136/372 | 2025_HARP13145_20250430_1948_20250430_2124 | targets=2
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13145_20250430_1948_20250430_2124,already_complete,2,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 137/372 | 2025_HARP13147_20250501_1424_20250502_1248 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13147_20250501_1424_20250502_1248,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 138/372 | 2025_HARP13171_20250502_2236_20250503_0012 | targets=2
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13171_20250502_2236_20250503_0012,already_complete,2,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 139/372 | 2025_HARP13171_20250503_1200_20250504_0224 | targets=10
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13171_20250503_1200_20250504_0224,already_complete,10,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 140/372 | 2025_HARP13171_20250505_0024_20250505_1624 | targets=11
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13171_20250505_0024_20250505_1624,already_complete,11,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 141/372 | 2025_HARP13171_20250505_1936_20250505_2112 | targets=2
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13171_20250505_1936_20250505_2112,already_complete,2,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 142/372 | 2025_HARP13182_20250506_0736_20250506_1712 | targets=7
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13182_20250506_0736_20250506_1712,already_complete,7,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 143/372 | 2025_HARP13171_20250507_0024_20250507_1136 | targets=8
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13171_20250507_0024_20250507_1136,already_complete,8,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 144/372 | 2025_HARP13190_20250508_0736_20250509_0424 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13190_20250508_0736_20250509_0424,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 145/372 | 2025_HARP13207_20250509_2324_20250510_2012 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13207_20250509_2324_20250510_2012,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 146/372 | 2025_HARP13190_20250510_2336_20250511_0424 | targets=4
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13190_20250510_2336_20250511_0424,already_complete,4,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 147/372 | 2025_HARP13207_20250511_2324_20250512_2148 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13207_20250511_2324_20250512_2148,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 148/372 | 2025_HARP13199_20250513_0312_20250513_1736 | targets=10
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13199_20250513_0312_20250513_1736,already_complete,10,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 149/372 | 2025_HARP13199_20250514_0136_20250514_1112 | targets=7
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13199_20250514_0136_20250514_1112,already_complete,7,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 150/372 | 2025_HARP13199_20250515_1500_20250515_1500 | targets=1
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13199_20250515_1500_20250515_1500,already_complete,1,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 151/372 | 2025_HARP13231_20250517_0900_20250518_0724 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13231_20250517_0900_20250518_0724,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 152/372 | 2025_HARP13249_20250518_1936_20250519_1624 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13249_20250518_1936_20250519_1624,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 153/372 | 2025_HARP13246_20250519_1424_20250520_1248 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13246_20250519_1424_20250520_1248,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 154/372 | 2025_HARP13232_20250520_0036_20250520_2300 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13232_20250520_0036_20250520_2300,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 155/372 | 2025_HARP13249_20250520_1936_20250521_1624 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13249_20250520_1936_20250521_1624,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 156/372 | 2025_HARP13269_20250521_0712_20250521_2212 | targets=10
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13269_20250521_0712_20250521_2212,already_complete,10,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 157/372 | 2025_HARP13246_20250522_1936_20250523_1624 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13246_20250522_1936_20250523_1624,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 158/372 | 2025_HARP13264_20250523_1548_20250524_1412 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13264_20250523_1548_20250524_1412,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 159/372 | 2025_HARP13264_20250524_1548_20250525_1412 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13264_20250524_1548_20250525_1412,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 160/372 | 2025_HARP13264_20250525_1548_20250526_1412 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13264_20250525_1548_20250526_1412,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 161/372 | 2025_HARP13292_20250526_0736_20250527_0636 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13292_20250526_0736_20250527_0636,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 162/372 | 2025_HARP13273_20250527_0500_20250528_0412 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13273_20250527_0500_20250528_0412,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 163/372 | 2025_HARP13264_20250527_1948_20250527_1948 | targets=1
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13264_20250527_1948_20250527_1948,already_complete,1,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 164/372 | 2025_HARP13274_20250528_0812_20250529_0712 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13274_20250528_0812_20250529_0712,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 165/372 | 2025_HARP13274_20250529_0848_20250529_1824 | targets=7
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13274_20250529_0848_20250529_1824,already_complete,7,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 166/372 | 2025_HARP13299_20250530_1700_20250530_2324 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13299_20250530_1700_20250530_2324,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 167/372 | 2025_HARP13294_20250601_0236_20250602_0100 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13294_20250601_0236_20250602_0100,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 168/372 | 2025_HARP13299_20250602_0236_20250603_0100 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13299_20250602_0236_20250603_0100,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 169/372 | 2025_HARP13306_20250603_0748_20250604_0500 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13306_20250603_0748_20250604_0500,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 170/372 | 2025_HARP13306_20250605_0848_20250605_1200 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13306_20250605_0848_20250605_1200,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 171/372 | 2025_HARP13327_20250607_0100_20250607_2324 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13327_20250607_0100_20250607_2324,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 172/372 | 2025_HARP13323_20250607_2312_20250608_2136 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13323_20250607_2312_20250608_2136,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 173/372 | 2025_HARP13323_20250608_2312_20250609_2136 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13323_20250608_2312_20250609_2136,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 174/372 | 2025_HARP13347_20250610_1648_20250611_1512 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13347_20250610_1648_20250611_1512,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 175/372 | 2025_HARP13323_20250611_2324_20250612_1036 | targets=8
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13323_20250611_2324_20250612_1036,already_complete,8,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 176/372 | 2025_HARP13345_20250613_0736_20250614_0424 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13345_20250613_0736_20250614_0424,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 177/372 | 2025_HARP13366_20250614_1812_20250615_1636 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13366_20250614_1812_20250615_1636,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 178/372 | 2025_HARP13366_20250615_1812_20250616_0212 | targets=6
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13366_20250615_1812_20250616_0212,already_complete,6,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 179/372 | 2025_HARP13345_20250616_0736_20250617_0424 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13345_20250616_0736_20250617_0424,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 180/372 | 2025_HARP13366_20250618_0700_20250619_0236 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13366_20250618_0700_20250619_0236,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 181/372 | 2025_HARP13386_20250622_0012_20250622_2236 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13386_20250622_0012_20250622_2236,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 182/372 | 2025_HARP13403_20250623_0736_20250624_0424 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13403_20250623_0736_20250624_0424,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 183/372 | 2025_HARP13403_20250624_0736_20250625_0424 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13403_20250624_0736_20250625_0424,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 184/372 | 2025_HARP13403_20250625_0736_20250625_1736 | targets=7
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13403_20250625_0736_20250625_1736,already_complete,7,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 185/372 | 2025_HARP13415_20250625_2148_20250626_0724 | targets=7
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13415_20250625_2148_20250626_0724,already_complete,7,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 186/372 | 2025_HARP13434_20250626_2012_20250627_1900 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13434_20250626_2012_20250627_1900,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 187/372 | 2025_HARP13434_20250627_2036_20250628_1900 | targets=15
==========================================================================================

----------------------------------------------------------------------
2025_HARP13434_20250627_2036_20250628_1900 | wavelength 94
94 Å cadence segments: 1 [('2025-06-27 20:36:00', '2025-06-28 19:00:00', 15)]
♻️ Segment 1/1 already covered by cached 94 Å files.

----------------------------------------------------------------------
2025_HARP13434_20250627_2036_20250628_1900 | wavelength 131
131 Å cadence segments: 1 [('2025-06-27 20:36:00', '2025-06-28 19:00:00', 15)]
♻️ Segment 1/1 already covered by cached 131 Å files.

----------------------------------------------------------------------
2025_HARP13434_20250627_2036_20250628_1900 | wavelength 171
171 Å cadence segments: 1 [('2025-06-27 20:36:00', '2025-06-28 19:00:00', 15)]
♻️ Segment 1/1 already covered by cached 171 Å files.

----------------------------------------------------------------------
2025_HARP13434_20250627_2036_20250628_1900 | wavelength 193
193 Å cadence segments: 1 [('2025-06-27 20:36:00', '2025-06-28 19:00:00', 15)]
♻️ Segment 1/1 already covered by cached 193 Å files.

----------------------------------------------------------------------
2025_HARP13434_20250627_2036_20250628_1900 | wavelength 211
211 Å cadence segments: 1 [('2025-06-27 20:36:00', '2025-06-28 19:00:00', 15)]
Segment query: aia.lev1_euv_12s[2025-06-27T20:36:00.000/1440m@96m][211]{image}
Segment reference: 2025-06-28 07:48:00 | targets: 15 | patch arcsec: 354.12478688257966
JSOC export attempt 1/10

2026-06-30 09:07:28 - drms - INFO: Export request pending. [id=JSOC_20260630_006071, status=2]

2026-06-30 09:07:28 - drms - INFO: Waiting for 15 seconds...

2026-06-30 09:07:44 - drms - INFO: Export request pending. [id=JSOC_20260630_006071, status=1]

2026-06-30 09:07:44 - drms - INFO: Waiting for 15 seconds...

2026-06-30 09:07:59 - drms - INFO: Export request pending. [id=JSOC_20260630_006071, status=1]

2026-06-30 09:07:59 - drms - INFO: Waiting for 15 seconds...

2026-06-30 09:08:15 - drms - INFO: Export request pending. [id=JSOC_20260630_006071, status=1]

2026-06-30 09:08:15 - drms - INFO: Waiting for 15 seconds...

2026-06-30 09:08:30 - drms - INFO: Export request finished. [id=JSOC_20260630_006071, status=0]

2026-06-30 09:08:30 - drms - INFO: Downloading file 1 of 14...

2026-06-30 09:08:30 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-06-27T20:35:59Z][211][JSOC_20260630_006071]

2026-06-30 09:08:30 - drms - INFO:     filename: aia.lev1_euv_12s.2025-06-27T203559Z.211.image.fits

2026-06-30 09:08:32 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13434_20250627_2036_20250628_1900/211/segment_01_20250627_2036_20250628_1900/aia.lev1_euv_12s.2025-06-27T203559Z.211.image.fits.1

2026-06-30 09:08:32 - drms - INFO: Downloading file 2 of 14...

2026-06-30 09:08:32 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-06-27T22:11:59Z][211][JSOC_20260630_006071]

2026-06-30 09:08:32 - drms - INFO:     filename: aia.lev1_euv_12s.2025-06-27T221159Z.211.image.fits

2026-06-30 09:08:33 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13434_20250627_2036_20250628_1900/211/segment_01_20250627_2036_20250628_1900/aia.lev1_euv_12s.2025-06-27T221159Z.211.image.fits.1

2026-06-30 09:08:33 - drms - INFO: Downloading file 3 of 14...

2026-06-30 09:08:33 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-06-27T23:47:59Z][211][JSOC_20260630_006071]

2026-06-30 09:08:33 - drms - INFO:     filename: aia.lev1_euv_12s.2025-06-27T234759Z.211.image.fits

2026-06-30 09:08:34 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13434_20250627_2036_20250628_1900/211/segment_01_20250627_2036_20250628_1900/aia.lev1_euv_12s.2025-06-27T234759Z.211.image.fits.1

2026-06-30 09:08:34 - drms - INFO: Downloading file 4 of 14...

2026-06-30 09:08:34 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-06-28T01:23:59Z][211][JSOC_20260630_006071]

2026-06-30 09:08:34 - drms - INFO:     filename: aia.lev1_euv_12s.2025-06-28T012359Z.211.image.fits

2026-06-30 09:08:36 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13434_20250627_2036_20250628_1900/211/segment_01_20250627_2036_20250628_1900/aia.lev1_euv_12s.2025-06-28T012359Z.211.image.fits.1

2026-06-30 09:08:36 - drms - INFO: Downloading file 5 of 14...

2026-06-30 09:08:36 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-06-28T02:59:59Z][211][JSOC_20260630_006071]

2026-06-30 09:08:36 - drms - INFO:     filename: aia.lev1_euv_12s.2025-06-28T025959Z.211.image.fits

2026-06-30 09:08:37 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13434_20250627_2036_20250628_1900/211/segment_01_20250627_2036_20250628_1900/aia.lev1_euv_12s.2025-06-28T025959Z.211.image.fits.1

2026-06-30 09:08:37 - drms - INFO: Downloading file 6 of 14...

2026-06-30 09:08:37 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-06-28T04:35:59Z][211][JSOC_20260630_006071]

2026-06-30 09:08:37 - drms - INFO:     filename: aia.lev1_euv_12s.2025-06-28T043559Z.211.image.fits

2026-06-30 09:08:38 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13434_20250627_2036_20250628_1900/211/segment_01_20250627_2036_20250628_1900/aia.lev1_euv_12s.2025-06-28T043559Z.211.image.fits.1

2026-06-30 09:08:38 - drms - INFO: Downloading file 7 of 14...

2026-06-30 09:08:38 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-06-28T06:11:59Z][211][JSOC_20260630_006071]

2026-06-30 09:08:39 - drms - INFO:     filename: aia.lev1_euv_12s.2025-06-28T061159Z.211.image.fits

2026-06-30 09:08:40 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13434_20250627_2036_20250628_1900/211/segment_01_20250627_2036_20250628_1900/aia.lev1_euv_12s.2025-06-28T061159Z.211.image.fits.1

2026-06-30 09:08:40 - drms - INFO: Downloading file 8 of 14...

2026-06-30 09:08:40 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-06-28T09:23:59Z][211][JSOC_20260630_006071]

2026-06-30 09:08:40 - drms - INFO:     filename: aia.lev1_euv_12s.2025-06-28T092359Z.211.image.fits

2026-06-30 09:08:41 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13434_20250627_2036_20250628_1900/211/segment_01_20250627_2036_20250628_1900/aia.lev1_euv_12s.2025-06-28T092359Z.211.image.fits.1

2026-06-30 09:08:41 - drms - INFO: Downloading file 9 of 14...

2026-06-30 09:08:41 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-06-28T10:59:59Z][211][JSOC_20260630_006071]

2026-06-30 09:08:41 - drms - INFO:     filename: aia.lev1_euv_12s.2025-06-28T105959Z.211.image.fits

2026-06-30 09:08:43 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13434_20250627_2036_20250628_1900/211/segment_01_20250627_2036_20250628_1900/aia.lev1_euv_12s.2025-06-28T105959Z.211.image.fits.1

2026-06-30 09:08:43 - drms - INFO: Downloading file 10 of 14...

2026-06-30 09:08:43 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-06-28T12:35:59Z][211][JSOC_20260630_006071]

2026-06-30 09:08:43 - drms - INFO:     filename: aia.lev1_euv_12s.2025-06-28T123559Z.211.image.fits

2026-06-30 09:08:44 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13434_20250627_2036_20250628_1900/211/segment_01_20250627_2036_20250628_1900/aia.lev1_euv_12s.2025-06-28T123559Z.211.image.fits.1

2026-06-30 09:08:44 - drms - INFO: Downloading file 11 of 14...

2026-06-30 09:08:44 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-06-28T14:11:59Z][211][JSOC_20260630_006071]

2026-06-30 09:08:44 - drms - INFO:     filename: aia.lev1_euv_12s.2025-06-28T141159Z.211.image.fits

2026-06-30 09:08:46 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13434_20250627_2036_20250628_1900/211/segment_01_20250627_2036_20250628_1900/aia.lev1_euv_12s.2025-06-28T141159Z.211.image.fits.1

2026-06-30 09:08:46 - drms - INFO: Downloading file 12 of 14...

2026-06-30 09:08:46 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-06-28T15:47:59Z][211][JSOC_20260630_006071]

2026-06-30 09:08:46 - drms - INFO:     filename: aia.lev1_euv_12s.2025-06-28T154759Z.211.image.fits

2026-06-30 09:08:47 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13434_20250627_2036_20250628_1900/211/segment_01_20250627_2036_20250628_1900/aia.lev1_euv_12s.2025-06-28T154759Z.211.image.fits.1

2026-06-30 09:08:47 - drms - INFO: Downloading file 13 of 14...

2026-06-30 09:08:47 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-06-28T17:23:59Z][211][JSOC_20260630_006071]

2026-06-30 09:08:47 - drms - INFO:     filename: aia.lev1_euv_12s.2025-06-28T172359Z.211.image.fits

2026-06-30 09:08:49 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13434_20250627_2036_20250628_1900/211/segment_01_20250627_2036_20250628_1900/aia.lev1_euv_12s.2025-06-28T172359Z.211.image.fits.1

2026-06-30 09:08:49 - drms - INFO: Downloading file 14 of 14...

2026-06-30 09:08:49 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-06-28T18:59:59Z][211][JSOC_20260630_006071]

2026-06-30 09:08:49 - drms - INFO:     filename: aia.lev1_euv_12s.2025-06-28T185959Z.211.image.fits

2026-06-30 09:08:50 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13434_20250627_2036_20250628_1900/211/segment_01_20250627_2036_20250628_1900/aia.lev1_euv_12s.2025-06-28T185959Z.211.image.fits.1

BLOCK ERROR: RuntimeError('Downloaded 211 Å segment does not cover all target timestamps within 180 seconds.')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13434_20250627_2036_20250628_1900,error,15,None,0,None,RuntimeError('Downloaded 211 Å segment does no...

==========================================================================================
BLOCK 188/372 | 2025_HARP13412_20250629_1136_20250629_1624 | targets=4
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13412_20250629_1136_20250629_1624,already_complete,4,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 189/372 | 2025_HARP13432_20250629_2248_20250630_1136 | targets=9
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13432_20250629_2248_20250630_1136,already_complete,9,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 190/372 | 2025_HARP13432_20250630_1936_20250701_0024 | targets=4
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13432_20250630_1936_20250701_0024,already_complete,4,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 191/372 | 2025_HARP13439_20250701_0036_20250701_0036 | targets=1
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13439_20250701_0036_20250701_0036,already_complete,1,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 192/372 | 2025_HARP13439_20250701_0348_20250701_2124 | targets=12
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13439_20250701_0348_20250701_2124,already_complete,12,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 193/372 | 2025_HARP13449_20250701_2100_20250701_2236 | targets=2
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13449_20250701_2100_20250701_2236,already_complete,2,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 194/372 | 2025_HARP13439_20250702_0036_20250702_0212 | targets=2
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13439_20250702_0036_20250702_0212,already_complete,2,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 195/372 | 2025_HARP13436_20250702_0200_20250702_1624 | targets=10
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13436_20250702_0200_20250702_1624,already_complete,10,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 196/372 | 2025_HARP13432_20250702_2000_20250703_0048 | targets=4
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13432_20250702_2000_20250703_0048,already_complete,4,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 197/372 | 2025_HARP13449_20250703_0036_20250703_0036 | targets=1
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13449_20250703_0036_20250703_0036,already_complete,1,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 198/372 | 2025_HARP13445_20250703_0400_20250703_2000 | targets=11
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13445_20250703_0400_20250703_2000,already_complete,11,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 199/372 | 2025_HARP13445_20250703_2312_20250704_2136 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13445_20250703_2312_20250704_2136,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 200/372 | 2025_HARP13436_20250704_2312_20250705_2136 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13436_20250704_2312_20250705_2136,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 201/372 | 2025_HARP13445_20250705_2312_20250706_0048 | targets=2
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13445_20250705_2312_20250706_0048,already_complete,2,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 202/372 | 2025_HARP13446_20250707_0736_20250708_0424 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13446_20250707_0736_20250708_0424,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 203/372 | 2025_HARP13483_20250710_0048_20250710_1600 | targets=10
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13483_20250710_0048_20250710_1600,already_complete,10,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 204/372 | 2025_HARP13470_20250711_0136_20250711_0624 | targets=4
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13470_20250711_0136_20250711_0624,already_complete,4,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 205/372 | 2025_HARP13470_20250711_1936_20250712_0648 | targets=8
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13470_20250711_1936_20250712_0648,already_complete,8,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 206/372 | 2025_HARP13476_20250712_1936_20250713_0536 | targets=7
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13476_20250712_1936_20250713_0536,already_complete,7,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 207/372 | 2025_HARP13470_20250713_1000_20250713_1624 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13470_20250713_1000_20250713_1624,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 208/372 | 2025_HARP13476_20250714_1936_20250715_0512 | targets=7
==========================================================================================

----------------------------------------------------------------------
2025_HARP13476_20250714_1936_20250715_0512 | wavelength 94
94 Å cadence segments: 1 [('2025-07-14 19:36:00', '2025-07-15 05:12:00', 7)]
♻️ Segment 1/1 already covered by cached 94 Å files.

----------------------------------------------------------------------
2025_HARP13476_20250714_1936_20250715_0512 | wavelength 131
131 Å cadence segments: 1 [('2025-07-14 19:36:00', '2025-07-15 05:12:00', 7)]

♻️ Segment 1/1 already covered by cached 131 Å files.

----------------------------------------------------------------------
2025_HARP13476_20250714_1936_20250715_0512 | wavelength 171
171 Å cadence segments: 1 [('2025-07-14 19:36:00', '2025-07-15 05:12:00', 7)]
♻️ Segment 1/1 already covered by cached 171 Å files.

----------------------------------------------------------------------
2025_HARP13476_20250714_1936_20250715_0512 | wavelength 193
193 Å cadence segments: 1 [('2025-07-14 19:36:00', '2025-07-15 05:12:00', 7)]
♻️ Segment 1/1 already covered by cached 193 Å files.

----------------------------------------------------------------------
2025_HARP13476_20250714_1936_20250715_0512 | wavelength 211
211 Å cadence segments: 1 [('2025-07-14 19:36:00', '2025-07-15 05:12:00', 7)]

♻️ Segment 1/1 already covered by cached 211 Å files.

----------------------------------------------------------------------
2025_HARP13476_20250714_1936_20250715_0512 | wavelength 335
335 Å cadence segments: 1 [('2025-07-14 19:36:00', '2025-07-15 05:12:00', 7)]
♻️ Segment 1/1 already covered by cached 335 Å files.

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250714_1936_HARP13476_NOAA14136 ValueError('Target crop leaves block patch: bounds=(13, 1838, 6, 1831), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250714_2112_HARP13476_NOAA14136 ValueError('Target crop leaves block patch: bounds=(7, 1835, 4, 1832), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250715_0512_HARP13476_NOAA14136 ValueError('Target crop leaves block patch: bounds=(-1, 1813, 7, 1821), shape=(1834, 1834)')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13476_20250714_1936_20250715_0512,completed,7,3,0,0.127,3 sample errors retained for retry

==========================================================================================
BLOCK 209/372 | 2025_HARP13476_20250716_1024_20250716_2136 | targets=8
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13476_20250716_1024_20250716_2136,already_complete,8,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 210/372 | 2025_HARP13501_20250717_0924_20250718_0612 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13501_20250717_0924_20250718_0612,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 211/372 | 2025_HARP13501_20250718_1012_20250719_0524 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13501_20250718_1012_20250719_0524,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 212/372 | 2025_HARP13493_20250719_1036_20250719_1212 | targets=2
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13493_20250719_1036_20250719_1212,already_complete,2,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 213/372 | 2025_HARP13532_20250719_1936_20250720_0512 | targets=7
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13532_20250719_1936_20250720_0512,already_complete,7,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 214/372 | 2025_HARP13517_20250720_1112_20250720_1248 | targets=2
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13517_20250720_1112_20250720_1248,already_complete,2,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 215/372 | 2025_HARP13506_20250721_0912_20250722_0424 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13506_20250721_0912_20250722_0424,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 216/372 | 2025_HARP13507_20250721_1936_20250722_0512 | targets=7
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13507_20250721_1936_20250722_0512,already_complete,7,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 217/372 | 2025_HARP13522_20250722_2136_20250723_0536 | targets=6
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13522_20250722_2136_20250723_0536,already_complete,6,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 218/372 | 2025_HARP13517_20250723_2148_20250724_0100 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13517_20250723_2148_20250724_0100,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 219/372 | 2025_HARP13524_20250724_1036_20250725_0112 | targets=10
==========================================================================================

----------------------------------------------------------------------
2025_HARP13524_20250724_1036_20250725_0112 | wavelength 94
94 Å cadence segments: 2 [('2025-07-24 10:36:00', '2025-07-24 20:12:00', 7), ('2025-07-24 22:00:00', '2025-07-25 01:12:00', 3)]
♻️ Segment 1/2 already covered by cached 94 Å files.

♻️ Segment 2/2 already covered by cached 94 Å files.

----------------------------------------------------------------------
2025_HARP13524_20250724_1036_20250725_0112 | wavelength 131
131 Å cadence segments: 2 [('2025-07-24 10:36:00', '2025-07-24 20:12:00', 7), ('2025-07-24 22:00:00', '2025-07-25 01:12:00', 3)]
♻️ Segment 1/2 already covered by cached 131 Å files.

♻️ Segment 2/2 already covered by cached 131 Å files.

----------------------------------------------------------------------
2025_HARP13524_20250724_1036_20250725_0112 | wavelength 171
171 Å cadence segments: 2 [('2025-07-24 10:36:00', '2025-07-24 20:12:00', 7), ('2025-07-24 22:00:00', '2025-07-25 01:12:00', 3)]

♻️ Segment 1/2 already covered by cached 171 Å files.
♻️ Segment 2/2 already covered by cached 171 Å files.

----------------------------------------------------------------------
2025_HARP13524_20250724_1036_20250725_0112 | wavelength 193
193 Å cadence segments: 2 [('2025-07-24 10:36:00', '2025-07-24 20:12:00', 7), ('2025-07-24 22:00:00', '2025-07-25 01:12:00', 3)]
♻️ Segment 1/2 already covered by cached 193 Å files.
♻️ Segment 2/2 already covered by cached 193 Å files.

----------------------------------------------------------------------
2025_HARP13524_20250724_1036_20250725_0112 | wavelength 211
211 Å cadence segments: 2 [('2025-07-24 10:36:00', '2025-07-24 20:12:00', 7), ('2025-07-24 22:00:00', '2025-07-25 01:12:00', 3)]
♻️ Segment 1/2 already covered by cached 211 Å files.
♻️ Segment 2/2 already covered by cached 211 Å files.

----------------------------------------------------------------------
2025_HARP13524_20250724_1036_20250725_0112 | wavelength 335
335 Å cadence segments: 2 [('2025-07-24 10:36:00', '2025-07-24 20:12:00', 7), ('2025-07-24 22:00:00', '2025-07-25 01:12:00', 3)]
♻️ Segment 1/2 already covered by cached 335 Å files.

♻️ Segment 2/2 already covered by cached 335 Å files.

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250724_1700_HARP13524_NOAA14149 ValueError('Target crop leaves block patch: bounds=(7, 1819, -9, 1803), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250724_1836_HARP13524_NOAA14149 ValueError('Target crop leaves block patch: bounds=(4, 1819, -10, 1805), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250724_2012_HARP13524_NOAA14149 ValueError('Target crop leaves block patch: bounds=(0, 1819, -11, 1807), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250725_0112_HARP13524_NOAA14149 ValueError('Target crop leaves block patch: bounds=(-4, 1842, -5, 1841), shape=(1834, 1834)')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13524_20250724_1036_20250725_0112,completed,10,4,0,0.23,4 sample errors retained for retry

==========================================================================================
BLOCK 220/372 | 2025_HARP13542_20250725_0548_20250725_0548 | targets=1
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13542_20250725_0548_20250725_0548,already_complete,1,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 221/372 | 2025_HARP13542_20250725_1000_20250725_1624 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13542_20250725_1000_20250725_1624,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 222/372 | 2025_HARP13561_20250726_1000_20250726_1624 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13561_20250726_1000_20250726_1624,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 223/372 | 2025_HARP13543_20250726_1748_20250727_0500 | targets=8
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13543_20250726_1748_20250727_0500,already_complete,8,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 224/372 | 2025_HARP13543_20250727_0912_20250728_0424 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13543_20250727_0912_20250728_0424,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 225/372 | 2025_HARP13568_20250727_1212_20250728_0548 | targets=12
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13568_20250727_1212_20250728_0548,already_complete,12,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 226/372 | 2025_HARP13548_20250728_0924_20250728_1236 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13548_20250728_0924_20250728_1236,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 227/372 | 2025_HARP13561_20250728_1024_20250728_1200 | targets=2
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13561_20250728_1024_20250728_1200,already_complete,2,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 228/372 | 2025_HARP13548_20250728_1548_20250729_0536 | targets=9
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13548_20250728_1548_20250729_0536,already_complete,9,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 229/372 | 2025_HARP13543_20250728_1636_20250728_1948 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13543_20250728_1636_20250728_1948,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 230/372 | 2025_HARP13568_20250729_0612_20250729_0612 | targets=1
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13568_20250729_0612_20250729_0612,already_complete,1,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 231/372 | 2025_HARP13542_20250729_1136_20250729_1624 | targets=4
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13542_20250729_1136_20250729_1624,already_complete,4,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 232/372 | 2025_HARP13576_20250730_0236_20250730_0236 | targets=1
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13576_20250730_0236_20250730_0236,already_complete,1,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 233/372 | 2025_HARP13552_20250730_0912_20250731_0500 | targets=13
==========================================================================================

----------------------------------------------------------------------
2025_HARP13552_20250730_0912_20250731_0500 | wavelength 94
94 Å cadence segments: 2 [('2025-07-30 09:12:00', '2025-07-30 14:00:00', 4), ('2025-07-30 16:12:00', '2025-07-31 05:00:00', 9)]
♻️ Segment 1/2 already covered by cached 94 Å files.

♻️ Segment 2/2 already covered by cached 94 Å files.

----------------------------------------------------------------------
2025_HARP13552_20250730_0912_20250731_0500 | wavelength 131
131 Å cadence segments: 2 [('2025-07-30 09:12:00', '2025-07-30 14:00:00', 4), ('2025-07-30 16:12:00', '2025-07-31 05:00:00', 9)]
♻️ Segment 1/2 already covered by cached 131 Å files.

Segment query: aia.lev1_euv_12s[2025-07-30T16:12:00.000/864m@96m][131]{image}
Segment reference: 2025-07-30 22:36:00 | targets: 9 | patch arcsec: 368.91213063917326
JSOC export attempt 1/10

2026-06-30 09:10:50 - drms - INFO: Export request pending. [id=JSOC_20260630_006110, status=2]

2026-06-30 09:10:50 - drms - INFO: Waiting for 15 seconds...

2026-06-30 09:11:06 - drms - INFO: Export request pending. [id=JSOC_20260630_006110, status=1]

2026-06-30 09:11:06 - drms - INFO: Waiting for 15 seconds...

2026-06-30 09:11:21 - drms - INFO: Export request pending. [id=JSOC_20260630_006110, status=1]

2026-06-30 09:11:21 - drms - INFO: Waiting for 15 seconds...

2026-06-30 09:11:37 - drms - INFO: Export request pending. [id=JSOC_20260630_006110, status=1]

2026-06-30 09:11:37 - drms - INFO: Waiting for 15 seconds...

2026-06-30 09:11:52 - drms - INFO: Export request finished. [id=JSOC_20260630_006110, status=0]

2026-06-30 09:11:52 - drms - INFO: Downloading file 1 of 8...

2026-06-30 09:11:52 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-07-30T17:47:59Z][131][JSOC_20260630_006110]

2026-06-30 09:11:52 - drms - INFO:     filename: aia.lev1_euv_12s.2025-07-30T174759Z.131.image.fits

2026-06-30 09:11:54 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13552_20250730_0912_20250731_0500/131/segment_02_20250730_1612_20250731_0500/aia.lev1_euv_12s.2025-07-30T174759Z.131.image.fits.1

2026-06-30 09:11:54 - drms - INFO: Downloading file 2 of 8...

2026-06-30 09:11:54 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-07-30T19:23:59Z][131][JSOC_20260630_006110]

2026-06-30 09:11:54 - drms - INFO:     filename: aia.lev1_euv_12s.2025-07-30T192359Z.131.image.fits

2026-06-30 09:11:55 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13552_20250730_0912_20250731_0500/131/segment_02_20250730_1612_20250731_0500/aia.lev1_euv_12s.2025-07-30T192359Z.131.image.fits.1

2026-06-30 09:11:55 - drms - INFO: Downloading file 3 of 8...

2026-06-30 09:11:55 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-07-30T20:59:59Z][131][JSOC_20260630_006110]

2026-06-30 09:11:55 - drms - INFO:     filename: aia.lev1_euv_12s.2025-07-30T205959Z.131.image.fits

2026-06-30 09:11:57 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13552_20250730_0912_20250731_0500/131/segment_02_20250730_1612_20250731_0500/aia.lev1_euv_12s.2025-07-30T205959Z.131.image.fits.1

2026-06-30 09:11:57 - drms - INFO: Downloading file 4 of 8...

2026-06-30 09:11:57 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-07-30T22:35:59Z][131][JSOC_20260630_006110]

2026-06-30 09:11:57 - drms - INFO:     filename: aia.lev1_euv_12s.2025-07-30T223559Z.131.image.fits

2026-06-30 09:11:58 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13552_20250730_0912_20250731_0500/131/segment_02_20250730_1612_20250731_0500/aia.lev1_euv_12s.2025-07-30T223559Z.131.image.fits.1

2026-06-30 09:11:58 - drms - INFO: Downloading file 5 of 8...

2026-06-30 09:11:58 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-07-31T00:11:59Z][131][JSOC_20260630_006110]

2026-06-30 09:11:58 - drms - INFO:     filename: aia.lev1_euv_12s.2025-07-31T001159Z.131.image.fits

2026-06-30 09:11:59 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13552_20250730_0912_20250731_0500/131/segment_02_20250730_1612_20250731_0500/aia.lev1_euv_12s.2025-07-31T001159Z.131.image.fits.1

2026-06-30 09:11:59 - drms - INFO: Downloading file 6 of 8...

2026-06-30 09:11:59 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-07-31T01:47:59Z][131][JSOC_20260630_006110]

2026-06-30 09:11:59 - drms - INFO:     filename: aia.lev1_euv_12s.2025-07-31T014759Z.131.image.fits

2026-06-30 09:12:01 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13552_20250730_0912_20250731_0500/131/segment_02_20250730_1612_20250731_0500/aia.lev1_euv_12s.2025-07-31T014759Z.131.image.fits.1

2026-06-30 09:12:01 - drms - INFO: Downloading file 7 of 8...

2026-06-30 09:12:01 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-07-31T03:23:59Z][131][JSOC_20260630_006110]

2026-06-30 09:12:01 - drms - INFO:     filename: aia.lev1_euv_12s.2025-07-31T032359Z.131.image.fits

2026-06-30 09:12:02 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13552_20250730_0912_20250731_0500/131/segment_02_20250730_1612_20250731_0500/aia.lev1_euv_12s.2025-07-31T032359Z.131.image.fits.1

2026-06-30 09:12:02 - drms - INFO: Downloading file 8 of 8...

2026-06-30 09:12:02 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-07-31T04:59:59Z][131][JSOC_20260630_006110]

2026-06-30 09:12:02 - drms - INFO:     filename: aia.lev1_euv_12s.2025-07-31T045959Z.131.image.fits

2026-06-30 09:12:04 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13552_20250730_0912_20250731_0500/131/segment_02_20250730_1612_20250731_0500/aia.lev1_euv_12s.2025-07-31T045959Z.131.image.fits.1

BLOCK ERROR: RuntimeError('Downloaded 131 Å segment does not cover all target timestamps within 180 seconds.')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13552_20250730_0912_20250731_0500,error,13,None,0,None,RuntimeError('Downloaded 131 Å segment does no...

==========================================================================================
BLOCK 234/372 | 2025_HARP13543_20250730_1700_20250730_2324 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13543_20250730_1700_20250730_2324,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 235/372 | 2025_HARP13548_20250731_1036_20250731_2324 | targets=9
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13548_20250731_1036_20250731_2324,already_complete,9,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 236/372 | 2025_HARP13567_20250801_0924_20250802_0612 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13567_20250801_0924_20250802_0612,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 237/372 | 2025_HARP13567_20250802_1936_20250803_0512 | targets=7
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13567_20250802_1936_20250803_0512,already_complete,7,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 238/372 | 2025_HARP13567_20250804_0936_20250804_1248 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13567_20250804_0936_20250804_1248,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 239/372 | 2025_HARP13567_20250805_1000_20250805_1000 | targets=1
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13567_20250805_1000_20250805_1000,already_complete,1,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 240/372 | 2025_HARP13610_20250806_1200_20250807_1112 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13610_20250806_1200_20250807_1112,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 241/372 | 2025_HARP13599_20250807_2200_20250808_0424 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13599_20250807_2200_20250808_0424,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 242/372 | 2025_HARP13599_20250808_1712_20250809_0424 | targets=8
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13599_20250808_1712_20250809_0424,already_complete,8,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 243/372 | 2025_HARP13606_20250809_1612_20250810_0148 | targets=7
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13606_20250809_1612_20250810_0148,already_complete,7,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 244/372 | 2025_HARP13597_20250810_1936_20250811_1624 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13597_20250810_1936_20250811_1624,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 245/372 | 2025_HARP13612_20250811_1936_20250812_1624 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13612_20250811_1936_20250812_1624,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 246/372 | 2025_HARP13597_20250812_1936_20250813_1624 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13597_20250812_1936_20250813_1624,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 247/372 | 2025_HARP13612_20250813_2000_20250814_1824 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13612_20250813_2000_20250814_1824,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 248/372 | 2025_HARP13624_20250814_1900_20250815_1724 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13624_20250814_1900_20250815_1724,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 249/372 | 2025_HARP13624_20250815_1900_20250816_1724 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13624_20250815_1900_20250816_1724,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 250/372 | 2025_HARP13627_20250817_0236_20250818_0100 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13627_20250817_0236_20250818_0100,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 251/372 | 2025_HARP13624_20250818_1912_20250818_2048 | targets=2
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13624_20250818_1912_20250818_2048,already_complete,2,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 252/372 | 2025_HARP13652_20250819_0536_20250820_0400 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13652_20250819_0536_20250820_0400,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 253/372 | 2025_HARP13652_20250820_0536_20250821_0412 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13652_20250820_0536_20250821_0412,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 254/372 | 2025_HARP13652_20250821_0548_20250822_0412 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13652_20250821_0548_20250822_0412,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 255/372 | 2025_HARP13676_20250822_0512_20250822_1624 | targets=8
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13676_20250822_0512_20250822_1624,already_complete,8,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 256/372 | 2025_HARP13676_20250822_1936_20250823_1624 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13676_20250822_1936_20250823_1624,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 257/372 | 2025_HARP13652_20250823_0548_20250823_1836 | targets=9
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13652_20250823_0548_20250823_1836,already_complete,9,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 258/372 | 2025_HARP13676_20250823_1936_20250824_1624 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13676_20250823_1936_20250824_1624,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 259/372 | 2025_HARP13694_20250824_1924_20250825_1748 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13694_20250824_1924_20250825_1748,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 260/372 | 2025_HARP13673_20250825_0812_20250825_1624 | targets=6
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13673_20250825_0812_20250825_1624,already_complete,6,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 261/372 | 2025_HARP13673_20250825_1936_20250826_1624 | targets=14
==========================================================================================

----------------------------------------------------------------------
2025_HARP13673_20250825_1936_20250826_1624 | wavelength 94
94 Å cadence segments: 1 [('2025-08-25 19:36:00', '2025-08-26 16:24:00', 14)]
♻️ Segment 1/1 already covered by cached 94 Å files.

----------------------------------------------------------------------
2025_HARP13673_20250825_1936_20250826_1624 | wavelength 131
131 Å cadence segments: 1 [('2025-08-25 19:36:00', '2025-08-26 16:24:00', 14)]
♻️ Segment 1/1 already covered by cached 131 Å files.

----------------------------------------------------------------------
2025_HARP13673_20250825_1936_20250826_1624 | wavelength 171
171 Å cadence segments: 1 [('2025-08-25 19:36:00', '2025-08-26 16:24:00', 14)]
♻️ Segment 1/1 already covered by cached 171 Å files.

----------------------------------------------------------------------
2025_HARP13673_20250825_1936_20250826_1624 | wavelength 193
193 Å cadence segments: 1 [('2025-08-25 19:36:00', '2025-08-26 16:24:00', 14)]
♻️ Segment 1/1 already covered by cached 193 Å files.

----------------------------------------------------------------------
2025_HARP13673_20250825_1936_20250826_1624 | wavelength 211
211 Å cadence segments: 1 [('2025-08-25 19:36:00', '2025-08-26 16:24:00', 14)]
Segment query: aia.lev1_euv_12s[2025-08-25T19:36:00.000/1344m@96m][211]{image}
Segment reference: 2025-08-26 06:00:00 | targets: 14 | patch arcsec: 317.12430893997123
JSOC export attempt 1/10

2026-06-30 09:13:01 - drms - INFO: Export request pending. [id=JSOC_20260630_006135, status=2]

2026-06-30 09:13:01 - drms - INFO: Waiting for 15 seconds...

2026-06-30 09:13:17 - drms - INFO: Export request pending. [id=JSOC_20260630_006135, status=1]

2026-06-30 09:13:17 - drms - INFO: Waiting for 15 seconds...

2026-06-30 09:13:32 - drms - INFO: Export request pending. [id=JSOC_20260630_006135, status=1]

2026-06-30 09:13:32 - drms - INFO: Waiting for 15 seconds...

2026-06-30 09:13:48 - drms - INFO: Export request pending. [id=JSOC_20260630_006135, status=1]

2026-06-30 09:13:48 - drms - INFO: Waiting for 15 seconds...

2026-06-30 09:14:03 - drms - INFO: Export request finished. [id=JSOC_20260630_006135, status=0]

2026-06-30 09:14:03 - drms - INFO: Downloading file 1 of 14...

2026-06-30 09:14:03 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-08-25T19:35:59Z][211][JSOC_20260630_006135]

2026-06-30 09:14:03 - drms - INFO:     filename: aia.lev1_euv_12s.2025-08-25T193559Z.211.image.fits

2026-06-30 09:14:05 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13673_20250825_1936_20250826_1624/211/segment_01_20250825_1936_20250826_1624/aia.lev1_euv_12s.2025-08-25T193559Z.211.image.fits

2026-06-30 09:14:05 - drms - INFO: Downloading file 2 of 14...

2026-06-30 09:14:05 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-08-25T21:11:59Z][211][JSOC_20260630_006135]

2026-06-30 09:14:05 - drms - INFO:     filename: aia.lev1_euv_12s.2025-08-25T211159Z.211.image.fits

2026-06-30 09:14:06 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13673_20250825_1936_20250826_1624/211/segment_01_20250825_1936_20250826_1624/aia.lev1_euv_12s.2025-08-25T211159Z.211.image.fits

2026-06-30 09:14:06 - drms - INFO: Downloading file 3 of 14...

2026-06-30 09:14:06 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-08-25T22:47:59Z][211][JSOC_20260630_006135]

2026-06-30 09:14:06 - drms - INFO:     filename: aia.lev1_euv_12s.2025-08-25T224759Z.211.image.fits

2026-06-30 09:14:07 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13673_20250825_1936_20250826_1624/211/segment_01_20250825_1936_20250826_1624/aia.lev1_euv_12s.2025-08-25T224759Z.211.image.fits

2026-06-30 09:14:07 - drms - INFO: Downloading file 4 of 14...

2026-06-30 09:14:07 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-08-26T00:23:59Z][211][JSOC_20260630_006135]

2026-06-30 09:14:07 - drms - INFO:     filename: aia.lev1_euv_12s.2025-08-26T002359Z.211.image.fits

2026-06-30 09:14:09 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13673_20250825_1936_20250826_1624/211/segment_01_20250825_1936_20250826_1624/aia.lev1_euv_12s.2025-08-26T002359Z.211.image.fits

2026-06-30 09:14:09 - drms - INFO: Downloading file 5 of 14...

2026-06-30 09:14:09 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-08-26T01:59:59Z][211][JSOC_20260630_006135]

2026-06-30 09:14:09 - drms - INFO:     filename: aia.lev1_euv_12s.2025-08-26T015959Z.211.image.fits

2026-06-30 09:14:10 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13673_20250825_1936_20250826_1624/211/segment_01_20250825_1936_20250826_1624/aia.lev1_euv_12s.2025-08-26T015959Z.211.image.fits

2026-06-30 09:14:10 - drms - INFO: Downloading file 6 of 14...

2026-06-30 09:14:10 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-08-26T03:35:59Z][211][JSOC_20260630_006135]

2026-06-30 09:14:10 - drms - INFO:     filename: aia.lev1_euv_12s.2025-08-26T033559Z.211.image.fits

2026-06-30 09:14:11 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13673_20250825_1936_20250826_1624/211/segment_01_20250825_1936_20250826_1624/aia.lev1_euv_12s.2025-08-26T033559Z.211.image.fits

2026-06-30 09:14:11 - drms - INFO: Downloading file 7 of 14...

2026-06-30 09:14:11 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-08-26T05:11:59Z][211][JSOC_20260630_006135]

2026-06-30 09:14:11 - drms - INFO:     filename: aia.lev1_euv_12s.2025-08-26T051159Z.211.image.fits

2026-06-30 09:14:13 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13673_20250825_1936_20250826_1624/211/segment_01_20250825_1936_20250826_1624/aia.lev1_euv_12s.2025-08-26T051159Z.211.image.fits

2026-06-30 09:14:13 - drms - INFO: Downloading file 8 of 14...

2026-06-30 09:14:13 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-08-26T06:47:59Z][211][JSOC_20260630_006135]

2026-06-30 09:14:13 - drms - INFO:     filename: aia.lev1_euv_12s.2025-08-26T064759Z.211.image.fits

2026-06-30 09:14:14 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13673_20250825_1936_20250826_1624/211/segment_01_20250825_1936_20250826_1624/aia.lev1_euv_12s.2025-08-26T064759Z.211.image.fits

2026-06-30 09:14:14 - drms - INFO: Downloading file 9 of 14...

2026-06-30 09:14:14 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-08-26T08:23:59Z][211][JSOC_20260630_006135]

2026-06-30 09:14:14 - drms - INFO:     filename: aia.lev1_euv_12s.2025-08-26T082359Z.211.image.fits

2026-06-30 09:14:15 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13673_20250825_1936_20250826_1624/211/segment_01_20250825_1936_20250826_1624/aia.lev1_euv_12s.2025-08-26T082359Z.211.image.fits

2026-06-30 09:14:15 - drms - INFO: Downloading file 10 of 14...

2026-06-30 09:14:15 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-08-26T09:59:59Z][211][JSOC_20260630_006135]

2026-06-30 09:14:15 - drms - INFO:     filename: aia.lev1_euv_12s.2025-08-26T095959Z.211.image.fits

2026-06-30 09:14:17 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13673_20250825_1936_20250826_1624/211/segment_01_20250825_1936_20250826_1624/aia.lev1_euv_12s.2025-08-26T095959Z.211.image.fits

2026-06-30 09:14:17 - drms - INFO: Downloading file 11 of 14...

2026-06-30 09:14:17 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-08-26T11:35:59Z][211][JSOC_20260630_006135]

2026-06-30 09:14:17 - drms - INFO:     filename: aia.lev1_euv_12s.2025-08-26T113559Z.211.image.fits

2026-06-30 09:14:18 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13673_20250825_1936_20250826_1624/211/segment_01_20250825_1936_20250826_1624/aia.lev1_euv_12s.2025-08-26T113559Z.211.image.fits

2026-06-30 09:14:18 - drms - INFO: Downloading file 12 of 14...

2026-06-30 09:14:18 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-08-26T13:11:59Z][211][JSOC_20260630_006135]

2026-06-30 09:14:18 - drms - INFO:     filename: aia.lev1_euv_12s.2025-08-26T131159Z.211.image.fits

2026-06-30 09:14:19 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13673_20250825_1936_20250826_1624/211/segment_01_20250825_1936_20250826_1624/aia.lev1_euv_12s.2025-08-26T131159Z.211.image.fits

2026-06-30 09:14:19 - drms - INFO: Downloading file 13 of 14...

2026-06-30 09:14:19 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-08-26T14:47:59Z][211][JSOC_20260630_006135]

2026-06-30 09:14:19 - drms - INFO:     filename: aia.lev1_euv_12s.2025-08-26T144759Z.211.image.fits

2026-06-30 09:14:21 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13673_20250825_1936_20250826_1624/211/segment_01_20250825_1936_20250826_1624/aia.lev1_euv_12s.2025-08-26T144759Z.211.image.fits

2026-06-30 09:14:21 - drms - INFO: Downloading file 14 of 14...

2026-06-30 09:14:21 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-08-26T16:23:59Z][211][JSOC_20260630_006135]

2026-06-30 09:14:21 - drms - INFO:     filename: aia.lev1_euv_12s.2025-08-26T162359Z.211.image.fits

2026-06-30 09:14:22 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13673_20250825_1936_20250826_1624/211/segment_01_20250825_1936_20250826_1624/aia.lev1_euv_12s.2025-08-26T162359Z.211.image.fits

----------------------------------------------------------------------
2025_HARP13673_20250825_1936_20250826_1624 | wavelength 335
335 Å cadence segments: 1 [('2025-08-25 19:36:00', '2025-08-26 16:24:00', 14)]
Segment query: aia.lev1_euv_12s[2025-08-25T19:36:00.000/1344m@96m][335]{image}
Segment reference: 2025-08-26 06:00:00 | targets: 14 | patch arcsec: 317.12430893997123
JSOC export attempt 1/10

2026-06-30 09:14:37 - drms - INFO: Export request pending. [id=JSOC_20260630_006157, status=2]

2026-06-30 09:14:37 - drms - INFO: Waiting for 15 seconds...

2026-06-30 09:14:53 - drms - INFO: Export request pending. [id=JSOC_20260630_006157, status=1]

2026-06-30 09:14:53 - drms - INFO: Waiting for 15 seconds...

2026-06-30 09:15:08 - drms - INFO: Export request pending. [id=JSOC_20260630_006157, status=1]

2026-06-30 09:15:08 - drms - INFO: Waiting for 15 seconds...

2026-06-30 09:15:24 - drms - INFO: Export request pending. [id=JSOC_20260630_006157, status=1]

2026-06-30 09:15:24 - drms - INFO: Waiting for 15 seconds...

2026-06-30 09:15:39 - drms - INFO: Export request pending. [id=JSOC_20260630_006157, status=1]

2026-06-30 09:15:39 - drms - INFO: Waiting for 15 seconds...

2026-06-30 09:15:55 - drms - INFO: Export request finished. [id=JSOC_20260630_006157, status=0]

2026-06-30 09:15:55 - drms - INFO: Downloading file 1 of 14...

2026-06-30 09:15:55 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-08-25T19:35:59Z][335][JSOC_20260630_006157]

2026-06-30 09:15:55 - drms - INFO:     filename: aia.lev1_euv_12s.2025-08-25T193559Z.335.image.fits

2026-06-30 09:15:56 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13673_20250825_1936_20250826_1624/335/segment_01_20250825_1936_20250826_1624/aia.lev1_euv_12s.2025-08-25T193559Z.335.image.fits

2026-06-30 09:15:56 - drms - INFO: Downloading file 2 of 14...

2026-06-30 09:15:56 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-08-25T21:11:59Z][335][JSOC_20260630_006157]

2026-06-30 09:15:56 - drms - INFO:     filename: aia.lev1_euv_12s.2025-08-25T211159Z.335.image.fits

2026-06-30 09:15:57 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13673_20250825_1936_20250826_1624/335/segment_01_20250825_1936_20250826_1624/aia.lev1_euv_12s.2025-08-25T211159Z.335.image.fits

2026-06-30 09:15:57 - drms - INFO: Downloading file 3 of 14...

2026-06-30 09:15:57 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-08-25T22:47:59Z][335][JSOC_20260630_006157]

2026-06-30 09:15:57 - drms - INFO:     filename: aia.lev1_euv_12s.2025-08-25T224759Z.335.image.fits

2026-06-30 09:15:58 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13673_20250825_1936_20250826_1624/335/segment_01_20250825_1936_20250826_1624/aia.lev1_euv_12s.2025-08-25T224759Z.335.image.fits

2026-06-30 09:15:58 - drms - INFO: Downloading file 4 of 14...

2026-06-30 09:15:58 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-08-26T00:23:59Z][335][JSOC_20260630_006157]

2026-06-30 09:15:58 - drms - INFO:     filename: aia.lev1_euv_12s.2025-08-26T002359Z.335.image.fits

2026-06-30 09:15:59 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13673_20250825_1936_20250826_1624/335/segment_01_20250825_1936_20250826_1624/aia.lev1_euv_12s.2025-08-26T002359Z.335.image.fits

2026-06-30 09:15:59 - drms - INFO: Downloading file 5 of 14...

2026-06-30 09:15:59 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-08-26T01:59:59Z][335][JSOC_20260630_006157]

2026-06-30 09:15:59 - drms - INFO:     filename: aia.lev1_euv_12s.2025-08-26T015959Z.335.image.fits

2026-06-30 09:16:00 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13673_20250825_1936_20250826_1624/335/segment_01_20250825_1936_20250826_1624/aia.lev1_euv_12s.2025-08-26T015959Z.335.image.fits

2026-06-30 09:16:00 - drms - INFO: Downloading file 6 of 14...

2026-06-30 09:16:00 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-08-26T03:35:59Z][335][JSOC_20260630_006157]

2026-06-30 09:16:00 - drms - INFO:     filename: aia.lev1_euv_12s.2025-08-26T033559Z.335.image.fits

2026-06-30 09:16:02 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13673_20250825_1936_20250826_1624/335/segment_01_20250825_1936_20250826_1624/aia.lev1_euv_12s.2025-08-26T033559Z.335.image.fits

2026-06-30 09:16:02 - drms - INFO: Downloading file 7 of 14...

2026-06-30 09:16:02 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-08-26T05:11:59Z][335][JSOC_20260630_006157]

2026-06-30 09:16:02 - drms - INFO:     filename: aia.lev1_euv_12s.2025-08-26T051159Z.335.image.fits

2026-06-30 09:16:03 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13673_20250825_1936_20250826_1624/335/segment_01_20250825_1936_20250826_1624/aia.lev1_euv_12s.2025-08-26T051159Z.335.image.fits

2026-06-30 09:16:03 - drms - INFO: Downloading file 8 of 14...

2026-06-30 09:16:03 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-08-26T06:47:59Z][335][JSOC_20260630_006157]

2026-06-30 09:16:03 - drms - INFO:     filename: aia.lev1_euv_12s.2025-08-26T064759Z.335.image.fits

2026-06-30 09:16:04 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13673_20250825_1936_20250826_1624/335/segment_01_20250825_1936_20250826_1624/aia.lev1_euv_12s.2025-08-26T064759Z.335.image.fits

2026-06-30 09:16:04 - drms - INFO: Downloading file 9 of 14...

2026-06-30 09:16:04 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-08-26T08:23:59Z][335][JSOC_20260630_006157]

2026-06-30 09:16:04 - drms - INFO:     filename: aia.lev1_euv_12s.2025-08-26T082359Z.335.image.fits

2026-06-30 09:16:05 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13673_20250825_1936_20250826_1624/335/segment_01_20250825_1936_20250826_1624/aia.lev1_euv_12s.2025-08-26T082359Z.335.image.fits

2026-06-30 09:16:05 - drms - INFO: Downloading file 10 of 14...

2026-06-30 09:16:05 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-08-26T09:59:59Z][335][JSOC_20260630_006157]

2026-06-30 09:16:05 - drms - INFO:     filename: aia.lev1_euv_12s.2025-08-26T095959Z.335.image.fits

2026-06-30 09:16:07 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13673_20250825_1936_20250826_1624/335/segment_01_20250825_1936_20250826_1624/aia.lev1_euv_12s.2025-08-26T095959Z.335.image.fits

2026-06-30 09:16:07 - drms - INFO: Downloading file 11 of 14...

2026-06-30 09:16:07 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-08-26T11:35:59Z][335][JSOC_20260630_006157]

2026-06-30 09:16:07 - drms - INFO:     filename: aia.lev1_euv_12s.2025-08-26T113559Z.335.image.fits

2026-06-30 09:16:08 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13673_20250825_1936_20250826_1624/335/segment_01_20250825_1936_20250826_1624/aia.lev1_euv_12s.2025-08-26T113559Z.335.image.fits

2026-06-30 09:16:08 - drms - INFO: Downloading file 12 of 14...

2026-06-30 09:16:08 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-08-26T13:11:59Z][335][JSOC_20260630_006157]

2026-06-30 09:16:08 - drms - INFO:     filename: aia.lev1_euv_12s.2025-08-26T131159Z.335.image.fits

2026-06-30 09:16:09 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13673_20250825_1936_20250826_1624/335/segment_01_20250825_1936_20250826_1624/aia.lev1_euv_12s.2025-08-26T131159Z.335.image.fits

2026-06-30 09:16:09 - drms - INFO: Downloading file 13 of 14...

2026-06-30 09:16:09 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-08-26T14:47:59Z][335][JSOC_20260630_006157]

2026-06-30 09:16:09 - drms - INFO:     filename: aia.lev1_euv_12s.2025-08-26T144759Z.335.image.fits

2026-06-30 09:16:10 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13673_20250825_1936_20250826_1624/335/segment_01_20250825_1936_20250826_1624/aia.lev1_euv_12s.2025-08-26T144759Z.335.image.fits

2026-06-30 09:16:10 - drms - INFO: Downloading file 14 of 14...

2026-06-30 09:16:10 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-08-26T16:23:59Z][335][JSOC_20260630_006157]

2026-06-30 09:16:10 - drms - INFO:     filename: aia.lev1_euv_12s.2025-08-26T162359Z.335.image.fits

2026-06-30 09:16:11 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13673_20250825_1936_20250826_1624/335/segment_01_20250825_1936_20250826_1624/aia.lev1_euv_12s.2025-08-26T162359Z.335.image.fits

/tmp/ipykernel_2312897/1546682576.py:174: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

✅ 20250825_1936_HARP13673_NOAA14190

/tmp/ipykernel_2312897/1546682576.py:174: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

✅ 20250825_2112_HARP13673_NOAA14190

/tmp/ipykernel_2312897/1546682576.py:174: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

✅ 20250825_2248_HARP13673_NOAA14190

/tmp/ipykernel_2312897/1546682576.py:174: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

✅ 20250826_0024_HARP13673_NOAA14190

/tmp/ipykernel_2312897/1546682576.py:174: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

✅ 20250826_0200_HARP13673_NOAA14190

/tmp/ipykernel_2312897/1546682576.py:174: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

✅ 20250826_0336_HARP13673_NOAA14190

/tmp/ipykernel_2312897/1546682576.py:174: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

✅ 20250826_0512_HARP13673_NOAA14190

/tmp/ipykernel_2312897/1546682576.py:174: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

✅ 20250826_0648_HARP13673_NOAA14190

/tmp/ipykernel_2312897/1546682576.py:174: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

✅ 20250826_0824_HARP13673_NOAA14190

/tmp/ipykernel_2312897/1546682576.py:174: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

✅ 20250826_1000_HARP13673_NOAA14190

/tmp/ipykernel_2312897/1546682576.py:174: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

✅ 20250826_1136_HARP13673_NOAA14190

/tmp/ipykernel_2312897/1546682576.py:174: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

✅ 20250826_1312_HARP13673_NOAA14190

/tmp/ipykernel_2312897/1546682576.py:174: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

✅ 20250826_1448_HARP13673_NOAA14190

/tmp/ipykernel_2312897/1546682576.py:174: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

✅ 20250826_1624_HARP13673_NOAA14190

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13673_20250825_1936_20250826_1624,completed,14,14,14,4.962,success

==========================================================================================
BLOCK 262/372 | 2025_HARP13694_20250826_1924_20250827_1748 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13694_20250826_1924_20250827_1748,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 263/372 | 2025_HARP13694_20250827_1948_20250828_0524 | targets=7
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13694_20250827_1948_20250828_0524,already_complete,7,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 264/372 | 2025_HARP13691_20250829_0300_20250829_0612 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13691_20250829_0300_20250829_0612,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 265/372 | 2025_HARP13708_20250829_1936_20250830_1624 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13708_20250829_1936_20250830_1624,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 266/372 | 2025_HARP13708_20250831_1848_20250901_0424 | targets=7
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13708_20250831_1848_20250901_0424,already_complete,7,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 267/372 | 2025_HARP13723_20250902_0100_20250902_2324 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13723_20250902_0100_20250902_2324,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 268/372 | 2025_HARP13723_20250903_0100_20250903_2336 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13723_20250903_0100_20250903_2336,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 269/372 | 2025_HARP13730_20250904_0424_20250904_0424 | targets=1
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13730_20250904_0424_20250904_0424,already_complete,1,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 270/372 | 2025_HARP13722_20250904_2324_20250905_2148 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13722_20250904_2324_20250905_2148,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 271/372 | 2025_HARP13722_20250905_2324_20250906_1036 | targets=8
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13722_20250905_2324_20250906_1036,already_complete,8,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 272/372 | 2025_HARP13747_20250906_1336_20250907_1236 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13747_20250906_1336_20250907_1236,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 273/372 | 2025_HARP13747_20250907_1412_20250908_1236 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13747_20250907_1412_20250908_1236,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 274/372 | 2025_HARP13747_20250908_1412_20250909_1236 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13747_20250908_1412_20250909_1236,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 275/372 | 2025_HARP13736_20250910_1300_20250911_0200 | targets=9
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13736_20250910_1300_20250911_0200,already_complete,9,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 276/372 | 2025_HARP13768_20250915_2136_20250916_2000 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13768_20250915_2136_20250916_2000,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 277/372 | 2025_HARP13768_20250916_2200_20250917_0424 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13768_20250916_2200_20250917_0424,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 278/372 | 2025_HARP13773_20250917_2236_20250918_0012 | targets=2
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13773_20250917_2236_20250918_0012,already_complete,2,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 279/372 | 2025_HARP13776_20250918_2200_20250919_0424 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13776_20250918_2200_20250919_0424,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 280/372 | 2025_HARP13768_20250919_1948_20250920_1012 | targets=10
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13768_20250919_1948_20250920_1012,already_complete,10,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 281/372 | 2025_HARP13777_20250920_1900_20250921_1724 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13777_20250920_1900_20250921_1724,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 282/372 | 2025_HARP13777_20250921_1900_20250922_1200 | targets=11
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13777_20250921_1900_20250922_1200,already_complete,11,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 283/372 | 2025_HARP13784_20250922_1348_20250923_1212 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13784_20250922_1348_20250923_1212,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 284/372 | 2025_HARP13801_20250924_1400_20250925_0424 | targets=10
==========================================================================================

----------------------------------------------------------------------
2025_HARP13801_20250924_1400_20250925_0424 | wavelength 94
94 Å cadence segments: 1 [('2025-09-24 14:00:00', '2025-09-25 04:24:00', 10)]
♻️ Segment 1/1 already covered by cached 94 Å files.

----------------------------------------------------------------------
2025_HARP13801_20250924_1400_20250925_0424 | wavelength 131
131 Å cadence segments: 1 [('2025-09-24 14:00:00', '2025-09-25 04:24:00', 10)]
Segment query: aia.lev1_euv_12s[2025-09-24T14:00:00.000/960m@96m][131]{image}
Segment reference: 2025-09-24 21:12:00 | targets: 10 | patch arcsec: 1100.0
JSOC export attempt 1/10

2026-06-30 09:18:40 - drms - INFO: Export request pending. [id=JSOC_20260630_006213, status=2]

2026-06-30 09:18:40 - drms - INFO: Waiting for 15 seconds...

2026-06-30 09:18:56 - drms - INFO: Export request pending. [id=JSOC_20260630_006213, status=1]

2026-06-30 09:18:56 - drms - INFO: Waiting for 15 seconds...

2026-06-30 09:19:11 - drms - INFO: Export request pending. [id=JSOC_20260630_006213, status=1]

2026-06-30 09:19:11 - drms - INFO: Waiting for 15 seconds...

2026-06-30 09:19:27 - drms - INFO: Export request pending. [id=JSOC_20260630_006213, status=1]

2026-06-30 09:19:27 - drms - INFO: Waiting for 15 seconds...

2026-06-30 09:19:43 - drms - INFO: Export request pending. [id=JSOC_20260630_006213, status=1]

2026-06-30 09:19:43 - drms - INFO: Waiting for 15 seconds...

2026-06-30 09:19:58 - drms - INFO: Export request finished. [id=JSOC_20260630_006213, status=0]

2026-06-30 09:19:58 - drms - INFO: Downloading file 1 of 9...

2026-06-30 09:19:58 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-09-24T15:35:59Z][131][JSOC_20260630_006213]

2026-06-30 09:19:58 - drms - INFO:     filename: aia.lev1_euv_12s.2025-09-24T153559Z.131.image.fits

2026-06-30 09:20:01 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13801_20250924_1400_20250925_0424/131/segment_01_20250924_1400_20250925_0424/aia.lev1_euv_12s.2025-09-24T153559Z.131.image.fits.1

2026-06-30 09:20:01 - drms - INFO: Downloading file 2 of 9...

2026-06-30 09:20:01 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-09-24T17:11:59Z][131][JSOC_20260630_006213]

2026-06-30 09:20:01 - drms - INFO:     filename: aia.lev1_euv_12s.2025-09-24T171159Z.131.image.fits

2026-06-30 09:20:04 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13801_20250924_1400_20250925_0424/131/segment_01_20250924_1400_20250925_0424/aia.lev1_euv_12s.2025-09-24T171159Z.131.image.fits.1

2026-06-30 09:20:04 - drms - INFO: Downloading file 3 of 9...

2026-06-30 09:20:04 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-09-24T18:47:59Z][131][JSOC_20260630_006213]

2026-06-30 09:20:04 - drms - INFO:     filename: aia.lev1_euv_12s.2025-09-24T184759Z.131.image.fits

2026-06-30 09:20:07 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13801_20250924_1400_20250925_0424/131/segment_01_20250924_1400_20250925_0424/aia.lev1_euv_12s.2025-09-24T184759Z.131.image.fits.1

2026-06-30 09:20:07 - drms - INFO: Downloading file 4 of 9...

2026-06-30 09:20:07 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-09-24T20:23:59Z][131][JSOC_20260630_006213]

2026-06-30 09:20:07 - drms - INFO:     filename: aia.lev1_euv_12s.2025-09-24T202359Z.131.image.fits

2026-06-30 09:20:10 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13801_20250924_1400_20250925_0424/131/segment_01_20250924_1400_20250925_0424/aia.lev1_euv_12s.2025-09-24T202359Z.131.image.fits.1

2026-06-30 09:20:10 - drms - INFO: Downloading file 5 of 9...

2026-06-30 09:20:10 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-09-24T21:59:59Z][131][JSOC_20260630_006213]

2026-06-30 09:20:10 - drms - INFO:     filename: aia.lev1_euv_12s.2025-09-24T215959Z.131.image.fits

2026-06-30 09:20:12 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13801_20250924_1400_20250925_0424/131/segment_01_20250924_1400_20250925_0424/aia.lev1_euv_12s.2025-09-24T215959Z.131.image.fits.1

2026-06-30 09:20:12 - drms - INFO: Downloading file 6 of 9...

2026-06-30 09:20:12 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-09-24T23:35:59Z][131][JSOC_20260630_006213]

2026-06-30 09:20:12 - drms - INFO:     filename: aia.lev1_euv_12s.2025-09-24T233559Z.131.image.fits

2026-06-30 09:20:15 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13801_20250924_1400_20250925_0424/131/segment_01_20250924_1400_20250925_0424/aia.lev1_euv_12s.2025-09-24T233559Z.131.image.fits.1

2026-06-30 09:20:15 - drms - INFO: Downloading file 7 of 9...

2026-06-30 09:20:15 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-09-25T01:11:59Z][131][JSOC_20260630_006213]

2026-06-30 09:20:15 - drms - INFO:     filename: aia.lev1_euv_12s.2025-09-25T011159Z.131.image.fits

2026-06-30 09:20:18 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13801_20250924_1400_20250925_0424/131/segment_01_20250924_1400_20250925_0424/aia.lev1_euv_12s.2025-09-25T011159Z.131.image.fits.1

2026-06-30 09:20:18 - drms - INFO: Downloading file 8 of 9...

2026-06-30 09:20:18 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-09-25T02:47:59Z][131][JSOC_20260630_006213]

2026-06-30 09:20:18 - drms - INFO:     filename: aia.lev1_euv_12s.2025-09-25T024759Z.131.image.fits

2026-06-30 09:20:21 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13801_20250924_1400_20250925_0424/131/segment_01_20250924_1400_20250925_0424/aia.lev1_euv_12s.2025-09-25T024759Z.131.image.fits.1

2026-06-30 09:20:21 - drms - INFO: Downloading file 9 of 9...

2026-06-30 09:20:21 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-09-25T04:23:59Z][131][JSOC_20260630_006213]

2026-06-30 09:20:21 - drms - INFO:     filename: aia.lev1_euv_12s.2025-09-25T042359Z.131.image.fits

2026-06-30 09:20:23 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP13801_20250924_1400_20250925_0424/131/segment_01_20250924_1400_20250925_0424/aia.lev1_euv_12s.2025-09-25T042359Z.131.image.fits.1

BLOCK ERROR: RuntimeError('Downloaded 131 Å segment does not cover all target timestamps within 180 seconds.')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13801_20250924_1400_20250925_0424,error,10,None,0,None,RuntimeError('Downloaded 131 Å segment does no...

==========================================================================================
BLOCK 285/372 | 2025_HARP13801_20250925_0736_20250926_0424 | targets=14
==========================================================================================

----------------------------------------------------------------------
2025_HARP13801_20250925_0736_20250926_0424 | wavelength 94
94 Å cadence segments: 1 [('2025-09-25 07:36:00', '2025-09-26 04:24:00', 14)]
♻️ Segment 1/1 already covered by cached 94 Å files.

----------------------------------------------------------------------
2025_HARP13801_20250925_0736_20250926_0424 | wavelength 131
131 Å cadence segments: 1 [('2025-09-25 07:36:00', '2025-09-26 04:24:00', 14)]
♻️ Segment 1/1 already covered by cached 131 Å files.

----------------------------------------------------------------------
2025_HARP13801_20250925_0736_20250926_0424 | wavelength 171
171 Å cadence segments: 1 [('2025-09-25 07:36:00', '2025-09-26 04:24:00', 14)]
♻️ Segment 1/1 already covered by cached 171 Å files.

----------------------------------------------------------------------
2025_HARP13801_20250925_0736_20250926_0424 | wavelength 193
193 Å cadence segments: 1 [('2025-09-25 07:36:00', '2025-09-26 04:24:00', 14)]
♻️ Segment 1/1 already covered by cached 193 Å files.

----------------------------------------------------------------------
2025_HARP13801_20250925_0736_20250926_0424 | wavelength 211
211 Å cadence segments: 1 [('2025-09-25 07:36:00', '2025-09-26 04:24:00', 14)]
♻️ Segment 1/1 already covered by cached 211 Å files.

----------------------------------------------------------------------
2025_HARP13801_20250925_0736_20250926_0424 | wavelength 335
335 Å cadence segments: 1 [('2025-09-25 07:36:00', '2025-09-26 04:24:00', 14)]
♻️ Segment 1/1 already covered by cached 335 Å files.

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250925_0736_HARP13801_NOAA14226 ValueError('Target crop leaves block patch: bounds=(-22, 1921, -56, 1886), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250925_0912_HARP13801_NOAA14226 ValueError('Target crop leaves block patch: bounds=(-30, 1924, -64, 1890), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250925_1048_HARP13801_NOAA14226 ValueError('Target crop leaves block patch: bounds=(-38, 1927, -68, 1896), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250925_1224_HARP13801_NOAA14226 ValueError('Target crop leaves block patch: bounds=(-46, 1928, -74, 1900), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250925_1400_HARP13801_NOAA14226 ValueError('Target crop leaves block patch: bounds=(-61, 1931, -82, 1910), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250925_1536_HARP13801_NOAA14226 ValueError('Target crop leaves block patch: bounds=(-73, 1935, -89, 1919), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250925_1712_HARP13801_NOAA14226 ValueError('Target crop leaves block patch: bounds=(-81, 1938, -93, 1926), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250925_1848_HARP13801_NOAA14226 ValueError('Target crop leaves block patch: bounds=(-88, 1940, -97, 1931), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250925_2024_HARP13801_NOAA14226 ValueError('Target crop leaves block patch: bounds=(-95, 1940, -100, 1935), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250925_2200_HARP13801_NOAA14226 ValueError('Target crop leaves block patch: bounds=(-100, 1940, -101, 1940), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250925_2336_HARP13801_NOAA14226 ValueError('Target crop leaves block patch: bounds=(-107, 1939, -103, 1943), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250926_0112_HARP13801_NOAA14226 ValueError('Target crop leaves block patch: bounds=(-113, 1938, -105, 1945), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250926_0248_HARP13801_NOAA14226 ValueError('Target crop leaves block patch: bounds=(-130, 1937, -113, 1955), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250926_0424_HARP13801_NOAA14226 ValueError('Target crop leaves block patch: bounds=(-145, 1937, -121, 1961), shape=(1834, 1834)')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13801_20250925_0736_20250926_0424,completed,14,14,0,0.519,14 sample errors retained for retry

==========================================================================================
BLOCK 286/372 | 2025_HARP13835_20250927_0500_20250928_0324 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13835_20250927_0500_20250928_0324,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 287/372 | 2025_HARP13801_20250928_0800_20250928_2224 | targets=10
==========================================================================================

----------------------------------------------------------------------
2025_HARP13801_20250928_0800_20250928_2224 | wavelength 94
94 Å cadence segments: 1 [('2025-09-28 08:00:00', '2025-09-28 22:24:00', 10)]
♻️ Segment 1/1 already covered by cached 94 Å files.

----------------------------------------------------------------------
2025_HARP13801_20250928_0800_20250928_2224 | wavelength 131
131 Å cadence segments: 1 [('2025-09-28 08:00:00', '2025-09-28 22:24:00', 10)]
♻️ Segment 1/1 already covered by cached 131 Å files.

----------------------------------------------------------------------
2025_HARP13801_20250928_0800_20250928_2224 | wavelength 171
171 Å cadence segments: 1 [('2025-09-28 08:00:00', '2025-09-28 22:24:00', 10)]
♻️ Segment 1/1 already covered by cached 171 Å files.

----------------------------------------------------------------------
2025_HARP13801_20250928_0800_20250928_2224 | wavelength 193
193 Å cadence segments: 1 [('2025-09-28 08:00:00', '2025-09-28 22:24:00', 10)]
♻️ Segment 1/1 already covered by cached 193 Å files.

----------------------------------------------------------------------
2025_HARP13801_20250928_0800_20250928_2224 | wavelength 211
211 Å cadence segments: 1 [('2025-09-28 08:00:00', '2025-09-28 22:24:00', 10)]
♻️ Segment 1/1 already covered by cached 211 Å files.

----------------------------------------------------------------------
2025_HARP13801_20250928_0800_20250928_2224 | wavelength 335
335 Å cadence segments: 1 [('2025-09-28 08:00:00', '2025-09-28 22:24:00', 10)]
♻️ Segment 1/1 already covered by cached 335 Å files.

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250928_0800_HARP13801_NOAA14226 ValueError('Target crop leaves block patch: bounds=(-65, 1969, -100, 1935), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250928_0936_HARP13801_NOAA14226 ValueError('Target crop leaves block patch: bounds=(-65, 1956, -93, 1928), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250928_1112_HARP13801_NOAA14226 ValueError('Target crop leaves block patch: bounds=(-69, 1946, -90, 1925), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250928_1248_HARP13801_NOAA14226 ValueError('Target crop leaves block patch: bounds=(-72, 1938, -88, 1922), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250928_1424_HARP13801_NOAA14226 ValueError('Target crop leaves block patch: bounds=(-72, 1928, -83, 1916), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250928_1600_HARP13801_NOAA14226 ValueError('Target crop leaves block patch: bounds=(-71, 1919, -52, 1938), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250928_1736_HARP13801_NOAA14226 ValueError('Target crop leaves block patch: bounds=(-71, 1909, -47, 1933), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250928_1912_HARP13801_NOAA14226 ValueError('Target crop leaves block patch: bounds=(-69, 1899, -41, 1927), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250928_2048_HARP13801_NOAA14226 ValueError('Target crop leaves block patch: bounds=(-65, 1888, -36, 1917), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250928_2224_HARP13801_NOAA14226 ValueError('Target crop leaves block patch: bounds=(-60, 1877, -31, 1906), shape=(1834, 1834)')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13801_20250928_0800_20250928_2224,completed,10,10,0,0.38,10 sample errors retained for retry

==========================================================================================
BLOCK 288/372 | 2025_HARP13801_20250929_0324_20250929_0812 | targets=4
==========================================================================================

----------------------------------------------------------------------
2025_HARP13801_20250929_0324_20250929_0812 | wavelength 94
94 Å cadence segments: 1 [('2025-09-29 03:24:00', '2025-09-29 08:12:00', 4)]
♻️ Segment 1/1 already covered by cached 94 Å files.

----------------------------------------------------------------------
2025_HARP13801_20250929_0324_20250929_0812 | wavelength 131
131 Å cadence segments: 1 [('2025-09-29 03:24:00', '2025-09-29 08:12:00', 4)]
♻️ Segment 1/1 already covered by cached 131 Å files.

----------------------------------------------------------------------
2025_HARP13801_20250929_0324_20250929_0812 | wavelength 171
171 Å cadence segments: 1 [('2025-09-29 03:24:00', '2025-09-29 08:12:00', 4)]
♻️ Segment 1/1 already covered by cached 171 Å files.

----------------------------------------------------------------------
2025_HARP13801_20250929_0324_20250929_0812 | wavelength 193
193 Å cadence segments: 1 [('2025-09-29 03:24:00', '2025-09-29 08:12:00', 4)]
♻️ Segment 1/1 already covered by cached 193 Å files.

----------------------------------------------------------------------
2025_HARP13801_20250929_0324_20250929_0812 | wavelength 211
211 Å cadence segments: 1 [('2025-09-29 03:24:00', '2025-09-29 08:12:00', 4)]
♻️ Segment 1/1 already covered by cached 211 Å files.

----------------------------------------------------------------------
2025_HARP13801_20250929_0324_20250929_0812 | wavelength 335
335 Å cadence segments: 1 [('2025-09-29 03:24:00', '2025-09-29 08:12:00', 4)]
♻️ Segment 1/1 already covered by cached 335 Å files.

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250929_0324_HARP13801_NOAA14226 ValueError('Target crop leaves block patch: bounds=(-14, 1878, -31, 1862), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250929_0500_HARP13801_NOAA14226 ValueError('Target crop leaves block patch: bounds=(-11, 1866, -21, 1856), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250929_0636_HARP13801_NOAA14226 ValueError('Target crop leaves block patch: bounds=(-6, 1853, -11, 1848), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20250929_0812_HARP13801_NOAA14226 ValueError('Target crop leaves block patch: bounds=(0, 1840, -2, 1838), shape=(1834, 1834)')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13801_20250929_0324_20250929_0812,completed,4,4,0,0.155,4 sample errors retained for retry

==========================================================================================
BLOCK 289/372 | 2025_HARP13845_20250930_0348_20251001_0224 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13845_20250930_0348_20251001_0224,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 290/372 | 2025_HARP13835_20251001_0412_20251001_1212 | targets=6
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13835_20251001_0412_20251001_1212,already_complete,6,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 291/372 | 2025_HARP13831_20251002_2200_20251003_0424 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13831_20251002_2200_20251003_0424,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 292/372 | 2025_HARP13855_20251003_1936_20251003_1936 | targets=1
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13855_20251003_1936_20251003_1936,already_complete,1,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 293/372 | 2025_HARP13852_20251004_0800_20251005_0624 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13852_20251004_0800_20251005_0624,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 294/372 | 2025_HARP13855_20251005_1936_20251006_1624 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13855_20251005_1936_20251006_1624,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 295/372 | 2025_HARP13876_20251006_1324_20251007_1148 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13876_20251006_1324_20251007_1148,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 296/372 | 2025_HARP13852_20251007_0800_20251008_0336 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13852_20251007_0800_20251008_0336,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 297/372 | 2025_HARP13852_20251008_0712_20251008_1336 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13852_20251008_0712_20251008_1336,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 298/372 | 2025_HARP13866_20251008_2248_20251009_1624 | targets=12
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13866_20251008_2248_20251009_1624,already_complete,12,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 299/372 | 2025_HARP13872_20251009_1936_20251010_1448 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13872_20251009_1936_20251010_1448,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 300/372 | 2025_HARP13872_20251010_1936_20251011_1624 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13872_20251010_1936_20251011_1624,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 301/372 | 2025_HARP13895_20251012_0400_20251013_0224 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13895_20251012_0400_20251013_0224,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 302/372 | 2025_HARP13881_20251012_2236_20251013_2100 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13881_20251012_2236_20251013_2100,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 303/372 | 2025_HARP13887_20251013_0736_20251013_1712 | targets=7
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13887_20251013_0736_20251013_1712,already_complete,7,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 304/372 | 2025_HARP13880_20251013_2048_20251014_0800 | targets=8
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13880_20251013_2048_20251014_0800,already_complete,8,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 305/372 | 2025_HARP13887_20251014_0736_20251015_0612 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13887_20251014_0736_20251015_0612,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 306/372 | 2025_HARP13881_20251015_0200_20251015_1136 | targets=7
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13881_20251015_0200_20251015_1136,already_complete,7,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 307/372 | 2025_HARP13881_20251015_1836_20251016_1212 | targets=12
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13881_20251015_1836_20251016_1212,already_complete,12,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 308/372 | 2025_HARP13881_20251016_1836_20251017_1348 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13881_20251016_1836_20251017_1348,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 309/372 | 2025_HARP13891_20251017_1912_20251018_1736 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13891_20251017_1912_20251018_1736,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 310/372 | 2025_HARP13901_20251018_2112_20251019_1624 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13901_20251018_2112_20251019_1624,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 311/372 | 2025_HARP13935_20251020_0812_20251021_0636 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13935_20251020_0812_20251021_0636,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 312/372 | 2025_HARP13935_20251021_0848_20251021_1824 | targets=7
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13935_20251021_0848_20251021_1824,already_complete,7,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 313/372 | 2025_HARP13935_20251021_2136_20251022_2024 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13935_20251021_2136_20251022_2024,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 314/372 | 2025_HARP13935_20251022_2200_20251023_0248 | targets=4
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13935_20251022_2200_20251023_0248,already_complete,4,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 315/372 | 2025_HARP13931_20251023_1936_20251024_1624 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13931_20251023_1936_20251024_1624,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 316/372 | 2025_HARP13931_20251024_1936_20251025_1624 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13931_20251024_1936_20251025_1624,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 317/372 | 2025_HARP13911_20251025_0736_20251025_2024 | targets=9
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13911_20251025_0736_20251025_2024,already_complete,9,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 318/372 | 2025_HARP13930_20251026_0148_20251027_0012 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13930_20251026_0148_20251027_0012,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 319/372 | 2025_HARP13929_20251027_0048_20251027_2312 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13929_20251027_0048_20251027_2312,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 320/372 | 2025_HARP13946_20251027_1324_20251028_1148 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13946_20251027_1324_20251028_1148,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 321/372 | 2025_HARP13955_20251028_0100_20251028_2336 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13955_20251028_0100_20251028_2336,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 322/372 | 2025_HARP13960_20251028_2248_20251029_1624 | targets=12
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13960_20251028_2248_20251029_1624,already_complete,12,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 323/372 | 2025_HARP13955_20251029_0736_20251029_1048 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13955_20251029_0736_20251029_1048,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 324/372 | 2025_HARP13960_20251030_2012_20251031_0900 | targets=9
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13960_20251030_2012_20251031_0900,already_complete,9,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 325/372 | 2025_HARP13982_20251104_2148_20251105_2036 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13982_20251104_2148_20251105_2036,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 326/372 | 2025_HARP13999_20251107_0524_20251108_0348 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP13999_20251107_0524_20251108_0348,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 327/372 | 2025_HARP14003_20251108_1300_20251109_1124 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14003_20251108_1300_20251109_1124,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 328/372 | 2025_HARP14008_20251109_1600_20251110_1424 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14008_20251109_1600_20251110_1424,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 329/372 | 2025_HARP14008_20251110_1600_20251111_1424 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14008_20251110_1600_20251111_1424,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 330/372 | 2025_HARP14008_20251111_1600_20251111_1736 | targets=2
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14008_20251111_1600_20251111_1736,already_complete,2,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 331/372 | 2025_HARP14009_20251113_1036_20251114_0900 | targets=15
==========================================================================================

----------------------------------------------------------------------
2025_HARP14009_20251113_1036_20251114_0900 | wavelength 94
94 Å cadence segments: 1 [('2025-11-13 10:36:00', '2025-11-14 09:00:00', 15)]
♻️ Segment 1/1 already covered by cached 94 Å files.

----------------------------------------------------------------------
2025_HARP14009_20251113_1036_20251114_0900 | wavelength 131
131 Å cadence segments: 1 [('2025-11-13 10:36:00', '2025-11-14 09:00:00', 15)]
♻️ Segment 1/1 already covered by cached 131 Å files.

----------------------------------------------------------------------
2025_HARP14009_20251113_1036_20251114_0900 | wavelength 171
171 Å cadence segments: 1 [('2025-11-13 10:36:00', '2025-11-14 09:00:00', 15)]
♻️ Segment 1/1 already covered by cached 171 Å files.

----------------------------------------------------------------------
2025_HARP14009_20251113_1036_20251114_0900 | wavelength 193
193 Å cadence segments: 1 [('2025-11-13 10:36:00', '2025-11-14 09:00:00', 15)]
♻️ Segment 1/1 already covered by cached 193 Å files.

----------------------------------------------------------------------
2025_HARP14009_20251113_1036_20251114_0900 | wavelength 211
211 Å cadence segments: 1 [('2025-11-13 10:36:00', '2025-11-14 09:00:00', 15)]
♻️ Segment 1/1 already covered by cached 211 Å files.

----------------------------------------------------------------------
2025_HARP14009_20251113_1036_20251114_0900 | wavelength 335
335 Å cadence segments: 1 [('2025-11-13 10:36:00', '2025-11-14 09:00:00', 15)]
♻️ Segment 1/1 already covered by cached 335 Å files.

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20251113_1036_HARP14009_NOAA14276 ValueError('Target crop leaves block patch: bounds=(-62, 1952, -94, 1919), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20251113_1212_HARP14009_NOAA14276 ValueError('Target crop leaves block patch: bounds=(-61, 1947, -89, 1919), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20251113_1348_HARP14009_NOAA14276 ValueError('Target crop leaves block patch: bounds=(-60, 1941, -85, 1916), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20251113_1524_HARP14009_NOAA14276 ValueError('Target crop leaves block patch: bounds=(-57, 1937, -81, 1913), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20251113_1700_HARP14009_NOAA14276 ValueError('Target crop leaves block patch: bounds=(-57, 1930, -76, 1911), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20251113_1836_HARP14009_NOAA14276 ValueError('Target crop leaves block patch: bounds=(-67, 1924, -79, 1913), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20251113_2012_HARP14009_NOAA14276 ValueError('Target crop leaves block patch: bounds=(-72, 1916, -78, 1911), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20251113_2148_HARP14009_NOAA14276 ValueError('Target crop leaves block patch: bounds=(-74, 1907, -75, 1907), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20251113_2324_HARP14009_NOAA14276 ValueError('Target crop leaves block patch: bounds=(-85, 1900, -75, 1910), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20251114_0100_HARP14009_NOAA14276 ValueError('Target crop leaves block patch: bounds=(-85, 1892, -71, 1906), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20251114_0236_HARP14009_NOAA14276 ValueError('Target crop leaves block patch: bounds=(-84, 1883, -66, 1900), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20251114_0412_HARP14009_NOAA14276 ValueError('Target crop leaves block patch: bounds=(-81, 1875, -61, 1895), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20251114_0548_HARP14009_NOAA14276 ValueError('Target crop leaves block patch: bounds=(-75, 1866, -54, 1886), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20251114_0724_HARP14009_NOAA14276 ValueError('Target crop leaves block patch: bounds=(-76, 1855, -51, 1880), shape=(1834, 1834)')

/tmp/ipykernel_2312897/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20251114_0900_HARP14009_NOAA14276 ValueError('Target crop leaves block patch: bounds=(-75, 1844, -45, 1874), shape=(1834, 1834)')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14009_20251113_1036_20251114_0900,completed,15,15,0,0.644,15 sample errors retained for retry

==========================================================================================
BLOCK 332/372 | 2025_HARP14024_20251114_1236_20251115_1100 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14024_20251114_1236_20251115_1100,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 333/372 | 2025_HARP14054_20251116_0912_20251117_0424 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14054_20251116_0912_20251117_0424,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 334/372 | 2025_HARP14059_20251117_1048_20251118_0248 | targets=11
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14059_20251117_1048_20251118_0248,already_complete,11,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 335/372 | 2025_HARP14045_20251118_1348_20251118_1348 | targets=1
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14045_20251118_1348_20251118_1348,already_complete,1,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 336/372 | 2025_HARP14056_20251121_1936_20251122_1624 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14056_20251121_1936_20251122_1624,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 337/372 | 2025_HARP14060_20251123_0736_20251124_0424 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14060_20251123_0736_20251124_0424,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 338/372 | 2025_HARP14056_20251123_1936_20251124_1448 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14056_20251123_1936_20251124_1448,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 339/372 | 2025_HARP14063_20251124_1548_20251124_1548 | targets=1
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14063_20251124_1548_20251124_1548,already_complete,1,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 340/372 | 2025_HARP14057_20251124_2324_20251124_2324 | targets=1
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14057_20251124_2324_20251124_2324,already_complete,1,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 341/372 | 2025_HARP14081_20251125_1512_20251126_1348 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14081_20251125_1512_20251126_1348,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 342/372 | 2025_HARP14060_20251126_1412_20251127_0748 | targets=12
==========================================================================================

----------------------------------------------------------------------
2025_HARP14060_20251126_1412_20251127_0748 | wavelength 94
94 Å cadence segments: 1 [('2025-11-26 14:12:00', '2025-11-27 07:48:00', 12)]
Segment query: aia.lev1_euv_12s[2025-11-26T14:12:00.000/1152m@96m][94]{image}
Segment reference: 2025-11-26 23:00:00 | targets: 12 | patch arcsec: 306.9316614315492
JSOC export attempt 1/10

2026-06-30 09:24:07 - drms - INFO: Export request pending. [id=JSOC_20260630_006293, status=2]

2026-06-30 09:24:07 - drms - INFO: Waiting for 15 seconds...

2026-06-30 09:24:23 - drms - INFO: Export request pending. [id=JSOC_20260630_006293, status=1]

2026-06-30 09:24:23 - drms - INFO: Waiting for 15 seconds...

2026-06-30 09:24:38 - drms - INFO: Export request pending. [id=JSOC_20260630_006293, status=1]

2026-06-30 09:24:38 - drms - INFO: Waiting for 15 seconds...

2026-06-30 09:24:54 - drms - INFO: Export request pending. [id=JSOC_20260630_006293, status=1]

2026-06-30 09:24:54 - drms - INFO: Waiting for 15 seconds...

2026-06-30 09:25:09 - drms - INFO: Export request finished. [id=JSOC_20260630_006293, status=0]

2026-06-30 09:25:09 - drms - INFO: Downloading file 1 of 11...

2026-06-30 09:25:09 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-11-26T14:11:59Z][94][JSOC_20260630_006293]

2026-06-30 09:25:09 - drms - INFO:     filename: aia.lev1_euv_12s.2025-11-26T141159Z.94.image.fits

2026-06-30 09:25:11 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP14060_20251126_1412_20251127_0748/94/segment_01_20251126_1412_20251127_0748/aia.lev1_euv_12s.2025-11-26T141159Z.94.image.fits.1

2026-06-30 09:25:11 - drms - INFO: Downloading file 2 of 11...

2026-06-30 09:25:11 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-11-26T15:47:59Z][94][JSOC_20260630_006293]

2026-06-30 09:25:11 - drms - INFO:     filename: aia.lev1_euv_12s.2025-11-26T154759Z.94.image.fits

2026-06-30 09:25:12 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP14060_20251126_1412_20251127_0748/94/segment_01_20251126_1412_20251127_0748/aia.lev1_euv_12s.2025-11-26T154759Z.94.image.fits.1

2026-06-30 09:25:12 - drms - INFO: Downloading file 3 of 11...

2026-06-30 09:25:12 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-11-26T17:23:59Z][94][JSOC_20260630_006293]

2026-06-30 09:25:12 - drms - INFO:     filename: aia.lev1_euv_12s.2025-11-26T172359Z.94.image.fits

2026-06-30 09:25:13 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP14060_20251126_1412_20251127_0748/94/segment_01_20251126_1412_20251127_0748/aia.lev1_euv_12s.2025-11-26T172359Z.94.image.fits.1

2026-06-30 09:25:13 - drms - INFO: Downloading file 4 of 11...

2026-06-30 09:25:13 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-11-26T18:59:59Z][94][JSOC_20260630_006293]

2026-06-30 09:25:13 - drms - INFO:     filename: aia.lev1_euv_12s.2025-11-26T185959Z.94.image.fits

2026-06-30 09:25:15 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP14060_20251126_1412_20251127_0748/94/segment_01_20251126_1412_20251127_0748/aia.lev1_euv_12s.2025-11-26T185959Z.94.image.fits.1

2026-06-30 09:25:15 - drms - INFO: Downloading file 5 of 11...

2026-06-30 09:25:15 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-11-26T20:35:59Z][94][JSOC_20260630_006293]

2026-06-30 09:25:15 - drms - INFO:     filename: aia.lev1_euv_12s.2025-11-26T203559Z.94.image.fits

2026-06-30 09:25:16 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP14060_20251126_1412_20251127_0748/94/segment_01_20251126_1412_20251127_0748/aia.lev1_euv_12s.2025-11-26T203559Z.94.image.fits.1

2026-06-30 09:25:16 - drms - INFO: Downloading file 6 of 11...

2026-06-30 09:25:16 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-11-26T22:11:59Z][94][JSOC_20260630_006293]

2026-06-30 09:25:16 - drms - INFO:     filename: aia.lev1_euv_12s.2025-11-26T221159Z.94.image.fits

2026-06-30 09:25:17 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP14060_20251126_1412_20251127_0748/94/segment_01_20251126_1412_20251127_0748/aia.lev1_euv_12s.2025-11-26T221159Z.94.image.fits.1

2026-06-30 09:25:17 - drms - INFO: Downloading file 7 of 11...

2026-06-30 09:25:17 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-11-26T23:47:59Z][94][JSOC_20260630_006293]

2026-06-30 09:25:17 - drms - INFO:     filename: aia.lev1_euv_12s.2025-11-26T234759Z.94.image.fits

2026-06-30 09:25:18 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP14060_20251126_1412_20251127_0748/94/segment_01_20251126_1412_20251127_0748/aia.lev1_euv_12s.2025-11-26T234759Z.94.image.fits.1

2026-06-30 09:25:18 - drms - INFO: Downloading file 8 of 11...

2026-06-30 09:25:18 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-11-27T01:23:59Z][94][JSOC_20260630_006293]

2026-06-30 09:25:18 - drms - INFO:     filename: aia.lev1_euv_12s.2025-11-27T012359Z.94.image.fits

2026-06-30 09:25:20 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP14060_20251126_1412_20251127_0748/94/segment_01_20251126_1412_20251127_0748/aia.lev1_euv_12s.2025-11-27T012359Z.94.image.fits.1

2026-06-30 09:25:20 - drms - INFO: Downloading file 9 of 11...

2026-06-30 09:25:20 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-11-27T02:59:59Z][94][JSOC_20260630_006293]

2026-06-30 09:25:20 - drms - INFO:     filename: aia.lev1_euv_12s.2025-11-27T025959Z.94.image.fits

2026-06-30 09:25:21 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP14060_20251126_1412_20251127_0748/94/segment_01_20251126_1412_20251127_0748/aia.lev1_euv_12s.2025-11-27T025959Z.94.image.fits.1

2026-06-30 09:25:21 - drms - INFO: Downloading file 10 of 11...

2026-06-30 09:25:21 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-11-27T04:35:59Z][94][JSOC_20260630_006293]

2026-06-30 09:25:21 - drms - INFO:     filename: aia.lev1_euv_12s.2025-11-27T043559Z.94.image.fits

2026-06-30 09:25:22 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP14060_20251126_1412_20251127_0748/94/segment_01_20251126_1412_20251127_0748/aia.lev1_euv_12s.2025-11-27T043559Z.94.image.fits.1

2026-06-30 09:25:22 - drms - INFO: Downloading file 11 of 11...

2026-06-30 09:25:22 - drms - INFO:     record: aia.lev1_euv_12s_mod[2025-11-27T06:11:59Z][94][JSOC_20260630_006293]

2026-06-30 09:25:22 - drms - INFO:     filename: aia.lev1_euv_12s.2025-11-27T061159Z.94.image.fits

2026-06-30 09:25:24 - drms - INFO:     -> ../harp_block_miner/production_aia2025-s0/temp_blocks/2025_HARP14060_20251126_1412_20251127_0748/94/segment_01_20251126_1412_20251127_0748/aia.lev1_euv_12s.2025-11-27T061159Z.94.image.fits.1

BLOCK ERROR: RuntimeError('Downloaded 94 Å segment does not cover all target timestamps within 180 seconds.')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14060_20251126_1412_20251127_0748,error,12,None,0,None,RuntimeError('Downloaded 94 Å segment does not...

==========================================================================================
BLOCK 343/372 | 2025_HARP14090_20251127_0700_20251128_0524 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14090_20251127_0700_20251128_0524,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 344/372 | 2025_HARP14090_20251128_0700_20251129_0524 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14090_20251128_0700_20251129_0524,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 345/372 | 2025_HARP14090_20251129_0700_20251129_1324 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14090_20251129_0700_20251129_1324,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 346/372 | 2025_HARP14090_20251129_1636_20251130_1500 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14090_20251129_1636_20251130_1500,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 347/372 | 2025_HARP14108_20251130_1936_20251201_1624 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14108_20251130_1936_20251201_1624,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 348/372 | 2025_HARP14111_20251203_1148_20251203_1536 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14111_20251203_1148_20251203_1536,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 349/372 | 2025_HARP14117_20251204_1236_20251205_1100 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14117_20251204_1236_20251205_1100,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 350/372 | 2025_HARP14124_20251205_1612_20251206_1436 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14124_20251205_1612_20251206_1436,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 351/372 | 2025_HARP14124_20251206_1612_20251207_1436 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14124_20251206_1612_20251207_1436,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 352/372 | 2025_HARP14117_20251207_1236_20251207_2036 | targets=6
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14117_20251207_1236_20251207_2036,already_complete,6,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 353/372 | 2025_HARP14138_20251208_1012_20251209_0836 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14138_20251208_1012_20251209_0836,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 354/372 | 2025_HARP14143_20251209_1536_20251210_0424 | targets=9
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14143_20251209_1536_20251210_0424,already_complete,9,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 355/372 | 2025_HARP14156_20251210_1136_20251210_1624 | targets=4
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14156_20251210_1136_20251210_1624,already_complete,4,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 356/372 | 2025_HARP14156_20251211_1948_20251212_1812 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14156_20251211_1948_20251212_1812,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 357/372 | 2025_HARP14156_20251212_1948_20251213_1812 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14156_20251212_1948_20251213_1812,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 358/372 | 2025_HARP14172_20251214_1448_20251214_1448 | targets=1
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14172_20251214_1448_20251214_1448,already_complete,1,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 359/372 | 2025_HARP14172_20251215_1048_20251216_0424 | targets=12
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14172_20251215_1048_20251216_0424,already_complete,12,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 360/372 | 2025_HARP14165_20251218_0148_20251219_0012 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14165_20251218_0148_20251219_0012,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 361/372 | 2025_HARP14177_20251219_2048_20251220_1912 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14177_20251219_2048_20251220_1912,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 362/372 | 2025_HARP14176_20251221_1836_20251222_1700 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14176_20251221_1836_20251222_1700,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 363/372 | 2025_HARP14176_20251222_1836_20251223_1700 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14176_20251222_1836_20251223_1700,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 364/372 | 2025_HARP14176_20251223_1836_20251224_0424 | targets=7
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14176_20251223_1836_20251224_0424,already_complete,7,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 365/372 | 2025_HARP14187_20251224_2048_20251225_1912 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14187_20251224_2048_20251225_1912,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 366/372 | 2025_HARP14187_20251225_2048_20251226_0800 | targets=8
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14187_20251225_2048_20251226_0800,already_complete,8,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 367/372 | 2025_HARP14200_20251226_1900_20251227_1724 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14200_20251226_1900_20251227_1724,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 368/372 | 2025_HARP14200_20251227_1900_20251228_1724 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14200_20251227_1900_20251228_1724,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 369/372 | 2025_HARP14205_20251228_1736_20251229_1600 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14205_20251228_1736_20251229_1600,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 370/372 | 2025_HARP14200_20251229_1900_20251230_0436 | targets=7
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14200_20251229_1900_20251230_0436,already_complete,7,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 371/372 | 2025_HARP14220_20251230_1612_20251230_1748 | targets=2
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14220_20251230_1612_20251230_1748,already_complete,2,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 372/372 | 2025_HARP14220_20251231_2124_20251231_2300 | targets=2
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2025_HARP14220_20251231_2124_20251231_2300,already_complete,2,0,0.0,all_samples_already_in_gcp

Run finished.
Completed model-ready objects now visible in GCP: 12115

## 10. Audit expected versus completed

In [13]:

fresh_listing = run_command(
    ["gcloud", "storage", "ls", "--recursive", GCP_OUTPUT_ROOT],
    check=False,
)
actual_ids = {
    Path(line.strip()).stem
    for line in fresh_listing.stdout.splitlines()
    if line.strip().endswith(".npz")
}

expected_ids = set(df["sample_id"].astype(str))

if RUN_MODE == "BLOCK_CANARY" or (
    RUN_MODE == "PRODUCTION" and NUM_SHARDS > 1
):
    selected_block_ids = set(block_plan["block_id"])
    expected_ids = set(
        pd.concat(
            [block_frames[item] for item in selected_block_ids],
            ignore_index=True,
        )["sample_id"].astype(str)
    )

missing_ids = expected_ids - actual_ids
unexpected_ids = actual_ids - set(df["sample_id"].astype(str))

print("Expected in this run scope:", len(expected_ids))
print("Completed in GCP:", len(actual_ids.intersection(expected_ids)))
print("Missing:", len(missing_ids))
print("Unexpected:", len(unexpected_ids))

audit = pd.DataFrame(
    {
        "metric": [
            "expected_scope",
            "completed_scope",
            "missing_scope",
            "unexpected_year_objects",
        ],
        "value": [
            len(expected_ids),
            len(actual_ids.intersection(expected_ids)),
            len(missing_ids),
            len(unexpected_ids),
        ],
    }
)
display(audit)

missing_path = LOCAL_META / f"missing_ids_{WORKER_ID}.txt"
missing_path.write_text("\n".join(sorted(missing_ids)))
run_command(
    [
        "gcloud", "storage", "cp",
        str(missing_path),
        f"{GCP_WORKER_META}/{missing_path.name}",
    ],
    check=True,
)

Expected in this run scope: 3664
Completed in GCP: 3433
Missing: 231
Unexpected: 0

                    metric  value
0           expected_scope   3664
1          completed_scope   3433
2            missing_scope    231
3  unexpected_year_objects      0

CompletedProcess(args=['gcloud', 'storage', 'cp', '/home/abmoses2000/solar_flare_aia/harp_block_miner/production_aia2025-s0/metadata/missing_ids_aia2025-s0.txt', 'gs://suryabench-sharp-pipeline-bamidele/jsoc_2025_2026_production_v1/metadata/workers/aia2025-s0/missing_ids_aia2025-s0.txt'], returncode=0, stdout='', stderr='Copying file:///home/abmoses2000/solar_flare_aia/harp_block_miner/production_aia2025-s0/metadata/missing_ids_aia2025-s0.txt to gs://suryabench-sharp-pipeline-bamidele/jsoc_2025_2026_production_v1/metadata/workers/aia2025-s0/missing_ids_aia2025-s0.txt\n  \n.\n')

## 11. Block-canary comparison with individual pilot outputs

In [14]:

if RUN_MODE != "BLOCK_CANARY":
    print("Comparison is only used in BLOCK_CANARY mode.")
else:
    comparison_root = LOCAL_ROOT / "comparison"
    comparison_root.mkdir(parents=True, exist_ok=True)

    comparison_rows = []

    for sample_id in CANARY_SAMPLE_IDS[TARGET_YEAR]:
        block_path = comparison_root / f"block_{sample_id}.npz"
        pilot_path = comparison_root / f"pilot_{sample_id}.npz"

        block_gcp = f"{GCP_OUTPUT_ROOT}/{sample_id}.npz"
        pilot_gcp = f"{PILOT_GCP_ROOT}/{sample_id}.npz"

        if not gcp_exists(block_gcp) or not gcp_exists(pilot_gcp):
            print("Comparison unavailable:", sample_id)
            continue

        run_command(
            ["gcloud", "storage", "cp", block_gcp, str(block_path)]
        )
        run_command(
            ["gcloud", "storage", "cp", pilot_gcp, str(pilot_path)]
        )

        with np.load(block_path, allow_pickle=True) as block_npz:
            block_x = block_npz["x"]
        with np.load(pilot_path, allow_pickle=True) as pilot_npz:
            pilot_x = pilot_npz["x"]

        for channel_index, wavelength in enumerate(AIA_WAVELENGTHS):
            first = block_x[:, :, channel_index]
            second = pilot_x[:, :, channel_index]

            correlation = float(
                np.corrcoef(first.ravel(), second.ravel())[0, 1]
            )
            ssim = float(
                structural_similarity(
                    first,
                    second,
                    data_range=1.0,
                )
            )

            comparison_rows.append(
                {
                    "sample_id": sample_id,
                    "wavelength": wavelength,
                    "pearson_r": correlation,
                    "ssim": ssim,
                }
            )

        fig, axes = plt.subplots(2, 6, figsize=(18, 6))
        for channel_index, wavelength in enumerate(AIA_WAVELENGTHS):
            axes[0, channel_index].imshow(
                pilot_x[:, :, channel_index],
                origin="lower",
                cmap="gray",
            )
            axes[0, channel_index].set_title(f"Pilot {wavelength} Å")
            axes[0, channel_index].axis("off")

            axes[1, channel_index].imshow(
                block_x[:, :, channel_index],
                origin="lower",
                cmap="gray",
            )
            axes[1, channel_index].set_title(f"Block {wavelength} Å")
            axes[1, channel_index].axis("off")

        fig.suptitle(sample_id)
        plt.tight_layout()
        plt.show()

    comparison_df = pd.DataFrame(comparison_rows)
    display(comparison_df)

    if len(comparison_df):
        print("\nMean correlation:", comparison_df["pearson_r"].mean())
        print("Mean SSIM:", comparison_df["ssim"].mean())

        comparison_path = (
            LOCAL_META / f"block_vs_pilot_{WORKER_ID}.csv"
        )
        comparison_df.to_csv(comparison_path, index=False)
        run_command(
            [
                "gcloud", "storage", "cp",
                str(comparison_path),
                f"{GCP_WORKER_META}/{comparison_path.name}",
            ],
            check=True,
        )

Comparison is only used in BLOCK_CANARY mode.


## 12. Acceptance gate

Before switching to `PRODUCTION`, confirm:

1. all target timestamps in the selected block are represented;
2. six AIA channels exist for every saved sample;
3. output shape is `(512, 512, 6)`;
4. all values are finite and within `[0, 1]`;
5. AIA-to-SHARP time differences are no more than 180 seconds;
6. active regions are centred and not clipped;
7. block-generated images visually match the individual pilot images;
8. correlation and SSIM are scientifically acceptable;
9. no unexpected sample IDs are present;
10. block runtime is materially faster than the former 7–8 minutes per sample.

## Starting production on the VM

Once the block canary passes, place the notebook in:

```text
~/solar_flare_aia/notebooks/
```

Then run the 2025 worker:

```bash
tmux new -s aia2025
source ~/solar_flare_aia/venv/bin/activate
export TARGET_YEAR=2025
export JSOC_EMAIL=abmoses2000@gmail.com
export WORKER_ID=aia2025
export RUN_MODE=PRODUCTION
jupyter nbconvert \
  --to notebook \
  --execute ~/solar_flare_aia/notebooks/05_AIA_JSOC_HARP_BLOCK_MINER_VM_READY.ipynb \
  --ExecutePreprocessor.timeout=-1 \
  --output ~/solar_flare_aia/logs/aia2025_executed.ipynb
```

Detach from `tmux` with `Ctrl+B`, then `D`.

A second worker can process 2026 using `worky4work@gmail.com`, but first verify that two simultaneous block workers do not overload the VM or JSOC.