
# AIA 2025–2026 HARP-Block Miner — VM Ready

This notebook replaces the slow **six JSOC exports per individual sample** strategy.

## Core idea

Instead of:

```text
1 sample × 6 wavelengths = 6 JSOC export jobs
```

the miner groups required timestamps by **HARPNUM** and **24-hour blocks**:

```text
1 HARP/time block × 6 wavelength-sequence exports
→ many model-ready samples
```

Each wavelength request returns a tracked time series of active-region cutouts. The notebook then:

1. matches each returned AIA image to the required SHARP timestamp;
2. locally extracts the target-specific crop using the FITS WCS;
3. resizes it to `512 × 512`;
4. applies the same historical preprocessing used for 2010–2024;
5. stacks the six channels;
6. uploads each `.npz` immediately to Google Cloud Storage;
7. checkpoints sample and block progress for safe restart.

## Safety

The notebook defaults to `BLOCK_CANARY` mode. It must pass a small block test before `PRODUCTION` mode is enabled.

Official JSOC/DRMS behaviour used here:

- query form: `Series[timespan@cadence][wavelength]{image}`;
- `im_patch` server-side cutouts;
- `t=0` enables solar-rotation tracking;
- one pending export at a time per registered email;
- RequestIDs are saved and reopened after interruption.

## VM execution

Run this notebook on the prepared Compute Engine VM inside `tmux`.

For 2025:

```bash
export TARGET_YEAR=2025
export JSOC_EMAIL=abmoses2000@gmail.com
export WORKER_ID=aia2025
export RUN_MODE=BLOCK_CANARY
```

For 2026, after the 2025 block canary succeeds:

```bash
export TARGET_YEAR=2026
export JSOC_EMAIL=worky4work@gmail.com
export WORKER_ID=aia2026
export RUN_MODE=BLOCK_CANARY
```

After QA passes, change `RUN_MODE=PRODUCTION`.

In [1]:

# The VM environment already contains most packages.
# This cell is safe to rerun and installs only missing dependencies.

%pip install -q --upgrade \
    "drms>=0.9.1" \
    "astropy>=7.0" \
    "sunpy[map]>=7.0" \
    "scikit-image>=0.25" \
    "google-cloud-storage>=3.0"

Note: you may need to restart the kernel to use updated packages.

In [2]:

import os
import re
import gc
import sys
import json
import time
import math
import shutil
import hashlib
import subprocess
from pathlib import Path
from datetime import datetime

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import drms
from drms.exceptions import DrmsExportError
from astropy.io import fits
from astropy import units as u
from astropy.coordinates import SkyCoord
from skimage.transform import resize
from skimage.metrics import structural_similarity

import sunpy.map

print("Python:", sys.version)
print("DRMS:", drms.__version__)
print("SunPy:", sunpy.__version__)

Python: 3.12.3 (main, Mar 23 2026, 19:04:32) [GCC 13.3.0]
DRMS: 0.9.1
SunPy: 7.1.2

/home/abmoses2000/solar_flare_aia/venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## 1. Configuration

In [3]:

# ============================================================
# ENVIRONMENT-AWARE CONFIGURATION
# ============================================================

PROJECT_ID = "sonorous-shore-450510-i4"
GCP_BUCKET = "gs://suryabench-sharp-pipeline-bamidele"

TARGET_YEAR = int(os.environ.get("TARGET_YEAR", "2025"))
JSOC_EMAIL = os.environ.get(
    "JSOC_EMAIL",
    "abmoses2000@gmail.com" if TARGET_YEAR == 2025 else "worky4work@gmail.com",
)
WORKER_ID = os.environ.get("WORKER_ID", f"aia{TARGET_YEAR}")
RUN_MODE = os.environ.get("RUN_MODE", "BLOCK_CANARY").upper()

if RUN_MODE not in {"BLOCK_CANARY", "PRODUCTION"}:
    raise ValueError("RUN_MODE must be BLOCK_CANARY or PRODUCTION.")

AIA_WAVELENGTHS = [94, 131, 171, 193, 211, 335]
IMAGE_SIZE = 512

# Time grouping
BLOCK_HOURS = 24
TARGET_CADENCE_MIN = 96
MAX_TARGET_TIME_DIFFERENCE_SEC = 180
MAX_GAP_WITHIN_TRACK_SEC = 3 * 3600

# The server-side tracked patch is deliberately larger than the
# target-specific crop. Each target is then cropped locally using WCS.
BLOCK_PATCH_MARGIN_ARCSEC = 160.0
MIN_BLOCK_PATCH_ARCSEC = 300.0
MAX_BLOCK_PATCH_ARCSEC = 1100.0

# Historical geometry constants retained for compatibility with the pilot.
FULL_DISK_SIZE = 4096
IMAGE_CENTER = FULL_DISK_SIZE // 2
AIA_PIXEL_SCALE_ARCSEC = 0.6
SOLAR_RADIUS_ARCSEC = 976.0
SOLAR_RADIUS_PIX = SOLAR_RADIUS_ARCSEC / AIA_PIXEL_SCALE_ARCSEC
CROP_SCALE = 1.2
CROP_PADDING_PIX = 30
MIN_CROP_PIX = 64

# JSOC queue protection
JSOC_MAX_RETRIES = 10
JSOC_INITIAL_BACKOFF_SEC = 20
JSOC_MAX_BACKOFF_SEC = 300
JSOC_WAIT_TIMEOUT_SEC = 7200
JSOC_COOLDOWN_SEC = 12

# Runtime limits
MAX_BLOCKS_THIS_RUN = (
    int(os.environ["MAX_BLOCKS_THIS_RUN"])
    if os.environ.get("MAX_BLOCKS_THIS_RUN")
    else (1 if RUN_MODE == "BLOCK_CANARY" else None)
)
MIN_FREE_DISK_GB = 15

# The canary block is chosen around a previously successful individual sample.
CANARY_SAMPLE_IDS = {
    2025: [
        "20250602_1348_HARP13299_NOAA14100",
        "20250628_2248_HARP13424_NOAA14122",
    ],
    2026: [
        "20260210_0400_HARP14361_NOAA14370",
        "20260211_1648_HARP14371_NOAA14373",
    ],
}

BASE = Path.home() / "solar_flare_aia"
LOCAL_ROOT = BASE / "harp_block_miner" / f"{RUN_MODE.lower()}_{WORKER_ID}"
LOCAL_META = LOCAL_ROOT / "metadata"
LOCAL_TEMP = LOCAL_ROOT / "temp_blocks"
LOCAL_OUTPUT = LOCAL_ROOT / "samples_npz"
LOCAL_LOG = LOCAL_META / f"sample_log_{WORKER_ID}.csv"
LOCAL_BLOCK_LOG = LOCAL_META / f"block_log_{WORKER_ID}.csv"
LOCAL_BLOCK_PLAN = LOCAL_META / f"block_plan_{WORKER_ID}.csv"

for directory in [LOCAL_ROOT, LOCAL_META, LOCAL_TEMP, LOCAL_OUTPUT]:
    directory.mkdir(parents=True, exist_ok=True)

if RUN_MODE == "BLOCK_CANARY":
    GCP_RUN_ROOT = f"{GCP_BUCKET}/jsoc_harp_block_canary_v1/{WORKER_ID}"
else:
    GCP_RUN_ROOT = f"{GCP_BUCKET}/jsoc_2025_2026_production_v1"

GCP_OUTPUT_ROOT = f"{GCP_RUN_ROOT}/samples_npz/{TARGET_YEAR}"
GCP_WORKER_META = f"{GCP_RUN_ROOT}/metadata/workers/{WORKER_ID}"

GCP_METADATA_CANDIDATES = [
    f"{GCP_BUCKET}/metadata/curated_sharp_suryabench_true96min_48h_AR_SPECIFIC_2010_2026.csv",
    f"{GCP_BUCKET}/metadata/curated_2025_2026_AR_SPECIFIC_EXTENSION.csv",
]

PILOT_GCP_ROOT = (
    f"{GCP_BUCKET}/jsoc_2025_2026_pilot/samples_npz/{TARGET_YEAR}"
)

print("=" * 80)
print("TARGET_YEAR:", TARGET_YEAR)
print("JSOC_EMAIL:", JSOC_EMAIL)
print("WORKER_ID:", WORKER_ID)
print("RUN_MODE:", RUN_MODE)
print("MAX_BLOCKS_THIS_RUN:", MAX_BLOCKS_THIS_RUN)
print("LOCAL_ROOT:", LOCAL_ROOT)
print("GCP_OUTPUT_ROOT:", GCP_OUTPUT_ROOT)
print("=" * 80)

================================================================================
TARGET_YEAR: 2026
JSOC_EMAIL: worky4work@gmail.com
WORKER_ID: aia2026
RUN_MODE: PRODUCTION
MAX_BLOCKS_THIS_RUN: None
LOCAL_ROOT: /home/abmoses2000/solar_flare_aia/harp_block_miner/production_aia2026
GCP_OUTPUT_ROOT: gs://suryabench-sharp-pipeline-bamidele/jsoc_2025_2026_production_v1/samples_npz/2026
================================================================================

## 2. Cloud and JSOC preflight

In [4]:

def run_command(command, check=True, capture=True):
    result = subprocess.run(
        command,
        text=True,
        capture_output=capture,
    )
    if check and result.returncode != 0:
        raise RuntimeError(
            f"Command failed ({result.returncode}): {' '.join(command)}\n"
            f"{result.stderr[-3000:] if result.stderr else ''}"
        )
    return result


def gcp_exists(path):
    return run_command(
        ["gcloud", "storage", "ls", path],
        check=False,
    ).returncode == 0


print("Bucket access:")
bucket_test = run_command(
    ["gcloud", "storage", "ls", GCP_BUCKET],
    check=True,
)
print(bucket_test.stdout[:1000])
print("✅ Bucket access works.")

jsoc_public = drms.Client()
registered = jsoc_public.check_email(JSOC_EMAIL)
print("JSOC registered:", registered, "|", JSOC_EMAIL)
if not registered:
    raise RuntimeError(f"JSOC email is not registered: {JSOC_EMAIL}")

jsoc = drms.Client(email=JSOC_EMAIL)
assert jsoc.email == JSOC_EMAIL
print("✅ JSOC client is using the intended email.")

Bucket access:

gs://suryabench-sharp-pipeline-bamidele/baseline_results/
gs://suryabench-sharp-pipeline-bamidele/jsoc_2025_2026_canary/
gs://suryabench-sharp-pipeline-bamidele/jsoc_2025_2026_pilot/
gs://suryabench-sharp-pipeline-bamidele/jsoc_2025_2026_production_v1/
gs://suryabench-sharp-pipeline-bamidele/jsoc_2026_canary_parallel/
gs://suryabench-sharp-pipeline-bamidele/jsoc_harp_block_canary_v1/
gs://suryabench-sharp-pipeline-bamidele/manifests/
gs://suryabench-sharp-pipeline-bamidele/metadata/
gs://suryabench-sharp-pipeline-bamidele/samples_npz/

✅ Bucket access works.

JSOC registered: True | worky4work@gmail.com

✅ JSOC client is using the intended email.

## 3. Load and validate corrected AR-specific metadata

In [5]:

def copy_first_existing(candidates, destination):
    for candidate in candidates:
        print("Checking:", candidate)
        if not gcp_exists(candidate):
            continue
        run_command(
            ["gcloud", "storage", "cp", candidate, str(destination)],
            check=True,
        )
        if destination.exists() and destination.stat().st_size > 0:
            print("✅ Copied:", candidate)
            return candidate
    raise FileNotFoundError("No compatible corrected metadata file was found.")


metadata_path = LOCAL_META / "corrected_ar_specific_metadata.csv"
metadata_source = copy_first_existing(
    GCP_METADATA_CANDIDATES,
    metadata_path,
)

raw_df = pd.read_csv(metadata_path, low_memory=False)
print("Raw metadata:", raw_df.shape)

Checking: gs://suryabench-sharp-pipeline-bamidele/metadata/curated_sharp_suryabench_true96min_48h_AR_SPECIFIC_2010_2026.csv

✅ Copied: gs://suryabench-sharp-pipeline-bamidele/metadata/curated_sharp_suryabench_true96min_48h_AR_SPECIFIC_2010_2026.csv

Raw metadata: (141644, 50)

In [6]:

def clean_noaa(value):
    if pd.isna(value):
        return np.nan
    try:
        number = int(float(value))
        return number if number > 0 else np.nan
    except Exception:
        matches = re.findall(r"\d+", str(value))
        return int(matches[0]) if matches else np.nan


def prepare_metadata(frame):
    frame = frame.copy()

    frame["T_REC_dt"] = pd.to_datetime(
        frame["T_REC_dt"],
        errors="coerce",
    )

    if "NOAA_AR_clean" not in frame.columns:
        source = "NOAA_ARS" if "NOAA_ARS" in frame.columns else "NOAA_AR"
        frame["NOAA_AR_clean"] = frame[source].apply(clean_noaa)

    label_source = next(
        (
            column
            for column in [
                "label_48h_final",
                "label_48h_ar_specific",
                "label_48h",
            ]
            if column in frame.columns
        ),
        None,
    )
    if label_source is None:
        raise ValueError("No AR-specific 48-hour label column exists.")

    frame["label_48h_final"] = pd.to_numeric(
        frame[label_source],
        errors="coerce",
    )
    frame["HARPNUM"] = pd.to_numeric(frame["HARPNUM"], errors="coerce")
    frame["NOAA_AR_clean"] = pd.to_numeric(
        frame["NOAA_AR_clean"],
        errors="coerce",
    )

    required = [
        "T_REC_dt", "HARPNUM", "NOAA_AR_clean", "label_48h_final",
        "LON_MIN", "LON_MAX", "LAT_MIN", "LAT_MAX",
    ]
    missing = [column for column in required if column not in frame.columns]
    if missing:
        raise ValueError(f"Missing required columns: {missing}")

    frame = frame.dropna(subset=required).copy()
    frame["HARPNUM"] = frame["HARPNUM"].astype(int)
    frame["NOAA_AR_clean"] = frame["NOAA_AR_clean"].astype(int)
    frame["label_48h_final"] = frame["label_48h_final"].astype(int)

    if "sample_id" not in frame.columns:
        frame["sample_id"] = frame.apply(
            lambda row: (
                f"{row['T_REC_dt'].strftime('%Y%m%d_%H%M')}"
                f"_HARP{row['HARPNUM']}"
                f"_NOAA{row['NOAA_AR_clean']}"
            ),
            axis=1,
        )

    frame["year"] = frame["T_REC_dt"].dt.year
    frame = frame[frame["year"] == TARGET_YEAR].copy()

    # 2026 rows in the source file were already created using a safe
    # complete-future-window cutoff. Preserve that curated selection.
    frame = (
        frame.drop_duplicates("sample_id")
        .sort_values(["HARPNUM", "T_REC_dt"])
        .reset_index(drop=True)
    )

    return frame


df = prepare_metadata(raw_df)

print("Prepared rows:", len(df))
print(df["label_48h_final"].value_counts().sort_index())
print("Unique HARPs:", df["HARPNUM"].nunique())

expected_rows = 14774 if TARGET_YEAR == 2025 else 3201
if len(df) != expected_rows:
    raise RuntimeError(
        f"Expected {expected_rows} curated rows for {TARGET_YEAR}, "
        f"but found {len(df)}."
    )

print("✅ Metadata count matches the curated year total.")

Prepared rows: 3201
label_48h_final
0    3023
1     178
Name: count, dtype: int64
Unique HARPs: 56
✅ Metadata count matches the curated year total.

## 4. Geometry and preprocessing

In [7]:

def lonlat_to_pixel(lon_deg, lat_deg):
    lon = np.deg2rad(float(lon_deg))
    lat = np.deg2rad(float(lat_deg))
    x = IMAGE_CENTER + SOLAR_RADIUS_PIX * np.cos(lat) * np.sin(lon)
    y = IMAGE_CENTER - SOLAR_RADIUS_PIX * np.sin(lat)
    return float(x), float(y)


def target_geometry(row):
    corners = [
        (row["LON_MIN"], row["LAT_MIN"]),
        (row["LON_MIN"], row["LAT_MAX"]),
        (row["LON_MAX"], row["LAT_MIN"]),
        (row["LON_MAX"], row["LAT_MAX"]),
    ]
    pixels = [lonlat_to_pixel(lon, lat) for lon, lat in corners]
    xs = [item[0] for item in pixels]
    ys = [item[1] for item in pixels]

    center_x_pix = (min(xs) + max(xs)) / 2.0
    center_y_pix = (min(ys) + max(ys)) / 2.0

    width_pix = max(max(xs) - min(xs), MIN_CROP_PIX)
    height_pix = max(max(ys) - min(ys), MIN_CROP_PIX)
    crop_pix = max(width_pix, height_pix) * CROP_SCALE + CROP_PADDING_PIX

    return {
        "x_arcsec": (center_x_pix - IMAGE_CENTER) * AIA_PIXEL_SCALE_ARCSEC,
        "y_arcsec": (IMAGE_CENTER - center_y_pix) * AIA_PIXEL_SCALE_ARCSEC,
        "box_arcsec": crop_pix * AIA_PIXEL_SCALE_ARCSEC,
    }


def historical_preprocess(image):
    image = np.asarray(image, dtype=np.float32)
    image = np.nan_to_num(image, nan=0.0, posinf=0.0, neginf=0.0)
    image = np.clip(image, 0, None)
    image = np.log1p(image)

    low = float(image.min())
    high = float(image.max())
    if high <= low:
        return np.zeros_like(image, dtype=np.float32)

    return ((image - low) / (high - low)).astype(np.float32)


def read_map(path):
    solar_map = sunpy.map.Map(path)
    data = np.asarray(solar_map.data, dtype=np.float32)
    return solar_map, data


def crop_target_from_block(fits_path, row):
    solar_map, data = read_map(fits_path)
    geometry = target_geometry(row)

    coordinate = SkyCoord(
        geometry["x_arcsec"] * u.arcsec,
        geometry["y_arcsec"] * u.arcsec,
        frame=solar_map.coordinate_frame,
    )
    pixel = solar_map.world_to_pixel(coordinate)
    center_x = float(pixel.x.value)
    center_y = float(pixel.y.value)

    scale_x = abs(float(solar_map.scale.axis1.to_value(u.arcsec / u.pix)))
    scale_y = abs(float(solar_map.scale.axis2.to_value(u.arcsec / u.pix)))
    half_width = geometry["box_arcsec"] / (2.0 * scale_x)
    half_height = geometry["box_arcsec"] / (2.0 * scale_y)

    x0 = int(math.floor(center_x - half_width))
    x1 = int(math.ceil(center_x + half_width))
    y0 = int(math.floor(center_y - half_height))
    y1 = int(math.ceil(center_y + half_height))

    if x0 < 0 or y0 < 0 or x1 > data.shape[1] or y1 > data.shape[0]:
        raise ValueError(
            f"Target crop leaves block patch: "
            f"bounds={(x0, x1, y0, y1)}, shape={data.shape}"
        )

    crop = data[y0:y1, x0:x1]
    if crop.size == 0:
        raise ValueError("Empty local crop.")

    resized = resize(
        crop,
        (IMAGE_SIZE, IMAGE_SIZE),
        anti_aliasing=True,
        preserve_range=True,
    )
    return historical_preprocess(resized), {
        "block_shape": list(data.shape),
        "local_bounds": [x0, x1, y0, y1],
        "target_geometry": geometry,
    }


print("✅ Geometry and preprocessing functions ready.")

✅ Geometry and preprocessing functions ready.

## 5. Create HARP/time blocks

In [8]:

def make_blocks(frame, block_hours=24):
    blocks = []

    for harpnum, group in frame.groupby("HARPNUM"):
        group = group.sort_values("T_REC_dt").copy()
        current_indices = []
        block_start = None
        previous_time = None

        for index, row in group.iterrows():
            timestamp = pd.Timestamp(row["T_REC_dt"])

            must_split = False
            if block_start is not None:
                elapsed_hours = (
                    timestamp - block_start
                ).total_seconds() / 3600.0

                gap_seconds = (
                    timestamp - previous_time
                ).total_seconds()

                must_split = (
                    elapsed_hours >= block_hours
                    or gap_seconds > MAX_GAP_WITHIN_TRACK_SEC
                )

            if must_split and current_indices:
                blocks.append(group.loc[current_indices].copy())
                current_indices = []
                block_start = None

            if block_start is None:
                block_start = timestamp

            current_indices.append(index)
            previous_time = timestamp

        if current_indices:
            blocks.append(group.loc[current_indices].copy())

    plan_rows = []
    block_frames = {}

    for number, block in enumerate(blocks):
        first = block["T_REC_dt"].min()
        last = block["T_REC_dt"].max()
        harpnum = int(block["HARPNUM"].iloc[0])
        block_id = (
            f"{TARGET_YEAR}_HARP{harpnum}_"
            f"{first.strftime('%Y%m%d_%H%M')}_"
            f"{last.strftime('%Y%m%d_%H%M')}"
        )

        block_frames[block_id] = block.reset_index(drop=True)
        plan_rows.append(
            {
                "block_id": block_id,
                "HARPNUM": harpnum,
                "start": first,
                "end": last,
                "n_targets": len(block),
                "n_positive": int(block["label_48h_final"].sum()),
            }
        )

    return pd.DataFrame(plan_rows), block_frames


block_plan, block_frames = make_blocks(df, BLOCK_HOURS)

if RUN_MODE == "BLOCK_CANARY":
    wanted_ids = set(CANARY_SAMPLE_IDS[TARGET_YEAR])
    canary_block_ids = []

    for block_id, block in block_frames.items():
        if set(block["sample_id"]).intersection(wanted_ids):
            canary_block_ids.append(block_id)

    if not canary_block_ids:
        raise RuntimeError("No block contains the configured canary samples.")

    block_plan = block_plan[
        block_plan["block_id"].isin(canary_block_ids)
    ].copy()

block_plan = block_plan.sort_values(
    ["start", "HARPNUM"]
).reset_index(drop=True)

block_plan.to_csv(LOCAL_BLOCK_PLAN, index=False)
run_command(
    [
        "gcloud", "storage", "cp",
        str(LOCAL_BLOCK_PLAN),
        f"{GCP_WORKER_META}/{LOCAL_BLOCK_PLAN.name}",
    ],
    check=True,
)

print("Blocks selected:", len(block_plan))
print("Targets represented:", int(block_plan["n_targets"].sum()))
display(block_plan.head(20))

Blocks selected: 336
Targets represented: 3201

,block_id,HARPNUM,start,end,n_targets,n_positive
0,2026_HARP14215_20260101_0024_20260101_1624,14215,2026-01-01 00:24:00,2026-01-01 16:24:00,11,0
1,2026_HARP14220_20260101_0036_20260101_1012,14220,2026-01-01 00:36:00,2026-01-01 10:12:00,7,0
2,2026_HARP14239_20260101_0100_20260101_2324,14239,2026-01-01 01:00:00,2026-01-01 23:24:00,15,0
3,2026_HARP14220_20260101_1324_20260102_1148,14220,2026-01-01 13:24:00,2026-01-02 11:48:00,15,0
4,2026_HARP14215_20260101_1936_20260102_1624,14215,2026-01-01 19:36:00,2026-01-02 16:24:00,14,0
5,2026_HARP14228_20260102_0012_20260102_2236,14228,2026-01-02 00:12:00,2026-01-02 22:36:00,15,0
6,2026_HARP14239_20260102_0100_20260102_2324,14239,2026-01-02 01:00:00,2026-01-02 23:24:00,15,0
7,2026_HARP14246_20260102_1100_20260103_0748,14246,2026-01-02 11:00:00,2026-01-03 07:48:00,14,0
8,2026_HARP14220_20260102_1324_20260103_0836,14220,2026-01-02 13:24:00,2026-01-03 08:36:00,13,0
9,2026_HARP14215_20260102_1936_20260103_0824,14215,2026-01-02 19:36:00,2026-01-03 08:24:00,9,0
10,2026_HARP14228_20260103_0012_20260103_0812,14228,2026-01-03 00:12:00,2026-01-03 08:12:00,6,0
11,2026_HARP14245_20260103_0036_20260103_0836,14245,2026-01-03 00:36:00,2026-01-03 08:36:00,6,0
12,2026_HARP14239_20260103_0100_20260103_0724,14239,2026-01-03 01:00:00,2026-01-03 07:24:00,5,0
13,2026_HARP14239_20260103_1924_20260104_1748,14239,2026-01-03 19:24:00,2026-01-04 17:48:00,15,0
14,2026_HARP14246_20260103_1948_20260104_1812,14246,2026-01-03 19:48:00,2026-01-04 18:12:00,15,0
15,2026_HARP14228_20260103_2012_20260104_1836,14228,2026-01-03 20:12:00,2026-01-04 18:36:00,15,0
16,2026_HARP14215_20260103_2024_20260103_2336,14215,2026-01-03 20:24:00,2026-01-03 23:36:00,3,0
17,2026_HARP14220_20260103_2036_20260104_0436,14220,2026-01-03 20:36:00,2026-01-04 04:36:00,6,0
18,2026_HARP14245_20260103_2036_20260104_1900,14245,2026-01-03 20:36:00,2026-01-04 19:00:00,15,0
19,2026_HARP14239_20260104_1924_20260105_0948,14239,2026-01-04 19:24:00,2026-01-05 09:48:00,10,0

## 6. Discover completed outputs and restore checkpoints

In [9]:

def download_if_exists(gcp_path, local_path):
    if not gcp_exists(gcp_path):
        return False
    run_command(
        ["gcloud", "storage", "cp", gcp_path, str(local_path)],
        check=True,
    )
    return True


download_if_exists(
    f"{GCP_WORKER_META}/{LOCAL_LOG.name}",
    LOCAL_LOG,
)
download_if_exists(
    f"{GCP_WORKER_META}/{LOCAL_BLOCK_LOG.name}",
    LOCAL_BLOCK_LOG,
)

sample_log = (
    pd.read_csv(LOCAL_LOG, low_memory=False)
    if LOCAL_LOG.exists() and LOCAL_LOG.stat().st_size > 0
    else pd.DataFrame()
)
block_log = (
    pd.read_csv(LOCAL_BLOCK_LOG, low_memory=False)
    if LOCAL_BLOCK_LOG.exists() and LOCAL_BLOCK_LOG.stat().st_size > 0
    else pd.DataFrame()
)

# The object listing is the source of truth for completed model-ready files.
listing = run_command(
    ["gcloud", "storage", "ls", "--recursive", GCP_OUTPUT_ROOT],
    check=False,
)
completed_sample_ids = {
    Path(line.strip()).stem
    for line in listing.stdout.splitlines()
    if line.strip().endswith(".npz")
}

print("Completed GCP samples already present:", len(completed_sample_ids))
print("Sample log rows:", len(sample_log))
print("Block log rows:", len(block_log))

Completed GCP samples already present: 2939
Sample log rows: 2984
Block log rows: 336

## 7. Retry-safe JSOC block export

## v2 cadence-phase fix
This version detects multiple 96-minute cadence phases inside one HARP block, reuses any compatible cached FITS files, and submits extra sequence exports only for uncovered timestamp phases.

In [10]:

def parse_jsoc_time(value):
    try:
        return pd.Timestamp(drms.to_datetime(str(value)))
    except Exception:
        text = str(value).replace("_TAI", "").replace("Z", "")
        return pd.to_datetime(text, errors="coerce")


def extract_request_id(message):
    match = re.search(r"(JSOC_\d{8}_\d+)", str(message))
    return match.group(1) if match else None


def wait_for_existing_request(request_id):
    print("Waiting for existing RequestID:", request_id)
    old_request = jsoc.export_from_id(request_id)
    old_request.wait(
        timeout=JSOC_WAIT_TIMEOUT_SEC,
        sleep=15,
        retries_notfound=30,
    )
    print(
        "Existing request status:",
        old_request.status,
        "succeeded:",
        old_request.has_succeeded(),
    )


def submit_export_retry_safe(query_string, process):
    delay = JSOC_INITIAL_BACKOFF_SEC
    last_error = None

    for attempt in range(1, JSOC_MAX_RETRIES + 1):
        try:
            print(
                f"JSOC export attempt {attempt}/{JSOC_MAX_RETRIES}"
            )
            request = jsoc.export(
                query_string,
                method="url",
                protocol="fits",
                email=JSOC_EMAIL,
                process=process,
            )
            request.wait(
                timeout=JSOC_WAIT_TIMEOUT_SEC,
                sleep=15,
                retries_notfound=30,
            )

            if not request.has_succeeded():
                raise RuntimeError(
                    f"Request failed: id={request.id}, "
                    f"status={request.status}"
                )
            return request

        except DrmsExportError as error:
            last_error = error
            message = str(error)

            if "pending export requests" not in message.lower():
                raise

            request_id = extract_request_id(message)
            print("JSOC pending-request protection triggered.")
            print(message)

            if request_id:
                try:
                    wait_for_existing_request(request_id)
                except Exception as wait_error:
                    print("Could not reopen old request:", repr(wait_error))

            print(f"Sleeping {delay} seconds...")
            time.sleep(delay)
            delay = min(delay * 2, JSOC_MAX_BACKOFF_SEC)

    raise RuntimeError(
        f"JSOC remained busy after all retries: {last_error}"
    )


def format_query_time(timestamp):
    return pd.Timestamp(timestamp).strftime("%Y-%m-%dT%H:%M:%S.000")


def split_block_into_cadence_segments(block):
    """Split a HARP block when target times change cadence phase."""
    block = block.sort_values("T_REC_dt").reset_index(drop=True).copy()
    cadence_seconds = TARGET_CADENCE_MIN * 60
    segments = []
    current_rows = [0]

    for position in range(1, len(block)):
        previous_time = pd.Timestamp(block.loc[position - 1, "T_REC_dt"])
        current_time = pd.Timestamp(block.loc[position, "T_REC_dt"])
        gap_seconds = (current_time - previous_time).total_seconds()
        cadence_steps = max(1, int(round(gap_seconds / cadence_seconds)))
        phase_error_seconds = abs(gap_seconds - cadence_steps * cadence_seconds)

        if phase_error_seconds > MAX_TARGET_TIME_DIFFERENCE_SEC:
            segments.append(block.loc[current_rows].copy())
            current_rows = [position]
        else:
            current_rows.append(position)

    if current_rows:
        segments.append(block.loc[current_rows].copy())

    return [segment.reset_index(drop=True) for segment in segments]


def files_cover_targets(files, target_frame):
    """Check that every target has a FITS file within the time tolerance."""
    files = [Path(item) for item in files if str(item).lower().endswith(".fits")]
    if not files:
        return False

    try:
        indexed = index_downloaded_files(files)
    except Exception:
        return False

    available_times = [item[0] for item in indexed]
    for target in pd.to_datetime(target_frame["T_REC_dt"]):
        nearest_delta = min(
            abs((timestamp - pd.Timestamp(target)).total_seconds())
            for timestamp in available_times
        )
        if nearest_delta > MAX_TARGET_TIME_DIFFERENCE_SEC:
            return False
    return True


def build_segment_export(segment, wavelength, segment_directory):
    segment_directory.mkdir(parents=True, exist_ok=True)
    metadata_json = segment_directory / "export_metadata.json"

    for partial in segment_directory.glob("*.part"):
        partial.unlink(missing_ok=True)

    existing_fits = sorted(segment_directory.glob("*.fits"))
    if metadata_json.exists() and existing_fits and files_cover_targets(existing_fits, segment):
        with metadata_json.open() as handle:
            saved = json.load(handle)
        print(f"♻️ Reusing {len(existing_fits)} cadence-aligned files for {wavelength} Å")
        return existing_fits, saved

    segment = segment.sort_values("T_REC_dt").reset_index(drop=True)
    start = pd.Timestamp(segment["T_REC_dt"].min())
    end = pd.Timestamp(segment["T_REC_dt"].max())
    duration_minutes = max(
        TARGET_CADENCE_MIN,
        int(math.ceil((end - start).total_seconds() / 60.0)) + TARGET_CADENCE_MIN,
    )

    reference_time = start + (end - start) / 2
    reference_index = (segment["T_REC_dt"] - reference_time).abs().idxmin()
    reference_row = segment.loc[reference_index]
    reference_geometry = target_geometry(reference_row)

    max_target_box = max(target_geometry(row)["box_arcsec"] for _, row in segment.iterrows())
    patch_size = np.clip(
        max_target_box + BLOCK_PATCH_MARGIN_ARCSEC,
        MIN_BLOCK_PATCH_ARCSEC,
        MAX_BLOCK_PATCH_ARCSEC,
    )

    query_string = (
        f"aia.lev1_euv_12s"
        f"[{format_query_time(start)}/{duration_minutes}m@{TARGET_CADENCE_MIN}m]"
        f"[{int(wavelength)}]"
        f"{{image}}"
    )

    process = {
        "im_patch": {
            "t_ref": format_query_time(reference_time),
            "t": 0,
            "r": 0,
            "c": 0,
            "locunits": "arcsec",
            "boxunits": "arcsec",
            "x": reference_geometry["x_arcsec"],
            "y": reference_geometry["y_arcsec"],
            "width": float(patch_size),
            "height": float(patch_size),
        }
    }

    print("Segment query:", query_string)
    print("Segment reference:", reference_time, "| targets:", len(segment), "| patch arcsec:", float(patch_size))

    request = submit_export_retry_safe(query_string, process)
    request.download(segment_directory, timeout=600)

    fits_files = sorted(segment_directory.glob("*.fits"))
    if not fits_files:
        raise FileNotFoundError(f"No FITS files downloaded for {wavelength} Å segment.")
    if not files_cover_targets(fits_files, segment):
        raise RuntimeError(
            f"Downloaded {wavelength} Å segment does not cover all target timestamps within "
            f"{MAX_TARGET_TIME_DIFFERENCE_SEC} seconds."
        )

    metadata = {
        "request_id": request.id,
        "query": query_string,
        "wavelength": int(wavelength),
        "reference_time": str(reference_time),
        "segment_start": str(start),
        "segment_end": str(end),
        "segment_targets": int(len(segment)),
        "patch_size_arcsec": float(patch_size),
        "reference_geometry": reference_geometry,
        "n_files": len(fits_files),
        "email": JSOC_EMAIL,
    }
    with metadata_json.open("w") as handle:
        json.dump(metadata, handle, indent=2)

    time.sleep(JSOC_COOLDOWN_SEC)
    return fits_files, metadata


def build_block_export(block, wavelength, block_directory):
    """Export one or more cadence-aligned sequences for a HARP block."""
    block_directory.mkdir(parents=True, exist_ok=True)
    wave_directory = block_directory / str(wavelength)
    wave_directory.mkdir(parents=True, exist_ok=True)

    segments = split_block_into_cadence_segments(block)
    print(
        f"{wavelength} Å cadence segments:",
        len(segments),
        [(str(s["T_REC_dt"].min()), str(s["T_REC_dt"].max()), len(s)) for s in segments],
    )

    request_ids = []
    for segment_number, segment in enumerate(segments, start=1):
        cached_files = sorted(wave_directory.rglob("*.fits"))
        if files_cover_targets(cached_files, segment):
            print(
                f"♻️ Segment {segment_number}/{len(segments)} already covered by cached "
                f"{wavelength} Å files."
            )
            continue

        start = pd.Timestamp(segment["T_REC_dt"].min())
        end = pd.Timestamp(segment["T_REC_dt"].max())
        segment_name = (
            f"segment_{segment_number:02d}_"
            f"{start.strftime('%Y%m%d_%H%M')}_"
            f"{end.strftime('%Y%m%d_%H%M')}"
        )
        segment_directory = wave_directory / segment_name
        _, segment_metadata = build_segment_export(segment, wavelength, segment_directory)
        request_ids.append(str(segment_metadata["request_id"]))

    all_fits = sorted(wave_directory.rglob("*.fits"))
    if not all_fits:
        raise FileNotFoundError(f"No complete FITS files available for {wavelength} Å.")

    if not files_cover_targets(all_fits, block):
        uncovered = []
        indexed = index_downloaded_files(all_fits)
        available_times = [item[0] for item in indexed]
        for target in pd.to_datetime(block["T_REC_dt"]):
            nearest_delta = min(
                abs((timestamp - pd.Timestamp(target)).total_seconds())
                for timestamp in available_times
            )
            if nearest_delta > MAX_TARGET_TIME_DIFFERENCE_SEC:
                uncovered.append({
                    "target": str(target),
                    "nearest_delta_seconds": float(nearest_delta),
                })
        raise RuntimeError(f"{wavelength} Å block remains incompletely covered: {uncovered[:10]}")

    for metadata_path in wave_directory.rglob("export_metadata.json"):
        try:
            with metadata_path.open() as handle:
                item = json.load(handle)
            request_id = item.get("request_id")
            if request_id:
                request_ids.append(str(request_id))
        except Exception:
            pass

    request_ids = sorted(set(request_ids))
    combined_metadata = {
        "request_id": ",".join(request_ids) if request_ids else "cached",
        "request_ids": request_ids,
        "wavelength": int(wavelength),
        "n_segments": int(len(segments)),
        "n_files": int(len(all_fits)),
        "coverage_verified": True,
        "max_time_difference_seconds": int(MAX_TARGET_TIME_DIFFERENCE_SEC),
        "email": JSOC_EMAIL,
    }
    return all_fits, combined_metadata


def fits_observation_time(path):
    with fits.open(path, memmap=False) as hdul:
        headers = [
            hdu.header
            for hdu in hdul
            if getattr(hdu, "header", None) is not None
        ]

    for header in headers:
        for key in ["T_REC", "DATE-OBS", "DATE_OBS", "T_OBS"]:
            if key in header:
                parsed = parse_jsoc_time(header[key])
                if not pd.isna(parsed):
                    return pd.Timestamp(parsed)

    raise ValueError(f"No observation time found in {path}")


def index_downloaded_files(files):
    indexed = []
    for path in files:
        try:
            timestamp = fits_observation_time(path)
            indexed.append((timestamp, path))
        except Exception as error:
            print("Skipping unreadable FITS time:", path, repr(error))

    if not indexed:
        raise RuntimeError("No downloaded FITS file has a valid timestamp.")

    return sorted(indexed, key=lambda item: item[0])


def nearest_file(indexed_files, target_time):
    target_time = pd.Timestamp(target_time)
    timestamp, path = min(
        indexed_files,
        key=lambda item: abs((item[0] - target_time).total_seconds()),
    )
    difference = abs((timestamp - target_time).total_seconds())

    if difference > MAX_TARGET_TIME_DIFFERENCE_SEC:
        raise ValueError(
            f"Nearest AIA file is {difference:.1f}s from target "
            f"{target_time}."
        )

    return path, timestamp, float(difference)

## 8. Save, upload and checkpoint model-ready samples

In [11]:

def free_disk_gb(path):
    usage = shutil.disk_usage(path)
    return usage.free / (1024 ** 3)


def upload_verified(local_path, gcp_path):
    run_command(
        ["gcloud", "storage", "cp", str(local_path), gcp_path],
        check=True,
    )
    if not gcp_exists(gcp_path):
        raise RuntimeError(f"Upload verification failed: {gcp_path}")


def append_checkpoint(frame, row, local_path, gcp_path):
    updated = pd.concat(
        [frame, pd.DataFrame([row])],
        ignore_index=True,
    )
    updated = updated.drop_duplicates(
        subset=["sample_id"],
        keep="last",
    )
    updated.to_csv(local_path, index=False)
    run_command(
        ["gcloud", "storage", "cp", str(local_path), gcp_path],
        check=True,
    )
    return updated


def append_block_checkpoint(frame, row):
    updated = pd.concat(
        [frame, pd.DataFrame([row])],
        ignore_index=True,
    )
    updated = updated.drop_duplicates(
        subset=["block_id"],
        keep="last",
    )
    updated.to_csv(LOCAL_BLOCK_LOG, index=False)
    run_command(
        [
            "gcloud", "storage", "cp",
            str(LOCAL_BLOCK_LOG),
            f"{GCP_WORKER_META}/{LOCAL_BLOCK_LOG.name}",
        ],
        check=True,
    )
    return updated


def process_block(block_id, block, sample_log):
    block_started = time.time()
    block_directory = LOCAL_TEMP / block_id
    block_directory.mkdir(parents=True, exist_ok=True)

    pending = block[
        ~block["sample_id"].isin(completed_sample_ids)
    ].copy()

    if len(pending) == 0:
        return sample_log, {
            "block_id": block_id,
            "status": "already_complete",
            "n_targets": len(block),
            "n_saved_this_run": 0,
            "elapsed_minutes": 0.0,
            "message": "all_samples_already_in_gcp",
        }

    if free_disk_gb(LOCAL_ROOT) < MIN_FREE_DISK_GB:
        raise RuntimeError(
            f"Free disk below {MIN_FREE_DISK_GB} GB."
        )

    wavelength_indices = {}
    wavelength_export_meta = {}

    for wavelength in AIA_WAVELENGTHS:
        print("\n" + "-" * 70)
        print(block_id, "| wavelength", wavelength)
        files, export_meta = build_block_export(
            block,
            wavelength,
            block_directory,
        )
        wavelength_indices[wavelength] = index_downloaded_files(files)
        wavelength_export_meta[wavelength] = export_meta

    saved_this_block = 0

    for _, row in pending.iterrows():
        sample_id = str(row["sample_id"])
        target_time = pd.Timestamp(row["T_REC_dt"])
        channels = []
        channel_meta = {}

        try:
            for wavelength in AIA_WAVELENGTHS:
                path, used_time, delta_seconds = nearest_file(
                    wavelength_indices[wavelength],
                    target_time,
                )
                channel, crop_meta = crop_target_from_block(path, row)
                channels.append(channel)

                channel_meta[str(wavelength)] = {
                    "source_file": path.name,
                    "used_time": str(used_time),
                    "delta_seconds": delta_seconds,
                    "request_id": wavelength_export_meta[wavelength][
                        "request_id"
                    ],
                    "crop": crop_meta,
                }

            tensor = np.stack(channels, axis=-1).astype(np.float32)

            if tensor.shape != (IMAGE_SIZE, IMAGE_SIZE, 6):
                raise ValueError(f"Unexpected shape: {tensor.shape}")
            if not np.isfinite(tensor).all():
                raise ValueError("Tensor contains NaN or infinity.")

            year_directory = LOCAL_OUTPUT / str(TARGET_YEAR)
            year_directory.mkdir(parents=True, exist_ok=True)
            local_npz = year_directory / f"{sample_id}.npz"

            np.savez_compressed(
                local_npz,
                x=tensor,
                y=np.array(
                    int(row["label_48h_final"]),
                    dtype=np.int64,
                ),
                sample_id=np.array(sample_id),
                T_REC_dt=np.array(str(target_time)),
                HARPNUM=np.array(int(row["HARPNUM"]), dtype=np.int64),
                NOAA_AR_clean=np.array(
                    int(row["NOAA_AR_clean"]),
                    dtype=np.int64,
                ),
                label_48h_final=np.array(
                    int(row["label_48h_final"]),
                    dtype=np.int64,
                ),
                wavelengths=np.array(
                    AIA_WAVELENGTHS,
                    dtype=np.int64,
                ),
                source=np.array(
                    "JSOC HARP-block tracked im_patch + local WCS crop"
                ),
                block_id=np.array(block_id),
                channel_metadata=np.array(json.dumps(channel_meta)),
            )

            gcp_npz = f"{GCP_OUTPUT_ROOT}/{local_npz.name}"
            upload_verified(local_npz, gcp_npz)
            completed_sample_ids.add(sample_id)
            saved_this_block += 1

            sample_row = {
                "sample_id": sample_id,
                "block_id": block_id,
                "T_REC_dt": str(target_time),
                "HARPNUM": int(row["HARPNUM"]),
                "NOAA_AR_clean": int(row["NOAA_AR_clean"]),
                "label_48h_final": int(row["label_48h_final"]),
                "status": "saved",
                "shape": str(tensor.shape),
                "gcp_path": gcp_npz,
                "message": "success",
                "updated_at_utc": pd.Timestamp.utcnow().isoformat(),
            }

            sample_log = append_checkpoint(
                sample_log,
                sample_row,
                LOCAL_LOG,
                f"{GCP_WORKER_META}/{LOCAL_LOG.name}",
            )

            local_npz.unlink(missing_ok=True)
            print("✅", sample_id)

        except Exception as error:
            sample_row = {
                "sample_id": sample_id,
                "block_id": block_id,
                "T_REC_dt": str(target_time),
                "HARPNUM": int(row["HARPNUM"]),
                "NOAA_AR_clean": int(row["NOAA_AR_clean"]),
                "label_48h_final": int(row["label_48h_final"]),
                "status": "error",
                "shape": None,
                "gcp_path": None,
                "message": repr(error),
                "updated_at_utc": pd.Timestamp.utcnow().isoformat(),
            }

            sample_log = append_checkpoint(
                sample_log,
                sample_row,
                LOCAL_LOG,
                f"{GCP_WORKER_META}/{LOCAL_LOG.name}",
            )
            print("❌", sample_id, repr(error))

    # The whole block is retained only when a target failed, allowing reuse.
    current_errors = sample_log[
        (sample_log["block_id"] == block_id)
        & (sample_log["status"] == "error")
    ] if len(sample_log) else pd.DataFrame()

    if len(current_errors) == 0:
        shutil.rmtree(block_directory, ignore_errors=True)

    elapsed_minutes = (time.time() - block_started) / 60.0

    return sample_log, {
        "block_id": block_id,
        "status": "completed",
        "n_targets": len(block),
        "n_pending_at_start": len(pending),
        "n_saved_this_run": saved_this_block,
        "elapsed_minutes": round(elapsed_minutes, 3),
        "message": (
            "success"
            if len(current_errors) == 0
            else f"{len(current_errors)} sample errors retained for retry"
        ),
    }

## 9. Execute selected blocks

In [12]:

blocks_to_run = block_plan.copy()

if MAX_BLOCKS_THIS_RUN is not None:
    blocks_to_run = blocks_to_run.head(MAX_BLOCKS_THIS_RUN)

print("Blocks this run:", len(blocks_to_run))

for position, plan_row in blocks_to_run.iterrows():
    block_id = plan_row["block_id"]
    block = block_frames[block_id]

    print("\n" + "=" * 90)
    print(
        f"BLOCK {position + 1}/{len(blocks_to_run)} | "
        f"{block_id} | targets={len(block)}"
    )
    print("=" * 90)

    try:
        sample_log, block_result = process_block(
            block_id,
            block,
            sample_log,
        )
    except Exception as error:
        block_result = {
            "block_id": block_id,
            "status": "error",
            "n_targets": len(block),
            "n_pending_at_start": None,
            "n_saved_this_run": 0,
            "elapsed_minutes": None,
            "message": repr(error),
        }
        print("BLOCK ERROR:", repr(error))

    block_log = append_block_checkpoint(
        block_log,
        block_result,
    )
    display(pd.DataFrame([block_result]))

print("\nRun finished.")
print(
    "Completed model-ready objects now visible in GCP:",
    len(completed_sample_ids),
)

Blocks this run: 336

==========================================================================================
BLOCK 1/336 | 2026_HARP14215_20260101_0024_20260101_1624 | targets=11
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14215_20260101_0024_20260101_1624,already_complete,11,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 2/336 | 2026_HARP14220_20260101_0036_20260101_1012 | targets=7
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14220_20260101_0036_20260101_1012,already_complete,7,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 3/336 | 2026_HARP14239_20260101_0100_20260101_2324 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14239_20260101_0100_20260101_2324,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 4/336 | 2026_HARP14220_20260101_1324_20260102_1148 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14220_20260101_1324_20260102_1148,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 5/336 | 2026_HARP14215_20260101_1936_20260102_1624 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14215_20260101_1936_20260102_1624,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 6/336 | 2026_HARP14228_20260102_0012_20260102_2236 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14228_20260102_0012_20260102_2236,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 7/336 | 2026_HARP14239_20260102_0100_20260102_2324 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14239_20260102_0100_20260102_2324,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 8/336 | 2026_HARP14246_20260102_1100_20260103_0748 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14246_20260102_1100_20260103_0748,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 9/336 | 2026_HARP14220_20260102_1324_20260103_0836 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14220_20260102_1324_20260103_0836,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 10/336 | 2026_HARP14215_20260102_1936_20260103_0824 | targets=9
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14215_20260102_1936_20260103_0824,already_complete,9,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 11/336 | 2026_HARP14228_20260103_0012_20260103_0812 | targets=6
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14228_20260103_0012_20260103_0812,already_complete,6,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 12/336 | 2026_HARP14245_20260103_0036_20260103_0836 | targets=6
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14245_20260103_0036_20260103_0836,already_complete,6,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 13/336 | 2026_HARP14239_20260103_0100_20260103_0724 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14239_20260103_0100_20260103_0724,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 14/336 | 2026_HARP14239_20260103_1924_20260104_1748 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14239_20260103_1924_20260104_1748,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 15/336 | 2026_HARP14246_20260103_1948_20260104_1812 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14246_20260103_1948_20260104_1812,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 16/336 | 2026_HARP14228_20260103_2012_20260104_1836 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14228_20260103_2012_20260104_1836,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 17/336 | 2026_HARP14215_20260103_2024_20260103_2336 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14215_20260103_2024_20260103_2336,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 18/336 | 2026_HARP14220_20260103_2036_20260104_0436 | targets=6
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14220_20260103_2036_20260104_0436,already_complete,6,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 19/336 | 2026_HARP14245_20260103_2036_20260104_1900 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14245_20260103_2036_20260104_1900,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 20/336 | 2026_HARP14239_20260104_1924_20260105_0948 | targets=10
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14239_20260104_1924_20260105_0948,already_complete,10,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 21/336 | 2026_HARP14246_20260104_1948_20260105_1812 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14246_20260104_1948_20260105_1812,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 22/336 | 2026_HARP14228_20260104_2012_20260105_1836 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14228_20260104_2012_20260105_1836,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 23/336 | 2026_HARP14245_20260104_2036_20260104_2212 | targets=2
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14245_20260104_2036_20260104_2212,already_complete,2,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 24/336 | 2026_HARP14245_20260105_0124_20260105_0612 | targets=4
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14245_20260105_0124_20260105_0612,already_complete,4,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 25/336 | 2026_HARP14245_20260105_0924_20260105_1724 | targets=6
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14245_20260105_0924_20260105_1724,already_complete,6,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 26/336 | 2026_HARP14246_20260105_1948_20260106_1848 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14246_20260105_1948_20260106_1848,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 27/336 | 2026_HARP14228_20260105_2012_20260106_1424 | targets=12
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14228_20260105_2012_20260106_1424,already_complete,12,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 28/336 | 2026_HARP14245_20260105_2036_20260106_1624 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14245_20260105_2036_20260106_1624,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 29/336 | 2026_HARP14251_20260106_1524_20260106_1836 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14251_20260106_1524_20260106_1836,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 30/336 | 2026_HARP14245_20260106_2124_20260107_0700 | targets=7
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14245_20260106_2124_20260107_0700,already_complete,7,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 31/336 | 2026_HARP14251_20260106_2200_20260107_0424 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14251_20260106_2200_20260107_0424,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 32/336 | 2026_HARP14246_20260106_2212_20260107_0124 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14246_20260106_2212_20260107_0124,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 33/336 | 2026_HARP14245_20260107_1036_20260107_1212 | targets=2
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14245_20260107_1036_20260107_1212,already_complete,2,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 34/336 | 2026_HARP14251_20260107_1112_20260107_1248 | targets=2
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14251_20260107_1112_20260107_1248,already_complete,2,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 35/336 | 2026_HARP14251_20260107_1948_20260108_0524 | targets=7
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14251_20260107_1948_20260108_0524,already_complete,7,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 36/336 | 2026_HARP14251_20260108_0912_20260109_0424 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14251_20260108_0912_20260109_0424,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 37/336 | 2026_HARP14260_20260108_1900_20260109_0612 | targets=8
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14260_20260108_1900_20260109_0612,already_complete,8,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 38/336 | 2026_HARP14260_20260109_1000_20260109_1624 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14260_20260109_1000_20260109_1624,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 39/336 | 2026_HARP14251_20260109_1124_20260110_0636 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14251_20260109_1124_20260110_0636,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 40/336 | 2026_HARP14260_20260109_1936_20260110_0648 | targets=8
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14260_20260109_1936_20260110_0648,already_complete,8,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 41/336 | 2026_HARP14251_20260110_1024_20260111_0536 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14251_20260110_1024_20260111_0536,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 42/336 | 2026_HARP14260_20260110_1036_20260111_0548 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14260_20260110_1036_20260111_0548,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 43/336 | 2026_HARP14260_20260111_1112_20260112_0624 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14260_20260111_1112_20260112_0624,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 44/336 | 2026_HARP14260_20260112_1036_20260113_0548 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14260_20260112_1036_20260113_0548,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 45/336 | 2026_HARP14277_20260113_0312_20260113_0624 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14277_20260113_0312_20260113_0624,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 46/336 | 2026_HARP14277_20260113_1036_20260114_0548 | targets=13
==========================================================================================

----------------------------------------------------------------------
2026_HARP14277_20260113_1036_20260114_0548 | wavelength 94
94 Å cadence segments: 1 [('2026-01-13 10:36:00', '2026-01-14 05:48:00', 13)]
Segment query: aia.lev1_euv_12s[2026-01-13T10:36:00.000/1248m@96m][94]{image}
Segment reference: 2026-01-13 20:12:00 | targets: 13 | patch arcsec: 408.4948640471757
JSOC export attempt 1/10

2026-06-26 03:10:04 - drms - INFO: Export request pending. [id=JSOC_20260626_001127, status=2]

2026-06-26 03:10:04 - drms - INFO: Waiting for 15 seconds...

2026-06-26 03:10:20 - drms - INFO: Export request pending. [id=JSOC_20260626_001127, status=1]

2026-06-26 03:10:20 - drms - INFO: Waiting for 15 seconds...

2026-06-26 03:10:35 - drms - INFO: Export request pending. [id=JSOC_20260626_001127, status=1]

2026-06-26 03:10:35 - drms - INFO: Waiting for 15 seconds...

2026-06-26 03:10:51 - drms - INFO: Export request finished. [id=JSOC_20260626_001127, status=0]

2026-06-26 03:10:51 - drms - INFO: Downloading file 1 of 12...

2026-06-26 03:10:51 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-01-13T10:35:59Z][94][JSOC_20260626_001127]

2026-06-26 03:10:51 - drms - INFO:     filename: aia.lev1_euv_12s.2026-01-13T103559Z.94.image.fits

2026-06-26 03:10:52 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14277_20260113_1036_20260114_0548/94/segment_01_20260113_1036_20260114_0548/aia.lev1_euv_12s.2026-01-13T103559Z.94.image.fits.2

2026-06-26 03:10:52 - drms - INFO: Downloading file 2 of 12...

2026-06-26 03:10:52 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-01-13T12:11:59Z][94][JSOC_20260626_001127]

2026-06-26 03:10:52 - drms - INFO:     filename: aia.lev1_euv_12s.2026-01-13T121159Z.94.image.fits

2026-06-26 03:10:54 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14277_20260113_1036_20260114_0548/94/segment_01_20260113_1036_20260114_0548/aia.lev1_euv_12s.2026-01-13T121159Z.94.image.fits.2

2026-06-26 03:10:54 - drms - INFO: Downloading file 3 of 12...

2026-06-26 03:10:54 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-01-13T13:47:59Z][94][JSOC_20260626_001127]

2026-06-26 03:10:54 - drms - INFO:     filename: aia.lev1_euv_12s.2026-01-13T134759Z.94.image.fits

2026-06-26 03:10:56 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14277_20260113_1036_20260114_0548/94/segment_01_20260113_1036_20260114_0548/aia.lev1_euv_12s.2026-01-13T134759Z.94.image.fits.2

2026-06-26 03:10:56 - drms - INFO: Downloading file 4 of 12...

2026-06-26 03:10:56 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-01-13T15:23:59Z][94][JSOC_20260626_001127]

2026-06-26 03:10:56 - drms - INFO:     filename: aia.lev1_euv_12s.2026-01-13T152359Z.94.image.fits

2026-06-26 03:10:57 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14277_20260113_1036_20260114_0548/94/segment_01_20260113_1036_20260114_0548/aia.lev1_euv_12s.2026-01-13T152359Z.94.image.fits.2

2026-06-26 03:10:57 - drms - INFO: Downloading file 5 of 12...

2026-06-26 03:10:57 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-01-13T16:59:59Z][94][JSOC_20260626_001127]

2026-06-26 03:10:57 - drms - INFO:     filename: aia.lev1_euv_12s.2026-01-13T165959Z.94.image.fits

2026-06-26 03:10:59 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14277_20260113_1036_20260114_0548/94/segment_01_20260113_1036_20260114_0548/aia.lev1_euv_12s.2026-01-13T165959Z.94.image.fits.2

2026-06-26 03:10:59 - drms - INFO: Downloading file 6 of 12...

2026-06-26 03:10:59 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-01-13T18:35:59Z][94][JSOC_20260626_001127]

2026-06-26 03:10:59 - drms - INFO:     filename: aia.lev1_euv_12s.2026-01-13T183559Z.94.image.fits

2026-06-26 03:11:01 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14277_20260113_1036_20260114_0548/94/segment_01_20260113_1036_20260114_0548/aia.lev1_euv_12s.2026-01-13T183559Z.94.image.fits.2

2026-06-26 03:11:01 - drms - INFO: Downloading file 7 of 12...

2026-06-26 03:11:01 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-01-13T21:47:59Z][94][JSOC_20260626_001127]

2026-06-26 03:11:01 - drms - INFO:     filename: aia.lev1_euv_12s.2026-01-13T214759Z.94.image.fits

2026-06-26 03:11:03 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14277_20260113_1036_20260114_0548/94/segment_01_20260113_1036_20260114_0548/aia.lev1_euv_12s.2026-01-13T214759Z.94.image.fits.2

2026-06-26 03:11:03 - drms - INFO: Downloading file 8 of 12...

2026-06-26 03:11:03 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-01-13T23:23:59Z][94][JSOC_20260626_001127]

2026-06-26 03:11:03 - drms - INFO:     filename: aia.lev1_euv_12s.2026-01-13T232359Z.94.image.fits

2026-06-26 03:11:04 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14277_20260113_1036_20260114_0548/94/segment_01_20260113_1036_20260114_0548/aia.lev1_euv_12s.2026-01-13T232359Z.94.image.fits.2

2026-06-26 03:11:04 - drms - INFO: Downloading file 9 of 12...

2026-06-26 03:11:04 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-01-14T00:59:59Z][94][JSOC_20260626_001127]

2026-06-26 03:11:04 - drms - INFO:     filename: aia.lev1_euv_12s.2026-01-14T005959Z.94.image.fits

2026-06-26 03:11:06 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14277_20260113_1036_20260114_0548/94/segment_01_20260113_1036_20260114_0548/aia.lev1_euv_12s.2026-01-14T005959Z.94.image.fits.2

2026-06-26 03:11:06 - drms - INFO: Downloading file 10 of 12...

2026-06-26 03:11:06 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-01-14T02:35:59Z][94][JSOC_20260626_001127]

2026-06-26 03:11:06 - drms - INFO:     filename: aia.lev1_euv_12s.2026-01-14T023559Z.94.image.fits

2026-06-26 03:11:08 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14277_20260113_1036_20260114_0548/94/segment_01_20260113_1036_20260114_0548/aia.lev1_euv_12s.2026-01-14T023559Z.94.image.fits.2

2026-06-26 03:11:08 - drms - INFO: Downloading file 11 of 12...

2026-06-26 03:11:08 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-01-14T04:11:59Z][94][JSOC_20260626_001127]

2026-06-26 03:11:08 - drms - INFO:     filename: aia.lev1_euv_12s.2026-01-14T041159Z.94.image.fits

2026-06-26 03:11:09 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14277_20260113_1036_20260114_0548/94/segment_01_20260113_1036_20260114_0548/aia.lev1_euv_12s.2026-01-14T041159Z.94.image.fits.2

2026-06-26 03:11:09 - drms - INFO: Downloading file 12 of 12...

2026-06-26 03:11:09 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-01-14T05:47:59Z][94][JSOC_20260626_001127]

2026-06-26 03:11:09 - drms - INFO:     filename: aia.lev1_euv_12s.2026-01-14T054759Z.94.image.fits

2026-06-26 03:11:11 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14277_20260113_1036_20260114_0548/94/segment_01_20260113_1036_20260114_0548/aia.lev1_euv_12s.2026-01-14T054759Z.94.image.fits.2

BLOCK ERROR: RuntimeError('Downloaded 94 Å segment does not cover all target timestamps within 180 seconds.')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14277_20260113_1036_20260114_0548,error,13,None,0,None,RuntimeError('Downloaded 94 Å segment does not...

==========================================================================================
BLOCK 47/336 | 2026_HARP14277_20260114_1000_20260115_0524 | targets=12
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14277_20260114_1000_20260115_0524,already_complete,12,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 48/336 | 2026_HARP14285_20260114_1448_20260115_0524 | targets=9
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14285_20260114_1448_20260115_0524,already_complete,9,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 49/336 | 2026_HARP14277_20260115_1112_20260116_0624 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14277_20260115_1112_20260116_0624,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 50/336 | 2026_HARP14285_20260115_1112_20260116_0624 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14285_20260115_1112_20260116_0624,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 51/336 | 2026_HARP14277_20260116_1036_20260117_0548 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14277_20260116_1036_20260117_0548,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 52/336 | 2026_HARP14285_20260116_1036_20260117_0548 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14285_20260116_1036_20260117_0548,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 53/336 | 2026_HARP14277_20260117_1000_20260117_1448 | targets=4
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14277_20260117_1000_20260117_1448,already_complete,4,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 54/336 | 2026_HARP14285_20260117_1000_20260117_1624 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14285_20260117_1000_20260117_1624,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 55/336 | 2026_HARP14285_20260117_1936_20260118_0512 | targets=7
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14285_20260117_1936_20260118_0512,already_complete,7,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 56/336 | 2026_HARP14284_20260118_0100_20260118_0548 | targets=4
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14284_20260118_0100_20260118_0548,already_complete,4,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 57/336 | 2026_HARP14282_20260118_1012_20260118_1500 | targets=4
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14282_20260118_1012_20260118_1500,already_complete,4,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 58/336 | 2026_HARP14284_20260118_1012_20260118_1500 | targets=4
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14284_20260118_1012_20260118_1500,already_complete,4,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 59/336 | 2026_HARP14297_20260118_1036_20260119_0236 | targets=11
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14297_20260118_1036_20260119_0236,already_complete,11,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 60/336 | 2026_HARP14285_20260118_1112_20260118_1736 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14285_20260118_1112_20260118_1736,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 61/336 | 2026_HARP14282_20260118_1812_20260119_0212 | targets=6
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14282_20260118_1812_20260119_0212,already_complete,6,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 62/336 | 2026_HARP14284_20260118_1812_20260119_0212 | targets=6
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14284_20260118_1812_20260119_0212,already_complete,6,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 63/336 | 2026_HARP14282_20260119_0612_20260119_0612 | targets=1
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14282_20260119_0612_20260119_0612,already_complete,1,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 64/336 | 2026_HARP14284_20260119_0612_20260119_0612 | targets=1
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14284_20260119_0612_20260119_0612,already_complete,1,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 65/336 | 2026_HARP14297_20260119_0924_20260120_0612 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14297_20260119_0924_20260120_0612,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 66/336 | 2026_HARP14282_20260119_1036_20260120_0548 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14282_20260119_1036_20260120_0548,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 67/336 | 2026_HARP14284_20260119_1036_20260120_0548 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14284_20260119_1036_20260120_0548,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 68/336 | 2026_HARP14282_20260120_1000_20260120_1624 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14282_20260120_1000_20260120_1624,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 69/336 | 2026_HARP14284_20260120_1000_20260120_1624 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14284_20260120_1000_20260120_1624,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 70/336 | 2026_HARP14297_20260120_1024_20260121_0536 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14297_20260120_1024_20260121_0536,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 71/336 | 2026_HARP14282_20260120_1936_20260121_0512 | targets=7
==========================================================================================

----------------------------------------------------------------------
2026_HARP14282_20260120_1936_20260121_0512 | wavelength 94
94 Å cadence segments: 1 [('2026-01-20 19:36:00', '2026-01-21 05:12:00', 7)]
♻️ Segment 1/1 already covered by cached 94 Å files.

----------------------------------------------------------------------
2026_HARP14282_20260120_1936_20260121_0512 | wavelength 131
131 Å cadence segments: 1 [('2026-01-20 19:36:00', '2026-01-21 05:12:00', 7)]

♻️ Segment 1/1 already covered by cached 131 Å files.

----------------------------------------------------------------------
2026_HARP14282_20260120_1936_20260121_0512 | wavelength 171
171 Å cadence segments: 1 [('2026-01-20 19:36:00', '2026-01-21 05:12:00', 7)]
♻️ Segment 1/1 already covered by cached 171 Å files.

----------------------------------------------------------------------
2026_HARP14282_20260120_1936_20260121_0512 | wavelength 193
193 Å cadence segments: 1 [('2026-01-20 19:36:00', '2026-01-21 05:12:00', 7)]
♻️ Segment 1/1 already covered by cached 193 Å files.

----------------------------------------------------------------------
2026_HARP14282_20260120_1936_20260121_0512 | wavelength 211
211 Å cadence segments: 1 [('2026-01-20 19:36:00', '2026-01-21 05:12:00', 7)]

Segment query: aia.lev1_euv_12s[2026-01-20T19:36:00.000/672m@96m][211]{image}
Segment reference: 2026-01-21 00:24:00 | targets: 7 | patch arcsec: 972.6266053299584
JSOC export attempt 1/10

2026-06-26 03:12:02 - drms - INFO: Export request pending. [id=JSOC_20260626_001133, status=2]

2026-06-26 03:12:02 - drms - INFO: Waiting for 15 seconds...

2026-06-26 03:12:17 - drms - INFO: Export request pending. [id=JSOC_20260626_001133, status=1]

2026-06-26 03:12:17 - drms - INFO: Waiting for 15 seconds...

2026-06-26 03:12:33 - drms - INFO: Export request pending. [id=JSOC_20260626_001133, status=1]

2026-06-26 03:12:33 - drms - INFO: Waiting for 15 seconds...

2026-06-26 03:12:49 - drms - INFO: Export request finished. [id=JSOC_20260626_001133, status=0]

2026-06-26 03:12:49 - drms - INFO: Downloading file 1 of 6...

2026-06-26 03:12:49 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-01-20T19:35:59Z][211][JSOC_20260626_001133]

2026-06-26 03:12:49 - drms - INFO:     filename: aia.lev1_euv_12s.2026-01-20T193559Z.211.image.fits

2026-06-26 03:12:52 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14282_20260120_1936_20260121_0512/211/segment_01_20260120_1936_20260121_0512/aia.lev1_euv_12s.2026-01-20T193559Z.211.image.fits.2

2026-06-26 03:12:52 - drms - INFO: Downloading file 2 of 6...

2026-06-26 03:12:52 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-01-20T21:11:59Z][211][JSOC_20260626_001133]

2026-06-26 03:12:52 - drms - INFO:     filename: aia.lev1_euv_12s.2026-01-20T211159Z.211.image.fits

2026-06-26 03:12:56 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14282_20260120_1936_20260121_0512/211/segment_01_20260120_1936_20260121_0512/aia.lev1_euv_12s.2026-01-20T211159Z.211.image.fits.2

2026-06-26 03:12:56 - drms - INFO: Downloading file 3 of 6...

2026-06-26 03:12:56 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-01-20T22:47:59Z][211][JSOC_20260626_001133]

2026-06-26 03:12:56 - drms - INFO:     filename: aia.lev1_euv_12s.2026-01-20T224759Z.211.image.fits

2026-06-26 03:12:59 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14282_20260120_1936_20260121_0512/211/segment_01_20260120_1936_20260121_0512/aia.lev1_euv_12s.2026-01-20T224759Z.211.image.fits.2

2026-06-26 03:12:59 - drms - INFO: Downloading file 4 of 6...

2026-06-26 03:12:59 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-01-21T00:23:59Z][211][JSOC_20260626_001133]

2026-06-26 03:12:59 - drms - INFO:     filename: aia.lev1_euv_12s.2026-01-21T002359Z.211.image.fits

2026-06-26 03:13:03 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14282_20260120_1936_20260121_0512/211/segment_01_20260120_1936_20260121_0512/aia.lev1_euv_12s.2026-01-21T002359Z.211.image.fits.2

2026-06-26 03:13:03 - drms - INFO: Downloading file 5 of 6...

2026-06-26 03:13:03 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-01-21T01:59:59Z][211][JSOC_20260626_001133]

2026-06-26 03:13:03 - drms - INFO:     filename: aia.lev1_euv_12s.2026-01-21T015959Z.211.image.fits

2026-06-26 03:13:06 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14282_20260120_1936_20260121_0512/211/segment_01_20260120_1936_20260121_0512/aia.lev1_euv_12s.2026-01-21T015959Z.211.image.fits.2

2026-06-26 03:13:06 - drms - INFO: Downloading file 6 of 6...

2026-06-26 03:13:06 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-01-21T03:35:59Z][211][JSOC_20260626_001133]

2026-06-26 03:13:06 - drms - INFO:     filename: aia.lev1_euv_12s.2026-01-21T033559Z.211.image.fits

2026-06-26 03:13:10 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14282_20260120_1936_20260121_0512/211/segment_01_20260120_1936_20260121_0512/aia.lev1_euv_12s.2026-01-21T033559Z.211.image.fits.2

BLOCK ERROR: RuntimeError('Downloaded 211 Å segment does not cover all target timestamps within 180 seconds.')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14282_20260120_1936_20260121_0512,error,7,None,0,None,RuntimeError('Downloaded 211 Å segment does no...

==========================================================================================
BLOCK 72/336 | 2026_HARP14284_20260120_1936_20260121_0512 | targets=7
==========================================================================================

----------------------------------------------------------------------
2026_HARP14284_20260120_1936_20260121_0512 | wavelength 94
94 Å cadence segments: 1 [('2026-01-20 19:36:00', '2026-01-21 05:12:00', 7)]
♻️ Segment 1/1 already covered by cached 94 Å files.

----------------------------------------------------------------------
2026_HARP14284_20260120_1936_20260121_0512 | wavelength 131
131 Å cadence segments: 1 [('2026-01-20 19:36:00', '2026-01-21 05:12:00', 7)]

♻️ Segment 1/1 already covered by cached 131 Å files.

----------------------------------------------------------------------
2026_HARP14284_20260120_1936_20260121_0512 | wavelength 171
171 Å cadence segments: 1 [('2026-01-20 19:36:00', '2026-01-21 05:12:00', 7)]
♻️ Segment 1/1 already covered by cached 171 Å files.

----------------------------------------------------------------------
2026_HARP14284_20260120_1936_20260121_0512 | wavelength 193
193 Å cadence segments: 1 [('2026-01-20 19:36:00', '2026-01-21 05:12:00', 7)]
♻️ Segment 1/1 already covered by cached 193 Å files.

----------------------------------------------------------------------
2026_HARP14284_20260120_1936_20260121_0512 | wavelength 211
211 Å cadence segments: 1 [('2026-01-20 19:36:00', '2026-01-21 05:12:00', 7)]

Segment query: aia.lev1_euv_12s[2026-01-20T19:36:00.000/672m@96m][211]{image}
Segment reference: 2026-01-21 00:24:00 | targets: 7 | patch arcsec: 904.7732058653959
JSOC export attempt 1/10

2026-06-26 03:13:14 - drms - INFO: Export request pending. [id=JSOC_20260626_001143, status=2]

2026-06-26 03:13:14 - drms - INFO: Waiting for 15 seconds...

2026-06-26 03:13:29 - drms - INFO: Export request pending. [id=JSOC_20260626_001143, status=1]

2026-06-26 03:13:29 - drms - INFO: Waiting for 15 seconds...

2026-06-26 03:13:45 - drms - INFO: Export request pending. [id=JSOC_20260626_001143, status=1]

2026-06-26 03:13:45 - drms - INFO: Waiting for 15 seconds...

2026-06-26 03:14:01 - drms - INFO: Export request finished. [id=JSOC_20260626_001143, status=0]

2026-06-26 03:14:01 - drms - INFO: Downloading file 1 of 6...

2026-06-26 03:14:01 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-01-20T19:35:59Z][211][JSOC_20260626_001143]

2026-06-26 03:14:01 - drms - INFO:     filename: aia.lev1_euv_12s.2026-01-20T193559Z.211.image.fits

2026-06-26 03:14:04 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14284_20260120_1936_20260121_0512/211/segment_01_20260120_1936_20260121_0512/aia.lev1_euv_12s.2026-01-20T193559Z.211.image.fits.2

2026-06-26 03:14:04 - drms - INFO: Downloading file 2 of 6...

2026-06-26 03:14:04 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-01-20T21:11:59Z][211][JSOC_20260626_001143]

2026-06-26 03:14:04 - drms - INFO:     filename: aia.lev1_euv_12s.2026-01-20T211159Z.211.image.fits

2026-06-26 03:14:07 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14284_20260120_1936_20260121_0512/211/segment_01_20260120_1936_20260121_0512/aia.lev1_euv_12s.2026-01-20T211159Z.211.image.fits.2

2026-06-26 03:14:07 - drms - INFO: Downloading file 3 of 6...

2026-06-26 03:14:07 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-01-20T22:47:59Z][211][JSOC_20260626_001143]

2026-06-26 03:14:07 - drms - INFO:     filename: aia.lev1_euv_12s.2026-01-20T224759Z.211.image.fits

2026-06-26 03:14:11 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14284_20260120_1936_20260121_0512/211/segment_01_20260120_1936_20260121_0512/aia.lev1_euv_12s.2026-01-20T224759Z.211.image.fits.2

2026-06-26 03:14:11 - drms - INFO: Downloading file 4 of 6...

2026-06-26 03:14:11 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-01-21T00:23:59Z][211][JSOC_20260626_001143]

2026-06-26 03:14:11 - drms - INFO:     filename: aia.lev1_euv_12s.2026-01-21T002359Z.211.image.fits

2026-06-26 03:14:14 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14284_20260120_1936_20260121_0512/211/segment_01_20260120_1936_20260121_0512/aia.lev1_euv_12s.2026-01-21T002359Z.211.image.fits.2

2026-06-26 03:14:14 - drms - INFO: Downloading file 5 of 6...

2026-06-26 03:14:14 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-01-21T01:59:59Z][211][JSOC_20260626_001143]

2026-06-26 03:14:14 - drms - INFO:     filename: aia.lev1_euv_12s.2026-01-21T015959Z.211.image.fits

2026-06-26 03:14:17 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14284_20260120_1936_20260121_0512/211/segment_01_20260120_1936_20260121_0512/aia.lev1_euv_12s.2026-01-21T015959Z.211.image.fits.2

2026-06-26 03:14:17 - drms - INFO: Downloading file 6 of 6...

2026-06-26 03:14:17 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-01-21T03:35:59Z][211][JSOC_20260626_001143]

2026-06-26 03:14:17 - drms - INFO:     filename: aia.lev1_euv_12s.2026-01-21T033559Z.211.image.fits

2026-06-26 03:14:20 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14284_20260120_1936_20260121_0512/211/segment_01_20260120_1936_20260121_0512/aia.lev1_euv_12s.2026-01-21T033559Z.211.image.fits.2

BLOCK ERROR: RuntimeError('Downloaded 211 Å segment does not cover all target timestamps within 180 seconds.')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14284_20260120_1936_20260121_0512,error,7,None,0,None,RuntimeError('Downloaded 211 Å segment does no...

==========================================================================================
BLOCK 73/336 | 2026_HARP14303_20260121_0112_20260121_0424 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14303_20260121_0112_20260121_0424,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 74/336 | 2026_HARP14282_20260121_0924_20260121_1248 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14282_20260121_0924_20260121_1248,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 75/336 | 2026_HARP14284_20260121_0924_20260121_1248 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14284_20260121_0924_20260121_1248,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 76/336 | 2026_HARP14303_20260121_1024_20260121_1336 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14303_20260121_1024_20260121_1336,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 77/336 | 2026_HARP14282_20260121_2036_20260122_0612 | targets=7
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14282_20260121_2036_20260122_0612,already_complete,7,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 78/336 | 2026_HARP14284_20260121_2036_20260122_0612 | targets=7
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14284_20260121_2036_20260122_0612,already_complete,7,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 79/336 | 2026_HARP14292_20260121_2112_20260122_0512 | targets=6
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14292_20260121_2112_20260122_0512,already_complete,6,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 80/336 | 2026_HARP14303_20260121_2124_20260122_0524 | targets=6
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14303_20260121_2124_20260122_0524,already_complete,6,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 81/336 | 2026_HARP14292_20260122_0924_20260122_1736 | targets=6
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14292_20260122_0924_20260122_1736,already_complete,6,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 82/336 | 2026_HARP14282_20260122_1036_20260122_1836 | targets=6
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14282_20260122_1036_20260122_1836,already_complete,6,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 83/336 | 2026_HARP14284_20260122_1036_20260122_1524 | targets=4
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14284_20260122_1036_20260122_1524,already_complete,4,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 84/336 | 2026_HARP14303_20260122_1124_20260123_0500 | targets=12
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14303_20260122_1124_20260123_0500,already_complete,12,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 85/336 | 2026_HARP14292_20260122_2048_20260123_0448 | targets=6
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14292_20260122_2048_20260123_0448,already_complete,6,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 86/336 | 2026_HARP14282_20260122_2148_20260123_0100 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14282_20260122_2148_20260123_0100,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 87/336 | 2026_HARP14303_20260123_0912_20260123_1724 | targets=6
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14303_20260123_0912_20260123_1724,already_complete,6,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 88/336 | 2026_HARP14292_20260123_1048_20260124_0124 | targets=10
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14292_20260123_1048_20260124_0124,already_complete,10,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 89/336 | 2026_HARP14303_20260123_2048_20260124_0500 | targets=6
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14303_20260123_2048_20260124_0500,already_complete,6,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 90/336 | 2026_HARP14292_20260124_0448_20260124_0624 | targets=2
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14292_20260124_0448_20260124_0624,already_complete,2,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 91/336 | 2026_HARP14303_20260124_0912_20260124_2348 | targets=10
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14303_20260124_0912_20260124_2348,already_complete,10,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 92/336 | 2026_HARP14292_20260124_1048_20260125_0112 | targets=10
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14292_20260124_1048_20260125_0112,already_complete,10,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 93/336 | 2026_HARP14332_20260125_0100_20260125_0100 | targets=1
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14332_20260125_0100_20260125_0100,already_complete,1,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 94/336 | 2026_HARP14332_20260125_0536_20260125_0536 | targets=1
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14332_20260125_0536_20260125_0536,already_complete,1,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 95/336 | 2026_HARP14292_20260125_0548_20260125_0548 | targets=1
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14292_20260125_0548_20260125_0548,already_complete,1,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 96/336 | 2026_HARP14292_20260125_1000_20260125_1624 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14292_20260125_1000_20260125_1624,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 97/336 | 2026_HARP14305_20260125_1000_20260125_1624 | targets=5
==========================================================================================

----------------------------------------------------------------------
2026_HARP14305_20260125_1000_20260125_1624 | wavelength 94
94 Å cadence segments: 1 [('2026-01-25 10:00:00', '2026-01-25 16:24:00', 5)]
♻️ Segment 1/1 already covered by cached 94 Å files.

----------------------------------------------------------------------
2026_HARP14305_20260125_1000_20260125_1624 | wavelength 131
131 Å cadence segments: 1 [('2026-01-25 10:00:00', '2026-01-25 16:24:00', 5)]
♻️ Segment 1/1 already covered by cached 131 Å files.

----------------------------------------------------------------------
2026_HARP14305_20260125_1000_20260125_1624 | wavelength 171
171 Å cadence segments: 1 [('2026-01-25 10:00:00', '2026-01-25 16:24:00', 5)]
♻️ Segment 1/1 already covered by cached 171 Å files.

----------------------------------------------------------------------
2026_HARP14305_20260125_1000_20260125_1624 | wavelength 193
193 Å cadence segments: 1 [('2026-01-25 10:00:00', '2026-01-25 16:24:00', 5)]
♻️ Segment 1/1 already covered by cached 193 Å files.

----------------------------------------------------------------------
2026_HARP14305_20260125_1000_20260125_1624 | wavelength 211
211 Å cadence segments: 1 [('2026-01-25 10:00:00', '2026-01-25 16:24:00', 5)]
♻️ Segment 1/1 already covered by cached 211 Å files.

----------------------------------------------------------------------
2026_HARP14305_20260125_1000_20260125_1624 | wavelength 335
335 Å cadence segments: 1 [('2026-01-25 10:00:00', '2026-01-25 16:24:00', 5)]
♻️ Segment 1/1 already covered by cached 335 Å files.

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260125_1136_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(9, 1835, 3, 1829), shape=(1834, 1834)')

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260125_1312_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-8, 1841, -8, 1841), shape=(1834, 1834)')

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260125_1448_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-18, 1845, -14, 1849), shape=(1834, 1834)')

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260125_1624_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-27, 1849, -21, 1855), shape=(1834, 1834)')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14305_20260125_1000_20260125_1624,completed,5,4,0,0.15,4 sample errors retained for retry

==========================================================================================
BLOCK 98/336 | 2026_HARP14303_20260125_1012_20260125_1636 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14303_20260125_1012_20260125_1636,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 99/336 | 2026_HARP14332_20260125_1124_20260125_1300 | targets=2
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14332_20260125_1124_20260125_1300,already_complete,2,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 100/336 | 2026_HARP14332_20260125_1612_20260125_1612 | targets=1
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14332_20260125_1612_20260125_1612,already_complete,1,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 101/336 | 2026_HARP14292_20260125_1948_20260126_0524 | targets=7
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14292_20260125_1948_20260126_0524,already_complete,7,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 102/336 | 2026_HARP14305_20260125_1948_20260126_0524 | targets=7
==========================================================================================

----------------------------------------------------------------------
2026_HARP14305_20260125_1948_20260126_0524 | wavelength 94
94 Å cadence segments: 1 [('2026-01-25 19:48:00', '2026-01-26 05:24:00', 7)]
♻️ Segment 1/1 already covered by cached 94 Å files.

----------------------------------------------------------------------
2026_HARP14305_20260125_1948_20260126_0524 | wavelength 131
131 Å cadence segments: 1 [('2026-01-25 19:48:00', '2026-01-26 05:24:00', 7)]

♻️ Segment 1/1 already covered by cached 131 Å files.

----------------------------------------------------------------------
2026_HARP14305_20260125_1948_20260126_0524 | wavelength 171
171 Å cadence segments: 1 [('2026-01-25 19:48:00', '2026-01-26 05:24:00', 7)]
♻️ Segment 1/1 already covered by cached 171 Å files.

----------------------------------------------------------------------
2026_HARP14305_20260125_1948_20260126_0524 | wavelength 193
193 Å cadence segments: 1 [('2026-01-25 19:48:00', '2026-01-26 05:24:00', 7)]
♻️ Segment 1/1 already covered by cached 193 Å files.

----------------------------------------------------------------------
2026_HARP14305_20260125_1948_20260126_0524 | wavelength 211
211 Å cadence segments: 1 [('2026-01-25 19:48:00', '2026-01-26 05:24:00', 7)]

♻️ Segment 1/1 already covered by cached 211 Å files.

----------------------------------------------------------------------
2026_HARP14305_20260125_1948_20260126_0524 | wavelength 335
335 Å cadence segments: 1 [('2026-01-25 19:48:00', '2026-01-26 05:24:00', 7)]
♻️ Segment 1/1 already covered by cached 335 Å files.

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260125_1948_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-58, 1931, -62, 1927), shape=(1834, 1834)')

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260125_2124_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-78, 1936, -81, 1933), shape=(1834, 1834)')

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260125_2300_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-95, 1940, -95, 1940), shape=(1834, 1834)')

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260126_0036_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-111, 1944, -112, 1944), shape=(1834, 1834)')

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260126_0212_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-121, 1948, -121, 1949), shape=(1834, 1834)')

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260126_0348_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-131, 1951, -129, 1953), shape=(1834, 1834)')

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260126_0524_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-139, 1954, -137, 1956), shape=(1834, 1834)')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14305_20260125_1948_20260126_0524,completed,7,7,0,0.258,7 sample errors retained for retry

==========================================================================================
BLOCK 103/336 | 2026_HARP14332_20260125_2200_20260126_0424 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14332_20260125_2200_20260126_0424,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 104/336 | 2026_HARP14332_20260126_1012_20260127_0524 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14332_20260126_1012_20260127_0524,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 105/336 | 2026_HARP14305_20260126_1112_20260127_0312 | targets=11
==========================================================================================

----------------------------------------------------------------------
2026_HARP14305_20260126_1112_20260127_0312 | wavelength 94
94 Å cadence segments: 1 [('2026-01-26 11:12:00', '2026-01-27 03:12:00', 11)]
♻️ Segment 1/1 already covered by cached 94 Å files.

----------------------------------------------------------------------
2026_HARP14305_20260126_1112_20260127_0312 | wavelength 131
131 Å cadence segments: 1 [('2026-01-26 11:12:00', '2026-01-27 03:12:00', 11)]
♻️ Segment 1/1 already covered by cached 131 Å files.

----------------------------------------------------------------------
2026_HARP14305_20260126_1112_20260127_0312 | wavelength 171
171 Å cadence segments: 1 [('2026-01-26 11:12:00', '2026-01-27 03:12:00', 11)]
♻️ Segment 1/1 already covered by cached 171 Å files.

----------------------------------------------------------------------
2026_HARP14305_20260126_1112_20260127_0312 | wavelength 193
193 Å cadence segments: 1 [('2026-01-26 11:12:00', '2026-01-27 03:12:00', 11)]
♻️ Segment 1/1 already covered by cached 193 Å files.

----------------------------------------------------------------------
2026_HARP14305_20260126_1112_20260127_0312 | wavelength 211
211 Å cadence segments: 1 [('2026-01-26 11:12:00', '2026-01-27 03:12:00', 11)]
♻️ Segment 1/1 already covered by cached 211 Å files.

----------------------------------------------------------------------
2026_HARP14305_20260126_1112_20260127_0312 | wavelength 335
335 Å cadence segments: 1 [('2026-01-26 11:12:00', '2026-01-27 03:12:00', 11)]
♻️ Segment 1/1 already covered by cached 335 Å files.

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260126_1112_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-137, 1999, -147, 1989), shape=(1834, 1834)')

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260126_1248_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-146, 2002, -153, 1995), shape=(1834, 1834)')

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260126_1424_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-155, 2004, -159, 2000), shape=(1834, 1834)')

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260126_1600_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-164, 2007, -167, 2005), shape=(1834, 1834)')

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260126_1736_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-172, 2011, -173, 2009), shape=(1834, 1834)')

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260126_1912_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-179, 2011, -179, 2011), shape=(1834, 1834)')

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260126_2048_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-186, 2013, -184, 2015), shape=(1834, 1834)')

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260126_2224_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-193, 2013, -187, 2019), shape=(1834, 1834)')

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260127_0000_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-199, 2012, -191, 2020), shape=(1834, 1834)')

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260127_0136_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-204, 2011, -194, 2021), shape=(1834, 1834)')

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260127_0312_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-209, 2009, -195, 2023), shape=(1834, 1834)')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14305_20260126_1112_20260127_0312,completed,11,11,0,0.415,11 sample errors retained for retry

==========================================================================================
BLOCK 106/336 | 2026_HARP14305_20260127_0624_20260127_0624 | targets=1
==========================================================================================

----------------------------------------------------------------------
2026_HARP14305_20260127_0624_20260127_0624 | wavelength 94
94 Å cadence segments: 1 [('2026-01-27 06:24:00', '2026-01-27 06:24:00', 1)]
♻️ Segment 1/1 already covered by cached 94 Å files.

----------------------------------------------------------------------
2026_HARP14305_20260127_0624_20260127_0624 | wavelength 131
131 Å cadence segments: 1 [('2026-01-27 06:24:00', '2026-01-27 06:24:00', 1)]
♻️ Segment 1/1 already covered by cached 131 Å files.

----------------------------------------------------------------------
2026_HARP14305_20260127_0624_20260127_0624 | wavelength 171
171 Å cadence segments: 1 [('2026-01-27 06:24:00', '2026-01-27 06:24:00', 1)]
♻️ Segment 1/1 already covered by cached 171 Å files.

----------------------------------------------------------------------
2026_HARP14305_20260127_0624_20260127_0624 | wavelength 193
193 Å cadence segments: 1 [('2026-01-27 06:24:00', '2026-01-27 06:24:00', 1)]
♻️ Segment 1/1 already covered by cached 193 Å files.

----------------------------------------------------------------------
2026_HARP14305_20260127_0624_20260127_0624 | wavelength 211
211 Å cadence segments: 1 [('2026-01-27 06:24:00', '2026-01-27 06:24:00', 1)]
♻️ Segment 1/1 already covered by cached 211 Å files.

----------------------------------------------------------------------
2026_HARP14305_20260127_0624_20260127_0624 | wavelength 335
335 Å cadence segments: 1 [('2026-01-27 06:24:00', '2026-01-27 06:24:00', 1)]
♻️ Segment 1/1 already covered by cached 335 Å files.

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260127_0624_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-197, 2030, -197, 2031), shape=(1834, 1834)')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14305_20260127_0624_20260127_0624,completed,1,1,0,0.037,1 sample errors retained for retry

==========================================================================================
BLOCK 107/336 | 2026_HARP14332_20260127_0924_20260128_0500 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14332_20260127_0924_20260128_0500,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 108/336 | 2026_HARP14305_20260127_1024_20260128_0424 | targets=12
==========================================================================================

----------------------------------------------------------------------
2026_HARP14305_20260127_1024_20260128_0424 | wavelength 94
94 Å cadence segments: 2 [('2026-01-27 10:24:00', '2026-01-27 18:24:00', 6), ('2026-01-27 20:24:00', '2026-01-28 04:24:00', 6)]
♻️ Segment 1/2 already covered by cached 94 Å files.

♻️ Segment 2/2 already covered by cached 94 Å files.

----------------------------------------------------------------------
2026_HARP14305_20260127_1024_20260128_0424 | wavelength 131
131 Å cadence segments: 2 [('2026-01-27 10:24:00', '2026-01-27 18:24:00', 6), ('2026-01-27 20:24:00', '2026-01-28 04:24:00', 6)]
♻️ Segment 1/2 already covered by cached 131 Å files.

♻️ Segment 2/2 already covered by cached 131 Å files.

----------------------------------------------------------------------
2026_HARP14305_20260127_1024_20260128_0424 | wavelength 171
171 Å cadence segments: 2 [('2026-01-27 10:24:00', '2026-01-27 18:24:00', 6), ('2026-01-27 20:24:00', '2026-01-28 04:24:00', 6)]

♻️ Segment 1/2 already covered by cached 171 Å files.
♻️ Segment 2/2 already covered by cached 171 Å files.

----------------------------------------------------------------------
2026_HARP14305_20260127_1024_20260128_0424 | wavelength 193
193 Å cadence segments: 2 [('2026-01-27 10:24:00', '2026-01-27 18:24:00', 6), ('2026-01-27 20:24:00', '2026-01-28 04:24:00', 6)]
♻️ Segment 1/2 already covered by cached 193 Å files.

♻️ Segment 2/2 already covered by cached 193 Å files.

----------------------------------------------------------------------
2026_HARP14305_20260127_1024_20260128_0424 | wavelength 211
211 Å cadence segments: 2 [('2026-01-27 10:24:00', '2026-01-27 18:24:00', 6), ('2026-01-27 20:24:00', '2026-01-28 04:24:00', 6)]
♻️ Segment 1/2 already covered by cached 211 Å files.

♻️ Segment 2/2 already covered by cached 211 Å files.

----------------------------------------------------------------------
2026_HARP14305_20260127_1024_20260128_0424 | wavelength 335
335 Å cadence segments: 2 [('2026-01-27 10:24:00', '2026-01-27 18:24:00', 6), ('2026-01-27 20:24:00', '2026-01-28 04:24:00', 6)]
♻️ Segment 1/2 already covered by cached 335 Å files.

♻️ Segment 2/2 already covered by cached 335 Å files.

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260127_1024_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-182, 2052, -200, 2034), shape=(1834, 1834)')

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260127_1200_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-187, 2050, -202, 2035), shape=(1834, 1834)')

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260127_1336_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-191, 2047, -202, 2036), shape=(1834, 1834)')

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260127_1512_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-194, 2045, -202, 2037), shape=(1834, 1834)')

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260127_1648_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-197, 2042, -204, 2035), shape=(1834, 1834)')

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260127_1824_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-200, 2038, -204, 2034), shape=(1834, 1834)')

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260127_2024_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-183, 2053, -201, 2035), shape=(1834, 1834)')

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260127_2200_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-185, 2048, -200, 2034), shape=(1834, 1834)')

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260127_2336_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-188, 2044, -199, 2033), shape=(1834, 1834)')

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260128_0112_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-189, 2040, -196, 2033), shape=(1834, 1834)')

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260128_0248_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-189, 2033, -193, 2030), shape=(1834, 1834)')

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260128_0424_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-189, 2029, -190, 2028), shape=(1834, 1834)')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14305_20260127_1024_20260128_0424,completed,12,12,0,0.457,12 sample errors retained for retry

==========================================================================================
BLOCK 109/336 | 2026_HARP14328_20260127_1536_20260127_1712 | targets=2
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14328_20260127_1536_20260127_1712,already_complete,2,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 110/336 | 2026_HARP14328_20260127_2048_20260128_0312 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14328_20260127_2048_20260128_0312,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 111/336 | 2026_HARP14328_20260128_0624_20260128_0624 | targets=1
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14328_20260128_0624_20260128_0624,already_complete,1,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 112/336 | 2026_HARP14305_20260128_1000_20260129_0548 | targets=13
==========================================================================================

----------------------------------------------------------------------
2026_HARP14305_20260128_1000_20260129_0548 | wavelength 94
94 Å cadence segments: 2 [('2026-01-28 10:00:00', '2026-01-28 13:12:00', 3), ('2026-01-28 15:24:00', '2026-01-29 05:48:00', 10)]
♻️ Segment 1/2 already covered by cached 94 Å files.

Segment query: aia.lev1_euv_12s[2026-01-28T15:24:00.000/960m@96m][94]{image}
Segment reference: 2026-01-28 22:36:00 | targets: 10 | patch arcsec: 1100.0
JSOC export attempt 1/10

2026-06-26 03:16:58 - drms - INFO: Export request pending. [id=JSOC_20260626_001154, status=2]

2026-06-26 03:16:58 - drms - INFO: Waiting for 15 seconds...

2026-06-26 03:17:14 - drms - INFO: Export request pending. [id=JSOC_20260626_001154, status=1]

2026-06-26 03:17:14 - drms - INFO: Waiting for 15 seconds...

2026-06-26 03:17:29 - drms - INFO: Export request pending. [id=JSOC_20260626_001154, status=1]

2026-06-26 03:17:29 - drms - INFO: Waiting for 15 seconds...

2026-06-26 03:17:45 - drms - INFO: Export request pending. [id=JSOC_20260626_001154, status=1]

2026-06-26 03:17:45 - drms - INFO: Waiting for 15 seconds...

2026-06-26 03:18:00 - drms - INFO: Export request finished. [id=JSOC_20260626_001154, status=0]

2026-06-26 03:18:00 - drms - INFO: Downloading file 1 of 9...

2026-06-26 03:18:00 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-01-28T16:59:59Z][94][JSOC_20260626_001154]

2026-06-26 03:18:00 - drms - INFO:     filename: aia.lev1_euv_12s.2026-01-28T165959Z.94.image.fits

2026-06-26 03:18:04 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14305_20260128_1000_20260129_0548/94/segment_02_20260128_1524_20260129_0548/aia.lev1_euv_12s.2026-01-28T165959Z.94.image.fits.1

2026-06-26 03:18:04 - drms - INFO: Downloading file 2 of 9...

2026-06-26 03:18:04 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-01-28T18:35:59Z][94][JSOC_20260626_001154]

2026-06-26 03:18:04 - drms - INFO:     filename: aia.lev1_euv_12s.2026-01-28T183559Z.94.image.fits

2026-06-26 03:18:08 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14305_20260128_1000_20260129_0548/94/segment_02_20260128_1524_20260129_0548/aia.lev1_euv_12s.2026-01-28T183559Z.94.image.fits.1

2026-06-26 03:18:08 - drms - INFO: Downloading file 3 of 9...

2026-06-26 03:18:08 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-01-28T20:11:59Z][94][JSOC_20260626_001154]

2026-06-26 03:18:08 - drms - INFO:     filename: aia.lev1_euv_12s.2026-01-28T201159Z.94.image.fits

2026-06-26 03:18:12 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14305_20260128_1000_20260129_0548/94/segment_02_20260128_1524_20260129_0548/aia.lev1_euv_12s.2026-01-28T201159Z.94.image.fits.1

2026-06-26 03:18:12 - drms - INFO: Downloading file 4 of 9...

2026-06-26 03:18:12 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-01-28T21:47:59Z][94][JSOC_20260626_001154]

2026-06-26 03:18:12 - drms - INFO:     filename: aia.lev1_euv_12s.2026-01-28T214759Z.94.image.fits

2026-06-26 03:18:15 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14305_20260128_1000_20260129_0548/94/segment_02_20260128_1524_20260129_0548/aia.lev1_euv_12s.2026-01-28T214759Z.94.image.fits.1

2026-06-26 03:18:15 - drms - INFO: Downloading file 5 of 9...

2026-06-26 03:18:15 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-01-28T23:23:59Z][94][JSOC_20260626_001154]

2026-06-26 03:18:15 - drms - INFO:     filename: aia.lev1_euv_12s.2026-01-28T232359Z.94.image.fits

2026-06-26 03:18:19 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14305_20260128_1000_20260129_0548/94/segment_02_20260128_1524_20260129_0548/aia.lev1_euv_12s.2026-01-28T232359Z.94.image.fits.1

2026-06-26 03:18:19 - drms - INFO: Downloading file 6 of 9...

2026-06-26 03:18:19 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-01-29T00:59:59Z][94][JSOC_20260626_001154]

2026-06-26 03:18:19 - drms - INFO:     filename: aia.lev1_euv_12s.2026-01-29T005959Z.94.image.fits

2026-06-26 03:18:23 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14305_20260128_1000_20260129_0548/94/segment_02_20260128_1524_20260129_0548/aia.lev1_euv_12s.2026-01-29T005959Z.94.image.fits.1

2026-06-26 03:18:23 - drms - INFO: Downloading file 7 of 9...

2026-06-26 03:18:23 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-01-29T02:35:59Z][94][JSOC_20260626_001154]

2026-06-26 03:18:23 - drms - INFO:     filename: aia.lev1_euv_12s.2026-01-29T023559Z.94.image.fits

2026-06-26 03:18:26 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14305_20260128_1000_20260129_0548/94/segment_02_20260128_1524_20260129_0548/aia.lev1_euv_12s.2026-01-29T023559Z.94.image.fits.1

2026-06-26 03:18:26 - drms - INFO: Downloading file 8 of 9...

2026-06-26 03:18:26 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-01-29T04:11:59Z][94][JSOC_20260626_001154]

2026-06-26 03:18:26 - drms - INFO:     filename: aia.lev1_euv_12s.2026-01-29T041159Z.94.image.fits

2026-06-26 03:18:30 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14305_20260128_1000_20260129_0548/94/segment_02_20260128_1524_20260129_0548/aia.lev1_euv_12s.2026-01-29T041159Z.94.image.fits.1

2026-06-26 03:18:30 - drms - INFO: Downloading file 9 of 9...

2026-06-26 03:18:30 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-01-29T05:47:59Z][94][JSOC_20260626_001154]

2026-06-26 03:18:30 - drms - INFO:     filename: aia.lev1_euv_12s.2026-01-29T054759Z.94.image.fits

2026-06-26 03:18:33 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14305_20260128_1000_20260129_0548/94/segment_02_20260128_1524_20260129_0548/aia.lev1_euv_12s.2026-01-29T054759Z.94.image.fits.1

BLOCK ERROR: RuntimeError('Downloaded 94 Å segment does not cover all target timestamps within 180 seconds.')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14305_20260128_1000_20260129_0548,error,13,None,0,None,RuntimeError('Downloaded 94 Å segment does not...

==========================================================================================
BLOCK 113/336 | 2026_HARP14328_20260128_1024_20260129_0300 | targets=11
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14328_20260128_1024_20260129_0300,already_complete,11,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 114/336 | 2026_HARP14332_20260128_1036_20260128_1212 | targets=2
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14332_20260128_1036_20260128_1212,already_complete,2,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 115/336 | 2026_HARP14332_20260128_1600_20260129_0312 | targets=8
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14332_20260128_1600_20260129_0312,already_complete,8,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 116/336 | 2026_HARP14344_20260128_2324_20260129_0548 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14344_20260128_2324_20260129_0548,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 117/336 | 2026_HARP14328_20260129_0612_20260129_0612 | targets=1
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14328_20260129_0612_20260129_0612,already_complete,1,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 118/336 | 2026_HARP14332_20260129_0624_20260129_0624 | targets=1
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14332_20260129_0624_20260129_0624,already_complete,1,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 119/336 | 2026_HARP14328_20260129_1000_20260129_1624 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14328_20260129_1000_20260129_1624,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 120/336 | 2026_HARP14343_20260129_1100_20260130_0300 | targets=11
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14343_20260129_1100_20260130_0300,already_complete,11,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 121/336 | 2026_HARP14305_20260129_1112_20260130_0136 | targets=10
==========================================================================================

----------------------------------------------------------------------
2026_HARP14305_20260129_1112_20260130_0136 | wavelength 94
94 Å cadence segments: 1 [('2026-01-29 11:12:00', '2026-01-30 01:36:00', 10)]
♻️ Segment 1/1 already covered by cached 94 Å files.

----------------------------------------------------------------------
2026_HARP14305_20260129_1112_20260130_0136 | wavelength 131
131 Å cadence segments: 1 [('2026-01-29 11:12:00', '2026-01-30 01:36:00', 10)]
♻️ Segment 1/1 already covered by cached 131 Å files.

----------------------------------------------------------------------
2026_HARP14305_20260129_1112_20260130_0136 | wavelength 171
171 Å cadence segments: 1 [('2026-01-29 11:12:00', '2026-01-30 01:36:00', 10)]
♻️ Segment 1/1 already covered by cached 171 Å files.

----------------------------------------------------------------------
2026_HARP14305_20260129_1112_20260130_0136 | wavelength 193
193 Å cadence segments: 1 [('2026-01-29 11:12:00', '2026-01-30 01:36:00', 10)]
♻️ Segment 1/1 already covered by cached 193 Å files.

----------------------------------------------------------------------
2026_HARP14305_20260129_1112_20260130_0136 | wavelength 211
211 Å cadence segments: 1 [('2026-01-29 11:12:00', '2026-01-30 01:36:00', 10)]
♻️ Segment 1/1 already covered by cached 211 Å files.

----------------------------------------------------------------------
2026_HARP14305_20260129_1112_20260130_0136 | wavelength 335
335 Å cadence segments: 1 [('2026-01-29 11:12:00', '2026-01-30 01:36:00', 10)]

♻️ Segment 1/1 already covered by cached 335 Å files.

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260129_1112_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-126, 1997, -149, 1974), shape=(1834, 1834)')

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260129_1248_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-124, 1988, -141, 1971), shape=(1834, 1834)')

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260129_1424_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-120, 1978, -134, 1964), shape=(1834, 1834)')

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260129_1600_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-116, 1971, -127, 1959), shape=(1834, 1834)')

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260129_1736_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-107, 1961, -117, 1950), shape=(1834, 1834)')

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260129_1912_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-100, 1951, -109, 1941), shape=(1834, 1834)')

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260129_2048_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-97, 1940, -102, 1935), shape=(1834, 1834)')

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260129_2224_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-91, 1931, -96, 1925), shape=(1834, 1834)')

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260130_0000_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-85, 1919, -89, 1915), shape=(1834, 1834)')

/tmp/ipykernel_1170028/1546682576.py:199: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "updated_at_utc": pd.Timestamp.utcnow().isoformat(),

❌ 20260130_0136_HARP14305_NOAA14349 ValueError('Target crop leaves block patch: bounds=(-77, 1907, -86, 1898), shape=(1834, 1834)')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14305_20260129_1112_20260130_0136,completed,10,10,0,0.39,10 sample errors retained for retry

==========================================================================================
BLOCK 122/336 | 2026_HARP14344_20260129_1112_20260130_0624 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14344_20260129_1112_20260130_0624,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 123/336 | 2026_HARP14328_20260129_1936_20260130_0512 | targets=7
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14328_20260129_1936_20260130_0512,already_complete,7,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 124/336 | 2026_HARP14343_20260130_0612_20260130_0612 | targets=1
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14343_20260130_0612_20260130_0612,already_complete,1,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 125/336 | 2026_HARP14328_20260130_0848_20260131_0536 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14328_20260130_0848_20260131_0536,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 126/336 | 2026_HARP14344_20260130_1000_20260130_1624 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14344_20260130_1000_20260130_1624,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 127/336 | 2026_HARP14343_20260130_1124_20260130_1300 | targets=2
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14343_20260130_1124_20260130_1300,already_complete,2,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 128/336 | 2026_HARP14337_20260130_1312_20260130_1624 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14337_20260130_1312_20260130_1624,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 129/336 | 2026_HARP14343_20260130_1612_20260131_0636 | targets=10
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14343_20260130_1612_20260131_0636,already_complete,10,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 130/336 | 2026_HARP14337_20260130_1936_20260131_0512 | targets=7
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14337_20260130_1936_20260131_0512,already_complete,7,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 131/336 | 2026_HARP14344_20260130_1936_20260131_0512 | targets=7
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14344_20260130_1936_20260131_0512,already_complete,7,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 132/336 | 2026_HARP14341_20260131_0048_20260131_0536 | targets=4
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14341_20260131_0048_20260131_0536,already_complete,4,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 133/336 | 2026_HARP14337_20260131_0848_20260201_0748 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14337_20260131_0848_20260201_0748,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 134/336 | 2026_HARP14344_20260131_0848_20260201_0748 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14344_20260131_0848_20260201_0748,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 135/336 | 2026_HARP14328_20260131_0912_20260201_0248 | targets=12
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14328_20260131_0912_20260201_0248,already_complete,12,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 136/336 | 2026_HARP14341_20260131_0912_20260201_0248 | targets=12
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14341_20260131_0912_20260201_0248,already_complete,12,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 137/336 | 2026_HARP14343_20260131_1012_20260201_0912 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14343_20260131_1012_20260201_0912,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 138/336 | 2026_HARP14328_20260201_0812_20260201_1124 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14328_20260201_0812_20260201_1124,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 139/336 | 2026_HARP14341_20260201_0812_20260202_0636 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14341_20260201_0812_20260202_0636,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 140/336 | 2026_HARP14337_20260201_0924_20260202_0748 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14337_20260201_0924_20260202_0748,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 141/336 | 2026_HARP14344_20260201_0924_20260202_0748 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14344_20260201_0924_20260202_0748,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 142/336 | 2026_HARP14343_20260201_1048_20260202_0248 | targets=11
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14343_20260201_1048_20260202_0248,already_complete,11,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 143/336 | 2026_HARP14349_20260202_0700_20260203_0524 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14349_20260202_0700_20260203_0524,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 144/336 | 2026_HARP14343_20260202_0736_20260203_0112 | targets=12
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14343_20260202_0736_20260203_0112,already_complete,12,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 145/336 | 2026_HARP14341_20260202_0812_20260203_0636 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14341_20260202_0812_20260203_0636,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 146/336 | 2026_HARP14355_20260202_0824_20260202_1624 | targets=6
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14355_20260202_0824_20260202_1624,already_complete,6,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 147/336 | 2026_HARP14351_20260202_0912_20260203_0248 | targets=12
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14351_20260202_0912_20260203_0248,already_complete,12,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 148/336 | 2026_HARP14337_20260202_0924_20260203_0748 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14337_20260202_0924_20260203_0748,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 149/336 | 2026_HARP14344_20260202_0924_20260202_1100 | targets=2
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14344_20260202_0924_20260202_1100,already_complete,2,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 150/336 | 2026_HARP14355_20260202_1936_20260203_1624 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14355_20260202_1936_20260203_1624,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 151/336 | 2026_HARP14349_20260203_0700_20260204_0524 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14349_20260203_0700_20260204_0524,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 152/336 | 2026_HARP14351_20260203_0736_20260203_1400 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14351_20260203_0736_20260203_1400,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 153/336 | 2026_HARP14341_20260203_0812_20260204_0636 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14341_20260203_0812_20260204_0636,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 154/336 | 2026_HARP14337_20260203_0924_20260203_1724 | targets=6
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14337_20260203_0924_20260203_1724,already_complete,6,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 155/336 | 2026_HARP14351_20260203_1712_20260204_0424 | targets=8
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14351_20260203_1712_20260204_0424,already_complete,8,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 156/336 | 2026_HARP14355_20260203_1936_20260204_1624 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14355_20260203_1936_20260204_1624,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 157/336 | 2026_HARP14337_20260203_2036_20260203_2348 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14337_20260203_2036_20260203_2348,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 158/336 | 2026_HARP14349_20260204_0700_20260205_0536 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14349_20260204_0700_20260205_0536,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 159/336 | 2026_HARP14351_20260204_0736_20260204_1712 | targets=7
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14351_20260204_0736_20260204_1712,already_complete,7,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 160/336 | 2026_HARP14341_20260204_0812_20260204_1300 | targets=4
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14341_20260204_0812_20260204_1300,already_complete,4,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 161/336 | 2026_HARP14351_20260204_2036_20260205_1548 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14351_20260204_2036_20260205_1548,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 162/336 | 2026_HARP14358_20260204_2112_20260205_1624 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14358_20260204_2112_20260205_1624,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 163/336 | 2026_HARP14355_20260204_2124_20260205_1636 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14355_20260204_2124_20260205_1636,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 164/336 | 2026_HARP14357_20260204_2300_20260205_1636 | targets=12
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14357_20260204_2300_20260205_1636,already_complete,12,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 165/336 | 2026_HARP14349_20260205_0712_20260205_1512 | targets=6
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14349_20260205_0712_20260205_1512,already_complete,6,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 166/336 | 2026_HARP14355_20260205_1948_20260206_1812 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14355_20260205_1948_20260206_1812,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 167/336 | 2026_HARP14357_20260205_1948_20260206_1812 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14357_20260205_1948_20260206_1812,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 168/336 | 2026_HARP14349_20260205_2000_20260206_1824 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14349_20260205_2000_20260206_1824,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 169/336 | 2026_HARP14351_20260205_2036_20260206_1724 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14351_20260205_2036_20260206_1724,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 170/336 | 2026_HARP14358_20260205_2112_20260206_1624 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14358_20260205_2112_20260206_1624,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 171/336 | 2026_HARP14361_20260206_0224_20260207_0048 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14361_20260206_0224_20260207_0048,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 172/336 | 2026_HARP14358_20260206_1936_20260207_1624 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14358_20260206_1936_20260207_1624,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 173/336 | 2026_HARP14355_20260206_1948_20260206_1948 | targets=1
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14355_20260206_1948_20260206_1948,already_complete,1,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 174/336 | 2026_HARP14357_20260206_1948_20260206_2124 | targets=2
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14357_20260206_1948_20260206_2124,already_complete,2,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 175/336 | 2026_HARP14349_20260206_2000_20260206_2000 | targets=1
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14349_20260206_2000_20260206_2000,already_complete,1,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 176/336 | 2026_HARP14357_20260207_0036_20260207_2300 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14357_20260207_0036_20260207_2300,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 177/336 | 2026_HARP14361_20260207_0224_20260207_1336 | targets=8
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14361_20260207_0224_20260207_1336,already_complete,8,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 178/336 | 2026_HARP14361_20260207_1648_20260207_2000 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14361_20260207_1648_20260207_2000,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 179/336 | 2026_HARP14358_20260207_1936_20260208_1624 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14358_20260207_1936_20260208_1624,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 180/336 | 2026_HARP14361_20260207_2312_20260208_2136 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14361_20260207_2312_20260208_2136,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 181/336 | 2026_HARP14357_20260208_0036_20260208_2300 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14357_20260208_0036_20260208_2300,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 182/336 | 2026_HARP14358_20260208_1936_20260209_1312 | targets=12
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14358_20260208_1936_20260209_1312,already_complete,12,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 183/336 | 2026_HARP14361_20260208_2312_20260209_2136 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14361_20260208_2312_20260209_2136,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 184/336 | 2026_HARP14357_20260209_0036_20260209_0836 | targets=6
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14357_20260209_0036_20260209_0836,already_complete,6,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 185/336 | 2026_HARP14361_20260209_2312_20260210_1512 | targets=11
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14361_20260209_2312_20260210_1512,already_complete,11,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 186/336 | 2026_HARP14371_20260210_0048_20260210_1648 | targets=11
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14371_20260210_0048_20260210_1648,already_complete,11,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 187/336 | 2026_HARP14371_20260210_2000_20260211_0848 | targets=9
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14371_20260210_2000_20260211_0848,already_complete,9,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 188/336 | 2026_HARP14371_20260211_1200_20260211_1648 | targets=4
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14371_20260211_1200_20260211_1648,already_complete,4,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 189/336 | 2026_HARP14371_20260211_2024_20260212_0424 | targets=6
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14371_20260211_2024_20260212_0424,already_complete,6,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 190/336 | 2026_HARP14371_20260212_0736_20260213_0424 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14371_20260212_0736_20260213_0424,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 191/336 | 2026_HARP14375_20260213_0500_20260214_0324 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14375_20260213_0500_20260214_0324,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 192/336 | 2026_HARP14371_20260213_0736_20260214_0424 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14371_20260213_0736_20260214_0424,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 193/336 | 2026_HARP14375_20260214_0500_20260215_0324 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14375_20260214_0500_20260215_0324,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 194/336 | 2026_HARP14371_20260214_0736_20260214_1048 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14371_20260214_0736_20260214_1048,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 195/336 | 2026_HARP14379_20260215_0000_20260215_2224 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14379_20260215_0000_20260215_2224,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 196/336 | 2026_HARP14375_20260215_0500_20260216_0324 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14375_20260215_0500_20260216_0324,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 197/336 | 2026_HARP14379_20260216_0000_20260216_2224 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14379_20260216_0000_20260216_2224,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 198/336 | 2026_HARP14375_20260216_0500_20260217_0324 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14375_20260216_0500_20260217_0324,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 199/336 | 2026_HARP14390_20260216_1336_20260217_1200 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14390_20260216_1336_20260217_1200,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 200/336 | 2026_HARP14379_20260217_0000_20260217_1600 | targets=11
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14379_20260217_0000_20260217_1600,already_complete,11,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 201/336 | 2026_HARP14397_20260217_0336_20260217_1448 | targets=8
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14397_20260217_0336_20260217_1448,already_complete,8,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 202/336 | 2026_HARP14375_20260217_0500_20260217_1612 | targets=8
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14375_20260217_0500_20260217_1612,already_complete,8,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 203/336 | 2026_HARP14390_20260217_1336_20260217_1648 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14390_20260217_1336_20260217_1648,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 204/336 | 2026_HARP14392_20260217_1724_20260217_1724 | targets=1
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14392_20260217_1724_20260217_1724,already_complete,1,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 205/336 | 2026_HARP14390_20260217_2124_20260218_1812 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14390_20260217_2124_20260218_1812,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 206/336 | 2026_HARP14392_20260217_2200_20260218_0424 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14392_20260217_2200_20260218_0424,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 207/336 | 2026_HARP14379_20260217_2212_20260218_1724 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14379_20260217_2212_20260218_1724,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 208/336 | 2026_HARP14397_20260217_2236_20260218_1748 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14397_20260217_2236_20260218_1748,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 209/336 | 2026_HARP14392_20260218_0736_20260218_1712 | targets=7
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14392_20260218_0736_20260218_1712,already_complete,7,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 210/336 | 2026_HARP14379_20260219_0024_20260219_1448 | targets=10
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14379_20260219_0024_20260219_1448,already_complete,10,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 211/336 | 2026_HARP14390_20260219_0112_20260219_0424 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14390_20260219_0112_20260219_0424,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 212/336 | 2026_HARP14392_20260219_0148_20260219_1436 | targets=9
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14392_20260219_0148_20260219_1436,already_complete,9,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 213/336 | 2026_HARP14397_20260219_0248_20260219_0424 | targets=2
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14397_20260219_0248_20260219_0424,already_complete,2,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 214/336 | 2026_HARP14390_20260219_0736_20260220_0424 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14390_20260219_0736_20260220_0424,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 215/336 | 2026_HARP14397_20260219_0736_20260220_0424 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14397_20260219_0736_20260220_0424,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 216/336 | 2026_HARP14392_20260219_1924_20260220_1612 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14392_20260219_1924_20260220_1612,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 217/336 | 2026_HARP14390_20260220_0736_20260220_1536 | targets=6
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14390_20260220_0736_20260220_1536,already_complete,6,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 218/336 | 2026_HARP14397_20260220_0736_20260220_1536 | targets=6
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14397_20260220_0736_20260220_1536,already_complete,6,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 219/336 | 2026_HARP14392_20260220_1936_20260220_1936 | targets=1
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14392_20260220_1936_20260220_1936,already_complete,1,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 220/336 | 2026_HARP14397_20260220_2212_20260221_1900 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14397_20260220_2212_20260221_1900,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 221/336 | 2026_HARP14392_20260220_2248_20260221_1624 | targets=12
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14392_20260220_2248_20260221_1624,already_complete,12,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 222/336 | 2026_HARP14392_20260221_1936_20260222_0336 | targets=6
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14392_20260221_1936_20260222_0336,already_complete,6,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 223/336 | 2026_HARP14445_20260227_0036_20260227_2300 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14445_20260227_0036_20260227_2300,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 224/336 | 2026_HARP14453_20260227_1536_20260227_2024 | targets=4
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14453_20260227_1536_20260227_2024,already_complete,4,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 225/336 | 2026_HARP14453_20260227_2336_20260228_0424 | targets=4
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14453_20260227_2336_20260228_0424,already_complete,4,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 226/336 | 2026_HARP14445_20260228_0036_20260228_2300 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14445_20260228_0036_20260228_2300,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 227/336 | 2026_HARP14453_20260228_0736_20260228_1536 | targets=6
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14453_20260228_0736_20260228_1536,already_complete,6,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 228/336 | 2026_HARP14445_20260301_0036_20260301_2300 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14445_20260301_0036_20260301_2300,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 229/336 | 2026_HARP14439_20260301_1612_20260302_1436 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14439_20260301_1612_20260302_1436,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 230/336 | 2026_HARP14445_20260302_0036_20260302_1500 | targets=10
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14445_20260302_0036_20260302_1500,already_complete,10,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 231/336 | 2026_HARP14438_20260302_0712_20260302_1512 | targets=6
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14438_20260302_0712_20260302_1512,already_complete,6,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 232/336 | 2026_HARP14439_20260302_1748_20260303_1612 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14439_20260302_1748_20260303_1612,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 233/336 | 2026_HARP14445_20260302_1812_20260303_1012 | targets=11
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14445_20260302_1812_20260303_1012,already_complete,11,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 234/336 | 2026_HARP14438_20260302_1824_20260303_1648 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14438_20260302_1824_20260303_1648,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 235/336 | 2026_HARP14445_20260303_1500_20260303_1500 | targets=1
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14445_20260303_1500_20260303_1500,already_complete,1,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 236/336 | 2026_HARP14439_20260303_1748_20260304_1436 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14439_20260303_1748_20260304_1436,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 237/336 | 2026_HARP14438_20260303_1824_20260304_1648 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14438_20260303_1824_20260304_1648,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 238/336 | 2026_HARP14439_20260304_1748_20260305_1624 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14439_20260304_1748_20260305_1624,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 239/336 | 2026_HARP14438_20260304_1824_20260305_1700 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14438_20260304_1824_20260305_1700,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 240/336 | 2026_HARP14448_20260304_1936_20260305_1624 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14448_20260304_1936_20260305_1624,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 241/336 | 2026_HARP14465_20260305_0112_20260305_0424 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14465_20260305_0112_20260305_0424,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 242/336 | 2026_HARP14465_20260305_0736_20260305_2336 | targets=11
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14465_20260305_0736_20260305_2336,already_complete,11,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 243/336 | 2026_HARP14438_20260305_1836_20260305_2324 | targets=4
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14438_20260305_1836_20260305_2324,already_complete,4,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 244/336 | 2026_HARP14439_20260305_1936_20260305_2248 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14439_20260305_1936_20260305_2248,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 245/336 | 2026_HARP14448_20260305_1936_20260305_2248 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14448_20260305_1936_20260305_2248,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 246/336 | 2026_HARP14465_20260306_2100_20260307_1924 | targets=15
==========================================================================================

----------------------------------------------------------------------
2026_HARP14465_20260306_2100_20260307_1924 | wavelength 94
94 Å cadence segments: 1 [('2026-03-06 21:00:00', '2026-03-07 19:24:00', 15)]
Segment query: aia.lev1_euv_12s[2026-03-06T21:00:00.000/1440m@96m][94]{image}
Segment reference: 2026-03-07 08:12:00 | targets: 15 | patch arcsec: 393.0381016306207
JSOC export attempt 1/10

2026-06-26 03:23:21 - drms - INFO: Export request pending. [id=JSOC_20260625_002374, status=2]

2026-06-26 03:23:21 - drms - INFO: Waiting for 15 seconds...

2026-06-26 03:23:37 - drms - INFO: Export request finished. [id=JSOC_20260625_002374, status=0]

2026-06-26 03:23:37 - drms - INFO: Downloading file 1 of 12...

2026-06-26 03:23:37 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-07T01:47:59Z][94][JSOC_20260625_002374]

2026-06-26 03:23:37 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-07T014759Z.94.image.fits

2026-06-26 03:23:38 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14465_20260306_2100_20260307_1924/94/segment_01_20260306_2100_20260307_1924/aia.lev1_euv_12s.2026-03-07T014759Z.94.image.fits.1

2026-06-26 03:23:38 - drms - INFO: Downloading file 2 of 12...

2026-06-26 03:23:38 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-07T03:23:59Z][94][JSOC_20260625_002374]

2026-06-26 03:23:38 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-07T032359Z.94.image.fits

2026-06-26 03:23:40 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14465_20260306_2100_20260307_1924/94/segment_01_20260306_2100_20260307_1924/aia.lev1_euv_12s.2026-03-07T032359Z.94.image.fits.1

2026-06-26 03:23:40 - drms - INFO: Downloading file 3 of 12...

2026-06-26 03:23:40 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-07T04:59:59Z][94][JSOC_20260625_002374]

2026-06-26 03:23:40 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-07T045959Z.94.image.fits

2026-06-26 03:23:41 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14465_20260306_2100_20260307_1924/94/segment_01_20260306_2100_20260307_1924/aia.lev1_euv_12s.2026-03-07T045959Z.94.image.fits.1

2026-06-26 03:23:41 - drms - INFO: Downloading file 4 of 12...

2026-06-26 03:23:41 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-07T06:35:59Z][94][JSOC_20260625_002374]

2026-06-26 03:23:41 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-07T063559Z.94.image.fits

2026-06-26 03:23:43 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14465_20260306_2100_20260307_1924/94/segment_01_20260306_2100_20260307_1924/aia.lev1_euv_12s.2026-03-07T063559Z.94.image.fits.1

2026-06-26 03:23:43 - drms - INFO: Downloading file 5 of 12...

2026-06-26 03:23:43 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-07T08:11:59Z][94][JSOC_20260625_002374]

2026-06-26 03:23:43 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-07T081159Z.94.image.fits

2026-06-26 03:23:45 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14465_20260306_2100_20260307_1924/94/segment_01_20260306_2100_20260307_1924/aia.lev1_euv_12s.2026-03-07T081159Z.94.image.fits.1

2026-06-26 03:23:45 - drms - INFO: Downloading file 6 of 12...

2026-06-26 03:23:45 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-07T09:47:59Z][94][JSOC_20260625_002374]

2026-06-26 03:23:45 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-07T094759Z.94.image.fits

2026-06-26 03:23:46 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14465_20260306_2100_20260307_1924/94/segment_01_20260306_2100_20260307_1924/aia.lev1_euv_12s.2026-03-07T094759Z.94.image.fits.1

2026-06-26 03:23:46 - drms - INFO: Downloading file 7 of 12...

2026-06-26 03:23:46 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-07T11:23:59Z][94][JSOC_20260625_002374]

2026-06-26 03:23:46 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-07T112359Z.94.image.fits

2026-06-26 03:23:48 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14465_20260306_2100_20260307_1924/94/segment_01_20260306_2100_20260307_1924/aia.lev1_euv_12s.2026-03-07T112359Z.94.image.fits.1

2026-06-26 03:23:48 - drms - INFO: Downloading file 8 of 12...

2026-06-26 03:23:48 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-07T12:59:59Z][94][JSOC_20260625_002374]

2026-06-26 03:23:48 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-07T125959Z.94.image.fits

2026-06-26 03:23:49 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14465_20260306_2100_20260307_1924/94/segment_01_20260306_2100_20260307_1924/aia.lev1_euv_12s.2026-03-07T125959Z.94.image.fits.1

2026-06-26 03:23:49 - drms - INFO: Downloading file 9 of 12...

2026-06-26 03:23:49 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-07T14:35:59Z][94][JSOC_20260625_002374]

2026-06-26 03:23:49 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-07T143559Z.94.image.fits

2026-06-26 03:23:51 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14465_20260306_2100_20260307_1924/94/segment_01_20260306_2100_20260307_1924/aia.lev1_euv_12s.2026-03-07T143559Z.94.image.fits.1

2026-06-26 03:23:51 - drms - INFO: Downloading file 10 of 12...

2026-06-26 03:23:51 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-07T16:11:59Z][94][JSOC_20260625_002374]

2026-06-26 03:23:51 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-07T161159Z.94.image.fits

2026-06-26 03:23:52 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14465_20260306_2100_20260307_1924/94/segment_01_20260306_2100_20260307_1924/aia.lev1_euv_12s.2026-03-07T161159Z.94.image.fits.1

2026-06-26 03:23:52 - drms - INFO: Downloading file 11 of 12...

2026-06-26 03:23:52 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-07T17:47:59Z][94][JSOC_20260625_002374]

2026-06-26 03:23:52 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-07T174759Z.94.image.fits

2026-06-26 03:23:54 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14465_20260306_2100_20260307_1924/94/segment_01_20260306_2100_20260307_1924/aia.lev1_euv_12s.2026-03-07T174759Z.94.image.fits.1

2026-06-26 03:23:54 - drms - INFO: Downloading file 12 of 12...

2026-06-26 03:23:54 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-07T19:23:59Z][94][JSOC_20260625_002374]

2026-06-26 03:23:54 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-07T192359Z.94.image.fits

2026-06-26 03:23:55 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14465_20260306_2100_20260307_1924/94/segment_01_20260306_2100_20260307_1924/aia.lev1_euv_12s.2026-03-07T192359Z.94.image.fits.1

BLOCK ERROR: RuntimeError('Downloaded 94 Å segment does not cover all target timestamps within 180 seconds.')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14465_20260306_2100_20260307_1924,error,15,None,0,None,RuntimeError('Downloaded 94 Å segment does not...

==========================================================================================
BLOCK 247/336 | 2026_HARP14471_20260306_2124_20260307_1948 | targets=15
==========================================================================================

----------------------------------------------------------------------
2026_HARP14471_20260306_2124_20260307_1948 | wavelength 94
94 Å cadence segments: 1 [('2026-03-06 21:24:00', '2026-03-07 19:48:00', 15)]
Segment query: aia.lev1_euv_12s[2026-03-06T21:24:00.000/1440m@96m][94]{image}
Segment reference: 2026-03-07 08:36:00 | targets: 15 | patch arcsec: 417.0281421511818
JSOC export attempt 1/10

2026-06-26 03:23:59 - drms - INFO: Export request pending. [id=JSOC_20260625_002389, status=2]

2026-06-26 03:23:59 - drms - INFO: Waiting for 15 seconds...

2026-06-26 03:24:15 - drms - INFO: Export request finished. [id=JSOC_20260625_002389, status=0]

2026-06-26 03:24:15 - drms - INFO: Downloading file 1 of 12...

2026-06-26 03:24:15 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-07T02:11:59Z][94][JSOC_20260625_002389]

2026-06-26 03:24:15 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-07T021159Z.94.image.fits

2026-06-26 03:24:16 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14471_20260306_2124_20260307_1948/94/segment_01_20260306_2124_20260307_1948/aia.lev1_euv_12s.2026-03-07T021159Z.94.image.fits.1

2026-06-26 03:24:16 - drms - INFO: Downloading file 2 of 12...

2026-06-26 03:24:16 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-07T03:47:59Z][94][JSOC_20260625_002389]

2026-06-26 03:24:16 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-07T034759Z.94.image.fits

2026-06-26 03:24:18 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14471_20260306_2124_20260307_1948/94/segment_01_20260306_2124_20260307_1948/aia.lev1_euv_12s.2026-03-07T034759Z.94.image.fits.1

2026-06-26 03:24:18 - drms - INFO: Downloading file 3 of 12...

2026-06-26 03:24:18 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-07T05:23:59Z][94][JSOC_20260625_002389]

2026-06-26 03:24:18 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-07T052359Z.94.image.fits

2026-06-26 03:24:20 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14471_20260306_2124_20260307_1948/94/segment_01_20260306_2124_20260307_1948/aia.lev1_euv_12s.2026-03-07T052359Z.94.image.fits.1

2026-06-26 03:24:20 - drms - INFO: Downloading file 4 of 12...

2026-06-26 03:24:20 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-07T06:59:59Z][94][JSOC_20260625_002389]

2026-06-26 03:24:20 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-07T065959Z.94.image.fits

2026-06-26 03:24:21 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14471_20260306_2124_20260307_1948/94/segment_01_20260306_2124_20260307_1948/aia.lev1_euv_12s.2026-03-07T065959Z.94.image.fits.1

2026-06-26 03:24:21 - drms - INFO: Downloading file 5 of 12...

2026-06-26 03:24:21 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-07T08:35:59Z][94][JSOC_20260625_002389]

2026-06-26 03:24:21 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-07T083559Z.94.image.fits

2026-06-26 03:24:23 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14471_20260306_2124_20260307_1948/94/segment_01_20260306_2124_20260307_1948/aia.lev1_euv_12s.2026-03-07T083559Z.94.image.fits.1

2026-06-26 03:24:23 - drms - INFO: Downloading file 6 of 12...

2026-06-26 03:24:23 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-07T10:11:59Z][94][JSOC_20260625_002389]

2026-06-26 03:24:23 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-07T101159Z.94.image.fits

2026-06-26 03:24:25 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14471_20260306_2124_20260307_1948/94/segment_01_20260306_2124_20260307_1948/aia.lev1_euv_12s.2026-03-07T101159Z.94.image.fits.1

2026-06-26 03:24:25 - drms - INFO: Downloading file 7 of 12...

2026-06-26 03:24:25 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-07T11:47:59Z][94][JSOC_20260625_002389]

2026-06-26 03:24:25 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-07T114759Z.94.image.fits

2026-06-26 03:24:26 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14471_20260306_2124_20260307_1948/94/segment_01_20260306_2124_20260307_1948/aia.lev1_euv_12s.2026-03-07T114759Z.94.image.fits.1

2026-06-26 03:24:26 - drms - INFO: Downloading file 8 of 12...

2026-06-26 03:24:26 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-07T13:23:59Z][94][JSOC_20260625_002389]

2026-06-26 03:24:26 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-07T132359Z.94.image.fits

2026-06-26 03:24:28 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14471_20260306_2124_20260307_1948/94/segment_01_20260306_2124_20260307_1948/aia.lev1_euv_12s.2026-03-07T132359Z.94.image.fits.1

2026-06-26 03:24:28 - drms - INFO: Downloading file 9 of 12...

2026-06-26 03:24:28 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-07T14:59:59Z][94][JSOC_20260625_002389]

2026-06-26 03:24:28 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-07T145959Z.94.image.fits

2026-06-26 03:24:29 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14471_20260306_2124_20260307_1948/94/segment_01_20260306_2124_20260307_1948/aia.lev1_euv_12s.2026-03-07T145959Z.94.image.fits.1

2026-06-26 03:24:29 - drms - INFO: Downloading file 10 of 12...

2026-06-26 03:24:29 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-07T16:35:59Z][94][JSOC_20260625_002389]

2026-06-26 03:24:29 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-07T163559Z.94.image.fits

2026-06-26 03:24:31 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14471_20260306_2124_20260307_1948/94/segment_01_20260306_2124_20260307_1948/aia.lev1_euv_12s.2026-03-07T163559Z.94.image.fits.1

2026-06-26 03:24:31 - drms - INFO: Downloading file 11 of 12...

2026-06-26 03:24:31 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-07T18:11:59Z][94][JSOC_20260625_002389]

2026-06-26 03:24:31 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-07T181159Z.94.image.fits

2026-06-26 03:24:33 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14471_20260306_2124_20260307_1948/94/segment_01_20260306_2124_20260307_1948/aia.lev1_euv_12s.2026-03-07T181159Z.94.image.fits.1

2026-06-26 03:24:33 - drms - INFO: Downloading file 12 of 12...

2026-06-26 03:24:33 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-07T19:47:59Z][94][JSOC_20260625_002389]

2026-06-26 03:24:33 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-07T194759Z.94.image.fits

2026-06-26 03:24:34 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14471_20260306_2124_20260307_1948/94/segment_01_20260306_2124_20260307_1948/aia.lev1_euv_12s.2026-03-07T194759Z.94.image.fits.1

BLOCK ERROR: RuntimeError('Downloaded 94 Å segment does not cover all target timestamps within 180 seconds.')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14471_20260306_2124_20260307_1948,error,15,None,0,None,RuntimeError('Downloaded 94 Å segment does not...

==========================================================================================
BLOCK 248/336 | 2026_HARP14448_20260306_2148_20260307_2012 | targets=15
==========================================================================================

----------------------------------------------------------------------
2026_HARP14448_20260306_2148_20260307_2012 | wavelength 94
94 Å cadence segments: 1 [('2026-03-06 21:48:00', '2026-03-07 20:12:00', 15)]
Segment query: aia.lev1_euv_12s[2026-03-06T21:48:00.000/1440m@96m][94]{image}
Segment reference: 2026-03-07 09:00:00 | targets: 15 | patch arcsec: 1072.1794972653815
JSOC export attempt 1/10

2026-06-26 03:24:38 - drms - INFO: Export request pending. [id=JSOC_20260625_002404, status=2]

2026-06-26 03:24:38 - drms - INFO: Waiting for 15 seconds...

2026-06-26 03:24:54 - drms - INFO: Export request finished. [id=JSOC_20260625_002404, status=0]

2026-06-26 03:24:54 - drms - INFO: Downloading file 1 of 12...

2026-06-26 03:24:54 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-07T02:35:59Z][94][JSOC_20260625_002404]

2026-06-26 03:24:54 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-07T023559Z.94.image.fits

2026-06-26 03:24:57 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14448_20260306_2148_20260307_2012/94/segment_01_20260306_2148_20260307_2012/aia.lev1_euv_12s.2026-03-07T023559Z.94.image.fits.1

2026-06-26 03:24:57 - drms - INFO: Downloading file 2 of 12...

2026-06-26 03:24:57 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-07T04:11:59Z][94][JSOC_20260625_002404]

2026-06-26 03:24:57 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-07T041159Z.94.image.fits

2026-06-26 03:25:00 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14448_20260306_2148_20260307_2012/94/segment_01_20260306_2148_20260307_2012/aia.lev1_euv_12s.2026-03-07T041159Z.94.image.fits.1

2026-06-26 03:25:00 - drms - INFO: Downloading file 3 of 12...

2026-06-26 03:25:00 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-07T05:47:59Z][94][JSOC_20260625_002404]

2026-06-26 03:25:00 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-07T054759Z.94.image.fits

2026-06-26 03:25:03 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14448_20260306_2148_20260307_2012/94/segment_01_20260306_2148_20260307_2012/aia.lev1_euv_12s.2026-03-07T054759Z.94.image.fits.1

2026-06-26 03:25:03 - drms - INFO: Downloading file 4 of 12...

2026-06-26 03:25:03 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-07T07:23:59Z][94][JSOC_20260625_002404]

2026-06-26 03:25:03 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-07T072359Z.94.image.fits

2026-06-26 03:25:07 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14448_20260306_2148_20260307_2012/94/segment_01_20260306_2148_20260307_2012/aia.lev1_euv_12s.2026-03-07T072359Z.94.image.fits.1

2026-06-26 03:25:07 - drms - INFO: Downloading file 5 of 12...

2026-06-26 03:25:07 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-07T08:59:59Z][94][JSOC_20260625_002404]

2026-06-26 03:25:07 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-07T085959Z.94.image.fits

2026-06-26 03:25:10 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14448_20260306_2148_20260307_2012/94/segment_01_20260306_2148_20260307_2012/aia.lev1_euv_12s.2026-03-07T085959Z.94.image.fits.1

2026-06-26 03:25:10 - drms - INFO: Downloading file 6 of 12...

2026-06-26 03:25:10 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-07T10:35:59Z][94][JSOC_20260625_002404]

2026-06-26 03:25:10 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-07T103559Z.94.image.fits

2026-06-26 03:25:13 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14448_20260306_2148_20260307_2012/94/segment_01_20260306_2148_20260307_2012/aia.lev1_euv_12s.2026-03-07T103559Z.94.image.fits.1

2026-06-26 03:25:13 - drms - INFO: Downloading file 7 of 12...

2026-06-26 03:25:13 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-07T12:11:59Z][94][JSOC_20260625_002404]

2026-06-26 03:25:13 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-07T121159Z.94.image.fits

2026-06-26 03:25:16 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14448_20260306_2148_20260307_2012/94/segment_01_20260306_2148_20260307_2012/aia.lev1_euv_12s.2026-03-07T121159Z.94.image.fits.1

2026-06-26 03:25:16 - drms - INFO: Downloading file 8 of 12...

2026-06-26 03:25:16 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-07T13:47:59Z][94][JSOC_20260625_002404]

2026-06-26 03:25:16 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-07T134759Z.94.image.fits

2026-06-26 03:25:20 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14448_20260306_2148_20260307_2012/94/segment_01_20260306_2148_20260307_2012/aia.lev1_euv_12s.2026-03-07T134759Z.94.image.fits.1

2026-06-26 03:25:20 - drms - INFO: Downloading file 9 of 12...

2026-06-26 03:25:20 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-07T15:23:59Z][94][JSOC_20260625_002404]

2026-06-26 03:25:20 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-07T152359Z.94.image.fits

2026-06-26 03:25:23 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14448_20260306_2148_20260307_2012/94/segment_01_20260306_2148_20260307_2012/aia.lev1_euv_12s.2026-03-07T152359Z.94.image.fits.1

2026-06-26 03:25:23 - drms - INFO: Downloading file 10 of 12...

2026-06-26 03:25:23 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-07T16:59:59Z][94][JSOC_20260625_002404]

2026-06-26 03:25:23 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-07T165959Z.94.image.fits

2026-06-26 03:25:26 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14448_20260306_2148_20260307_2012/94/segment_01_20260306_2148_20260307_2012/aia.lev1_euv_12s.2026-03-07T165959Z.94.image.fits.1

2026-06-26 03:25:26 - drms - INFO: Downloading file 11 of 12...

2026-06-26 03:25:26 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-07T18:35:59Z][94][JSOC_20260625_002404]

2026-06-26 03:25:26 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-07T183559Z.94.image.fits

2026-06-26 03:25:29 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14448_20260306_2148_20260307_2012/94/segment_01_20260306_2148_20260307_2012/aia.lev1_euv_12s.2026-03-07T183559Z.94.image.fits.1

2026-06-26 03:25:29 - drms - INFO: Downloading file 12 of 12...

2026-06-26 03:25:29 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-07T20:11:59Z][94][JSOC_20260625_002404]

2026-06-26 03:25:29 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-07T201159Z.94.image.fits

2026-06-26 03:25:33 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14448_20260306_2148_20260307_2012/94/segment_01_20260306_2148_20260307_2012/aia.lev1_euv_12s.2026-03-07T201159Z.94.image.fits.1

BLOCK ERROR: RuntimeError('Downloaded 94 Å segment does not cover all target timestamps within 180 seconds.')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14448_20260306_2148_20260307_2012,error,15,None,0,None,RuntimeError('Downloaded 94 Å segment does not...

==========================================================================================
BLOCK 249/336 | 2026_HARP14465_20260307_2100_20260308_1924 | targets=15
==========================================================================================

----------------------------------------------------------------------
2026_HARP14465_20260307_2100_20260308_1924 | wavelength 94
94 Å cadence segments: 1 [('2026-03-07 21:00:00', '2026-03-08 19:24:00', 15)]
♻️ Segment 1/1 already covered by cached 94 Å files.

----------------------------------------------------------------------
2026_HARP14465_20260307_2100_20260308_1924 | wavelength 131
131 Å cadence segments: 1 [('2026-03-07 21:00:00', '2026-03-08 19:24:00', 15)]
♻️ Segment 1/1 already covered by cached 131 Å files.

----------------------------------------------------------------------
2026_HARP14465_20260307_2100_20260308_1924 | wavelength 171
171 Å cadence segments: 1 [('2026-03-07 21:00:00', '2026-03-08 19:24:00', 15)]
♻️ Segment 1/1 already covered by cached 171 Å files.

----------------------------------------------------------------------
2026_HARP14465_20260307_2100_20260308_1924 | wavelength 193
193 Å cadence segments: 1 [('2026-03-07 21:00:00', '2026-03-08 19:24:00', 15)]
Segment query: aia.lev1_euv_12s[2026-03-07T21:00:00.000/1440m@96m][193]{image}
Segment reference: 2026-03-08 08:12:00 | targets: 15 | patch arcsec: 385.7513118796153
JSOC export attempt 1/10

2026-06-26 03:25:38 - drms - INFO: Export request pending. [id=JSOC_20260625_002483, status=2]

2026-06-26 03:25:38 - drms - INFO: Waiting for 15 seconds...

2026-06-26 03:25:53 - drms - INFO: Export request finished. [id=JSOC_20260625_002483, status=0]

2026-06-26 03:25:53 - drms - INFO: Downloading file 1 of 13...

2026-06-26 03:25:53 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-08T00:11:59Z][193][JSOC_20260625_002483]

2026-06-26 03:25:53 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-08T001159Z.193.image.fits

2026-06-26 03:25:55 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14465_20260307_2100_20260308_1924/193/segment_01_20260307_2100_20260308_1924/aia.lev1_euv_12s.2026-03-08T001159Z.193.image.fits.1

2026-06-26 03:25:55 - drms - INFO: Downloading file 2 of 13...

2026-06-26 03:25:55 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-08T01:47:59Z][193][JSOC_20260625_002483]

2026-06-26 03:25:55 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-08T014759Z.193.image.fits

2026-06-26 03:25:57 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14465_20260307_2100_20260308_1924/193/segment_01_20260307_2100_20260308_1924/aia.lev1_euv_12s.2026-03-08T014759Z.193.image.fits.1

2026-06-26 03:25:57 - drms - INFO: Downloading file 3 of 13...

2026-06-26 03:25:57 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-08T03:23:59Z][193][JSOC_20260625_002483]

2026-06-26 03:25:57 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-08T032359Z.193.image.fits

2026-06-26 03:25:58 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14465_20260307_2100_20260308_1924/193/segment_01_20260307_2100_20260308_1924/aia.lev1_euv_12s.2026-03-08T032359Z.193.image.fits.1

2026-06-26 03:25:58 - drms - INFO: Downloading file 4 of 13...

2026-06-26 03:25:58 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-08T04:59:59Z][193][JSOC_20260625_002483]

2026-06-26 03:25:58 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-08T045959Z.193.image.fits

2026-06-26 03:26:00 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14465_20260307_2100_20260308_1924/193/segment_01_20260307_2100_20260308_1924/aia.lev1_euv_12s.2026-03-08T045959Z.193.image.fits.1

2026-06-26 03:26:00 - drms - INFO: Downloading file 5 of 13...

2026-06-26 03:26:00 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-08T06:35:59Z][193][JSOC_20260625_002483]

2026-06-26 03:26:00 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-08T063559Z.193.image.fits

2026-06-26 03:26:01 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14465_20260307_2100_20260308_1924/193/segment_01_20260307_2100_20260308_1924/aia.lev1_euv_12s.2026-03-08T063559Z.193.image.fits.1

2026-06-26 03:26:01 - drms - INFO: Downloading file 6 of 13...

2026-06-26 03:26:01 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-08T08:11:59Z][193][JSOC_20260625_002483]

2026-06-26 03:26:01 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-08T081159Z.193.image.fits

2026-06-26 03:26:03 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14465_20260307_2100_20260308_1924/193/segment_01_20260307_2100_20260308_1924/aia.lev1_euv_12s.2026-03-08T081159Z.193.image.fits.1

2026-06-26 03:26:03 - drms - INFO: Downloading file 7 of 13...

2026-06-26 03:26:03 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-08T09:47:59Z][193][JSOC_20260625_002483]

2026-06-26 03:26:03 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-08T094759Z.193.image.fits

2026-06-26 03:26:04 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14465_20260307_2100_20260308_1924/193/segment_01_20260307_2100_20260308_1924/aia.lev1_euv_12s.2026-03-08T094759Z.193.image.fits.1

2026-06-26 03:26:04 - drms - INFO: Downloading file 8 of 13...

2026-06-26 03:26:04 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-08T11:23:59Z][193][JSOC_20260625_002483]

2026-06-26 03:26:04 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-08T112359Z.193.image.fits

2026-06-26 03:26:06 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14465_20260307_2100_20260308_1924/193/segment_01_20260307_2100_20260308_1924/aia.lev1_euv_12s.2026-03-08T112359Z.193.image.fits.1

2026-06-26 03:26:06 - drms - INFO: Downloading file 9 of 13...

2026-06-26 03:26:06 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-08T12:59:59Z][193][JSOC_20260625_002483]

2026-06-26 03:26:06 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-08T125959Z.193.image.fits

2026-06-26 03:26:08 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14465_20260307_2100_20260308_1924/193/segment_01_20260307_2100_20260308_1924/aia.lev1_euv_12s.2026-03-08T125959Z.193.image.fits.1

2026-06-26 03:26:08 - drms - INFO: Downloading file 10 of 13...

2026-06-26 03:26:08 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-08T14:35:59Z][193][JSOC_20260625_002483]

2026-06-26 03:26:08 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-08T143559Z.193.image.fits

2026-06-26 03:26:09 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14465_20260307_2100_20260308_1924/193/segment_01_20260307_2100_20260308_1924/aia.lev1_euv_12s.2026-03-08T143559Z.193.image.fits.1

2026-06-26 03:26:09 - drms - INFO: Downloading file 11 of 13...

2026-06-26 03:26:09 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-08T16:11:59Z][193][JSOC_20260625_002483]

2026-06-26 03:26:09 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-08T161159Z.193.image.fits

2026-06-26 03:26:11 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14465_20260307_2100_20260308_1924/193/segment_01_20260307_2100_20260308_1924/aia.lev1_euv_12s.2026-03-08T161159Z.193.image.fits.1

2026-06-26 03:26:11 - drms - INFO: Downloading file 12 of 13...

2026-06-26 03:26:11 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-08T17:47:59Z][193][JSOC_20260625_002483]

2026-06-26 03:26:11 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-08T174759Z.193.image.fits

2026-06-26 03:26:12 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14465_20260307_2100_20260308_1924/193/segment_01_20260307_2100_20260308_1924/aia.lev1_euv_12s.2026-03-08T174759Z.193.image.fits.1

2026-06-26 03:26:12 - drms - INFO: Downloading file 13 of 13...

2026-06-26 03:26:12 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-08T19:23:59Z][193][JSOC_20260625_002483]

2026-06-26 03:26:12 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-08T192359Z.193.image.fits

2026-06-26 03:26:14 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14465_20260307_2100_20260308_1924/193/segment_01_20260307_2100_20260308_1924/aia.lev1_euv_12s.2026-03-08T192359Z.193.image.fits.1

BLOCK ERROR: RuntimeError('Downloaded 193 Å segment does not cover all target timestamps within 180 seconds.')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14465_20260307_2100_20260308_1924,error,15,None,0,None,RuntimeError('Downloaded 193 Å segment does no...

==========================================================================================
BLOCK 250/336 | 2026_HARP14471_20260307_2124_20260308_1948 | targets=15
==========================================================================================

----------------------------------------------------------------------
2026_HARP14471_20260307_2124_20260308_1948 | wavelength 94
94 Å cadence segments: 1 [('2026-03-07 21:24:00', '2026-03-08 19:48:00', 15)]
♻️ Segment 1/1 already covered by cached 94 Å files.

----------------------------------------------------------------------
2026_HARP14471_20260307_2124_20260308_1948 | wavelength 131
131 Å cadence segments: 1 [('2026-03-07 21:24:00', '2026-03-08 19:48:00', 15)]
♻️ Segment 1/1 already covered by cached 131 Å files.

----------------------------------------------------------------------
2026_HARP14471_20260307_2124_20260308_1948 | wavelength 171
171 Å cadence segments: 1 [('2026-03-07 21:24:00', '2026-03-08 19:48:00', 15)]
♻️ Segment 1/1 already covered by cached 171 Å files.

----------------------------------------------------------------------
2026_HARP14471_20260307_2124_20260308_1948 | wavelength 193
193 Å cadence segments: 1 [('2026-03-07 21:24:00', '2026-03-08 19:48:00', 15)]
Segment query: aia.lev1_euv_12s[2026-03-07T21:24:00.000/1440m@96m][193]{image}
Segment reference: 2026-03-08 08:36:00 | targets: 15 | patch arcsec: 412.69127684904424
JSOC export attempt 1/10

2026-06-26 03:26:19 - drms - INFO: Export request pending. [id=JSOC_20260625_002551, status=2]

2026-06-26 03:26:19 - drms - INFO: Waiting for 15 seconds...

2026-06-26 03:26:34 - drms - INFO: Export request finished. [id=JSOC_20260625_002551, status=0]

2026-06-26 03:26:34 - drms - INFO: Downloading file 1 of 13...

2026-06-26 03:26:34 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-08T00:35:59Z][193][JSOC_20260625_002551]

2026-06-26 03:26:34 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-08T003559Z.193.image.fits

2026-06-26 03:26:36 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14471_20260307_2124_20260308_1948/193/segment_01_20260307_2124_20260308_1948/aia.lev1_euv_12s.2026-03-08T003559Z.193.image.fits.1

2026-06-26 03:26:36 - drms - INFO: Downloading file 2 of 13...

2026-06-26 03:26:36 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-08T02:11:59Z][193][JSOC_20260625_002551]

2026-06-26 03:26:36 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-08T021159Z.193.image.fits

2026-06-26 03:26:38 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14471_20260307_2124_20260308_1948/193/segment_01_20260307_2124_20260308_1948/aia.lev1_euv_12s.2026-03-08T021159Z.193.image.fits.1

2026-06-26 03:26:38 - drms - INFO: Downloading file 3 of 13...

2026-06-26 03:26:38 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-08T03:47:59Z][193][JSOC_20260625_002551]

2026-06-26 03:26:38 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-08T034759Z.193.image.fits

2026-06-26 03:26:40 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14471_20260307_2124_20260308_1948/193/segment_01_20260307_2124_20260308_1948/aia.lev1_euv_12s.2026-03-08T034759Z.193.image.fits.1

2026-06-26 03:26:40 - drms - INFO: Downloading file 4 of 13...

2026-06-26 03:26:40 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-08T05:23:59Z][193][JSOC_20260625_002551]

2026-06-26 03:26:40 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-08T052359Z.193.image.fits

2026-06-26 03:26:41 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14471_20260307_2124_20260308_1948/193/segment_01_20260307_2124_20260308_1948/aia.lev1_euv_12s.2026-03-08T052359Z.193.image.fits.1

2026-06-26 03:26:41 - drms - INFO: Downloading file 5 of 13...

2026-06-26 03:26:41 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-08T06:59:59Z][193][JSOC_20260625_002551]

2026-06-26 03:26:41 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-08T065959Z.193.image.fits

2026-06-26 03:26:43 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14471_20260307_2124_20260308_1948/193/segment_01_20260307_2124_20260308_1948/aia.lev1_euv_12s.2026-03-08T065959Z.193.image.fits.1

2026-06-26 03:26:43 - drms - INFO: Downloading file 6 of 13...

2026-06-26 03:26:43 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-08T08:35:59Z][193][JSOC_20260625_002551]

2026-06-26 03:26:43 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-08T083559Z.193.image.fits

2026-06-26 03:26:45 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14471_20260307_2124_20260308_1948/193/segment_01_20260307_2124_20260308_1948/aia.lev1_euv_12s.2026-03-08T083559Z.193.image.fits.1

2026-06-26 03:26:45 - drms - INFO: Downloading file 7 of 13...

2026-06-26 03:26:45 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-08T10:11:59Z][193][JSOC_20260625_002551]

2026-06-26 03:26:45 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-08T101159Z.193.image.fits

2026-06-26 03:26:46 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14471_20260307_2124_20260308_1948/193/segment_01_20260307_2124_20260308_1948/aia.lev1_euv_12s.2026-03-08T101159Z.193.image.fits.1

2026-06-26 03:26:46 - drms - INFO: Downloading file 8 of 13...

2026-06-26 03:26:46 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-08T11:47:59Z][193][JSOC_20260625_002551]

2026-06-26 03:26:46 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-08T114759Z.193.image.fits

2026-06-26 03:26:48 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14471_20260307_2124_20260308_1948/193/segment_01_20260307_2124_20260308_1948/aia.lev1_euv_12s.2026-03-08T114759Z.193.image.fits.1

2026-06-26 03:26:48 - drms - INFO: Downloading file 9 of 13...

2026-06-26 03:26:48 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-08T13:23:59Z][193][JSOC_20260625_002551]

2026-06-26 03:26:48 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-08T132359Z.193.image.fits

2026-06-26 03:26:50 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14471_20260307_2124_20260308_1948/193/segment_01_20260307_2124_20260308_1948/aia.lev1_euv_12s.2026-03-08T132359Z.193.image.fits.1

2026-06-26 03:26:50 - drms - INFO: Downloading file 10 of 13...

2026-06-26 03:26:50 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-08T14:59:59Z][193][JSOC_20260625_002551]

2026-06-26 03:26:50 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-08T145959Z.193.image.fits

2026-06-26 03:26:51 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14471_20260307_2124_20260308_1948/193/segment_01_20260307_2124_20260308_1948/aia.lev1_euv_12s.2026-03-08T145959Z.193.image.fits.1

2026-06-26 03:26:51 - drms - INFO: Downloading file 11 of 13...

2026-06-26 03:26:51 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-08T16:35:59Z][193][JSOC_20260625_002551]

2026-06-26 03:26:51 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-08T163559Z.193.image.fits

2026-06-26 03:26:53 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14471_20260307_2124_20260308_1948/193/segment_01_20260307_2124_20260308_1948/aia.lev1_euv_12s.2026-03-08T163559Z.193.image.fits.1

2026-06-26 03:26:53 - drms - INFO: Downloading file 12 of 13...

2026-06-26 03:26:53 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-08T18:11:59Z][193][JSOC_20260625_002551]

2026-06-26 03:26:53 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-08T181159Z.193.image.fits

2026-06-26 03:26:55 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14471_20260307_2124_20260308_1948/193/segment_01_20260307_2124_20260308_1948/aia.lev1_euv_12s.2026-03-08T181159Z.193.image.fits.1

2026-06-26 03:26:55 - drms - INFO: Downloading file 13 of 13...

2026-06-26 03:26:55 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-08T19:47:59Z][193][JSOC_20260625_002551]

2026-06-26 03:26:55 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-08T194759Z.193.image.fits

2026-06-26 03:26:57 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14471_20260307_2124_20260308_1948/193/segment_01_20260307_2124_20260308_1948/aia.lev1_euv_12s.2026-03-08T194759Z.193.image.fits.1

BLOCK ERROR: RuntimeError('Downloaded 193 Å segment does not cover all target timestamps within 180 seconds.')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14471_20260307_2124_20260308_1948,error,15,None,0,None,RuntimeError('Downloaded 193 Å segment does no...

==========================================================================================
BLOCK 251/336 | 2026_HARP14448_20260307_2148_20260308_2012 | targets=15
==========================================================================================

----------------------------------------------------------------------
2026_HARP14448_20260307_2148_20260308_2012 | wavelength 94
94 Å cadence segments: 1 [('2026-03-07 21:48:00', '2026-03-08 20:12:00', 15)]
♻️ Segment 1/1 already covered by cached 94 Å files.

----------------------------------------------------------------------
2026_HARP14448_20260307_2148_20260308_2012 | wavelength 131
131 Å cadence segments: 1 [('2026-03-07 21:48:00', '2026-03-08 20:12:00', 15)]
♻️ Segment 1/1 already covered by cached 131 Å files.

----------------------------------------------------------------------
2026_HARP14448_20260307_2148_20260308_2012 | wavelength 171
171 Å cadence segments: 1 [('2026-03-07 21:48:00', '2026-03-08 20:12:00', 15)]
♻️ Segment 1/1 already covered by cached 171 Å files.

----------------------------------------------------------------------
2026_HARP14448_20260307_2148_20260308_2012 | wavelength 193
193 Å cadence segments: 1 [('2026-03-07 21:48:00', '2026-03-08 20:12:00', 15)]
Segment query: aia.lev1_euv_12s[2026-03-07T21:48:00.000/1440m@96m][193]{image}
Segment reference: 2026-03-08 09:00:00 | targets: 15 | patch arcsec: 1060.9991163685863
JSOC export attempt 1/10

2026-06-26 03:27:01 - drms - INFO: Export request pending. [id=JSOC_20260625_002640, status=2]

2026-06-26 03:27:01 - drms - INFO: Waiting for 15 seconds...

2026-06-26 03:27:17 - drms - INFO: Export request finished. [id=JSOC_20260625_002640, status=0]

2026-06-26 03:27:17 - drms - INFO: Downloading file 1 of 13...

2026-06-26 03:27:17 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-08T00:59:59Z][193][JSOC_20260625_002640]

2026-06-26 03:27:17 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-08T005959Z.193.image.fits

2026-06-26 03:27:21 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14448_20260307_2148_20260308_2012/193/segment_01_20260307_2148_20260308_2012/aia.lev1_euv_12s.2026-03-08T005959Z.193.image.fits.1

2026-06-26 03:27:21 - drms - INFO: Downloading file 2 of 13...

2026-06-26 03:27:21 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-08T02:35:59Z][193][JSOC_20260625_002640]

2026-06-26 03:27:21 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-08T023559Z.193.image.fits

2026-06-26 03:27:24 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14448_20260307_2148_20260308_2012/193/segment_01_20260307_2148_20260308_2012/aia.lev1_euv_12s.2026-03-08T023559Z.193.image.fits.1

2026-06-26 03:27:24 - drms - INFO: Downloading file 3 of 13...

2026-06-26 03:27:24 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-08T04:11:59Z][193][JSOC_20260625_002640]

2026-06-26 03:27:24 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-08T041159Z.193.image.fits

2026-06-26 03:27:28 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14448_20260307_2148_20260308_2012/193/segment_01_20260307_2148_20260308_2012/aia.lev1_euv_12s.2026-03-08T041159Z.193.image.fits.1

2026-06-26 03:27:28 - drms - INFO: Downloading file 4 of 13...

2026-06-26 03:27:28 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-08T05:47:59Z][193][JSOC_20260625_002640]

2026-06-26 03:27:28 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-08T054759Z.193.image.fits

2026-06-26 03:27:31 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14448_20260307_2148_20260308_2012/193/segment_01_20260307_2148_20260308_2012/aia.lev1_euv_12s.2026-03-08T054759Z.193.image.fits.1

2026-06-26 03:27:31 - drms - INFO: Downloading file 5 of 13...

2026-06-26 03:27:31 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-08T07:23:59Z][193][JSOC_20260625_002640]

2026-06-26 03:27:31 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-08T072359Z.193.image.fits

2026-06-26 03:27:34 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14448_20260307_2148_20260308_2012/193/segment_01_20260307_2148_20260308_2012/aia.lev1_euv_12s.2026-03-08T072359Z.193.image.fits.1

2026-06-26 03:27:34 - drms - INFO: Downloading file 6 of 13...

2026-06-26 03:27:34 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-08T08:59:59Z][193][JSOC_20260625_002640]

2026-06-26 03:27:34 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-08T085959Z.193.image.fits

2026-06-26 03:27:38 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14448_20260307_2148_20260308_2012/193/segment_01_20260307_2148_20260308_2012/aia.lev1_euv_12s.2026-03-08T085959Z.193.image.fits.1

2026-06-26 03:27:38 - drms - INFO: Downloading file 7 of 13...

2026-06-26 03:27:38 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-08T10:35:59Z][193][JSOC_20260625_002640]

2026-06-26 03:27:38 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-08T103559Z.193.image.fits

2026-06-26 03:27:41 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14448_20260307_2148_20260308_2012/193/segment_01_20260307_2148_20260308_2012/aia.lev1_euv_12s.2026-03-08T103559Z.193.image.fits.1

2026-06-26 03:27:41 - drms - INFO: Downloading file 8 of 13...

2026-06-26 03:27:41 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-08T12:11:59Z][193][JSOC_20260625_002640]

2026-06-26 03:27:41 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-08T121159Z.193.image.fits

2026-06-26 03:27:45 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14448_20260307_2148_20260308_2012/193/segment_01_20260307_2148_20260308_2012/aia.lev1_euv_12s.2026-03-08T121159Z.193.image.fits.1

2026-06-26 03:27:45 - drms - INFO: Downloading file 9 of 13...

2026-06-26 03:27:45 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-08T13:47:59Z][193][JSOC_20260625_002640]

2026-06-26 03:27:45 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-08T134759Z.193.image.fits

2026-06-26 03:27:49 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14448_20260307_2148_20260308_2012/193/segment_01_20260307_2148_20260308_2012/aia.lev1_euv_12s.2026-03-08T134759Z.193.image.fits.1

2026-06-26 03:27:49 - drms - INFO: Downloading file 10 of 13...

2026-06-26 03:27:49 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-08T15:23:59Z][193][JSOC_20260625_002640]

2026-06-26 03:27:49 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-08T152359Z.193.image.fits

2026-06-26 03:27:52 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14448_20260307_2148_20260308_2012/193/segment_01_20260307_2148_20260308_2012/aia.lev1_euv_12s.2026-03-08T152359Z.193.image.fits.1

2026-06-26 03:27:52 - drms - INFO: Downloading file 11 of 13...

2026-06-26 03:27:52 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-08T16:59:59Z][193][JSOC_20260625_002640]

2026-06-26 03:27:52 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-08T165959Z.193.image.fits

2026-06-26 03:27:56 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14448_20260307_2148_20260308_2012/193/segment_01_20260307_2148_20260308_2012/aia.lev1_euv_12s.2026-03-08T165959Z.193.image.fits.1

2026-06-26 03:27:56 - drms - INFO: Downloading file 12 of 13...

2026-06-26 03:27:56 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-08T18:35:59Z][193][JSOC_20260625_002640]

2026-06-26 03:27:56 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-08T183559Z.193.image.fits

2026-06-26 03:28:00 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14448_20260307_2148_20260308_2012/193/segment_01_20260307_2148_20260308_2012/aia.lev1_euv_12s.2026-03-08T183559Z.193.image.fits.1

2026-06-26 03:28:00 - drms - INFO: Downloading file 13 of 13...

2026-06-26 03:28:00 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-08T20:11:59Z][193][JSOC_20260625_002640]

2026-06-26 03:28:00 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-08T201159Z.193.image.fits

2026-06-26 03:28:03 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14448_20260307_2148_20260308_2012/193/segment_01_20260307_2148_20260308_2012/aia.lev1_euv_12s.2026-03-08T201159Z.193.image.fits.1

BLOCK ERROR: RuntimeError('Downloaded 193 Å segment does not cover all target timestamps within 180 seconds.')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14448_20260307_2148_20260308_2012,error,15,None,0,None,RuntimeError('Downloaded 193 Å segment does no...

==========================================================================================
BLOCK 252/336 | 2026_HARP14465_20260308_2100_20260309_0948 | targets=9
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14465_20260308_2100_20260309_0948,already_complete,9,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 253/336 | 2026_HARP14471_20260308_2124_20260309_1636 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14471_20260308_2124_20260309_1636,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 254/336 | 2026_HARP14448_20260308_2148_20260309_0724 | targets=7
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14448_20260308_2148_20260309_0724,already_complete,7,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 255/336 | 2026_HARP14471_20260309_1948_20260310_1636 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14471_20260309_1948_20260310_1636,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 256/336 | 2026_HARP14471_20260310_2012_20260310_2012 | targets=1
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14471_20260310_2012_20260310_2012,already_complete,1,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 257/336 | 2026_HARP14486_20260310_2136_20260311_2000 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14486_20260310_2136_20260311_2000,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 258/336 | 2026_HARP14486_20260311_2136_20260312_0048 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14486_20260311_2136_20260312_0048,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 259/336 | 2026_HARP14486_20260312_0400_20260313_0224 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14486_20260312_0400_20260313_0224,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 260/336 | 2026_HARP14479_20260312_1500_20260313_1324 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14479_20260312_1500_20260313_1324,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 261/336 | 2026_HARP14486_20260313_0400_20260314_0224 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14486_20260313_0400_20260314_0224,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 262/336 | 2026_HARP14479_20260313_1500_20260314_1324 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14479_20260313_1500_20260314_1324,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 263/336 | 2026_HARP14486_20260314_0400_20260315_0224 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14486_20260314_0400_20260315_0224,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 264/336 | 2026_HARP14479_20260314_1500_20260314_1636 | targets=2
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14479_20260314_1500_20260314_1636,already_complete,2,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 265/336 | 2026_HARP14479_20260314_1948_20260314_2300 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14479_20260314_1948_20260314_2300,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 266/336 | 2026_HARP14479_20260315_0212_20260316_0036 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14479_20260315_0212_20260316_0036,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 267/336 | 2026_HARP14486_20260315_0400_20260315_1024 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14486_20260315_0400_20260315_1024,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 268/336 | 2026_HARP14491_20260315_2136_20260316_2000 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14491_20260315_2136_20260316_2000,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 269/336 | 2026_HARP14479_20260316_0212_20260317_0036 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14479_20260316_0212_20260317_0036,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 270/336 | 2026_HARP14498_20260316_2036_20260317_1724 | targets=14
==========================================================================================

----------------------------------------------------------------------
2026_HARP14498_20260316_2036_20260317_1724 | wavelength 94
94 Å cadence segments: 1 [('2026-03-16 20:36:00', '2026-03-17 17:24:00', 14)]
Segment query: aia.lev1_euv_12s[2026-03-16T20:36:00.000/1344m@96m][94]{image}
Segment reference: 2026-03-17 07:00:00 | targets: 14 | patch arcsec: 381.6863401136711
JSOC export attempt 1/10

2026-06-26 03:28:43 - drms - INFO: Export request pending. [id=JSOC_20260625_004535, status=2]

2026-06-26 03:28:43 - drms - INFO: Waiting for 15 seconds...

2026-06-26 03:28:59 - drms - INFO: Export request finished. [id=JSOC_20260625_004535, status=0]

2026-06-26 03:28:59 - drms - INFO: Downloading file 1 of 13...

2026-06-26 03:28:59 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-16T20:35:59Z][94][JSOC_20260625_004535]

2026-06-26 03:28:59 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-16T203559Z.94.image.fits

2026-06-26 03:29:00 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14498_20260316_2036_20260317_1724/94/segment_01_20260316_2036_20260317_1724/aia.lev1_euv_12s.2026-03-16T203559Z.94.image.fits.1

2026-06-26 03:29:00 - drms - INFO: Downloading file 2 of 13...

2026-06-26 03:29:00 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-16T22:11:59Z][94][JSOC_20260625_004535]

2026-06-26 03:29:00 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-16T221159Z.94.image.fits

2026-06-26 03:29:02 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14498_20260316_2036_20260317_1724/94/segment_01_20260316_2036_20260317_1724/aia.lev1_euv_12s.2026-03-16T221159Z.94.image.fits.1

2026-06-26 03:29:02 - drms - INFO: Downloading file 3 of 13...

2026-06-26 03:29:02 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-16T23:47:59Z][94][JSOC_20260625_004535]

2026-06-26 03:29:02 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-16T234759Z.94.image.fits

2026-06-26 03:29:03 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14498_20260316_2036_20260317_1724/94/segment_01_20260316_2036_20260317_1724/aia.lev1_euv_12s.2026-03-16T234759Z.94.image.fits.1

2026-06-26 03:29:03 - drms - INFO: Downloading file 4 of 13...

2026-06-26 03:29:03 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-17T01:23:59Z][94][JSOC_20260625_004535]

2026-06-26 03:29:03 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-17T012359Z.94.image.fits

2026-06-26 03:29:05 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14498_20260316_2036_20260317_1724/94/segment_01_20260316_2036_20260317_1724/aia.lev1_euv_12s.2026-03-17T012359Z.94.image.fits.1

2026-06-26 03:29:05 - drms - INFO: Downloading file 5 of 13...

2026-06-26 03:29:05 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-17T02:59:59Z][94][JSOC_20260625_004535]

2026-06-26 03:29:05 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-17T025959Z.94.image.fits

2026-06-26 03:29:07 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14498_20260316_2036_20260317_1724/94/segment_01_20260316_2036_20260317_1724/aia.lev1_euv_12s.2026-03-17T025959Z.94.image.fits.1

2026-06-26 03:29:07 - drms - INFO: Downloading file 6 of 13...

2026-06-26 03:29:07 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-17T04:35:59Z][94][JSOC_20260625_004535]

2026-06-26 03:29:07 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-17T043559Z.94.image.fits

2026-06-26 03:29:08 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14498_20260316_2036_20260317_1724/94/segment_01_20260316_2036_20260317_1724/aia.lev1_euv_12s.2026-03-17T043559Z.94.image.fits.1

2026-06-26 03:29:08 - drms - INFO: Downloading file 7 of 13...

2026-06-26 03:29:08 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-17T06:11:59Z][94][JSOC_20260625_004535]

2026-06-26 03:29:08 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-17T061159Z.94.image.fits

2026-06-26 03:29:10 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14498_20260316_2036_20260317_1724/94/segment_01_20260316_2036_20260317_1724/aia.lev1_euv_12s.2026-03-17T061159Z.94.image.fits.1

2026-06-26 03:29:10 - drms - INFO: Downloading file 8 of 13...

2026-06-26 03:29:10 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-17T07:47:59Z][94][JSOC_20260625_004535]

2026-06-26 03:29:10 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-17T074759Z.94.image.fits

2026-06-26 03:29:11 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14498_20260316_2036_20260317_1724/94/segment_01_20260316_2036_20260317_1724/aia.lev1_euv_12s.2026-03-17T074759Z.94.image.fits.1

2026-06-26 03:29:11 - drms - INFO: Downloading file 9 of 13...

2026-06-26 03:29:11 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-17T09:23:59Z][94][JSOC_20260625_004535]

2026-06-26 03:29:11 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-17T092359Z.94.image.fits

2026-06-26 03:29:13 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14498_20260316_2036_20260317_1724/94/segment_01_20260316_2036_20260317_1724/aia.lev1_euv_12s.2026-03-17T092359Z.94.image.fits.1

2026-06-26 03:29:13 - drms - INFO: Downloading file 10 of 13...

2026-06-26 03:29:13 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-17T10:59:59Z][94][JSOC_20260625_004535]

2026-06-26 03:29:13 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-17T105959Z.94.image.fits

2026-06-26 03:29:14 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14498_20260316_2036_20260317_1724/94/segment_01_20260316_2036_20260317_1724/aia.lev1_euv_12s.2026-03-17T105959Z.94.image.fits.1

2026-06-26 03:29:14 - drms - INFO: Downloading file 11 of 13...

2026-06-26 03:29:14 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-17T12:35:59Z][94][JSOC_20260625_004535]

2026-06-26 03:29:14 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-17T123559Z.94.image.fits

2026-06-26 03:29:16 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14498_20260316_2036_20260317_1724/94/segment_01_20260316_2036_20260317_1724/aia.lev1_euv_12s.2026-03-17T123559Z.94.image.fits.1

2026-06-26 03:29:16 - drms - INFO: Downloading file 12 of 13...

2026-06-26 03:29:16 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-17T14:11:59Z][94][JSOC_20260625_004535]

2026-06-26 03:29:16 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-17T141159Z.94.image.fits

2026-06-26 03:29:18 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14498_20260316_2036_20260317_1724/94/segment_01_20260316_2036_20260317_1724/aia.lev1_euv_12s.2026-03-17T141159Z.94.image.fits.1

2026-06-26 03:29:18 - drms - INFO: Downloading file 13 of 13...

2026-06-26 03:29:18 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-17T17:23:59Z][94][JSOC_20260625_004535]

2026-06-26 03:29:18 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-17T172359Z.94.image.fits

2026-06-26 03:29:19 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14498_20260316_2036_20260317_1724/94/segment_01_20260316_2036_20260317_1724/aia.lev1_euv_12s.2026-03-17T172359Z.94.image.fits.1

BLOCK ERROR: RuntimeError('Downloaded 94 Å segment does not cover all target timestamps within 180 seconds.')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14498_20260316_2036_20260317_1724,error,14,None,0,None,RuntimeError('Downloaded 94 Å segment does not...

==========================================================================================
BLOCK 271/336 | 2026_HARP14491_20260316_2136_20260317_2012 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14491_20260316_2136_20260317_2012,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 272/336 | 2026_HARP14479_20260317_0212_20260317_0348 | targets=2
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14479_20260317_0212_20260317_0348,already_complete,2,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 273/336 | 2026_HARP14498_20260317_2048_20260318_2036 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14498_20260317_2048_20260318_2036,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 274/336 | 2026_HARP14499_20260317_2136_20260318_0848 | targets=8
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14499_20260317_2136_20260318_0848,already_complete,8,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 275/336 | 2026_HARP14491_20260317_2148_20260318_0900 | targets=8
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14491_20260317_2148_20260318_0900,already_complete,8,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 276/336 | 2026_HARP14499_20260318_1200_20260318_2300 | targets=7
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14499_20260318_1200_20260318_2300,already_complete,7,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 277/336 | 2026_HARP14491_20260318_1212_20260318_2312 | targets=7
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14491_20260318_1212_20260318_2312,already_complete,7,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 278/336 | 2026_HARP14498_20260318_2212_20260318_2348 | targets=2
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14498_20260318_2212_20260318_2348,already_complete,2,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 279/336 | 2026_HARP14498_20260319_1512_20260320_1336 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14498_20260319_1512_20260320_1336,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 280/336 | 2026_HARP14499_20260319_1600_20260320_1548 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14499_20260319_1600_20260320_1548,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 281/336 | 2026_HARP14491_20260319_1612_20260320_0812 | targets=11
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14491_20260319_1612_20260320_0812,already_complete,11,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 282/336 | 2026_HARP14514_20260320_0348_20260320_1324 | targets=7
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14514_20260320_0348_20260320_1324,already_complete,7,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 283/336 | 2026_HARP14498_20260320_1512_20260321_0536 | targets=10
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14498_20260320_1512_20260321_0536,already_complete,10,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 284/336 | 2026_HARP14514_20260320_1636_20260321_1500 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14514_20260320_1636_20260321_1500,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 285/336 | 2026_HARP14507_20260321_0100_20260321_2324 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14507_20260321_0100_20260321_2324,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 286/336 | 2026_HARP14514_20260321_1636_20260322_1500 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14514_20260321_1636_20260322_1500,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 287/336 | 2026_HARP14513_20260321_1824_20260322_1648 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14513_20260321_1824_20260322_1648,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 288/336 | 2026_HARP14506_20260321_2148_20260322_2012 | targets=15
==========================================================================================

----------------------------------------------------------------------
2026_HARP14506_20260321_2148_20260322_2012 | wavelength 94
94 Å cadence segments: 1 [('2026-03-21 21:48:00', '2026-03-22 20:12:00', 15)]
♻️ Segment 1/1 already covered by cached 94 Å files.

----------------------------------------------------------------------
2026_HARP14506_20260321_2148_20260322_2012 | wavelength 131
131 Å cadence segments: 1 [('2026-03-21 21:48:00', '2026-03-22 20:12:00', 15)]
♻️ Segment 1/1 already covered by cached 131 Å files.

----------------------------------------------------------------------
2026_HARP14506_20260321_2148_20260322_2012 | wavelength 171
171 Å cadence segments: 1 [('2026-03-21 21:48:00', '2026-03-22 20:12:00', 15)]
♻️ Segment 1/1 already covered by cached 171 Å files.

----------------------------------------------------------------------
2026_HARP14506_20260321_2148_20260322_2012 | wavelength 193
193 Å cadence segments: 1 [('2026-03-21 21:48:00', '2026-03-22 20:12:00', 15)]
♻️ Segment 1/1 already covered by cached 193 Å files.

----------------------------------------------------------------------
2026_HARP14506_20260321_2148_20260322_2012 | wavelength 211
211 Å cadence segments: 1 [('2026-03-21 21:48:00', '2026-03-22 20:12:00', 15)]
Segment query: aia.lev1_euv_12s[2026-03-21T21:48:00.000/1440m@96m][211]{image}
Segment reference: 2026-03-22 09:00:00 | targets: 15 | patch arcsec: 411.7992833606065
JSOC export attempt 1/10

2026-06-26 03:30:01 - drms - INFO: Export request pending. [id=JSOC_20260625_006654, status=2]

2026-06-26 03:30:01 - drms - INFO: Waiting for 15 seconds...

2026-06-26 03:30:16 - drms - INFO: Export request finished. [id=JSOC_20260625_006654, status=0]

2026-06-26 03:30:16 - drms - INFO: Downloading file 1 of 14...

2026-06-26 03:30:16 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-21T21:47:59Z][211][JSOC_20260625_006654]

2026-06-26 03:30:16 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-21T214759Z.211.image.fits

2026-06-26 03:30:18 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14506_20260321_2148_20260322_2012/211/segment_01_20260321_2148_20260322_2012/aia.lev1_euv_12s.2026-03-21T214759Z.211.image.fits.1

2026-06-26 03:30:18 - drms - INFO: Downloading file 2 of 14...

2026-06-26 03:30:18 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-21T23:23:59Z][211][JSOC_20260625_006654]

2026-06-26 03:30:18 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-21T232359Z.211.image.fits

2026-06-26 03:30:20 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14506_20260321_2148_20260322_2012/211/segment_01_20260321_2148_20260322_2012/aia.lev1_euv_12s.2026-03-21T232359Z.211.image.fits.1

2026-06-26 03:30:20 - drms - INFO: Downloading file 3 of 14...

2026-06-26 03:30:20 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-22T00:59:59Z][211][JSOC_20260625_006654]

2026-06-26 03:30:20 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-22T005959Z.211.image.fits

2026-06-26 03:30:21 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14506_20260321_2148_20260322_2012/211/segment_01_20260321_2148_20260322_2012/aia.lev1_euv_12s.2026-03-22T005959Z.211.image.fits.1

2026-06-26 03:30:21 - drms - INFO: Downloading file 4 of 14...

2026-06-26 03:30:21 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-22T02:35:59Z][211][JSOC_20260625_006654]

2026-06-26 03:30:21 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-22T023559Z.211.image.fits

2026-06-26 03:30:23 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14506_20260321_2148_20260322_2012/211/segment_01_20260321_2148_20260322_2012/aia.lev1_euv_12s.2026-03-22T023559Z.211.image.fits.1

2026-06-26 03:30:23 - drms - INFO: Downloading file 5 of 14...

2026-06-26 03:30:23 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-22T04:11:59Z][211][JSOC_20260625_006654]

2026-06-26 03:30:23 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-22T041159Z.211.image.fits

2026-06-26 03:30:24 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14506_20260321_2148_20260322_2012/211/segment_01_20260321_2148_20260322_2012/aia.lev1_euv_12s.2026-03-22T041159Z.211.image.fits.1

2026-06-26 03:30:24 - drms - INFO: Downloading file 6 of 14...

2026-06-26 03:30:24 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-22T05:47:59Z][211][JSOC_20260625_006654]

2026-06-26 03:30:24 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-22T054759Z.211.image.fits

2026-06-26 03:30:26 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14506_20260321_2148_20260322_2012/211/segment_01_20260321_2148_20260322_2012/aia.lev1_euv_12s.2026-03-22T054759Z.211.image.fits.1

2026-06-26 03:30:26 - drms - INFO: Downloading file 7 of 14...

2026-06-26 03:30:26 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-22T07:23:59Z][211][JSOC_20260625_006654]

2026-06-26 03:30:26 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-22T072359Z.211.image.fits

2026-06-26 03:30:28 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14506_20260321_2148_20260322_2012/211/segment_01_20260321_2148_20260322_2012/aia.lev1_euv_12s.2026-03-22T072359Z.211.image.fits.1

2026-06-26 03:30:28 - drms - INFO: Downloading file 8 of 14...

2026-06-26 03:30:28 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-22T08:59:59Z][211][JSOC_20260625_006654]

2026-06-26 03:30:28 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-22T085959Z.211.image.fits

2026-06-26 03:30:29 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14506_20260321_2148_20260322_2012/211/segment_01_20260321_2148_20260322_2012/aia.lev1_euv_12s.2026-03-22T085959Z.211.image.fits.1

2026-06-26 03:30:29 - drms - INFO: Downloading file 9 of 14...

2026-06-26 03:30:29 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-22T10:35:59Z][211][JSOC_20260625_006654]

2026-06-26 03:30:29 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-22T103559Z.211.image.fits

2026-06-26 03:30:31 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14506_20260321_2148_20260322_2012/211/segment_01_20260321_2148_20260322_2012/aia.lev1_euv_12s.2026-03-22T103559Z.211.image.fits.1

2026-06-26 03:30:31 - drms - INFO: Downloading file 10 of 14...

2026-06-26 03:30:31 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-22T12:11:59Z][211][JSOC_20260625_006654]

2026-06-26 03:30:31 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-22T121159Z.211.image.fits

2026-06-26 03:30:33 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14506_20260321_2148_20260322_2012/211/segment_01_20260321_2148_20260322_2012/aia.lev1_euv_12s.2026-03-22T121159Z.211.image.fits.1

2026-06-26 03:30:33 - drms - INFO: Downloading file 11 of 14...

2026-06-26 03:30:33 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-22T15:23:59Z][211][JSOC_20260625_006654]

2026-06-26 03:30:33 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-22T152359Z.211.image.fits

2026-06-26 03:30:34 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14506_20260321_2148_20260322_2012/211/segment_01_20260321_2148_20260322_2012/aia.lev1_euv_12s.2026-03-22T152359Z.211.image.fits.1

2026-06-26 03:30:34 - drms - INFO: Downloading file 12 of 14...

2026-06-26 03:30:34 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-22T16:59:59Z][211][JSOC_20260625_006654]

2026-06-26 03:30:34 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-22T165959Z.211.image.fits

2026-06-26 03:30:36 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14506_20260321_2148_20260322_2012/211/segment_01_20260321_2148_20260322_2012/aia.lev1_euv_12s.2026-03-22T165959Z.211.image.fits.1

2026-06-26 03:30:36 - drms - INFO: Downloading file 13 of 14...

2026-06-26 03:30:36 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-22T18:35:59Z][211][JSOC_20260625_006654]

2026-06-26 03:30:36 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-22T183559Z.211.image.fits

2026-06-26 03:30:38 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14506_20260321_2148_20260322_2012/211/segment_01_20260321_2148_20260322_2012/aia.lev1_euv_12s.2026-03-22T183559Z.211.image.fits.1

2026-06-26 03:30:38 - drms - INFO: Downloading file 14 of 14...

2026-06-26 03:30:38 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-22T20:11:59Z][211][JSOC_20260625_006654]

2026-06-26 03:30:38 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-22T201159Z.211.image.fits

2026-06-26 03:30:39 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14506_20260321_2148_20260322_2012/211/segment_01_20260321_2148_20260322_2012/aia.lev1_euv_12s.2026-03-22T201159Z.211.image.fits.1

BLOCK ERROR: RuntimeError('Downloaded 211 Å segment does not cover all target timestamps within 180 seconds.')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14506_20260321_2148_20260322_2012,error,15,None,0,None,RuntimeError('Downloaded 211 Å segment does no...

==========================================================================================
BLOCK 289/336 | 2026_HARP14507_20260322_0100_20260322_2324 | targets=15
==========================================================================================

----------------------------------------------------------------------
2026_HARP14507_20260322_0100_20260322_2324 | wavelength 94
94 Å cadence segments: 1 [('2026-03-22 01:00:00', '2026-03-22 23:24:00', 15)]
♻️ Segment 1/1 already covered by cached 94 Å files.

----------------------------------------------------------------------
2026_HARP14507_20260322_0100_20260322_2324 | wavelength 131
131 Å cadence segments: 1 [('2026-03-22 01:00:00', '2026-03-22 23:24:00', 15)]
♻️ Segment 1/1 already covered by cached 131 Å files.

----------------------------------------------------------------------
2026_HARP14507_20260322_0100_20260322_2324 | wavelength 171
171 Å cadence segments: 1 [('2026-03-22 01:00:00', '2026-03-22 23:24:00', 15)]
♻️ Segment 1/1 already covered by cached 171 Å files.

----------------------------------------------------------------------
2026_HARP14507_20260322_0100_20260322_2324 | wavelength 193
193 Å cadence segments: 1 [('2026-03-22 01:00:00', '2026-03-22 23:24:00', 15)]
♻️ Segment 1/1 already covered by cached 193 Å files.

----------------------------------------------------------------------
2026_HARP14507_20260322_0100_20260322_2324 | wavelength 211
211 Å cadence segments: 1 [('2026-03-22 01:00:00', '2026-03-22 23:24:00', 15)]
Segment query: aia.lev1_euv_12s[2026-03-22T01:00:00.000/1440m@96m][211]{image}
Segment reference: 2026-03-22 12:12:00 | targets: 15 | patch arcsec: 433.09493590191687
JSOC export attempt 1/10

2026-06-26 03:30:44 - drms - INFO: Export request pending. [id=JSOC_20260625_006761, status=2]

2026-06-26 03:30:44 - drms - INFO: Waiting for 15 seconds...

2026-06-26 03:31:00 - drms - INFO: Export request finished. [id=JSOC_20260625_006761, status=0]

2026-06-26 03:31:00 - drms - INFO: Downloading file 1 of 14...

2026-06-26 03:31:00 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-22T00:59:59Z][211][JSOC_20260625_006761]

2026-06-26 03:31:00 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-22T005959Z.211.image.fits

2026-06-26 03:31:02 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14507_20260322_0100_20260322_2324/211/segment_01_20260322_0100_20260322_2324/aia.lev1_euv_12s.2026-03-22T005959Z.211.image.fits.1

2026-06-26 03:31:02 - drms - INFO: Downloading file 2 of 14...

2026-06-26 03:31:02 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-22T02:35:59Z][211][JSOC_20260625_006761]

2026-06-26 03:31:02 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-22T023559Z.211.image.fits

2026-06-26 03:31:03 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14507_20260322_0100_20260322_2324/211/segment_01_20260322_0100_20260322_2324/aia.lev1_euv_12s.2026-03-22T023559Z.211.image.fits.1

2026-06-26 03:31:03 - drms - INFO: Downloading file 3 of 14...

2026-06-26 03:31:03 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-22T04:11:59Z][211][JSOC_20260625_006761]

2026-06-26 03:31:03 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-22T041159Z.211.image.fits

2026-06-26 03:31:05 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14507_20260322_0100_20260322_2324/211/segment_01_20260322_0100_20260322_2324/aia.lev1_euv_12s.2026-03-22T041159Z.211.image.fits.1

2026-06-26 03:31:05 - drms - INFO: Downloading file 4 of 14...

2026-06-26 03:31:05 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-22T05:47:59Z][211][JSOC_20260625_006761]

2026-06-26 03:31:05 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-22T054759Z.211.image.fits

2026-06-26 03:31:07 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14507_20260322_0100_20260322_2324/211/segment_01_20260322_0100_20260322_2324/aia.lev1_euv_12s.2026-03-22T054759Z.211.image.fits.1

2026-06-26 03:31:07 - drms - INFO: Downloading file 5 of 14...

2026-06-26 03:31:07 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-22T07:23:59Z][211][JSOC_20260625_006761]

2026-06-26 03:31:07 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-22T072359Z.211.image.fits

2026-06-26 03:31:08 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14507_20260322_0100_20260322_2324/211/segment_01_20260322_0100_20260322_2324/aia.lev1_euv_12s.2026-03-22T072359Z.211.image.fits.1

2026-06-26 03:31:08 - drms - INFO: Downloading file 6 of 14...

2026-06-26 03:31:08 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-22T08:59:59Z][211][JSOC_20260625_006761]

2026-06-26 03:31:08 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-22T085959Z.211.image.fits

2026-06-26 03:31:10 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14507_20260322_0100_20260322_2324/211/segment_01_20260322_0100_20260322_2324/aia.lev1_euv_12s.2026-03-22T085959Z.211.image.fits.1

2026-06-26 03:31:10 - drms - INFO: Downloading file 7 of 14...

2026-06-26 03:31:10 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-22T10:35:59Z][211][JSOC_20260625_006761]

2026-06-26 03:31:10 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-22T103559Z.211.image.fits

2026-06-26 03:31:12 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14507_20260322_0100_20260322_2324/211/segment_01_20260322_0100_20260322_2324/aia.lev1_euv_12s.2026-03-22T103559Z.211.image.fits.1

2026-06-26 03:31:12 - drms - INFO: Downloading file 8 of 14...

2026-06-26 03:31:12 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-22T12:11:59Z][211][JSOC_20260625_006761]

2026-06-26 03:31:12 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-22T121159Z.211.image.fits

2026-06-26 03:31:13 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14507_20260322_0100_20260322_2324/211/segment_01_20260322_0100_20260322_2324/aia.lev1_euv_12s.2026-03-22T121159Z.211.image.fits.1

2026-06-26 03:31:13 - drms - INFO: Downloading file 9 of 14...

2026-06-26 03:31:13 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-22T15:23:59Z][211][JSOC_20260625_006761]

2026-06-26 03:31:13 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-22T152359Z.211.image.fits

2026-06-26 03:31:15 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14507_20260322_0100_20260322_2324/211/segment_01_20260322_0100_20260322_2324/aia.lev1_euv_12s.2026-03-22T152359Z.211.image.fits.1

2026-06-26 03:31:15 - drms - INFO: Downloading file 10 of 14...

2026-06-26 03:31:15 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-22T16:59:59Z][211][JSOC_20260625_006761]

2026-06-26 03:31:15 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-22T165959Z.211.image.fits

2026-06-26 03:31:17 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14507_20260322_0100_20260322_2324/211/segment_01_20260322_0100_20260322_2324/aia.lev1_euv_12s.2026-03-22T165959Z.211.image.fits.1

2026-06-26 03:31:17 - drms - INFO: Downloading file 11 of 14...

2026-06-26 03:31:17 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-22T18:35:59Z][211][JSOC_20260625_006761]

2026-06-26 03:31:17 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-22T183559Z.211.image.fits

2026-06-26 03:31:19 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14507_20260322_0100_20260322_2324/211/segment_01_20260322_0100_20260322_2324/aia.lev1_euv_12s.2026-03-22T183559Z.211.image.fits.1

2026-06-26 03:31:19 - drms - INFO: Downloading file 12 of 14...

2026-06-26 03:31:19 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-22T20:11:59Z][211][JSOC_20260625_006761]

2026-06-26 03:31:19 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-22T201159Z.211.image.fits

2026-06-26 03:31:20 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14507_20260322_0100_20260322_2324/211/segment_01_20260322_0100_20260322_2324/aia.lev1_euv_12s.2026-03-22T201159Z.211.image.fits.1

2026-06-26 03:31:20 - drms - INFO: Downloading file 13 of 14...

2026-06-26 03:31:20 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-22T21:47:59Z][211][JSOC_20260625_006761]

2026-06-26 03:31:20 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-22T214759Z.211.image.fits

2026-06-26 03:31:22 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14507_20260322_0100_20260322_2324/211/segment_01_20260322_0100_20260322_2324/aia.lev1_euv_12s.2026-03-22T214759Z.211.image.fits.1

2026-06-26 03:31:22 - drms - INFO: Downloading file 14 of 14...

2026-06-26 03:31:22 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-22T23:23:59Z][211][JSOC_20260625_006761]

2026-06-26 03:31:22 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-22T232359Z.211.image.fits

2026-06-26 03:31:25 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14507_20260322_0100_20260322_2324/211/segment_01_20260322_0100_20260322_2324/aia.lev1_euv_12s.2026-03-22T232359Z.211.image.fits.1

BLOCK ERROR: RuntimeError('Downloaded 211 Å segment does not cover all target timestamps within 180 seconds.')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14507_20260322_0100_20260322_2324,error,15,None,0,None,RuntimeError('Downloaded 211 Å segment does no...

==========================================================================================
BLOCK 290/336 | 2026_HARP14514_20260322_1636_20260323_0836 | targets=11
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14514_20260322_1636_20260323_0836,already_complete,11,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 291/336 | 2026_HARP14513_20260322_1824_20260323_1648 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14513_20260322_1824_20260323_1648,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 292/336 | 2026_HARP14506_20260322_2148_20260323_2012 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14506_20260322_2148_20260323_2012,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 293/336 | 2026_HARP14507_20260323_0100_20260323_2324 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14507_20260323_0100_20260323_2324,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 294/336 | 2026_HARP14513_20260323_1824_20260324_0400 | targets=7
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14513_20260323_1824_20260324_0400,already_complete,7,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 295/336 | 2026_HARP14506_20260323_2148_20260324_2024 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14506_20260323_2148_20260324_2024,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 296/336 | 2026_HARP14507_20260324_0100_20260324_2336 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14507_20260324_0100_20260324_2336,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 297/336 | 2026_HARP14513_20260324_0712_20260325_0548 | targets=15
==========================================================================================

----------------------------------------------------------------------
2026_HARP14513_20260324_0712_20260325_0548 | wavelength 94
94 Å cadence segments: 2 [('2026-03-24 07:12:00', '2026-03-24 16:48:00', 7), ('2026-03-24 18:36:00', '2026-03-25 05:48:00', 8)]
♻️ Segment 1/2 already covered by cached 94 Å files.

Segment query: aia.lev1_euv_12s[2026-03-24T18:36:00.000/768m@96m][94]{image}
Segment reference: 2026-03-25 00:12:00 | targets: 8 | patch arcsec: 434.01836489571104
JSOC export attempt 1/10

2026-06-26 03:31:42 - drms - INFO: Export request pending. [id=JSOC_20260625_007610, status=2]

2026-06-26 03:31:42 - drms - INFO: Waiting for 15 seconds...

2026-06-26 03:31:58 - drms - INFO: Export request finished. [id=JSOC_20260625_007610, status=0]

2026-06-26 03:31:58 - drms - INFO: Downloading file 1 of 7...

2026-06-26 03:31:58 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-24T18:35:59Z][94][JSOC_20260625_007610]

2026-06-26 03:31:58 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-24T183559Z.94.image.fits

2026-06-26 03:32:00 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14513_20260324_0712_20260325_0548/94/segment_02_20260324_1836_20260325_0548/aia.lev1_euv_12s.2026-03-24T183559Z.94.image.fits.1

2026-06-26 03:32:00 - drms - INFO: Downloading file 2 of 7...

2026-06-26 03:32:00 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-24T21:47:59Z][94][JSOC_20260625_007610]

2026-06-26 03:32:00 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-24T214759Z.94.image.fits

2026-06-26 03:32:02 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14513_20260324_0712_20260325_0548/94/segment_02_20260324_1836_20260325_0548/aia.lev1_euv_12s.2026-03-24T214759Z.94.image.fits.1

2026-06-26 03:32:02 - drms - INFO: Downloading file 3 of 7...

2026-06-26 03:32:02 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-24T23:23:59Z][94][JSOC_20260625_007610]

2026-06-26 03:32:02 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-24T232359Z.94.image.fits

2026-06-26 03:32:04 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14513_20260324_0712_20260325_0548/94/segment_02_20260324_1836_20260325_0548/aia.lev1_euv_12s.2026-03-24T232359Z.94.image.fits.1

2026-06-26 03:32:04 - drms - INFO: Downloading file 4 of 7...

2026-06-26 03:32:04 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-25T00:59:59Z][94][JSOC_20260625_007610]

2026-06-26 03:32:04 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-25T005959Z.94.image.fits

2026-06-26 03:32:07 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14513_20260324_0712_20260325_0548/94/segment_02_20260324_1836_20260325_0548/aia.lev1_euv_12s.2026-03-25T005959Z.94.image.fits.1

2026-06-26 03:32:07 - drms - INFO: Downloading file 5 of 7...

2026-06-26 03:32:07 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-25T02:35:59Z][94][JSOC_20260625_007610]

2026-06-26 03:32:07 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-25T023559Z.94.image.fits

2026-06-26 03:32:09 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14513_20260324_0712_20260325_0548/94/segment_02_20260324_1836_20260325_0548/aia.lev1_euv_12s.2026-03-25T023559Z.94.image.fits.1

2026-06-26 03:32:09 - drms - INFO: Downloading file 6 of 7...

2026-06-26 03:32:09 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-25T04:11:59Z][94][JSOC_20260625_007610]

2026-06-26 03:32:09 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-25T041159Z.94.image.fits

2026-06-26 03:32:11 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14513_20260324_0712_20260325_0548/94/segment_02_20260324_1836_20260325_0548/aia.lev1_euv_12s.2026-03-25T041159Z.94.image.fits.1

2026-06-26 03:32:11 - drms - INFO: Downloading file 7 of 7...

2026-06-26 03:32:11 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-25T05:47:59Z][94][JSOC_20260625_007610]

2026-06-26 03:32:11 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-25T054759Z.94.image.fits

2026-06-26 03:32:13 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14513_20260324_0712_20260325_0548/94/segment_02_20260324_1836_20260325_0548/aia.lev1_euv_12s.2026-03-25T054759Z.94.image.fits.1

BLOCK ERROR: RuntimeError('Downloaded 94 Å segment does not cover all target timestamps within 180 seconds.')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14513_20260324_0712_20260325_0548,error,15,None,0,None,RuntimeError('Downloaded 94 Å segment does not...

==========================================================================================
BLOCK 298/336 | 2026_HARP14506_20260324_2200_20260325_0424 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14506_20260324_2200_20260325_0424,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 299/336 | 2026_HARP14507_20260325_0112_20260325_0424 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14507_20260325_0112_20260325_0424,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 300/336 | 2026_HARP14513_20260325_0724_20260326_0624 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14513_20260325_0724_20260326_0624,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 301/336 | 2026_HARP14506_20260325_0736_20260326_0636 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14506_20260325_0736_20260326_0636,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 302/336 | 2026_HARP14507_20260325_0736_20260325_1400 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14507_20260325_0736_20260325_1400,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 303/336 | 2026_HARP14520_20260325_2112_20260326_1624 | targets=13
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14520_20260325_2112_20260326_1624,already_complete,13,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 304/336 | 2026_HARP14519_20260325_2200_20260326_0424 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14519_20260325_2200_20260326_0424,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 305/336 | 2026_HARP14519_20260326_0736_20260327_0424 | targets=14
==========================================================================================

----------------------------------------------------------------------
2026_HARP14519_20260326_0736_20260327_0424 | wavelength 94
94 Å cadence segments: 1 [('2026-03-26 07:36:00', '2026-03-27 04:24:00', 14)]
Segment query: aia.lev1_euv_12s[2026-03-26T07:36:00.000/1344m@96m][94]{image}
Segment reference: 2026-03-26 18:00:00 | targets: 14 | patch arcsec: 402.6869049157133
JSOC export attempt 1/10

2026-06-26 03:32:31 - drms - INFO: Export request pending. [id=JSOC_20260625_007986, status=2]

2026-06-26 03:32:31 - drms - INFO: Waiting for 15 seconds...

2026-06-26 03:32:46 - drms - INFO: Export request finished. [id=JSOC_20260625_007986, status=0]

2026-06-26 03:32:46 - drms - INFO: Downloading file 1 of 1...

2026-06-26 03:32:46 - drms - INFO:     record: warning=No FITS files were exported. The requested FITS files no longer exist.

2026-06-26 03:32:46 - drms - INFO:     filename:

2026-06-26 03:32:47 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14519_20260326_0736_20260327_0424/94/segment_01_20260326_0736_20260327_0424.2

BLOCK ERROR: FileNotFoundError('No FITS files downloaded for 94 Å segment.')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14519_20260326_0736_20260327_0424,error,14,None,0,None,FileNotFoundError('No FITS files downloaded fo...

==========================================================================================
BLOCK 306/336 | 2026_HARP14513_20260326_0800_20260326_0800 | targets=1
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14513_20260326_0800_20260326_0800,already_complete,1,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 307/336 | 2026_HARP14506_20260326_0812_20260326_0812 | targets=1
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14506_20260326_0812_20260326_0812,already_complete,1,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 308/336 | 2026_HARP14520_20260326_1936_20260327_1624 | targets=14
==========================================================================================

----------------------------------------------------------------------
2026_HARP14520_20260326_1936_20260327_1624 | wavelength 94
94 Å cadence segments: 1 [('2026-03-26 19:36:00', '2026-03-27 16:24:00', 14)]

Segment query: aia.lev1_euv_12s[2026-03-26T19:36:00.000/1344m@96m][94]{image}
Segment reference: 2026-03-27 06:00:00 | targets: 14 | patch arcsec: 706.7997032649299
JSOC export attempt 1/10

2026-06-26 03:32:55 - drms - INFO: Export request pending. [id=JSOC_20260625_008054, status=2]

2026-06-26 03:32:55 - drms - INFO: Waiting for 15 seconds...

2026-06-26 03:33:11 - drms - INFO: Export request finished. [id=JSOC_20260625_008054, status=0]

2026-06-26 03:33:11 - drms - INFO: Downloading file 1 of 13...

2026-06-26 03:33:11 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-26T21:11:59Z][94][JSOC_20260625_008054]

2026-06-26 03:33:11 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-26T211159Z.94.image.fits

2026-06-26 03:33:14 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14520_20260326_1936_20260327_1624/94/segment_01_20260326_1936_20260327_1624/aia.lev1_euv_12s.2026-03-26T211159Z.94.image.fits.1

2026-06-26 03:33:14 - drms - INFO: Downloading file 2 of 13...

2026-06-26 03:33:14 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-26T22:47:59Z][94][JSOC_20260625_008054]

2026-06-26 03:33:14 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-26T224759Z.94.image.fits

2026-06-26 03:33:18 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14520_20260326_1936_20260327_1624/94/segment_01_20260326_1936_20260327_1624/aia.lev1_euv_12s.2026-03-26T224759Z.94.image.fits.1

2026-06-26 03:33:18 - drms - INFO: Downloading file 3 of 13...

2026-06-26 03:33:18 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-27T00:23:59Z][94][JSOC_20260625_008054]

2026-06-26 03:33:18 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-27T002359Z.94.image.fits

2026-06-26 03:33:21 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14520_20260326_1936_20260327_1624/94/segment_01_20260326_1936_20260327_1624/aia.lev1_euv_12s.2026-03-27T002359Z.94.image.fits.1

2026-06-26 03:33:21 - drms - INFO: Downloading file 4 of 13...

2026-06-26 03:33:21 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-27T01:59:59Z][94][JSOC_20260625_008054]

2026-06-26 03:33:21 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-27T015959Z.94.image.fits

2026-06-26 03:33:24 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14520_20260326_1936_20260327_1624/94/segment_01_20260326_1936_20260327_1624/aia.lev1_euv_12s.2026-03-27T015959Z.94.image.fits.1

2026-06-26 03:33:24 - drms - INFO: Downloading file 5 of 13...

2026-06-26 03:33:24 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-27T03:35:59Z][94][JSOC_20260625_008054]

2026-06-26 03:33:24 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-27T033559Z.94.image.fits

2026-06-26 03:33:27 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14520_20260326_1936_20260327_1624/94/segment_01_20260326_1936_20260327_1624/aia.lev1_euv_12s.2026-03-27T033559Z.94.image.fits.1

2026-06-26 03:33:27 - drms - INFO: Downloading file 6 of 13...

2026-06-26 03:33:27 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-27T05:11:59Z][94][JSOC_20260625_008054]

2026-06-26 03:33:27 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-27T051159Z.94.image.fits

2026-06-26 03:33:31 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14520_20260326_1936_20260327_1624/94/segment_01_20260326_1936_20260327_1624/aia.lev1_euv_12s.2026-03-27T051159Z.94.image.fits.1

2026-06-26 03:33:31 - drms - INFO: Downloading file 7 of 13...

2026-06-26 03:33:31 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-27T06:47:59Z][94][JSOC_20260625_008054]

2026-06-26 03:33:31 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-27T064759Z.94.image.fits

2026-06-26 03:33:34 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14520_20260326_1936_20260327_1624/94/segment_01_20260326_1936_20260327_1624/aia.lev1_euv_12s.2026-03-27T064759Z.94.image.fits.1

2026-06-26 03:33:34 - drms - INFO: Downloading file 8 of 13...

2026-06-26 03:33:34 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-27T08:23:59Z][94][JSOC_20260625_008054]

2026-06-26 03:33:34 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-27T082359Z.94.image.fits

2026-06-26 03:33:37 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14520_20260326_1936_20260327_1624/94/segment_01_20260326_1936_20260327_1624/aia.lev1_euv_12s.2026-03-27T082359Z.94.image.fits.1

2026-06-26 03:33:37 - drms - INFO: Downloading file 9 of 13...

2026-06-26 03:33:37 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-27T09:59:59Z][94][JSOC_20260625_008054]

2026-06-26 03:33:37 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-27T095959Z.94.image.fits

2026-06-26 03:33:40 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14520_20260326_1936_20260327_1624/94/segment_01_20260326_1936_20260327_1624/aia.lev1_euv_12s.2026-03-27T095959Z.94.image.fits.1

2026-06-26 03:33:40 - drms - INFO: Downloading file 10 of 13...

2026-06-26 03:33:40 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-27T11:35:59Z][94][JSOC_20260625_008054]

2026-06-26 03:33:40 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-27T113559Z.94.image.fits

2026-06-26 03:33:43 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14520_20260326_1936_20260327_1624/94/segment_01_20260326_1936_20260327_1624/aia.lev1_euv_12s.2026-03-27T113559Z.94.image.fits.1

2026-06-26 03:33:43 - drms - INFO: Downloading file 11 of 13...

2026-06-26 03:33:43 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-27T13:11:59Z][94][JSOC_20260625_008054]

2026-06-26 03:33:43 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-27T131159Z.94.image.fits

2026-06-26 03:33:47 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14520_20260326_1936_20260327_1624/94/segment_01_20260326_1936_20260327_1624/aia.lev1_euv_12s.2026-03-27T131159Z.94.image.fits.1

2026-06-26 03:33:47 - drms - INFO: Downloading file 12 of 13...

2026-06-26 03:33:47 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-27T14:47:59Z][94][JSOC_20260625_008054]

2026-06-26 03:33:47 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-27T144759Z.94.image.fits

2026-06-26 03:33:50 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14520_20260326_1936_20260327_1624/94/segment_01_20260326_1936_20260327_1624/aia.lev1_euv_12s.2026-03-27T144759Z.94.image.fits.1

2026-06-26 03:33:50 - drms - INFO: Downloading file 13 of 13...

2026-06-26 03:33:50 - drms - INFO:     record: aia.lev1_euv_12s_mod[2026-03-27T16:23:59Z][94][JSOC_20260625_008054]

2026-06-26 03:33:50 - drms - INFO:     filename: aia.lev1_euv_12s.2026-03-27T162359Z.94.image.fits

2026-06-26 03:33:53 - drms - INFO:     -> ../harp_block_miner/production_aia2026/temp_blocks/2026_HARP14520_20260326_1936_20260327_1624/94/segment_01_20260326_1936_20260327_1624/aia.lev1_euv_12s.2026-03-27T162359Z.94.image.fits.1

BLOCK ERROR: RuntimeError('Downloaded 94 Å segment does not cover all target timestamps within 180 seconds.')

,block_id,status,n_targets,n_pending_at_start,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14520_20260326_1936_20260327_1624,error,14,None,0,None,RuntimeError('Downloaded 94 Å segment does not...

==========================================================================================
BLOCK 309/336 | 2026_HARP14519_20260327_0736_20260327_1848 | targets=8
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14519_20260327_0736_20260327_1848,already_complete,8,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 310/336 | 2026_HARP14520_20260327_1936_20260328_0024 | targets=4
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14520_20260327_1936_20260328_0024,already_complete,4,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 311/336 | 2026_HARP14519_20260327_2200_20260327_2336 | targets=2
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14519_20260327_2200_20260327_2336,already_complete,2,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 312/336 | 2026_HARP14519_20260328_0436_20260329_0300 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14519_20260328_0436_20260329_0300,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 313/336 | 2026_HARP14520_20260328_0524_20260329_0348 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14520_20260328_0524_20260329_0348,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 314/336 | 2026_HARP14530_20260328_1248_20260329_1112 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14530_20260328_1248_20260329_1112,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 315/336 | 2026_HARP14519_20260329_0436_20260330_0300 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14519_20260329_0436_20260330_0300,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 316/336 | 2026_HARP14520_20260329_0524_20260330_0348 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14520_20260329_0524_20260330_0348,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 317/336 | 2026_HARP14530_20260329_1248_20260330_1112 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14530_20260329_1248_20260330_1112,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 318/336 | 2026_HARP14519_20260330_0436_20260330_1100 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14519_20260330_0436_20260330_1100,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 319/336 | 2026_HARP14520_20260330_0524_20260330_1148 | targets=5
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14520_20260330_0524_20260330_1148,already_complete,5,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 320/336 | 2026_HARP14530_20260330_1248_20260331_1112 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14530_20260330_1248_20260331_1112,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 321/336 | 2026_HARP14536_20260330_2124_20260331_1948 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14536_20260330_2124_20260331_1948,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 322/336 | 2026_HARP14535_20260331_0012_20260331_2236 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14535_20260331_0012_20260331_2236,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 323/336 | 2026_HARP14530_20260331_1248_20260331_1736 | targets=4
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14530_20260331_1248_20260331_1736,already_complete,4,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 324/336 | 2026_HARP14530_20260331_2048_20260401_1924 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14530_20260331_2048_20260401_1924,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 325/336 | 2026_HARP14536_20260331_2124_20260401_2000 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14536_20260331_2124_20260401_2000,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 326/336 | 2026_HARP14535_20260401_0012_20260401_2248 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14535_20260401_0012_20260401_2248,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 327/336 | 2026_HARP14530_20260401_2100_20260402_0012 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14530_20260401_2100_20260402_0012,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 328/336 | 2026_HARP14536_20260401_2136_20260402_2000 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14536_20260401_2136_20260402_2000,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 329/336 | 2026_HARP14551_20260401_2136_20260402_2000 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14551_20260401_2136_20260402_2000,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 330/336 | 2026_HARP14535_20260402_0024_20260402_1624 | targets=11
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14535_20260402_0024_20260402_1624,already_complete,11,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 331/336 | 2026_HARP14535_20260402_1936_20260403_1624 | targets=14
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14535_20260402_1936_20260403_1624,already_complete,14,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 332/336 | 2026_HARP14536_20260402_2136_20260403_2000 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14536_20260402_2136_20260403_2000,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 333/336 | 2026_HARP14551_20260402_2136_20260403_2000 | targets=15
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14551_20260402_2136_20260403_2000,already_complete,15,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 334/336 | 2026_HARP14535_20260403_1936_20260403_2248 | targets=3
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14535_20260403_1936_20260403_2248,already_complete,3,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 335/336 | 2026_HARP14536_20260403_2136_20260403_2312 | targets=2
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14536_20260403_2136_20260403_2312,already_complete,2,0,0.0,all_samples_already_in_gcp

==========================================================================================
BLOCK 336/336 | 2026_HARP14551_20260403_2136_20260403_2312 | targets=2
==========================================================================================

,block_id,status,n_targets,n_saved_this_run,elapsed_minutes,message
0,2026_HARP14551_20260403_2136_20260403_2312,already_complete,2,0,0.0,all_samples_already_in_gcp

Run finished.
Completed model-ready objects now visible in GCP: 2939

## 10. Audit expected versus completed

In [13]:

fresh_listing = run_command(
    ["gcloud", "storage", "ls", "--recursive", GCP_OUTPUT_ROOT],
    check=False,
)
actual_ids = {
    Path(line.strip()).stem
    for line in fresh_listing.stdout.splitlines()
    if line.strip().endswith(".npz")
}

expected_ids = set(df["sample_id"].astype(str))

if RUN_MODE == "BLOCK_CANARY":
    selected_block_ids = set(block_plan["block_id"])
    expected_ids = set(
        pd.concat(
            [block_frames[item] for item in selected_block_ids],
            ignore_index=True,
        )["sample_id"].astype(str)
    )

missing_ids = expected_ids - actual_ids
unexpected_ids = actual_ids - set(df["sample_id"].astype(str))

print("Expected in this run scope:", len(expected_ids))
print("Completed in GCP:", len(actual_ids.intersection(expected_ids)))
print("Missing:", len(missing_ids))
print("Unexpected:", len(unexpected_ids))

audit = pd.DataFrame(
    {
        "metric": [
            "expected_scope",
            "completed_scope",
            "missing_scope",
            "unexpected_year_objects",
        ],
        "value": [
            len(expected_ids),
            len(actual_ids.intersection(expected_ids)),
            len(missing_ids),
            len(unexpected_ids),
        ],
    }
)
display(audit)

missing_path = LOCAL_META / f"missing_ids_{WORKER_ID}.txt"
missing_path.write_text("\n".join(sorted(missing_ids)))
run_command(
    [
        "gcloud", "storage", "cp",
        str(missing_path),
        f"{GCP_WORKER_META}/{missing_path.name}",
    ],
    check=True,
)

Expected in this run scope: 3201
Completed in GCP: 2939
Missing: 262
Unexpected: 0

                    metric  value
0           expected_scope   3201
1          completed_scope   2939
2            missing_scope    262
3  unexpected_year_objects      0

CompletedProcess(args=['gcloud', 'storage', 'cp', '/home/abmoses2000/solar_flare_aia/harp_block_miner/production_aia2026/metadata/missing_ids_aia2026.txt', 'gs://suryabench-sharp-pipeline-bamidele/jsoc_2025_2026_production_v1/metadata/workers/aia2026/missing_ids_aia2026.txt'], returncode=0, stdout='', stderr='Copying file:///home/abmoses2000/solar_flare_aia/harp_block_miner/production_aia2026/metadata/missing_ids_aia2026.txt to gs://suryabench-sharp-pipeline-bamidele/jsoc_2025_2026_production_v1/metadata/workers/aia2026/missing_ids_aia2026.txt\n  \n.\n')

## 11. Block-canary comparison with individual pilot outputs

In [14]:

if RUN_MODE != "BLOCK_CANARY":
    print("Comparison is only used in BLOCK_CANARY mode.")
else:
    comparison_root = LOCAL_ROOT / "comparison"
    comparison_root.mkdir(parents=True, exist_ok=True)

    comparison_rows = []

    for sample_id in CANARY_SAMPLE_IDS[TARGET_YEAR]:
        block_path = comparison_root / f"block_{sample_id}.npz"
        pilot_path = comparison_root / f"pilot_{sample_id}.npz"

        block_gcp = f"{GCP_OUTPUT_ROOT}/{sample_id}.npz"
        pilot_gcp = f"{PILOT_GCP_ROOT}/{sample_id}.npz"

        if not gcp_exists(block_gcp) or not gcp_exists(pilot_gcp):
            print("Comparison unavailable:", sample_id)
            continue

        run_command(
            ["gcloud", "storage", "cp", block_gcp, str(block_path)]
        )
        run_command(
            ["gcloud", "storage", "cp", pilot_gcp, str(pilot_path)]
        )

        with np.load(block_path, allow_pickle=True) as block_npz:
            block_x = block_npz["x"]
        with np.load(pilot_path, allow_pickle=True) as pilot_npz:
            pilot_x = pilot_npz["x"]

        for channel_index, wavelength in enumerate(AIA_WAVELENGTHS):
            first = block_x[:, :, channel_index]
            second = pilot_x[:, :, channel_index]

            correlation = float(
                np.corrcoef(first.ravel(), second.ravel())[0, 1]
            )
            ssim = float(
                structural_similarity(
                    first,
                    second,
                    data_range=1.0,
                )
            )

            comparison_rows.append(
                {
                    "sample_id": sample_id,
                    "wavelength": wavelength,
                    "pearson_r": correlation,
                    "ssim": ssim,
                }
            )

        fig, axes = plt.subplots(2, 6, figsize=(18, 6))
        for channel_index, wavelength in enumerate(AIA_WAVELENGTHS):
            axes[0, channel_index].imshow(
                pilot_x[:, :, channel_index],
                origin="lower",
                cmap="gray",
            )
            axes[0, channel_index].set_title(f"Pilot {wavelength} Å")
            axes[0, channel_index].axis("off")

            axes[1, channel_index].imshow(
                block_x[:, :, channel_index],
                origin="lower",
                cmap="gray",
            )
            axes[1, channel_index].set_title(f"Block {wavelength} Å")
            axes[1, channel_index].axis("off")

        fig.suptitle(sample_id)
        plt.tight_layout()
        plt.show()

    comparison_df = pd.DataFrame(comparison_rows)
    display(comparison_df)

    if len(comparison_df):
        print("\nMean correlation:", comparison_df["pearson_r"].mean())
        print("Mean SSIM:", comparison_df["ssim"].mean())

        comparison_path = (
            LOCAL_META / f"block_vs_pilot_{WORKER_ID}.csv"
        )
        comparison_df.to_csv(comparison_path, index=False)
        run_command(
            [
                "gcloud", "storage", "cp",
                str(comparison_path),
                f"{GCP_WORKER_META}/{comparison_path.name}",
            ],
            check=True,
        )

Comparison is only used in BLOCK_CANARY mode.


## 12. Acceptance gate

Before switching to `PRODUCTION`, confirm:

1. all target timestamps in the selected block are represented;
2. six AIA channels exist for every saved sample;
3. output shape is `(512, 512, 6)`;
4. all values are finite and within `[0, 1]`;
5. AIA-to-SHARP time differences are no more than 180 seconds;
6. active regions are centred and not clipped;
7. block-generated images visually match the individual pilot images;
8. correlation and SSIM are scientifically acceptable;
9. no unexpected sample IDs are present;
10. block runtime is materially faster than the former 7–8 minutes per sample.

## Starting production on the VM

Once the block canary passes, place the notebook in:

```text
~/solar_flare_aia/notebooks/
```

Then run the 2025 worker:

```bash
tmux new -s aia2025
source ~/solar_flare_aia/venv/bin/activate
export TARGET_YEAR=2025
export JSOC_EMAIL=abmoses2000@gmail.com
export WORKER_ID=aia2025
export RUN_MODE=PRODUCTION
jupyter nbconvert \
  --to notebook \
  --execute ~/solar_flare_aia/notebooks/05_AIA_JSOC_HARP_BLOCK_MINER_VM_READY.ipynb \
  --ExecutePreprocessor.timeout=-1 \
  --output ~/solar_flare_aia/logs/aia2025_executed.ipynb
```

Detach from `tmux` with `Ctrl+B`, then `D`.

A second worker can process 2026 using `worky4work@gmail.com`, but first verify that two simultaneous block workers do not overload the VM or JSOC.